### ISSUE TITLE
Xournal++ 1.0.20 does not work on M1-Mac (macOS 11.2.3)

### ISSUE THREAD

**Issue by chris-mair** [xournalpp/xournalpp#2942] opened 2021-03-13 15:13 UTC
**Affects versions :**

 - macOS 11.2.3

 - Which version of libgtk do you use

```
% /Applications/Xournal++.app/Contents/MacOS/xournalpp --version     
2021-03-13 16:03:16.728 defaults[2817:217076] 
The domain/default pair of (.GlobalPreferences, AppleCollationOrder) does not exist

(com.github.xournalpp.xournalpp:2812): Gtk-WARNING **: 16:03:16.894: Locale not supported by C library.
	Using the fallback 'C' locale.
Xournal++ 1.0.20 
└──libgtk: 3.24.10 
** Message: 16:03:16.895: MemoryLeak: sum 0 objects.
```

 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]

Github Release Xournal++ 1.0.20 -> xournalpp-1.0.20-macos.zip

 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

official release

**Describe the bug**

Xournal++ crashes at startup

**To Reproduce**

Launch Xournal++ either via GUI->Open or via Terminal as /Applications/Xournal++.app/Contents/MacOS/xournalpp

**Expected behavior**

Xournal++ should not crash at startup

**Screenshots of Problem**

see logs

**Additional context**

stderr output and crashlog

```
2021-03-13 15:54:44.840 defaults[2768:214511] 
The domain/default pair of (.GlobalPreferences, AppleCollationOrder) does not exist

(com.github.xournalpp.xournalpp:2763): Gtk-WARNING **: 15:54:45.006: Locale not supported by C library.
	Using the fallback 'C' locale.

** (com.github.xournalpp.xournalpp:2763): WARNING **: 15:54:45.080: Failed to load "colornames.ini" (/Users/REDACTED/.xournalpp//colornames.ini): No such file or directory


** (com.github.xournalpp.xournalpp:2763): WARNING **: 15:54:45.122: configfile does not exist /Users/REDACTED/.xournalpp/settings.xml


** (com.github.xournalpp.xournalpp:2763): WARNING **: 15:54:45.448: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!


(com.github.xournalpp.xournalpp:2763): GLib-GObject-WARNING **: 15:54:45.466: g_object_get_is_valid_property: object class 'GtkLabel' has no property named 'accel-closure'

(com.github.xournalpp.xournalpp:2763): Gtk-WARNING **: 15:54:45.653: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node marks owner GtkScale)

(com.github.xournalpp.xournalpp:2763): Gtk-WARNING **: 15:54:45.653: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(com.github.xournalpp.xournalpp:2763): Gtk-WARNING **: 15:54:45.653: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(com.github.xournalpp.xournalpp:2763): Gtk-WARNING **: 15:54:45.653: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(com.github.xournalpp.xournalpp:2763): Gtk-WARNING **: 15:54:45.653: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

** (com.github.xournalpp.xournalpp:2763): WARNING **: 15:54:45.702: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:2763): WARNING **: 15:54:45.702: [Crash Handler] Wrote crash log to: /Users/REDACTED/.xournalpp/errorlogs/errorlog.20210313-155445.log
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found
sh: addr2line: command not found

** (com.github.xournalpp.xournalpp:2763): WARNING **: 15:54:45.733: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:2763): WARNING **: 15:54:45.733: Successfully saved document to "/Users/REDACTED/.xournalpp//emergencysave.xopp"
```

```
Date: Sat Mar 13 15:54:45 2021
Error: signal 11
[bt]: (0) 0   xournalpp-bin                       0x0000000102ea4974 _ZL12crashHandleri + 84
[bt]: (1) 1   libsystem_platform.dylib            0x00007fff203c6d7d _sigtramp + 29
[bt]: (2) 2   ???                                 0xaaaaaaaaaaaaaaaa 0x0 + 12297829382473034410
[bt]: (3) 3   ???                                 0x434f4e4400000001 0x0 + 4850181377666056193


Try to get a better stracktrace...
[bt] #1 1   xournalpp-bin                       0x0000000102ea4fda _ZL12crashHandleri + 1722
[bt] #2 2   libsystem_platform.dylib            0x00007fff203c6d7d _sigtramp + 29
[bt] #3 3   ???                                 0xaaaaaaaaaaaaaaaa 0x0 + 12297829382473034410
[bt] #4 4   ???                                 0x434f4e4400000001 0x0 + 4850181377666056193
```

**Comment by rolandlo** [comment] 2021-03-14 19:04
Looks like a duplicate of #2823 and #2836.

**Comment by chris-mair** [comment] 2021-03-15 17:37
> Looks like a duplicate of #2823 and #2836.

OK, so #2823 looks like the person managed to compile the development version via homebrew and had it working.

#2836 was an Intel Mac, maybe macOS Version is the problem then...

I looked around and so others reporting crashes of 1.0.20 on Mac specifically. I'll try to see what happens with 1.0.19 or a nightly build and report back.

-- Chris

**Comment by chris-mair** [comment] 2021-03-16 20:51
> I looked around and so others reporting crashes of 1.0.20 on Mac specifically. I'll try to see what happens with 1.0.19 or a nightly build and report back.

Ok, so it turns out 1.0.19 works fine!

Something that was added in 1.0.20 seems to have broken something at least on this Mac.

-- Chris.

**Comment by rolandlo** [comment] 2021-04-01 12:38
@chris-mair Please try again with the nightly build that is relased tonight. On an Intel Mac it works now at least (both on Catalina and BigSur)

**Closed** 2021-04-22 10:36 UTC
Labels: bug, os::mac
