### ISSUE TITLE
Ctrl and Shift modifiers not working for ellipse and rectangle tools when using a tablet

### ISSUE THREAD

**Issue by 12jgy** [xournalpp/xournalpp#3294] opened 2021-07-31 17:05 UTC
**Affects versions :**
 - OS: Windows 10 (build 2004)
 - Version of libgtk: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: Official release

**Describe the bug**
Shift and Ctrl modifiers for both the rectangle and ellipse tools, which should respectively make perfect circles/squares and draw from center, don't affect what's being drawn in any way. The bug only occurs when using my Huion tablet as the input method.

**To Reproduce**
1. Select the rectangle/ellipse tool
2. Press ctrl or shift
3. Try drawing a shape

**Expected behavior**
Depending on the modifier and tool being used, a perfect square/circle or a figure drawn from the center should be drawn

**Additional context**
The modifiers works as expected when using the mouse to draw the shapes.
The bug stills occurs on the lasted nightly build (as of 31st of July), and didn't occur on version 1.0.20.
Model of the tablet: Huion HS64.

**Comment by Technius** [comment] 2021-08-01 03:51
Is this with or without the hotfix?

**Comment by 12jgy** [comment] 2021-08-01 22:49
With the hotfix.

**Comment by Technius** [comment] 2021-08-02 18:45
Does this bug occur on the non-hotfix version? I can't reproduce this on Linux so it must be some sort of GTK issue.

**Comment by 12jgy** [comment] 2021-08-03 10:40
I tested it now and it works just fine on the non-hotfix version.

**Comment by NelkonParker** [comment] 2021-08-04 07:34
I can confirm that this seems to be a bug present in the 1.1.0 hotfix on Windows 10.

**Comment by VidalDuval** [comment] 2022-01-26 19:41
With 1.1.0-hotfix, I also get this bug on Windows 10 using a Wacom One tablet (and with a Wacom Intuos S as well). Downgrading to the non-hotfix version solved the problem.

**Comment by rolandlo** [comment] 2022-01-26 19:43
Does it also occur with the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? It may have been fixed in Gtk 3.24.31 (which is currently in use for the nightly release).

**Comment by VidalDuval** [comment] 2022-01-26 20:00
The bug does not occur in the nightly release using Gtk 3.24.31. The ctrl and shift modifiers are now working as expected.

**Closed** 2022-05-20 08:05 UTC
Labels: bug, os::windows, Input, regression
