### ISSUE TITLE
Error 135 in Acrobat Reader form PDF export

### ISSUE THREAD

**Issue by mAxGarak** [xournalpp/xournalpp#2636] opened 2021-01-08 08:49 UTC
**Affects versions :**
 - OS:  Windows 10
 - Version of Xournal++: 1.0.20+

**Describe the bug**
Tested on several Windows 10 computers : some files that where correctly exported to `.pdf` from releases 1.0.18 and 1.0.19 generate an error 135 in Acrobat Reader DC 2020.013.20074 when exported from 1.0.20 (and 1.1+ nightly build tested too).

Example files :
[test libe.zip](https://github.com/xournalpp/xournalpp/files/5786104/test.libe.zip) : original `xopp` file
[test libe 19.pdf](https://github.com/xournalpp/xournalpp/files/5786110/test.libe.19.pdf) : 1.0.19 export, OK in Acroread
[test libe 20.pdf](https://github.com/xournalpp/xournalpp/files/5786109/test.libe.20.pdf) : 1.0.20 export, error 135 in Acroread

**Comment by rolandlo** [comment] 2021-01-08 09:18
Duplicate of #2601. This is due to a bug in Cairo.

**Closed by rolandlo** 2021-01-08 09:18 UTC
Labels: bug
