### ISSUE TITLE
Cannot use drop-down menus with touchscreen

### ISSUE THREAD

**Issue by sanette** [xournalpp/xournalpp#2635] opened 2021-01-08 08:44 UTC
**Affects versions :**
 - OS: Linux Ubuntu 20.04
 - X11
 - libgtk 3.24.20
 - Version of Xournal++:
 - 1.1.0+dev, current commit:
https://github.com/xournalpp/xournalpp/commit/94d93c9cf7bb75a58d7eab1b6f9a94e6b1a0cd07
 - Manual build

**Describe the bug**
I have an XPS 13 with touchscreen, I can use the touchscreen to draw, and select things on the __toolbar__, but I cannot use the __drop-down menus__. If I press on a menu, it opens, and I can even _highlight_ entries, but I cannot _select_ any on them.
Weird: when I close the menu, I can see that my finger motions actually produced drawing beneath the menu!

**To Reproduce**
1. Press on the File menu with a finger, it opens
2. Try to select "Open" for instance. Impossible

**Expected behavior**
Menus should be usable with touchscreen

**Comment by rolandlo** [comment] 2021-01-08 09:30
Does that happen in older versions, too? What are the settings you use? I can't reproduce the problem.

**Comment by sanette** [comment] 2021-01-08 10:15
I have the same issue with
`http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu focal/main amd64 xournalpp amd64 1.0.6+dev~202101072106~ubuntu20.04.`

My Elan Touchscreen is set up in the Entry System to 'Pen',
but if I set it to 'Mouse' or 'Touchscreen' I have the same problem
(except that for 'Touchscreen' it doesn't draw under the menu, of course)

**Comment by sanette** [comment] 2021-01-08 10:20
I deleted `.config/xournalpp` and `.config/com.github.xournalpp.xournalpp` but the problem persists

**Comment by sanette** [comment] 2021-01-08 10:29
Here is a video where I use only my finger.
I have to press several times on several menu entries in the top bar before the menu opens, and then I try to select things, but nothing happens. When I press outside the menu closes and one can see the drawing under the menu.

https://user-images.githubusercontent.com/7536536/104004870-93bc2700-51a4-11eb-810d-bd9aa72e3ffc.mp4

**Comment by sanette** [comment] 2021-01-08 10:33
of course I should mention that in my other GTK apps like emacs, thunderbird, firefox, I can use drop-down menus correctly with the touchscreen

**Comment by sanette** [comment] 2021-01-08 11:00
it looks pretty much the same as https://gitlab.gnome.org/GNOME/gtk/-/issues/945
so that would be a GTK issue, but then I don't understand why it works with other GTK apps.
(I even tested Xournal (not pp), it works)

**Comment by rolandlo** [comment] 2021-01-08 12:24
Xournal is based on GTK2, not GTK3, see https://sourceforge.net/p/xournal/bugs/191/

**Comment by sanette** [comment] 2021-01-08 12:46
thanks for the interesting link.
Well, at least my emacs is GTK3 based, it says "GTK+ Version 3.24.14"

**Comment by personalizedrefrigerator** [comment] 2021-01-08 12:49
I can confirm this on Plasma (X11 and Wayland), except, for me, the menus sometimes work (attempting to open one -> attempting to open another -> attempting to open the first menu opens the first menu).

**Comment by sanette** [comment] 2021-01-08 12:52
@personalizedrefrigerator , when you say "the menus sometimes work" do you mean you can _open_ the menu, or that you can also then _select_ an entry?
(I have the same behavior as you concerning opening: first try another, and then re-try the first... But in any case I am never able to activate an entry in a open menu)

**Comment by sanette** [comment] 2021-01-08 12:53
Ah, in Wayland I can activate entries. But not in X11

**Comment by personalizedrefrigerator** [comment] 2021-01-09 08:37
Interesting... I can activate entries under X11, but sometimes need to tap multiple times (libgtk 3.24.23). I am running KDE Neon, with Plasma 5.20.5 and KWin 5.20.5. This could be a Plasma issue...

**Comment by sanette** [comment] 2021-01-09 17:28
even if this is related to plasma, this is weird that I didn't have this issue with other GTK apps

**Comment by sanette** [comment] 2021-01-10 12:22
I think Inkscape also uses GTK3, and I have no issue with it.
I can try to investigate, but does anyone have a clue where to start looking?

**Comment by sanette** [comment] 2021-01-10 21:39
seems to be same as https://github.com/xournalpp/xournalpp/issues/1364

**Comment by personalizedrefrigerator** [comment] 2021-01-18 21:39
I'm having this issue with LibreOffice Writer on KDE Plasma -- I am able to open menus, but not activate menu items with touch.

**Comment by sanette** [comment] 2021-01-19 08:29
> I'm having this issue with LibreOffice Writer on KDE Plasma

I don't, but my version says it's using vcl: kf5, so it's probably made for KDE.

**Comment by sanette** [comment] 2021-01-19 09:09
I also tested Inkscape 1.0, which apparently is now using GTK3 https://inkscape.org/news/2020/05/04/introducing-inkscape-10/
and it does work

**Comment by compilebunny** [comment] 2021-09-12 11:54
@sanette

This is a known problem. As sanette mentioned, it is described here: https://gitlab.gnome.org/GNOME/gtk/-/issues/945

It is also described in two other places:
https://bugzilla.gnome.org/show_bug.cgi?id=789041
https://bugs.launchpad.net/ubuntu-mate/+bug/1792787

A gnome contributor named niteshgupta16 contributed an unofficial fix here: https://www.hastebin.com/uwuviteyeb.py
but the service that it was uploaded to deleted it. Hastebin is a javascript-obfuscated service, so the file is not on archive.org. I am unable to find an email address for niteshgupta16 to ask if he still has the file.

**Comment by gvcallen** [comment] 2021-10-05 08:37
I am running the same setup as OP, i.e.:
- Ubuntu 20.04
- Xournal++ 1.1.0 (official release though, not a manual build)
- libgtk 3.24.20

And menus do not work as expected within touchscreen for me.

I opened up GIMP, and menus DO work as expected, indicating this is most likely a Xournal issue. I'm not sure if GIMP might be using a newer version of gtk though which supposedly fixeds this problem (although I doubt it).

Any updates on this issue?

**Comment by LittleHuba** [comment] 2021-10-17 16:14
In regards to our involvement, I'll close this issue as even Windows releases ship GTK 3.24.30 by now. Linux distributions may ship GTK versions that still exhibit this error but we can't do anything about this. Take it up with the maintainers of the Distribution if it bothers you.

**Closed by LittleHuba** 2021-10-17 16:14 UTC
Labels: bug
