### ISSUE TITLE
dark mode don't work on windows 10

### ISSUE THREAD

**Issue by Daddie2** [xournalpp/xournalpp#3730] opened 2022-01-19 16:22 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows] windows
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch] 1.1.0
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

**Describe the bug**

**To Reproduce**
1. Step 1 install stable version 
2. Step 2  enable dark theme
![Immagine2](https://user-images.githubusercontent.com/50950554/150171885-8a76a37f-32b2-4d63-9a8c-0ff73eb0268e.png)

3. etc.

**Expected behavior**
dark mode don't work even if i enable it for all the app 
**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment] 2022-01-21 07:43
At least with the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) (which uses Gtk `3.24.31`) it works for me on Windows 10. Just don't forget to restart Xournal++ after enabling "Dark theme" in the Xournal++ settings (as you did).

Here is how it should look (in fullscreen mode):
![grafik](https://user-images.githubusercontent.com/40485433/150486302-77cb483d-4de1-430a-8f27-860790e980c9.png)

**Comment by rolandlo** [comment] 2022-01-22 15:09
It was confirmed in #3735 that upgrading to the latest nightly release fixes the problem. So I'm closing the issue.

**Closed by rolandlo** 2022-01-22 15:09 UTC
Labels: bug
