### ISSUE TITLE
[Feature Request] Update underlying PDF file

### ISSUE THREAD

**Issue by vinieich** [xournalpp/xournalpp#1588] opened 2019-11-04 20:43 UTC
I have a PDF that have one of my classes topics and my professor changes it after every class.

Sometimes he updates it with 50+ pages and I use this pdf on Xournalpp but the problem is that the only way to add the new pages is manually selecting one by one.

I've tried to delete the PDF and then selecting the new one as the background (using the xournalpp dialog that complains for the missing pdf after opening the file) but the page count is still the same.

PS:
I put the [Feature Request] tag because I honestly searched everywhere that I could but couldn't find how to do this. If there is some way to do this then I apologize.
English is not my primary language so maybe the text is a little confuse. I can try to reformulate if necessary.

**Comment by LittleHuba** [comment] 2019-11-05 00:30
This is actually a duplicate of #889. Stil thanks for reporting this.

I'm not quite sure it is worth adding this functionality before moving to the new rendering system. It is quite a huge modification and we would have to do it twice...

For now you might want to open the new pdf in another instance of Xournal++ and just move all the annotations via copy&paste if it is not too much hassle.

**Closed by LittleHuba** 2019-11-05 00:30 UTC
