### ISSUE TITLE
Multiple Individual Select / Group Selections

### ISSUE THREAD

**Issue by jason-v-w** [xournalpp/xournalpp#1838] opened 2020-04-06 01:49 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use the select object function with the ctrl or shift key (as is common with other programs) to be able to select multiple objects. For example, I may want to change the color of 7 items in the document all to red.

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
Currently, I have to select the first object, then apply a new color, then select the next object, etc.

**Additional context**
It seems that the ability to have multiple objects selected would not be an issue since using the select region tool allows for multiple items to be simultaneously selected.

**Comment by theanshm** [comment] 2020-10-01 07:24
I would like to give this issue a shot. I am new to contributing to open source (might ask some dumb questions) but willing to learn.

**Comment by Dettorer** [comment] 2020-12-28 22:17
I think I'll have a go at this, but just to be sure, is someone already working on it?

**Comment by rolandlo** [comment] 2020-12-29 05:56
I don't think anyone else is already working on it.

**Comment by frohro** [comment] 2021-01-15 19:55
Kudos to all you guys working on this.  I would find this especially helpful.
Thanks,
Rob

**Comment by Izerpizer** [comment] 2021-02-11 05:03
In my post that @Technius closed because its a duplicate of this, I mentioned that it would also be nice to be able to multi select objects from other layers as well, which ties into [#2782](https://github.com/xournalpp/xournalpp/issues/2782#issue-804175775).

**Comment by mjg** [comment] 2022-11-21 17:36
Just as a UI suggestion:
SHIFT adds to the selection, CTRL removes from the selection e.g. in GIMP.

Implementing SHIFT should be as simple as not resetting the currect selection when a select tool starts selecting, although I haven't figured out in code where it reset yet ...

Note that the resulting view may be misleading, just like the current view of lasso selected objects, because it's the bounding box rectangle.

**Closed** 2023-08-04 07:15 UTC
Labels: enhancement, good first issue, papercut, difficulty::easy, priority::medium
