### ISSUE TITLE
Can't write since upgrade to Ubuntu 23.10

### ISSUE THREAD

**Issue by scroom** [xournalpp/xournalpp#5303] opened 2023-10-29 20:15 UTC
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 23.10

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

PPA

### Xournal++ Version

1.2.2+dev

### libgtk Version

3.24.38

### Bug Description

I've upgraded from Ubuntu 23.04 to 23.10. Since upgrading to Ubuntu 23.10, I can no longer write in the app and only see a red dot where I place the pen.
Also, I can no longer close the app via mouse.

### Expected Behaviour

Before, everything was going great. Writing, erasing, etc.

### Steps to Reproduce

1. Open the app under Ubuntu 23.10.

### Additional Context

Hardware is a Lenovo ThinkPad X1 Yoga 3rd generation.

**Comment by rolandlo** [comment] 2023-10-31 13:02
I'm also on Ubuntu 23.10 with a Lenovo ThinkPad X1 Yoga 3rd generation, but for me everything still works (on Wayland).
Can you try removing and reinstalling Xournal++?
Do you experience those problems even if you don't use the stylus?

**Comment by 5bpa** [comment] 2023-11-01 05:06
Hello, 

I have exactly the same problem.
I am using Wacom CTL-472.

My environment info below.
---
(Linux only) Distribution
Ubuntu 23.10

(Linux only) Desktop Environment
GNOME

(Linux Only) Display Server
"xorg"

Installation Method
apt install from Ubuntu official repo 

Xournal++ Version
1.2.1-1

libgtk Version
3.24.38-5ubuntu1
---

As you recommended, I reinstalled xournalpp from ubuntu official repo. 
(apt remove xournalpp && apt install xournalpp)
Unfortunately, it didn't work. 

With mouse, it works greatly.

If you need anything that can help, please let me know. 

Thank you.

**Comment by rolandlo** [comment] 2023-11-01 07:14
@5bpa Does it matter for you if you use X11 (xorg) or Wayland?

**Comment by 5bpa** [comment] 2023-11-01 07:54
@rolandlo wayland is not working on my labtop (lenovo x1e gen3), so i can't help but use xorg.

**Comment by rolandlo** [comment] 2023-11-01 19:30
I'm closing this as a duplicate of #5249

**Closed** 2023-11-01 19:30 UTC
Labels: bug

**Comment by 5bpa** [comment] 2023-11-06 01:30
@rolandlo  works perfectly on wayland in my labtop. It seems like xorg problem.
