### ISSUE TITLE
Wacom cursor and pen position not the same

### ISSUE THREAD

**Issue by writeblankspace** [xournalpp/xournalpp#3347] opened 2021-08-26 04:04 UTC
**Affects versions :**
 - OS: [Windows
 - Which version of libgtk do you use: 3.24.29
 - Version of Xournal++: 1.1.0
 - Installation method: stable .exe, from website
 
 **Describe the bug**
When I use my wacom tablet to draw, pen writing is a few inches above the pen cursor

**To Reproduce**
1. Open xournal
2. Use a wacom tablet to draw
3. bug

**Expected behavior**
The cursor and the pen writing would be on the same place

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/75297066/130898759-47f34a46-99cd-4c35-b725-c77aca68b0dc.png)

**Comment by lb90** [comment] 2021-08-31 17:39
Hello @jeanravenclaw! This issue should be fixed in the [1.1.0-hotfix.1 release](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). Could you make a test and tell us whether it works?

**Comment by bhennion** [comment] 2021-08-31 19:17
Duplicate of #2436

**Closed as completed** 2021-10-25 09:40 UTC
Labels: bug
