### ISSUE TITLE
can't open several xournalpp documents from desktop menu

### ISSUE THREAD

**Issue by dinojr** [xournalpp/xournalpp#4759] opened 2023-03-24 17:57 UTC
**Affects versions :**
 - OS: Ubuntu 22.10
 - \Gnome-Wayland
 - Which version of libgtk do you use
     - 3.24.34
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.1.3+dev
 - Installation method: PPA
 -
**Describe the bug**
Right clicking the xournalpp icon in the Gnome Dash doesn't offer to create a new xournapp window 

**To Reproduce**
1. Open a Xournalpp window
2. Open the Gnome-shell dash
3. Right-click the xounalpp window

**Expected behavior**
An entry should display `Create a new window`

**Screenshots of Problem**
![Capture d’écran du 2023-03-24 18-55-57](https://user-images.githubusercontent.com/2698065/227603732-3fcb394b-f216-40bf-92df-6c4ac266d744.png)

**Additional context**
In previous versions, the option to add a new window was present.

**Comment by rolandlo** [comment] 2023-03-24 20:40
I can confirm this (also on Ubuntu 22.10). @dinojr Do you have any estimate since when that option is missing?

**Comment by rolandlo** [comment] 2023-03-25 06:23
I did a git bisection and found that 9dda71dd6dfefbf4a584931527c1f1cf67c7ed34 merged on February 24, 2023 is the culprit.

**Comment by rolandlo** [comment] 2023-03-25 06:34
The issue is caused by this line:

https://github.com/xournalpp/xournalpp/blob/9dda71dd6dfefbf4a584931527c1f1cf67c7ed34/src/core/gui/MainWindow.cpp#L52-L53

@bhennion What is this line good for? Can we remove it?

**Comment by bhennion** [comment] 2023-03-25 08:31
I don't remember specifically, something to do with accelerators I think.
Anyway, linking window and app seems the right to do, so I would not remove this.

Maybe using the [NON_UNIQUE flag](https://docs.gtk.org/gio/flags.ApplicationFlags.html#non_unique) would do the trick?

**Comment by rolandlo** [comment] 2023-03-25 09:48
> I don't remember specifically, something to do with accelerators I think. Anyway, linking window and app seems the right to do, so I would not remove this.
> 
> Maybe using the [NON_UNIQUE flag](https://docs.gtk.org/gio/flags.ApplicationFlags.html#non_unique) would do the trick?

We already use that flag:

https://github.com/xournalpp/xournalpp/blob/4d8b2107565c42435bbc222faba7932f9544745b/src/core/control/XournalMain.cpp#L52-L53

**Comment by bhennion** [comment] 2023-03-25 11:47
It looks like Gnome shell is ignoring the NON_UNIQUE flag, for some reason. This issus is not present e.g. on Plasma KDE. (but I confirm it is present on Gnome on Archlinux).

Removing the line `gtk_window_set_application(GTK_WINDOW(getWindow()), parent);` (and fixing whatever stops working once this is done) sounds like a dirty fix to me.
Either there is a gnome-shell bug (which should take the NON_UNIQUE flag into account), or there is a way for us to inform gnome-shell directly.

**Comment by dinojr** [comment] 2023-03-25 13:38
For what it's worth some applications like Firefox still manage to get a menu entry to open a new window.

Le 25 mars 2023 12:47:17 GMT+01:00, Benjamin Hennion ***@***.***> a écrit :
>It looks like Gnome shell is ignoring the NON_UNIQUE flag, for some reason. This issus is not present e.g. on Plasma KDE. (but I confirm it is present on Gnome on Archlinux).
>
>Removing the line `gtk_window_set_application(GTK_WINDOW(getWindow()), parent);` (and fixing whatever stops working once this is done) sounds like a dirty fix to me.
>Either there is a gnome-shell bug (which should take the NON_UNIQUE flag into account), or there is a way for us to inform gnome-shell directly.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/xournalpp/xournalpp/issues/4759#issuecomment-1483803466
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Envoyé d'un smartphone. Veuillez excuser la brièveté de ce message.

**Closed** 2023-05-31 03:34 UTC
Labels: bug, confirmed
