### ISSUE TITLE
cannot dark mode

### ISSUE THREAD

**Issue by newyorkthink** [xournalpp/xournalpp#5357] opened 2023-11-22 22:40 UTC
### Operating System

Linux

### (Linux only) Distribution

kali

### (Linux Only) Display Server

None

### Installation Method

appimage

### Xournal++ Version

latest

### libgtk Version

appimage

### Bug Description

cannot enable dark theme

### Expected Behaviour

![image](https://github.com/xournalpp/xournalpp/assets/87791643/45943805-b98e-4eec-9527-4313163415f7)
![image](https://github.com/xournalpp/xournalpp/assets/87791643/ea11e144-eb63-424e-a0aa-d387c7421fec)
```

❯ ./Downloads/xournalpp-1.2.2-x86_64.AppImage
xopp-Message: 06:37:51.330: TEXTDOMAINDIR = /tmp/.mount_xournaTDF24m/usr/share/locale:, Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /tmp/.mount_xournaTDF24m/usr/share/locale
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
xopp-Message: 06:37:51.512: Plugin "MigrateFontSizes" UI initialized

** (com.github.xournalpp.xournalpp:23210): WARNING **: 06:38:16.770: atk-bridge: get_device_events_reply: unknown signature

(com.github.xournalpp.xournalpp:23210): GtkSourceView-CRITICAL **: 06:38:55.208: gtk_source_style_scheme_chooser_set_style_scheme: assertion 'GTK_SOURCE_IS_STYLE_SCHEME (scheme)' failed
xopp-Message: 06:38:55.208: TEXTDOMAINDIR = /tmp/.mount_xournaTDF24m/usr/share/locale:, Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /tmp/.mount_xournaTDF24m/usr/share/locale

(com.github.xournalpp.xournalpp:23210): GtkSourceView-CRITICAL **: 06:39:33.911: gtk_source_style_scheme_get_id: assertion 'GTK_SOURCE_IS_STYLE_SCHEME (scheme)' failed

(com.github.xournalpp.xournalpp:23210): xopp-WARNING **: 06:39:33.911: [Crash Handler] Crashed with signal 11

(com.github.xournalpp.xournalpp:23210): xopp-WARNING **: 06:39:33.923: [Crash Handler] Wrote crash log to: /home/thinker/.cache/xournalpp/errorlogs/errorlog.20231123-063933.log

(com.github.xournalpp.xournalpp:23210): xopp-WARNING **: 06:39:34.053: Trying to emergency save the current open document…

(com.github.xournalpp.xournalpp:23210): xopp-WARNING **: 06:39:34.054: Successfully saved document to "/home/thinker/.config/xournalpp/emergencysave.xopp"
```

### Steps to Reproduce

![image](https://github.com/xournalpp/xournalpp/assets/87791643/0f02b5f1-ab47-44b0-8be6-bbf0428d1870)

**Comment by rolandlo** [comment] 2023-11-23 04:45
Duplicate of #5094

**Closed by rolandlo** 2023-11-23 04:45 UTC
Labels: bug
