### ISSUE TITLE
Cannot open my courses note file anymore! my exam is in a week

### ISSUE THREAD

**Issue by BelalQ** [xournalpp/xournalpp#4399] opened 2022-11-09 21:01 UTC
Affects versions :

OS: Windows 10 Pro 19044.2130
Version of Xournal++: 1.1.1
Installation method: win64x-package from Github

I have been working on my class notes for over a month now (60+ pages) and I have an exam next week, but when I tried opening the file today it gave me this error (tried downgrading to 1.1.1) but the same error keep showing whenever I try to open this specific file! please please help.

![Capture](https://user-images.githubusercontent.com/115403964/200940694-a59d5b2b-def8-4ac6-b24c-0ff293abbe0b.PNG)

**Comment by rolandlo** [comment] 2022-11-09 21:08
Looks like a corrupted file, but probably at least part of it can be recovered. Can you post the `Revit.xopp` file (within a .zip-file, so that it can be posted here)? Also check if you have any autosave file (`Revit.xopp~` in the same folder, I think). If you prefer you can also pass it privately to me in the [Gitter chat](https://gitter.im/xournalpp/xournalpp)

**Comment by rolandlo** [comment] 2022-11-09 22:21
For the record:
Most of the file (first 63 pages + part of the 64th page) was recovered. The problem likely resulted from the device being switched off while Xournal++ was still saving.

The method to recover the file was the following:

Rename `Revit.xopp` to `Revit.gz` and then (on Linux) run 
```term
gunzip -c  Revit.gz > Revit.xml
```
this saved all of the .xopp-file that could be recovered as an .xml file. Somehwere around line 9930 there was an `image` tag with a base64-encoded part of an image that suddenly broke off and mutated into the list of points of some stroke, ending with the `/stroke` tag. The next couple of lines were repeated hundreds of times. I removed those repeated lines and fixed the closing tags and saved the repaired `.xml`-file. Then I gzipped that file and renamed it into `Revit_repaired.xopp`. That did the trick.

I'm closing the issue, since the problem is fixed.

**Closed by rolandlo** 2022-11-09 22:21 UTC
