### ISSUE TITLE
**External keyboard not working.**

### ISSUE THREAD

**Issue by jayu9493** [xournalpp/xournalpp#4106] opened 2022-06-21 14:12 UTC
**Affects versions :**
 - OS: Linux (Kubuntu)
 - Desktop environment: KDE
 - Which version of libgtk do you use
     - 3.24.20
 - Version of Xournal++: 1.1.1+dev
 - Installation method: PPA

Xournalpp not responding the keys of external keyboard and i can assure because i have tried in other apps and keyboard is working just fine also by pressing ctrl+arrow keys i can navigate through the document but can't add text.
Also from my default keyboard (laptop's keyboard) I don't have to press ctrl to navigate through the document.
At the same time i can add text from my laptop keyboard.

**Comment by rolandlo** [comment] 2022-06-21 14:41
Probably a duplicate of #3859. Try the solution from that issue.

**Closed** 2022-06-22 14:07 UTC
Labels: bug
