### ISSUE TITLE
No Windows x32 version available

### ISSUE THREAD

**Issue by Sogolumbo** [xournalpp/xournalpp#2504] opened 2020-12-08 10:47 UTC
The windows release installer does not work on x32 systems (There's an error which says so).
In the build handbook it says that one has to use x64 tools.

Is it possible to build xournal++ for win32 if I just use the x32 tools?

**Comment by LittleHuba** [comment] 2020-12-08 11:52
Duplicate of #1747

**Closed by LittleHuba** 2020-12-08 11:52 UTC
