### ISSUE TITLE
Dropdown menus fall onto monitor to the left when clicked with stylus on Windows

### ISSUE THREAD

**Issue by lf-** [xournalpp/xournalpp#2400] opened 2020-11-15 03:10 UTC
**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows] Windows 10
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use -- 3.24.23
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch] -- 1.0.19 d376e7a6
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.] -- releases page

**Describe the bug**
When I click on any of the dropdowns on the top bar with my stylus, it pops up the menu on the monitor *left* of it [tested on 3 screen setup; it's always one to the left]. It doesn't seem to matter if it is in full screen. If I click on them on my leftmost monitor, the menu pops up as it would with the mouse.

Another strange observation is that if I open the settings dialog with my stylus, it opens on the screen to the left, whereas it opens on the same screen as the app if I use my mouse.

My tablet is a Huion H640P.

I am using the experimental input system although this reproduces with the default one as well.

**To Reproduce**
1. Click on a drop down button with a stylus

**Expected behavior**
Get the menu on the main screen.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/6652840/99161875-b140a900-26ab-11eb-819d-0660257b1984.png)
![image](https://user-images.githubusercontent.com/6652840/99161878-b69df380-26ab-11eb-8f0d-66284bca6fe8.png)

**Additional context**
Add any other information or context about the problem here.

**Comment by Technius** [comment] 2020-11-15 03:48
Duplicate of #1204. Unfortunately, this is not a bug we can really fix here.

**Closed by Technius** 2020-11-15 03:48 UTC
Labels: bug
