### ISSUE TITLE
Crash on double click outside page

### ISSUE THREAD

**Issue by Fraetor** [xournalpp/xournalpp#1651] opened 2019-12-03 17:00 UTC
**Affects versions :**
 - OS: Ubuntu 19.10, on GNOME on X11.
 - `libgtk-3-0/eoan,now 3.24.12-1ubuntu1 amd64`
 - Xournal++ 1.1.0, the latest from the Ubuntu ppa.
![Screenshot from 2019-12-03 16-34-53](https://user-images.githubusercontent.com/38766515/70071754-b5d09680-15ed-11ea-97c9-6fe7fe447865.png)

**Describe the bug**
Whenever I double click outside of the page area, either with a mouse or with a pen, Xournal++ crashes.

**To Reproduce**
1. Open Xournal++
2. Double click in light grey area outside of page, but not on toolbar, etc.

**Expected behavior**
It doesn't crash.

**Screenshots of Problem**
![xournal_crash](https://user-images.githubusercontent.com/38766515/70071683-9d607c00-15ed-11ea-813e-e9b38f9bbd69.gif)

**Logs**
[errorlog.20191203-164856.log](https://github.com/xournalpp/xournalpp/files/3917764/errorlog.20191203-164856.log)

**Comment by bitbacchus** [comment] 2019-12-03 21:09
Hm, I cannot reproduce this on Ubuntu 18.04.3 / Gnome / libgtk-3-0 3.22.30-1ubuntu4

Maybe it's some kind of upstream bug?

**Comment by LittleHuba** [comment] 2019-12-03 22:07
I can reproduce it locally on my machine.

**Comment by Technius** [comment] 2019-12-05 00:38
Should be fixed now. This seems to be a regression that affects only 1.1.0+dev versions (or transitory 1.0.15/16-1.1.0).

**Closed** 2019-12-05 00:37 UTC
Labels: Crash, bug, priority: high
