### ISSUE TITLE
Phantom lines sometimes when switching from one page to another (pen tool)

### ISSUE THREAD

**Issue by ArlingtonBrooks** [xournalpp/xournalpp#3663] opened 2021-12-15 16:16 UTC
**Affects versions :**
 - OS: Linux (arch): Kernel 5.15.7-arch1-1
 - Desktop environment: XFCE + X11
 - Which version of libgtk do you use
    3.24.30
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     1.1.0 git commit 9d1277de
 - Installation method: official repos (pacman)

**Describe the bug**
Phantom input drawing with multiple drawing tablets when using pen buttons to change tools frequently

**To Reproduce**
(using a graphics tablet): 
1. Assign a pen button to change tools
2. Switch rapidly between tools using pen button (example: switching from pen mode to scroll to pen frequently)
3. May take 5-10 minutes for bug to occur; issue occurs more frequently when moving from one page to another (eg: using hand tool to scroll)
4. 
(While writing this, I also noticed that I can reproduce this behaviour with just the mouse)
1. Create a document with 2 pages
2. Select the pen tool
3. Scroll to mid-way between page 1 and 2
4. Hold down the pen tool to draw a line, rapidly swipe onto page 1 and back to page 2.  
5. Switch tools; the pen continues to draw.  When you press with the new tool, the line stays (if you press with the pen tool, sometimes the line disappears).  

**Expected behavior**
When there is no input pressure (or when the mouse button is not pressed), no line should be drawn with the pen tool

**Screenshots of Problem**
![Bug1](https://user-images.githubusercontent.com/16168606/146218864-08ffd45e-2381-43d4-a4dd-2a507cc5b431.png)
![Bug2](https://user-images.githubusercontent.com/16168606/146218878-b971cca1-a069-4236-95e7-9bcd3c59182f.png)
Screen-capture (video) of problem using just computer mouse input: https://user-images.githubusercontent.com/16168606/146222841-3194a981-5358-44c5-bc4a-83395d7c710c.mp4

**Additional context**
I have confirmed using the tablet-maker's own software that no pressure is detected from the pen, additionally I have confirmed that this is not an xinput issue using `xinput test <id>` which shows zero pen pressure while xournalpp is drawing ghost lines. 

While writing this, I noticed this issue can be reproduced using just a computer mouse.

**Comment by MichelReims** [comment] 2021-12-21 12:22
I confirm under Windows 7 and 10

**Comment by nimota** [comment] 2022-01-03 13:54
I am also experiencing this, though the steps to reproduce it in my case are much simpler: using a tablet, hover from the background area of Xournal++ to the page. As soon as I hover over the page, it draws these phantom lines. This only happens when hovering from the background to the page itself.

**Comment by Technius** [comment] 2022-02-22 04:02
I believe this is a duplicate of #3274, which was fixed in 1.1.1.

**Closed by Technius** 2022-02-22 04:02 UTC
Labels: bug
