### ISSUE TITLE
Resizing xournalpp does not update horizontal scrolling range

### ISSUE THREAD

**Issue by debdeepbh** [xournalpp/xournalpp#1139] opened 2019-05-12 18:55 UTC
**Affects versions :**
 - OS: Ubuntu 18.04
 - Version of Xournal++: 1.0.11

**Describe the bug**
After xournalpp is resized, the horizontal scrolling range is not re-calculated until the drawing area is resized. In other words, the non-drawing region is not trimmed. As a result, it is possible to horizontally scroll out way beyond the drawing area.

**To Reproduce**
1. Maximize xournalpp
2. Un-maximize xournalpp so that it resizes horizontally
3. Drag the horizontal scrollbar to the right

**Expected behavior**
Horizontal scrolling should stop immediately after encountering the right border of the drawing area.

**Additional context**
Hitting Ctrl+(-) or Ctrl+Shift+(+) immediately fixes the issue.

**Comment by Technius** [comment] 2019-05-12 19:08
Seems like it's related to #1132.

**Comment by JJones780** [comment] 2019-05-17 09:09
I can replicate this in the new and old input system.
Note that to replicate: 
step1 - whole width showing with large space on either side. i.e. zoomed out.
 I'll have a look into it soon.

**Comment by Febbe** [comment] 2019-06-02 07:20
I looked into that issue and i think the problem is, that the preferred and minimal size is not calculated dynamically, instead, it uses a previously calculated value, which is only set after the space allocation.
The Layout derives its boundaries also from this value. This Size must be set before the space allocation or calculated dynamical every time when "gtk_xournal_get_preferred_width" and "gtk_xournal_get_preferred_height" is called.

**Comment by Febbe** [comment] 2019-06-04 17:45
Ok the main problem is that the gtk_widget_queue_resize signal has no effect when it's called from inside the gtk_widget_size_allocate routine. Since the "size_allocate" signal is connected to ZoomControl::onWidgetSizeChangedEvent the and it is called inside this function since we detect the size change over this function gtk_widget_queue_resize will be ignored.

I really don't have an idea how to get around that, we need to set the allocation of the xournal manually in size_allocate. The fact that we use the allocation from the previous call of layoutPages for the minimal size request is still a problem, but i fixed that in my local branch.

For further information see: https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-queue-resize

**Comment by JJones780** [comment] 2019-09-15 08:38
I can't replicate this anymore... looks like it's fixed?

**Comment by LittleHuba** [comment] 2019-09-16 15:44
The fix was #1213 which got merged.

**Closed by LittleHuba** 2019-09-16 15:44 UTC
Labels: PR available, bug
