### ISSUE TITLE
Installation Xournal++ 1.1.1. crashes

### ISSUE THREAD

**Issue by ikanakova** [xournalpp/xournalpp#3837] opened 2022-02-18 18:35 UTC
**Affects versions :**
 - OS: Windows
 - Installation method: official release (github)

**Describe the bug**
During installation, the program crashes unexpectedly, then the application cannot be uninstalled. You need to reinstall Xournal ++ 1.1.0-hotfix.1, which will install without any problems and can be uninstalled without any problems. This problem is for the latest version 1.1.1 for windows and nightly build xournalpp-1.1.1 + dev-nightly.20220218-windows as well.

**To Reproduce**
1. Install aplication.
2. The installation crashes.

**Expected behavior**
The installation completes without problems.

**Screenshots of Problem**
![1 1 1 +dev](https://user-images.githubusercontent.com/38765251/154741376-702087e4-4c67-4364-a694-e728834324e1.PNG)
Translation:
Xournalpp-1.1.1 + dev-nightly.20220218-windows has stopped working.
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.
Debug / Close program

![uninstall](https://user-images.githubusercontent.com/38765251/154741389-51c7f787-774d-4b6d-a03b-6b7e3a056bef.PNG)
Translation:
Un_A.exe has stopped working.
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.
Debug / Close program

**Comment by rolandlo** [comment] 2022-02-19 15:03
I cannot reproduce the issue. Both 1.1.1 and 1.1.1+dev install fine on my Windows 10 installation.
@ikanakova Do you use Windows 10 or Windows 11?

**Comment by ikanakova** [comment] 2022-02-20 14:23
@rolandlo Windows 10 Pro, version 21H2, build 19044.1526

**Comment by ikanakova** [comment] 2022-02-20 14:37
@rolandlo I think the problem is when creating a shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Xournal++\Uninstall.lnk

**Comment by ikanakova** [comment] 2022-02-23 20:36
Overwriting C:\Program Files\Xournal++\Uninstall.exe (1.1.1+dev) with the same file from 1.1.0-hotfix.1 apparently solved the error with Un_A.exe has stopped working. I think the error is directly in the C:\Program Files\Xournal++\Uninstall.exe.

**Comment by Technius** [comment] 2022-03-12 19:37
The only recent change to the uninstaller logic is `f76a2630`, but I don't see how that could've caused the issue.

I'm going to assume that this crash is specific to your computer, so I'm going to close this issue for now. Feel free to reopen if you get a similar crash in the next update.

**Closed by Technius** 2022-03-12 19:37 UTC
Labels: bug, priority::high, os::windows, Crash

**Comment by navarhontes** [comment] 2022-10-31 22:40
I'm having the same issue.  I'm also on Windows 10.  
![image](https://user-images.githubusercontent.com/21990957/199123401-2a14fe93-1cea-440a-b8e6-1292b9d27087.png)

**Comment by Technius** [comment] 2022-11-01 05:56
This bug has already been fixed in Xournal++ 1.1.2, which you can [download here](https://github.com/xournalpp/xournalpp/releases/tag/v1.1.2) (the website will be updated soon).
