### ISSUE TITLE
Hand tool isn't scrolling

### ISSUE THREAD

**Issue by njtwiseman** [xournalpp/xournalpp#1501] opened 2019-09-27 01:34 UTC
**Affects versions :**
 - Manjaro 18.1.0 Juhraya Linux 4.19.69-1-Manjaro
 - Version 1.0.13, Commit 26f95cb6

**Describe the bug**
Hand tool is not scrolling around the page

**To Reproduce**
This happens to me with any input, tablet, mouse, with the hand tool selected, or with it mapped to a button

**Expected behavior**
The page should scroll

**Comment by Technius** [comment] 2019-09-27 17:30
Do you have the old input system or the new input system enabled?

Please follow the [input debugging instructions](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs) so we can help you debug the problem.

**Comment by njtwiseman** [comment] 2019-09-30 04:25
Sry for the wait...haven't had a chance to follow through with info.  I believe it happens on both input systems.

Will follow input debugging instructions soon, hopefully.

**Comment by MisterPresident** [comment] 2019-10-19 13:36
I can confirm that the hand tool is broken on both new and old input system.
When I touch the screen, I can see the cursor (hand) "crapping" the page, the cursor moves but the page doesn't scroll. After releasing the hand "opens" again.

I am on the newest release.

**Comment by jug007** [comment] 2019-11-12 17:36
The hand tool works on my notebook, but not on my desktop computer. They are both running Linux Mint 19.2 with xournalpp "Version 1.0.15 Built on Oct 19 2019, 23:47:16" from the PPA.

**Comment by LittleHuba** [comment] 2019-11-12 17:41
@jug007 Can you make sure that the settings are identical on both machines?

**Comment by jug007** [comment] 2019-11-12 17:48
Yes they are identical. The only difference is the input devices.
Working:
![Bildschirmfoto vom 2019-11-12 18-44-03](https://user-images.githubusercontent.com/11144627/68696277-f142ec80-057c-11ea-83c2-67efbd9faba5.png)
Not working:
![Bildschirmfoto vom 2019-11-12 18-44-05](https://user-images.githubusercontent.com/11144627/68696308-03248f80-057d-11ea-8328-57ea00007ac2.png)

**Comment by LittleHuba** [comment] 2019-11-12 18:37
You have not activated the new input system. Please do so, as the old system is buggy and no longer maintained. We will remove it from the source in one or two releases. It only exists if anybody finds a major issue and can't downgrade.

**Comment by jug007** [comment] 2019-11-12 18:40
It doesn't work in the new input system as well (restarted the app after enabling it)

**Comment by LittleHuba** [comment] 2019-11-12 18:41
On both machines ore on the one it did not work before as well?

**Comment by jug007** [comment] 2019-11-12 18:42
Sorry, on the machine it that it doesn't work on without the old input system as well.

**Comment by LittleHuba** [comment] 2019-11-12 18:47
> Do you have the old input system or the new input system enabled?
> 
> Please follow the [input debugging instructions](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs) so we can help you debug the problem.

Please provide input logs. We have to rule out that it is something device specific. Best would be if you could provide logs of both machines and the exact same steps. One single try to move the page without doing anything else before. Approximate timestamps would be nice when you started the stroke with the handtool.

**Comment by kamatikos** [comment] 2020-03-23 08:16
I just came across this bug myself.

It occurred starting with the old input system, and persisted through me switching to the new system.

I can't seem to reproduce the bug, but enabling "paired pages" and "presentation" mode simultaneously, then disabling them, then using "zoom fit to screen" seems to have been what restored the hand tool's functionality. I doubt that exact sequence in its entirety is what caused the restoration, but it didn't seem purely coincidental (ie: something within that sequence is what did it). If the bug returns, I'll investigate each of those display options individually, if possible.

**Comment by jug007** [comment] 2020-05-03 23:59
Finally went around to look at providing the logs, but cannot actually build according to https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs
#1931

**Comment by jug007** [comment] 2020-05-04 08:28
Here are the logs from the machine running into the problem:
[debug_input.log](https://github.com/xournalpp/xournalpp/files/4573533/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/4573534/debug_gdk_input.log)
```
motofckr9k@motofckr9k-mint-desktop:~/xournalpp/build$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Microsoft® Nano Transceiver v2.0 Mouse	id=13	[slave  pointer  (2)]
⎜   ↳ Microsoft Microsoft® Nano Transceiver v2.0 Consumer Control	id=14	[slave  pointer  (2)]
⎜   ↳ Microsoft Microsoft® Nano Transceiver v2.0 Consumer Control	id=15	[slave  pointer  (2)]
⎜   ↳ HID 046a:0023                           	id=9	[slave  pointer  (2)]
⎜   ↳ Logitech G703                           	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® Nano Transceiver v2.0	id=12	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® Nano Transceiver v2.0 System Control	id=16	[slave  keyboard (3)]
    ↳ 3D Camera: eTronVideo                   	id=17	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® Nano Transceiver v2.0 Consumer Control	id=20	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® Nano Transceiver v2.0 Consumer Control	id=21	[slave  keyboard (3)]
    ↳ HID 046a:0023                           	id=10	[slave  keyboard (3)]
    ↳ Logitech G703                           	id=18	[slave  keyboard (3)]
    ↳ HID 046a:0023                           	id=19	[slave  keyboard (3)]
motofckr9k@motofckr9k-mint-desktop:~/xournalpp/build$ 
```

**Comment by LittleHuba** [comment] 2020-05-04 12:56
Please check your settings once more. The device you tested with is set to be ignored. Hence all events of the device are ignored.

```
** Message: 10:08:22.390: Event
Event type:	GDK_MOTION_NOTIFY
Source device:	GDK_SOURCE_MOUSE
Device Class:	INPUT_DEVICE_IGNORE
```

**Comment by jug007** [comment] 2020-05-04 13:06
Okay I enabled it and tried with and without the "new input system". Like before it still doesn't scroll.
Here are the new logs with the new input system disabled:
[debug_input.log](https://github.com/xournalpp/xournalpp/files/4574793/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/4574794/debug_gdk_input.log)

**Comment by jug007** [comment] 2020-05-04 13:21
Looks like the logging only really work when the new input system is enabled:
[debug_input.log](https://github.com/xournalpp/xournalpp/files/4574872/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/4574879/debug_gdk_input.log)

**Comment by LittleHuba** [comment] 2020-05-04 13:22
The input logs only work with the new input system enabled.

Try to enable the new input system and set each device to "ignored" and then back to "mouse" or "pen". Then retry.

**Comment by jug007** [comment] 2020-05-04 13:25
Putting them to ignore and then back to mouse, doesn't change the behavior.
Do you want logs of me doing that, or was that only to be sure that the new logs were fine?

**Comment by LittleHuba** [comment] 2020-05-04 13:27
That was only to ensure that the class is correctly set. Please go through each input class for your mouse and make one stroke (button down-move-button up) on the page. Then send me the log. Please also send me in which order you iterated through the classes.

**Comment by jug007** [comment] 2020-05-04 13:33
What do you mean with "make one stroke (button down-move-button up)"?
Just click once, try to scroll downwards, try to scroll up?

**Comment by LittleHuba** [comment] 2020-05-04 13:39
Just do the exact sequence:
- primary button down / touch screen with your pen
- move in any direction
- primary button up / hover with pen above screen

The tool that is activated is of no interest.

**Comment by jug007** [comment] 2020-05-04 19:06
I went from top to bottom. One by one.
![Bildschirmfoto vom 2020-05-04 21-00-28](https://user-images.githubusercontent.com/11144627/81003389-1c7f0800-8e4b-11ea-882b-a997f9af71ff.png)

[debug_input.log](https://github.com/xournalpp/xournalpp/files/4576781/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/4576779/debug_gdk_input.log)

**Comment by LittleHuba** [comment] 2020-05-05 18:08
Sorry I think you missunderstood me. Please take one single device and go through each class (entries in the dropdown menu)

**Comment by jug007** [comment] 2020-05-06 15:46
[debug_input.log](https://github.com/xournalpp/xournalpp/files/4587788/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/4587789/debug_gdk_input.log)
I went from Disabled -> Mouse -> Mouse+Keyboard Combo -> Pen -> Eraser -> Touchscreen -> Disabled

**Comment by LittleHuba** [comment] 2020-05-07 08:27
Okay that is strange now. Your assignments seem correct but the one log you sent me earlier on where your device was disabled makes no sense. Could you set all your devices to `Mouse` and try if things work?

**Comment by jug007** [comment] 2020-05-07 11:36
It doesn't work with all devices set to Mouse. Do you want a log of that?

**Comment by LittleHuba** [comment] 2020-05-07 11:52
Yeah please give me the log once more. Something is really awkward here...

**Comment by jug007** [comment] 2020-05-08 10:37
Here are the updated logs with every device set to mouse:
[debug_input.log](https://github.com/xournalpp/xournalpp/files/4598470/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/4598469/debug_gdk_input.log)

**Comment by LittleHuba** [comment] 2020-05-08 12:38
Okay those logs make more sense now at least the input class is correct. I assume the problem still persists?

**Comment by jug007** [comment] 2020-05-08 14:36
Yes

**Comment by dinojr** [comment] 2020-05-13 13:57
> When I touch the screen, I can see the cursor (hand) "crapping" the page, the cursor moves but the page doesn't scroll. After releasing the hand "opens" again.
> 
> I am on the newest release.

Same here with a Wacom BambooFun tablet. What are the input devices needed ? Here are my settings.
![xournapp](https://user-images.githubusercontent.com/2698065/81821660-64c8b500-9532-11ea-9651-eebbe17d71f1.png)

**Comment by LittleHuba** [comment] 2020-05-15 09:42
@jug007 I just took another look through your settings. Seems like the presentation mode is switched on. Could you go into your settings file with an editor and set the property `presentationMode` to false and try if things work then?

**Comment by tomcalverley** [comment] 2020-05-15 10:26
I can confirm that toggling View->Presentation Mode on/off fixes this problem for me on ubuntu 18.04.4 LTS with a Wacom Intuos CTH490. Thanks @LittleHuba!

**Comment by LittleHuba** [comment] 2020-05-15 10:40
Nice! I assume this is a big in the versioning routine when the settings are updated for a new version.

**Comment by jug007** [comment] 2020-05-15 15:19
@LittleHuba the presentation mode was not on. Turning it on and off, does fix the problem though. I am also very sure that I never turned that on ever before.

**Comment by LittleHuba** [comment] 2020-05-16 00:05
I assume the state was corrupted by an update. This mode was overhauled some months ago and it seems like the settings were not updated to a consistent state by the upgrade algorithm. As your issue is "fixed", I'll close this ticket. Updating the algorithm is not worth it. It only runs when the settings are updated and for any users affected by this, that is already done and won't run again. We can't do anything about this anymore unfortunately.

**Closed by LittleHuba** 2020-05-16 00:05 UTC
Labels: Input, bug, confirmed, difficulty:medium, need info, priority: high

**Comment by dinojr** [comment] 2020-05-16 13:05
>Turning it on and off, does fix the problem though.

Same here.

**Comment by LittleHuba** [comment] 2020-05-16 16:26
> @LittleHuba the presentation mode was not on. Turning it on and off, does fix the problem though. I am also very sure that I never turned that on ever before.

The problem seems to be in there as in the settings it is switched on but only partially. That way the GUI is not reflecting this but the internal algorithms get confused.

**Comment by cerotidinon** [comment] 2020-12-09 11:36
Had the same problem right now, turning presentation mode on and off fixed it. Notably, scrolling didn't work only when selecting the input class "pen", for touchscreen it worked.

**Comment by ottowhite** [comment] 2021-04-20 08:22
To enable the bug: disable scrollbar fade out and restart. To disable the bug: enable scrollbar fade out and restart.

**Comment by tmelorc** [comment] 2021-09-13 13:51
> Had the same problem right now, turning presentation mode on and off fixed it. Notably, scrolling didn't work only when selecting the input class "pen" or "mouse", for touchscreen it worked.

Thanks so much. 
Turning off presentation mode fixed it here also.
