### ISSUE TITLE
macOS Monterey : Failed to open desktop file

### ISSUE THREAD

**Issue by YangThinking** [xournalpp/xournalpp#3957] opened 2022-04-13 05:56 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: macOS Monterey & M1Max
 - Version of Xournal++: 1.1.1

**Describe the bug**
Failed to open desktop file

**To Reproduce**
1. Step 1 : open desktop PDF file
2. Step 2 : No permissions for desktop files
3. Step 3 : Screenshot of the screen is as follows

<img width="782" alt="image" src="https://user-images.githubusercontent.com/60769311/163109853-98452913-a6d5-418e-a24b-d668f8c1c41e.png">

**Comment by rolandlo** [comment] 2022-04-13 07:43
This is a duplicate of #1757.

**Closed by rolandlo** 2022-04-13 07:43 UTC
Labels: bug
