### ISSUE TITLE
Surface could not find kpsewhich in PATH

### ISSUE THREAD

**Issue by git4lei** [xournalpp/xournalpp#1738] opened 2020-02-08 07:40 UTC
**Affects versions :**

 - OS: Windows 10 on Surface Pro 6
 - Version of Xournal++ 1.0.17 (Git commit 12febf7e, Built on Feb 3, 2020, 02:51:48)

**Describe the bug**
Xournal++ could not find kpsewhich in PATH, although I have already install MiKTeX 2.9, and make sure kpsewhich is in PATH, and can be run from shell

**To Reproduce**
open Xournalpp
Click on the button to input Math TeX
Pop-up says: Could not find kpsewhich in PATH; please install kpsewhich and put it on path

**Expected behavior**
Able to input TeX using my MiKTeX installation and kpsewhich binary that's on PATH

**Screenshots of Problem**
Please see attached screenshot 
![screen](https://user-images.githubusercontent.com/2008132/74081329-b9b6e400-4a88-11ea-9700-df2984299d90.jpeg)

**Comment by aarjaneiro** [comment] 2020-03-05 04:32
Same here unfortunately. Unsure if it can be manually specified (maybe under latexcontroller.h at line Path pdflatexPath ?)

**Comment by aarjaneiro** [comment] 2020-03-07 04:35
Added ~\Programs\MiKTeX 2.9\miktex\bin\x64\kpsewhich.exe directly onto the path, still receive error.

**Comment by DQuanR2** [comment] 2020-03-25 17:43
Added the path but the problem remains

**Comment by Javipove** [comment] 2020-04-01 09:30
Same problem
Also used MiKTeX for installing latex

**Comment by ronnie-oldgit** [comment] 2020-04-08 13:00
Same problem when using TeXLive distribution with Windows 10.

**Comment by dishantpandya777** [comment] 2020-04-09 14:41
Yes, I am also getting the same problem.

**Comment by Technius** [comment] 2020-04-09 23:48
I finally had the time to debug this in my Windows VM. Looks like an issue with our packaging: we need to copy `/mingw64/bin/gspawn-win64-helper-console.exe` into the `bin` folder. There's still one problem though: now a console window will flash open every time a key is pressed, which absolutely kills usability. I'll see if I can do something about this...in the meantime, the packaging fix PR will be uploaded tomorrow.

After I fix this: if you are using a `1.0.x` version of Xournal++, you can make it work by copying `gspawn-win64-helper-console.exe` from the `bin` folder of the nightly.

**Comment by lazcol** [comment] 2020-04-10 16:02
Hello.
I have the same error running Debian Buster.
I have installed Texlive and TexMaker.
kpsewhich is installed, i am able to run it from everywhere, so it's in the $PATH.
in the echo $PATH i have the /usr/bin folder where is the kpsewhich.
`name@host:~$ echo $PATH`
`/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
`
I copied the kpsewhich file in the .xournalpp folder, just to try, but nothing happens.

**Comment by Technius** [comment] 2020-04-10 17:42
@lazcol This issue is for Windows; please open another issue.

**Comment by dishantpandya777** [comment] 2020-04-11 13:05
> I finally had the time to debug this in my Windows VM. Looks like an issue with our packaging: we need to copy `/mingw64/bin/gspawn-win64-helper-console.exe` into the `bin` folder. There's still one problem though: now a console window will flash open every time a key is pressed, which absolutely kills usability. I'll see if I can do something about this...in the meantime, the packaging fix PR will be uploaded tomorrow.
> 
> After I fix this: if you are using a `1.0.x` version of Xournal++, you can make it work by copying `gspawn-win64-helper-console.exe` from the `bin` folder of the nightly.

Hello Sir, I have tried to work out, but still getting the same error.

I have downloaded latest Nightly Build, and tried to find that console exe but couldn't find it. So, I found it and downloaded from the Google. And put it in bin folder too. But it returned with no effect. :)  Please help me.

**Comment by Technius** [comment] 2020-04-11 17:55
The fix has not been released yet and will be available after some testing.

**Comment by AHaumer** [comment] 2020-04-12 15:53
Same problem on a Dell Vostro with Windows 10 Pro 64 bit, TexLive2020 installed. 
Would need a solution within short, I have to teach online (as many others in the wordl) using Xournal++ with a pen tablet, but would prefer to write the more complicated formulae with Tex.
Thanks in advance for a quick solution!

**Comment by Mottok** [comment] 2020-04-12 16:52
Same problem:
The path C:\Program Files\MiKTeX 2.9\miktex\bin\x64 is already set as demanded by the error message. But not does not work.

**Comment by Technius** [comment] 2020-04-13 16:09
The fix will be available either in tonight's nightly build (if you are using the bleeding edge version `1.1.0+dev`) or in `1.0.18`, which will be released later this week.

**Comment by ronnie-oldgit** [comment] 2020-04-13 16:12
That's great thanks. Want to recommend it to colleagues and having the integration with LaTeX is a big sell.

**Comment by AHaumer** [comment] 2020-04-14 19:45
Thanks a lot - waiting for the 1.18.0 later this week. Just in time, we start on Moday 20. 
Tex formulas are extremely usefull - I'm teaching Electric Engineering.
Stay healthy!

**Comment by AHaumer** [comment] 2020-04-14 20:06
Just tried the nightly build on Windows 10 Pro 64 bit:
- Tex formula works
- Can't choose "Insert rectangle" (an other geometric figures, right from formula)
- Xournal++ craches when leaving Xournal++
Getting a little bit nervous since lectures start next Monday ...

**Comment by Technius** [comment] 2020-04-14 21:25
> * Tex formula works

Great!

> * Can't choose "Insert rectangle" (and other geometric figures, right from formula)

Do you mean while the latex dialog is open? The dialog is modal so you'll have to close it before you try using the other toolbar buttons.

> * Xournal++ crashes when leaving Xournal++

I can confirm that this happens, but only on `master` branch/nightly. The crash does not occur in the `1.0.18` build that is currently being tested (#1864).

**Comment by Technius** [comment] 2020-04-14 21:34
I have confirmed that the crash is due to some other change on `master` branch. I will open another issue once I have narrowed down the cause.

**Comment by AHaumer** [comment] 2020-04-14 21:49
Thanks for your help up to now!

> > * Can't choose "Insert rectangle" (and other geometric figures, right from formula)
> Do you mean while the latex dialog is open? The dialog is modal so you'll have to close it before you try using the other toolbar buttons.

No, even if no other tool is active I can't insert a geometric figure. Clicking on the rectangle - just nothung happens.

Looking forward to 1.18.0 ;-)

Stay healthy!

**Comment by Technius** [comment] 2020-04-15 19:44
The fix is now available to stable users in `1.0.18`.

**Closed by Technius** 2020-04-15 19:44 UTC
Labels: PR available, Windows, bug, confirmed, priority: high

**Comment by guiguilhermegui** [comment] 2021-06-12 12:56
Hi there, trying to configure Tex for me, I discover that with `Texlive` the issue still remains.
Xournal Version `1.0.20`   Windows 10
First it was showing a similar message but for `pdflatex`, I put the bin folder on PATH and it was solved, clicking again in add Tex this message openned, wich is strange since `kpsewich` also is in the same bin folder.  Does installing `MikTex` is the best option for fixing it?
