### ISSUE TITLE
[Wayland] Menu popup out of place/hard to select

### ISSUE THREAD

**Issue by MatsG23** [xournalpp/xournalpp#4453] opened 2022-11-27 17:16 UTC
**Affects versions :**
 - OS: openSUSE Tumbleweed 20221126
 - Desktop environment: KDE Plasma 5.26.3 (Wayland)
 - Version of libgtk: 3.24.34
 - Version of Xournal++: 1.1.2
 - Installation method: Software repository of the distribution

**Describe the bug**
If you click on one of the buttons at the top to open a menu, the clicked menu is often not opened. Instead it selects the first menu.

**To Reproduce**
1. Click to open a menu

**Expected behavior**
You should be able to properly and easily open specific menues.

**Comment by maehne** [comment] 2022-11-28 10:35
I can reproduce the same behaviour with Xournal++ 1.1.3 on an up-to-date EndeavourOS installation with KDE Plasma (Wayland) as desktop environment. When I execute Xournal++ from the command line, I see the following GDK warning message each time when I try to open a menu with the mouse:

```
[...]
(xournalpp:48667): Gdk-WARNING **: 11:27:24.340: Tried to map a popup with a non-top most parent
[...]
```

One detail, which I also observe is that instead of the Xournal++ icon, the Wayland icon is shown as window menu button on the top left.

**Comment by AlexRamallo** [comment] 2022-11-28 18:35
This exact same bug also happens in Sublime Text 3 and Inkscape on a brand new Fedora 37 Kinoite installation (also Wayland + KDE), so I'm guessing it's not a Xournal bug.

**Comment by rolandlo** [comment] 2022-12-11 22:17
@MatsG23 Using Ubuntu 22.10 (Gnome, Wayland) I don't experience the issue. Can someone post a screen recording? It might only occur on KDE.
The bug report mentioned is very old and has been closed (as fixed apparently) 5 years ago.

**Comment by AlexRamallo** [comment] 2022-12-11 23:34
[untitled.webm](https://user-images.githubusercontent.com/656330/206935178-d4f224f6-873b-4604-9f43-4b39d99950a0.webm)

Notice how the **File** menu opens when I click on **Help**, but hovering the mouse over the desired menu option fixes it. It's only the initial popup that's in the wrong place. This was recorded using the flathub version of xournalpp.

Software versions from KDE system settings app:
```
Operating System: Fedora Linux 37
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 6.0.12-300.fc37.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-8665U CPU @ 1.90GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: LENOVO
Product Name: 20QGS4SL02
System Version: ThinkPad X1 Yoga 4th
```

This is on Fedora Kinoite 37 (with latest updates)

I don't believe this is a xournal issue, because I've encountered the problem in all other GTK apps, as well as a text selection issue (I don't know if the text selection bug is related to this). AFAIK, xournalpp's text input is custom made rather than using standard GTK stuff, so that might be why text selection works. Maybe it's a Kwin+Wayland issue?

Also [posted this](https://discussion.fedoraproject.org/t/text-selection-doesnt-work-at-all-in-gtk-apps-other-issues/44679) a few days ago.

**Comment by bhennion** [comment] 2022-12-25 11:08
Closing as the bug seems to be a packaging/dependency issue.

**Closed by bhennion** 2022-12-25 11:08 UTC
Labels: bug

**Comment by rolandlo** [comment] 2023-02-25 10:57
I have noticed though that we use the deprecated (since: Gtk 3.22) [`gtk_menu_popup`](https://docs.gtk.org/gtk3/method.Menu.popup.html) at various places in the code. The recommendation is:
>Please use gtk_menu_popup_at_widget(), gtk_menu_popup_at_pointer(). or gtk_menu_popup_at_rect() instead.
