### ISSUE TITLE
"Laser" pointer

### ISSUE THREAD

**Issue by JCBustamante** [xournalpp/xournalpp#2550] opened 2020-12-17 14:48 UTC
It would be nice for lecturing if there was something similar to the "laser pointer" existing in e.g. goodnotes.

It is not the highlighter, rather is a non permanent stroke that would vanish a few seconds after being drawn.
Perhaps this could be a variation of the highlighter.

**Comment by rolandlo** [comment] 2020-12-17 14:53
Duplicate of  #2410

**Closed by rolandlo** 2020-12-17 14:53 UTC
Labels: enhancement
