### ISSUE TITLE
Saving creates big files which take long to save

### ISSUE THREAD

**Issue by funnym0nk3y** [xournalpp/xournalpp#3915] opened 2022-03-16 23:32 UTC
**Affects versions :**
 - OS: Win10 21H2
 - Which version of libgtk do you use: 3.24.31
 - Version of Xournal++: 4f113e94
 - Installation method: exe

**Describe the bug**
Documents with roughly 50 handwritten pages create big files (~10MB)  when saving. This in itself is not a problem, but saving takes some time (~5-10s). In that time Xournal is pretty unresponsive (some weird rendering errors on the page, pen offset, etc.). As it crashes very often in my case, I need to do autosaves every few minutes. I also think (based on my usage as it crashes purely when an autosave is happening) that some user actions while saving lead to those crashes.

**Comment by bhennion** [comment] 2022-07-21 18:11
Closing as a duplicate of #2684

**Closed by bhennion** 2022-07-21 18:11 UTC
Labels: bug
