### ISSUE TITLE
 Xournal ++ closing alone on Win10 and MacOS.

### ISSUE THREAD

**Issue by tiagoadmrj** [xournalpp/xournalpp#2739] opened 2021-02-01 21:51 UTC
Good night!

First, I would like to mention, that this developed application is very functional and useful.

Problem I had: I have a graphics tablet for the gaomon s620. In Pop OS 20.10, Xournal ++ is working perfectly. On Mac Big Sur (Hackinstosh) and Windows 10, with the final version .19, the software opens, works, but the moment I press the pen on the graphics tablet it closes. Access the app as administrator and Win8 compatibility.

**Comment by personalizedrefrigerator** [comment] 2021-02-02 06:24
Could you try this again with version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? It might have been fixed since version 1.0.19!

Additionally, this might be a duplicate of https://github.com/xournalpp/xournalpp/issues/2719#issue-795751030.

**Comment by mslxl** [comment] 2021-11-07 03:49
I am using Gaomon Pro1060 and I have met the same problem with Xournal++ 1.1.0 on Windows 10.
But I can't reproduce this problem with version 1.1.0+dev, it seems the problem have been solved on Xournal++ 1.1.0+dev,

**Comment by rolandlo** [comment] 2022-06-20 19:14
Closing due to inactivity. The issue is probably fixed.

**Closed by rolandlo** 2022-06-20 19:14 UTC
Labels: bug, os::windows, os::mac, need info
