### ISSUE TITLE
If opened in split screen , then if its toggled to full screen the app gets stuck and crashes. Scrolling through pages is choppy

### ISSUE THREAD

**Issue by Reshad-Ul-Karim** [xournalpp/xournalpp#5643] opened 2024-04-27 09:27 UTC
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

Official release

### Xournal++ Version

1.2.2

### libgtk Version

3.24.38

### Bug Description

Does not work in split screen. App gets stuck and after saving if the file gets quitted it crashes frequently. Scaling does not work in windowed mode. Often full screen cant be toggled OFF if split screen is used

Scrolling through pages often gets choppy and lags a lot. 

### Expected Behaviour

Split screen mode should be more optimised and stable. 
Scrolling through pages should be smooth and dragging should be smooth

### Steps to Reproduce

Simply go to split screen mode in MACOS

**Comment by rolandlo** [comment] 2024-04-27 09:29
Please add the MacOS version and whether it's an ARM device or not.

**Comment by Reshad-Ul-Karim** [comment] 2024-04-27 09:54
macOS 14.4.1

**Comment by rolandlo** [comment] 2024-04-27 09:59
And is it an ARM device (does it have an M1,M2 or M3 SoC)?

**Comment by Reshad-Ul-Karim** [comment] 2024-04-27 10:14
Macbook Pro M2 13 inch 16GB RAM / 512GB SSD

**Comment by Febbe** [comment] 2024-04-28 21:27
The problem is, that we can't create any installers / binaries for arm based processors, since neither github-actions nor microsoft azure support those as runners. On top, none of us devs has an arm based mac. 

But we may look into this: https://github.com/actions/runner-images/issues/8971#issuecomment-1898175991

**Comment by rolandlo** [comment] 2024-04-29 19:14
Since today I have a Mac Mini M2 (with 8 GB of RAM), so I can test and debug.

I already have an MacOS ARM build for Xournal++. Can you access it on https://cirrus-ci.com/task/5138787729145856 (under Artifacts)?
Not sure if it is possible without logging in, but give it a try. 
After downloading and installing into the /Applications folder you may have to get it out of quarantine, otherwise it will say that the file is damaged and can't be opened. I did so from the command line via 
```shell
xattr -d com.apple.quarantine /Applications/Xournal++.app/
````
On my M2 it seems to work pretty fine. I haven't encountered a major issue yet.

**Comment by Reshad-Ul-Karim** [comment] 2024-04-29 21:27
Thanks, I have tried it and it is far better than the version I have been using. However, the zoom in and zoom out choppiness remains whilst the scrolling is smoother than before; I havent faced the crashes yet. The split screen issues are also solved in this one and most features are accessible and theres no fatal crash yet. Thanks for the effort. Kudos

**Comment by Reshad-Ul-Karim** [comment] 2024-05-05 16:08
There are some issues I have found out @rolandlo in this version if you could have a look at it
1. Saving with cmd+S takes a while and you cannot work as the app is stuck while it's fully saved

2. Sometimes copying after selecting any drawing does not appear directly when I paste it, I have to either save or exit the file and again enter to access it.

3. Zooming  seems choppy and lags if I try it with the trackpad. It can be much smoother if I use the trackpad of MacBook. Maybe you could have a look into it.

**Comment by rolandlo** [comment] 2024-05-07 17:48
I'll have a look. How does your trackpad look like? And what screen resolution and dpi scale factor do you use? What kind of documents are you working with when you experience "app stuck while saving" or "choppy zooming"?

**Comment by Reshad-Ul-Karim** [comment] 2024-05-07 19:29
I am using 1440x900 resolution, trackpad is of the default macbook pro M2 13 inch. In this given video, I didnt write anything before pressing cmd+s to save, but if I write something it takes longer. Its document that has screenshots and is in xopp format. Zoom in out often gets really laggy

Uploading 2024-05-08 01-26-08.mp4…

**Comment by Reshad-Ul-Karim** [comment] 2024-05-07 20:22
Uploading 2024-05-08 01-26-08.mp4…

**Comment by rolandlo** [comment] 2024-05-08 01:16
The mp4 wasn't really uploaded. Could you please try again?

**Comment by Reshad-Ul-Karim** [comment] 2024-05-09 22:40
hello @rolandlo here is the video file for your convenience
https://drive.google.com/file/d/1omoKbSIJ9Gy5OqYcLwUxYlB8MRXtDev2/view?usp=sharing

When the file gets big ( 30- 40 pages ) and after every edit I make the manual save takes 10 seconds or more. And it lags a lot and if it crashes during the save all files are lost and a recovery file reappears and recreates. Due to not clearing log files every time I open the app it offers me a log file.

I used the windows version too , the MACOS one is way too choppy than the windows one. 

Please if you could look into another recommendation :

The features given are useful and I couldnt ask for more. However, as an instructor and sometimes a presenter a laser pointer pen tool with disappearing ink is a killer feature. 
Please refer to this video 7:20 for the feature available in Goodnotes available both in macOS and ipadOS ; https://youtu.be/G6lAWTgY0mo

**Comment by HiramTheHero** [comment] 2024-09-30 14:19
> Since today I have a Mac Mini M2 (with 8 GB of RAM), so I can test and debug.
> 
> I already have an MacOS ARM build for Xournal++. Can you access it on https://cirrus-ci.com/task/5138787729145856 (under Artifacts)? Not sure if it is possible without logging in, but give it a try. After downloading and installing into the /Applications folder you may have to get it out of quarantine, otherwise it will say that the file is damaged and can't be opened. I did so from the command line via
> 
> ```shell
> xattr -d com.apple.quarantine /Applications/Xournal++.app/
> ```
> 
> On my M2 it seems to work pretty fine. I haven't encountered a major issue yet.

I'm trying to download the file you shared. I signed into the service, and when I click on the download button I get the following error:
`{"code":500,"message":"There was an error processing your request. It has been logged (ID 352f317b3fddd0fc)."}`.

If I drill into the folder and try to download the `.dmg` file I get the following error:
`{"code":404,"message":"com.google.cloud.storage.StorageException: 404 Not Found\nGET https://storage.googleapis.com/download/storage/v1/b/cirrus-ci-6033383598325760-3271c9/o/artifacts%2Frolandlo%2Fxournalpp%2F5138787729145856%2Fxournalpp%2Fmac-setup%2FXournal++.dmg?alt=media\nNo such object: cirrus-ci-6033383598325760-3271c9/artifacts/rolandlo/xournalpp/5138787729145856/xournalpp/mac-setup/Xournal++.dmg"}`

Not sure if the artifact expired or something. Just curious if you have some pointers on how to get it downloaded. Thanks for taking the time to build the project for M1 Macs.

**Comment by rolandlo** [comment] 2024-09-30 14:23
> > Since today I have a Mac Mini M2 (with 8 GB of RAM), so I can test and debug.
> > I already have an MacOS ARM build for Xournal++. Can you access it on https://cirrus-ci.com/task/5138787729145856 (under Artifacts)? Not sure if it is possible without logging in, but give it a try. After downloading and installing into the /Applications folder you may have to get it out of quarantine, otherwise it will say that the file is damaged and can't be opened. I did so from the command line via
> > ```shell
> > xattr -d com.apple.quarantine /Applications/Xournal++.app/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On my M2 it seems to work pretty fine. I haven't encountered a major issue yet.
> 
> I'm trying to download the file you shared. I signed into the service, and when I click on the download button I get the following error: `{"code":500,"message":"There was an error processing your request. It has been logged (ID 352f317b3fddd0fc)."}`.
> 
> If I drill into the folder and try to download the `.dmg` file I get the following error: `{"code":404,"message":"com.google.cloud.storage.StorageException: 404 Not Found\nGET https://storage.googleapis.com/download/storage/v1/b/cirrus-ci-6033383598325760-3271c9/o/artifacts%2Frolandlo%2Fxournalpp%2F5138787729145856%2Fxournalpp%2Fmac-setup%2FXournal++.dmg?alt=media\nNo such object: cirrus-ci-6033383598325760-3271c9/artifacts/rolandlo/xournalpp/5138787729145856/xournalpp/mac-setup/Xournal++.dmg"}`
> 
> Not sure if the artifact expired or something. Just curious if you have some pointers on how to get it downloaded. Thanks for taking the time to build the project for M1 Macs.

Looks like it got deleted somehow. I'm updating the build instructions and there is now an issue with `gobject-introspection` that needs to get fixed. Once it builds again I will let you know.

**Comment by HiramTheHero** [comment] 2024-10-13 18:51
Thank you, @O1Alweheshy,  so much for sharing this! I did have to run: `xattr -c /Applications/Xournal++.app/` to get it working. But it works great. Thank you, again.

**Comment by rolandlo** [comment] 2024-10-21 02:49
A MacOS ARM build has been released with version 1.2.4. Closing the issue therefore.

**Closed by rolandlo** 2024-10-21 02:49 UTC
Labels: bug, os::mac
