### ISSUE TITLE
Picture Rotate und Filesize

### ISSUE THREAD

**Issue by Raffinade** [xournalpp/xournalpp#1450] opened 2019-09-01 11:33 UTC
Is it possible to make pictures wich are imported could rotate? 
And if i save the file with an imported picture (Jgp maybe 500kB) the .xopp file is really big maybe 7MB. Is it possible to leave the compressed file in the .xopp? So it is a waste of space.

**Comment by Technius** [comment] 2019-09-03 03:25
Rotation is duplicate of #918.

The imported pictures could be stored uncompressed, so we'll look into it. This will probably not be an issue when we implement a new file format.

**Comment by LittleHuba** [comment] 2019-09-03 07:12
Pictures are stored using Base64 uncompressed. So we add an additional 30% overhead to the image data. The new format solves this by just zipping up the compressed file.

**Comment by LittleHuba** [comment] 2019-09-16 20:22
> And if i save the file with an imported picture (Jgp maybe 500kB) the .xopp file is really big maybe 7MB. Is it possible to leave the compressed file in the .xopp? So it is a waste of space.

This is actually mentioned in a lot of other issues and will be solved by the new format anyway. Therefore I'll close this issue as both topics are handled by other tickets.

**Closed by LittleHuba** 2019-09-16 20:22 UTC
Labels: enhancement
