### ISSUE TITLE
Xournal++ AppImage crashes on Ubuntu

### ISSUE THREAD

**Issue by PaulCombal** [xournalpp/xournalpp#2555] opened 2020-12-17 22:53 UTC
**Affects versions :**
 - OS: Ubuntu Linux 20.04
 - (Linux only) Desktop environment: XFCE (Xubuntu)
 - Which version of libgtk do you use
     - 3.18.9
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.0.20
 - Installation method: AppImage downloaded from the release tab

**Describe the bug**
The app crashes on startup.

**To Reproduce**
Mark the AppImage as executable & run it. At least with Xubuntu 20.04.

**Expected behavior**
The application starts

**Screenshots of Problem**
N/A

**Additional context**
[errorlog.20201217-234442.log](https://github.com/xournalpp/xournalpp/files/5712558/errorlog.20201217-234442.log)

```
paul@vivobook:~/Téléchargements$ ./xournalpp-1.0.20-x86_64.AppImage 

** (com.github.xournalpp.xournalpp:44793): WARNING **: 23:44:41.529: Failed to load "colornames.ini" (/home/paul/.xournalpp//colornames.ini): Aucun fichier ou dossier de ce type

ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

** (com.github.xournalpp.xournalpp:44793): WARNING **: 23:44:42.104: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:44793): WARNING **: 23:44:42.111: [Crash Handler] Wrote crash log to: /home/paul/.xournalpp/errorlogs/errorlog.20201217-234442.log

** (com.github.xournalpp.xournalpp:44793): WARNING **: 23:44:42.415: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:44793): WARNING **: 23:44:42.416: Successfully saved document to "/home/paul/.xournalpp//emergencysave.xopp"
paul@vivobook:~/Téléchargements$ ./xournalpp-1.0.20-x86_64.AppImage --version
Xournal++ 1.0.20 
└──libgtk: 3.18.9 
** Message: 23:47:45.531: MemoryLeak: sum 0 objects.
paul@vivobook:~/Téléchargements$ uname -a
Linux vivobook 5.8.0-050800-generic #202008022230 SMP Sun Aug 2 22:33:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
paul@vivobook:~/Téléchargements$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

**Comment by Technius** [comment] 2020-12-18 00:37
Duplicate of #2555.

**Closed by Technius** 2020-12-18 00:37 UTC
Labels: Crash, bug, buildsystem, packaging
