### ISSUE TITLE
PDF in presentation mode, scroll doesn't move by a PDF page exactly.

### ISSUE THREAD

**Issue by boffi** [xournalpp/xournalpp#1764] opened 2020-03-10 10:00 UTC
- OS: Debian Sid
 - Desktop environment: none, display run by X11 not Wayland
 - Which version of libgtk do you use: ?
 - Version of Xournal++: 1.0.17
 - Installation method: debian package (as provided by xournalpp developers)

My use case:
  I want to present a PDF, full screen, one page a time, occasionally drawing-scribbling on it
My solution:
  full screen, presentation mode, zoom fit to height
My problem:
  scrolling - whenever I scroll using, e.g.,  PgDown the scroll amount is less than one page and larger and larger portions of the previous page are left in sight. 

I have to remark that `xournal` behaves perfectly with respect to my use case, possibly because it has an option to turn off the continuous display of a document that `xournalpp` apparently has dropped, so it's not a show stopper for me.

**Comment by ohthehugemanatee** [comment] 2020-03-11 12:04
In fact this entire issue can be resolved with a single-page view in presentation mode.

TBH I don't really understand the use case for the current "presentation mode". In every other viewer, presentation mode treats the document like a slideshow, ie one page at a time, fit to screen. Usually it's coupled with some behavioral modifications like touch gestures (or just taps on the left/right side of the screen) to change pages. 

Would love some context here...

**Comment by boffi** [comment] 2020-03-11 13:36
My idea of a good PDF presentation mode for xournalpp:
- one page at a time (i.e., single page mode) zoomed to fit the screen;
- no visible UI with a keyboard shortcut / gesture to toggle the UI;
- all navigation shortcuts are active, plus a shortcut to insert a blank page at point.

But simply fixing the scroll amount  in current presentation mode would be fine.

**Comment by Technius** [comment] 2020-03-11 17:29
I'll look into this when I get around to the next part of the viewport refactor.

**Comment by ohthehugemanatee** [comment] 2020-03-16 22:28
@Technius I'd be happy to have a look before then. Can you point me in the right direction? \

From a quick skim of the source I guess that in `XournalView.cpp` we're getting an incorrect response from `XournalView::ensureRectIsVisible`... which must be a problem with the layout returned from `gtk_xournal_get_layout` in Presentation mode.

am I in the right direction here?

**Comment by ohthehugemanatee** [comment] 2020-03-16 22:42
This simple PR fixes it for me... I couldn't test with a PDF though, since my compiled version segfaults when it tries to load a PDF. highly doubt that's a problem with this one-liner change though. :)

**Comment by ohthehugemanatee** [comment] 2020-03-21 07:53
Thanks for the review and explanation on my simple PR. Realized in testing further that this ONLY happens on PDF documents... which means it's more likely to be a wrong Y dimension calculation. Unfortunately my home-compiled version still crashes when I try to load a PDF, so I'll have to solve that before I can make further progress.

**Comment by Technius** [comment] 2020-03-21 17:55
Is this without any changes that you've made? Can you post your crash log?

**Comment by bhennion** [comment] 2022-12-25 11:29
Marking as a duplicate of #1035

**Closed by bhennion** 2022-12-25 11:29 UTC
Labels: bug, Zoom, difficulty::medium, priority::medium
