### ISSUE TITLE
Duplicate key Shortcut "shift ctrl e"

### ISSUE THREAD

**Issue by gzmorell** [xournalpp/xournalpp#855] opened 2019-02-08 12:03 UTC
Hi, "shift ctrl e" is duplicated:
file: export as.
tools: eraser.

In main.glade:

<object class="GtkMenuItem" id="menuFileExportAs">
                        <property name="visible">True</property>
                        <property name="can_focus">False</property>
                        <property name="label" translatable="yes">Export as...</property>
                        <property name="use_underline">True</property>
                        <signal name="activate" handler="ACTION_EXPORT_AS" swapped="no"/>
<accelerator key="e" signal="activate" modifiers="GDK_SHIFT_MASK | GDK_CONTROL_MASK"/>

<object class="GtkCheckMenuItem" id="menuToolsEraser">
                        <property name="visible">True</property>
                        <property name="can_focus">False</property>
                        <property name="label" translatable="yes">_Eraser</property>
                        <property name="use_underline">True</property>
                        <property name="draw_as_radio">True</property>
                        <signal name="toggled" handler="ACTION_TOOL_ERASER" swapped="no"/>
<accelerator key="e" signal="activate" modifiers="GDK_SHIFT_MASK | GDK_CONTROL_MASK"/>

**Comment by andreasb242** [comment] 2019-02-09 09:49
confirmed - easy to fix, but currently not sure to which key

**Comment by luco5826** [comment] 2019-02-09 12:01
Hi guys!
I don't think that `Export as PDF` and `Export as...` should have two different short-cuts, I would remove the one for `Export as PDF` at all or assign it to a completely different Shortcut, since all the tools use `Shift+Ctrl` I would set `Export as...` to `Ctrl+E` and the PDF option to a different (unused) shortcut. 
Moreover, when you select `Export as..` the default starting option is PDF file, so `Export as PDF` wouldn't make sense as a standalone shortcut!

**Closed** 2019-02-11 17:50 UTC
Labels: bug
