### ISSUE TITLE
Crush session when close xournal++

### ISSUE THREAD

**Issue by Daddie2** [xournalpp/xournalpp#3559] opened 2021-11-11 12:00 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: manjaro
 - (Linux only) gnome wayland
 - libgtk 3.24.30
 - xournal++ 1.1.0+dev
     

**Describe the bug**
If I use xournalpp for some time maybe hours my de restart 

**To Reproduce**
1. Step 1 open xournal and use it for hours 
2. Step 2 close it 
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![IMG_20211111_125351.jpg](https://user-images.githubusercontent.com/50950554/141294422-582b80d2-7043-4d6c-af47-babddab22d87.jpg)

**Additional context**
Add any other information or context about the problem here.

**Comment by LittleHuba** [comment] 2021-11-11 12:10
We need some more detail to fix this. When you encounter this bug, please call `journalctl -b-1 -e` in a terminal once your machine is up and running again. This command will provide you the log of the last session. The last few lines should give us some detail concerning the problem. Please be aware that this log may contain sensitive data. So check what you post.

**Comment by Daddie2** [comment] 2021-11-11 12:43
> We need some more detail to fix this. When you encounter this bug, please call `journalctl -b-1 -e` in a terminal once your machine is up and running again. This command will provide you the log of the last session. The last few lines should give us some detail concerning the problem. Please be aware that this log may contain sensitive data. So check what you post.

https://mega.nz/file/MOIgkb5a#HUKnxYkMGrQ1Wqn2pftx13ikDlPkANfwzq--gIr4y_k I don't care about my sentive data but I don't know what line do you need so I post everything

**Comment by LittleHuba** [comment] 2021-11-11 13:36
This seems to be a problem with your distribution. The log entry right before the system powers down is 

```
gnome-shell[8186]: endSessionDialog: No XDG_SESSION_ID, fetched fr>
```

Could you try if `gtk3-examples` shows the same behavior? I think this is not specific to Xournal++ but originates somewhere deeper in the stack.

**Comment by LittleHuba** [comment] 2021-11-11 13:38
It may also be called `gtk-demo`. The name depends on the distribution.

**Comment by Daddie2** [comment] 2021-11-12 00:37
i never use it so i don't know what of this examplei have to try i trying some on this example but nothing happend

**Comment by Lime-Parallelogram** [comment] 2021-12-21 19:31
I observe this issue also - it is very annoying. Some things I noticed, however you close Xournal (e.g. kill from task manager) it still crashes the desktop environment. I observed the same issue when using the stylus in GIMP so my suspicion is that it is something to do with the Xwayland translation layer. I'm assuming that Xournal runs though Xwayland given it starts with an X.

**Comment by sebastian-arnhold** [comment] 2021-12-28 09:23
I can confirm the bug. It's true what @Lime-Parallelogram says. With latest Ubuntu 22.04 LTS development version, crash happens when using pen for a while and then closing application - both on Xournal++ and on GIMP.

In addition, I get random freezes on Xournal++ after maybe 10-15 min. of using the pen.

Fixing this bug fast would be highly appreciated, since application is critical for education (e.g. schools).

**Comment by sebastian-387** [comment] 2022-01-01 19:47
I have a new hint.

At least for me, the bug does NOT occur while my convertible laptop is in "laptop" mode. It only occurs when folded over in "tablet" mode.

Very strange, can somebody confirm?

**Comment by rolandlo** [comment] 2022-01-01 19:52
@sebastian-387 Can you please tell what convertible you use? Do you expect I could reproduce it on Ubuntu 21.10 with my Lenovo Yoga (3rd gen) convertible? Or do I have to try the Ubuntu 22.04 developer version?

**Comment by sebastian-387** [comment] 2022-01-01 20:06
I'm using Ubuntu 22.04 developer version on an ASUS ExpertBook B5 Flip.

Since I'm not sure what the source of this bug is, I can only speculate. Putting the convertible into tablet mode and doodling with a pen for approx. 15 minutes crashes it with 100% reliability. Sometimes it crashes while doodling, but at the very least, when trying to exit the program.

**Comment by rolandlo** [comment] 2022-01-01 20:35
@sebastian-387 I just tried it (with Ubuntu 21.10 on X11 in tablet mode) writing with my stylus for almost 20 minutes, but didn't get a crash (even when closing Xournal++ at the end). It would help if you tried to reproduce it on X11 (assuming you used Wayland so far).

**Comment by sebastian-387** [comment] 2022-01-01 21:13
Can confirm! With Ubuntu 22.04 development version under X11, I can doodle for over 20 mins without a crash. This seems to be Wayland-related.

**Comment by sebastian-387** [comment] 2022-01-09 13:30
In a matter of last resort, I re-installed Ubuntu competely from scratch. I didn't even import the /home folder, as to prevent any remnants of the previous installation to make it over to my new one.

Bug still persists under Wayland. Doodling for about 15 min. on my ASUS ExpertBook B5 Flip consistently leads to a crash when closing the application. It crashes the whole Desktop Environment and I'm being thrown back to the login screen.  

Application does not crash when doodling for a shorter period of time, interestingly.

**Comment by rolandlo** [comment] 2022-01-09 13:38
@sebastian-387 Thanks for doing this great effort to debug the problem. I will now try to put my convertible into tablet mode on Wayland and see if I also get a crash after > 15 minutes or so. If I can reproduce it, I will try to find out, where exactly Xournal++ crashes on closing the application. Then we will see what we can do about it. 
If I can't reproduce it, I will provide you a version that emits a lot of debug messages when closing the application. That should narrow down possible reasons for the crash.

**Comment by rolandlo** [comment] 2022-01-09 14:52
I have tried it for more than 20 minutes on my Lenovo Yoga (3rd gen) in tablet mode on Wayland, but didn't get a crash. Closing the application at the end was also normal. I'm on Ubuntu 21.10 (with Gtk 3.24.30), maybe that makes the difference.
@sebastian-387 Can you please report, what version of Gtk you use?

**Comment by sebastian-387** [comment] 2022-01-09 15:05
This is really mysterious! We're even using the same GTK version!

I'm using Ubuntu 22.04 development version with all updates installed. I am using the following packages:
libgtk-3-0:amd64 (Version: 3.24.30-3ubuntu2)
libgtk2.0-0:amd64 (Version: 2.24.33-2ubuntu1)
Both came pre-installed.

**Comment by rolandlo** [comment] 2022-01-09 16:31
I have added debug messages in PR #3708. Unfortunately the built binaries won't work on Ubuntu 22.04 (at least not without some sym-linking). Best would be, if you could build from source @sebastian-387 following the instructions in [the wiki](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md) and [this modification](https://github.com/xournalpp/xournalpp/wiki/Installing#building-a-pull-request) to checkout the pull request. Is that something you manage to do? @sebastian-387 ?

**Comment by sebastian-387** [comment] 2022-01-09 18:56
I think I can manage that, but I'd have to wait for a couple of days because of job-related stuff.

**Comment by d3nnis77** [comment] 2022-01-10 21:30
I can confirm the bug. It only happens on Wayland and strangely only after longer use of Xournal++ (about an hour).
I´ve compiled the PR and let it crash, here is my stderr output and the journalctl output at the time of the crash.

(Manjaro GNOME with Linux 5.15.12)

[crashlog.txt](https://github.com/xournalpp/xournalpp/files/7841975/crashlog.txt)
[xournalpp_stderr.txt](https://github.com/xournalpp/xournalpp/files/7841977/xournalpp_stderr.txt)

**Comment by rolandlo** [comment] 2022-01-10 21:46
@d3nnis77 So it crashed while executing `g_application_quit ..`? (at `20:34:56.674`)

**Comment by d3nnis77** [comment] 2022-01-10 21:48
I´m no expert, but I assume that. I just closed Xournal++ normally and the stderr output ended there...

**Comment by rolandlo** [comment] 2022-01-10 21:58
Your `journalctl` starts with
```
Jan 10 20:34:56 user-hpenvyx360 gnome-shell[6706]: mutter:ERROR:../mutter/src/wayland/meta-wayland-touch.c:138:touch_handle_surface_destroy: assertion failed: (g_hash_table_remove (touch->touch_surfaces, surface) == FALSE)
```
So I'm pretty sure it's [this bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4701) that also happens in other drawing apps (Krita, GIMP, Drawing) appearently.

**Comment by sebastian-387** [comment] 2022-01-10 23:51
Yes, that absolutely makes sense! As @Lime-Parallelogram and I have stated, the bug also occurs when using GIMP under Wayland.

Should I still attempt to build and make a crashlog, or do we have sufficient evidence?

Because if we've tracked it down, the people at GNOME should fix this ASAP, since multiple softwares are affected and GNOME 42 is imminent! The bugfix could then be included in 42 before shipping to various distributions. Many distros will have switched to Wayland by now, so not fixing this in time for the next release could end up leaving potentially all people with convertible laptops with a very annoying bug!

(I personally don't wanna imagine how many students are using this for note taking in classes etc.)

**Comment by sebastian-387** [comment] 2022-01-10 23:51
@d3nnis77 your description fits my bug exactly.

**Comment by rolandlo** [comment] 2022-01-11 05:22
@sebastian-387 @d3nnis77 We do have sufficient evidence. From Xournal++'s side we can do nothing about it. We don't even distribute `Gnome shell` / `XWayland` / `Mutter` etc. If you would like to help fix this ASAP, please head over to the [Gnome shell issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4701), explain your observations, reference this Xournal++ ticket and offer your help to debug the issue further.

**Comment by sebastian-387** [comment] 2022-01-11 05:57
Done! Thanks for your support. Let's hope they can come up with a solution.

Maybe the other people who are affected by this bug are interested in helping, too - if so, they should bookmark the link.

**Comment by d3nnis77** [comment] 2022-01-11 07:54
I havent testet other drawing apps yet, but I'm absolutley sure, that it's this GNOME bug.

@rolandlo Thanks for your fast support, and lets hope for a fast bugfix.

**Comment by sebastian-387** [comment] 2022-01-15 18:09
Can confirm the bug for Fedora 35 as well. This seems to be more widespread than we thought.

Have reported this to the upstream GNOME shell bug.

**Comment by d3nnis77** [comment] 2022-01-25 14:08
Issue can be closed. It was / is a mutter issue (https://gitlab.gnome.org/GNOME/mutter/-/issues/584), the according patch fixes the problem: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2251

**Comment by rolandlo** [comment] 2022-01-25 14:44
Thanks for reporting. I am closing the issue.

**Closed by rolandlo** 2022-01-25 14:44 UTC
Labels: bug, priority::high, confirmed, wayland

**Comment by JulianHeuser** [comment] 2022-02-22 19:52
I know this has been fixed, but has anyone figured out a workaround? I can't easily upgrade to mutter 41.4 and this is the one usability issue I've been having.

**Comment by sebastian-387** [comment] 2022-02-22 20:21
Sorry, no idea. I can however confirm that the bug is gone both in Fedora Rawhide (latest Fedora development version, GNOME 42) and Arch Linux (rolling release, GNOME 42). So these two distributions would be possible workarounds at the moment.
