### ISSUE TITLE
xournalpp crashes upon use of text selection tool

### ISSUE THREAD

**Issue by DarkShadow4** [xournalpp/xournalpp#5372] opened 2023-11-29 14:49 UTC
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 20.04

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

X.Org

### Installation Method

sudo apt install xournal

### Xournal++ Version

xournalpp 1.2.2+dev

### libgtk Version

libgtk: 3.24.20

### Bug Description

App crashes when I try to select text for underlining.

### Expected Behaviour

Expected behavior is that the text gets selected and the app stays open.

### Steps to Reproduce

Step 1: Select "Select Linear PDF Text" tool
Step 2: Try to select text

### Additional Context

Date: Wed Nov 29 15:45:50 2023
Error: signal 6
Xournal++ version 1.2.2+dev
Gtk version 3.24.20

[bt]: (0) xournalpp(+0xf6190) [0x559536649190]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7fecb2b06090]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7fecb2b0600b]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7fecb2ae5859]
[bt]: (4) xournalpp(+0xec45a) [0x55953663f45a]
[bt]: (5) xournalpp(_ZNK11XojPageView11repaintAreaEdddd+0x2c9) [0x55953673ebb9]
[bt]: (6) xournalpp(_ZN16PdfElemSelection10currentPosEdd24XojPdfPageSelectionStyle+0x1ff) [0x5595367305bf]
[bt]: (7) xournalpp(_ZN11XojPageView19onMotionNotifyEventERK17PositionInputData+0x21c) [0x55953673d79c]
[bt]: (8) xournalpp(_ZN15PenInputHandler12actionMotionERK10InputEvent+0x311) [0x559536699091]
[bt]: (9) xournalpp(_ZN18StylusInputHandler10handleImplERK10InputEvent+0x35b) [0x55953669992b]
[bt]: (10) xournalpp(_ZN12InputContext6handleEP9_GdkEvent+0x324) [0x5595366964b4]
[bt]: (11) xournalpp(_ZN3xoj4util6detail9wrap_implIXadL_ZN12InputContext13eventCallbackEP10_GtkWidgetP9_GdkEventPS3_EEbS8_JS5_S7_EEENSt11conditionalIX9is_same_vIbT0_EEiSA_E4typeEDpT2_Pv+0x10) [0x559536696c50]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3e736f) [0x7fecb3c0b36f]
[bt]: (13) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14a56) [0x7fecb3467a56]
[bt]: (14) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x2e1) [0x7fecb3485df1]
[bt]: (15) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fecb34870f3]
[bt]: (16) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x391949) [0x7fecb3bb5949]
[bt]: (17) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x24ced8) [0x7fecb3a70ed8]
[bt]: (18) /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x89b) [0x7fecb3a7318b]
[bt]: (19) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3cf69) [0x7fecb375bf69]
[bt]: (20) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x700f6) [0x7fecb378f0f6]
[bt]: (21) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7fecb337b17d]
[bt]: (22) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7fecb337b400]
[bt]: (23) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fecb337b4a3]
[bt]: (24) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7fecb35bdfe5]
[bt]: (25) xournalpp(_ZN11XournalMain3runEiPPc+0x5ed) [0x55953664b26d]
[bt]: (26) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fecb2ae7083]
[bt]: (27) xournalpp(_start+0x2e) [0x55953664849e]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xf681f) [0x55953664981f]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7fecb2b06090]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7fecb2b0600b]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7fecb2ae5859]
??:0
[bt] #5 xournalpp(+0xec45a) [0x55953663f45a]
??:0
[bt] #6 xournalpp(_ZNK11XojPageView11repaintAreaEdddd+0x2c9) [0x55953673ebb9]
??:0
[bt] #7 xournalpp(_ZN16PdfElemSelection10currentPosEdd24XojPdfPageSelectionStyle+0x1ff) [0x5595367305bf]
??:0
[bt] #8 xournalpp(_ZN11XojPageView19onMotionNotifyEventERK17PositionInputData+0x21c) [0x55953673d79c]
??:0
[bt] #9 xournalpp(_ZN15PenInputHandler12actionMotionERK10InputEvent+0x311) [0x559536699091]
??:0
[bt] #10 xournalpp(_ZN18StylusInputHandler10handleImplERK10InputEvent+0x35b) [0x55953669992b]
??:0
[bt] #11 xournalpp(_ZN12InputContext6handleEP9_GdkEvent+0x324) [0x5595366964b4]
??:0
[bt] #12 xournalpp(_ZN3xoj4util6detail9wrap_implIXadL_ZN12InputContext13eventCallbackEP10_GtkWidgetP9_GdkEventPS3_EEbS8_JS5_S7_EEENSt11conditionalIX9is_same_vIbT0_EEiSA_E4typeEDpT2_Pv+0x10) [0x559536696c50]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3e736f) [0x7fecb3c0b36f]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x14a56) [0x7fecb3467a56]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x2e1) [0x7fecb3485df1]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fecb34870f3]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x391949) [0x7fecb3bb5949]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x24ced8) [0x7fecb3a70ed8]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x89b) [0x7fecb3a7318b]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3cf69) [0x7fecb375bf69]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x700f6) [0x7fecb378f0f6]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7fecb337b17d]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7fecb337b400]
??:0
[bt] #24 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fecb337b4a3]
??:0
[bt] #25 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7fecb35bdfe5]
??:0
[bt] #26 xournalpp(_ZN11XournalMain3runEiPPc+0x5ed) [0x55953664b26d]
??:0
[bt] #27 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fecb2ae7083]
??:0
[bt] #28 xournalpp(_start+0x2e) [0x55953664849e]
??:0

Execution log:

DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/eric/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
CRITICAL: Gtk :: gtk_tree_model_iter_children: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
CRITICAL: GLib-GObject :: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
DEBUG   : -- :: Name com.canonical.AppMenu.Registrar does not exist on the session bus

CRITICAL: xopp :: Assertion failed: rv0 == static_cast<Float>(rv1)
    in function ceil_cast
    at line 91 of /build/xournalpp-JYsCJS/xournalpp-1.2.2+dev/src/util/include/util/safe_casts.h
WARNING : xopp :: [Crash Handler] Crashed with signal 6
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/eric/.cache/xournalpp/errorlogs/errorlog.20231129-154550.log

**Comment by rolandlo** [comment] 2023-11-29 15:03
Duplicate of #5348

**Closed by rolandlo** 2023-11-29 15:03 UTC
Labels: bug
