### ISSUE TITLE
Wiki-link [[]] like Obsidian

### ISSUE THREAD

**Issue by slimhk45** [xournalpp/xournalpp#4132] opened 2022-07-04 21:11 UTC
I would like to create subpage to store comments, definitions etc... For this I would like to have something like wikilinks [[]] to create and link to them.

**Comment by bhennion** [comment] 2022-07-05 06:16
Could you be more specific and describe what it should do?
Is this related to or a duplicate of #846 or #1126?
Duplicate of #3684?

**Closed** 2022-07-08 17:45 UTC
Labels: enhancement
