### ISSUE TITLE
what's the .xopp~ file extension?

### ISSUE THREAD

**Issue by andrewchenshx** [xournalpp/xournalpp#1498] opened 2019-09-25 05:24 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Windows
 - Version of Xournal++ 1.0.12

**Describe the bug**
double click a .xopp file to open it with xournalpp, then a file with the extension .xopp~ is created in the same folder. even when the xournalpp is closed, the .xopp~ is still there.

**Comment by ysooqe** [comment] 2019-09-26 07:19
same thing happens for me on Arch Linux (with the latest xournalpp from the `Community' repo)

**Comment by Technius** [comment] 2019-09-27 17:44
I cannot reproduce this when only opening files, but I see the file appearing when saving files. Are you certain this occurs when _opening_ files?

The `.xopp~` file is backup file that is generated before saving an open journal (in case there is an issue when saving, so the file does not become corrupted). The fact that the backup file is not deleted after a successful save is a bug, though. The fix is to delete the backup file after the save in `src/control/jobs/SaveJob.cpp`.

**Comment by Simon04090** [comment] 2020-12-01 09:14
This is still an issue.

**Comment by ngoonee** [comment] 2021-03-25 08:38
This https://github.com/xournalpp/xournalpp/pull/2885 is supposed to fix this issue? Doesn't seem to for me though.

**Comment by BachoSeven** [comment] 2021-03-25 10:40
@ngoonee I don't think it is supposed to, it seems to be about the timing of backup creation with certain file types.

**Comment by BachoSeven** [comment] 2021-03-27 16:37
Following master, the issue where every succesful saving would not delete the `.xopp~` seems to have disappeared. I looked around in the commits, but did not find anything related ¯\_(ツ)_/¯

**Comment by ngoonee** [comment] 2021-03-27 22:37
@BachoSeven odd, I just built latest master (from AUR it gives me 1.0.15.r721.g28971748-1 for version) and am still having that behaviour when opening .xopp files and then saving them, a .xopp~ file will be left.

**Comment by BachoSeven** [comment] 2021-03-27 22:42
Uhm I tried again and it is indeed still present...
It kind of happens only in certain situtations, i.e. not always reproducible

For instance, if you create a file and save it for the first time, the bug is not present
If you then open the file and save again, the bug is present; 
but if you close it, open again, delete the `.xopp~` and then save, it does not recreate the ~ file

**Comment by qstommyshu** [comment] 2021-10-05 18:22
Yep, this is still an issue for me on Ubuntu as well.

**Comment by Technius** [comment] 2022-02-06 02:55
Fixed in #3445.

**Closed by Technius** 2022-02-06 02:55 UTC
Labels: bug, difficulty::easy, priority::medium, hacktoberfest
