### ISSUE TITLE
Highlighter tool does not "paint" when using black paper color

### ISSUE THREAD

**Issue by JaviMaciasG** [xournalpp/xournalpp#3711] opened 2022-01-10 15:58 UTC
**Affects versions :**
 - OS: Ubuntu 20.04 (x11 with cinnamon, libgtk 3.24.20) and Windows 10 Pro (Education, version 20H2)
 - Using Xournal++ version 1.1.0+dev in Ubuntu and 1.1.0 in Windows
 - Installation method: Andreas Butti PPA in Ubuntu, and official release in Windows

**Describe the bug**
The highligher tool does not show its highlight when using black paper color.

**To Reproduce**
1. Change paper color to black
2. Try to use the highlighter with any color
3. If after 2, you change the paper color to any other one, you will be able to see the highlighs you did

**Expected behavior**
Highlighting should be seen over black paper color

**Comment by bhennion** [comment] 2022-01-10 16:53
This is a duplicate of #2471, for which we haven't really found a solution so far. See #2900 for a workaround using filled strokes instead.

**Closed by bhennion** 2022-01-10 16:53 UTC
Labels: bug

**Comment by JaviMaciasG** [comment] 2022-01-11 07:38
Sorry for not noticing the duplicate before and thanks for the hint.
