### ISSUE TITLE
Add startup interface for organizing pdf books?

### ISSUE THREAD

**Issue by xh542428798** [xournalpp/xournalpp#5208] opened 2023-10-07 06:47 UTC
### Feature Description

Sir, I really hope to use xournal++ as my PDF note-taking tool. It already meets most of my needs, but there are still some small requirements. For example, I hope there is a startup interface that displays various recently opened PDF files, just like SumatraPDF. In addition, if this startup interface can be made into a library form, it may be more convenient. This way, I can organize and classify all my PDFs, making it more like a PDF note-taking software.

![微信截图_20231007144606](https://github.com/xournalpp/xournalpp/assets/49368033/7309c744-d60c-4563-a335-026888feb6af)

**Comment by bhennion** [comment] 2023-10-07 12:09
Duplicate of #4945

**Closed by bhennion** 2023-10-07 12:09 UTC
Labels: enhancement
