### ISSUE TITLE
Starting Xournalpp by clicking opening an existing file will reset all settings if there already is another instance of Xournalpp

### ISSUE THREAD

**Issue by ysooqe** [xournalpp/xournalpp#1610] opened 2019-11-18 12:17 UTC
**Affects versions :**
 - OS: Linux
 - Gnome (X11)
 - Version of Xournal++ : 1.1.0+dev (compiled 2019-11-18) and 1.0.16

**Description**
When an instance of Xournalpp is started by clicking on an existing .xopp file while there is another open instance of Xournalpp running that was started through an application launcher (e.g. the Super-key on Gnome), all settings for Xournalpp are reset to the defaults in the instance that is opend by opening a .xopp file.

I used the [this](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs) set of instructions to record the logs. This issue does happen with the current stable version available in the Arch Linux repos aswell (Version 1.0.16-1).

**Steps to reproduce**
1. Open Xournalpp through a terminal (`xournalpp`) or through an application launcher and keep it open.
2. Open a .xopp file with Xournalpp.

**Expected behaviour** 
The second instance of Xournalpp uses all the settings that were already set.

**Actual Behaviour** The second instance of Xournalpp uses the default settings and if the file is saved and this instance of Xournalpp is closed after closing the first one, this "reset" of the settings to the default persists.

**Attached logs**
[debug_input_firstInstance](https://github.com/xournalpp/xournalpp/files/3858505/debug_input_p1-blank.log)
[debug_input_secondInstance](https://github.com/xournalpp/xournalpp/files/3858507/debug_input_p1-test.log)

[debug_gdk_input_firstInstance](https://github.com/xournalpp/xournalpp/files/3858518/debug_gdk_input_p1-blank.log)
[debug_gdk_input_secondInstance](https://github.com/xournalpp/xournalpp/files/3858522/debug_gdk_input_p1-test.log)

[xinput_list.log](https://github.com/xournalpp/xournalpp/files/3858528/xinput_list.log)

**Comment by LittleHuba** [comment] 2019-11-18 14:47
Duplicate of #1074

**Closed by LittleHuba** 2019-11-18 14:47 UTC
