### ISSUE TITLE
Pen registration wrong

### ISSUE THREAD

**Issue by funnym0nk3y** [xournalpp/xournalpp#2793] opened 2021-02-10 13:22 UTC
**Affects versions :**
 - OS: Windows
 - Version of Xournal++: 1.0.20

**Describe the bug**
The pen shows in the right location, but on the canvas the registartion is wrong. In the screenshot below I drew on the red dot, and the pen location is shown there aswell. 

**Input Logs**
Follow this tutorial https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs and attach the generated files.

**Expected behavior**
Well, draw where my pen is. 

**Screenshots of Problem**
![InkedScreenshot 2021-02-10 141420_LI](https://user-images.githubusercontent.com/41870754/107515003-b332df00-6baa-11eb-98ad-659eb1025c6e.jpg)

**Additional context**
Hardware is a Yoga 370 with integrated wacom stylus. But the pen is registerd as three different devices. See below:
![Screenshot 2021-02-10 142117](https://user-images.githubusercontent.com/41870754/107515467-52f06d00-6bab-11eb-9004-f9bb6b87f364.png)

**Comment by Technius** [comment] 2021-02-10 22:26
Duplicate of #1801 (see the comments for a workaround).

**Closed by Technius** 2021-02-10 22:26 UTC
Labels: Input, bug
