### ISSUE TITLE
Some personal plugins no longer work

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#5266] opened 2023-10-21 18:11 UTC
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

exe

### Xournal++ Version

xournalpp-1.2.2+dev-nightly.20231021-windows

### libgtk Version

3.24.39

### Bug Description

**Few months ago, I have created a plugin file main.lua that contains :**

function initUi()
.........
app.registerUi({["menu"] = "Stylo Bleu", ["callback"] ="StyloBleu",["accelerator"] = "s",["toolbarId"] = "STYLO_BLEU", ["iconName"] = "Stylo_Bleu"});
 app.registerUi({["menu"] = "Marqueur Jaune", ["callback"] ="MarqueurJaune",["accelerator"] = "m",["toolbarId"] = "MARQUEUR_JAUNE", ["iconName"] = "Marqueur_Jaune"});
........
end
.........

function Stylo()
-- Choisir le stylo "PEN"
app.uiAction({["action"]="ACTION_TOOL_PEN"});
-- Pour choisir l'épaisseur "MEDIUM" 
app.uiAction({["action"]="ACTION_TOOL_PEN_SIZE_FINE"});
-- pour choisir ligne pleine
app.uiAction({["action"]="ACTION_TOOL_LINE_STYLE_PLAIN"});
-- Pour dessin normal (pas de cercle, rectangle...)
app.uiAction({["action"]="ACTION_RULER", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_RECT", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_ELLIPSE", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_ARROW", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_DOUBLE_ARROW", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_SPLINE", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_FILL", ["enabled"]=false});
end

function StyloBleu()
Stylo()
app.changeToolColor({["color"] = 0x0D256F, ["tool"] = "pen"});
end
function Marqueur()
-- Choisir le stylo "MARQUEUR"
app.uiAction({["action"]="ACTION_TOOL_HIGHLIGHTER"});
-- Pour choisir l'épaisseur "MEDIUM" 
app.uiAction({["action"]="ACTION_TOOL_HIGHLIGHTER_SIZE_THICK"});
-- pour choisir ligne pleine
app.uiAction({["action"]="ACTION_TOOL_LINE_STYLE_PLAIN"});
-- Pour dessin normal (pas de cercle, rectangle...)
app.uiAction({["action"]="ACTION_RULER", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_RECT", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_ELLIPSE", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_ARROW", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_DOUBLE_ARROW", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_DRAW_SPLINE", ["enabled"]=false});
app.uiAction({["action"]="ACTION_TOOL_FILL", ["enabled"]=false});
end

function MarqueurJaune()
Marqueur()
app.changeToolColor({["color"] = 0xFFFF30, ["tool"] = "highlighter"});
end
.......

**(With personnal icons in the icon directory)

I call these plugins functions with  icons ("Marqueur_Jaune.png" and "Stylo_Bleu.png") in toolbar.ini
But since the version : xournalpp-1.2.2+dev-nightly.20231020-windows, the plugin "MarqueurJaune" does not work anymore
(Others personnal plugins work, for example plugin "StyloBleu")
But all my plugins work with : xournalpp-1.2.2+dev-nightly.20231015-windows.zip**

### Expected Behaviour

Solve this problem

### Steps to Reproduce

Call MarquerJaune()

**Comment by rolandlo** [comment] 2023-10-21 18:33
This looks like a duplicate of #5192. Can you please try the installer in the PR https://github.com/xournalpp/xournalpp/pull/5253#issuecomment-1769259953 and report back if the plugin works again?

**Comment by MichelReims** [comment] 2023-10-21 18:51
No, my plugin doesn't work with the installer in the PR #5253

**Comment by MichelReims** [comment] 2023-10-21 19:11
When I click on the icon in the toolbar or on the name on the of plugin in the menu, nothing happens.

**Comment by rolandlo** [comment] 2023-10-21 19:12
I can reproduce this. Let me debug.

**Comment by MichelReims** [comment] 2023-10-21 19:15
I remark the problem is with ACTION_TOOL_HIGHLIGHTER

**Comment by MichelReims** [comment] 2023-10-21 19:16
Thank you

**Comment by MichelReims** [comment] 2023-10-21 19:52
Now I understand : when I used my plugin "MarqueurJaune", I always had the pen.
Great thanks.

**Closed** 2023-10-21 19:54 UTC
Labels: bug
