### ISSUE TITLE
I found that I can't input Chinese, I can input English

### ISSUE THREAD

**Issue by songzongquan** [xournalpp/xournalpp#3356] opened 2021-09-01 07:34 UTC
**Affects versions :**
 - OS:  Windows 10 
 - Version of Xournal++  : v1.1.0    git commit  9d1277de

**Describe the bug**
When I use any Chinese input method and use the text input function, an input box appears, but the typed text does not appear in the box when I confirm the input, but switch to English input method, and English can be input normally.

**To Reproduce**
1. Open app
2. Click the "text" tool button and click create text box on the paper in the workspace
3. Switch the Chinese input method, input any text and submit it. The text cannot be displayed in the text box,
4. Switch the English input method, enter English and submit, and the text can be presented in the text box.

**Input Logs**
Follow this tutorial https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs and attach the generated files.

**Expected behavior**

**Screenshots of Problem**

**Additional context**

**Comment by LittleHuba** [comment] 2021-09-01 11:31
Could you start Xournal++ from the console and check if there is any relevant input?

**Comment by minchai23** [comment] 2021-09-04 09:13
> Could you start Xournal++ from the console and check if there is any relevant output?

nothing output

**Comment by MedivhGO** [comment] 2021-09-11 10:22
It seems missing *.so files about gtk2.0 and gtk3.0 under the xournal++/lib/ folder

**Comment by LittleHuba** [comment] 2021-09-12 20:32
> > Could you start Xournal++ from the console and check if there is any relevant output?
> 
> nothing output

Sorry, you'll have to start it from a git bash or mingw64 console window.

**Comment by LittleHuba** [comment] 2021-09-12 20:32
> It seems missing *.so files about gtk2.0 and gtk3.0 under the xournal++/lib/ folder

You'll have to be a little more specific. What files are missing exactly?

**Comment by minchai23** [comment] 2021-09-13 01:22
> > > Could you start Xournal++ from the console and check if there is any relevant output?
> > 
> > 
> > nothing output
> 
> Sorry, you'll have to start it from a git bash or mingw64 console window.

start from git bash:
$ ./xournalpp.exe

** (com.github.xournalpp.xournalpp:7660): WARNING **: 09:19:45.519: Could not open plugin dir: «D:\Program Files\Xournal++\bin\..\plugins»

** (com.github.xournalpp.xournalpp:7660): WARNING **: 09:19:45.582: No device found. Is Xournal++ running in debugger / Eclipse...?
Probably this is the reason for not finding devices!


(com.github.xournalpp.xournalpp:7660): Pango-WARNING **: 09:19:45.895: couldn't load font "C059 Not-Rotated 8", falling back to "Sans Not-Rotated 8", expect ugly output.

**Comment by MedivhGO** [comment] 2021-09-13 03:02
![image](https://user-images.githubusercontent.com/2456440/133017623-4b3e9dba-d1dd-4d91-89b1-0643ff8d0e18.png)
![image](https://user-images.githubusercontent.com/2456440/133017642-461e267f-1bae-4be5-9b8f-a49f6268ee2c.png)

i don't know which one affect the program.

**Comment by LittleHuba** [comment] 2021-09-15 19:03
@minchai23 Did you actually install the hotfix version of 1.1.0 or another version?

**Comment by LittleHuba** [comment] 2021-09-15 19:04
@MedivhGO I don't really see your point. We are talking about a Windows 10 system here. It does not come with any *.so files.

**Comment by Technius** [comment] 2021-09-16 01:03
Duplicate of #1997.

**Closed by Technius** 2021-09-16 01:03 UTC
Labels: bug, os::windows, Input
