### ISSUE TITLE
Artifacts after exporting pdf file

### ISSUE THREAD

**Issue by fekir** [xournalpp/xournalpp#5567] opened 2024-03-16 10:24 UTC
### Operating System

Linux

### (Linux only) Distribution

Debian

### (Linux only) Desktop Environment

KDE

### (Linux Only) Display Server

X.Org

### Installation Method

Repository

### Xournal++ Version

xournalpp 1.2.2

### libgtk Version

libgtk: 3.24.41

### Bug Description

 * importing a PDF document
 * add one image or piece of text in one position
 * export as PDF document
 * compare original document and exported document with diffpdf (with compare: appearance)
 * note that (depending on the original document) some other text has slightly changed (maybe a font issue?)

### Expected Behaviour

No part of the document should be changed expect the location where the text or image has been added

### Steps to Reproduce

See bug description

Unfortunately I do not have a document to share, but I can try to create one if necessary

### Additional Context

I've noticed that in one case a document was converted from "%PDF-1.5" to "%PDF-1.7", and has been completely restructured.

I would have expected that, in order to ensure that the original content does not change, changes would only get appended, which would also ensure that the old content is preserved, and would work together which digital signatures (did not test if the program behaves differently with a signed document).

**Comment by fekir** [comment] 2024-03-16 10:28
![image](https://github.com/xournalpp/xournalpp/assets/11912465/3b2a5bcf-0dea-4eaa-859e-d3455e1f4e15)


left is the annotated document, right the original document

I added a piece of text at the beginning of the page, and this diff is at the end of the page.

note how some lines are more bold in the annotated document.


diff created with diffpdf

**Comment by rolandlo** [comment] 2024-03-16 10:55
This is basically  a duplicate of #3177. Closing therefore. See also https://github.com/xournalpp/xournalpp/issues/1873#issuecomment-1450946389

**Closed by rolandlo** 2024-03-16 10:55 UTC
Labels: bug
