### ISSUE TITLE
Hand tool broken

### ISSUE THREAD

**Issue by Krzmbrzl** [xournalpp/xournalpp#2293] opened 2020-09-30 09:25 UTC
**Affects versions** :

- OS: Linux
- (Linux only) Desktop environment: X11 (KDE Plasma)
- Which version of libgtk do you use
    -3.24.20
- Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
        1.1.0+dev
- Installation method: PPA

**Describe the bug**
Hand-tool can't move page

**To Reproduce**
1. Selecting hand tool
2. Attempt to move the page by clicking on it and then dragging the mouse (while keeping the mouse button pressed)

**Expected behavior**
Page moves

**Comment by rolandlo** [comment] 2020-09-30 09:51
I can't reproduce this on Ubuntu 20.04

**Comment by Krzmbrzl** [comment] 2020-09-30 09:56
I should note that it used to work. I have used Xournalpp before and it always worked as expected

**Comment by rolandlo** [comment] 2020-09-30 15:12
Can you please provide the error logs then?

**Comment by Krzmbrzl** [comment] 2020-10-01 14:15
If you tell me where I can find them :)

**Comment by rolandlo** [comment] 2020-10-01 17:14
It should be in `.cache/com.github.xournalpp.xournalpp/errorlogs`

**Comment by Krzmbrzl** [comment] 2020-10-01 18:22
No error log is created for this case.
I opened Xournalpp, used the hand tool (which again failed to do anything) and the closed it again.

**Comment by helq** [comment] 2020-10-04 17:22
Hi. I am experiencing the same problem. It's weird because it used to work, but around two weeks ago it stopped working. Just after a system update, I believe.



**Affects versions** :

* OS: Archlinux
* (Linux only) Desktop environment: X11 (KDE Plasma)
* Which version of libgtk do you use
    3.24.23
* Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
    1.0.18
* Installation method: Archlinux repositories

**Describe the bug**
Hand-tool can't move page. The error persists even using a stylus and custom key on the pen to activate the hand.

**To Reproduce**
Steps to reproduce the behavior:

1. Select hand tool
2. Attempt to move the page by clicking on it and then dragging the mouse (while keeping the mouse button pressed)

**Expected behavior**
Page moves

**Comment by rolandlo** [comment] 2020-10-04 19:45
@helq Can you test if the hand tool works in version 1.1.0+dev for you? See [nightly releases](https://github.com/xournalpp/xournalpp/releases/tag/nightly) for download.

**Comment by helq** [comment] 2020-10-04 23:21
So, it also didn't work with the latest version. But the message "we're moving your configuration folder" (paraphrasing) gave me the idea to delete the configuration files and see if it works anew. And it does! It does work now.

After some fiddling I found the culprit. This line:

    <property name="presentationMode" value="true"/>

should be 

    <property name="presentationMode" value="false"/>

I have no idea when I activated the presentation mode, but it obviously causes this to happen.

I suppose you can reproduce it just by changing the property to "true" and starting the application.

**Comment by Krzmbrzl** [comment] 2020-10-05 13:39
After activating presentation mode and deactivating it again, the hand tool now works as expected again. Thank you for the hint @helq! :)

With this information the way to reproduce this situation is as follows:
1. Open Xournal++
2. Enable presentation mode
3. Close Xournal++
4. Open it again
5. Now the hand tool doesn't work

To fix the problem, activate and deactivate the presentation mode in the running Xournal++ instance.

When closing Xournal++ without having the presentation mode active, the hand tool keeps working as expected.

My guess is that the presentation mode state is saved but is only partially restored (the UI doesn't seem to indicate that Xournal++ is still in presentation mode after a restart).

**Comment by rolandlo** [comment] 2020-10-05 19:50
@helq @Krzmbrzl Thank you for finding the root of this problem. It was reported in #1694. I didn't realize that it would also affect the hand tool.

**Comment by Krzmbrzl** [comment] 2020-10-06 04:31
In that case I think this issue can be closed as a duplicate

**Comment by rolandlo** [comment] 2020-10-06 18:38
Closed in favor of #1694

**Closed by rolandlo** 2020-10-06 18:38 UTC
Labels: bug, confirmed, priority: high
