### ISSUE TITLE
When Using Stylus, Things are Offset From the Stylus Tip Horizontally

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3169] opened 2021-06-19 04:57 UTC
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use: 3.24.29
 - Version of Xournal++: 1.1.0+dev git commit 99df9684
 - Installation method: windows zip from github

**Describe the bug**
When using a stylus (mouse is fine), everything in xournal is offset from the pen tip horizontally. It seems that the x-position  of what xournal thinks is the pen tip is being scaled by some factor, so the further I move to one side, the further the pen tip strays away from its actual position.

**To Reproduce**
I'm not sure how to reproduce this behaviour. It's just like this for the windows version for me.

**Expected behavior**
Pen tip should, of course, be right under the actual pen tip.

**Screenshots of Problem**
https://imgur.com/a/r7Rq8YZ

**Comment by Technius** [comment] 2021-06-20 07:41
This looks like a duplicate of #1801, unless there's a detail I'm mistaken about.

**Closed by Technius** 2021-06-20 07:41 UTC
Labels: bug

**Comment by K4LCIFER** [comment] 2021-06-21 05:13
> 
> 
> This looks like a duplicate of #1801, unless there's a detail I'm mistaken about.

Ah yeah it is. Sorry about that.
