### ISSUE TITLE
Pen lag upon starting a stroke

### ISSUE THREAD

**Issue by modicin** [xournalpp/xournalpp#1707] opened 2020-01-17 16:47 UTC
linux Elementary OS
libgtk-3-bin	3.22.30-1ubuntu4
Xournal++ 1.1.0 +dev

When using the pen input at the start of the stroke the pen output is laggy and inaccurate for about 500-700 ms from which onwards the stroke is smooth and fluent

This happens with the start of every pen stroke.
Pen input works fine with other apps with no lag so I don't think it's input side.

I've tried all new input settings (on and off) but to no avail.

**Comment by Febbe** [comment] 2020-01-18 19:20
did you compiled xournal++ yourself?
It may be, that there is still a vector used in Stroke.h. The initial size of the vector is very low (I think 10) so it will resize -> move very often at the beginning of the stroke. Can you test it with an deque? On my system  can't reproduce it.

**Comment by modicin** [comment] 2020-01-18 22:00
Thank you for replying, I'm not quite sure how to do what you asked, i am new to linux, do you have any documentation?

**Comment by Febbe** [comment] 2020-01-18 22:51
If you don't have any programming experience in c++ and if you also don't want to learn it, I would suggest I'll change that part and give you an executable.

**Comment by modicin** [comment] 2020-01-19 10:24
yes please, would i be able to have an executable?

**Comment by Maniform** [comment] 2020-01-21 10:46
Do you mean that you have tiny lines that appears when you're writting with your pen like in this screeshot ?

![70656824-177ea980-1c5b-11ea-84a9-884cdd40dc42](https://user-images.githubusercontent.com/44653826/72798489-803a4800-3c43-11ea-9573-ef5e5781200b.png)

**Comment by Maniform** [comment] 2020-01-21 10:49
If it's that, I had the same issue that I reported here [https://github.com/xournalpp/xournalpp/issues/1662](url). But the problem didn't came from Xournal++. It's comes from Linux which may be a bit new with stylus input. If you upgrade your system in the last version (including bêta), you may fix theses problems.

**Comment by modicin** [comment] 2020-01-21 21:28
Heya, it's not unfortunately, I have recorded my screen and it's visible here what the problems is. The start of the stroke is laggy and then smooths out. Then it repeats for the next stroke
https://www.dropbox.com/s/b7nc8g78n5o0gx5/xournallag1.mp4?dl=0

**Comment by Technius** [comment] 2020-01-22 01:56
This looks like a rendering bug. If you zig-zag your stylus very quickly while drawing, does the final output match what you expected to draw?

**Comment by modicin** [comment] 2020-01-22 07:11
Yes it does!! It's just not easy to draw

**Comment by tormec** [comment] 2020-01-24 09:23
Could be a tip's issue of your pen? 
https://ubuntuforums.org/showthread.php?t=2264742&highlight=

**Comment by Febbe** [comment] 2020-01-24 12:50
@tormec thanks for the link, but unfortunately this is not the problem in this ticket. Please don't mix issues.

@modicin, sorry I didn't had time the last week, but the fix is already done. I will provide it when I can get on my computer

**Comment by modicin** [comment] 2020-01-26 16:59
Thank you very much, i'll await your fix :)

**Comment by Febbe** [comment] 2020-01-28 14:57
Can you try this
[xournalpp.zip](https://github.com/xournalpp/xournalpp/files/4122972/xournalpp.zip)
unfortunately it thinks to be a shared library, maybe you have to start it from console.

**Comment by modicin** [comment] 2020-01-29 13:12
Hiya, this didn't work but i've enabled the work around for GTK touch/ scrolling and now it works fine.
Thank you for your help, you are a good person

**Comment by Febbe** [comment] 2020-03-25 01:20
Thank you for the information, then I will refactor my draft and merge it. Unfortunately I have not seen your edit till now.

**Comment by qwence** [comment] 2020-04-12 19:47
@modicin What is the "gtk touch/scrolling workaround"?
I built #1709 and the bug is still there.
Also possibly relevant info: I experience the bug in 1.0.14 but not in 1.0.12. I can try to bisect if you think that might help (though it seems you all already know what the issue is?)

**Comment by Febbe** [comment] 2020-04-12 22:05
> Also possibly relevant info: I experience the bug in 1.0.14 but not in 1.0.12. 

Thats indeed a relevant information.
> I can try to bisect if you think that might help (though it seems you all already know what the issue is?)

No we don't know directly what causes this. We can't reproduce it either. We just know it happens for (now) both of you an a dark number of people. Also it disappears when enabling the "gtk touch/scrolling workaround" and with that fix enabled.

Since we will remove it for v.1.1 because it has many other bugs and unresolvable design flaws, it would be a great help you find that commit with that regression :)

PS.: You can find that option under the Touchscreen section in the Settings. Its the last checkbox.

**Comment by qwence** [comment] 2020-04-13 03:42
The issue appears to be this: 1b69019c98
I should mention that these tests were done with the new input system; at least as of now, I don't observe this issue with the old input system.

**Comment by Febbe** [comment] 2020-04-13 16:10
For me it seems, that one of the two parents are the reason for this. Setting the cursor to be visible should not be produce such an overhead.

**Comment by qwence** [comment] 2020-04-14 05:12
As far as I can tell, 1b6901 is bad; 1b6901 with that one line removed is good. I'll admit that my testing may not be perfect, as the problem only shows up when my laptop randomly gets slow (probably some kind of throttling, haven't figured it out yet). But I've tried each of these multiple times, and I've seen lag in the first one but not the second one.

One thing that seems to make the problem more noticeable is drawing a lot of parallel lines as fast as possible.

**Comment by Technius** [comment] 2020-04-14 05:30
The code has changed quite a bit since `1.0.14`: on `master` branch, that line has been moved to `MouseInputHandler` and `StylusInputHandler`. Can you try uncommenting the corresponding line in `StylusInputHandler` (search for it) and see if it causes lag? This will make it easier for us to narrow down the problem.

**Comment by openyost** [comment] 2020-04-16 18:50
I can confirm the lag using a Wacom pen small and the nightly build for ubuntu (19.10). Enabling the GTK Touch Workaround helped shorten the lag (and made it so that my touchscreen worked), but the lag is still slightly there.

**Comment by qwence** [comment] 2020-04-18 02:51
> As far as I can tell, 1b6901 is bad; 1b6901 with that one line removed is good.
I'm no longer able to reproduce this claim; I think I must have made a mistake. (And I did check that current master with the change you suggested is still bad.)

I bisected again, and got the following:

    There are only 'skip'ped commits left to test.
    The first bad commit could be any of:
    286ce5b8b92339d4754b64c8d8422362babfa930
    c0ac8f541207d6b6225d17bd8ee0caa3deb58aa2

Does that make any more sense? (I get compile errors in 286ce5b.)

**Comment by Febbe** [comment] 2020-04-19 02:09
> I'm no longer able to reproduce this claim; I think I must have made a mistake. (And I did check that current master with the change you suggested is still bad.)

The thing is, you really have to delete your binary/compile folder every time you change the commit. Because either the cmake cache is a little bit corrupted or the incremental build does not do what he should. Therefore it can happen, that a corrupted binary is linked even the commit was a good one and it seems like that commit is the evil one.

>  There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 286ce5b8b92339d4754b64c8d8422362babfa930
> c0ac8f541207d6b6225d17bd8ee0caa3deb58aa2

Ill take a look into those.

**Comment by qwence** [comment] 2020-04-19 05:54
@Febbe I got it to compile after removing the function starting in line 449 of src/gui/Layout.cpp.
I found that 286ce5b is bad.

**Comment by Febbe** [comment] 2020-04-19 10:30
Thank you! Then the hard search which funktion is the problem begins. It may be the easiest way just to use a profiler

**Comment by qwence** [comment] 2020-04-24 17:15
I tried running valgrind as you suggested. Here is output for 7349762 (good) and 286ce5b (bad).
https://gist.github.com/qwence/45102bb9e95a90245f15270b2ad6e914
https://gist.github.com/qwence/2d96b0c109e3ea6092398bae858e9796
https://gist.github.com/qwence/b74d71441aff4eceee542bb9924f24f1
https://gist.github.com/qwence/b012f85617fa2a9ff97337b3c7e9f11b

I did two tests each-- "long" was writing for a couple minutes (both good and bad developed unusable degrees of lag during this time due to the overhead of valgrind); "short" was writing only about a line.

Any ideas? I'm happy to do more tests, but I'm not a developer (just some internet rando who writes a little python once in a while) so I don't know what to do with these.

**Comment by Duska007** [comment] 2020-11-07 15:16
I have had the same problem, but it disappeared when I have stopped to use the Right rand note-taking toolbar and opt for Xournal++ toolbar (View>Toolbars>Xournal++

**Comment by aryajur** [comment] 2020-12-03 04:22
Just started using Xournalapp on windows and I see the same problem. My version is 1.0.19. Was this already fixed.

**Comment by sh-cau** [comment] 2021-05-04 11:36
I'm experiencing the same issue on Ubuntu 18.04.5, Xournalpp v1.0.20 and a Wacom Intuos M. None of the ideas worked for me so far.

**Comment by rolandlo** [comment] 2021-05-04 11:46
@sh-cau Does [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) work for you? You can simply try out the AppImage (no installation required).

**Comment by sh-cau** [comment] 2021-05-04 14:05
> @sh-cau Does [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) work for you? You can simply try out the AppImage (no installation required).

Thank you, this works fine!

**Comment by shubhampaul** [comment] 2021-08-29 11:15
> @sh-cau Does [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) work for you? You can simply try out the AppImage (no installation required).

I was facing the same issue but this built solves it. Thanks.

**Comment by Technius** [comment] 2021-08-29 18:47
It appears that this bug has been fixed in 1.1.0, so I'm closing this issue.

**Comment by LittleHuba** [comment] 2021-10-17 14:46
This might be fixed by #3480

**Closed** 2021-11-13 18:56 UTC
Labels: bug, rendering, priority::medium

**Comment by bhennion** [comment] 2021-11-13 19:03
@varadpatil This issue should have been fixed by recent work (to be included in 1.2 as some point).
You can try out the next nightly build (wait until tomorrow at least). They are available on [this page](https://github.com/xournalpp/xournalpp/releases/tag/nightly).
