### ISSUE TITLE
make install with BUILD_POPPLER does not work due to the lack of libpoppler.so.72

### ISSUE THREAD

**Issue by shuhaowu** [xournalpp/xournalpp#243] opened 2017-11-24 15:58 UTC
Calling make install for a build that has BUILD_POPPLER=ON does not work as it does not install libpoppler.so.72.

Now if it does install that file, it probably should not be called that or be at the same path, but rather be called a different file so it doesn't clash with a system version if it is already installed.

**Comment by andreasb242** [comment] 2018-11-11 20:30
Confirmed. This should be fixed or there should be a workaround. Executing in the build folder does work for me at the moment.

**Comment by andreasb242** [comment] 2018-11-13 18:54
Duplicate of #262

**Closed by andreasb242** 2018-11-13 18:54 UTC
Labels: bug, good first issue
