### ISSUE TITLE
Select text when annotating PDF

### ISSUE THREAD

**Issue by asanakoy** [xournalpp/xournalpp#1948] opened 2020-05-09 01:21 UTC
**Is your feature request related to a problem? Please describe.**
 I'm a little bit frustrated that I cannot simply select a piec of text in he pdf which I'm annotating.

Is it possible to add a feature to be able to interact with text while annotating?
For example, sometime I wat to select something and copy-paste in me textbox.

**Comment by Technius** [comment] 2020-05-10 21:20
Duplicate of #1745.

**Closed by Technius** 2020-05-10 21:20 UTC
Labels: enhancement
