### ISSUE TITLE
Text objects shifted when exporting PDF

### ISSUE THREAD

**Issue by Photon89** [xournalpp/xournalpp#2933] opened 2021-03-10 19:27 UTC
**Affects versions :**
 - OS: Manjaro Linux
 - (Linux only) Desktop environment: X11 (Xfce)
 - Which version of libgtk do you use: 3.24.24
 - Version of Xournal++: 1.1.0+dev
 - Installation method: AUR package (built from latest git)

**Describe the bug**
When exporting a .xopp file to PDF text fields are moved such that their relative position to the page and other objects changes.

**To Reproduce**
1. Write some text.
2. Make some strokes (say, underline the text with the pen tool).
3. Export the file as PDF
4. Observe the bug.

**Expected behavior**
The text objects should not be shifted

**Screenshots of Problem**
See attached .xopp file and its PDF export (the problem is best visible on the top of the second page).

**Additional context**

[xournal issue.zip](https://github.com/xournalpp/xournalpp/files/6118360/xournal.issue.zip)

**Comment by Photon89** [comment] 2021-03-10 19:33
Possibly, they are scaled and not shifted. Actually, most probably they are scaled, sorry for the confusing description!

**Comment by Technius** [comment] 2021-03-10 19:36
This is a duplicate #1390, but I thought it was fixed in #2182.

**Comment by rolandlo** [comment] 2021-03-10 19:36
duplicate of  #2104
Note that there is a fix in #2182, but sadly it can't be merged because of an apparent [bug in pango](https://gitlab.gnome.org/GNOME/pango/-/issues/499) with empty lines. I never got any answer by the Pango team on my bug report. Somehow Inkscape (which doesn't use `pango_layout_set_line_spacing` has a workaround, but the code is complicated.

**Comment by Photon89** [comment] 2021-03-10 19:39
Oh, sorry, my search query didn't show those reports! Then I guess, this one can be closed and I subscribe to updates from the other bug and PR. Thanks for the quick reply!

**Closed as completed** 2021-03-10 19:40 UTC
Labels: bug
