### ISSUE TITLE
Default pen is ignored

### ISSUE THREAD

**Issue by thecandyman** [xournalpp/xournalpp#2428] opened 2020-11-20 17:25 UTC
**Affects versions:**
 - OS: Ubuntu 20.04 (Gnome Desktop)
 - libgtk: 3.24.20
- Xournal++ 1.1.0+dev 
 - Installation method: PPA (http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu)

**Bug description:**
The default pen (set in "Defaults" section in "Preferences") is not used by Xournal++.

**Comment by rolandlo** [comment] 2020-11-21 22:36
This is a duplicate of  #2303 and should get fixed in #2339

**Closed by rolandlo** 2020-11-21 22:36 UTC
Labels: bug
