### ISSUE TITLE
Pen (drwaing tablet) drawing position does not match actual position (on resolutions other than 1920x1080)

### ISSUE THREAD

**Issue by WakanaYuki** [xournalpp/xournalpp#2915] opened 2021-03-07 22:33 UTC
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use
     - does not display idk why
 - Version of Xournal++: 1.0.19
 - Installation method: official release

**Describe the bug**
This bug happens on multiple Windows PC's of mine (not on my linux laptop, though its 1920x1080). So everytime I use my xournal++ with my wacom intuos M with a monitor that is bigger than 1920x1080 the pen drawing is completly off. The pen draws, erases, etc. on a parallel position many pixels away, roughly equivelant to the formula: 2560(monitor size) - 1920 = 640px
This bug is extremely annoying and I havent found any work around yet, besides using a 1920x1080 display. Even resizing the window to roughly fit does not help. This bug for me has occured on an 2560x1440 display but even on a 1660x1080 display.

**To Reproduce**
1. Plug in Wacom Intuos M Tablet
2. Start Xournal++ (on a monitor with a higher resolution than 1920x1080) with the tablet (idk, xournal++ often does not detect it on the first start, but that's okay imo)
3. Start writing something with the tablet and it will write in the wrong position

**Expected behavior**
That the drawing is at the position the cursor is, which it is not. It is displaced many pixels next to it, which makes writing or drawing, practiaclly impossible.

**Screenshots of Problem**
Here a gif of the problem:
![2021-03-07-23-29-47](https://user-images.githubusercontent.com/36765765/110257281-75548b00-7f9d-11eb-8b6f-d52e2695253c.gif)

**Comment by rolandlo** [comment] 2021-03-08 05:13
duplicate of #1801

**Closed by rolandlo** 2021-03-08 05:13 UTC
Labels: bug
