### ISSUE TITLE
AppImage cannot run on Pop!_OS

### ISSUE THREAD

**Issue by github2099** [xournalpp/xournalpp#3237] opened 2021-07-17 06:57 UTC
**Affects versions :**
 - OS: Pop!_OS
 - (Linux only) Desktop environment: Gnome
 - Which version of libgtk do you use: Don't know
 - Version of Xournal++: 1.0.20, 1.0.19
 - Installation method: AppImage

**Describe the bug**
Download the AppImage and run it, however, it's cannot open.

**Terminal**
$ chmod a+x xournalpp-1.0.20-x86_64.AppImage
$ ./xournalpp-1.0.20-x86_64.AppImage

/tmp/.mount_xournayQ0u4B/usr/bin/xournalpp: /tmp/.mount_xournayQ0u4B/usr/lib/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
/tmp/.mount_xournayQ0u4B/usr/bin/xournalpp: /tmp/.mount_xournayQ0u4B/usr/lib/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libmount.so.1)

** (com.github.xournalpp.xournalpp:4439): WARNING **: 02:50:23.334: Failed to load "colornames.ini" (/home/user/.xournalpp//colornames.ini): No such file or directory

ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib setup.c:547:(add_elem) Cannot obtain info for CTL elem (MIXER,'IEC958 Playback Default',0,0,0): No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

** (com.github.xournalpp.xournalpp:4439): WARNING **: 02:50:23.988: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:4439): WARNING **: 02:50:24.007: [Crash Handler] Wrote crash log to: /home/user/.xournalpp/errorlogs/errorlog.20210717-025024.log

** (com.github.xournalpp.xournalpp:4439): WARNING **: 02:50:24.512: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:4439): WARNING **: 02:50:24.513: Successfully saved document to "/home/user/.xournalpp//emergencysave.xopp"

**Comment by rolandlo** [comment] 2021-07-17 07:05
Duplicate of #2567 . Please upgrade to [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)

**Closed by rolandlo** 2021-07-17 07:05 UTC
Labels: bug
