### ISSUE TITLE
xournal++ crashes while scrolling with graphic tablet

### ISSUE THREAD

**Issue by CryptKid** [xournalpp/xournalpp#2524] opened 2020-12-10 13:05 UTC
**Affects versions :**
 - OS: Linux (Arch Linux
 - (Linux only) Desktop environment: X11 (i3wm)
 - Which version of libgtk do you use
     - 3.24.24
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.0.19
 - Installation method: offical release: community/xournalpp 1.0.19-1

**Describe the bug**
I  use a graphic tablet for writing and have mapped one of the pens buttons to the "Hand" tool so i can scroll with the tablet. Here is a screenshot of my settings:
![image](https://user-images.githubusercontent.com/30263141/101774420-5f464400-3aee-11eb-9de5-93eb7a467c72.png)

Scrolling in general works fine that way but as soon as the mouse no longer hovers abouve the page but over one of the menu bars (that happens when you want to scroll further than one screens worth of page), xournal++ instantly crashes.
It is worth noting that the crash does not occur if i don't use the pen button but select the "hand" to by mouse (even if i use it with the tablet) 

**To Reproduce**
Use a graphic tablet (I only have a Wacom Intuos S (CTL-4100) so i couldn't test that on any other tablet) and set the same shortcut. (See screenshot)
Try to scroll and if you move the cursor to far up or down (or even to the side if zoomed in enough)
xournal++ crashes

**Expected behavior**
The page should move regardless of where the cursor is as long as if started over the page (same behavior as if the hand was selected a different way) 

**Screenshots of Problem**
None, it simply crashes without anything visible, but here are the logs:

To stdout/stderr:
On program startup (probably audio related and not relevant, i will include it nevertheless)
```
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 933
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
```
As soon as xournal crashes:
```
** (com.github.xournalpp.xournalpp:26033): WARNING **: 13:58:52.867: Input for the same device started twice!

** (com.github.xournalpp.xournalpp:26033): WARNING **: 13:59:05.248: [Crash Handler] Crashed with signal 11

** (com.github.xournalpp.xournalpp:26033): WARNING **: 13:59:05.249: [Crash Handler] Wrote crash log to: /home/<REDACTED>/.xournalpp/errorlogs/errorlog.20201210-135905.log

** (com.github.xournalpp.xournalpp:26033): WARNING **: 13:59:05.435: Trying to emergency save the current open document…

** (com.github.xournalpp.xournalpp:26033): WARNING **: 13:59:05.436: Successfully saved document to "/home/<REDACTED>/.xournalpp//emergencysave.xopp"
```

**Additional context**
Error log file contains:
```
Date: Thu Dec 10 13:59:05 2020
Error: signal 11
[bt]: (0) xournalpp(+0x1d95c2) [0x557d37ab35c2]
[bt]: (1) /usr/lib/libc.so.6(+0x3d6a0) [0x7f82ed4dd6a0]
[bt]: (2) xournalpp(_ZN17NewGtkInputDevice10getXournalEv+0x1) [0x557d37a512f1]
[bt]: (3) xournalpp(+0x175721) [0x557d37a4f721]
[bt]: (4) xournalpp(+0x1e068e) [0x557d37aba68e]
[bt]: (5) /usr/lib/libgdk-3.so.0(+0x2d8ac) [0x7f82ee0c18ac]
[bt]: (6) /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x184) [0x7f82ee98d8f4]
[bt]: (7) /usr/lib/libglib-2.0.so.0(+0xa6821) [0x7f82ee9e1821]
[bt]: (8) /usr/lib/libglib-2.0.so.0(g_main_loop_run+0x83) [0x7f82ee98ce43]
[bt]: (9) /usr/lib/libgtk-3.so.0(gtk_main+0x9f) [0x7f82ee37422f]
[bt]: (10) xournalpp(_ZN11XournalMain3runEiPPc+0xbf1) [0x557d3799fbe1]
[bt]: (11) xournalpp(main+0x37) [0x557d37973147]
[bt]: (12) /usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7f82ed4c8152]
[bt]: (13) xournalpp(_start+0x2e) [0x557d379736de]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0x1d986b) [0x557d37ab386b]
??:0
[bt] #2 /usr/lib/libc.so.6(+0x3d6a0) [0x7f82ed4dd6a0]
??:0
[bt] #3 xournalpp(_ZN17NewGtkInputDevice10getXournalEv+0x1) [0x557d37a512f1]
??:0
[bt] #4 xournalpp(+0x175721) [0x557d37a4f721]
??:0
[bt] #5 xournalpp(+0x1e068e) [0x557d37aba68e]
??:0
[bt] #6 /usr/lib/libgdk-3.so.0(+0x2d8ac) [0x7f82ee0c18ac]
??:0
[bt] #7 /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x184) [0x7f82ee98d8f4]
??:0
[bt] #8 /usr/lib/libglib-2.0.so.0(+0xa6821) [0x7f82ee9e1821]
??:0
[bt] #9 /usr/lib/libglib-2.0.so.0(g_main_loop_run+0x83) [0x7f82ee98ce43]
??:0
[bt] #10 /usr/lib/libgtk-3.so.0(gtk_main+0x9f) [0x7f82ee37422f]
??:0
[bt] #11 xournalpp(_ZN11XournalMain3runEiPPc+0xbf1) [0x557d3799fbe1]
??:0
[bt] #12 xournalpp(main+0x37) [0x557d37973147]
??:0
[bt] #13 /usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7f82ed4c8152]
??:0
[bt] #14 xournalpp(_start+0x2e) [0x557d379736de]
??:0
```
Thanks for your awesome project anyway

**Comment by rolandlo** [comment] 2020-12-10 15:16
Do you have the new input system enabled? If not, try that!

**Comment by CryptKid** [comment] 2020-12-10 18:45
Seems to help, thank you!

**Comment by rolandlo** [comment] 2020-12-10 20:58
I will close this issue then, since it is a duplicate of #1960

**Closed by rolandlo** 2020-12-10 20:58 UTC
Labels: bug
