### ISSUE TITLE
Line spacing gets smaller during export to PDF

### ISSUE THREAD

**Issue by E-Wal** [xournalpp/xournalpp#2073] opened 2020-06-17 15:18 UTC
**Affects versions**
 - OS: Linux (Ubuntu 18.04)
 - Desktop environment: Ubuntu Standard [Gnome-Wayland]
 - Version of libgtk: `xournalpp --version` crashed with unknown option
 - Version of Xournal++: 1.0.16, git commit 07cb970f
 - Installation method: snap store

**Describe the bug**
When exporting a document with textfield, the text field in the PDF is vertically smaller than it has been in Xournal++, whereas highlighting stays at it's place. That courses problems in long textfields: Words further down in the textfield seem to be highlighted in Xournal++, but are not highlighted in the exported PDF - instead the word one or two lines further down is highlighted...

**To Reproduce**
1. Write three words in a textfield and bring one of them (through blanklines) to the middle of the page and the last one down to the bottom.
2. Highlight each word.
3. Export to PDF.
4. See the difference: The highlighting stays on it's place, whereas the second and especially the third word appear further above.

**Expected behavior**
Highlighted words should be still highlighted after exporting to PDF.

**Screenshots of Problem**
![Auswahl_355](https://user-images.githubusercontent.com/66143769/84916509-7582c280-b0be-11ea-8165-7a91a989a816.png)
![Auswahl_356](https://user-images.githubusercontent.com/66143769/84916513-761b5900-b0be-11ea-8071-fcaad8593736.png)

**Comment by Technius** [comment] 2020-06-17 21:05
Duplicate of #1390.

**Closed by Technius** 2020-06-17 21:05 UTC
Labels: bug
