### ISSUE TITLE
Missing autosave for unsaved document

### ISSUE THREAD

**Issue by TI-Admin** [xournalpp/xournalpp#1142] opened 2019-05-13 09:43 UTC
**Affects versions :**
 - OS: archlinux
 - Version of Xournal++ 1.0.11 installed with AUR package xournalpp-git.

**Describe the bug**
If I start xournalpp and have an unsaved document, there is no autosave in ~/.xournalpp/autosave though autosave is activated and set to 1 minute.

**To Reproduce**
1. Start xournalpp 
2. Look for autosave of unsaved document in ~/.xournalpp/autosave

**Expected behavior**
An autosave file in ~/.xournalpp/autosave after 1 minute.

**Additional context**
If I save the file afterwards there will be an autosave file in the folder the file was saved to.

**Comment by Technius** [comment] 2019-05-13 17:30
Looks like when I was fixing a bug a week ago I made a small mistake.

The issue is that the autosave is being saved as `<number><number>.xopp` instead of `<number>.<filename>.xopp`.

I'll be fixing this shortly. If you're missing an autosave in the mean time, try loading those files.

**Comment by Technius** [comment] 2019-05-13 17:44
If you run xournalpp from the console, do you get the autosaving message?

**Comment by TI-Admin** [comment] 2019-05-14 09:30
1. I'm talking about a fresh, unsaved document
2. No, the autosave is not in ~/.xournalpp/autosave which is empty
3. Yes, there is an autosave message.

**Comment by Technius** [comment] 2019-05-14 18:52
Can you check if https://github.com/Technius/xournalpp/tree/issue-1142 fixes the issue? You can compile it with

```
git clone https://github.com/Technius/xournalpp -b issue-1142
cd xournalpp
mkdir build && cd build
cmake ..
cmake --build .
```

Then run `src/xournalpp` in a terminal. I've added some messages that indicate where the autosave files are located, so please check for those.

**Comment by TI-Admin** [comment] 2019-05-15 06:29
The 

> Can you check if https://github.com/Technius/xournalpp/tree/issue-1142 fixes the issue? You can compile it with
> 
> ```
> git clone https://github.com/Technius/xournalpp -b issue-1142
> cd xournalpp
> mkdir build && cd build
> cmake ..
> cmake --build .
> ```
> 
> Then run `src/xournalpp` in a terminal. I've added some messages that indicate where the autosave files are located, so please check for those.

This version does work as expected and fixes the issue.

**Comment by TI-Admin** [comment] 2019-05-15 06:45
Question: I have an autosave from an unsaved document in  ~/.xournalpp/autosave.
I save this document and a new autosave is created in the folder were I did save the document. The old, first autosave <pid>.old.autosave.xopp still remains in ~/.xournalpp/autosave even after I close the programm. Is this the expected behavior? Shouldn't it be deleted as soon as the newer autosave is created?

**Comment by Technius** [comment] 2019-05-15 07:34
To generate an autosave, xournalpp first backs up any existing autosave file to `~/.xournalpp/autosave` (overwriting any autosave with the same name in that folder) and then creates a new autosave. This is so that if xournalpp crashes during an autosave, it will always have a backup it can load.

There's really no good location to place autosaves of fresh unsaved documents, so we just default to putting their autosave files in `~/.xournalpp/autosave`. The `pid.old.autosave.xopp` is really just the backup of the autosave. I don't want to cause any unwelcome surprises by deleting them, so my fix just leaves them as is. But there's definitely room to improve on this.

**Comment by TI-Admin** [comment] 2019-05-15 07:39
But I don't need the old autosave of a fresh document if I saved that same document afterwards and a working autosave of that saved document does exist. At that point the old autosave is no longer needed.

**Comment by Technius** [comment] 2019-05-15 07:53
That's true, but we need a better solution because the folder is going to get cluttered up anyways by regular use (I've already accumulated 20 MB of garbage in the autosave directory in the past few weeks from working on various documents!). I'm thinking that a periodic autosave cleanup feature will fit the bill here, but it's out of scope of this current issue. I'll be opening another issue in which we can discuss this in more detail.

**Closed** 2019-05-21 05:22 UTC
Labels: PR available, bug
