### ISSUE TITLE
Replace PDF Background

### ISSUE THREAD

**Issue by giancarlocp** [xournalpp/xournalpp#1527] opened 2019-10-08 16:48 UTC
**Is your feature request related to a problem?**
I can't replace the **pdf background** the menu:
`Journal > Configure Template Page > load from file` is not working.
I can replace the **pdf background** with a trick:
`close all > rename the original pdf background file > open > it detect the missing file`
I choose a different file and it is done.

But the final goal couldn't be reach.
I just remove some page in the original pdf, and to work with the new pdf I can't just remove the page, I am getting page-shifted/misaligned annotations.

**Describe the solution you'd like**
Is there a way to import annotations?

**PD**: I have noticed a lag loading big pdf.
Is it a way to do partial load to open faster?

**Comment by LittleHuba** [comment] 2019-10-08 20:15
Duplicate of #889 

> Is there a way to import annotations?

Copy-pasting between two instances of X++ should work.

> PD: I have noticed a lag loading big pdf.
Is it a way to do partial load to open faster?

Currently this is not supported, but we are working on a new file format that will provide this functionality.

**Closed by LittleHuba** 2019-10-08 20:15 UTC
Labels: enhancement
