### ISSUE TITLE
Resizing window jumps to another page

### ISSUE THREAD

**Issue by otoomet** [xournalpp/xournalpp#2160] opened 2020-08-13 05:40 UTC
**Affects versions :**
 - OS: Ubuntu 20.04 
 - (Linux only) Desktop environment: X11, i3 window manager
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.1.0+dev (Aug 5th 2020)
 - Installation method: ppa ( http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu focal/main amd64 Packages)

**Describe the bug**

When you open a multipage document, and "zoom to fit the screen", the document jumps from one page to another rather far away when you resize the window (e.g. shift to full screen).  For instance, it may jump b/w pages 4 and 23.  When leaving full screen, it jumps to another page again, often to the same page from where it came from.

**To Reproduce**
1. open a multi-page document
2. set the window size to a half of screen
2. click the "zoom fit to screen" button, so the document has optimal width
3. press F11

**Expected behavior**
the document remains centered on the same page where it was before full screen.

**Additional context**
I suspect it is related to #1795 pack of issues.

**Comment by rolandlo** [comment] 2020-08-13 06:40
This is basically a duplicate of issue  #2054.

**Closed by rolandlo** 2020-08-13 06:40 UTC
Labels: bug
