### ISSUE TITLE
(Add/Edit tex) button

### ISSUE THREAD

**Issue by antidote3** [xournalpp/xournalpp#4447] opened 2022-11-25 17:27 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [Windows]
 - Which version of libgtk do you use: 3.24.34
   
 - Version of Xournal++: [1.1.2]

 - Installation method: [official release]

**Describe the bug**
when i click on the (Add/Edit tex) icon the whole application closes

**To Reproduce**
only one step by clicking on the (Add/Edit tex) button and the entire application will crash 

**Expected behavior**
is to edit text by clicking on the (Add/Edit tex) button

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment] 2022-11-25 18:07
Duplicate of #4370. This will be fixed in the upcoming 1.1.3 release. Note that you need a TeX generator (like pdflatex) accessible via your PATH environment variable.

**Closed by rolandlo** 2022-11-25 18:07 UTC
Labels: bug
