### ISSUE TITLE
sidebar page highlighting should correpond to page in the main view

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#1499] opened 2019-09-25 19:29 UTC
**Affects versions :**
using:
linux (ubuntu 18.04)
latest master

**Describe the bug**
Currently the main document view does not influence the highlighted page in the sidebar. A common use case for me is say highlighting something on a page, then copying it. Then scrolling to the next page, or maybe two pages down say, and doing a 'paste'. The material gets pasted to the old page where it was copied from and not to the currently visible one (unless one taps the screen). 

**To Reproduce**
1. Step 1 copy something form a given page
2. Step 2 scroll down two pages
3. Step 3 paste
now the item got pasted on the same page it was originally copied from and not the page you see. 

**Expected behavior**
When moving around the main document the highlighted page in the sidebar should follow the page visible in the main document at all times given time. Clicking on the page in the sidebar should take the user to that page in the main view (as it does currently). 

**Additional context**
The way to overcome this now, is to basically do a 'tap' on the screen somewhere in on the page where the contents are to be pasted to highlight the current page. But this is not optimal, because it leaves a mark, which one has to erase. 

thanks for all your work on xournalpp, devs - it's extremely useful to me.

**Comment by Technius** [comment] 2019-09-25 21:37
Duplicate of #1184.

**Closed by Technius** 2019-09-25 21:37 UTC
Labels: bug
