### ISSUE TITLE
Flashcards with collapsible bloc

### ISSUE THREAD

**Issue by slimhk45** [xournalpp/xournalpp#4151] opened 2022-07-14 12:59 UTC
Implement collapsible bloc where the parent bloc is the front and the nest bloc is the answer.

Each bloc is be marked with a tag (for instance #flashcard) to be indexed by a flashcard player that will crawl the file to find all flashcards. The flashcard player allow you to play a flashcard from that deck, and store the score you give (easy, good, difficult) as a tag too for later reuse according to the SuperMemo algorithm.

**Comment by bhennion** [comment] 2022-07-21 17:53
I don't quite understand the "player" idea. Could you elaborate?

As for collapsible blocs, I guess this is related to (or a duplicate of) #3684.

**Comment by slimhk45** [comment] 2022-07-23 10:52
The flashcard reader will simply take a random flashcard in your notebook according to the [SM-2 algorithm](https://en.wikipedia.org/wiki/SuperMemo#Description_of_SM-2_algorithm).

Like the software Anki do.

**Comment by rolandlo** [comment] 2022-07-23 12:39
I don't see why that should be implemented in Xournal++. It's too far from the purpose of a note-taking app.

**Comment by bhennion** [comment] 2022-07-23 12:48
> I don't see why that should be implemented in Xournal++. It's too far from the purpose of a note-taking app.

I second that. Closing as won't-do.

**Closed by bhennion** 2022-07-23 12:48 UTC
Labels: enhancement

**Comment by slimhk45** [comment] 2022-07-24 22:47
Because making flashcards is part of note-taking.
