### ISSUE TITLE
Unable to open URL's when opening a PDF

### ISSUE THREAD

**Issue by triptronics** [xournalpp/xournalpp#1592] opened 2019-11-06 18:55 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux
 - In case of linux, which desktop environment X11
 - Which version of libgtk do you use.
 - Version of Xournal++ [e.g. 1.0.10, specific commit, specific branch]

**Describe the bug**
There is no way to open links when annotating a PDF. It looks like a link on the page but you can't click it, not even with the hand tool.

**To Reproduce**
1. Open a PDF with links.
2. Try to open the link.

**Expected behavior**
The link opens in the default browser if I hit ctrl and click the link.
**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Maybe would be nice to also allow the ability to insert links?

**Comment by Technius** [comment] 2020-04-17 22:12
This is actually a duplicate of #1027.

**Closed by Technius** 2020-04-17 22:12 UTC
Labels: difficulty:medium, enhancement, priority: medium
