### ISSUE TITLE
Crash on Fedora 38 KDE

### ISSUE THREAD

**Issue by esamson** [xournalpp/xournalpp#5168] opened 2023-09-22 02:21 UTC
I was just doodling, exploring the different pen tools and options. App crashed. Next launch told me to share a bug report with you, so here we are.

* Fedora Linux 38
* KDE Plasma 5.27.8
* Kernel 6.4.15-200.fc38.x86_64
* X11

[errorlog.20230922-101317.log](https://github.com/xournalpp/xournalpp/files/12696026/errorlog.20230922-101317.log)

**Comment by bhennion** [comment] 2023-09-24 07:18
Thanks for reporting. Duplicate of #5087

**Closed by bhennion** 2023-09-24 07:18 UTC
