### ISSUE TITLE
Segfault Crash with Crash report

### ISSUE THREAD

**Issue by Popaulol** [xournalpp/xournalpp#5101] opened 2023-08-28 20:35 UTC
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

Wayland

### Installation Method

pacman xournalpp package

### Xournal++ Version

xournalpp 1.2.1 (b48932a2)

### libgtk Version

libgtk: 3.24.38

### Bug Description

Crash when trying to continue editing (hand drawing using a stylus), after doing a "save as operation"

### Expected Behaviour

Xournal shouldn't crash

### Steps to Reproduce

Not aplicable as this was a one time occurance i that i was unable to reproduce, even after repeating the same actions multiple times.

### Additional Context
```
Date: Mon Aug 28 08:58:21 2023
Error: signal 11
Xournal++ version 1.2.1
Git commit b48932a2 from srcdest/makepkg
Gtk version 3.24.38

[bt]: (0) /usr/bin/xournalpp(+0xbefa5) [0x556fd48fffa5]
[bt]: (1) /usr/lib/libc.so.6(+0x3e710) [0x7fe0c883e710]
[bt]: (2) /usr/lib/libgtk-3.so.0(+0x2773e7) [0x7fe0c9c773e7]
[bt]: (3) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
[bt]: (4) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
[bt]: (5) /usr/lib/libgtk-3.so.0(+0x19d460) [0x7fe0c9b9d460]
[bt]: (6) /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x97) [0x7fe0c92c24f7]
[bt]: (7) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
[bt]: (8) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
[bt]: (9) /usr/lib/libgtk-3.so.0(+0x19df68) [0x7fe0c9b9df68]
[bt]: (10) /usr/lib/libgobject-2.0.so.0(g_closure_invoke+0x140) [0x7fe0c92be6c0]
[bt]: (11) /usr/lib/libgobject-2.0.so.0(+0x42938) [0x7fe0c92ec938]
[bt]: (12) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x10e7) [0x7fe0c92ddaa7]
[bt]: (13) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
[bt]: (14) /usr/lib/libgtk-3.so.0(+0x1ee20e) [0x7fe0c9bee20e]
[bt]: (15) /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
[bt]: (16) /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
[bt]: (17) /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
[bt]: (18) /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
[bt]: (19) /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
[bt]: (20) /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
[bt]: (21) /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
[bt]: (22) /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
[bt]: (23) /usr/lib/libgtk-3.so.0(+0x222135) [0x7fe0c9c22135]
[bt]: (24) /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
[bt]: (25) /usr/lib/libgtk-3.so.0(+0x35f1aa) [0x7fe0c9d5f1aa]
[bt]: (26) /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
[bt]: (27) /usr/lib/libgtk-3.so.0(+0x1ee392) [0x7fe0c9bee392]
[bt]: (28) /usr/lib/libgtk-3.so.0(+0x257909) [0x7fe0c9c57909]
[bt]: (29) /usr/lib/libgtk-3.so.0(+0x86965) [0x7fe0c9a86965]
[bt]: (30) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
[bt]: (31) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
[bt]: (32) /usr/lib/libgtk-3.so.0(+0x1a5647) [0x7fe0c9ba5647]
[bt]: (33) /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x97) [0x7fe0c92c24f7]
[bt]: (34) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
[bt]: (35) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
[bt]: (36) /usr/lib/libgtk-3.so.0(+0x19df07) [0x7fe0c9b9df07]
[bt]: (37) /usr/lib/libgtk-3.so.0(+0x1a5142) [0x7fe0c9ba5142]
[bt]: (38) /usr/lib/libgtk-3.so.0(+0x1a5b13) [0x7fe0c9ba5b13]
[bt]: (39) /usr/lib/libgtk-3.so.0(gtk_event_controller_handle_event+0x74) [0x7fe0c9b610f4]
[bt]: (40) /usr/lib/libgtk-3.so.0(+0x345967) [0x7fe0c9d45967]
[bt]: (41) /usr/lib/libgtk-3.so.0(+0x345cda) [0x7fe0c9d45cda]
[bt]: (42) /usr/lib/libgtk-3.so.0(+0x85039) [0x7fe0c9a85039]
[bt]: (43) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
[bt]: (44) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
[bt]: (45) /usr/lib/libgtk-3.so.0(+0x3546e5) [0x7fe0c9d546e5]
[bt]: (46) /usr/lib/libgtk-3.so.0(+0x1ee91b) [0x7fe0c9bee91b]
[bt]: (47) /usr/lib/libgtk-3.so.0(gtk_main_do_event+0x9b7) [0x7fe0c9bef447]
[bt]: (48) /usr/lib/libgdk-3.so.0(+0x33b87) [0x7fe0c993ab87]
[bt]: (49) /usr/lib/libgdk-3.so.0(+0x6b848) [0x7fe0c9972848]
[bt]: (50) /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x141) [0x7fe0c979ea31]
[bt]: (51) /usr/lib/libglib-2.0.so.0(+0xb7cc9) [0x7fe0c97fbcc9]
[bt]: (52) /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x7fe0c979c0e2]
[bt]: (53) /usr/lib/libgio-2.0.so.0(g_application_run+0x176) [0x7fe0c942fed6]
[bt]: (54) /usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x656) [0x556fd48f9ee6]
[bt]: (55) /usr/lib/libc.so.6(+0x27cd0) [0x7fe0c8827cd0]
[bt]: (56) /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fe0c8827d8a]
[bt]: (57) /usr/bin/xournalpp(_start+0x25) [0x556fd48f7775]


Try to get a better stracktrace...
[bt] #1 /usr/bin/xournalpp(+0xbf57f) [0x556fd490057f]
??:0
[bt] #2 /usr/lib/libc.so.6(+0x3e710) [0x7fe0c883e710]
??:0
[bt] #3 /usr/lib/libgtk-3.so.0(+0x2773e7) [0x7fe0c9c773e7]
??:0
[bt] #4 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
??:0
[bt] #5 /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
??:0
[bt] #6 /usr/lib/libgtk-3.so.0(+0x19d460) [0x7fe0c9b9d460]
??:0
[bt] #7 /usr/lib/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0x97) [0x7fe0c92c24f7]
??:0
[bt] #8 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
??:0
[bt] #9 /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
??:0
[bt] #10 /usr/lib/libgtk-3.so.0(+0x19df68) [0x7fe0c9b9df68]
??:0
[bt] #11 /usr/lib/libgobject-2.0.so.0(g_closure_invoke+0x140) [0x7fe0c92be6c0]
??:0
[bt] #12 /usr/lib/libgobject-2.0.so.0(+0x42938) [0x7fe0c92ec938]
??:0
[bt] #13 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x10e7) [0x7fe0c92ddaa7]
??:0
[bt] #14 /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fe0c92ddd34]
??:0
[bt] #15 /usr/lib/libgtk-3.so.0(+0x1ee20e) [0x7fe0c9bee20e]
??:0
[bt] #16 /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
??:0
[bt] #17 /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
??:0
[bt] #18 /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
??:0
[bt] #19 /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
??:0
[bt] #20 /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
??:0
[bt] #21 /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
??:0
[bt] #22 /usr/lib/libgtk-3.so.0(+0xb65b0) [0x7fe0c9ab65b0]
??:0
[bt] #23 /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
??:0
[bt] #24 /usr/lib/libgtk-3.so.0(+0x222135) [0x7fe0c9c22135]
??:0
[bt] #25 /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
??:0
[bt] #26 /usr/lib/libgtk-3.so.0(+0x35f1aa) [0x7fe0c9d5f1aa]
??:0
[bt] #27 /usr/lib/libgtk-3.so.0(+0x1ee187) [0x7fe0c9bee187]
??:0
[bt] #28 /usr/lib/libgtk-3.so.0(+0x1ee392) [0x7fe0c9bee392]
??:0
[bt] #29 /usr/lib/libgtk-3.so.0(+0x257909) [0x7fe0c9c57909]
??:0
[bt] #30 /usr/lib/libgtk-3.so.0(+0x86965) [0x7fe0c9a86965]
??:0
[bt] #31 /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x1209) [0x7fe0c92ddbc9]
??:0


Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = (null), Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /usr/share/xournalpp/../locale
INFO    : xopp :: Loading plugins from: /usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/Strawby/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
DEBUG   : GdkPixbuf :: gdk_pixbuf_from_pixdata() called on:
DEBUG   : GdkPixbuf :: 	Encoding raw
DEBUG   : GdkPixbuf :: 	Dimensions: 14 x 14
DEBUG   : GdkPixbuf :: 	Rowstride: 56, Length: 808
DEBUG   : GdkPixbuf :: 	Copy pixels == false
MESSAGE : xopp :: lastOpenPath set
MESSAGE : xopp :: Info: autosave document...
MESSAGE : xopp :: Autosaving to /home/Strawby/.cache/xournalpp/autosaves/2151.autosave.xopp
DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/Strawby/.cache/xournalpp/errorlogs/errorlog.20230828-085821.log
```

**Comment by bhennion** [comment] 2023-09-03 16:30
Duplicate of #4931

**Closed by bhennion** 2023-09-03 16:30 UTC
Labels: bug
