### ISSUE TITLE
crashed session again

### ISSUE THREAD

**Issue by NinjaTuna007** [xournalpp/xournalpp#4865] opened 2023-05-07 10:50 UTC
Date: Wed Apr 26 19:25:45 2023
Error: signal 6
[bt]: (0) /usr/bin/xournalpp(+0xbec98) [0x55b00ec6dc98]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f5a1cc89520]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f5a1ccdda7c]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f5a1cc89476]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f5a1cc6f7f3]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f5a1cc6f71b]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f5a1cc80e96]
[bt]: (7) /usr/bin/xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x144) [0x55b00ed8f104]
[bt]: (8) /usr/bin/xournalpp(_ZN9RenderJob3runEv+0xa3) [0x55b00ed8f1c3]
[bt]: (9) /usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x102) [0x55b00ec6c8b2]
[bt]: (10) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x84a51) [0x7f5a1d4bea51]
[bt]: (11) /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f5a1ccdbb43]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f5a1cd6da00]

Try to get a better stracktrace...
[bt] #1 /usr/bin/xournalpp(+0xbf13d) [0x55b00ec6e13d]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f5a1cc89520]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7f5a1ccdda7c]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f5a1cc89476]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7f5a1cc6f7f3]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libc.so.6(+0x2871b) [0x7f5a1cc6f71b]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libc.so.6(+0x39e96) [0x7f5a1cc80e96]
??:0
[bt] #8 /usr/bin/xournalpp(_ZN9RenderJob17rerenderRectangleERKN3xoj4util9RectangleIdEE+0x144) [0x55b00ed8f104]
??:0
[bt] #9 /usr/bin/xournalpp(_ZN9RenderJob3runEv+0xa3) [0x55b00ed8f1c3]
??:0
[bt] #10 /usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x102) [0x55b00ec6c8b2]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x84a51) [0x7f5a1d4bea51]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f5a1ccdbb43]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f5a1cd6da00]
??:0

**Comment by bhennion** [comment] 2023-08-08 16:37
Duplicate of #4991

**Closed by bhennion** 2023-08-08 16:37 UTC
