### ISSUE TITLE
Crash when using GTK Touch/Scrolling workaround

### ISSUE THREAD

**Issue by Scafir** [xournalpp/xournalpp#980] opened 2019-03-12 10:36 UTC
I just installed xournalpp on the latest openSUSE tumbleweed (20190310) using kde on wayland. I am using a Surface-like machine (Lenovo Miix 720). The reported wacom device are Wacom HID 5099 Pen and Wacom HID 5099 Finger.

Xournalpp crashes when scrolling with finger touch and GTK Touch/Scrolling workaround enable (when disabled it works fine)
[errorlog.20190312-101140.log](https://github.com/xournalpp/xournalpp/files/2956324/errorlog.20190312-101140.log)
When launched from a terminal, it also says:
`(xournalpp:4094): Gdk-CRITICAL **: 10:11:18.208: gdk_device_get_state: assertion 'gdk_device_get_device_type (device) != GDK_DEVICE_TYPE_SLAVE || gdk_display_device_is_grabbed (gdk_device_get_display (device), device)' failed
`

**Comment by Scafir** [comment] 2019-03-13 10:25
After some tests, I can safely say that it is not linked with wayland, as it crashes all the same on the server X version of kde

**Comment by peetCreative** [comment] 2019-03-14 20:32
OK I can reproduce this. The application sigsev at the same location as in #760 and #764.
I don't understand what is the difference by this setting as I didn't wrote this workaround.

**Comment by Scafir** [comment] 2019-03-15 08:26
From the (very small) experience I have, I find it strange to have this workaround enabled by default since it disables inertia scrolling and crashes the system.. Maybe posting the solution in the FAQ of the main page will help other people?

**Comment by LittleHuba** [comment] 2019-05-13 19:41
@Scafir could you test with the new experimental input system (you can enable it in the settings)?

**Comment by Scafir** [comment] 2019-05-13 22:14
@LittleHuba Short answer: it does not crash anymore! We can close this issue, good job :)

Long answer: everything is not perfect. I performed tests with/without workaround and with/without new input system on my two current systems (ubuntu LTS 18.04.2 and fedora 30), went a bit out of the scope of this particular issue and got different small malfunctions/errors. The main things are:
* An error `(xournalpp:13386): Gtk-WARNING **: 22:42:56.739: Error loading theme icon 'gtk-ok' for stock: Icon 'gtk-ok' not present in theme hicolor` appears with the new input system only on ubuntu
* The settings tab for the input system is not translated (= appears in german) but only on ubuntu. Maybe a mismatch between the available version in the repo (ubuntu) and the latest build (fedora)?
* With the combo fedora/new input system/workaround it is not possible to use tools with the touchscreen, but in every other case it's fine
* I think that a recurrent problem with the pinch to zoom, when it  works almost as intended, but it is not very stable (easily jumps between 30% zoom and 700% zoom in milliseconds, even if my finger are not moving) exists because two things are fighting: the finger pressed wants to keep the same point of the document under him and the scrolling effect due to bad pinch to zoom wants the document to move.
* Always test the pinch to zoom issues with multi-page documents. Documents with a single page usually behave much better

I join the [test document](https://github.com/xournalpp/xournalpp/files/3175019/report_workaround.txt) describing everything I did and got. Feel free to read it as it is detailed

**Comment by LittleHuba** [comment] 2019-05-13 22:42
> * An error `(xournalpp:13386): Gtk-WARNING **: 22:42:56.739: Error loading theme icon 'gtk-ok' for stock: Icon 'gtk-ok' not present in theme hicolor` appears with the new input system only on ubuntu

This is an issue of your icon theme we are unable to fix.

> * The settings tab for the input system is not translated (= appears in german) but only on ubuntu. Maybe a mismatch between the available version in the repo (ubuntu) and the latest build (fedora)?

This is already fixed in the newest version.

> * With the combo fedora/new input system/workaround it is not possible to use tools with the touchscreen, but in every other case it's fine

Please file a new bug report for that. 

> * I think that a recurrent problem with the pinch to zoom, when it works almost as intended, but it is not very stable (easily jumps between 30% zoom and 700% zoom in milliseconds, even if my finger are not moving) exists because two things are fighting: the finger pressed wants to keep the same point of the document under him and the scrolling effect due to bad pinch to zoom wants the document to move.

Also file a bug report for this and attach a gif of the issue.

Concerning the other issues in your attached document:
* Scrolling with finger-touchscreen does not work (workaround enabled) -> this is an intended behaviour
* Scrolling with two-finger-on-trackpad does not work / Pinch to zoom on the trackpad may be related to a system wide setting you need to enable. If you find the setting enabled file another report please.

Generally I'm unable to reproduce the issues with pinch-to-zoom...

**Closed** 2019-05-13 22:42 UTC
Labels: bug
