### ISSUE TITLE
xournalpp fails to build on 18.04 due to `make` version requirement.

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#3558] opened 2021-11-10 20:08 UTC
As of recently looks like the build fails on ubuntu 18.04 fails, due to a new cmake requirement:

cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.14 or higher is required.  You are running version 3.10.2

it would be great if things worked (18.04 is a long-term-support release, so it would be great if things worked, as it's widely used)
thanks!

**Comment by petergthatsme** [comment] 2021-11-10 20:19
replying to @Febbe comment here: https://github.com/xournalpp/xournalpp/issues/2543 : 

> I propose to upgrade to latest Ubuntu.
> Or just install a newer cmake + add it to path.

(sorry should have right away created a new issues and not updated that other one, as it's a different cause). 

@Febbe 
thanks for your comment. Are you saying it's an absolute technical necessity to insist on latest cmake version?  ubuntu 18.04 is still very widely used all over the place (it's a LTS) and this will make it more painful to set things up for many people.

**Comment by LittleHuba** [comment] 2021-11-10 21:36
You may want to consider at least updating to the latest LTS release of Ubuntu (20.04). The latest release of CMake is 3.21.4 so our requirement is not even near the "latest" CMake version. CMake 3.14 was released in March 2019 which should be sufficiently old enough for up-to-date distributions to ship it. Ubuntu 18.04 is just that outdated...

**Comment by petergthatsme** [comment] 2021-11-11 00:29
Thanks for your thoughts on this. 
I guess I was just asking if requiring cmake >3.10 stems from some new features that the xournalpp build system is actively using, or if it's more an arbitrary choice to not support it because it's old. If the it's the former, then so be it.. but my point was only that if it's the latter, then you might want to reconsider as ubuntu 18.04 is still very widely used. Under some conditions, people may be more limited in what OSes they use, and in such cases, installing recent xournalpp build will be more painful.

**Comment by LittleHuba** [comment] 2021-11-11 00:41
I understand your reasoning now. We do normally not make such arbitrary version bumps for such basic requirements. In this instance @bhennion can give you some insights as the version bump was caused by a PR from him. (If I'm not mistaken)

**Comment by personalizedrefrigerator** [comment] 2021-11-11 01:21
See https://github.com/xournalpp/xournalpp/pull/3476

**Comment by personalizedrefrigerator** [comment] 2021-11-11 01:22
> I understand your reasoning now. We do normally not make such arbitrary version bumps for such basic requirements. In this instance @bhennion can give you some insights as the version bump was caused by a PR from him. (If I'm not mistaken)

@idotobi

**Comment by Technius** [comment] 2021-11-11 03:43
Our (tacitly agreed upon) policy was to pin minimum dependency versions to the oldest non-EOL Ubuntu LTS release.

In the future, we should pin to Debian stable since `xournalpp` is now available in Debian repositories, which will then trickle downstream to Ubuntu anyways.

**Comment by Febbe** [comment] 2021-11-11 10:12
> Our (tacitly agreed upon) policy was to pin minimum dependency versions to the oldest non-EOL Ubuntu LTS release.

I think, for normal deps yes, but for buildtime deps it should be free for us to upgrade them. But then we also should make sure, that the pipelines for that versions still work. (Allowing normal users to download it). People who want to contribute should work on newer Operating systems.

@petergthatsme you can try to downgrade the cmake features.

**Comment by idotobi** [comment] 2021-11-11 18:39
@petergthatsme: I guess I'm the one responsible for breaking the build for you :sweat_smile: (and probably others) . Sorry.

I basically had to bump the version because of the CMake functionality [FetchContent_MakeAvailable](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable) which is used in the main `CMaeksLists.txt` for building `gtest`.

As long as you're not interested in building tests it's actually not even used so you could easily comment out these lines again and downgrade again. Not sure if this is something that works for your usecase.

@Febbe: I agree building for release should be possible for users on older systems as well. I'll check if there's an easy replacement that allows for downgrading this weekend.
If any one has a different/better idea for resolving this I'm happy for pointers.

**Comment by Febbe** [comment] 2021-11-12 01:34
@idotobi no, that was not what I meant. I meant, that it should be ok to break building deps (like using newer cmake etc.). But not to break run time deps.
So in my opinion, there is nothing you have to fix here.

The latest stable (1.1.x) will probably gain bugfixes until ubuntu 18.04 leaves the support cycle (early 2022).
Also, I have an open CMake refactoring, which will also break or fix this. Even if we decide to support cmake 3.10 again, this should be done after the refactoring. 

@petergthatsme unfortunately we have to make such decisions sometimes, that is always an uncomfortable decision between development comfort+speed and fulfilling the wish of every user, running an old OS.

Will close this for now.

**Closed by Febbe** 2021-11-12 01:34 UTC

**Comment by petergthatsme** [comment] 2021-11-12 23:35
Thanks everyone for your comments. 

@idotobi  graet!.. i don't need to build `gtest`, and so manually lowering the requirement seems to indeed work fine for me. Thanks for pointing this out.

@Febbe just a minor (not very relevant in the end) point - ubuntu 18.04 EOL is in actually april 2023.
