### ISSUE TITLE
errorlog

### ISSUE THREAD

**Issue by florianjansen** [xournalpp/xournalpp#4839] opened 2023-04-26 10:27 UTC
Date: Sun Dec 11 11:42:14 2022
Error: signal 11
[bt]: (0) xournalpp(+0xb55f8) [0x55c4128675f8]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f6fd09dc520]
[bt]: (2) xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x55c4128b666b]
[bt]: (3) xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xc56) [0x55c4128aa736]
[bt]: (4) xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x55c412897399]
[bt]: (5) xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbb) [0x55c41289776b]
[bt]: (6) xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x93c) [0x55c4128988ec]
[bt]: (7) xournalpp(+0xb7ec7) [0x55c412869ec7]
[bt]: (8) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f6fd12ddd2f]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f6fd12f9c36]
[bt]: (10) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f6fd12fb614]
[bt]: (11) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f6fd12fb863]
[bt]: (12) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x241) [0x7f6fd1439421]
[bt]: (13) /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe0b8e) [0x7f6fd1439b8e]
[bt]: (14) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x136) [0x7f6fd1439f46]
[bt]: (15) xournalpp(_ZN11XournalMain3runEiPPc+0x5df) [0x55c4128655ef]
[bt]: (16) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f6fd09c3d90]
[bt]: (17) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f6fd09c3e40]
[bt]: (18) xournalpp(_start+0x25) [0x55c412863815]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xb5a9d) [0x55c412867a9d]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f6fd09dc520]
??:0
[bt] #3 xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x55c4128b666b]
??:0
[bt] #4 xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xc56) [0x55c4128aa736]
??:0
[bt] #5 xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x55c412897399]
??:0
[bt] #6 xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbb) [0x55c41289776b]
??:0
[bt] #7 xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x93c) [0x55c4128988ec]
??:0
[bt] #8 xournalpp(+0xb7ec7) [0x55c412869ec7]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f6fd12ddd2f]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f6fd12f9c36]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f6fd12fb614]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f6fd12fb863]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x241) [0x7f6fd1439421]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe0b8e) [0x7f6fd1439b8e]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x136) [0x7f6fd1439f46]
??:0
[bt] #16 xournalpp(_ZN11XournalMain3runEiPPc+0x5df) [0x55c4128655ef]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f6fd09c3d90]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f6fd09c3e40]
??:0
[bt] #19 xournalpp(_start+0x25) [0x55c412863815]
??:0

**Comment by rolandlo** [comment] 2023-04-26 10:29
Duplicate of #4836

**Closed by rolandlo** 2023-04-26 10:29 UTC
