### ISSUE TITLE
Scrolling not working properly on new documents

### ISSUE THREAD

**Issue by nicola-bastianello** [xournalpp/xournalpp#2066] opened 2020-06-14 16:18 UTC
**Affects versions :**
 - OS: Xubuntu 18.04
 - Desktop environment: XFCE
 - Which version of libgtk do you use: 3.22.30
 - Version of Xournal++: 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
After launching Xournal++ on a new document scrolling does not work; when launching it by opening a saved document scrolling works. Zooming out solves the issue.

**To Reproduce**
1. Open Xournal++ on a new document
2. Scroll does not work:
    * the scroll bar can be moved up and down with the mouse, but does not affect which part of the document is shown
    * with the two-finger gesture on the laptop's touchpad the scroll bar moves rapidly and erratically up and down, but still only the top of the page is shown
4. Try opening a previously saved document: scroll still does not work
3. Zoom out (CTRL+minus) and scrolling starts to work normally (tried after seeing -- possibly related -- issue #2062)
4. Close Xournal++, and open a previously saved document (even a blank one): scrolling works normally

**Additional context**
The issue is the same when launching Xournal++ from the program menu and a terminal. When opening from a terminal some error messages are printed, see [attached file](https://github.com/xournalpp/xournalpp/files/4776821/terminal.txt))

**Comment by Technius** [comment] 2020-06-17 01:33
Does this occur when zoom fit is disabled?

Possible regression #1383.

**Comment by Technius** [comment] 2020-06-17 01:34
@Febbe maybe the recent zoom changes caused this?

**Comment by Technius** [comment] 2020-06-18 02:45
Do you have the `Touch Workaround` enabled?

**Comment by nicolabastianello** [comment] 2020-06-18 09:26
1. Indeed, it happens only when zoom fit is on.
2. No, I don't have the touch workaraound enabled.

**Comment by wolfgang-noichl** [comment] 2020-06-22 08:34
**Version**

- Xubuntu 20.04
- libgtk 3.24.18-1ubuntu1
- Xournal 1.0.6-0\~202005080350\~ubuntu19.10.1

**Description**

Reproduced the above. In more detail: If the GTK Touch / Scrolling workaround is enabled, zooming does not restore the ability to scroll. "Zoom gestures" settings don't seem to have any influence.

**Comment by BMicraft** [comment] 2020-12-13 14:07
This seems to be the same issue as 2138. I think this issue can be close in favor of the other one.

**Comment by rolandlo** [comment] 2020-12-13 18:43
This is probably fixed by PR #2541. I will close it in favor of #2138.

**Closed by rolandlo** 2020-12-13 18:43 UTC
Labels: Zoom, bug, papercut, priority::high, regression
