### ISSUE TITLE
Page disappear after adding a new page at the end

### ISSUE THREAD

**Issue by aweinstein** [xournalpp/xournalpp#1943] opened 2020-05-06 12:58 UTC
**Affects versions :**
- OS: Linux Mint 19.2
- Desktop environment: Cinnamon
 - Which version of libgtk do you use: 3.22.30-1ubuntu4
 - Version of Xournal++: 1.1.0+dev, built on May 4 2020, 02:46:40
 - Installation method: PPA

**Describe the bug**

When I add a third page to the journal, the second one disappears. 

**To Reproduce**

1. Open a new journal, and write something.
2. Add a new page at the end and write something on the new page.
3. Add a new page at the end and write something on the new page.
4. Go back to check page 2 and see that that page disappeared. 

**Expected behavior**
Keep all the pages.

**Screenshots of Problem**

I am attaching a short screencast showing the issue.
![vokoscreen-2020-05-06_08-34-40](https://user-images.githubusercontent.com/123405/81179252-6533df80-8f77-11ea-9b2d-585f9d1fa6cd.gif)

**Comment by Technius** [comment] 2020-05-07 07:01
I can't reproduce this bug. Can you set the portrait view in `View > Toolbars` and see what happens in the sidebar preview?

**Comment by aweinstein** [comment] 2020-05-07 13:07
Hi:

I did what you said (see image) and now I see that page 2 does not disappear, but is placed to the right of page 1. Scrolling with the mouse it jumps from page 1 to 3. Using PgUp/PgDn it goes through the expected sequence 1>2>3.

Do you think this is a bug? 
 
![vokoscreen-2020-05-07_08-29-31 (1)](https://user-images.githubusercontent.com/123405/81297209-eefbaf80-9040-11ea-8797-7516e2d317a6.gif)

**Comment by Febbe** [comment] 2020-05-07 14:13
No it is not a bug, you've enabled the book view. Unfortunately the zoom to fit is buggy there, so the zoom does not fit to both pages. There is a button in the bottom right to disable the book view

**Comment by LittleHuba** [comment] 2020-05-07 17:08
As @Febbe mentioned this is not a bug - closing

**Closed by LittleHuba** 2020-05-07 17:08 UTC
Labels: bug, priority: high
