### ISSUE TITLE
Change the default pen colours from neons to more saturated natural colours

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3727] opened 2022-01-18 23:56 UTC
**Is your feature request related to a problem? Please describe.**
When you write with some of the colours, specifically yellow, pink, green, and light blue, the writing is near illegible on a white background. 

**Describe the solution you'd like**
Most writing software uses decently saturated colours over neon colours for writing, so it might be a good idea to switch the colours to those that are easier to see.

**Comment by rolandlo** [comment] 2022-01-21 07:54
Please see [this discussion](https://github.com/xournalpp/xournalpp/issues/1812) and checkout the [website](https://xournalpp.github.io/guide/config/toolbar-colors/). Closing as a duplicate of #1812.

**Closed by rolandlo** 2022-01-21 07:54 UTC
Labels: enhancement
