### ISSUE TITLE
Zooming with touch gestures doesn't workt shortly after stroke

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1224] opened 2019-06-09 13:54 UTC
OS: Arch Linux
Version of Xournal++ : 1.0.11

After you have drawn a stroke, you can't immediately zoom. You have to scroll before and then can zoom again. 

        1. Draw a stroke
        2. Try to zoom with touch gesture
        3. Scroll with touch input and afterwards zooming is possible

**Comment by LittleHuba** [comment] 2019-06-10 06:56
Are you running on the old or the new input system?

**Comment by coldspark29** [comment] 2019-06-10 18:55
It is the new input system. This problem did not occur in the one, I think.

**Comment by LittleHuba** [comment] 2019-06-10 21:37
There is a blocking algorithm that disables zooming while there is active input. That was introduced in the new input system. It should definitely reenable zooming after the input is done. I'll look into it.

**Comment by lehmanju** [comment] 2019-07-22 20:42
It could also be that your device disables touch screen for the time your stylus is near the screen (that's is the behavior my device has). After removing the pen from screen proximity it takes a few seconds for it to reactivate. I don't know if this is configured or hardware dependent.

**Comment by coldspark29** [comment] 2019-07-23 06:49
If it was so, it would also occur in the old input system

**Comment by LittleHuba** [comment] 2019-07-25 11:02
Yeah this is definitely a regression of the new input system. It correlates with the hand recognition as it only shows this behaviour if hand recognition is enabled. (At least on my device)

I'll look into it.

**Comment by LittleHuba** [comment] 2019-07-25 11:03
> It could also be that your device disables touch screen for the time your stylus is near the screen (that is the behavior my device has). After removing the pen from screen proximity it takes a few seconds for it to reactivate. I don't know if this is configured or hardware dependent.

The problem is it reactivates after the first touch for some reason.
I'm actually not happy how the hand recognition works so far. This timeout is really ugly...

**Comment by lehmanju** [comment] 2019-07-26 12:22
I have hand recognition turned off, so this is actually hardware implemented for me somehow.

**Comment by LittleHuba** [comment] 2019-09-16 17:22
This is not reproducible anymore. @lehmanju please check if it persists on your machine.

**Comment by LittleHuba** [comment] 2019-10-16 13:34
Should be fixed by #1528 if still an issue. Otherwise orphaned.

**Closed** 2019-10-17 22:49 UTC
Labels: Zoom, bug, need info, priority: high
