### ISSUE TITLE
Highlighter Tool fill option different tones

### ISSUE THREAD

**Issue by couldNOTcompute** [xournalpp/xournalpp#3709] opened 2022-01-09 19:02 UTC
OS:
- Windows 10 Pro
   - Xournalpp 1.1.0 Win. hotfix
   - Com.: 9d1277de
- Ubuntu 21.10 (Wayland)
   - Xournalpp 1.1.0
Libgtk:
- 3.24.30

Description:
**I'm not sure if it's a bug, but I regard it as unexpected behavior.**
When using the Highlighter Tool with the fill option with certain colors, lines in a different tone appear. Others do not show this behavior (as I’d expect it).
The thickness doesn’t matter (small, medium and large). It only appears with fill option enabled.

1. Select the Highlighter and the fill option
2. Draw shapes (using rectangle or free hand - that's what I tested)

Expected behavior:
Uniform tone (like yellow, red, ... have)

![xournalpp-bug-1](https://user-images.githubusercontent.com/95862384/148696537-88a61d11-265f-468c-a0b5-52085b68e75e.JPG)
(The last two are just two random from the pallet)

![xournalpp-bug-2](https://user-images.githubusercontent.com/95862384/148696536-d9b57b68-5a63-418b-bb46-abe28824fbfa.JPG)

**Comment by bhennion** [comment] 2022-01-09 20:19
This is a duplicate of #2904, which has been fixed in master. You can use one of the nighlty builds for a version with the fix.

**Closed by bhennion** 2022-01-09 20:19 UTC
Labels: bug
