### ISSUE TITLE
Black Screen on MacOS 12.1

### ISSUE THREAD

**Issue by suyanhanx** [xournalpp/xournalpp#3741] opened 2022-01-23 10:42 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows] MaxOS 12.1
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use   I can't get the version. The menu is unusable.
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch] 1.1.0
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.] Official release

**Describe the bug**

Like this pic
![image](https://user-images.githubusercontent.com/24221472/150674793-082b431a-13b9-4bc9-be43-c17f1449fd1e.png)

**To Reproduce**
1. Just open it

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

**Comment by rolandlo** [comment] 2022-01-23 16:14
Duplicate of #3517

**Closed by rolandlo** 2022-01-23 16:14 UTC
Labels: bug
