### ISSUE TITLE
Graphic bug when resizing Tex objects

### ISSUE THREAD

**Issue by Fef0** [xournalpp/xournalpp#1550] opened 2019-10-17 09:55 UTC
**Affects versions :**
 - OS: Arch Linux
 - DE: Gnome 3.24
 - Version of Xournal++: 1.0.1.5

**Describe the bug**
A graphic bug (pic in the bottom) always happens when resizing multiple times a Tex object.
Basically the Tex formatting get broken and I have to restart Xournal++ in order to show it correctly.

**To Reproduce**
1. Write something in Tex (Sums, for example)
2. Select the object and resize it multiple times.
3. If you're unlucky enough, you'll see the same bug

**Expected behavior**
It should just resize the object, keeping the formatting.

**Screenshots of Problem**
```\sum _{i=1} ^ {\infty} \int _{m-n} ^ {n} f(x)```
![texbug1](https://user-images.githubusercontent.com/19290442/66998478-9ed4f400-f0d4-11e9-9cee-1520bbed0b6b.png)

**Comment by LittleHuba** [comment] 2019-10-17 14:30
Duplicate of #1497

**Comment by Technius** [comment] 2019-10-22 17:32
Closing this and reopening the original issue.

**Closed by Technius** 2019-10-22 17:32 UTC
Labels: bug
