### ISSUE TITLE
Mainstreaming

### ISSUE THREAD

**Issue by PerEGronvik** [xournalpp/xournalpp#2307] opened 2020-10-10 06:21 UTC
The program has difficulty gaining popularity. This because most people don't understand how to even install it. Most people use windows and the windows link does not go directly to the download, but to a list of files. This in nice for tech people, but will scare most older people and newbs away.

**Describe the solution you'd like**
I would like the site to have a direct link. And that the person who writes the page will at all times do a mental check where they pretend to be a anxious know-nothing'er trying to install or find a tool. 

Continue as usual and have the tool not be used. The long term effect is that there will be less funding for the project and the ecosystem in general. 

I have a personal goal to establishing state funding for opensource.

**Comment by Technius** [comment] 2020-10-11 01:40
Related: #2045.

> The program has difficulty gaining popularity. This because most people don't understand how to even install it.

This is a major issue that we've been trying to address, and some improvements should come in the following weeks.

> I would like the site to have a direct link. 

We have a work-in-progress website being worked on at http://github.com/xournalpp/xournalpp.github.io. Once it has more information than the readme, we'll update the readme and repository to point to the new website.

> Continue as usual and have the tool not be used. The long term effect is that there will be less funding for the project and the ecosystem in general.

Right, and this would be terrible for everyone. But the problem is that we're lacking _time_, as the project is maintained completely in our free time; money would not be useful for us at this point.

**Comment by pktiuk** [comment] 2020-10-12 09:34
@PerEGronvik 
If you have any other thoughts about its site you can share it here: https://github.com/xournalpp/xournalpp.github.io/issues/5  
If you have some free time you could also help with writing (rewriting/copying) guides to this new site (no coding skills needed :) )

**Comment by Technius** [comment] 2022-02-19 08:56
Closing this issue as the website has a nice splash page and has multiple pages describing how to install the application.

**Closed by Technius** 2022-02-19 08:56 UTC
Labels: question
