### ISSUE TITLE
Mouse wheel not scrolling

### ISSUE THREAD

**Issue by kangourou13** [xournalpp/xournalpp#1629] opened 2019-11-25 20:23 UTC
Hi,
I use Xournalpp on Ubuntu 16.04/64, GNOME Shell 3.18.5, libgtk-3-0:amd 3.18.9-1ubun amd64.
Issue on Xournalpp 1.0.8 and 1.0.15.

Use of mouse wheel into the document don't scroll. Mouse wheel only scroll when mouse in on the scroll bar on the right of the window.   
What i expect : scroll up and down when i use mouse wheel in the document (works in xournal legacy). Bug or bad configuration ?
Regards. 

**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]
 - In case of linux, which desktop environment [Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use.
 - Version of Xournal++ [e.g. 1.0.10, specific commit, specific branch]

**Describe the bug**

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by LittleHuba** [comment] 2019-11-25 23:01
Please open settings dialog and go to `Input System`. Check if the new input system is activated or not. If not please activate it and check that the device classes beneath are assigned correctly. Then recheck behaviour and update the ticket accrodingly.

**Comment by Technius** [comment] 2020-05-20 03:52
Closing due to lack of activity.

**Comment by guycohen** [comment] 2020-11-30 12:08
This is happening to me now, using new input system and with mouse correctly assigned.

**Comment by Technius** [comment] 2020-11-30 19:39
> This is happening to me now, using new input system and with mouse correctly assigned. Using version 1.0.16 on Ubuntu 18.04.5 LTS.

Seems like you installed through the Snap store / Software center, which we do not support. Can you try using the official `.deb` file of version 1.0.19 on the [releases page](https://github.com/xournalpp/xournalpp/releases/tag/1.0.19)?

**Comment by guycohen** [comment] 2020-12-01 06:52
Thanks, yes - this actually seems to partially resolve the issue. However, I notice that in this version it still occurs, inconsistently but often. The problem now usually appears after a window resize/maximization with "Zoom fit to screen" activated. When this happens, the scroll bar also disappears, a behavior I didn't see with the Snap version.

**Comment by Technius** [comment] 2020-12-01 07:03
> The problem now usually appears after a window resize/maximization with "Zoom fit to screen" activated. When this happens, the scroll bar also disappears, a behavior I didn't see with the Snap version.

The scroll bar disappearing is different bug, probably some sort of layout calculation issue. Might be related to #2066.

**Comment by LittleHuba** [comment] 2020-12-03 09:32
@guycohen could you please provide input logs (https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs)?

**Comment by guycohen** [comment] 2020-12-03 10:29
Willing to try, but having trouble compiling. Possibly a mismatch with
Ubuntu 18.04's version of Portaudio?
...
[ 97%] Linking CXX executable xournalpp
CMakeFiles/xournalpp-core.dir/control/Control.cpp.o: In function
`portaudio::AutoSystem::AutoSystem(bool)':
/usr/include/portaudiocpp/AutoSystem.hxx:37: undefined reference to
`portaudio::System::initialize()'

**Comment by LittleHuba** [comment] 2020-12-03 10:50
Did you install all packages listed in the Wiki?
```
sudo apt-get install cmake libgtk-3-dev libpoppler-glib-dev portaudio19-dev libsndfile-dev \
libcppunit-dev dvipng texlive libxml2-dev liblua5.3-dev libzip-dev
```

**Comment by guycohen** [comment] 2020-12-03 11:36
Yes, but looks like I broke something else in the CMake configuration.
Managed to compile, but can't reproduce the bug in the latest version. So,
I guess you can close this - thanks very much for the help!

**Comment by LittleHuba** [comment] 2020-12-03 11:40
That is the best outcome^^. Thanks for trying it out!

You can use the nightly versions until we release a new official one with the fix included.
https://github.com/xournalpp/xournalpp/releases/tag/nightly

**Closed by LittleHuba** 2020-12-03 11:40 UTC
Labels: bug, need info
