### ISSUE TITLE
not smooth input with MacOS - Wacom Pen not detected as Input System

### ISSUE THREAD

**Issue by birba** [xournalpp/xournalpp#2302] opened 2020-10-07 20:27 UTC
**Setup:**
 - tablet/pen: Wacom Intuos M BT
 - OS: MacOX Catalina 1.15.7 (MacBook Pro 2020)
 - Version of Xournal++: 1.0.18
 - Installation method: downloaded the ``xournalpp-1.0.18-macos.zip'' (from https://github.com/xournalpp/xournalpp/releases), the system automatically recognise it as an .app which runs. No need to unzip or install at all.

**Description of the problem:**
The strokes are ugly (not smooth, with ''edges'') and there is a notable lag. If I run the app and open: Edit->Preferences->InputSystems I see the message: ''No devices were found. This seems wrong - maybe file a bug report?''

Remark 1) The same Wacom pen on the same laptop writes smoothly on OneNote (terrible software, though). 
Remark 2)I have Xournal++ on fedora in my office and with the same tablet it is 10times smoother with a machine which is half as powerful as the MacBook. So I think there is a real issue.
Remark 3) it looks exactly as this issue: (https://github.com/xournalpp/xournalpp/issues/1531). Also the pictures are the same. The links to the ''these/those'' are broken.

**Attempted solution:**
Download the full ''source code tar.gz'' and try a manual build following this guide: https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md (I did not have installed Homebrew - whatever that is). Took a lot of time, got around 5 errors which are _very_ far from my level of expertise. Most of the commands ended up with ''correct'' or something like that. The following commands _did not_ ended up with ``correct'': ./build-poppler.sh and ./build-portaudio.sh.

**Excpeted behaviour:**
I expect the Xournal++ for Mac to run as smoothly as the Xournal++ I have in the Fedora in the office.

**Screenshots of Problem**
The _same_ screenshots as https://github.com/xournalpp/xournalpp/issues/1531.

**Comment by fredowski** [comment] 2020-11-09 11:38
I could fix the detection problem by using the gtk version 3.24.23 which I installed via macports. The "smooth" problem is still there but the strange thing is that when I turn the Wacom pen and use the eraser and then turn back, then it is smooth. Very strange. Behaviour did not change when I chose Eraser via the menu, i.e. I had to turn the pen.

**Comment by fredowski** [comment] 2020-11-09 12:04
Hi @birba, 

could you maybe try the fork with my changes in the mac-setup directory

https://github.com/fredowski/xournalpp/tree/macapp

to see if you can create the build environment? This takes quite long.

**Comment by mschinca** [comment] 2021-03-30 17:44
@fredowski I'm also experiencing the "smooth" issue. I'm using your fork.
I'm not using a tablet so I think the lag is unrelated to the input method.
I noticed that the lag is proportional to the application window size and is independent from the zoom level.
I took a [screen capture](https://www.youtube.com/watch?v=BRb4ie6XjRo) to show the behavior.
I the problem is noticeable only on a high DPI screen (e.g. Mac retina 16) and not on an older screen.
Trying to adjust DPI settings didn't help

**Comment by rolandlo** [comment] 2021-04-01 13:24
> I'm not using a tablet so I think the lag is unrelated to the input method.
> I noticed that the lag is proportional to the application window size and is independent from the zoom level.
> I took a [screen capture](https://www.youtube.com/watch?v=BRb4ie6XjRo) to show the behavior.

I have made the same observations with the latest master (with the updated dependencies).

**Comment by fredowski** [comment] 2021-04-01 13:32
Do you also see the behaviour that the lag is gone if you turn the pen, do something with the eraser and turn back?

**Comment by rolandlo** [comment] 2021-04-01 13:35
I haven't observed that yet with my 3D Pen (which doesn't have an eraser on the bottom). I have another pen (which has an eraser at the bottom), and will try it, once I can find it.

**Comment by mschinca** [comment] 2021-04-01 16:23
Not sure if relevant, but I had the chance to try `1.0.19` and it looks very smooth instead on same hardware. So maybe some performance regression introduced later?

**Comment by rolandlo** [comment] 2021-04-01 16:39
Version `1.0.19` looks much smoother indeed. It's especially visible when drawing filled shapes. The question is, whether the performance regression comes from something in Xournal++ or from updated dependencies.

**Comment by rolandlo** [comment] 2021-04-01 16:57
Since the lag depends very much on the window size, it might be an issue with the rendering. Maybe lots of rerenders. We will have to investigate this.

**Comment by mschinca** [comment] 2021-04-01 17:06
> Version `1.0.19` looks much smoother indeed. It's especially visible when drawing filled shapes. The question is, whether the performance regression comes from something in Xournal++ or from updated dependencies.

I suspect it may be the latter.
I've just built tag `1.0.19` with the `brew` method. The drawing  is as laggy as latest master.
I'm now trying to build the same tag with the bundled `gtk+` for comparison.

**Comment by mschinca** [comment] 2021-04-02 00:20
I managed to build `1.0.19` with the `jhbuild` method - with some obstacles due to unpinned dependencies.
The drawing was still laggy.
I then noticed that the `gtk+3` version pulled by `gtk-osx-setup.sh` was not the same as the one shown by the 'released' `1.0.19`

<img width="606" alt="xournalpp-about" src="https://user-images.githubusercontent.com/88272/113365801-35d84f00-934f-11eb-948a-a3c0bd07b6d1.png">

I'm not sure how to build an earlier `gtk+3` so I could not confirm that the gtk version is what makes the difference.
At this stage it is probably better to investigate the issue on the latest version anyway.

**Comment by fredowski** [comment] 2021-04-02 06:30
Hi, the idea of the changing the gtk version was because the wacom pen was not detected: https://github.com/xournalpp/xournalpp/issues/1772#issuecomment-723540523

**Comment by rolandlo** [comment] 2021-04-02 06:50
It's no option to go back to GTK version 3.24.10 as pointed out by @fredowski . It might be an option to use a more recent GTK version though. Currently we get 3.24.23 because we use the **stable** moduleset and the version is hardcoded in 

https://gitlab.gnome.org/GNOME/gtk-osx/-/blob/master/modulesets-stable/gtk-osx.modules#L326

We might try out the **unstable** moduleset, which would currently use GTK version 3.24.28 as seen from

https://gitlab.gnome.org/GNOME/gtk-osx/-/blob/master/modulesets-unstable/gtk-osx.modules#L252

and https://download.gnome.org/sources/gtk+/3.24/

**Comment by fredowski** [comment] 2021-04-02 07:06
Yes sure - it is not an option to go back to 3.24.10. My guess is that there are maybe not too many applications which use pen support with gtk on MacOS. Maybe Xournal is the only one? This is the history of the gdk/quartz section in gtk: https://github.com/GNOME/gtk/commits/gtk-3-24/gdk/quartz . Not too much happens there. Maybe it is possible to disect the problem or is the problem the updated pen support https://github.com/GNOME/gtk/commit/ecbed15d47fc29fc0da133c255fb7e4cb62e4129#diff-779883cae9c0feee3d7d2e781b4255a305a14cab7e8c227eb077f32eaec9f8d6 which was the change that fixes the pen detection?

**Comment by rolandlo** [comment] 2021-05-02 14:46
Seems I finally got a Xournal++ build for MacOS without the annoying lag on BigSur. All I had to do was to follow the instructions on the [wiki page](https://github.com/xournalpp/xournalpp/blob/master/readme/MacBuild.md) and in the end upgrade Gtk+-3.0 from version 3.24.23 to version 3.24.28 by executing 
```
jhbuild buildone gtk+-3.0
```
followed by the usual `complete-build.sh`. The former downloads the latest Gtk+ 3 version and builds it.

Note that I did the build on MacOS Catalina and it works fine there as well.
Maybe we can also upgrade Cairo like this (from version 1.16 to 1.17). This might solve some problems with PDF exports.

**Comment by rolandlo** [comment] 2021-05-02 20:51
@birba @mschinca @fredowski if you want to try the non-laggy build of Xournal++ on BigSur, I can upload it somewhere for testing purposes. Just let me know.

**Comment by mschinca** [comment] 2021-05-04 12:56
@rolandlo great news, sure I'd be happy to test it

**Comment by rolandlo** [comment] 2021-05-04 13:27
@mschinca Ok, please download from [this link](https://loetscher-cloud.yourownnet.eu/s/MZfo0BETeyh8aJx). Password is `Xpp` and it's valid for 7 days. You need to unzip it after download.

**Comment by fredowski** [comment] 2021-05-04 15:17
I tried on MacOS 10.13.6 but there it says: 
![Bildschirmfoto 2021-05-04 um 17 15 42](https://user-images.githubusercontent.com/1280457/117026965-82bb9680-acfc-11eb-9463-bc2a35133ba6.JPG)

You compiled on Catalina, right?

**Comment by rolandlo** [comment] 2021-05-04 15:23
Yes, I compiled on Catalina. I tested it on both Catalina and BigSur. High Sierra is not supported anymore, see #2888.

**Comment by mschinca** [comment] 2021-05-04 20:43
> @mschinca Ok, please download from [this link](https://loetscher-cloud.yourownnet.eu/s/MZfo0BETeyh8aJx). Password is `Xpp` and it's valid for 7 days. You need to unzip it after download.

@rolandlo I managed to try your build. All in all it looks very smooth so far, no more input lag, which is great news :)
My environment is macOS Big Sur 11.2.3

Just a side note on the package, after unzipping I needed to give execution permission in order to launch the program from Finder, like so:

```
chmod a+x Xournal++.app/Contents/MacOS/xournalpp*
```

**Comment by rolandlo** [comment] 2021-05-04 20:47
> @rolandlo I managed to try your build. All in all it looks very smooth so far, no more input lag, which is great news :)

Wonderful! I am glad to hear that. @Febbe will work on updating the binary blob in our Azure pipeline, so that all future versions released on the Github page will use the updated Gtk version (that fixes the lag).

**Comment by rolandlo** [comment] 2021-05-12 16:19
@pegonma 
Here is [another link](https://loetscher-cloud.yourownnet.eu/s/i97UcXkrKHibGTb), valid for another 7 days, same password (`Xpp`).

**Comment by BeaconOnAChairMC** [comment] 2021-05-14 15:02
@rolandlo I keep seeing on my mac "you do not have permission to open this file"

**Comment by rolandlo** [comment] 2021-05-14 16:02
@BeaconOnAChairMC So you can't download it? Have you entered the password correctly? Or could you download and unzip it and fail to open it in the finder?

**Comment by BeaconOnAChairMC** [comment] 2021-05-14 19:57
@rolandlo nevermind, I downloaded it but couldn't open, but I got it opened. Hmm, seems I am getting input lag on this build as well, but it might be my computer itself, I can see distinct "jagged" curves, even when using trackpad/mouse to draw, hmm

oh well, thanks anyway!

**Comment by pegonma** [comment] 2021-05-17 11:25
@rolandlo thank you very much! Sadly, I cannot launch it, even after setting xournalpp as executable. It is likely due to the fact that I am running a way outdated version of MacOS (10.12!). I wonder if it would be too much trouble for you to rebuild it with 10.12 as min requirement...?

**Comment by rolandlo** [comment] 2021-05-17 13:37
@pegonma I'm sorry, but rebuilding it with 1.0.12 would be a huge effort.

**Comment by rolandlo** [comment] 2021-05-19 16:12
@lupja Here is [another link](https://loetscher-cloud.yourownnet.eu/s/pX47xZqcrHSV8c6), valid another 7 days, same password `Xpp`.

**Comment by lupja** [comment] 2021-05-19 16:23
> @lupja Here is [another link](https://loetscher-cloud.yourownnet.eu/s/pX47xZqcrHSV8c6), valid another 7 days, same password `Xpp`.

I managed to open the file.
Unfortunately, the issue still persists.

![image](https://user-images.githubusercontent.com/84447275/118848616-33b25b80-b8cf-11eb-88b4-125f945f579b.png)

**Comment by mschinca** [comment] 2021-05-19 21:52
I took a [screen recording ](https://www.youtube.com/watch?v=piVzUobBank) on Catalina recent Mac Pro and GTK 3.24.28.
I noticed some rare glitches, but overall the strokes are fluid and generally speaking it is a big improvement compared to [old version ](https://www.youtube.com/watch?v=BRb4ie6XjRo), so I believe GTK 3.24.28 should be used for latest builds.

**Comment by lorenzmant** [comment] 2021-05-22 18:11
> @lupja Here is [another link](https://loetscher-cloud.yourownnet.eu/s/pX47xZqcrHSV8c6), valid another 7 days, same password `Xpp`.

I have tried out Rolandlo's latest build, and I confirm that I'm experiencing a quite evident non-smooth input.
I don't think I'm adding anything to what has already been observed so far. Here's what I notice.

a. There's a bit of latency between the input and the displaying of traits. Not terrible but not great for handwriting.
b. The app tends to render "curved traits" with "polygonal traits". When I input lines via trackpad the phenomenon is not so annoying, although present. When I draw via an Intuos M BT the phenomenon is way more evident and way more annoying.

Overall I think I am getting something similar to what mschinca shows in his video. If I draw small signs, as mschinca does, I get a similar result. If I draw at the same time more quickly and bigger pictures, the lag and polygonal shape of traits become definitely more evident.

I can provide screenshots/screen recordings if needed; I can also make some specific tests if you think it would be helpful. For the record: I'm on a Macbook Pro M1 under OS 11.2.2.

**Comment by rolandlo** [comment] 2021-07-16 04:22
It seems the lag is related to the icons rendering. Can you please try to use the empty toolbar and see if the lag is reduced?

**Comment by rolandlo** [comment] 2021-07-16 09:03
Even simpler: Hiding the toolbars (with F9) makes the lag go away. Showing them again (with F9) makes the lag come back again. Can anyone confirm these observations (on BigSur)? @mschinca @fredowski @lorenzmant @lupja

**Comment by lorenzmant** [comment] 2021-07-16 12:10
> Even simpler: Hiding the toolbars (with F9) makes the lag go away. Showing them again (with F9) makes the lag come back again. Can anyone confirm these observations (on BigSur)? @mschinca @fredowski @lorenzmant @lupja

I've tried to do what you suggested using your version (built on May 2nd at 15:52 with gtk 3.24.28) on OS 11.2.2 on a macbook pro M1. Is this ok? or you compiled a newer version?

With the given version, I don't see any difference between writing with or without toolbar.
When I draw with small traits there isn't much latency, and traits are ok. But when I'm drawing large traits the latency increases and the software translates a smooth curved line to a polygonal line. The phenomenon seems to be proportional to the writing speed: the quicker the trait is, the worse the quality of traits.

Ah, is it expected that when I'm using your version of Xournal++, on the menu bar of MacOS there are only two menus? I can only see the apple menu (which is always there), and one single Xournal++ menu. All Xournal's menus are on Xournal++'s window. On the other hand when i use Xournal 1.0.16 the menus aren't in Xournal++ window, but rather on macOS menu bar. May this be connected to the lag?

**Comment by rolandlo** [comment] 2021-07-16 12:18
@lorenzmant You are supposed to use a more recent 1.1.0+dev version, not older than 2021, June 16. Ideally try the latest [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly). 

As for the menus: We have removed the Gtk-Mac-Integration. That is probably not related to the lag.

**Comment by lorenzmant** [comment] 2021-07-16 12:23
> @lorenzmant You are supposed to use a more recent 1.1.0+dev version, not older than 2021, June 16. Ideally try the latest [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly).
> 
> As for the menus: We have removed the Gtk-Mac-Integration. That is probably not related to the lag.

Right, so I retried with the version you suggested, but my comment remain the same. No real difference with or without toolbars.

**Comment by rolandlo** [comment] 2021-07-16 12:29
> Right, so I retried with the version you suggested, but my comments remain the same. No real difference with or without toolbars.

Thanks for testing. So this issue is even more complicated.

**Comment by Febbe** [comment] 2021-07-16 15:32
Currently, Stroke::calcSize() eats 14% of cpu time.

**Comment by Febbe** [comment] 2021-07-16 18:21
![image](https://user-images.githubusercontent.com/2228627/125992115-ae48e559-1645-4319-8c8f-1b89399a1005.png)

**Comment by Febbe** [comment] 2021-07-17 09:21
Can someone of you, who does not experience the toolbar issue, test #3236.

**Comment by rolandlo** [comment] 2021-07-18 17:08
Reading a bit about GTK+ performance on BigSur I found the following two sources, which show that Xournal++ is experiencing the same problems as other GTK+ apps (in particular GIMP):
[GIMP issue](https://gitlab.gnome.org/GNOME/gimp/-/issues/5989)
[GTK issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/3714)

As I understood GIMP managed to solve the problem (with a patched GTK+ version?), which was related to color space conversion and full redraws after many events. See these two posts:

[first post](https://gitlab.gnome.org/GNOME/gimp/-/issues/5989#note_991082)
[second post](https://gitlab.gnome.org/GNOME/gimp/-/issues/5989#note_1015892)

In particular the observation with full redraws triggered by motion events look relevant.

**Comment by ruizbaier** [comment] 2021-07-21 03:53
> @lupja Here is [another link](https://loetscher-cloud.yourownnet.eu/s/pX47xZqcrHSV8c6), valid another 7 days, same password `Xpp`.

Could you please share the link of that build again so I can try? with my current build I still see the lag.

**Comment by rolandlo** [comment] 2021-07-22 21:18
> 
> @rolandlo Could you please share the link of that build again so I can try? with my current build I still see the lag.

[Here](https://loetscher-cloud.yourownnet.eu/s/M7LuM6FVqgTy6WZ) it is (same password `Xpp`)

**Comment by ruizbaier** [comment] 2021-07-23 00:08
> > @rolandlo Could you please share the link of that build again so I can try? with my current build I still see the lag.
> 
> [Here](https://loetscher-cloud.yourownnet.eu/s/M7LuM6FVqgTy6WZ) it is (same password `Xpp`)

Thank you!!

**Comment by rolandlo** [comment] 2021-07-30 09:22
Please check out the latest nightly release. The lag should be greatly reduced there (both in MacOS Catlina and MacOS BigSur), at least when using the `Minimal Left` toolbar or when the toolbar is hidden.

**Comment by mschinca** [comment] 2021-07-31 16:49
@rolandlo I gave it a shot on Big Sur, Mac Pro 16inch 2019. I think it is getting better, although I can still notice a few lags every now and then when the window is maximized. I made a [screen recording](https://www.youtube.com/watch?v=-F9d64hQbeQ)

**Comment by lorenzmant** [comment] 2021-08-02 10:28
@rolandlo I have given a try to the last nightly build, downloaded from your link, and I had a bit of a surprise in trying it out. Here are some thoughts.

1. Regarding the lag:
-Very high, no difference with previous versions, on **internal display**
-Very low on **external display**, no difference with previous version (Nightly build of July 16th)
Basically nothing changed in my point of view from version of Jul16th to the last nightly build.
What changed was that I tried to use the software on an external display.

2. Regarding the other issues that I see:
-High cpu use on both displays
-Scrolling the sheet most of the times does not work
-The traits are still kind of polygonal, and handwriting looks like "trembling"

3. I have made a screen capture with some comments, available on request.
(I'm a bit shy in posting a link with myself saying nonsense)

**Comment by rolandlo** [comment] 2021-08-02 10:41
@lorenzmant Thanks for testing. You can also make the link available to me privately in a private [Gitter.im](https://gitter.im/) chat.
It would be interesting to know the screen resolutions of your internal and external displays. Also color schemes may have an influence, since color scheme conversions can take up time.

Doesn't the lag (using internal/external display) have an influence on how the traits (strokes) look?

**Comment by lorenzmant** [comment] 2021-08-02 11:18
@rolandlo I have found something a bit less public than youtube. I'll just share an expiring link to my cloud. Here it is:
https://drive.math.uzh.ch/index.php/s/tH26zqCSDKSEqoy

The displays where:
-External: 1920x1080, 60HZ, colour profile: Philips 241PL (this is also the model of the screen)
-Internal: max resolution (apple doesn't want me to know what it is :-((... maybe a 2560x1600), frequency not available, colour profile: Colour LCD

**Comment by lorenzmant** [comment] 2021-08-02 12:00
Update: I wanted to try on another external screen to see if increasing resolution influenced the output. 
Unfortunately I can't find a screen with a higher resolution at the moment. So I tried another screen with the same resolution. But the result is about the same as what I have previously reported

I also tried -while on the other external screen- to lower the resolution of the internal display. 
My impression is that xournal++ is slightly more responsive, but overall not so much. It might be that I'm just making this up.

I'll add the pdf output for comparison to the shared folder.

**Comment by Febbe** [comment] 2021-08-02 12:19
All our releases are built with debug symbols enabled, so the most helpful way to solve this, is that someone in the community profiles the app.

**Comment by rolandlo** [comment] 2021-08-02 14:37
@lorenzmant Thanks for your detailed report. The problem looks pretty complex, since there seem to be multiple issues preventing better performance on Mac OS (Big Sur), and it heavily depends on the display used. 

I'm linking an upstream issue here https://gitlab.gnome.org/GNOME/gtk/-/issues/3714, which relates to the high CPU usage and give some starters on how to profile on Mac OS.

**Comment by lorenzmant** [comment] 2021-09-02 09:03
Guys, I have spotted what might be another issue on the nightly version of July 30th 2021 (git commit: 97c20f62).

Xournal doesn't let me import pdf's. I've tried with different pdf files, and none works. I always get the following message: "The document “blabla.pdf” could not be opened. Xournal++ cannot open files in the “Apple PDF pasteboard type” format."

It might be something completely unrelated to the smoothness issue: in case feel free to repost this text where you think it's appropriate. I have looked for a few keywords, but I haven't found any thread opened for this.

**Comment by Febbe** [comment] 2021-09-05 12:04
You should do it yourself: Click on the options for this post and click mention in new issue. But this is most likely a dependency issue. We might can't fix it.

**Comment by ezyang** [comment] 2021-12-15 21:28
To chime in a data point here, I tried on macOS Big Sur 11.6.1 on a tablet with the 20211211 nightly and I was also getting jagged input.

**Comment by rolandlo** [comment] 2022-01-09 15:49
This [GIMP issue](https://gitlab.gnome.org/GNOME/gimp/-/issues/7690) looks very much related.

**Comment by ldshou** [comment] 2022-02-17 13:48
Hi, xournalpp developers, thank you very much for the wonderful software! I have recently done some testing on my iMac 2015 running Catalina using a Gaomon M7 pen tablet, and would like to share some of my findings:

1) The pen strokes on macOS are very polygonal at first, and as the pen keeps drawing (without raising the tip from the board), things become smoother. That means if you draw a very long curve for 10 seconds, then you're gonna see polygons in the beginning part and then a really nice curve later. If a new long stroke is started, then it becomes polygonal again and then smoother. Unfortunately, I cannot keep drawing long curves in real use. So what i get in real writing is very 'choppy'.
 
2) Another interesting finding is that when a single page is completely visible and being drawn on, the strokes are much smoother than otherwise (if a new page is added, or if the page is zoomed in enough to show only a portion of the canvas). If the single page is entirely visible, then the polygon issue doesn't occur at all and everything is just fine. I guess that still means a small canvas secures good performance?

I didn't try small pen icon. Maybe should give it a try tomorrow. Anyway, this smoothness issue is critical and probably the ONLY problem I have with xournalpp on my mac.

**Comment by bhennion** [comment] 2022-02-17 14:05
@ldshou Thanks for the feedback!

There are significant issues with performances on MacOs that are due to dependencies of ours, so on which we cannot directly act.
Still, the behaviour you are describing should not be as bad if you try one of the Nighly builds (available [here](https://github.com/xournalpp/xournalpp/releases/tag/nightly)). Some changes made in #3480 should have improved this. Those changes will however not appear in a stable release before version 1.2 (whose release is not yet scheduled -- it could take years).

So I'd advise you to try out the [Nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) and see if things are better.

**Comment by ldshou** [comment] 2022-02-18 07:30
Thank you for your quick response, @bhennion ! 
I did another experiment, and found that the lagging reduced significantly when I "Hide the vertical scroll bar" & "Hide the horizontal bar" in the View preference! With both scroll bars hidden, the lagging is much better now on a low-resolution external display. But still a bit bad on the iMac built-in retina screen. 
The polygonal problem can be solved by turning the Arithmetic Mean on for the input system. 

With these settings, and by slowing the pen a little bit, I would say the pen strokes are mostly okay now.

**Comment by gh4n** [comment] 2022-03-01 22:56
@bhennion, I have tried the most recent nightly build and it seems like the lagging did not improve. @ldshou, I can't see the scroll bar options you described which version are you using? I noticed that the lagging improved when "presentation mode" was enabled.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/28796511/156262770-8cda94b6-c508-4939-b400-923bc99c4891.png">

**Comment by rolandlo** [comment] 2022-03-29 18:05
We have just updated the Gtk version for the MacOS version (from 3.24.30 to 3.24.33) and also the Cairo version (drawing library). Using the installer [here](https://github.com/xournalpp/xournalpp/pull/3933#issuecomment-1082199975) I do observe some performance improvement on BigSur, although it's still quite a bit worse than on Linux and Windows. Can anybody check if he or she observes a performance gain as well?

**Comment by borisPristupa** [comment] 2022-04-20 11:47
@rolandlo definitely smoother on BigSur, thank you!

**Comment by geier1993** [comment] 2022-11-28 10:52
I got a Mac from work and use an build from August 16, 2022 with libgtk 3.24.33.
There is still an delay. Compared to the experience on linux it's horrible... :(
(With mouse and pen, guess it's the same problem)

**Comment by rolandlo** [comment] 2022-11-28 11:09
@geier1993 You are right about that. In the meantime Gtk 3.24.35 has been released with drastic improvements for rendering on MacOS. Once Gtk 3.24.35 makes it into `gtk-osx` we will rebuild Xournal++ and mac users should have a smooth experience as well. Hopefully it will be ready for the 1.2.0 release.
In the meantime, consider using the stroke stabilizer in the input system tab in menu `Edit > Preferences`. With settings tuned to your device it will already look quite a bit smoother.

**Comment by geier1993** [comment] 2022-11-28 13:08
ah that are good news. Without stabilizer drawings and "signatures" look ugly 😒

**Comment by rolandlo** [comment] 2022-12-17 09:09
The latest nightly build uses Gtk `3.24.35`. The lag is fixed there. Please install the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) or wait for the release of version 1.2.0.

**Closed by rolandlo** 2022-12-17 09:09 UTC
Labels: bug, os::mac
