### ISSUE TITLE
CRITICAL: GtkSourceView :: gtk_source_style_scheme_get_id: assertion 'GTK_SOURCE_IS_STYLE_SCHEME (scheme)' failed

### ISSUE THREAD

**Issue by Robin-Sch** [xournalpp/xournalpp#5150] opened 2023-09-15 11:37 UTC
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

BSPWM

### (Linux Only) Display Server

X.Org

### Installation Method

AppImage

### Xournal++ Version

1.2.1

### libgtk Version

3.24.20

### Bug Description

When I open preferences and press "ok", xournalpp crashes. No matter whether I change a preference or keep everything the same.

### Expected Behaviour

Xournalpp should not crash (and should save the preferences)

### Steps to Reproduce

1. Open xournalpp
2. Open preferences
3. Press "ok"

### Additional Context

Error: GtkSourceView :: gtk_source_style_scheme_get_id: assertion 'GTK_SOURCE_IS_STYLE_SCHEME (scheme)' failed

**Comment by rolandlo** [comment] 2023-09-15 11:42
Duplicate of #5094
Sorry for the inconvenience, but currently you need to install gtksourceview4 separately on your system. On Arch you should find it in the Extra repo.

**Closed by rolandlo** 2023-09-15 11:42 UTC
Labels: bug
