### ISSUE TITLE
The app was closed unexpectedly while I was writing with a graphics tablet

### ISSUE THREAD

**Issue by AnnaBlok** [xournalpp/xournalpp#5219] opened 2023-10-09 15:59 UTC
### Operating System

Linux

### (Linux only) Distribution

ubuntu 

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

None

### Installation Method

snap

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

The app was closed unexpectedly while I was writing with a graphics tablet

### Expected Behaviour

Not closing

### Steps to Reproduce

I don't know, I was writing and that's it.
[errorlog.20231009-185323.log](https://github.com/xournalpp/xournalpp/files/12848202/errorlog.20231009-185323.log)

**Comment by bhennion** [comment] 2023-10-10 09:43
Duplicate of #5087 
It should be fixed in the upcoming 1.2.2 release.

**Closed by bhennion** 2023-10-10 09:43 UTC
Labels: bug
