### ISSUE TITLE
Selecting image moves it to "top", cannot be undone

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#2441] opened 2020-11-24 21:12 UTC
**Affects versions :**
 - OS: Linux (Ubuntu 20.04, X11)
 - `xournalpp --version`:
    - Xournal++ 1.0.19 
    - libgtk: 3.24.20 
 - Installation method: built package from git

**Describe the bug**
When pasting an image into a document, drawing on it, and then selecting (not even moving) the image, the image is moved to the "top", obscuring the handwritten text & annotations. This is an issue for me as I often want to draw onto a photo (e.g. mark points of interest), and then move the image around only to have all of my annotations disappear "beneath" the image. Ideally, the images would always be "below" the written text even when moving the image (hard to imagine anyone wanting to layer an image over hand-written annotations). 

Undo does not allow to go back to the original. 

**To Reproduce**
1. Copy a picture (e.g. right-click and copy this [image](https://user-images.githubusercontent.com/3056063/100151555-2489ae00-2e56-11eb-9e5b-0c8a49cd871a.png)
2. Paste into xournalpp (I use ctrl-v)
3. Annotate it with e.g. a pen, say encircling the green "K"
4. Using Tools>Select Region, click on the pasted image to select it
5. Notice that your annotation is no longer visible, as it is obscured by the image. 
6. Try to Undo (Ctrl-z), note that it does not return. 

**Expected behavior**
The "order" of image and written annotations is not affected by selecting the image, or by moving it. "Undo" acts also on changes in display order.

**Comment by rolandlo** [comment] 2020-11-25 06:01
The selection algorithm is improvedt in version 1.1.0+dev. You may want to try it out.
I couldn't reproduce the image being moved to the top. Does that depend on where the image is pasted (e.g. whether it overlaps the page borders)?

**Comment by markwmuller** [comment] 2020-11-25 16:44
I've made a video showing the behavior here -- https://youtu.be/HA0kciMAq_s

Doesn't seem to matter where the image is pasted.

**Comment by rolandlo** [comment] 2020-11-25 17:02
Sorry, seems I misunderstood. Yes, in versions 1.0.x what you select is moved "to the top", i.e. covering other elements at the same position. In version 1.1.0+dev however, things that you select are only moved "to the top" while it is selected (so you can see it even if it is covered by other elements). After finishing the selection the original order is restored (automatically).

**Comment by markwmuller** [comment] 2020-11-25 17:53
OK, thanks @rolandlo . How do I try the 1.1.0+dev? I can't find a branch or tag by that name, am I missing something? Do you know when this will be released? (I use X++ to lecture a class with 100 students, I'd prefer to minimize real-time surprises :)  )

**Comment by rolandlo** [comment] 2020-11-25 18:02
You can find it under the [nightly tag](https://github.com/xournalpp/xournalpp/releases/tag/nightly). 
There is no fixed release day for version 1.1.0, but we are working hard to release it as soon as possible. 

Another option would be to install the latest nightly release from [PPA](https://xournalpp.github.io/installation/#ubuntu-and-derivatives), but ff you want to minimize real time surprises, you better stick with one version for a while instead of upgrading nearly every day.

**Comment by markwmuller** [comment] 2020-11-25 18:29
Can confirm that latest master does not show this issue. I'll stick with 1.0.19 for now though :)

**Comment by rolandlo** [comment] 2020-11-25 20:04
I will close this issue, since the selection behavior in version 1.0.19 is not really a bug, just a different (arguably weaker) algorithm (compared to the one from version 1.1.0+dev) for how to deal with selections.

**Closed by rolandlo** 2020-11-25 20:04 UTC
Labels: bug
