### ISSUE TITLE
Doesn't detect pdflatex in PATH

### ISSUE THREAD

**Issue by SwiftWinds** [xournalpp/xournalpp#3048] opened 2021-04-19 06:57 UTC
**Affects versions :**
 - OS: macOS Big Sur 11.2.3
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.1.0+dev commit 1002c131
 - Installation method: official release

**Describe the bug**
When I try to annotate a PDF with the Add/Edit Tex button, an error pops up saying it cannot find `pdflatex` in PATH, even though it is in PATH.

**To Reproduce**
1. download version 1.1.0+dev of Xournal++ from https://github.com/xournalpp/xournalpp/releases/tag/nightly
2. click File -> Annotate PDF and select any PDF
3. click Add/Edit Tex
4. observe error

**Expected behavior**
For there not to be an error and to successfully add LaTeX to the PDF.

**Screenshots of Problem**

Error popup:
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/12981958/115193830-84048680-a0a1-11eb-996e-b186e877a447.png">

`pdflatex` is in my PATH:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/12981958/115193841-88c93a80-a0a1-11eb-8959-fce762886927.png">

**Additional context**
Many thanks for the fantastic PDF annotation software. I hope you will consider my request to make this app even better! :)

**Comment by rolandlo** [comment] 2021-04-19 08:43
This is a duplicate of #1723. 

The thing is that the environment variables (including the PATH variable) in MacOS are not passed to GUI applications if you start them from the GUI. You can start Xournal++ from the Terminal by typing `open Xournal++.app` in the folder where you have the `Xournal++.app` bundle. Then the PATH variable should be set correctly.

**Comment by SwiftWinds** [comment] 2021-04-20 03:23
Ahh, now it works. Any chance of a workaround so I don't need to launch Xournal++ from the terminal each time I want to use it?

**Comment by personalizedrefrigerator** [comment] 2021-04-21 00:38
> Any chance of a workaround so I don't need to launch Xournal++ from the terminal each time I want to use it?

Does changing `pdflatex` to `/Library/TeX/texbin/pdflatex` work for you? This can be done (in v1.1.0+dev) in Settings/LaTeX.
![Settings: Latex settings: Change command to library slash tex slash texbin slash pdflatex](https://user-images.githubusercontent.com/46334387/115480329-1ec6a780-a1ff-11eb-9d61-6f70e009678a.png)

**Comment by rolandlo** [comment] 2021-04-21 18:35
@personalizedrefrigerator That does work indeed! I just tested it on MacOS Catalina.

**Comment by rolandlo** [comment] 2021-04-21 19:15
I would suggest to make `/Library/TeX/texbin/pdflatex -interaction=nonstopmode '{}'` the default LaTeX generation command on MacOS. This folder is the default installation folder for `MacTeX` on any recent system, so it should make the LaTeX tool work out of the box for MacOS users without any need to launch from terminal or to modify the LaTeX generation command.

**Comment by SwiftWinds** [comment] 2021-04-23 17:13
> > Any chance of a workaround so I don't need to launch Xournal++ from the terminal each time I want to use it?
> 
> 
> 
> Does changing `pdflatex` to `/Library/TeX/texbin/pdflatex` work for you? This can be done (in v1.1.0+dev) in Settings/LaTeX.
> 
> ![Settings: Latex settings: Change command to library slash tex slash texbin slash pdflatex](https://user-images.githubusercontent.com/46334387/115480329-1ec6a780-a1ff-11eb-9d61-6f70e009678a.png)
> 
> 
> 
> 

This works for me too! Thank you 🎉👏

**Closed** 2021-04-23 20:28 UTC
Labels: bug

**Comment by ElBi21** [comment] 2024-05-05 16:31
As @personalizedrefrigerator said, by changing `pdflatex` with the absolute path of the executable then Xournal++ works perfectly. Tried on Pop!_OS, so the solution should work on Linux too. Kudos
