### ISSUE TITLE
List of recent files not appearing

### ISSUE THREAD

**Issue by Flinxcoder** [xournalpp/xournalpp#2994] opened 2021-04-02 11:32 UTC
**Affects versions :**

OS: Linux Mint 19
(Linux only) Desktop environment: X11
Version of  xournalpp-1.1.0.dev-nightly.20210329-x86_64.AppImage
Installation method: AppImage

**Describe the bug:**

Current version does not  show the list of recent files.
Instead a narrow box is displayed. (see screenshot)

Regards

![Xournal_Screenshot 2021-04-02 13-16-32](https://user-images.githubusercontent.com/49238945/113411817-0a894a80-93b7-11eb-873a-34598a2964df.png)

**Comment by personalizedrefrigerator** [comment] 2021-04-02 12:14
See also https://github.com/xournalpp/xournalpp/issues/1970

**Comment by thirschbuechler** [comment] 2021-04-03 18:14
The issue could be your gtk recentmanager list itself (not xournalpp), does[ this python stackoverflow script (in the question)](https://stackoverflow.com/questions/39836725/how-does-one-add-an-item-to-gtks-recently-used-file-list-from-python/39927261), which prints recent files as registered, print any `xopp` or `pdfs`?

**Comment by Febbe** [comment] 2021-04-03 20:44
Maybe it is caused by undefined behavior fixed in #2999, but as long, as this is not reproducible, we can only clean up and read our code.

**Comment by bhennion** [comment] 2023-05-01 07:56
Our handling of the gtk_recent_manager has been refactored in #4448. Hopefully this was fixed in the process. Closing this issue. Please reopen if this still occurs on latest master or nightly build.

**Closed by bhennion** 2023-05-01 07:56 UTC
Labels: bug, orphaned
