### ISSUE TITLE
Failing assert in RenderJob::rerenderRect()

### ISSUE THREAD

**Issue by Talha76** [xournalpp/xournalpp#4991] opened 2023-08-02 07:58 UTC
**OS:** Ubuntu 20.04.6 LTS x86_64
**Kernel:** 5.15.0-78-generic
**WM:** i3
**Xournal++ version:** 1.2.0
**Error:** signal 6

The log file is attached here.
[errorlog.20230801-194040.log](https://github.com/xournalpp/xournalpp/files/12237573/errorlog.20230801-194040.log)

**Comment by bhennion** [comment] 2023-08-08 16:07
Thanks for reporting! From the crashlog, it is most likely this assert that fails
https://github.com/xournalpp/xournalpp/blob/5ef49b7d8f5ce7e7d32038db3e08adcf211783c6/src/core/control/jobs/RenderJob.cpp#L49
This is very weird.

Does this happen a lot (with the same backtrace)? If so, do you have a way to reproduce? or even the time to try out the last nightly build? -- this would give us a more detailled crashlog and the precise failing assertion --

**Comment by bhennion** [comment] 2023-08-14 02:33
The bug report #5046 is a duplicate of this one, but it is more detailled and contains a how-to reproduce.
Closing this in favor of #5046.

**Closed by bhennion** 2023-08-14 02:33 UTC
Labels: bug, priority::high, Crash, rendering, regression
