### ISSUE TITLE
Scroll does not work in zoom to fit

### ISSUE THREAD

**Issue by ar13pit** [xournalpp/xournalpp#1799] opened 2020-03-25 15:21 UTC
**Affects versions :**
 - OS: Ubuntu 18.04
 - Desktop environment: X11
 - Which version of libgtk do you use: I have both 2.24 and 3.22 installed
 - Version of Xournal++: 1.0.16 or 1.1.0+dev
 - Installation method: PPA

**Describe the bug**
Scrolling does not work when the document is zoom to fit. After zooming in/out it works again.

**To Reproduce**
1. Open an empty document
2. Zoom to fit
3. Try scrolling (Does not work)
4. Zoom In/Out
5. Try scrolling (Starts working again)

**Expected behavior**
Scrolling should work irrespective of zoom.

**Comment by Febbe** [comment] 2020-03-25 21:15
Duplicate of #1795.
Nevertheless, do you have the GTK/Scrolling workaround enabled (Edit -> Preferences -> Touchscreen -> Workaround).
If yes deactivate it.

**Closed** 2020-03-25 21:15 UTC
Labels: bug
