### ISSUE TITLE
[Feature request] Separate font family and style (font size, bold, italic, underlined)

### ISSUE THREAD

**Issue by renatobellotti** [xournalpp/xournalpp#3698] opened 2022-01-05 08:14 UTC
I'm new to Xournal++, but afaik it is not possible to make a single letter or word bold.

Is it possible to split the font button into several buttons (font family, font size, bold, italic, underlined) like e. g. in LibreOffice?

**Comment by netlimpopo** [comment] 2022-01-06 09:26
Correct. Right now in a standard text field one can only apply changes to the whole textfield (all bold, all italic, different font). 
A workaround with textfields is leaving space inbetween then put another textfield at the blank position on top. 
Alternatively one can use latex textfields and for instance \textbf{...} to apply the bold font. A LaTex textfield on the other hand is highly customiseable. 
There are several attempts to bring your requested feature into xournal++ in the future.
#3408  #1430  also markdownsupport #3659 #1092. 
Also a new file format is in discussion. We will see which version will be implemented first in the future.

**Comment by bhennion** [comment] 2023-09-14 14:42
Duplicate of #729

**Closed by bhennion** 2023-09-14 14:42 UTC
Labels: enhancement
