### ISSUE TITLE
Strip .pdf from default filename for annotated PDFs.

### ISSUE THREAD

**Issue by Fraetor** [xournalpp/xournalpp#2813] opened 2021-02-17 01:44 UTC
**Affects versions :**
 - OS: Linux (Debian Unstable)
 - (Linux only) Desktop environment: X11
 - Version of libgtk: 3.24.21
 - Version of Xournal++: 1.0.20
 - Installation method: Flatpak

**Describe the bug**
When you save a file created with Annotate PDF, the default filename keeps the original extension. E.g. `FILENAME.pdf` is saved as `FILENAME.pdf.xopp`

**To Reproduce**
1. Annotate a PDF, and save the .xopp file.
2. Observe the saved file with the double extension `.pdf.xopp`

**Expected behavior**
The `.pdf` is stripped from the filename, and it is saved as `FILENAME.xopp`

**Comment by Technius** [comment] 2021-02-17 09:13
Duplicate of #1754.

**Closed by Technius** 2021-02-17 09:13 UTC
Labels: bug
