### ISSUE TITLE
1.0.17 is broken: cs.gmo: No such file or directory.

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#1731] opened 2020-02-05 02:00 UTC
```
  file INSTALL cannot find
  "/usr/ports/graphics/xournalpp/work/.build/po/cs.gmo": No such file or
  directory.
```

**Comment by nicegamer7** [comment] 2020-02-05 05:27
Possibly realted to #1596?

**Comment by Technius** [comment] 2020-02-05 06:08
Closing as duplicate of #1596.

**Closed by Technius** 2020-02-05 06:08 UTC
Labels: bug
