### ISSUE TITLE
Bad positioning of eterogeneous elements in the exported pdf by a xournal file

### ISSUE THREAD

**Issue by LittarruFrancesco** [xournalpp/xournalpp#2104] opened 2020-07-08 09:18 UTC
**Affects versions :1.0.15**
 - OS: Ubuntu 18.04 LTS
 - (Linux only) Desktop environment: MATE
 - version of libgtk: 3.22.30-1ubuntu4
 - Version of Xournal++: 1.0.15
 - Installation method: official release

**Describe the bug**
I made a xournalpp page with eterogeneous elements like images, text, and markers.
The page is just one, but with many small elements.
When exported in pdf, some elements are overlapping and others are moved downwards (text over images and marker in different positions).

**To Reproduce**
1. Open a new xopp file
2. Edit a page with eterogeneous elements, in my case: texts, images, markers
3. Export in pdf
4. The pdf file should look exactly like the xopp one.

**Expected behavior**
I expect the pdf to look identical to the xopp file I designed.

**Screenshots of Problem**
![xournal_bug_comparison_bad_positioning_after_pdf_exportation](https://user-images.githubusercontent.com/11428019/86901265-aa59c680-c10c-11ea-8073-b24d710c809b.png)

Edit: the screen res is 1080p. (PCSpecialist Cosmos VII)

**Comment by rolandlo** [comment] 2020-07-13 06:20
duplicate of  #1390

**Comment by rolandlo** [comment] 2020-07-23 17:41
I may have closed this issue prematurely. Could you please provide the xopp-file for testing purposes? You can do it by renaming the file as .txt and dragging it into the text field that you use to answer.

**Comment by LittarruFrancesco** [comment] 2020-07-23 17:55
Yes sure!
[Input_Capture_Mode.txt](https://github.com/xournalpp/xournalpp/files/4967887/Input_Capture_Mode.txt)

I also tried to open it in another computer with the same OS and the same Xournal version but with screen res of 1366*768 instead of 1080p and the file in xournal++ is formatted even worse than the pdf version of that in 1080p

**Comment by rolandlo** [comment] 2020-07-27 09:02
It is a bit complicated, since we apparently get different output with different versions and different computers. Still one central question is whether the bug is only specific to the text handling (line spacing) or not. From my tests with your document so far I would bet on the former. 

I have extracted the text into one xopp-file 
[Input_Capture_Mode_Text.txt](https://github.com/xournalpp/xournalpp/files/4980924/Input_Capture_Mode_Text.txt)
and all the rest into another xopp file.
[Input_Capture_Mode_Rest.txt](https://github.com/xournalpp/xournalpp/files/4980927/Input_Capture_Mode_Rest.txt)

Could you please make the following test using the two files (after renaming to .xopp) and the original xopp file:

1. Export all of the 3 xopp-files to pdf.
2. Open the 3 pdfs with evince (or another pdf viewer) and arrange them from left to right (all with the same zoom ) like I did below:
![Pdfs](https://user-images.githubusercontent.com/40485433/88523005-8694ec80-cff7-11ea-8ef0-7a8750753c03.png)
3. Check if the content of the pdf export of the full document is exactly the "sum" of the pdf-exports of the two parts. (in my test this seems to be the case). 
4. Compare the text xopp-file with its pdf export (using the same zoom). Can you see any difference?
5. Compare the rest xopp-file with its pdf export (using the same zoom). Can you see any difference?

**Comment by Photon89** [comment] 2021-05-09 09:37
Looks like the bug in Pango has been fixed finally! https://gitlab.gnome.org/GNOME/pango/-/issues/499

**Comment by rolandlo** [comment] 2021-05-09 19:55
> I've prepared the [fixed](https://gitlab.gnome.org/GNOME/pango/-/commit/1661f1b2c1651009c324f851eeee1957db097910) Pango, and built xournalpp with reference to #2182:

Thanks for working on this. Could you share some details on how you prepared the fixed Pango?

**Comment by tattsan** [comment] 2021-05-10 00:48
I only applied [this patch](https://gitlab.gnome.org/GNOME/pango/-/commit/1661f1b2c1651009c324f851eeee1957db097910) to the current release of pango-1.48.4 , and built it with Arch Linux official PKGBUILD. There have been many commits since 1.48.4 was released, so I might have been better off trying the current master. The version number of pango master was bumped to 1.49 one month ago.

**Comment by tattsan** [comment] 2021-05-19 06:23
pango-1.48.5 has been released. The empty line spacing bug is fixed.

**Comment by rolandlo** [comment] 2021-06-13 21:15
Fixed by PR #2182.

**Closed by rolandlo** 2021-06-13 21:15 UTC
Labels: bug
