### ISSUE TITLE
"Draw Line" does not work properly (Lines disappear) when "Grid Snapping" is off

### ISSUE THREAD

**Issue by malnaanah** [xournalpp/xournalpp#1585] opened 2019-11-03 09:50 UTC
Lines disappear when trying to draw lines while Grid snapping is off.

I use version 1.0.15 on  Kubuntu 19.04.

See the video:

https://youtu.be/DYhDdHCZrX8

**Comment by Technius** [comment] 2019-11-06 00:09
Duplicate of #1580.

**Closed by Technius** 2019-11-06 00:09 UTC
Labels: bug, confirmed, priority: high
