### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by opaluja** [xournalpp/xournalpp#5000] opened 2023-08-03 13:25 UTC
Date: Thu Aug  3 08:20:53 2023
Error: signal 11
Xournal++ version 1.2.0
Git commit: 10ed72c9
Gtk version 3.24.38

[bt]: (0) /snap/xournalpp/82/usr/bin/xournalpp(+0x3e14d5) [0x55dc6bf094d5]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fb516ca4520]
[bt]: (2) /snap/xournalpp/82/usr/bin/xournalpp(_ZNKSt6vectorI10NamedColorSaIS0_EE4sizeEv+0x10) [0x55dc6bfb853a]
[bt]: (3) /snap/xournalpp/82/usr/bin/xournalpp(_ZNK7Palette10getColorAtEm+0x24) [0x55dc6bfb7408]
[bt]: (4) /snap/xournalpp/82/usr/bin/xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0x868) [0x55dc6bfa22ca]
[bt]: (5) /snap/xournalpp/82/usr/bin/xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0xc5) [0x55dc6bf7ceb5]
[bt]: (6) /snap/xournalpp/82/usr/bin/xournalpp(_ZN10MainWindow15toolbarSelectedEP11ToolbarData+0x78) [0x55dc6bf7cd54]
[bt]: (7) /snap/xournalpp/82/usr/bin/xournalpp(_ZN10MainWindow15toolbarSelectedERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xc7) [0x55dc6bf7ccbd]
[bt]: (8) /snap/xournalpp/82/usr/bin/xournalpp(+0x476b17) [0x55dc6bf9eb17]
[bt]: (9) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7fb5174fa2ef]
[bt]: (10) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c713) [0x7fb517510713]
[bt]: (11) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11bd) [0x7fb51751ba7d]
[bt]: (12) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fb51751bf23]
[bt]: (13) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xfb3bb) [0x7fb51767b3bb]
[bt]: (14) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_action_activate+0x65) [0x7fb517679975]
[bt]: (15) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x24610e) [0x7fb517b8410e]
[bt]: (16) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7fb5174fa2ef]
[bt]: (17) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c713) [0x7fb517510713]
[bt]: (18) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11bd) [0x7fb51751ba7d]
[bt]: (19) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fb51751bf23]
[bt]: (20) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_activate+0x5c) [0x7fb517cdb2ac]
[bt]: (21) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_menu_shell_activate_item+0x13e) [0x7fb517b7fe3e]
[bt]: (22) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x242113) [0x7fb517b80113]
[bt]: (23) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x9b058) [0x7fb5179d9058]
[bt]: (24) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x16529) [0x7fb5174fa529]
[bt]: (25) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x38b) [0x7fb51751ac4b]
[bt]: (26) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fb51751bf23]
[bt]: (27) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x399a14) [0x7fb517cd7a14]
[bt]: (28) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x22a360) [0x7fb517b68360]
[bt]: (29) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x7f5) [0x7fb517b6a315]
[bt]: (30) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x40e19) [0x7fb517862e19]
[bt]: (31) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0xa4a26) [0x7fb5178c6a26]
[bt]: (32) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27b) [0x7fb5173eb64b]
[bt]: (33) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x62908) [0x7fb5173eb908]
[bt]: (34) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fb5173eb9d3]
[bt]: (35) /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7fb517671df5]
[bt]: (36) /snap/xournalpp/82/usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x794) [0x55dc6bf1166d]
[bt]: (37) /snap/xournalpp/82/usr/bin/xournalpp(main+0x29) [0x55dc6bf09092]
[bt]: (38) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fb516c8bd90]
[bt]: (39) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fb516c8be40]
[bt]: (40) /snap/xournalpp/82/usr/bin/xournalpp(_start+0x25) [0x55dc6bf08fa5]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/82/usr/bin/xournalpp(+0x3e1be7) [0x55dc6bf09be7]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fb516ca4520]
??:0
[bt] #3 /snap/xournalpp/82/usr/bin/xournalpp(_ZNKSt6vectorI10NamedColorSaIS0_EE4sizeEv+0x10) [0x55dc6bfb853a]
??:0
[bt] #4 /snap/xournalpp/82/usr/bin/xournalpp(_ZNK7Palette10getColorAtEm+0x24) [0x55dc6bfb7408]
??:0
[bt] #5 /snap/xournalpp/82/usr/bin/xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0x868) [0x55dc6bfa22ca]
??:0
[bt] #6 /snap/xournalpp/82/usr/bin/xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0xc5) [0x55dc6bf7ceb5]
??:0
[bt] #7 /snap/xournalpp/82/usr/bin/xournalpp(_ZN10MainWindow15toolbarSelectedEP11ToolbarData+0x78) [0x55dc6bf7cd54]
??:0
[bt] #8 /snap/xournalpp/82/usr/bin/xournalpp(_ZN10MainWindow15toolbarSelectedERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xc7) [0x55dc6bf7ccbd]
??:0
[bt] #9 /snap/xournalpp/82/usr/bin/xournalpp(+0x476b17) [0x55dc6bf9eb17]
??:0
[bt] #10 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7fb5174fa2ef]
??:0
[bt] #11 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c713) [0x7fb517510713]
??:0
[bt] #12 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11bd) [0x7fb51751ba7d]
??:0
[bt] #13 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fb51751bf23]
??:0
[bt] #14 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xfb3bb) [0x7fb51767b3bb]
??:0
[bt] #15 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_action_activate+0x65) [0x7fb517679975]
??:0
[bt] #16 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x24610e) [0x7fb517b8410e]
??:0
[bt] #17 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7fb5174fa2ef]
??:0
[bt] #18 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2c713) [0x7fb517510713]
??:0
[bt] #19 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11bd) [0x7fb51751ba7d]
??:0
[bt] #20 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fb51751bf23]
??:0
[bt] #21 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_activate+0x5c) [0x7fb517cdb2ac]
??:0
[bt] #22 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_menu_shell_activate_item+0x13e) [0x7fb517b7fe3e]
??:0
[bt] #23 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x242113) [0x7fb517b80113]
??:0
[bt] #24 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x9b058) [0x7fb5179d9058]
??:0
[bt] #25 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x16529) [0x7fb5174fa529]
??:0
[bt] #26 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x38b) [0x7fb51751ac4b]
??:0
[bt] #27 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7fb51751bf23]
??:0
[bt] #28 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x399a14) [0x7fb517cd7a14]
??:0
[bt] #29 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x22a360) [0x7fb517b68360]
??:0
[bt] #30 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x7f5) [0x7fb517b6a315]
??:0
[bt] #31 /snap/xournalpp/82/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x40e19) [0x7fb517862e19]
??:0

Execution log:

DEBUG   : GLib-GIO :: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
DEBUG   : GLib-GIO :: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
DEBUG   : GLib :: unsetenv() is not thread-safe and should not be used after threads are created
MESSAGE : xopp :: TEXTDOMAINDIR = /snap/xournalpp/82/usr/share/locale, Platform-specific locale dir = /usr/share/xournalpp/../locale, chosen directory = /snap/xournalpp/82/usr/share/locale
WARNING : xopp :: configfile does not exist /home/paula/snap/xournalpp/82/.config/xournalpp/settings.xml

INFO    : xopp :: Loading plugins from: /snap/xournalpp/82/usr/share/xournalpp/plugins
INFO    : xopp :: Loading plugins from: /home/paula/snap/xournalpp/82/.config/xournalpp/plugins
MESSAGE : xopp :: Plugin "MigrateFontSizes" UI initialized
MESSAGE : xopp :: Using default latex template in /snap/xournalpp/82/usr/share/xournalpp/resources/default_template.tex
WARNING : xopp :: [Crash Handler] Crashed with signal 11
WARNING : xopp :: [Crash Handler] Wrote crash log to: /home/paula/snap/xournalpp/common/.cache/xournalpp/errorlogs/errorlog.20230803-082053.log

**Comment by rolandlo** [comment] 2023-08-03 13:29
Duplicate of #4997
Just restart Xournal++, delete the crashlog and everything should be fine.

**Closed by rolandlo** 2023-08-03 13:29 UTC
