### ISSUE TITLE
Memory leak - rectangle

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#90] opened 2014-05-20 04:21 UTC
Closing an open document with a selected object leaks 1 rectangle. This isn't serious but can be fixed easily.

**Comment by wbrenna** [comment] 2016-05-24 19:55
To replicate, save an xoj containing some strokes. Open that file, select them, and close. This remains even after the clearSelectionEndText() that's being called in close() now.

**Comment by andreasb242** [comment] 2018-11-17 17:49
The problem is the RepaintWidgetHandler which is static in the .cpp file.
This needs to be fixed with threading. #93

**Closed** 2018-11-17 21:45 UTC
Labels: bug, low prio
