### ISSUE TITLE
[Bug] Error loading libpoppler.so while running xournalpp-1.1.0.dev-nightly.20200920-x86_64.AppImage

### ISSUE THREAD

**Issue by malnaanah** [xournalpp/xournalpp#2260] opened 2020-09-20 18:58 UTC
The appimage does not run and I get the following message when running xournalpp-1.1.0.dev-nightly.20200920-x86_64.AppImage

/tmp/.mount_xournahBx2HU/usr/bin/xournalpp: error while loading shared libraries: libpoppler.so.73: cannot open shared object file: No such file or directory

I use Kubuntu 20.04

What doe you think is the problem?

Regards,

**Comment by Technius** [comment] 2020-09-20 19:11
Looks like poppler is not being copied by the AppImage build.

**Comment by Technius** [comment] 2020-09-20 19:12
As a temporary workaround, I recommend you use the FlatPak instead.

**Comment by Technius** [comment] 2020-09-21 18:23
Poppler is not being copied, probably caused by linuxdeploy/linuxdeploy#145.

CI needs to check if the AppImage has linking issues (e.g. by attempting to run it on a newer distro).

**Comment by TheAssassin** [comment] 2020-09-21 22:47
@Technius can you perhaps run some A/B testing with the old possibly-known-working version mentioned in the issue and a recent build and post your logs there? That'll really help.

**Comment by Technius** [comment] 2020-09-22 19:36
I have confirmed that the upstream fix (linuxdeploy/linuxdeploy#146) works, so the issue should be resolved in the next nightly build.

**Closed by Technius** 2020-09-22 19:36 UTC
Labels: Dependency Issue, appimage, bug, buildsystem, confirmed, priority: high, regression
