### ISSUE TITLE
Crash while using hand tool

### ISSUE THREAD

**Issue by legendofa** [xournalpp/xournalpp#1666] opened 2019-12-13 17:41 UTC
Xournalpp crashes while using the hand tool.
This is only persistent when using the graphics tablet.

Input device:
- Gaomon M106K Graphics Tablet

Kernel:
- 5.3.15-1-MANJARO

Desktop Environment:
- i3

Xournalpp version:
- 1.0.16

Steps to reproduce:
1. Map the hand tool to the included pen
2. Drag the page
3. Hover over the menubar or in an other application
4. Crash

Expected behaviour:
- Stable operation of Xournalpp

[errorlog.20191213-181700.log](https://github.com/xournalpp/xournalpp/files/3961929/errorlog.20191213-181700.log)

**Comment by Technius** [comment] 2019-12-14 20:49
I cannot reproduce the bug. Can you upload a GIF/video showing how you triggered the crash, as well as the [input debugging logs](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs)?

**Comment by legendofa** [comment] 2019-12-17 19:10
This is the crash, it is not 100% reproducable.

![crash](https://user-images.githubusercontent.com/34162874/71024780-8ea1bb00-20fd-11ea-9943-34bc9a9100d7.gif)

Interestingly the hand tool does not work in the self compiled logging version of Xournalpp.
Here is a GIF of the behaviour.

![brokentool](https://user-images.githubusercontent.com/34162874/71025875-e8a38000-20ff-11ea-84ec-c305edd478e4.gif)

Input Logs:
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/3974992/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/3974993/debug_input.log)

**Comment by LittleHuba** [comment] 2019-12-18 13:41
You are using the old input system for the version where it crashes. Hence we won't fix that bug. Most likely the self compiled version uses the new input system which has an open ticket for buggy hand tool. For some people it doesn't work while for others it does.

**Comment by LittleHuba** [comment] 2019-12-18 13:42
For this reason I'll close the ticket. The other bug is handled in #1501 if I'm not mistaken.

**Closed** 2019-12-18 13:43 UTC
Labels: Crash, Input, bug, need info
