### ISSUE TITLE
Easier way to change z-index or layers for objects (in order to move it to the fg or bg)

### ISSUE THREAD

**Issue by ericschdt** [xournalpp/xournalpp#2670] opened 2021-01-14 15:51 UTC
**Is your feature request related to a problem? Please describe.**
I first inserted an image in a Xournal++ document and the draw on it when I noticed I chose the wrong version of the image.

So I selected the image and removed it and dragged/dropped the other version in. Now I want to place it behind my writings as it was for the image before. 

**Describe the solution you'd like**
I'd like to select a z-index for the image object or right click and select "move to background". 

**Describe alternatives you've considered**
Create a new layer, paste the image there. 

**Additional context**
Maybe the alternative solution is the correct one, but it would be nice if this could be automated somehow. :)

**Comment by Technius** [comment] 2021-01-14 20:27
Duplicate of #810.

**Closed by Technius** 2021-01-14 20:27 UTC
Labels: enhancement
