### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marceloliveirali** [xournalpp/xournalpp#5047] opened 2023-08-13 13:58 UTC
Date: Tue May  2 11:47:52 2023
Error: signal 11
[bt]: (0) xournalpp(+0x1b06b8) [0x55b3cea8e6b8]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7eff98642520]
[bt]: (2) xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x21) [0x55b3cea847a1]
[bt]: (3) xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x84) [0x55b3cea849c4]
[bt]: (4) xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xf4) [0x55b3cea84ad4]
[bt]: (5) xournalpp(_ZN10PreviewJob8drawPageEv+0x362) [0x55b3ce9afd02]
[bt]: (6) xournalpp(_ZN10PreviewJob3runEv+0x6f) [0x55b3ce9afe0f]
[bt]: (7) xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x102) [0x55b3ce9ab9b2]
[bt]: (8) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x84a51) [0x7eff99e91a51]
[bt]: (9) /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7eff98694b43]
[bt]: (10) /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7eff98726a00]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0x1b0b5d) [0x55b3cea8eb5d]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7eff98642520]
??:0
[bt] #3 xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x21) [0x55b3cea847a1]
??:0
[bt] #4 xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x84) [0x55b3cea849c4]
??:0
[bt] #5 xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xf4) [0x55b3cea84ad4]
??:0
[bt] #6 xournalpp(_ZN10PreviewJob8drawPageEv+0x362) [0x55b3ce9afd02]
??:0
[bt] #7 xournalpp(_ZN10PreviewJob3runEv+0x6f) [0x55b3ce9afe0f]
??:0
[bt] #8 xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x102) [0x55b3ce9ab9b2]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x84a51) [0x7eff99e91a51]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7eff98694b43]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7eff98726a00]
??:0

**Comment by bhennion** [comment] 2023-08-13 18:25
Duplicate of #4917

**Closed** 2023-08-13 18:25 UTC
