### ISSUE TITLE
Pen issue on Surface Pro 6

### ISSUE THREAD

**Issue by SamLukeYes** [xournalpp/xournalpp#1976] opened 2020-05-14 02:22 UTC
**Affects versions :**
 - OS: Windows 10
 - _Where to find the libgtk version on Windows?_
 - Version of Xournal++: 1.0.18
 - Installation method: official release

**Describe the bug**
Pressure sensitivity and eraser doesn't work with Surface Pen. When I want to erase something with the pen's eraser, it draws a new line instead.

**To Reproduce**
1. Open Xournal++ with pressure sensitivity enabled.
2. Draw a line with Surface Pen.
3. Draw another line with lighter pressure.
4. Use the pen's eraser to erase the two lines.

**Expected behavior**
The first line should be wider than the second one, and they should be erased by the eraser later.

**Additional context**
Everything works as expected with Manjaro Cinnamon (Kernel: linux-4.19.114-surface-lts) on the same device. It's a bit strange that it doesn't work on Windows.

**Comment by Technius** [comment] 2020-05-15 01:22
This seems like #659.

**Comment by SamLukeYes** [comment] 2020-05-15 03:10
> This seems like #659.

Maybe not the same issue. I've tried restarting xournal++ for several times, but pressure sensitivity never worked. The eraser of the pen doesn't work either.

**Comment by Faberix** [comment] 2020-05-15 13:50
I have a similar issue on Ubuntu 20.04: Since I updated this morning, the eraser button on my stylus is not working anymore (pressure sensitivity works, though). I am using a ThinkPad X1 Yoga 3rd gen with the pen that was delivered with it.

**Comment by Technius** [comment] 2020-05-16 18:24
> > This seems like #659.
> 
> Maybe not the same issue. I've tried restarting xournal++ for several times, but pressure sensitivity never worked. The eraser of the pen doesn't work either.

Then maybe it's #1346? Unfortunately, it's hard to debug these issues on Windows since we have to build with MSYS.

> I have a similar issue on Ubuntu 20.04: Since I updated this morning, the eraser button on my stylus is not working anymore (pressure sensitivity works, though). I am using a ThinkPad X1 Yoga 3rd gen with the pen that was delivered with it.

If you are using the PPA, your settings may have been altered by the recent fix to #1961.

**Comment by Faberix** [comment] 2020-05-20 11:01
> If you are using the PPA, your settings may have been altered by the recent fix to #1961.
Yes, they have been changed indeed, but even after changing them back (which I did before I wrote my comment) the eraser does not work (it draws a line instead of erasing).
What might be important to note is that my pen actually has two buttons (not an eraser on the other end of the pen); one of them never worked anyway, but I can disable the one that used to activate my eraser in previous versions with the result that nothing happens when I press it and drag the pen across the screen. So I guess that fix somehow broke the eraser activation for a device.

**Comment by Technius** [comment] 2020-05-22 00:26
> So I guess that fix somehow broke the eraser activation for a device.

Can you check out #2003?

**Comment by SamLukeYes** [comment] 2020-05-25 05:35
> > > This seems like #659.
> > 
> > 
> > Maybe not the same issue. I've tried restarting xournal++ for several times, but pressure sensitivity never worked. The eraser of the pen doesn't work either.
> 
> Then maybe it's #1346? Unfortunately, it's hard to debug these issues on Windows since we have to build with MSYS.
> 
> > I have a similar issue on Ubuntu 20.04: Since I updated this morning, the eraser button on my stylus is not working anymore (pressure sensitivity works, though). I am using a ThinkPad X1 Yoga 3rd gen with the pen that was delivered with it.
> 
> If you are using the PPA, your settings may have been altered by the recent fix to #1961.

I've found the same issue when using Wayland. #1821

**Comment by hacker1024** [comment] 2020-06-17 01:05
I don't think the Linux and Windows issues are caused by the same thing. The Windows issue is also being discussed at #2000.

**Comment by 1900011604** [comment] 2020-09-23 11:12
So how do you open the Xournal++ with pressure sensitivity enabled?

**Comment by SamLukeYes** [comment] 2020-09-23 11:38
> So how do you open the Xournal++ with pressure sensitivity enabled?

It should be enabled by default if it is supported. You can check the stylus settings in Xournal++.

**Comment by 1900011604** [comment] 2020-09-23 11:53
no. look at #693, it **is** by default open but no matter how many times I restart it or my computer IT CANNOT DETECT MY FORCE!

**Comment by SamLukeYes** [comment] 2020-09-23 12:20
> no. look at #693, it **is** by default open but no matter how many times I restart it or my computer IT CANNOT DETECT MY FORCE!

Are you using Plasma Wayland session? Pressure sensitivity didn't work when I tested on Plasma Wayland. But it's curious that it works both on Plasma Xorg session and GNOME Wayland session.

**Comment by 1900011604** [comment] 2020-09-23 12:37
No. this bug can be only seen on Win10, on Manjaro Kde Plasma it is OK

**Comment by SamLukeYes** [comment] 2020-09-23 13:07
> No. this bug can be only seen on Win10, on Manjaro Kde Plasma it is OK

So I seldom used Xournal++ on Windows.

**Comment by rolandlo** [comment] 2021-07-03 17:33
The patched GTK+ 3 has now been merged. You can copy the `libgdk-3-0.dll` and `libgtk-3-0.dll` into your [Xournal++ 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) installation as described [here](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907). This may solve the issue.

**Comment by rolandlo** [comment] 2021-07-22 19:50
The issue should be fixed in [Version 1.1.0-hotfix+1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). Please report if you experience otherwise.

**Closed by rolandlo** 2021-07-22 19:50 UTC
Labels: Input, bug, os::windows
