### ISSUE TITLE
Problem resizing a selection if I use the handle at the bottom of the selection

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2458] opened 2020-11-29 10:12 UTC
Xournal ++ version : xournalpp-1.1.0.dev-nightly.20201124-windows

I create a rectangle and then I select it.
I click on the right sizing handle of the selection. So I can stretch the rectangle without any problem.
I click on the resize handle at the bottom of the selection. So the resizing is done but taking a lot of time.

Note: This problem does not appear in Xournalpp 1.0.19

**Comment by rolandlo** [comment] 2020-11-29 11:00
It's also not in the June 12 2020 commit 8afb3841. Looks like a recent regression.

**Comment by rolandlo** [comment] 2020-11-29 11:01
The top handle has the same problem.

**Comment by rolandlo** [comment] 2020-11-29 11:21
I have found the problem. There was a missing `break` statement in `XournalppCursor::updateCursor`. This will be fixed with PR #2459.

**Closed** 2020-11-29 11:22 UTC
Labels: bug, confirmed, priority::high, regression
