### ISSUE TITLE
Crash trying to export as pdf

### ISSUE THREAD

**Issue by peterman65** [xournalpp/xournalpp#5887] opened 2024-09-25 06:51 UTC
### Operating System

Linux

### (Linux only) Distribution

XUBUNTU

### (Linux only) Desktop Environment

XFCE

### (Linux Only) Display Server

X.Org

### Installation Method

official release

### Xournal++ Version

1.2.3+dev

### libgtk Version

3.24.20

### Bug Description

When I try to export a xournal file containing a annoted pdf as a new  pdf, the program crashes

### Expected Behaviour

It should generate a pdf file with my notes.

### Steps to Reproduce

Open Xournal++
Select annotated pdf
 write something into 
Select Export as pdf
(Then the program exit directly, doing nothing, the next time  I enter xournal++ I get dialog message 'archivo de recuperación detectado'. and I can remove the file or restore the file. and another dialog in which I have five options: To report a fail; open register file; open folder of register files; remove register file; and cancel.

**Comment by rolandlo** [comment] 2024-09-27 04:46
Looks like a duplicate of #5884. Closing therefore.

**Closed by rolandlo** 2024-09-27 04:46 UTC
Labels: bug
