### ISSUE TITLE
Shapes and lines don't have the same thickness as pen tool

### ISSUE THREAD

**Issue by jclsn** [xournalpp/xournalpp#1015] opened 2019-03-26 20:42 UTC
When drawing shapes, they are exactly one level thicker than the normal pen tool. This results in having to select the shape, then making the size one level smaller and having to make it bigger after you deselected the shapes.

**Comment by LittleHuba** [comment] 2019-03-28 09:53
Unfortunately I'm unable to reproduce that issue. Shapes are drawn with the same stroke width as normal strokes. Could you make a video so I can make sure I didn't misunderstand you?

**Comment by eliasrg** [comment] 2019-04-08 21:21
I have also experienced this. It's not about the shape tools, it is because any strokes without pressure sensitivity (including shapes) tend to be approximately one size thicker than those with pressure sensitivity when written with normal pressure, at least on my machine. If I press as hard as I can, I get about the same thickness as without pressure sensitivity.
![comparison-1](https://user-images.githubusercontent.com/7657466/55757685-dd6a6180-5a54-11e9-8fad-b7348939aa8b.png)

**Comment by LittleHuba** [comment] 2019-04-08 23:12
We could assign a weighing factor to the line width of shapes, to fit the mean pressure values of the pen.
But this value might be device specific which means we need to provide some setting with a good initial value.

**Comment by LittleHuba** [comment] 2019-04-08 23:12
@andreasb242 what do you think?

**Comment by LittleHuba** [comment] 2019-09-16 15:51
This will be solved with #1170

**Comment by coldspark29** [comment] 2020-03-15 13:10
Has this already been implemented? This is really buggin me the most, when I am writing for Uni

**Comment by Technius** [comment] 2020-03-15 22:06
Not yet. But instead of a pressure curve like #1170, we could implement a few basic sliders for scaling, which would be much easier and faster to implement. Pull requests are welcome!

**Comment by alexhuntley** [comment] 2022-03-11 16:38
Without knowing anything about the codebase, I don't think it should be necessary to have device-specific settings to tune.

Wouldn't it be possible to just calculate the width of the straight line from the current pen pressure (or average or maximum pressure), in exactly the same way as for the pen tool?

In this way the line thicknesses would be consistent, without needing any device-specific tuning, and without needing users to mess with pressure curves or sliders.

Does this sound reasonable?

**Comment by bhennion** [comment] 2022-05-01 09:54
A pressure multiplier slider has been added in the configuration panel (Stylus section). IMO, this is better than @alexhuntley's suggestion: we do not want the shape's thickness to vary between two strokes.

Anyway, closing this issue as a good solution is now available.

**Closed by bhennion** 2022-05-01 09:54 UTC
Labels: enhancement, priority::high, difficulty::medium
