### ISSUE TITLE
Hand Tool doesn't work work with pen

### ISSUE THREAD

**Issue by Hedronmx** [xournalpp/xournalpp#520] opened 2018-12-11 18:38 UTC
Hand tool doesn't work when used with a pen or touch.
I can use hand tool with my mouse.

**Comment by andreasb242** [comment] 2018-12-11 19:06
Confirmed, This is because of a Workaround with Touch Input.

**Comment by andreasb242** [comment] 2018-12-15 18:52
This is fixed now

**Closed by andreasb242** 2018-12-15 18:52 UTC
Labels: bug, high priority
