### ISSUE TITLE
wrong LaTeX linesize after export

### ISSUE THREAD

**Issue by RichardScharf** [xournalpp/xournalpp#4467] opened 2022-12-01 14:58 UTC
**Affects versions :**
 - OS: Linux Mint 20.3 x86_64
 - Version of Xournal++ v1.1.3

**Describe the bug**
The size of lines created using the LaTeX tool changes when exporting as .pdf and .svg

This effect is especially apparent if you scale down the LaTeX contents before exporting.

**To Reproduce**
1. Open Xournal++
2. Open the LaTeX tool
3. Type `$\boxed{samplebox}$` and press ok
4. Export as .pdf
5. Open the created .pdf file and compare the sizes of lines.

**Expected behavior**
Linesizes should match.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/72913455/205084577-07af6386-dade-48be-97bc-7b395a3357fb.png)

**Comment by tattsan** [comment] 2022-12-01 15:07
Duplicate of #3692. There are workarounds for this issue, but not resolved yet.

**Closed** 2022-12-01 17:30 UTC
Labels: bug, Input
