### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by Zuechti** [xournalpp/xournalpp#1270] opened 2019-06-18 11:57 UTC
Hello,
While i was using your program (specifically copying and pasting the same image of a graph), i encountered a little problem:
Everything i pasted disappeared after I entered writing mode again. I saved and reopened the file, now everything i select (with rectengular select).
Ive attached the corrupted file, maybe theres some useful trash data that will help you find the bug. Thanks for your hard work! Xournal++ is amazing, keep going :3
[2019-06-18.zip](https://github.com/xournalpp/xournalpp/files/3301324/2019-06-18.zip)

**Comment by Technius** [comment] 2019-06-18 22:03
The file doesn't seem to be corrupt (I'm not getting any issues in the terminal). This bug is really bizarre, and it's probably a combination of several different issues. Most likely has to do with the rendering system.

**Comment by JJones780** [comment] 2019-06-19 09:03
Yes, that is odd behaviour when selecting items.
It reminds me of behaviour when I tried to allow negative scaling - was not appreciated by cairo ( the underlying drawing library).
I suspect this is related somehow.

**Comment by petergthatsme** [comment] 2019-06-20 15:38
i had a similar (maybe?) case. I opened a document (which was a few MB in size, maybe 15 pages). Then saved from within xournalpp, but the file got currupted somehow, and only 147 Bytes got saved. Opening it does not work.

**Comment by R4ygen** [comment] 2020-03-09 14:22
I'll join with another similar case, maybe it can be useful:

I was editing a document and at some random point (i don't remember very well what i've done precisely to trigger this) the program just glitched all out: The page itself and the title bar on the top of the program would disappear becoming completely invisible and click-through, and the side and bottom toolbars would become blank, without icons.
When scrolling up in the document, surpassing the last 2-3 pages, the pages would reappear and i was able to edit them normally, but the title bar and toolbars would still be glitched.

Even by closing the program and re-opening the file, the glitch would still happear as soon as i'd scroll to the last 2-3 pages. Here is when i thought the file itself was corrupted.
**I "fixed" this** by exporting the file into the old .xoj format, and then re-exporting it again into the new .xopp format. The file and the last 2-3 pages was perfectly fine and working.

But here's the strange part: I then tried to open the old, "corrupted" file and: It was working perfectly again.
I'll [attach](https://github.com/xournalpp/xournalpp/files/4307077/Maybe.a.corrupted.file.zip) the file anyway, if you can find some trash data in it.

'till today i wasn't able to reproduce this phenomenon. But at least i'm glad it seems to be just a glitch and it doesn't corrupt the file itself (that would be bad).

**Comment by jaykijay** [comment] 2020-03-28 17:38
Hello,
i've got some similiar Problem once again, this happend a lot of times now.
I copied an pasted some parts in the file and after this the complete file/program got corrupt and broken. Some parts disappear random and come back when i select them. (last page right diagramm.. select it, and the blue lines will appear again.)
If i export to .pdf it only exports 2 pages instead of all.. and yeah.. it's completly odd...
Exporting it to.xoj and opening it agfain did not solved the problem :(
[Beispielskizzen.zip](https://github.com/xournalpp/xournalpp/files/4397561/Beispielskizzen.zip)

**Comment by R4ygen** [comment] 2020-08-24 18:28
I think I've found **another way to temporarily fix it**:

While your program is [glitching out](https://user-images.githubusercontent.com/49517480/76432960-f3467c00-63b3-11ea-89cd-17c345400beb.png) try to scroll the pages just to be able to click / select another one, and just THEN close Xournal and restart it.

With this method I'm able to reliably make the issue disappear every time it happens.

**Comment by bhennion** [comment] 2022-05-01 10:02
I think the source of the corrupt file has been fixed in #2857. Closing this issue.

**Closed by bhennion** 2022-05-01 10:02 UTC
Labels: bug, priority::high, confirmed
