### ISSUE TITLE
Xournal++ crashes when Edit->Preferences is clicked

### ISSUE THREAD

**Issue by aslmx** [xournalpp/xournalpp#2140] opened 2020-07-30 11:32 UTC
**Affects versions :**
 - OS: Linux Mint 19.3
 - (Linux only) Desktop environment: XFCE
 - Which version of libgtk do you use: xournalpp --version -> Unkonwn option --version
 - Version of Xournal++: 1.0.18, git commit 535d261d
 - Installation method: official release **xournalpp-1.0.18-Ubuntu-xenial-x86_64.deb**

**Describe the bug**
Xournal++ crashes when Edit->Preferences is clicked.
Crash = The window closes

**To Reproduce**
1. install xournal++ 
2. run xournal++ from application menu
3. Click Edit -> Preferences  

**Expected behavior**
The Preferences Windows opens

**Screenshots of Problem**
no screens hot, but this  is shown in the console, if i launch xournalpp via console

```
$ xournalpp

** (xournalpp:31261): WARNING **: 13:29:39.295: Failed to load "colornames.ini" (/home/username/.xournalpp//colornames.ini): No such file or directory

ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

(xournalpp:31261): Gtk-WARNING **: 13:29:39.788: Theme parsing error: <data>:1:22: Junk at end of value for font-family

// -> here Edit-> Preferences is clicked.
xournalpp: symbol lookup error: xournalpp: undefined symbol: _ZN9portaudio6System14DeviceIteratorneERKS1_
(╯°□°）╯︵ ┻━┻
```

**Comment by rolandlo** [comment] 2020-07-30 17:57
You installed an incompatible version. Duplicate of #1959. See also the [installation guide](https://xournalpp.github.io/installation/)

**Closed** 2020-07-30 17:57 UTC
Labels: bug

**Comment by aslmx** [comment] 2020-07-31 05:58
ok.

Whats the status on ppa for stable release?

**Comment by rolandlo** [comment] 2020-07-31 20:35
Currently the ppa is only for the latest (unstable) nightly release. Adding a stable release ppa has already been suggested. The ticket tracking this is issue #1013.
