### ISSUE TITLE
Buttons on Wacom Bamboo Ink Pen 

### ISSUE THREAD

**Issue by wftmate** [xournalpp/xournalpp#831] opened 2019-02-02 05:03 UTC
I'm using a Lenovo Thinkpad Yoga 460 with the Wacom Bamboo Ink pen. The options for "Stylus Button 1", "Stylus Button 1" and "Eraser" don't seem to be working. Regardless of which tool has been configured for each button on the pen, the software will only use the currently selected tool.

For example, if the eraser is assigned to Stylus Button 1 and the Pen tool is selected, the software will write using the Pen tool just fine. When the Stylus Button 1 is pressed, the software does not switch to the Eraser tool, it just keeps writing with the Pen.

**Comment by andreasb242** [comment] 2019-02-02 08:33
Hi, can you install gtk3-demo, open the tablet demo (or something like this) and test there, if the button are working?
If they are working, take screenshots of the window, and post it here, then we fix it.
If they are not working, you have to figure out why, then it's a GTK Bug, a Driver bug or whatever, and we cannot fix it. (but we may can help you find a workaround or tell you where to place bug, as here are a lot of user which have such bugs)

**Comment by wftmate** [comment] 2019-02-04 03:18
I think I may be in over my head here. I do not know how to install the gtk3-demo. Can gtk3-demo be installed on Windows 10 or is it only available on Linux? Is this difficult to do?

If it helps, I have a dual boot setup with Linux Mint and Windows 10 and I noticed different behavior in Windows than Linux. 

In Linux:
The first time I open the software, if I click the buttons while hovering the pen, Xournalpp seems to detect it and switches to a the tool associated with that button. When I touch the pen to the screen however, the software immediately switches back to the pen tool. If I try this again though Xournalpp will not recognize the button presses until the software is restarted.

In Windows:
All bets are off. Xournalpp does not seem to recognize button presses at all. Even after starting the software, touching the pen to the screen once and restarting the software.

**Comment by andreasb242** [comment] 2019-02-04 17:45
GTK Demo is available for both. On Linux you should find a package.
On Windows 10 I never checked it yet, so I need to check this, before I can tell you what's the problem.
I mark this as bug now, and check it when I have time.

**Comment by galettof** [comment] 2019-02-08 19:24
Hello. I am on a Surface Pro 2017 with Windows 10 and I am facing similar issues. No pressure sensitivity and the eraser end of the pen writes instead of erasing. I tried changing the options for stylus buttons but I still couldn't get the eraser. Thanks.

**Comment by andreasb242** [comment] 2019-02-08 19:29
Eraser is not working on Windows, thats a GTK Bug. Already linked on a Ticket somewhere here.
On macOS Pen was not supported at all, for this I created now a GTK Pull Request, but it's not yet merged...

For Windows I need to do probably the same... We cannot fix it in Xournal++...

**Comment by galettof** [comment] 2019-02-08 19:35
No worries, I only just downloaded the software to give it a try and it already looks great. I'm happy to bring such issues to your attention so you can pass them on to GTK as needed. Cheers!

**Comment by Raffinade** [comment] 2019-02-21 07:11
I have exact the same problem as wftmate. In the normal xournal i dont have such problems.

_In Linux:
The first time I open the software, if I click the buttons while hovering the pen, Xournalpp seems to detect it and switches to a the tool associated with that button. When I touch the pen to the screen however, the software immediately switches back to the pen tool. If I try this again though Xournalpp will not recognize the button presses until the software is restarted._

But there are two other bugs maybe features i am missing
a) If i put an picture for example about 300kb in xournal (Jpg), the xournal-file i save is about 3MB big. Thats a wate of space.
b) The power consumption is much higher in xournal++ as in xournal.

I am using Mint Cinnamon 19.1 with kernel 4.15.0.45-generic on a surface 3 pro. I use instead of the original pen the Bamboo Ink Stylus.

**Comment by LittleHuba** [comment] 2019-02-21 09:06
I think I have an idea what the problem is. I'll write a small script to log the input of your pen so I can be sure my idea is correct. 

Concerning the two other things: please open own tickets for them. Otherwise we can't follow up on them. For a) we already have a solution but it will take some time. 
b) is not high priority unfortunately as this is something we can only do with a feature-freeze and that currently is not the right moment for that.

**Comment by andreasb242** [comment] 2019-02-21 20:25
to b) how did you measure that?
Whit powertop? Or did you simple recognize, that the battery is draining to much?

I do currently more development, than I use Xournal++, the most I used it for notes, after about 4h Meeting with some notes I had still about 40% to 50% Battery on my Lenovo Helix.

**Comment by Raffinade** [comment] 2019-02-21 21:32
Little Huba, your're welcome! 
If you have an script that can measure the power consumption and the other bugs, i'll give you an response! I use xournal in school as a teacher and the normal xournal works well. I use it all the day.
Btw i need shortcuts in the main.glade (/usr/share/xournalpp/ui/) for the colors and an color-picker as it is in the normal xournal. In the old xournal i can configure my shortcuts in xo-interface.c but in the new version i cant configure my shortcuts in the main.glade

Greetings 

Raffinade

**Comment by LittleHuba** [comment] 2019-02-22 00:18
The script is only for the original issue. I'll come up with that the next few days... 

You can create the color shortcuts in the `toolbar.ini` file.

**Comment by Raffinade** [comment] 2019-02-22 06:58
LittleHuba, 
can you explain, how i can make shortcuts in toolbar.ini? I need only an example, maybe to choose green color maybe with alt+x
I think this will not work anymore:

`colorGreen = gtk_radio_menu_item_new_with_mnemonic (colorBlack_group, _("_green"));
  colorBlack_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (colorGreen));
  gtk_widget_show (colorGreen);
  gtk_container_add (GTK_CONTAINER (toolsColor_menu), colorGreen);
  gtk_widget_add_accelerator (colorGreen, "activate", accel_group,
                              GDK_Y, (GdkModifierType) GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (colorGreen), TRUE);`

And do you know, whats the modifier for altgr? For alt it is GDK_MOD1_MASK but for altgr i didnt found anything in the web.

Greets 

Raffinade

**Comment by andreasb242** [comment] 2019-02-22 08:09
There are no shortcuts in toolbar.ini, and the shortcuts are not customable.
The most shortcuts are defined in ui/main.glade (you can edit it with glade).
https://glade.gnome.org/

But as the Color items does not have a menu entry, this will not be possible.

I'm currently working on a Plugin / Scripting interface, this will make something like this possible. But not yet, as it's not yet finished.

**Comment by Raffinade** [comment] 2019-02-22 09:55
Many thx for the information andreas. The new features in the xournal++ are making the much program better, i hope in the future i can use it like the old xournal with shortcuts. Maybe it will be possible to define shortcuts in the frontend for everything, that will make it easier to configure the program like i want.

**Comment by LittleHuba** [comment] 2019-02-22 11:08
Ahh sorry I misunderstood that. You should create a ticket for that. It would require some changes but it is not that complex to provide this functionality.

**Comment by andreasb242** [comment] 2019-02-25 07:16
This issue has now mixed different issues, this needs to be cleaned up... I'll do this later.

**Comment by Epse** [comment] 2019-04-22 15:35
@flipmess seems correct. On thinkpad pens (and most Wacom pens) that's how button presses are sent.

**Comment by LittleHuba** [comment] 2019-05-02 21:47
This should get fixed by the new input system (#1070) then. I'll close this as its first issue is a duplicate of #940 and there are many mixed issues in this thread. If any of the other issues needs to be adressed please open own issues for them.

**Closed by LittleHuba** 2019-05-02 21:47 UTC
Labels: bug, need info, question

**Comment by Nestak2** [comment] 2020-09-12 10:11
Has the original issue with not working pen buttons been solved? I at least face it, too, on an Eve V tablet with Ubuntu 20.04. and Unity desktop environment
