### ISSUE TITLE
Menu text/font errors when open saved .xopp and .pdf files

### ISSUE THREAD

**Issue by bvqbao** [xournalpp/xournalpp#3553] opened 2021-11-08 15:42 UTC
**Affects versions :**
 - OS: Windows 11
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: 1.1.0-hotfix.1
 - Installation method: official release on GitHub

**Describe the bug**
Sometime when open a saved .xopp and .pdf file, the menu text in the app isn't readable .

**To Reproduce**
Just open a saved .xopp and .pdf files. The problem happens randomly.

**Expected behavior**
Menu text should be readable.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/4357219/140770237-e2dff040-9a1e-4bb0-8385-395220a5cff4.png)

**Additional context**
Links to the files: https://drive.google.com/drive/folders/1qZfHlVf3YZ6Z0e7tidufg-Tbs6VjqR8x?usp=sharing

**Comment by LittleHuba** [comment] 2021-11-08 15:48
Duplicate of #3371. Please see the fix there or switch to the nightly releases for now.

**Closed by LittleHuba** 2021-11-08 15:48 UTC
Labels: bug
