### ISSUE TITLE
Grid (ruled page) color on dark page color, Ubuntu

### ISSUE THREAD

**Issue by JuanManuel1096** [xournalpp/xournalpp#3654] opened 2021-12-11 03:29 UTC
Hi. I where obsessed by change the color and size of grid in my ruled page. I did it changing the template in pagetemplates.ini as follows:

name=White Mesh
name[de]=Rot gepunktet
format=graph
config=f1=FFFFFF,rm=1,m1=40,r1=20,

But, when I change the page color by a dark, like black or dark green, mesh backs to its original color. It just happen with dark color as i show u next. Some idea why?

![Captura de pantalla de 2021-12-10 22-26-50](https://user-images.githubusercontent.com/66631945/145662224-78816728-2d6a-4668-ba2a-7c43241a7f6a.png)
![Captura de pantalla de 2021-12-10 22-26-24](https://user-images.githubusercontent.com/66631945/145662226-9218e4e8-bbbf-4874-9d41-271c07b9fbb8.png)

**Comment by rolandlo** [comment] 2021-12-11 08:21
Please check [this description](https://github.com/xournalpp/xournalpp/issues/2137#issuecomment-799956788). You should use `af1` for dark backgrounds,  I think.

**Comment by rolandlo** [comment] 2021-12-13 16:31
Duplicate of #3617

**Closed by rolandlo** 2021-12-13 16:31 UTC
Labels: bug
