### ISSUE TITLE
Translations through `_(TEXT)` macro are not used in the application

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#3870] opened 2022-02-25 18:29 UTC
Strings in the `_(TEXT)` macro in the source files appear in Crowdin, but their translations do not seem to be used in the app. The original english strings are used instead.

See for instance the Journal/Paper Background menu
![Screenshot_20220225_191649](https://user-images.githubusercontent.com/17818041/155766894-3a8de993-0d9c-4d11-915d-9c0555f4a12f.png)

The corresponding strings:
https://github.com/xournalpp/xournalpp/blob/master/src/core/control/pagetype/PageTypeHandler.cpp#L20-L27

The Crowdin page for `Ruled with vertical line` item
![Screenshot_20220225_191954](https://user-images.githubusercontent.com/17818041/155767330-2347bdca-a7e9-4d90-959f-aa06985cac4b.png)

See #3863 for other examples.

**Comment by Febbe** [comment] 2022-02-25 19:46
@LittleHuba is the reason, that the new translations aren't merged into v1.1.x?

**Comment by LittleHuba** [comment] 2022-02-25 20:48
It's just that nobody merged the PR 😉 Just did so and they should be updated now.

**Comment by LittleHuba** [comment] 2022-02-25 20:49
See #3808

**Comment by bhennion** [comment] 2022-02-25 21:01
> @LittleHuba is the reason, that the new translations aren't merged into v1.1.x?

But this is not the issue here. The french translation of those strings is 3 years old, way before the new branching scheme. And the same behaviour happens in both master and 1.1.1.

**Comment by LittleHuba** [comment] 2022-02-25 21:40
I'll take a look what the problem might be.

**Comment by bhennion** [comment] 2022-02-26 09:34
Also, the translations are definitely in the .po file. It's really the app not using them for some reason

**Comment by LittleHuba** [comment] 2022-02-26 11:49
Could you tell me the selected language strings activated on your system?

**Comment by bhennion** [comment] 2022-02-26 12:24
> Could you tell me the selected language strings activated on your system?

Is this what you want?
```
$ echo $LANG
fr_FR.UTF-8
```

**Comment by LittleHuba** [comment] 2022-02-27 16:20
Okay, so it turns out that translations for these strings must be added here:

https://github.com/xournalpp/xournalpp/blob/master/ui/pagetemplates.ini

See the following format that adds a translation for german:
```
name[de]=...
```

If you want to add a translation to french, please file a PR with the added lines.

**Closed by LittleHuba** 2022-02-27 16:20 UTC
Labels: bug, confirmed, UX

**Comment by bhennion** [comment] 2022-02-27 16:49
Oh wow! Thanks for figuring that out! Could we add something to the Translations cmake target that would use Crowdin translations and pu them in this .ini file?
We definitely won't be doing this by hand for every language.

Also, I realized the strings of "ui/toolbar.ini" (i.e. the toolbar names) are not translated either (except in dutch, italian and russian), and they do not appear in Crowdin.

Lastly, a similar scheme, with a Cowdin updated .ini file, could also be used to actually solve #3863 and localize the color names.

**Comment by LittleHuba** [comment] 2022-02-27 19:44
That is unfortunately not that easy... Crowdin is fed by *.pot files that in essence list occurrence in the file, the original text and its translation. Crowdin parses that file and stores it in a database. What we get back from Crowdin are *.po files, which have the same format as *.pot files. These *.po files are then translated into *.gmo files that resemble a machine-readable version of *.po files. Those files are then parsed by gettext at runtime through libicu.

The problem is that we can not automatically parse a *.pot file from such *.ini files nor can we get Crowdin to feed that information back to the *.ini files. We could add some code to our build system to do this for us but that is quite a lot of work.

You are of course welcome to give it a try. I can give you a run-down of what you would need to do but have unfortunately not the time to do it myself.

**Comment by bhennion** [comment] 2022-02-28 15:16
Maybe we could open a dedicated issue (with a clear title) identifying the 3 categories of strings that are not translated through Crowding, and with your run-down in it. This way, if someone (could be me, could be someone else) wants to tackle this in the future, we'll have a clear reference.

**Comment by LittleHuba** [comment] 2022-02-28 18:47
Yes, that would be a good idea.

**Comment by bhennion** [comment] 2022-03-01 14:40
Done. See #3881

**Comment by LittleHuba** [comment] 2022-03-02 07:46
Thanks! I'll add some ideas in the next few days on how to tackle the colors.
