### ISSUE TITLE
Page seems to resist being scrolled by finger, goes back to top on scrolling

### ISSUE THREAD

**Issue by WaseemAlkurdi** [xournalpp/xournalpp#3425] opened 2021-09-29 06:35 UTC
**Affects versions :**
 - OS: Windows 11 version 21H2 build 22000.194
 - Version of Xournal++:  `e25f0b0a`
 - libgtk: `3.24.30`
 - Installation method: Official release
![image](https://user-images.githubusercontent.com/15712695/135212599-3912d764-3964-4d9b-83f4-f366d44b5cd0.png)

**Describe the bug**
When finger scrolling, the page scrolls down for a split second, but then instantly returns to its former position, as if something was anchoring it to its former position. This makes for a really annoying experience ...
I've tried various options in Edit - Preferences (too many to list), all to no avail.

**To Reproduce**
Install the latest nightly release of Xournal++, then open, and try to scroll. Scrolling using the touchpad or scrollbar does work.
A video is attached.

**Expected behavior**
That scrolling would work.

**Screenshots of Problem**
Please see attached video below. In the video, I finger-scroll down first, then I use the scrollbar to scroll down to show the expected behavior.

https://user-images.githubusercontent.com/15712695/135216370-f321e6a8-ee8f-487d-b147-af6d28f95d07.mp4

**Comment by LittleHuba** [comment] 2021-09-29 06:51
Could you please try enabling and disabling presentation mode?

**Comment by WaseemAlkurdi** [comment] 2021-09-29 06:59
@LittleHuba It didn't work :-(

**Comment by LittleHuba** [comment] 2021-09-29 07:04
Okay, then please provide a screenshot of the dialog `Edit->Preferences->Input System`.

**Comment by WaseemAlkurdi** [comment] 2021-09-29 07:08
There you go:
![image](https://user-images.githubusercontent.com/15712695/135219794-ded2c146-e9f9-43e2-aeb9-11fee23b04cc.png)

**Comment by LittleHuba** [comment] 2021-09-29 07:18
Please also provide the section `Input System`.

In the section you posted just now, you can try enabling `Disable GTK3's built-in inertial scroll functionality`.

**Comment by WaseemAlkurdi** [comment] 2021-09-29 07:25
This worked! 😍
Would there be a fix to have this work even with inertial scrolling turned on though?
Without it, Xournal++ would look rather dated IMHO.

**Comment by WaseemAlkurdi** [comment] 2021-09-29 07:27
As for `Input system`, here you go:

![image](https://user-images.githubusercontent.com/15712695/135222421-3a82e046-d7dc-4bb8-a0af-cfa15eaa3d54.png)

**Comment by WaseemAlkurdi** [comment] 2021-09-29 07:56
Ah, I see what's happening now @LittleHuba ... looks like I'm running into this bug: https://github.com/xournalpp/xournalpp/issues/3260

**Comment by LittleHuba** [comment] 2021-09-29 07:57
We have another issue tracking this problem (#3260). The issue is something explicit to Xournal++, so it is a bug in our codebase. This means we can fix it but do not yet know what the exact cause is. We'll discuss this further in the other ticket and try to find a solution.

**Comment by LittleHuba** [comment] 2021-09-29 07:57
Duplicate of #3260. I'll close this ticket in favor of the other ticket.

**Closed by LittleHuba** 2021-09-29 07:57 UTC
Labels: bug
