### ISSUE TITLE
Incorrect terms spacing after second equal sign in Tex mode.

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2480] opened 2020-12-03 17:46 UTC
I use Xournal 1.1.0 on Windows 10. For some reason, when I use this in Tex mode: a). \ f'(x) = 3\left(5x^4 \right)- 5\left(4x^3\right)+0 =g
all the terms get incorrect spaced out. However, if I replace \ with slash+, (GitHub somehow does not allow me to add \ plus a character) , it has the correct spacing. And, this only occurs after I type in the second equal sign.

EDIT: 
Then, if continue: a). slash+, f'(x) = 3\left(5x^4 \right)- 5\left(4x^3\right)+0 = 15x^4-,
The spacing error comes up again. Changing slash+, to \ does not fix the issue.

However, wrapping the equation in \text{$$} does solve the issue.

Error:
![image](https://user-images.githubusercontent.com/49244768/101069744-65757700-3568-11eb-9c05-fdb83d26aab4.png)

Expected: 
![image](https://user-images.githubusercontent.com/49244768/101069799-7aeaa100-3568-11eb-8237-128e199b08be.png)

**Comment by rolandlo** [comment] 2020-12-03 18:05
Could you please add a screenshot of how the formula looks with incorrect spacing and how you expect it to be?

**Comment by DUOLabs333** [comment] 2020-12-03 18:05
Ok, it seems like what was happening is that Tex was trying to fill out the line to push everything else to the next line (as I had some other things on the same line that made it overflow), as doing slash+slash on the overflowing bit fixed the problem. Don't know if this is a "bug" at all, or intentional behaviour, and whether this behavior is with LaTeX or with Xournal.

**Comment by DUOLabs333** [comment] 2020-12-03 18:07
@rolandlo Added.

**Comment by rolandlo** [comment] 2020-12-03 18:17
On Linux I can only reproduce the expected spacing. This must be related to your TeX distribution. Xournal++ passes the LaTeX file to pdfLaTeX (or the LaTeX generator that you predefine in the preferences LaTeX panel). So you should be able to reproduce the problem with your LaTeX-editor of choice, using the `default_template.tex` file while substituting `%%XPP_TEXT_COLOR%%` and  `%%XPP_TOOL_INPUT%%` appropriately.

**Comment by Rmano** [comment] 2020-12-03 18:20
Maybe I am not understanding the problem... but: 

![image](https://user-images.githubusercontent.com/6414907/101071175-88218300-359c-11eb-85d0-afbd6bddadf0.png)

Seems ok to me. What you describe seems like if you are in a line in which LaTeX is trying to justify the line --- have you changed the template file?

**Comment by rolandlo** [comment] 2020-12-03 18:22
You could also try to find the generated .tex-file in the temporary folder with the substitutions already applied. Then we can make sure that the problem is not in applying the substitutions correctly.

**Comment by DUOLabs333** [comment] 2020-12-03 18:31
@Rmano I did have other things on the line, specifically right after the equation, something like \ \text{Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tempus mauris nec purus aliquam auctor. Pellentesque sollicitudin id neque eu pulvinar.} Then I believe the problem will occur.

**Comment by rolandlo** [comment] 2020-12-03 18:53
@DUOLabs333 So far I can't see anything that suggests that there is something wrong on the Xournal++ side. I can't reproduce the incorrect spacing even with the text added to it. The standalone package behaves a bit differently than other packages. If you don't come up with a clear reproducible misbehavior on Xournal++'s side (not occuring in your LaTeX-editor with the same packages) we can't help you and I will close this issue (or I suggest you close it yourself).

**Comment by Rmano** [comment] 2020-12-03 19:12
`amsmath`'s `\text` command is for small sections of text --- if it spans more than one line everything can happen. If you need to add full paragraphs of text, you probably need a different template than the standard one, I think.

**Closed** 2020-12-03 19:22 UTC
Labels: bug
