### ISSUE TITLE
the captured pen position dosen't fit in with the pen cursor

### ISSUE THREAD

**Issue by HuangBoHong** [xournalpp/xournalpp#1816] opened 2020-03-31 12:58 UTC
**Affects versions :**
 - OS:Windows 10
 - Version of Xournal++: 1.0.17
 - Installation method: official release

**Describe the bug**
I'm using wacom tablet pc, and when my pen approaches the screen, the black dot cursor looks just correct, but actually the pen position captured and recorded by xournalpp is offset. 
**To Reproduce**
I've calibrated the pen input in Windows  Tablet PC Settings, so I guess xournalpp doesn't recognize and utilize the calibration data generated by Windows. 
**Expected behavior**
I think there are 2 solutions that could hopefully help with this issue: 
1. Add support to Windows Ink API(Windows 8+) 
2. Add independent input calibration system in xournalpp.  

**Screenshots of Problem**
![bug](https://user-images.githubusercontent.com/11132087/78025874-5319bc80-738d-11ea-96be-e7b73e0658d5.gif)

**Comment by prof-anderson** [comment] 2020-12-17 22:45
I seem to be having the same problem with even more misalignment:
- OS: Windows 10
- Version of Xournal++: 1.0.20
- Installation method: official release

It is misaligned by around 300-500 pixels both vertically and horizontally.  
Tablet is a Huion Kamvas Pro 16, current drivers, calibrated, no alignment issues with other apps.

**Comment by thepiratedude** [comment] 2020-12-22 18:26
I found a solution (for me) here: https://github.com/xournalpp/xournalpp/issues/1472
Xournallpp presume that you have been set your text,apps and other items on 100%, if you have change it you found problem with the alignment throw the pen and the digital line.

**Comment by ErgastiAlex** [comment] 2021-01-05 17:39
Same problem, if i map the graphics tablet to just a portion of the monitor i have a misalignment.
No problem with other app.

**Comment by prof-anderson** [comment] 2021-01-05 18:03
Great recommendation @thepiratedude !  I changed the windows scaling for the tablet from 150% to 100%.  That seems to have fixed the problem.  Thanks!

**Comment by realtofuine** [comment] 2021-01-18 20:32
Setting the resolution to 100% works, but it basically makes my second display unusable. Is there any other solution?

**Comment by Technius** [comment] 2021-02-10 22:26
Duplicate of #1801. See the comments there for a workaround.

**Closed by Technius** 2021-02-10 22:26 UTC
Labels: Input, bug, os::windows
