### ISSUE TITLE
Secondary stylus button only works when there is no contact

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#940] opened 2019-02-26 07:57 UTC
I have a Thinkpad X380 Yoga and when I use Button 2 with the e.g. the eraser tool, it only works when I don't touch the screen. As soon as I touch the screen it reverts back to the drawing tool.

**Comment by LittleHuba** [comment] 2019-02-26 10:20
I can reproduce the problem.

**Comment by LittleHuba** [comment] 2019-02-26 12:49
Problem is that contact fires as button 1 of the pen and thus overwrites the button 2 event of the pen. This is recognized as tool change by Xournal++.
When I'm finished with the new file format I'll rewrite parts of the input handling to support such pens and also handle other input devices more nicely. But this will take some time as a lot of testing is involved.
@andreasb242 I'll probably need your input here as you have touch devices that have different hardware. We'll need to check that we have no regression with the changes.

**Comment by andreasb242** [comment] 2019-02-26 19:32
We need a FAQ, this is a driver settings, and we already have somewhere in the ticket a description, how to change it.
You cannot change this problematically, I thinks @morrolinux know how?
We need to add this to the readme.

**Comment by morrolinux** [comment] 2019-02-26 19:38
This seem to be more of a driver setting, which you can configure with `TPCButton` or `TabletPCButton` directive if using `Wacom` driver (but other drivers might have this setting too)
Here's a `/usr/share/X11/xorg.conf.d/30-wacom.conf` example snippet
```
Section "InputClass"
	Identifier "Wacom tablets class"
	MatchProduct "Wacom"
	MatchDevicePath "/dev/input/event*"
	MatchIsTablet "on"
	Driver "wacom"
	Option "TabletPCButton" "on"
	Option "TPCButton" "on"
EndSection
```

**Comment by LittleHuba** [comment] 2019-02-27 09:59
@coldspark29 Could you check whether you are using libinput as driver?

Either we are misinpterpreting some events or GDK just uses the same event for tip and buttons of the screen. Libinput should differ between both.

https://wayland.freedesktop.org/libinput/doc/1.3.1/tablet-support.html

**Comment by LittleHuba** [comment] 2019-02-28 14:12
For libinput see the following ticket: https://gitlab.freedesktop.org/libinput/libinput/issues/193

**Comment by flipmess** [comment] 2019-04-01 20:19
How come Xournal doesn't need any 'driver quirks' to function correctly in this regard? You can i.e. select text while holding a button on the pen without having to worry about touching the tablet.

**Comment by AlessandroW** [comment] 2019-04-02 10:03
I have the same Issue (Bamboo Ink Pen and Lenovo Yoga) but only in xournalpp, xournal works fine.
The wiki's solution didn't help and setting it with `xsetwacom` either, probably because I am using libinput as driver (?).
```shell
$ xinput list-props 11
Device 'Wacom HID 50EE Pen stylus':
	Device Enabled (152):	1
	Coordinate Transformation Matrix (154):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (283):	0
	Device Accel Constant Deceleration (284):	1.000000
	Device Accel Adaptive Deceleration (285):	1.000000
	Device Accel Velocity Scaling (286):	10.000000
	Device Node (278):	"/dev/input/event7"
	Wacom Tablet Area (328):	0, 0, 29376, 16524
	Wacom Rotation (329):	0
	Wacom Pressurecurve (330):	0, 0, 100, 100
	Wacom Serial IDs (331):	20718, 965089588, 73, 0, 0
	Wacom Serial ID binding (332):	0
	Wacom Pressure Threshold (333):	26
	Wacom Sample and Suppress (334):	2, 4
	Wacom Enable Touch (335):	0
	Wacom Hover Click (336):	1
	Wacom Enable Touch Gesture (337):	0
	Wacom Touch Gesture Parameters (338):	0, 0, 250
	Wacom Tool Type (339):	"STYLUS" (321)
	Wacom Button Actions (340):	"Wacom button action 0" (341), "Wacom button action 1" (342), "Wacom button action 2" (343), "None" (0), "None" (0), "None" (0), "None" (0), "Wacom button action 3" (344)
	Wacom button action 0 (341):	1572865
	Wacom button action 1 (342):	1572867
	Wacom button action 2 (343):	1572866
	Wacom button action 3 (344):	1572872
	Wacom Pressure Recalibration (345):	1
	Wacom Panscroll Threshold (346):	1300
	Device Product ID (279):	1386, 20718
	Wacom Debug Levels (347):	0, 0
```

For reference here's the difference between xournal and xournalpp in action:
First writing, then hovering while pressing a button and then touching the screen  without releasing it.
![xournal](https://user-images.githubusercontent.com/29565912/55393764-247cc200-553e-11e9-922d-eb9ef4304e61.gif)
![xournalpp](https://user-images.githubusercontent.com/29565912/55393771-28104900-553e-11e9-92c2-185d06795524.gif)

**Comment by LittleHuba** [comment] 2019-04-02 21:07
We'll have to rewrite parts of the input handling for this. But that is a lot of work and is currently not at the top of the todos. Please be patient with us. We are a small team and work continuously to make Xournal++ better.

**Comment by andreasb242** [comment] 2019-04-03 17:11
I checked this, this should be easy to fix, I think we should not apply the new config if we don't get a button release. So if we get the right button pressed, and then the left button pressed, without a button released, ignore the left button pressed, should be relative easy.

@LittleHuba agree or do I miss something which you saw?

**Comment by LittleHuba** [comment] 2019-04-03 21:43
Actually a quick fix should be fairly easy. You are right in that regard. 

But to fix our input system completely I see the only way in moving to a pattern that supports reproducible scenarios. 
One such pattern would be the State Pattern that switches the states along with the input events.

When introducing such a pattern this work would be done twice and we are lagging behind the tickets enough as it is.

**Comment by andreasb242** [comment] 2019-04-04 15:23
@LittleHuba you mean a state machine? That's maybe really easy...

**Comment by LittleHuba** [comment] 2019-04-04 21:54
Yeah we are talking about the same thing. 
Best would be to use the pattern for both stylus and touch. 
That would also give us with deterministic behaviour what we are currently missing.

**Comment by LittleHuba** [comment] 2019-04-07 21:13
I played with the proposed approach for some time now and do actually not think it is feasible to continue on that path. Between the states are simply too many interonnections to really separate them. 

What I found is a good solution is to differ between the device types. So each type has its own event listener which simplifies the distinction. Additionally I added the feature that listeners can deactivate other listeners on purpose which allows us to block touch input when pen input is recognized. 

There is still a lot of work to do but the overall approach seams to work quite well so far. I'll provide further info when it is available.

**Comment by AlessandroW** [comment] 2019-04-21 10:47
I had an idea:
**Why isn't it possible to change the pen when pressing the button; like change the pen to marker?**
Then, writing and hovering would be the same (although only because of the same pen option)

As a current workaround, without patching, I did the following:

First, select the marker as pen and then start marking.
Now, when I press the button it still works while hovering.
Only drawback: as soon as the pen touches the screen I have to re-press the button to get the hovering back.
![fix](https://user-images.githubusercontent.com/29565912/56468930-4aa5cb80-6433-11e9-974c-04f1c08937e9.gif)

So, maybe this is an easy workaround for now.

**Comment by LittleHuba** [comment] 2019-04-21 13:07
This issue will be resolved once #1070 is merged in. I don't think putting any effort into the old input system has any merrit.

**Comment by whot** [comment] 2019-05-01 05:59
@coldspark29 can you confirm the behaviour of that stylus please? Does it have a separate eraser end (Wacom type) or do you have to hold the button on the stylus down to get the eraser behaviour (Windows surface type)? If the latter, this issue isn't necessarily a TPCButton issue but rather one of correct tool changes.

**Comment by coldspark29** [comment] 2019-05-02 20:12
I have to hold down the button. It does not have a secondary eraser. The behavior is as follow: When you don't touch the screen with the tip and press the button, you have a more or less floating eraser. As soon as you touch the screen, the tool reverts back to the pen. BUT if you are already touching the screen and then hit the eraser button, you can erase normally, but then the tools doesn't revert back to the pen, when you release the button. You have to start drawing to have it revert back.

**Comment by LittleHuba** [comment] 2019-05-02 21:17
The problem is that the button press / release event sequences differ with the TPCButton parameter set or not.
An input system cannot react to both perfectly without querying the state of that parameter. But I actually do not want to add libwacom as dependency to check this.
The new system has handling for both options implemented and users can change the behaviour in the settings.
@whot That should essentially also fix the bug with libinput.

**Comment by wftmate** [comment] 2019-05-02 23:50
Where in the settings can this behaviour be changed? Sorry if this is obvious.

**Comment by whot** [comment] 2019-05-03 01:19
FTR, I tried a MS Surface pen [recording](https://gist.githubusercontent.com/stephenjust/08f67f1668aa116c78be4412610ad4d0/raw/6e00c33a9d0156fddbe2d8334e5202ade0c6fd0f/surface3-pen.evemu) that I found which should have the same HW behaviour as @coldspark29 's device, i.e. a 

the libinput output seems correct (bar a cosmetic [bug](https://gitlab.freedesktop.org/libinput/libinput/issues/284) with proximity events being sent in the correct order and the pen going out of proximity before the eraser event. So at least that layer of the stack behaves correctly.

Note: if that's the same behaviour, the eraser button is *never* sent as actual button press to userspace, it's a tool proximity change only. Pressing that button is equivalent to turning the stylus around on a Wacom tablet but it's not a button press.

The sequences you get:
- normal pen stroke is: pen-proximity-in, tip-down, ... tip-up, pen-proximity-out
- eraser button pressed while up: pen-proximity-in, pen-proximity-out*, eraser-proximity-in, tip-down, ... tip-up, eraser-proximity-out
- eraser button while down: pen-proximity-in, tip-down, tip-up*, pen-proximity-out*, eraser-proximity-in, tip-down*, ... tip-up, eraser-proximity-out

Events marked with * are faked events that don't represent the physical interaction.

TPCButton should really not come into effect here unless you *also* press the stylus button in addition to the eraser button (which on most pens isn't physically possible but it may be on the lenovo pen).

So what am I missing? Are we just mixing bugs here? Or is that pen actually sending the eraser button to userspace? an `evemu-record`/`libinput record` will confirm that.


Unrelated:
> 	Option "TabletPCButton" "on"

This option doesn't exist and is ignored, `TPCButton` is the right name

**Comment by LittleHuba** [comment] 2019-05-03 06:10
@wftmate the new input system is not yet merged so the setting does not yet exist. Either build manually from the branch or wait for us to merge this into master.

**Comment by LittleHuba** [comment] 2019-05-03 06:34
@whot I think there are two mixed bugs. One is the issue that erasing using the tip of the pen and pressing a button is working while hovering and another different bug is that the physical eraser of some pens is not working. 

The first bug is already fixed by #1070 but the second is hard for me to find and fix. I do not have hardware with a physical eraser on the pen. But I do have an idea on how to get the necessary information. I'll get back to that in a few days. 

Related to the first bug: 
Unfortunately GDK does not relay those tip down events as it only knows of button presses. Thus `tip-down` is rendered as a `button-press 1` but actually only happens when the tip touches the surface of the screen and not when a tip event is received. 

That means (using `xf86-input-wacom`) for us the sequences are: 

- with `TPCButton` enabled: 
``` 
motion 
button-press 3 
motion 
button-release 3 
motion 
```
- with `TPCButton` disabled: 
``` 
motion 
button-press 3 
motion 
button-press 1 
motion 
button-release 1 
motion 
button-release 3 
motion 
```

I'll have to check if the event sequence differs when I use libinput as driver but I doubt that. 

To refer to your `TPCButton` comment: 
Interestingly xsetwacom has deprecated `TPCButton` and wants one to use `TabletPCButton`. But that is just cosmetics and should not further influence anything.

**Comment by LittleHuba** [comment] 2019-05-03 06:43
@coldspark29 concerning the drawing after releasing the button on the pen: 
This will be impossible with `TPCButton` enabled as there is a problem with the events we get. The sequence is as follows: 

``` 
motion 
button-press 1 
motion 
button-release 1 <-- you press the button on the pen
button-press 3 
motion 
button-release 3 <-- you release the button on the pen
motion 
``` 

As you may see after releasing the button we never get a `button-press 1` again. This is a problem that even #1070 is not able to fix. 

If you disable `TPCButton` we get a better sequence where I can handle this scenario correctly.

**Comment by whot** [comment] 2019-05-07 00:23
> I do not have hardware with a physical eraser on the pen. 

Record the interaction you want with `evemu` or `libinput record`. Then go through the file and replace any `BTN_TOOL_STYLUS` with `BTN_TOOL_RUBBER`. Or more precisely, the `0x140` with `0x141` because the human-readable names are just comments. Then replay that file with `evemu-play` or `libinput replay` - voila, you have a separate eraser end now :)

> I'll have to check if the event sequence differs when I use libinput as driver but I doubt that.

FTR, it shouldn't, it'd be the same with TPCButton off, anything else would be a bug at this point.

> xsetwacom has deprecated

oh, right, I keep forgetting about this. So: xorg.conf uses TPCButton only, xsetwacom uses TabletPCButton. maybe not the smartest thing I did but we all made mistakes a decade ago.

>  Unfortunately GDK does not relay those tip down events as it only knows of button presses. Thus tip-down is rendered as a button-press 1 but actually only happens when the tip touches the surface of the screen and not when a tip event is received.

right, so this is the real issue here and the crux of the matter. the design of libinput doesn't really allow for anything but "tip down while button3 is down", see [this comment](https://gitlab.freedesktop.org/libinput/libinput/issues/193#note_156088) and the same is true for the Wayland protocol. Right now it looks like we're basically stuck having to implement this in all clients/toolkits. Which is unfortunate, but I don't know any other solution. Open to suggestions though.

**Comment by LittleHuba** [comment] 2019-05-07 21:32
> Record the interaction you want with evemu or libinput record. Then go through the file and replace any BTN_TOOL_STYLUS with BTN_TOOL_RUBBER. Or more precisely, the 0x140 with 0x141 because the human-readable names are just comments. Then replay that file with evemu-play or libinput replay - voila, you have a separate eraser end now :)

Thanks for this info!

> right, so this is the real issue here and the crux of the matter. the design of libinput doesn't really allow for anything but "tip down while button3 is down", see this comment and the same is true for the Wayland protocol. Right now it looks like we're basically stuck having to implement this in all clients/toolkits. Which is unfortunate, but I don't know any other solution. Open to suggestions though.

This is actually the right approach as it logically separates those events and tip down is just not a button press. That GTK can not handle this is just awful but nothing that libinput should work around. Thats something for GTK to fix. As it stands the support for styluses is not working well anyway at the moment and needs an overhaul.

As it stands `TPCButton` should be disabled by all users as it is quite buggy (See my comment above). Still Xournal++ comes with support for both.

**Closed** 2019-05-10 13:27 UTC
Labels: question

**Comment by Nestak2** [comment] 2020-09-12 10:22
In Sept 2020 I am facing the same problem on an Eve V tablet with Ubuntu 20.04. Has a solution to the problem been found?

**Comment by coldspark29** [comment] 2020-09-12 11:31
For me it was solved a long time ago

**Comment by Nestak2** [comment] 2020-09-12 11:36
@coldspark29 Alright. Can you explain how or what made it work for you? I don't find an explanation in the thread. Thanks!

**Comment by coldspark29** [comment] 2020-09-12 15:25
Ulrich fixed it I think. It might depend on the stylus you are using. I have an X380 Yoga and the Bamboo Ink. Works with both of them. I can’t help you really. Sorry

**Comment by Nestak2** [comment] 2020-09-12 16:16
Thanks, I understand. Can you let me know what xournal++ version you are using? You find it under the tab "help"->"about"

**Comment by Nestak2** [comment] 2020-09-12 16:44
Strange, now my primary button works, but the secondary exhibits still the strange behaviour as described in the original question....

**Comment by coldspark29** [comment] 2020-09-12 18:45
The latest version, bit haven’t updated for a week or so. You could try swapping the buttons. And make sure you built the version from Github. The versions in the package managers of distributions are usually very old.

**Comment by coldspark29** [comment] 2020-09-12 18:49
And well with some bugs you have to live. When I was still having more lectures I was using it daily and reported heavily. Many bugs got fixed, but then other coders break things again. It will never be perfect.

**Comment by Nestak2** [comment] 2020-09-13 06:49
Thanks for the suggestions! I got what you mean about not being perfect, and yes, xournal++ is still a great tool
