### ISSUE TITLE
Arrow vector grows too big

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#1722] opened 2020-01-30 19:43 UTC
**Affects versions :**
 - OS: Fedora 31, Gnome 3.34, X11
 - Xournal 1.0.16(c4745271d4dc114b0ee2145b3e9ace257b7f4c28)

**Bug description**

I use Xournal++ to annotate slides, so I will often draw an arrow from one area of the page, to another. The way arrows are currently rendered, the head grows too big and ends up occupying a very large area of the page, and covering a lot of text. 

**To Reproduce**

* Draw a long arrow

**Expected behavior**

Arrow head has a constant size(The way it is currently implemented in Libreoffice, regardless of the length of the arrow). 

**Screenshots of [Problem**]
![xournal_arrow](https://user-images.githubusercontent.com/39338488/73484158-c9d71100-436e-11ea-894e-1c2aec5edf19.png)

**Comment by Technius** [comment] 2020-01-31 07:46
This has already been fixed in `master` branch (unstable/nightly), but I can't quite remember when it was fixed...

**Closed by Technius** 2020-01-31 07:46 UTC
Labels: bug

**Comment by Technius** [comment] 2020-01-31 07:49
Ok, found it. This is a duplicate of #967 and was fixed in #1606.
