### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hatxvm** [xournalpp/xournalpp#4495] opened 2022-12-11 11:34 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when
 [when record in obs , i can't record cursor (help me please)]

**Describe the solution you'd like**
[...I need to have cursor when record in obs...]
**Describe alternatives you've considered**

**Additional context**
![Screenshot 2022-12-11 182921](https://user-images.githubusercontent.com/83224828/206900954-31317f02-4cd1-4aeb-be42-c768deea7ac6.jpg)

**Comment by rolandlo** [comment] 2022-12-11 11:43
Duplicate of #3469

**Closed by rolandlo** 2022-12-11 11:43 UTC
Labels: enhancement

**Comment by hatxvm** [comment] 2022-12-11 12:11
thanks
