### ISSUE TITLE
crash when try to open some files with images

### ISSUE THREAD

**Issue by aberetta145** [xournalpp/xournalpp#4009] opened 2022-05-05 11:29 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS:ubuntu 20.04
 - gnome
 - Version of Xournal++: 
 xournalpp 1.1.1+dev
└──libgtk: 3.24.20

 - Installation method: ppa:andreasbutti/xournalpp-master

**Describe the bug**
some files with images (most from the clipboard) are impossible to open, even the pdf version of the xopp file.
when I open another xopp file i get the message:
"Xournal crashed the last time. Would you like to restore the last edited file?"
(see screenshot of problem)
>yes
"Error opening ...." (see screenshot of problem)

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/68437253/166891536-c6c5c93f-ba3f-4dd9-9ce6-eb5c8b04bac4.png)
![Screenshot from 2022-05-05 13-26-52](https://user-images.githubusercontent.com/68437253/166914072-778892f9-2aa5-42a9-9787-02f7575be239.png)

**Comment by rolandlo** [comment] 2022-05-05 11:39
Can you please share an image and/or pdf-export, which is impossible to open/results in a crash?

**Comment by rolandlo** [comment] 2022-05-07 05:30
Thanks @stefano-mori and @aberetta145 for the files.
When I open @aberetta145's xopp-file from the console via 
```
xournalpp ./mag_induzione_teoria_magnetismo_circuiti_5CL.xopp
```

I get the following error message:

```term
ERROR:./src/core/model/Image.cpp:88:void Image::setImage(std::string&&): assertion failed: (this->format != nullptr && "could not parse the image format!")
Bail out! ERROR:./src/core/model/Image.cpp:88:void Image::setImage(std::string&&): assertion failed: (this->format != nullptr && "could not parse the image format!")

** (xournalpp:8130): WARNING **: 07:22:17.308: [Crash Handler] Crashed with signal 6

** (xournalpp:8130): WARNING **: 07:22:17.308: [Crash Handler] Wrote crash log to: /home/roland/.cache/xournalpp/errorlogs/errorlog.20220507-072217.log

** (xournalpp:8130): WARNING **: 07:22:17.342: Versuche eine Notfall-Speicherung des aktuell geöffneten Dokuments…

** (xournalpp:8130): WARNING **: 07:22:17.342: Dokument erfolgreich nach "/home/roland/.config/xournalpp/emergencysave.xopp" gespeichert.
```

So the problem is that the image format could not be parsed, which makes some assertion fail, hence Xournal++ crashes.
Now we must try to find out why the image format cannot be parsed and how Xournal++ should deal with it, if it can't parse the image format.

**Comment by Dolland** [comment] 2022-05-08 17:37
Same bug happens on 1.1.1 dev but not on 1.1.0, qhen i try to open the same file

**Comment by aberetta145** [comment] 2022-05-08 18:02
> Same bug happens on 1.1.1 dev but not on 1.1.0, when i try to open the same file

yess, thank you!!

**Comment by tattsan** [comment] 2022-05-08 18:40
It seems to be introduced when #3782 was merged.

**Comment by Technius** [comment] 2022-05-09 00:31
First, we need to figure out whether this is a saving bug, a loading bug, or both.

**Comment by Technius** [comment] 2022-05-09 00:49
Seems like a data _loading_ bug; the images in the xopp file shared by @aberetta145 can be manually extracted to the correct PNGs.

**Comment by Technius** [comment] 2022-05-09 02:54
Should be fixed in #4014. We really need more unit/integration tests for the (de-)serialization code.

**Comment by PascalGotz** [comment] 2022-05-09 07:49
Hi @Technius , I have the same issue on my Windows machine in xournalpp 1.1.1+dev build from 26.04.22. 
My cloud System has a versionn history containing many autosave files of a broken project. Could it be helpful to send them to you? Only the last four or so aren't readable anymore. But I don't have the original image that distroyed the files. But I know it needs to be an areal screenshot made with the new snipping tool integraded in Windows 11. I only imported images by taking a screenshot and pasting them directly in the file. I had two corruped files in the last few days.

**Comment by stefano-mori** [comment] 2022-05-09 09:14
> Should be fixed in #4014. We really need more unit/integration tests for the (de-)serialization code.

This fix solved the issue for me. Thank you all! Great work and support!

**Closed** 2022-05-10 05:14 UTC
Labels: bug, priority::high, Crash, confirmed, regression

**Comment by PascalGotz** [comment] 2022-06-04 08:45
@Technius If I download the latest build, would this fix included?

**Comment by Technius** [comment] 2022-06-04 20:19
Yes, the fix has already been incorporated into the nightly build.
