### ISSUE TITLE
Input Pen not detected on MacOS: No devices found

### ISSUE THREAD

**Issue by andrew67912** [xournalpp/xournalpp#1772] opened 2020-03-14 19:41 UTC
**Affects versions :**
 - MacOS High Sierra, Ver. 10.13.6
 - Xournal++, 1.0.17, Feb 3 2020
 - Pen Wacom Intuous

**Describe the bug**
The pen device is not properly detected. In [Preferences > Input System > Input Devices] the following note shows up:
"No devices were found. This seems wrong - may file a bug report?"

Nevertheless, the pen is working but at only low resolution and without pressure sensitivity. 

**Input Logs**
(As we use the pre-built binary, we do not have a log report file. If required, we could try to rebuild and create a log.) 

A workaround/solution to this bug would be great as we use Xournal++ on multiple OS.

**Comment by adundovi** [comment] 2020-03-14 22:43
I can confirm this, although on a different platform.

- OS: Fedora 31, KDE
- Version: Xournal++ 1.0.16 (RPM from the official repository)
- Wacom Cintiq 16

No tablet features (sensitivity, button, eraser) available within the app, and the stylus acts like a regular mouse. In the settings. the same message as above is displayed. KDE apps recognise it normally, including Krita. GIMP also works with all features, but Inkscape doesn't... maybe a GTK issue after all?

**Comment by fredowski** [comment] 2020-03-19 10:24
I can confirm this 

  * MacOS High Sierra 10.13.6
  * Xournal++ 1.0.17
  * Wacom Cintiq 13 HD

Thanks for your efforts!

**Comment by gioiadc** [comment] 2020-04-02 17:24
Same here, 

- MacOS High Sierra, Ver. 10.15.3

- Xournal++, 1.0.17, Feb 3 2020

- Wacom Intuos

thanks!

**Comment by lagrange2art** [comment] 2020-04-14 18:39
Same with me,

- maxOS Catalina, Ver. 10.15.3
- Wacom Intuos S (Driver Ver. 6.3.38-3) 

The tablet attached via an USBc hub from Aukey. It is properly configured and performs well in OneNote and other programs. There is no version of xournal++ for which the Wacom is recognised as input-device. 
- Xournal++ 1.0.17: no pressure sensitivity, pen buttons cannot be customised
- Xournal++ 1.0.8:  there is pressure sensitivity (although tablet is not recognised) however with     low resolution and "lagging" behaviour.

**Comment by airbete** [comment] 2020-05-01 02:22
Same here:
- OS: Fedora 30, KDE
- Version: Xournal++ 1.1.0+ dev (22a0dd89)
- Wacom Graphire4

The tablet is recognized in KDE settings and works well in other programs (e.g. GIMP) but in xournal++ I get the message "No devices were found. This seems wrong - may file a bug report?"

**Comment by Karuso33** [comment] 2020-05-02 15:17
I can confirm this bug exists on:

- Fedora 31, KDE
- The AppImage release and compiled from source

(I can however also confirm that the exact same setup works on Ubuntu 20.04)

I did find a workaround though: running the application as root works.

I tried to narrow down the problem by debugging DeviceListHelper.cpp (Disclaimer: I have never done anything with Gtk at all). It seems to me that when run as a normal user, the call to `gdk_seat_get_slaves` does not find any devices at all (not even mouse or touchpad), whereas when its run as root, it does find my touchpad for example (and also the graphic tablet).

Testing further, I tried to run `gdk_display_list_devices (gdk_display_get_default())` (which seems to be deprecated now) and when run as root, this lists all devices as expected. When run as a normal user, this only lists a single device with the name "Core Pointer".

I suspect this might be a configuration issue with Fedora, but I don't have the slightest clue as to what config I should even look at.

**Comment by LittleHuba** [comment] 2020-05-02 15:41
Seems like it does not have the permissions to list these devices. I'd recommend filing a bug with the people from Fedora. They know best what could create this issue. 

For the macOS people in this thread your problem ist most likely that GTK does not recognize your device correctly. We get these issues a lot. One fix would be to fix GTK but that is somewhat out of scope for us and currently not managable with our team. We don't really work on Macs and do not have the hardware necessary to test it nor the funds to buy it. Your best bet is heading over to the bug tracker of GTK and file a report there.

But we do have some good news for the long run. We currently work on separating our core logic into a system independent library which will then allow us to write OS-specific apps. But and this but is unfortunately quite big. It will take a few more month to get anywhere with this library. And then we have not even started on developing any OS-specific apps and with the current size of our team this will mot likely not be possible at all. But we might get help by more devs till then...

**Comment by fredowski** [comment] 2020-11-08 07:22
I also see the problem of the not detected wacom pen in xournalpp release 1.0.19 with a Wacom Tablet with MacOS 10.13.6. The pen sensitivity is not working as already desribed in #569. The problem that the input pen is not detected is a problem of the underlying gtk quartz system. This has been addressed by @andreasb242 and [Ignacio](https://gitlab.gnome.org/icq) in gtk.

https://gitlab.gnome.org/GNOME/gtk/-/issues/1551
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1937

The patches landed in the gtk-3-24 branch in May 2020. So they should be included in gtk 3.24.23. 

I have build the latest version of gtk in branch gtk-3-24 with the master branch of xournalpp and then the pen is detected. It works on MacOS 10.13.6 with a Wacom Tablet. It is however a bit laggy as described in  #2302. 

It is [mentioned](https://github.com/xournalpp/xournalpp#mac-os-x) that the MacOS bundle release is build with a patched gtk version. At least the history of mac-setup folder indicates that @LittleHuba and  @andreasb242 are building the MacOS bundle.

I did the build in the macports environment where I only build gtk from source. I build on 10.13.6 with XCode 10. As far as I followed the discussion for the gtk patch it seems that some features are MacOS Version dependent. I did not dig into the details but maybe the build requires to set the MacOS deployment target to make it run for other (older) versions than the build machine version? My test xournalpp MacOS app is here:

https://www.hs-augsburg.de/homes/beckmanf/xournalpp-custom-build-gtk.zip

**Comment by LittleHuba** [comment] 2020-11-08 08:44
I did fix it back then when it was completely broken. As I don't have a Mac which means I'm not really up for string up all that stuff a second time. You can check out the scripts in the `mac-setup` directory and modify them to build the latest version. Make sure to stay on MacOs 10.13 though. After you built GTK you'll have to pack the GTK directory and upload it to this repository. 

https://github.com/xournalpp/xournalpp-pipeline-dependencies/tree/master/gtk 

Check out the packaging script there as well. This will ensure our pipelines work with the new version as well and any automatic releases are built with it.

**Comment by fredowski** [comment] 2020-11-09 11:34
I build all the prerequisites via macports. Then I need to install gettext 0.21 and gtk-mac-integration via normal configure/make. I see that you install gtk via gtk-osx-setup with jhbuild but that did not work for me. I get some build errors. However, the whole build environment from macports is 3.4 GB, e.g. because adwaita-icon-theme needs llvm and rustc. Maybe this can be downstripped by removing pieces like rust.

**Comment by LittleHuba** [comment] 2020-11-09 15:27
That was how it was done before I "fixed" it. In essence it does not really matter how you create the build environment as long as we can use the same approach or a "sufficiently sized" prepared environment in our pipeline.

More important and maybe a deal breaker for macports is that the resulting app should be usable on a MacOS system without any additional stuff. I don't know if you can do that using macports packages as basis for building Xournal++.

**Comment by jcelaya** [comment] 2021-02-25 20:16
For the people with problems in Fedora KDE, the solution is here https://github.com/mypaint/mypaint/issues/388

**Comment by rolandlo** [comment] 2021-04-01 12:12
With the new MacOS pipeline dependencies my `Wacom Intuos Pro` is recognized (as Quartz (Pen)) under MacOS Catalina (1.0.15) and pressure sensitivity works. I have to use input stabilization to get decent strokes, though. You will have to wait for the nightly release tonight until you can test it out.

**Comment by rolandlo** [comment] 2021-07-25 10:52
This is fixed in version 1.1.0

**Closed by rolandlo** 2021-07-25 10:52 UTC
Labels: Input, bug, os::mac, priority::high

**Comment by benjyvc** [comment] 2021-12-04 16:29
If I might revive this thread, which seems relevant to my Intuos tablet not showing pressure sensitivity in Gimp 2.10. Rolandio says "Intuos Pro is recognized (as Quartz (Pen))", which makes sense with what I'm seeing in Gimp Prefs under configure input devices. The strokes are fine, just no pressure sensitivity, have Pressure Opacity enabled under Dynamics. Rolandio, you suggest "This is fixed in version 1.1.0", but can you throw me a bone, not sure what was fixed. Can you point me to an install or such? Many thanks.
