### ISSUE TITLE
Text-tool doesn't work on Windows 7

### ISSUE THREAD

**Issue by ngbvol** [xournalpp/xournalpp#800] opened 2019-01-22 08:27 UTC
No Text can be inserted via keyboard except the CR/LF-key

**Comment by andreasb242** [comment] 2019-01-23 06:37
@morrolinux had the same on macOS, but it was not reproducible by me...
Probably the same issue...

**Comment by peetCreative** [comment] 2019-01-29 12:22
I have under Windows 10 the problem as well.
Now I have to figure out how to compile and debug things. aaaahrg.

**Comment by LittleHuba** [comment] 2019-02-28 23:42
A friend of mine has the same big on his laptop. I'll take a look the next time I see him and triage the issue.

**Comment by morrolinux** [comment] 2019-04-01 08:19
A friend of mine has the same issue on Win10, I can do tests if needed

**Comment by LittleHuba** [comment] 2019-09-10 20:12
Duplicate of #767

**Closed by LittleHuba** 2019-09-10 20:12 UTC
Labels: bug
