### ISSUE TITLE
When I plug a second monitor into my notebook and I'm trying to draw with my Huion tablet, the pointer is in one place but xournall++ draw in other place

### ISSUE THREAD

**Issue by Jus129** [xournalpp/xournalpp#3546] opened 2021-11-06 08:47 UTC
### Discussed in https://github.com/xournalpp/xournalpp/discussions/3340

<div type='discussions-op-text'>

<sup>Originally posted by **geraldotnf-unb** August 21, 2021</sup>
When I plug a second monitor into my notebook and I'm trying to draw with my Huion tablet, the pointer is in one place but Xournal++ draw in other place a little bit to the left and to the bottom where I'm drawing. What I can do solve this?
OBS: When I used to use the old version of Xournal, I just had to to disable the option "use Xinput" to solve this problem, but I'm not founding this option in Xournal++.
I really apreciate it if someone could help me :)</div>

**Comment by bhennion** [comment] 2021-11-06 15:39
What operating system are you running? If Windows, then this is most likely a duplicate of #1801.

**Comment by Jus129** [comment] 2021-11-07 06:57
> What operating system are you running? If Windows, then this is most likely a duplicate of #1801.

Yes, It is windows, and indeed, it's the exact same issue of #1801, I will try the fixes mentioned there, has the bug resurfaced again?

**Closed** 2021-11-07 11:04 UTC
