### ISSUE TITLE
Bold selected words in a textbox

### ISSUE THREAD

**Issue by ra314** [xournalpp/xournalpp#1758] opened 2020-03-03 05:05 UTC
Currently if you press "ctrl + b" while in a textbox, the entire textbox gets boldened. Regardless of wheter or not you have some text already selected. I would like it if only the selected text was boldened.

![Screenshot from 2020-03-03 16-05-22](https://user-images.githubusercontent.com/55324331/75744552-aede2f00-5d68-11ea-92e4-47249471be12.png)

![Screenshot from 2020-03-03 16-05-27](https://user-images.githubusercontent.com/55324331/75744554-b00f5c00-5d68-11ea-876b-f363e76c45bd.png)

**Comment by Technius** [comment] 2020-03-05 20:00
Duplicate of #729.

**Closed by Technius** 2020-03-05 20:00 UTC
Labels: enhancement
