### ISSUE TITLE
How can I make the Default Tool to be Pencil, it chooses the Normal pencil without Tools that I previously used.

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#4177] opened 2022-07-31 22:27 UTC
**Is your feature request related to an issue? Please describe it.**
not specifically, but with a tool

**Describe the solution you would like**
I would like that when selecting the default tool in my case (normal pencil) it is selected without the fill that previously used

**Describe the alternatives you have considered**.
What I can do is go back to the select box and choose to disable padding.

**Additional context**
when geometry exercises or other topics and I use the fill or some type of line (dashed, semipoint) and I try to return to the type of line style I do normal of the pencil it does not work but it returns to the pencil but with the previously selected tools example:
If you are doing a drawing with fill and I want to write and I press the default tool (pencil) it returns to the pencil but still with the fill activated.
another example:
when I am making internal lines of triangles with the dotted line style and I try to choose the main tool that should be a normal pencil with the normal line style it does not happen, it returns to pencil but with the previously selected line style which I would be interested to know if is there a chance to change that 

https://user-images.githubusercontent.com/28522011/182048605-673d1fcc-aad6-40ef-a3bb-56633fcfb450.mp4

**Comment by bhennion** [comment] 2022-08-01 06:32
Duplicate of #2625

**Closed by bhennion** 2022-08-01 06:32 UTC
Labels: enhancement
