### ISSUE TITLE
Xournal asked me to send this logfile

### ISSUE THREAD

**Issue by schoklau** [xournalpp/xournalpp#4988] opened 2023-08-01 11:46 UTC
Date: Thu Jan 12 20:55:49 2023
Error: signal 11
[bt]: (0) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(+0x1e0a60) [0x56269ebe0a60]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fd1c9df0520]
[bt]: (2) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN20AbstractInputHandler5blockEb+0) [0x56269eb90f10]
[bt]: (3) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN12InputContext13unblockDeviceENS_10DeviceTypeE+0x1d) [0x56269eb91acd]
[bt]: (4) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN15HandRecognition11enableTouchEv+0x17) [0x56269eb91187]
[bt]: (5) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN15HandRecognitionD2Ev+0x35) [0x56269eb911e5]
[bt]: (6) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN15HandRecognitionD0Ev+0x9) [0x56269eb911f9]
[bt]: (7) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN11XournalViewD1Ev+0xa3) [0x56269eb6ff43]
[bt]: (8) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN11XournalViewD0Ev+0x9) [0x56269eb6ff89]
[bt]: (9) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN10MainWindowD2Ev+0x90) [0x56269eb60070]
[bt]: (10) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN10MainWindowD0Ev+0x9) [0x56269eb60119]
[bt]: (11) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN11XournalMain3runEiPPc+0x4e3) [0x56269eadd143]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fd1c9dd7d90]
[bt]: (13) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fd1c9dd7e40]
[bt]: (14) /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_start+0x2a) [0x56269eabbe1a]

Try to get a better stracktrace...
[bt] #1 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(+0x1e0f31) [0x56269ebe0f31]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fd1c9df0520]
??:0
[bt] #3 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN20AbstractInputHandler5blockEb+0) [0x56269eb90f10]
??:0
[bt] #4 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN12InputContext13unblockDeviceENS_10DeviceTypeE+0x1d) [0x56269eb91acd]
??:0
[bt] #5 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN15HandRecognition11enableTouchEv+0x17) [0x56269eb91187]
??:0
[bt] #6 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN15HandRecognitionD2Ev+0x35) [0x56269eb911e5]
??:0
[bt] #7 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN15HandRecognitionD0Ev+0x9) [0x56269eb911f9]
??:0
[bt] #8 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN11XournalViewD1Ev+0xa3) [0x56269eb6ff43]
??:0
[bt] #9 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN11XournalViewD0Ev+0x9) [0x56269eb6ff89]
??:0
[bt] #10 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN10MainWindowD2Ev+0x90) [0x56269eb60070]
??:0
[bt] #11 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN10MainWindowD0Ev+0x9) [0x56269eb60119]
??:0
[bt] #12 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_ZN11XournalMain3runEiPPc+0x4e3) [0x56269eadd143]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fd1c9dd7d90]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fd1c9dd7e40]
??:0
[bt] #15 /tmp/.mount_xournaXsiq5O/AppRun.wrapped(_start+0x2a) [0x56269eabbe1a]
??:0

**Comment by bhennion** [comment] 2023-08-01 19:19
This crash log is dated from january. You have probably upgraded Xournal++, so now existing bugreports are shown. This is a duplicate of #4917, #4651, #4038, #2013. and #4979. So I'm closing it.

**Closed by bhennion** 2023-08-01 19:19 UTC
