### ISSUE TITLE
Tool switching doesn't work correctly when using the erasor with a shortcut previously

### ISSUE THREAD

**Issue by Cogitri** [xournalpp/xournalpp#1546] opened 2019-10-15 12:09 UTC
**Affects versions :**
 - OS: Linux
 - In case of linux, which desktop environment: GNOME Wayland
 - Which version of libgtk do you use: 3.24.12
 - Version of Xournal++: 1.0.14

**Describe the bug**
When I set one of the buttons my of my pen (stylus?) to be a shortcut to eraser switching colours (or other tools rdoesn't work correctly)

**To Reproduce**
1. Set shortcut as mentioned above (in my case use Key2 for eraser)
2. Erase something, triggered by the shortcut
3. Stop pressing the key to switch back to the pen
4. Select another colour
5. When starting to draw it will switch back to the previous colour instead of using the newly selected colour. You have to draw once with the pen, then selecting the colour works.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by MisterPresident** [comment] 2019-10-29 22:44
Same issue here, my stylus buttons do not work correctly on wayland.
Under X my button selects the Tool of "Button 1" and everything works correctly. Using wayland the same button selects the "Button 2" tool and I have to repress the button (near the screen) to switch back to the tool which I had before pressing the button.

**Comment by LittleHuba** [comment] 2019-10-30 11:53
@MisterPresident 
1. This looks like a different bug. If you mix bugs it is hard for us to follow them so please open a separate ticket.
2. Please provide input logs. For any input related error we will need the input logs every single time. Otherwise we are not really able to see what the issue is and what causes it.

**Comment by jvwowd** [comment] 2020-04-04 17:20
#1712

**Comment by idotobi** [comment] 2020-05-12 16:14
@Cogitri : I would close this and continue the discussion at #1712 as it seems to be that this is basically the same problem/root cause. Do you agree?

**Comment by Cogitri** [comment] 2020-05-12 16:57
Ah, sure, sounds good.

**Comment by idotobi** [comment] 2020-05-25 20:36
I just realized that this bug is actually slightly different in nature than the one described in #1712 :sweat_smile:  so I reopen it.

**Closed** 2020-10-04 16:22 UTC
Labels: bug
