### ISSUE TITLE
Export to PDF : accent disappears

### ISSUE THREAD

**Issue by deb75** [xournalpp/xournalpp#3206] opened 2021-07-03 12:42 UTC
**Affects versions :**
 - OS: windows 10
 - xournalpp : 1.0.20

**Describe the bug**, **To Reproduce**

- install locally xournalpp with scoop or zip archive
- open xournalpp by clicking on xounrnalpp_bin.exe
- open a pdf to annotate, make some
- export as pdf
- open pdf with another viewer : all accents are replaced by phi symbols
- open pdf with xournalpp itself : result is "ugly"

On launching xournalpp from the command line, I get the warning : 
```
(com.github.xournalpp.xournalpp:12160): Pango-WARNING **: 14:38:59.155: couldn't load font "C059 Not-Rotated 8", falling back to "Sans Not-Rotated 8", expect ugly output.
```

Sometimes, I start xournalpp from a mingw64 shell, which means that xournalpp will probably load the libraries it need from the mingw64 path instead of the provided libraries in the xournalpp bin directory. Could it be the issue ?

Regards

**Comment by rolandlo** [comment] 2021-07-03 13:34
Duplicate of  #3014. Please upgrade to version 1.1.0+dev.

**Closed by rolandlo** 2021-07-03 13:34 UTC
Labels: bug

**Comment by deb75** [comment] 2021-07-03 23:12
Thanks, it works now with 1.1.0+dev

Regards
