### ISSUE TITLE
Object library target "xournalpp-core" may not link to anything

### ISSUE THREAD

**Issue by Krzmbrzl** [xournalpp/xournalpp#2058] opened 2020-06-11 06:27 UTC
**Affects versions :**
 - OS: Linux
 - (Linux only) Desktop environment: X11
 - cmake: 3.10.2

**Describe the bug**
When trying to invoke cmake it errors with
```
Found: TRUE
-- Checking for module 'gtk-mac-integration'
--   No package 'gtk-mac-integration' found
Enable Xournal++ Plugins
CMake Error at src/CMakeLists.txt:87 (target_link_libraries):
  Object library target "xournalpp-core" may not link to anything.

-- Configuring incomplete, errors occurred!
```

**To Reproduce**
1. Clone current master
2. `mkdir build && cd build`
3. `cmake ..`

According to https://stackoverflow.com/questions/53416527/cmake-object-library-target-may-not-link-to-anything the error is correct and object libraries shouldn't link to anything :shrug:

**Comment by Technius** [comment] 2020-06-11 19:00
Duplicate of #2048.

**Closed by Technius** 2020-06-11 19:00 UTC
Labels: bug
