### ISSUE TITLE
Pen-Buttons not working

### ISSUE THREAD

**Issue by taneher** [xournalpp/xournalpp#1050] opened 2019-04-05 09:27 UTC
First of all, thanks for this actually actively developed stylus-supported note-taking tool!

I just cloned and built xournalpp on Debian sid (4.19.0-1-amd64 #1 SMP Debian 4.19.13-1 (2018-12-30) x86_64 GNU/Linux) on my HP Spectre X360. I use the HP Pro Active Pen 408 G1 with it. It comes with two programmable buttons, which I want to map to Eraser/Highlighter.

I mapped them under settings > stylus, but button2 does not work at allm (when I press it, I'm still using the same tool than I was using before) and the eraser does only work when hovering. So I can erase strokes made by the pen while pressing button1, but the pen mustn't touch the screen, but hover a few millimeters above the screen, close enough for the screen to still recognize the pen.

**Comment by LittleHuba** [comment] 2019-04-05 09:44
See the FAQ for the hovering issue. We are currently discussing a fix in #940.

Please provide us the internal number xinput maps your stylus button to by following the guide in this article using `xev`:
https://wiki.archlinux.org/index.php/wacom_tablet#Remapping_buttons

**Comment by taneher** [comment] 2019-04-06 14:20
Hey, sorry for the late reply. I only searched for 'pen' in the issues, so I didn't find it.

The output of the 'xev'-command for my pen is as follows:

```
[alex@debian-laptop: ~]$ xev -event button
Outer window is 0x3800001, inner window is 0x3800002

ButtonPress event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 180582, (54,118), root:(981,340),
    state 0x0, button 1, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 180661, (55,121), root:(982,343),
    state 0x100, button 1, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 186651, (60,111), root:(987,333),
    state 0x0, button 1, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 186754, (62,115), root:(989,337),
    state 0x100, button 1, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 194665, (72,133), root:(999,355),
    state 0x0, button 2, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 194729, (75,135), root:(1002,357),
    state 0x200, button 1, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 194815, (77,139), root:(1004,361),
    state 0x300, button 1, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3800001,
    root 0x1aa, subw 0x0, time 194891, (64,132), root:(991,354),
    state 0x200, button 2, same_screen YES
```

This was first tapping the pen without any buttons pressed, then with the front button pressed and then with the back button pressed. 
The no-button and front-button pressed created each two blocks and the back-button created the last four blocks.

**Comment by LittleHuba** [comment] 2019-04-06 14:30
The problem is in xinput not recognizing your first button. There is some bug in your dirver or system settings. We can do nothing from our side unfortunately. 

Therefore I'll close the issue but you may post your configuration files of the XServer and I'll take a look.

**Closed by LittleHuba** 2019-04-06 14:30 UTC
