### ISSUE TITLE
Xournal++ does not open any document

### ISSUE THREAD

**Issue by tumb1er** [xournalpp/xournalpp#1393] opened 2019-08-04 16:09 UTC
**Affects versions :**
 - OS: Ubuntu 19.04
 - Version of Xournal++ 1.0.13

**Describe the bug**
Error "XML Parser error: Wrong count of points (1)" on any opened document

**To Reproduce**
1. Create new document
2. Draw anything (single stroke is enough)
3. Save document
4. Reopen doc from "open" dialog or "Recent Documents"
5. An "XML Parser error" occurs, file not loaded.

**Expected behavior**
File is opened correctly

**Screenshots of Problem**
no.

**Additional context**
no.

**Comment by veecue** [comment] 2019-08-04 16:29
I'm afraid, I can't reproduce this. Can you specify your exact xournalpp version (commit id) and attach the .xopp file that creates the error (you have to zip it so you can upload it to github)?

**Comment by tumb1er** [comment] 2019-08-05 07:27
[2019-08-03-Note-16-17.zip](https://github.com/xournalpp/xournalpp/files/3466367/2019-08-03-Note-16-17.zip)

```
$ apt show xournalpp
Package: xournalpp
Version: 1.0.6-0~201908020631~ubuntu19.04.1
Priority: optional
Section: misc
Maintainer: Andreas Butti <andreasbutti@gmail.com>
Installed-Size: 4 253 kB
Depends: libc6 (>= 2.29), libcairo2 (>= 1.4.10), libgcc1 (>= 1:3.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk-3-0 (>= 3.19.12), liblua5.3-0, libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libpoppler-glib8 (>= 0.18.0), libportaudio2 (>= 19+svn20101113), libportaudiocpp0, libsndfile1 (>= 1.0.20), libstdc++6 (>= 6), libx11-6, libxi6 (>= 2:1.2.0), libxml2 (>= 2.7.4), libzip5 (>= 1.0), zlib1g (>= 1:1.1.4)
Download-Size: 955 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu disco/main amd64 Packages
Description: Xournal++ is a handwriting Notetaking software with PDF annotation support. Supports Pen input like Wacom Tablets.
```

**Comment by veecue** [comment] 2019-08-05 08:44
The problem relies in `Util::getCoordinateString`, because `g_snprintf` is affected by the system locale (e.g. `LANG=de_DE.UTF-8`). I couldn't find a simple alternative like `g_ascii_snprintf`, so we might have to roll our own

**Comment by veecue** [comment] 2019-08-05 08:45
CC @siliconninja

**Comment by Febbe** [comment] 2019-08-05 09:16
That's why I hate c style io the c++ iostreams are way more robust. They are just incredibly slow

**Comment by LittleHuba** [comment] 2019-08-05 09:23
Please also add a test to our test suite so we catch these issues in the future. Something like this should not make it into a release.

**Comment by JJones780** [comment] 2019-08-05 09:28
This is my fault. I reviewed the code and merged it... and should've known better as I also looked at the locale issue quite recently.  Yes, a test case would go a long way to avoid this recurring in the future.

**Comment by veecue** [comment] 2019-08-05 09:31
@tumb1er Can you checkout issue-1393 to see if the issue is fixed?

**Comment by JJones780** [comment] 2019-08-05 09:36
@veecue - your #1396 looks good to me. Thanks.

**Comment by veecue** [comment] 2019-08-05 09:41
So how would we test this? Load an existing document from the the test assets (with strokes, lines, dots, etc), save it, reopen it and check whether the contents are the same? Would be the easiest method, I can imagine.

**Comment by JJones780** [comment] 2019-08-05 10:24
I think loading a test file and comparing the save from an English locale run and a Swiss locale run would do it.

**Comment by tumb1er** [comment] 2019-08-05 11:21
> @tumb1er Can you checkout issue-1393 to see if the issue is fixed?

Not sure if I can quickly build it from source...

**Comment by veecue** [comment] 2019-08-05 11:32
> Not sure if I can quickly build it from source...

Try replacing your xournalpp executable with this one (I just built it):
[xournalpp.zip](https://github.com/xournalpp/xournalpp/files/3467362/xournalpp.zip)

**Comment by tumb1er** [comment] 2019-08-05 11:49
@veecue binary from zip-file needs `liblua.so.5.3`.
I've checkout-ed [issue-1393](https://github.com/xournalpp/xournalpp/tree/issue-1393) and build binary with [these instructions](https://github.com/xournalpp/xournalpp/blob/issue-1393/readme/LinuxBuild.md).
* Old files still have same error on open.
* New file is saved and opened correctly.

But! There is another strange case:
1. Open invalid document (like zipped one in issue)
2. Write a stroke on current doc in same process
3. Save this as NEW doc
3. Try to reopen NEW doc
Expected: NEW doc is opened correctly
Real: NEW doc is opened with hidden background and app crashes on Background Layer - Show click:
```
** (xournalpp:18431): WARNING **: 14:46:48.666: XojTypeCheck failed: NULL /tmp/xournalpp/src/model/XojPage.cpp:138

** (xournalpp:18431): WARNING **: 14:46:48.666: [Crash Handler] Crashed with signal 11

** (xournalpp:18431): WARNING **: 14:46:48.667: [Crash Handler] Wrote crash log to: /home/tumbler/.xournalpp/errorlogs/errorlog.20190805-144648.log

** (xournalpp:18431): WARNING **: 14:46:49.120: Trying to emergency save the current open document…

** (xournalpp:18431): WARNING **: 14:46:49.120: Successfully saved document to "/home/tumbler/.xournalpp//emergencysave.xopp"
```

If you create new document after "open error", all works correctly.

**Comment by veecue** [comment] 2019-08-05 13:48
@tumb1er The error when opening the old document is expected since it occured on saving. If you rely on those documents, you might try to replace "0,00" (all numbers) with "0.00" in the xml file (gunzipped).
Please repost the other strange case as a new issue, it should be unrelated to this.

**Comment by tumb1er** [comment] 2019-08-05 14:23
Well, that strange case will not be reproducible after fixing this issue, because there will be not possible to get corrupted document. So I'll just wait for this issue to be fixed.

**Comment by Rmano** [comment] 2019-08-05 14:29
> Well, that strange case will not be reproducible after fixing this issue, because there will be not possible to get corrupted document. So I'll just wait for this issue to be fixed.

In my opinion it would be worth the effort to fix. You never know when you can get a corrupted document (user editing the XML, disc failure, [oh-my-god particle ](https://what-if.xkcd.com/20/)hitting the RAM ;-) )  --- hard crashes should be avoided.

**Comment by siliconninja** [comment] 2019-08-05 14:33
> The problem relies in Util::getCoordinateString, because g_snprintf is affected by the system locale (e.g. LANG=de_DE.UTF-8). I couldn't find a simple alternative like g_ascii_snprintf, so we might have to roll our own
Huh. That's interesting. I did not know that. I'm glad that a test case is being added for this.
> In my opinion it would be worth the effort to fix. You never know when you can get a corrupted document (user editing the XML, disc failure, oh-my-god particle hitting the RAM ;-) ) --- hard crashes should be avoided.
I agree.

**Comment by tumb1er** [comment] 2019-08-05 14:41
@Rmano @siliconninja #1397 - related bug.

**Closed** 2019-08-10 06:51 UTC
Labels: bug, confirmed

**Comment by veecue** [comment] 2019-08-10 11:50
For everybody who needs their corrupted files:
`cat corrupted.xopp | gunzip | sed -E 's/([0-9]+),([0-9]{8})/\1.\2/g' | gzip > fixed.xopp`
