### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by drussellluke-nam** [xournalpp/xournalpp#4980] opened 2023-07-31 16:35 UTC
I just tried to open a pdf document in Xournal++.  Nothing unusual.  Was not running anything other than THunderbird and Firefox in background. 

**************
Date: Mon Jan 24 08:34:50 2022
Error: signal 11
[bt]: (0) /snap/xournalpp/62/usr/bin/xournalpp(+0x437bac) [0x55df28407bac]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f9e0f790210]
[bt]: (2) /snap/xournalpp/62/usr/bin/xournalpp(_ZNK7Element7getTypeEv+0x10) [0x55df283c69ce]
[bt]: (3) /snap/xournalpp/62/usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x24) [0x55df283fa51a]
[bt]: (4) /snap/xournalpp/62/usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x13a) [0x55df283fa7c4]
[bt]: (5) /snap/xournalpp/62/usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0x16e) [0x55df283fb032]
[bt]: (6) /snap/xournalpp/62/usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x1fe) [0x55df28282fc8]
[bt]: (7) /snap/xournalpp/62/usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x4d) [0x55df28283387]
[bt]: (8) /snap/xournalpp/62/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x55df28282355]
[bt]: (9) /snap/xournalpp/62/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e8) [0x55df2828668c]
[bt]: (10) /snap/xournalpp/62/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x8b691) [0x7f9e10e17691]
[bt]: (11) /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f9e0fd8f609]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f9e0f86c293]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/62/usr/bin/xournalpp(+0x43811e) [0x55df2840811e]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f9e0f790210]
??:0
[bt] #3 /snap/xournalpp/62/usr/bin/xournalpp(_ZNK7Element7getTypeEv+0x10) [0x55df283c69ce]
??:0
[bt] #4 /snap/xournalpp/62/usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x24) [0x55df283fa51a]
??:0
[bt] #5 /snap/xournalpp/62/usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x13a) [0x55df283fa7c4]
??:0
[bt] #6 /snap/xournalpp/62/usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0x16e) [0x55df283fb032]
??:0
[bt] #7 /snap/xournalpp/62/usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x1fe) [0x55df28282fc8]
??:0
[bt] #8 /snap/xournalpp/62/usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x4d) [0x55df28283387]
??:0
[bt] #9 /snap/xournalpp/62/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x55df28282355]
??:0
[bt] #10 /snap/xournalpp/62/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e8) [0x55df2828668c]
??:0
[bt] #11 /snap/xournalpp/62/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x8b691) [0x7f9e10e17691]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f9e0fd8f609]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f9e0f86c293]
??:0

**Comment by rolandlo** [comment] 2023-07-31 16:39
The bug happened on Jan 24, 2022. You have probably upgraded Xournal++, so now existing bugreports are shown. This is a duplicate of #4917, #4651, #4038, #2013. and #4979. So I'm closing it.

**Closed by rolandlo** 2023-07-31 16:39 UTC
