### ISSUE TITLE
Moving a selection crashed the app

### ISSUE THREAD

**Issue by amitnovick** [xournalpp/xournalpp#5135] opened 2023-09-09 20:57 UTC
### Operating System

Linux

### (Linux only) Distribution

Linux Mint 21

### (Linux only) Desktop Environment

XFCE

### (Linux Only) Display Server

X.Org

### Installation Method

Github Releases: xournalpp-1.2.1-Ubuntu-jammy-x86_64.deb

### Xournal++ Version

1.2.1

### libgtk Version

3.24.33

### Bug Description

I was moving some selection from one place to another
the app crashed

Error log files:
[xournalpp_error_log_1.txt](https://github.com/xournalpp/xournalpp/files/12566771/xournalpp_error_log_1.txt)
[xournalpp_error_log_2.txt](https://github.com/xournalpp/xournalpp/files/12566772/xournalpp_error_log_2.txt)

### Expected Behaviour

Selection moves over
app not crashing

### Steps to Reproduce

I don't know how to reproduce it

### Additional Context

The prompt to report on this issue came from the app

I have been using this version of Xournal for only 2 days.
Before that, I had been using an earlier version (don't remember which) that never crashed on me.

EDIT: downgraded to Xournal++ version 1.1.3 and don't get more crashing events.

**Comment by Febbe** [comment] 2023-09-13 17:09
Dupe of  #5126

**Closed by Febbe** 2023-09-13 17:09 UTC
Labels: bug
