### ISSUE TITLE
Suggestion: zoom panel

### ISSUE THREAD

**Issue by lfourquaux** [xournalpp/xournalpp#1114] opened 2019-05-03 15:31 UTC
A zoom panel (aka zoom window or zoom box), similar to the one in some iOS app (e.g. GoodNotes) would IMHO be a very useful addition to xournal++.

The key benefit is to provide a zoomed area for input (and thus, much enhanced precision) while simultaneously offering a global view of the page.

If you have never seen such a UI, this would split the window into a (smaller) lower panel which accepts pen input and provides a zoomed view of the document, and a higher panel that shows a whole page (or a much less zoomed view) and a rectangle indicating the area shown in the lower panel. Pen/mouse/touch input in the higher panel can be used to scroll the document and to move the zoomed area.

This can later be enhanced by heuristics for moving the zoomed area whenever input approaches its edge.

**Comment by LittleHuba** [comment] 2019-05-03 15:36
This is mostly a duplicate of #936. I'll close it for now as your use case is covered by that issue except:
> a rectangle indicating the area shown in the lower panel

**Closed** 2019-05-03 15:36 UTC

**Comment by lfourquaux** [comment] 2019-05-03 17:44
There are UI differences between this and simply multiple views (note that the pen behaves differently in the two panels), but #936 (which I missed because it does not mention zooming) would certainly be a good first step.  Thanks!
