### ISSUE TITLE
possibility of filling a closed figure with a paint can tool

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#4630] opened 2023-01-31 22:45 UTC
**Is your feature request related to a problem? Please describe.**
no, but it would be interesting to have this functionality

**Describe the solution you'd like**
I would like to have 2 things: 1) paint pot inside and that you can adjust the opacity. 2) when making a closed shape allow to fill the closed area with paint pot windows style. I think it would be very interesting to be able to fill in a more optimal and precise way small or large spaces, which would be very useful in courses such as geometry, trigonometry etc.

**Describe alternatives you've considered**
at the moment the alternative I use is to use the highlighter in thick point but it is not very precise, or sometimes I use the fill tool but it is only optimal with the preset figures or if you make your own figure the result is not the expected as for example I tried to make 2 circles intersecting but I wanted to be shaded both sides except the intersection, and I did not achieve the expected result with the fill tool.

**Additional context**
![image](https://user-images.githubusercontent.com/28522011/215900533-371d7271-0af8-40bf-985e-a0878f54aa4a.png)
![image](https://user-images.githubusercontent.com/28522011/215900712-d39a429d-e3ad-4f4c-81bb-586c18ebb379.png)

**Comment by bhennion** [comment] 2023-02-01 07:20
Duplicate of #3327

**Closed** 2023-02-01 07:21 UTC
Labels: enhancement

**Comment by vladQll** [comment] 2023-02-02 14:34
@bhennion Hi I understand that you closed this but I checked the duplicate and I still don't understand how #3327 would solve my aggregate function request I followed the steps in the example video in #3327 and I wanted to try it by trying to fill in a few angles but it doesn't get what I expected, however one of the solutions would be to try to carefully draw with the pencil a portion of the angle to fill it or I could try to paint it very carefully by hand using the pencil or highlighter but the goal of my request was to be able to fill a figure that would close something like in mspaint, or other programs.
I attach images

rfilling an area with the fill tool in xournal++
![image](https://user-images.githubusercontent.com/28522011/216351150-ae26702b-a148-4527-81fe-2b845e346d62.png)

trying to create a figure of the angle to be able to fill it in xournal++
![image](https://user-images.githubusercontent.com/28522011/216351690-2a7d9ef2-9e06-4e49-92a1-1d8936367d04.png)

mspaint fill mode expected in xournal++
![image](https://user-images.githubusercontent.com/28522011/216352836-71e99e0d-566d-40ba-8c3d-6544d9accd68.png)

**Comment by bhennion** [comment] 2023-02-02 20:40
Half of #3327 is about requesting the filling "can" (or whatever it's called) that most raster graphics programs have. Exactly the tool you are mentionning in MSPaint for instance.
By marking this as a duplicate, I am not saying this is resolved, I'm just saying someone else has already requested that feature. There is not need to keep several redundant tickets open.

**Comment by rxge-maker** [comment] 2026-06-06 00:33
hi did anyone find a solution for it?
