### ISSUE TITLE
The cursor doesn't change.

### ISSUE THREAD

**Issue by DuendeInexistente** [xournalpp/xournalpp#1321] opened 2019-07-03 05:38 UTC
**Affects versions :**
 - OS: ubuntu 17.10
 - Version of Xournal++: 32cf15ad3a4c7988ae02fc08c8700ff9c2b923f9

**Describe the bug**
The cursor isn't changed by the pen and marker tools.
Using the tools temporarily changes the cursor to its square as usual, but releasing the pen/mouse button it reverts it back to the default OS pointer.

**To Reproduce**
Compile and open xournalpp in ubuntu.

**Comment by LittleHuba** [comment] 2019-07-03 06:23
Are you using the new input system? Please activate it in the settings to fix this "bug".

**Comment by LittleHuba** [comment] 2019-07-03 06:24
Duplicate of #1290

**Closed by LittleHuba** 2019-07-03 06:24 UTC
Labels: bug
