### ISSUE TITLE
Canvas Blank on Switch Desktop

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#17] opened 2013-09-01 01:36 UTC
Sometimes upon switching desktop away and back to Xournalpp (Fedora Core 19 addpoppler branch) the canvas is completely blank (the view is just a titlebar with no features) with a stroke-input cursor until some stroke is drawn, upon which a complete refresh takes place.

This might be due to incompatibilities with the newest gtk, perhaps?

**Comment by MarPiRK** [comment] 2015-10-02 20:10
Is it still there? It is a while since `addpoppler`.

**Comment by wbrenna** [comment] 2015-10-02 20:12
I suspect it is - I think it's due to the threading problems. Basically it works OK when I run it without threads but there is a large host of problems because threading is currently broken.

**Comment by MarPiRK** [comment] 2015-10-10 09:22
I can reproduce this problem on my machine (lowering system clock and a little of stress on CPU).

**Comment by wbrenna** [comment] 2015-10-10 15:06
Good to know - stressing the CPU can bring a wealth of threading bugs. IMO the entire threading needs to be rethought for gtk3.

**Comment by MarPiRK** [comment] 2015-10-10 15:58
True

**Comment by andreasb242** [comment] 2018-11-11 19:55
Changed to GTK - close this bug because of age

**Closed by andreasb242** 2018-11-11 19:55 UTC
Labels: bug, high priority
