### ISSUE TITLE
Immediate Crash under MacOS

### ISSUE THREAD

**Issue by Addlai** [xournalpp/xournalpp#3198] opened 2021-06-30 18:07 UTC
Version 1.0.20 crashes instantly on start up on 
MacBook Pro 15 inch, 2018
MacOS BigSur 11.4

**Comment by rolandlo** [comment] 2021-06-30 18:12
Duplicate of  #2836. 
Please try out the nightly release of version [1.1.0+dev](https://github.com/xournalpp/xournalpp/tree/nightly) or wait for the official release of version 1.1.0, which is going to happen in a couple of days.

**Closed by rolandlo** 2021-06-30 18:12 UTC
