### ISSUE TITLE
Clicking Stylus Button 2 activates  defined function again and again and again

### ISSUE THREAD

**Issue by StefanL38** [xournalpp/xournalpp#2894] opened 2021-03-02 08:23 UTC
Hi I'm currently using xournal++ V1.1 Build 25.02.21

If I define any kind of action for Stylus-Button 2 and click on this button the function gets actiavted like it should.  
But then the function gets actiavted always the stylus comes close to the touch-screen

Example: I have activated normal pen normal drawing and draw some freehand lines.  
No I press stylus-button 2 which activates highlighting. I do some highlighting and then change back to normal drawing.

Each time the stylus comes near to the surface of the touch-screen so the "target-point" appears.  
high-lighting gets activated again.  
I activate normal pen-drawing by tapping on the normal-pen-drawing-button I want to start drawing come close to the touch-screen "target-point appears" xournal++ switches to highlighting

I activate normal pen-drawing by tapping on the normal-pen-drawing-button I want to start drawing come close to the touch-screen "target-point appears" xournal++ switches to highlighting

I activate normal pen-drawing by tapping on the normal-pen-drawing-button I want to start drawing come close to the touch-screen "target-point appears" xournal++ switches to highlighting  
again and again and again.

The only thing that stops this behaviour is to disable the button or to restart xournal+

best regards Stefan

**Comment by tattsan** [comment] 2021-03-02 08:55
See ``Merge button events with stylus tip events`` checkbox in ``Edit -> Preferences -> Input System`` .
If it is checked, try uncheck it.

**Comment by StefanL38** [comment] 2021-03-02 09:55
It was unchecked 

so I tried it checked activating merge button-events with stylus tip-events 

but the behaviour stays the same: still every time the stylus comes near the surface not even touching it

I activate pen-drawing stylus comes near the surface mode switches to highlighting

best regards Stefan

**Comment by tattsan** [comment] 2021-03-02 10:33
I can't reproduce it. It would be better to describe your environment in detail.

**Comment by StefanL38** [comment] 2021-03-02 10:40
Lenovo Thinkpad X1 tablet generation 1

processor Intel Core m7-6Y75 CPU 1,2 GHz / 1.51 GHz 8 GB RAM, 

Windows 10 pro Version 20H2 OS-Build 19042.572

Windows Feature Experience Pack 120.2212.31.0

supports stylus and touch-input with up to 10 touch-points

What do you need more? microsoft.net versions?   microsoft-redistributable-versions?

additional installated software?

Do you have any kind of system-info-software that can look up all these data-details that is freeware and I can run it posting you the resultfile?

best regards Stefan

**Comment by tattsan** [comment] 2021-03-02 10:59
Sorry, I'm not a Windows user. Wait until other Windows users confirm it.

**Comment by rolandlo** [comment] 2021-03-02 11:31
This looks related to  #2628. I also have troubles with stylus buttons on Windows. The input logs generated under Windows are quite different than those under Linux what concerns stylus buttons. The question is whether something is wrong on Xournal++ side or if it is a pure Gtk+ problem. See #2316 for a version which supports the Windows Pointer API. Gtk+'s stylus support under Windows looks still quite primitive. It's not only Xournal++ struggling with that problem. 

@everybody having troubles with stylus buttons on Windows: Consider [building Xournal++ from source](https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md), [generate the input logs](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs) from the MinGW64 console, do the same thing under Linux (if available) and help trying to find out the core of the problem.

@StefanL38 Writing things like 

> What the heck are you coding guys? Do you skip testing most of the time?
> to me xournal++ seems to have left the early alpha-state.

makes you come across rude and creates a bad atmosphere. Please refrain from it! After all Xournal++ is a free and open source project created by volunteers in their free time, with no financial benefit at all, and apparently works beautifully for lots of users. Sure Xournal++ is not tested as well on Windows as on Linux (which is the main platform used by all devs), but there are also things which simply have to be solved upstream. The whole project needs the feedback/testing and bug fixes from the whole community and this applies especially to platforms that we (the dev team) don't use so much.

**Comment by StefanL38** [comment] 2021-03-02 11:53
Just out of interest:  without beeing an expert about C-compilers etc. my imagination of developing a cross-plattform software is:

use a programming-language that is available for all platforms. Try to keep the code euqal as much as possible to reduce maintaining-effort. To jump from one OS to another: copy source-code to the other OS and re-compile. Done.

If any changes have to be made for compiling for another OS use extra-files that control this 

or at least #ifdefine-conditions to compile this or that OS

best regards Stefan

**Comment by kubajaburek** [comment] 2021-03-09 13:40
> The question is whether something is wrong on Xournal++ side or if it is a pure Gtk+ problem. See #2316 for a version which supports the Windows Pointer API.

I think it’s on Xournal++ side, as I have the same issue even with WinPointer API and I didn’t have the issue before the old input system got removed.

Do we actually need the whole build environment to generate input logs? Or could I build Xournal++ with some kind of debug flag on my computer and then run it on my tablet (without installing Mingw) to try to debug the issue?

**Comment by rolandlo** [comment] 2021-03-09 21:43
@kubajaburek 

Let's try to find out what goes wrong with the new input system. I think running Xournal++ outside of MinGW (and inside the Windows command prompt) has the problem, that you won't see the debug messages. It would certainly be possible to modify the code to get the debug messages printed into a file directly, rather than vanishing in the air. The messages printed for the input logs are printed inside `#ifdef DEBUG_INPUT`  and `#endif` precompiler statements in `InputContext.cpp`, `PenInputHandler.cpp` and `TouchDiableGdk.cpp` using `g_message`s. These messages would have to be printed to a file.

**Comment by rolandlo** [comment] 2021-03-10 13:54
> Do we actually need the whole build environment to generate input logs? Or could I build Xournal++ with some kind of debug flag on my computer and then run it on my tablet (without installing Mingw) to try to debug the issue?



> @kubajaburek
> 
> Let's try to find out what goes wrong with the new input system. I think running Xournal++ outside of MinGW (and inside the Windows command prompt) has the problem, that you won't see the debug messages. It would certainly be possible to modify the code to get the debug messages printed into a file directly, rather than vanishing in the air. The messages printed for the input logs are printed inside `#ifdef DEBUG_INPUT` and `#endif` precompiler statements in `InputContext.cpp`, `PenInputHandler.cpp` and `TouchDiableGdk.cpp` using `g_message`s. These messages would have to be printed to a file.

Adding to that: We actually have a Logger class, for writing logs into a file. It has been used for other purposes (it seems to detect memory leaks) and doesn't log anything any more (even with activated `DEV_CALL_LOG` flag), but it could be easily used for writing the input debug messages into a log file.

**Comment by StefanL38** [comment] 2021-03-11 22:21
Just to inform you: I have bought a licence for the software concepts 5 for 15 Euro

very efficient operating concept and a lot of tools. You can download a free version with limited functiona.

This free version still gives a good impression how it works. Maybe you find some functions useful and will implement them in a later version of xournal++

my personal opinion: if xournal is ++   concepts 5 is ++++++++

best regards Stefan

**Comment by rolandlo** [comment] 2021-03-11 22:39
@StefanL38 This is completely off-topic.

**Comment by rolandlo** [comment] 2021-07-03 17:34
The patched GTK+ 3 has now been merged. You can copy the `libgdk-3-0.dll` and `libgtk-3-0.dll` into your [Xournal++ 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) installation as described [here](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907). This may solve the issue.

**Comment by rolandlo** [comment] 2021-07-23 04:38
The issue should be fixed in [Version 1.1.0-hotfix+1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). Please report if you experience otherwise.

**Closed by rolandlo** 2021-07-23 04:38 UTC
Labels: bug, os::windows
