### ISSUE TITLE
Presentation Window

### ISSUE THREAD

**Issue by H-M-H** [xournalpp/xournalpp#2020] opened 2020-05-29 09:52 UTC
**Is your feature request related to a problem? Please describe.**
I use Xournal++ to record lessons and want my students to see only the area I draw on. Right now I use OBS Studio to record the Xournal++ window and crop it so only the drawing area is visible.

**Describe the solution you'd like**
I propose an option to show a second window that only displays what is being drawn. Like that I could easily capture this new window and would not need to worry about cropping. Additionally this is probably useful if you do a live presentation using two screens.

**Describe alternatives you've considered**
Of course on could go for implementing a videorecord function using ffmpeg but this is probably a lot more involved and less flexible than just having a second window for presentation. Like that things like choosing the correct audioinput or adding effects can be handled by external programs like OBS Studio.

**Comment by LittleHuba** [comment] 2020-05-29 10:12
I agree with you on integrating our own recording feature being wide out of scope. There are some amazing apps out there that do a way better job than we would be able to realize.

We plan on making multiple views of a document possible in an upcoming version. As this will take quite some time though, a simple hack up of this feature might be interesting. As long as the view does not have to have editing capabilities it should be possible with reasonable effort. Some other dev than me has to take that up tough. I'm currently bogged down with writing that new version mentioned above.

**Comment by frohro** [comment] 2022-09-18 05:15
This is very similar to #4239.

**Comment by bhennion** [comment] 2022-12-25 11:27
Duplicate of #936

**Closed by bhennion** 2022-12-25 11:27 UTC
Labels: enhancement
