### ISSUE TITLE
pdf page backgrounds mixed up between different documents

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#1696] opened 2020-01-06 21:36 UTC
**Affects versions :**
Affects versions :

- OS: Ubuntu 19.10

- X11

- libgtk 3.24.12.1

- Version of Xournal++: 1.1.0+dev

**Describe the bug**
Changing between different Xournal++ documents with pdf background sometimes results in mixing of their pdf backgrounds. Hence when viewing one of the documents, some (of all) of the background pages come from the other (recently opened) document. I can annotate the mixed up pdf background and change page and it keeps being mixed up. It is quite annoying. Probably something with the pdf cache is flawed.

**To Reproduce**
1. Create two pdf's with 2 pages each
2. Open up the first pdf and save it as a Xournal++ file, opening up the second pdf and save it as Xournal++ file
3. Switch a couple of times between the documents.
4. Suddenly the pdf-backgrounds are mixed up. For instance the opened Xournal++ document shows first page background from the other Xournal++ file.

**Expected behavior**
I would expect that the background pdf shown is always the one that was annotated to begin with.

**Additional context**
When zooming in (or out) the mixed up background is always replaced with the correct one, it seems.

**Comment by Technius** [comment] 2020-01-07 00:10
This bug only seems to occur if zoom fit or presentation mode are enabled. Additionally, there's an issue with scrolling. I'm guessing the layout is not being recalculated?

Anyways, the zoom/scroll/layout system is in a dire need of a rewrite--there's just too many bugs and design issues in the current one.

**Comment by clemdc** [comment] 2020-05-24 11:53
Probably duplicate of  #1964

Could you try my PR #2009

**Comment by rolandlo** [comment] 2020-05-25 09:24
Seems this works as expected now. Thanks for the PR @clemdc .

**Closed** 2020-05-25 13:59 UTC
Labels: Zoom, bug, confirmed, papercut, priority: medium
