### ISSUE TITLE
Add fill to shapes

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#85] opened 2014-05-04 21:16 UTC
Creating filled objects would be pleasant. This has been in the works for a while but I don't see a direct path to it.

**Comment by MarPiRK** [comment] 2015-04-03 23:35
But this kind of approach leads to many nasty workarounds and possible bugs. Any bigger functional enhancement will lead to this kind of doubts and stops us from pushing forward.
After making some behind the scenes cleanup I'd like to write brand new file format.
Here are my thoughts about it:
- almost entirely binary to reduce file size
- support for different compression algorithms
- support continuous saving (not only to file, but maybe also to some kind of cloud stream)
- encryption
- background generator
What do you think about it?

**Comment by wbrenna** [comment] 2015-04-04 03:53
In my experience the reverse compatibility works fine. Since Xournal is still the leader in terms of compatibility and install numbers I think we have to work hard to maintain compatibility. If you can convince them to update to a new, incompatible format, then absolutely!

However, personally I have never found saves to be too large, so I haven't found a need for the first two points. And I'm not entirely sure I've come across continuous saving - do you have some piece software example in mind to emulate? 

Encryption would be nice though supporting it would not be without pain. Rolling our own would be foolish, I think, though something wrapping openssl might work well and I'd be open to testing out. For this I'd suggest an extension like .xoe. This wouldn't need to alter .xoj and wouldn't break compatibility.

Not really sure what a background generator is...

**Comment by MarPiRK** [comment] 2015-04-04 09:29
I'm using Xournal++ as my school notebook and I have to create separate file for each chapter. Files aren't this way too large – about 5 MB per chapter, but for convenience I'd prefer one file for each subject. For example maths notebook up to this day would weight 48 MB, which is little too big for my school's internet connection to sync with cloud.
About software with continuous saving, not really. It'd be some kind of autosave, which we have now, but much less CPU hungry. You see, I'm using Xournal++ on my ThinkPad X220t and I'd be very grateful for less CPU usage while saving to improve time on battery. When I use it on battery it changes to powersave mode, which means 1,7GHz on each core. It's not too bad, but if I want to save for example my maths notebook it needs some time to complete this process. While lesson I don't have many opportunities like this, but I'm afraid to loose my notes, by some unexpected crash. At the end of lesson I don't have time to save document, export to PDF and sync with cloud, with our crappy internet connection. There comes my idea – firstly we would support continuous saving to prevent from accidental loose of data and then maybe we'll find a way to continuously sync it with cloud.
Background generator would allow to create our own background patterns, for example it'd allow to change line density, margin, color of lines.

**Comment by Rmano** [comment] 2015-04-04 15:35
If I can chime in, I use both `xournalpp` and `xournal`. I think that both programs are (too much?) similar, and that is quite difficult to choose between them. Unfortunately, my skills in bot C and C++ are too old to be useful (a pity we don't have a py_xournal). The things that could really change the status of thing are, in my opinions, these: 

1. although I like the addition of "traditional" shapes, it's a pity that the circle/square/triangle recognition of `xournal` has been removed. Especially the circle detection worked nicely and was handy while correcting things; I use it all the time (and it's the primary reason I went back to `xournal` lately). 

2. Filled and semitransparent shapes will be really useful. I understand they would need a file format change; do it in a forward compatible way --- add XML elements so that `xournalpp` will *still* be able to read `xournal` files. If successful, when and if `xournal` will add them, they will probably using the same extension. Change the file extension --- no problem at all.

3. The other really missing thing is the paste selection behavior. It should be possible to resize maintaining the aspect ratio, as well as rotate the selection before pasting. 

4. A better usability of layers would be great. Like individual show-hide, and maybe an optional layer view that can be toggled with the page view on the right pane. 

5. About the format, I doubt that a binary format could be more compact than a gzipped XML; gzip is quite good in compacting things... 

6. Instead of a BG generator, I normally prepare my backgrounds with LaTeX/Tikz and then write on them, with "all page the same background". It's elegant and let you replace them, although with a bit of work (I have a python script to do it; will share if anyone is interested). 

7. A thing that's a bit strange: lool at these circles: 

![selection_050](https://cloud.githubusercontent.com/assets/6414907/6993273/b6690a16-daef-11e4-8f0b-c9b9ab8b43f4.png)

`xournal` rendering is really much more smooth.

**Comment by MarPiRK** [comment] 2015-04-04 19:43
I chose Xournal++ pretty much because of much quicker loading and saving.
3. I think that all kinds of transformations should be implemented, such as rotation, mirroring.
4. Yeah, I agree.
5. If I'd find some time, I'll try to hand convert some existing document to draft binary format to see difference in size.
6. I think, that embedding this feature directly to Xournal++ would be more convenient than using third-party scripts.

**Comment by andreasb242** [comment] 2015-05-03 18:45
>A thing that's a bit strange: look at these circles: 
>xournal rendering is really much more smooth.

The rendering Engine should display exactly the same result on both tool.
The Problem is, that both tools don't support circles (not so easy to implement for Xournal++ because I try to keep the backward compatibility).

I use now 4 times more stroke in the circle tool, now it looks much better.
But later we should save circles as circles, I already created a ticket #129

**Comment by Rmano** [comment] 2015-05-03 18:56
Thanks --- which is the branch where I can check all the new things? Is it master, or another one?

**Comment by andreasb242** [comment] 2015-05-03 19:12
>5. If I'd find some time, I'll try to hand convert some existing document to draft binary format to see >difference in size.

The initial size of a compressed binary file is may smaller, but the more data you have, the less will be the difference, so in my opinion a binary format is no choice.

Test it with this script:
```php
<?php

$bin = fopen('data.bin', 'wb');
$txt = fopen('data.txt', 'wb');

for ($i = 0; $i < 10000000; $i++) {
	fprintf($txt, '%d,', $i);
	fwrite($bin, pack('l', $i));
}

fclose($bin);
fclose($txt);

?>
```
Produce 2 files, the size of the files:
bin: 40.0MB
txt: 78.9MB

GZip Compressed:
bin: 13.8MB
txt: 21.1MB

About 50% more for the binary, but this does not contain images etc.


On random data (both the same random numbers!)
bin: 40.0MB
txt:104.8MB (depending on the ramdom numbers!)

GZip Compressed:
bin: 40.0MB (seems to be good random numbers :-))
txt: 49.8MB

About 25% more size of the text size.

So a realistic difference (with all overhead) will be 20%, so a file which is now 50MB may gets 40MB.

**Comment by andreasb242** [comment] 2015-05-03 19:15
>Thanks --- which is the branch where I can check all the new things? Is it master, or another one? 
I'm currently working on string_new.

I'll later merge all these changes to master, if you would like to try on your current branch you can replace in 
 src/control/tools/InputHandler.cpp 

the line
```cpp
int npts = (int) (diameter / 2.0);
```
through
```cpp
int npts = (int) (diameter * 2.0);
```

**Comment by MarPiRK** [comment] 2015-05-04 11:34
For me even 20% is better :) 
It's not that much necessary for now, but maybe some time I'll try to implement this, even for sake of training :)

**Comment by andreasb242** [comment] 2015-05-04 17:21
But may look for a container library, e.g. google saves the XML on android in a binary format, which can be converted from and to XML, even if this not the right solution for us, there are may similar libraries.

**Comment by andreasb242** [comment] 2018-12-24 23:13
Basically fixed by https://github.com/xournalpp/xournalpp/pull/597

**Closed by andreasb242** 2018-12-24 23:13 UTC
Labels: enhancement
