### ISSUE TITLE
problem Xournal ++

### ISSUE THREAD

**Issue by JuanDiego360** [xournalpp/xournalpp#5008] opened 2023-08-05 14:10 UTC
Date: Thu Jul 27 16:45:45 2023
Error: signal 11
[bt]: (0) /snap/xournalpp/69/usr/bin/xournalpp(+0x435b8a) [0x5594c88d3b8a]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7fbe5862a090]
[bt]: (2) /snap/xournalpp/69/usr/bin/xournalpp(_ZNK7Element7getTypeEv+0x10) [0x5594c8892a52]
[bt]: (3) /snap/xournalpp/69/usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x24) [0x5594c88c63d2]
[bt]: (4) /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x13a) [0x5594c88c667c]
[bt]: (5) /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0x16e) [0x5594c88c6eea]
[bt]: (6) /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x1fe) [0x5594c874e666]
[bt]: (7) /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x4d) [0x5594c874ea25]
[bt]: (8) /snap/xournalpp/69/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x5594c874d9f5]
[bt]: (9) /snap/xournalpp/69/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e8) [0x5594c8751f36]
[bt]: (10) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x8be31) [0x7fbe59d63e31]
[bt]: (11) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7fbe58c2b609]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fbe58706133]

Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/69/usr/bin/xournalpp(+0x4360fc) [0x5594c88d40fc]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7fbe5862a090]
??:0
[bt] #3 /snap/xournalpp/69/usr/bin/xournalpp(_ZNK7Element7getTypeEv+0x10) [0x5594c8892a52]
??:0
[bt] #4 /snap/xournalpp/69/usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x24) [0x5594c88c63d2]
??:0
[bt] #5 /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x13a) [0x5594c88c667c]
??:0
[bt] #6 /snap/xournalpp/69/usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0x16e) [0x5594c88c6eea]
??:0
[bt] #7 /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x1fe) [0x5594c874e666]
??:0
[bt] #8 /snap/xournalpp/69/usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x4d) [0x5594c874ea25]
??:0
[bt] #9 /snap/xournalpp/69/usr/bin/xournalpp(_ZN3Job7executeEv+0x27) [0x5594c874d9f5]
??:0
[bt] #10 /snap/xournalpp/69/usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x1e8) [0x5594c8751f36]
??:0
[bt] #11 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x8be31) [0x7fbe59d63e31]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7fbe58c2b609]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fbe58706133]
??:0

**Comment by rolandlo** [comment] 2023-08-05 14:13
This a duplicate of https://github.com/xournalpp/xournalpp/issues/4917, https://github.com/xournalpp/xournalpp/issues/4651, https://github.com/xournalpp/xournalpp/issues/4038, https://github.com/xournalpp/xournalpp/issues/2013. and https://github.com/xournalpp/xournalpp/issues/4979. So I'm closing it.

**Closed by rolandlo** 2023-08-05 14:13 UTC
