### ISSUE TITLE
Opening new file, old file overwrites some pages

### ISSUE THREAD

**Issue by CharlieL7** [xournalpp/xournalpp#1934] opened 2020-05-04 20:57 UTC
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: gtk3 1:3.24.20-1
 - Version of Xournal++: 1.0.18-1
 - Installation method: Arch Extra repo

**Describe the bug**
When opening a PDF file with a PDF file already open sometimes the newly opened file does not show up properly. Several of the pages are replaced with pages from the old file and the thumbnails are not updated. This occurs with some specific PDF files that I am unsure of what the difference is. This will additionally happen with any PDF file and much more often when having the opened PDF file in Okular. 

**To Reproduce**
1. open a multi-page PDF file in Okular
2. open the same multi-page PDF file in XournalPP
3. open another multi-page PDF file in XournalPP
4. observe that new file does not open properly
*** Can also occur when opening specific PDF files or switching between files quickly.

**Expected behavior**
New file is opened without any of the old file.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem. 

**Additional context**
Add any other information or context about the problem here.

**Comment by clemdc** [comment] 2020-05-23 19:20
Is it linked to #1964 ?

If so, could you try #2009

**Comment by Technius** [comment] 2020-05-24 00:25
Duplicate of #1964 (closing this one since it has less activity).

**Closed by Technius** 2020-05-24 00:25 UTC
Labels: bug, confirmed, papercut, priority: high
