### ISSUE TITLE
Xournal loses all saved settings sometimes

### ISSUE THREAD

**Issue by xinxinw1** [xournalpp/xournalpp#1074] opened 2019-04-16 01:49 UTC
Most of the times, when I close xournal, the settings I set (like pen color, eraser type and shape, stylus button settings) are saved and restored when I open it again. But seemingly randomly, sometimes when I open xournal again, my settings seem to be wiped and I see the default settings again. I'm not sure how to reproduce this, but it seems to happen every 8 opens and closes or so? It's really frustrating when I have to reapply all my settings every couple days :(

**Comment by JJones780** [comment] 2019-04-29 11:27
Had a quick look through... we're going to need some more hints.  Please run Xournalpp from the command line for the next while and let us know of any errors that are reported.
Which OS are you using?
Do you change locale on your machine.. ie between languages and/or numerical radix systems ( 100.00 vs 100,00 ) ?  Do you use multiple language keyboards?

**Comment by xinxinw1** [comment] 2019-05-04 04:20
Ok, I just switched to a new computer so let's see if it keeps happening, but details of my previous setup:
- OS: Arch Linux, Desktop environment: MATE
- Xournal version: 1.0.10
- Change locale: No, I always had locale set to en_US.UTF-8
- Language keyboards: Yes, I had a Chinese keyboard

**Comment by xinxinw1** [comment] 2019-05-04 04:24
Some good news, I was just able to reproduce this somewhat more frequently on my old computer:

It happens if I open around 3 xournalpp windows simultaneously, like if I open 3 terminals and run xournalpp on each one. Often two is also enough. I can tell the bug happened because I set my default pen color to black and on the new window it changes to blue.

Here is the command line output on each run (it is the same when the failure happens and when it doesn't happen):

```
$ xournalpp
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
** Message: 00:20:03.066: MemoryLeak: sum 0 objects.
```

**Comment by xinxinw1** [comment] 2019-05-04 04:32
I just confirmed that it still happens on my new computer (also Arch Linux, but with GNOME). In fact, it seems to happen every time I do these steps:

1. Open Terminal
2. $ xournalpp
3. Open 2nd Terminal (keep 1st xournal open)
4. $ xournalpp

The console message for both times is the same and is

```
$ xournalpp
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
** Message: 00:29:46.186: MemoryLeak: sum 0 objects.
```

**Comment by JJones780** [comment] 2019-05-05 09:33
Thanks for the update. I guess that rules out locales.

**Comment by LittleHuba** [comment] 2019-05-05 21:44
I think this is caused by the parallel access to the settings file. In some circumstances it may create an invalid file that can not be read by Xournal++ on startup and is therefore discarded. That would at least explain the somewhat randomness.

**Comment by JJones780** [comment] 2019-05-09 01:20
I had another look.
The pen settings don't get saved on their own and might not get saved until you exit Xournal++. So if you run Xournal++, change the pen color then open another Xournal++ without closing the first it will likely not use the new color.
Please try setting Preferences->view>HighlightCursorPosition to true and report back if the cursor is highlighted in the second running of Xournal++.

**Comment by xinxinw1** [comment] 2019-05-20 02:00
@JJones780 I tried setting HighlightCursorPosition and the cursor is not highlighted in the second running.

Here is my process:
1. Open xournalpp
2. Set highlight cursor position
3. Close xournalpp
4. Open xournalpp again (highlight is still set)
5. Open 2nd xournalpp (highlight is not set)

Maybe opening one xournalpp locks the settings file and the 2nd instance can't access it so it resets the settings?

**Comment by JoalpaLe** [comment] 2019-10-29 20:21
Can confirm this behaviour. 

I additionally noticed that restoring my settings.xml from a week-old backup did not restore my Xournal++ settings. Are there any other locations where settings are cached/saved?

**Closed** 2020-02-23 19:17 UTC
Labels: bug, confirmed, priority: high
