### ISSUE TITLE
Mouse Wheel zoom changes pages

### ISSUE THREAD

**Issue by seedship** [xournalpp/xournalpp#1587] opened 2019-11-03 22:34 UTC
**Affects versions :**
 - OS: Arch Linux
 - In case of linux, which desktop environment XFCE4
 - Which version of libgtk do you use. gtk-xfce-engine 2.10.1-2
 - Xournal++ 1.0.15

**Describe the bug**
When using a large PDF (100+ pages) and trying to zoom with ctrl + mousewheel, each mouse wheel step, in addition to changing the zoom, will also change the page in view forward or backward, depending on zooming in or out

**To Reproduce**
1. Open up a large PDF (100+ pages)
2. Go randomly in the middle
3. Look at the current page.
4. ctrl + mousewheel zoom
5. Look at the current page. It changed

**Expected behavior**
The page should stay the same, just the zoom should change

**Comment by LittleHuba** [comment] 2019-11-03 22:49
Duplicate of #1516

**Comment by seedship** [comment] 2020-02-16 16:20
I have tried enabling and disabling presentation mode as stated in #1516, but I still have this issue.

**Comment by seedship** [comment] 2020-02-16 16:36
I have just updated to version 1.0.17, and turned on and off presentation mode as the #1516  suggested.

However, the issue still persists

**Closed** 2020-04-06 18:08 UTC
Labels: bug
