### ISSUE TITLE
"Export as..." refuses to overwrite files

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#2369] opened 2020-11-03 15:31 UTC
**Affects versions :**
 - OS: Linux Ubuntu 20.04 Gnome Shell 3.36.4
 - Xournal++ 1.0.19 
└──libgtk: 3.24.20 
 - Installation method: built `.deb` form source and installed

**Describe the bug**
When trying to override a PDF file already existing with "Export as..." the save don't succeed (and enters in a loop...)

**To Reproduce**
1. Draw something
2. "Export as..:", choose "PDF without background", new name like `exp1.pdf`
3. Draw something more
4. "Export as..." --- when the chooser pops out, click on the existing file, choose "PDF without background"
5. (Correctly) a pop up ask if you want to replace. Say "Yes"
6. Nothing happens... the "export as" dialog stays put, the file is not overwritten

**Expected behavior**
The file should be overwritten and the "export as..." dialog should disappear

**Screenshots of Problem**
![test](https://user-images.githubusercontent.com/6414907/98005834-c9820f80-1df1-11eb-859b-de84c67d39f1.gif)

**Additional context**
Once it locked --- there was no way to exit the dialog; but I can't reproduce the lock.

**Comment by rolandlo** [comment] 2020-11-03 16:33
This is a duplicate of #2355

**Closed by rolandlo** 2020-11-03 16:33 UTC
Labels: bug
