### ISSUE TITLE
Scrolls to black

### ISSUE THREAD

**Issue by andrewaclear** [xournalpp/xournalpp#2632] opened 2021-01-08 06:08 UTC
I am running Manjaro Gnome using Wayland on an AcerSpin1 and when I scroll the rest of the document is not visible.

![image](https://user-images.githubusercontent.com/51063733/103980517-06e67e80-514e-11eb-935a-fa2e98cf80f4.png)

**Comment by rolandlo** [comment] 2021-01-08 06:18
Duplicate of #2631. I assume you use the latest 1.1.0+dev version.

**Closed** 2021-01-08 06:29 UTC

**Comment by andrewaclear** [comment] 2021-01-08 22:57
I was using the latest 1.1.0+dev as it has many features I very much like, and oh sorry didn't realize the issue was already posted.
