### ISSUE TITLE
Page numbering

### ISSUE THREAD

**Issue by pmaen** [xournalpp/xournalpp#2274] opened 2020-09-24 13:37 UTC
Hi, 
I use xournalpp with pdf export a lot and it would be helpful to have a way to add the page number to the pages (multiple options for like p. 3,4,5 or Page 3/5, 4/5, 5/5 would be ideal). That way you don't need to rely on the page numbering of the printing service every time.

**Comment by rolandlo** [comment] 2020-09-24 16:39
I don't quite get what you mean. 
1) Should the page numbers be added to the xopp-file or just to the exported pdf? 
2) Do you realize that page numbers (selected page and total page number) is displayed in the toolbar. For instance if you use the Xournal++ toolbar it is displayed on the bottom left: 
![grafik](https://user-images.githubusercontent.com/40485433/94173863-cc095500-fe94-11ea-9ec8-01e2b997528f.png)
Also if you export to pdf and view the exported pdf in a pdf-viewer you will see page numbers in a similar way.

**Comment by pmaen** [comment] 2020-09-24 17:37
I don't know enough about the programming to say if the page number should be only in the pdf or the xopp-file.
The point is to have page numbers on printed notes taken in Xournal++ to be able to discuss the content with people who prefer the digital version as well as those who prefer a piece of paper

**Comment by rolandlo** [comment] 2020-09-24 18:01
Ok, now I get it. After you print, there are no page numbers to see. Maybe it could be made optional to add page numbers both when printing and when exporting to pdf. Saving them in the xopp-file would not be a good idea, since it could get tricky to update page numbers after you modify the document.

**Comment by Technius** [comment] 2020-09-24 21:08
Duplicate of #1053.

**Closed by Technius** 2020-09-24 21:08 UTC
Labels: enhancement
