### ISSUE TITLE
Code style issue (and possible refactoring) (slightly easier pick than #349): Change name of "GROUP_RULER" in ToolMenuHandler.cpp

### ISSUE THREAD

**Issue by siliconninja** [xournalpp/xournalpp#350] opened 2018-11-21 21:37 UTC
When looking into my other issues (#343 and #349), I also found something surprising in the code in ToolMenuHandler.cpp:

https://github.com/xournalpp/xournalpp/blob/1253046df36b8f80cf966b8161e2781461790d18/src/gui/toolbarMenubar/ToolMenuHandler.cpp#L431-L436

Why are they grouped under this name: GROUP_RULER when they could be given a better name like GROUP_TOOL_DRAW_COMBO_CONTROL that says which GUI component (the "tool draw combo control" box) these buttons are a part of, or something shorter like GROUP_SHAPE_TOOLS (because this drop-down menu handles drawing shapes)?

Other code files might need to be changed. Search for GROUP_RULER or fix issues when compiling.

That would make it less confusing for me and easier to debug if there are issues. This entire drop-down menu shouldn't be called a "ruler menu" either, in issue https://github.com/xournalpp/xournalpp/issues/343#issuecomment-440803325 (Ctrl+F, search for Meanings of the 2 different tool names - github won't let me link to markdown headers in issues), I mentioned the code just referred to the "draw line" tool as a "ruler". This specific name in the code for the entire group confuses me because it seems like all drawing shape tools are ruler tools, which they are not.

Sorry if I'm being unclear at all. Just pointing this out to anyone who wants to contribute to the code. Let me know if you have questions.

**Comment by andreasb242** [comment] 2018-11-21 22:29
It's clear, no Problem.

In this case I can explain you, why the Group is called GROUP_RULER. It's really simple, first, there was only a ruler on/off button, but for all toggle button there is a group.
Somebody added the other shapes, and made a menu button out of the ruler button.

In my opinion, this is maybe a bad naming, but not a Bug.
As written in the other Ticket, if you have time to fix something, feel free to do it.

You are the first native english speaking person I sure now, as you may saw on the translation files, there are developers all over the world.

Probably there are a lot more spelling and naming errors in the code.
But for me, this are no Bugs, so I'll close this Ticket.

As you may mentioned, I closed really a lot ticket in the last 3 weeks, I let only tickes open which are really improvements or which are bugs (crashes, wrong functionality etc.) because it's much harder to track if there are to much ticket open, e.g. I closed also the ticket create a new Icon set.

As mentioned before - the discussion can be ongoing, and the ticket can be reopened any time if needed.

**Closed by andreasb242** 2018-11-21 22:29 UTC
