### ISSUE TITLE
Adding new page moves view unexpectedly

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#1517] opened 2019-10-04 18:13 UTC
**Affects versions :**
- OS: Linux, Ubuntu 18.04, X11
- Version of Xournal++ master

**Describe the bug**
On a multiple page document, when adding a page somewhere in the middle of the document, occasionally the view jumps unexpectedly. The view sometimes remains unchanged, sometimes jumps to the new page, and sometimes jumps to some other odd place in the document. This doesn't seem to happen when adding pages to the end of the document, though.

**To Reproduce**
1. Create new document. Add 2 pages, and scribble something on them so you know where you are (e.g. "1" on page 1, through to page 3) 
2. Go to page 2, scribble something. Add a new page.
3. Where is the view now? For me, it was on the blank new page.
4. Scribble again, add new page. 
5. Where is view now? For me, it was on page 1 (top of document).

**Expected behavior**
Ideally, adding a new page doesn't change the view point at all.

**Comment by gyps** [comment] 2019-10-06 13:06
I have the same problem. 
OS: Debian testing  5.2.17-1 (2019-09-26) x86_64 GNU/Linux
Xournal++ master (as of today).

I use slides generated with latex-beamer (option aspectratio=169) to insert pages of the same size I set the page-size-template to custom 16cmx9cm. When I insert a new page the view jumps more or less nondeterministically to some page (often the first page).

Focus though is on the new page (which I find ideal also for the view). Going one page back and forth shows the newly created page.

**Comment by markwmuller** [comment] 2019-10-06 16:45
@gyps : note, you don't need to make the page size template manually, there's a way for it to copy the last page's size. I think it's under Journal>Configure page template. (Not sure, because reading it now suggests that that only applies to first page, but I know that it's possible because I get the right page size when editing slides, or regular sized documents)

**Comment by Febbe** [comment] 2019-10-06 16:49
If no one fixes this I'll do it when I have time.

**Comment by gyps** [comment] 2019-10-07 05:47
> @gyps : note, you don't need to make the page size template manually, there's a way for it to copy the last page's size. I think it's under Journal>Configure page template.

You're right. I checked the wrong one and that's why the page background was copied as well. Now I checked "copy last page size" and size is find. The nodeterministic move of the view is still present however.

**Comment by jonasBoss** [comment] 2019-11-25 21:12
I can confirm this issue, however I experience always the same behavior: The view jumps to the very first page in the document. My OS is Arch with (AUR) xournalpp-git 1.0.15.r79.gc533ab9b-1

**Comment by LittleHuba** [comment] 2019-11-25 22:57
I do not know who the maintainer of the aur package is but this seems to be very wrong. Switch to the nightlies for bleeding edge.

Yeah if everything would work correctly the new page would be added after the currently active page and the view would show the newly added page. For some reason this behaviour got broken. As soon as I got time I'll work on this (if @Febbe isn't faster).

**Comment by gyps** [comment] 2019-11-26 06:41
That's strange. Every time I try to reproduce this error it gets less and less reproducible. I always work with the current git version. 
With today's version only one time out of about 20 insertions the view ended up on the wrong page (and it was some arbitrary page not the first one). Anyway, if this happens (since focus is on the correct page) going back and forward one page always results in the correct view. If I knew were to start, I would try to fix it.

**Comment by LittleHuba** [comment] 2019-11-26 09:26
That is actually a perfect description of a race condition. I assume it results from the page being added and then the try to jump to the correct position while the view still updates it's dimensions.

**Comment by rolandlo** [comment] 2020-11-13 22:11
This has been fixed with PR #2346

**Closed by rolandlo** 2020-11-13 22:11 UTC
Labels: bug, confirmed, difficulty:easy, hacktoberfest, priority: low
