### ISSUE TITLE
Mouse buttons in xournal++ don't work after pressing a pen button

### ISSUE THREAD

**Issue by GuentherE** [xournalpp/xournalpp#2628] opened 2021-01-07 14:27 UTC
Affected versions: 1.0.20 and 1.1.0-nightly-20210106
OS: Windows 10

Hi,

Thanks for this great software. I like it very much. I use it under Ubuntu 18.04 with no problems with my XP-Pen Artist 12 Pro tablet. 

Now I have a problem as a customer project forces me to use Windows 10. Installation was flawless and using the tablet with my pen and my mouse works also. But after I have pressed one of the pen buttons my mouse stops working: I can use it in other programs but in xournal++ pressing the mouse buttons has no effect. After restarting xournal++ the mouse is working again.

As a workaround I have tried to disable the pen buttons and use the shortcut buttons on the tablet for switching between eraser and highlighter, but this is also not working. It seems that the signal of the pen buttons is influenicing the mouse behaviour even there is no action assigned.

Using the same szenario with e.g. MS whiteboard works.

Is this a configuration problem or a bug?

TIA,
Guenther

**Comment by personalizedrefrigerator** [comment] 2021-01-07 14:35
Thank you for reporting this! When broken, does the mouse open/close the dropdown menus at the top of the screen? Are you using the new input system?

**Comment by GuentherE** [comment] 2021-01-07 14:40
I can open/close the dropdown menus of other programs but can do nothing in xournal++. Even closing the app is not possible.

**Comment by personalizedrefrigerator** [comment] 2021-01-07 14:49
Try running Xournal++ from `cmd.exe` or similar. Some warnings/messages should be logged in its output.

**Comment by GuentherE** [comment] 2021-01-07 14:59
Unfortunately no messages when started from command line. Same behaviour.

The mouse cursor vanishes when entering xournal++ and is a small dot when in the title bar area. Outside xournal++ it shows the normal cursor.

**Comment by personalizedrefrigerator** [comment] 2021-01-07 15:03
@rolandlo Could you look at this? I don't have access to a windows machine with pen input. Thank you!

**Comment by personalizedrefrigerator** [comment] 2021-01-07 15:06
@GuentherE Can you post the version of libgtk Xournal++ is using (see Help > About).

**Comment by GuentherE** [comment] 2021-01-07 15:11
Version 1.0.20 with libgtk 3.24.23

**Comment by GuentherE** [comment] 2021-01-07 16:21
I've tested it with 1.0.18 and 1.0.12: same effect.

**Comment by rolandlo** [comment] 2021-01-07 16:25
Some comments: 
- Under Windows there are only warnings/messages when building from source (as described in the [wiki](https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md)).
-I can reproduce the problem. All it takes is pressing the stylus button 1 once and then the mouse and stylus will just act like the stylus button 1 was still pressed. Depending on what tool you have assigned to the stylus this means you draw with the highlighter or you use the hand tool (and can't draw anymore) or whatever.
- The stylus button 2 works normally.

**Comment by rolandlo** [comment] 2021-01-07 17:15
I have also observed the same effect on 1.0.18. It could also be related to a bugged Windows update. How could it be that nobody has noticed it otherwise, if it were not quite recent?

**Comment by kubajaburek** [comment] 2021-01-16 17:57
Hey, I’m experiencing the same issue as @rolandlo described – I configured button 1 on my Surface Pen to trigger the selection tool, and after I press it and select something, the selection tool stays active and I can’t switch back to the pen tool, it keeps reverting to the selection tool. I have to restart Xournal++ to switch back to the pen tool.

However, for me, this issue only exists when I enable the new input system, it works correctly with the old one. I have been having this issue ever since I started using Xournal++ (version 1.0.18 I think), if I remember correctly.

**Comment by maehne** [comment] 2021-02-04 21:32
I am observing the same bug with a Wacom Cintiq Pro 13 tablet using Xournal++ 1.0.20 on Windows 10.

**Comment by rafisics** [comment] 2021-02-11 03:41
- OS: Windows 10 Pro
- Version of Xournalpp: [1.1.0.dev-nightly.20210211-windows](https://github.com/xournalpp/xournalpp/releases/tag/nightly)
- Tablet: [XP Pen Star G640S](https://www.xp-pen.com/product/54.html)

I am having the same problem as @GuentherE mentioned. Once I start writing/erasing with the pen for some moments, the mouse clicks stop working inside Xournalpp. And after some more time, the `Minimize`, `Restore` and `Close` buttons stop working. At that moment, I have to go to `File > Quit` to close it. Everything behaves normally when I reopen it. And the problem returns after using the pen again. How can solve this issue?

**Comment by Keraldi** [comment] 2021-03-04 17:40
I'm experiencing it as well:

XournalPP: 1.0.20 (09ec4999) with libgtk 3.24.23
Windows 10 Pro 20H2 (19042.746)
Tablet: Wacom Intuos

Mouse works for window decorator until one tries to click inside the application. This function can be restored by clicking on the window decorator with the stylus. It happens with both the experimental and default input settings.

**Comment by rolandlo** [comment] 2021-03-09 22:55
In my case using different stylus settings I got the stylus buttons work again, see [this issue](https://github.com/xournalpp/xournalpp/issues/2894#issuecomment-794556611) (just without pressure sensitivity)

**Comment by rolandlo** [comment] 2021-07-03 17:33
The patched GTK+ 3 has now been merged. You can copy the `libgdk-3-0.dll` and `libgtk-3-0.dll` into your [Xournal++ 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly) installation as described [here](https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-873435907). This may solve the issue.

**Comment by rolandlo** [comment] 2021-07-22 19:49
The issue should be fixed in [Version 1.1.0-hotfix+1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). Please report if you experience otherwise.

**Closed by rolandlo** 2021-07-22 19:49 UTC
Labels: confirmed, os::windows, priority::high
