### ISSUE TITLE
Annotating with more space in PDFs

### ISSUE THREAD

**Issue by blobotic** [xournalpp/xournalpp#4587] opened 2023-01-15 07:20 UTC
**Is your feature request related to a problem? Please describe.**
I mainly use xournal++ with pdfs, usually math/physics textbooks. When doing problems, most textbooks don't actually give any space, so I end up adding a new page after to work in, but it gets messy fast when I have to scroll up and down past my work. 

**Describe the solution you'd like**
In short, the ability to select a region, then for a separate popup/window to open with the selected region visible at the top and space to write/annotate on indefinite pages below. I've been looking into e-ink readers recently, and something like "digest" in the Supernote would be amazing to have. When exporting as a PDF, we could handle it similarly: in order of vertical position, have each highlighted region followed by the subsequent annotations. A dividing line or a new page would separate each one. 

**Describe alternatives you've considered**
An alternative that would work for my use case would be hyperlinks to different places in a single pdf (so I could skip scrolling, and I could imagine an implementation that uses hyperlinks for my proposed solution, except with the addition of a new window opening), or the ability to add vertical space (which would, I imagine, be an extension of implementing infinite vertical scrolling; I'm aware of the existing vertical space tool, but to the best of my knowledge it doesn't affect the PDF itself, right?).

**Additional context**

**Comment by bhennion** [comment] 2023-01-15 11:45
Duplicate of #1698. Closing

**Closed by bhennion** 2023-01-15 11:45 UTC
Labels: enhancement
