### ISSUE TITLE
Strokes create flashing

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1107] opened 2019-04-30 13:20 UTC
![StrokeBug](https://user-images.githubusercontent.com/19779511/56964435-7e7fa000-6b5b-11e9-8303-fc1d5e6daade.gif)

Did not find steps to reproduce yet. It occured in a PDF, where I inserted a new page via Journal -> New page after and then chose "Checked background". The background that flashes up says "loading...". Maybe that helps to narrow down the origin.

**Comment by faaaaabi** [comment] 2019-07-06 10:04
Can confirm that for a files with many pages (> 20 pages). No flashing in files with small amount of pages

**Comment by LittleHuba** [comment] 2019-07-06 11:44
@coldspark29 @faaaaabi could one of you share a file with the bug?

**Comment by faaaaabi** [comment] 2019-07-09 14:05
Here is my file: https://drive.google.com/file/d/1spPZuDnXh_NAKbzLGwPDpe2RJeTbSAA2/view?usp=sharing

**Comment by lehmanju** [comment] 2019-07-23 18:55
Might be related to #1213 #1139 #1132. This seems to be an issue with the underlying repaint system.

**Comment by LittleHuba** [comment] 2019-09-10 19:09
Please see #1405 for a description why this is happening and the proposed solution. Since the bug is the same, those two tickets are duplicates. As the solution is posted in #1405 I'll close this ticket and keep track of this bug in the other ticket.

**Closed by LittleHuba** 2019-09-10 19:09 UTC
Labels: bug, rendering

**Comment by JJones780** [comment] 2019-09-11 11:05
The description seems to match #1405 but the gif looks unique... ?
The gif seems to be edit-centric.

**Comment by LittleHuba** [comment] 2019-09-11 22:05
It is the same root cause. For some reason the cache is invalidated and therefore the loading page is shown. We might have to investigate why the cache was invalidated though. It might have happended without a good reason. But this is lower priority than fixing the painting algorithm.
