### ISSUE TITLE
After going outside the page, and coming back, pen draws randomly

### ISSUE THREAD

**Issue by rinakra** [xournalpp/xournalpp#3286] opened 2021-07-29 18:26 UTC
https://user-images.githubusercontent.com/49998102/127545904-88160f28-1e16-45e9-a668-c2b961582b64.mp4

**Affects versions :**
 - OS: Linux
 - Desktop environment: X11, i3wm 
 -libgtk: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: Pacman (Arch linux repository? )

**Describe the bug**
Xournalpp is drawing when my pen is not touching my Wacom tablet. (Wacom Cintiq 16)

**To Reproduce**
It's a little random
1. Start drawing
2. Go outside the page like to click a tool. Come back to the page,
3. After a while repeating steps 1 and 2 it happens. (see video)

**Expected behavior**
It should not draw unless the pen is touching the tablet. 

**Additional context**
This has been happening for a while on different operating systems. I decided to report it now because it was not fixed in the most recent update.

**Comment by rolandlo** [comment] 2021-07-29 19:57
This is a duplicate of #2762 and #3274. You are right that the bug wasn't fixed yet. We  had a fix #2749, but had to revert it in #2835, since the fix introduced another bug.

**Comment by zwergnase1970** [comment] 2021-08-25 07:12
I have the same problem in Windows 10. Is there already a solution or a workaround?

**Comment by phantamanta44** [comment] 2021-11-03 04:35
experiencing the same issue. maybe of note: when my tablet is in "hover click" mode, as below:

![image](https://user-images.githubusercontent.com/5924141/140010236-9061cd67-d5c3-4f99-ad53-64c20b40f036.png)

...xournal++ still behaves as if it were in click-and-tap mode (unlike the rest of my system), but it no longer exhibits this issue. this is inconvenient, because while i prefer to use click-and-tap mode, it makes xournal++ all but unusable, and so i end up having to change this option every time i switch applications.

**Comment by bhennion** [comment] 2021-12-17 10:33
A fix has been proposed in #3658. It'd be helpful if affected people could try out the fix and report in #3658.
Installers with the fix are available in [this post](https://github.com/xournalpp/xournalpp/pull/3658#issuecomment-996576296).

**Closed** 2022-07-12 20:30 UTC
Labels: bug
