### ISSUE TITLE
Opening a LaTeX annotation, then closing the edit box before the LaTeX renders crashes the program.

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2481] opened 2020-12-03 19:38 UTC
I'm on Windows with version 1.1.0. If I go to a PDF with some LaTeX annotations, click on one and open the box to Edit it, but before the LaTeX fully renders, close the edit box, the program crashes.

**Comment by rolandlo** [comment] 2020-12-03 20:10
Duplicate of #2332

**Closed by rolandlo** 2020-12-03 20:10 UTC
Labels: bug
