### ISSUE TITLE
Crash when using middle mouse button and drag out of window

### ISSUE THREAD

**Issue by JJones780** [xournalpp/xournalpp#1007] opened 2019-03-22 22:03 UTC
When:
  Using the middle mouse button as hand tool ( but not when selecting the hand tool and using left mouse button ).
  Drag the mouse out of the window. Crash

** (xournalpp:25537): WARNING **: XojTypeCheck failed: NULL xournalpp/src/gui/inputdevices/NewGtkInputDevice.cpp:64
*** Program received signal SIGSEGV (Segmentation fault) ***

Tested on Linux Mint.

**Comment by theKlanc** [comment] 2019-03-29 23:15
Also happening to me when using a stylus button, I'll try to fix it.

**Comment by gad-o** [comment] 2019-04-05 11:31
I had to activate "gtk workaround" for using my graphic tablet. 
When relase hand tool(both of mouse and tablet) crash with this backtrace

[scrollreleasecrash.log](https://github.com/xournalpp/xournalpp/files/3047657/scrollreleasecrash.log)

**Comment by Epse** [comment] 2019-04-22 15:29
I get this same issue when mapping hand tool to a pen button. As soon as my cursor leaves the drawing area (e.g. onto the buttons up top, which happens often) the entire app crashes.

**Comment by LittleHuba** [comment] 2019-05-07 23:48
Could you test this with the new input system #1070? I'm unable to reproduce it on my platform with the old system. Hence I'm unsure whether this persists.

**Comment by JJones780** [comment] 2019-05-08 09:40
When I enable the new input system the middle mouse button no longer turns into a hand tool so I can't test for the crash.
If I go back to the old input system I can mmb the hand and get the crash.

**Comment by gad-o** [comment] 2019-05-09 00:11
> Could you test this with the new input system #1070? I'm unable to reproduce it on my platform with the old system. Hence I'm unsure whether this persists.

If i only check _cbNewInputSystem_, i can't get the hand tool.

After also checking _cbNewInputSystemTPCButton_ my problem fixed. I'm not getting the crash with hand tool when go outside of drawing area.

**Comment by gad-o** [comment] 2019-05-09 13:24
> Now drawing should work with secondary mouse buttons. Please try again only using _cbNewInputSystem_.

Tried with 928b7a6 But without cvNewInputSystemTPCButton checked, secondary mouse buttons not working

**Comment by LittleHuba** [comment] 2019-05-09 22:31
@gad-o this should be fixed now.

**Comment by JJones780** [comment] 2019-05-10 09:24
I can now get the hand tool on middle mouse button and no longer get the crash. 
Good job!

**Closed** 2019-05-10 13:27 UTC
