### ISSUE TITLE
latest master build failing on linux due to package 'gtk-mac-integration' missing

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#1554] opened 2019-10-18 18:11 UTC
latest master builds are failing on linux due to error:

> Call Stack (most recent call first):
>   CMakeLists.txt:64 (find_package)
> 
> 
> -- Checking for module 'gtk-mac-integration'
> --   No package 'gtk-mac-integration' found

... perhaps gtk-mac-integration should not be required on linux?  (i'm on ubuntu 18.04)

**Comment by andreasb242** [comment] 2019-10-18 18:13
This is probably not the reason for the failure.
Optional dependencies are always checked, on every operating system.

**Comment by petergthatsme** [comment] 2019-10-18 18:17
fair enough.. below is the full error i end up with. Maybe my target 'cxx17' is not what it should be? 

> cd ./build
> make
> CMake Error at cmake/find/FindCXX17.cmake:72 (target_compile_features):
>   Cannot specify compile features for imported target "cxx17".
> Call Stack (most recent call first):
>   CMakeLists.txt:64 (find_package)
> 
> 
> -- Checking for module 'gtk-mac-integration'
> --   No package 'gtk-mac-integration' found
> Enable Xournal++ Plugins
> Installing desktop files
> 
> Configuration:
>         Compiler:                   /usr/bin/c++
>         CppUnit enabled:            OFF
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pgroszko/xournalpp/build/CMakeFiles/CMakeOutput.log".
> See also "/home/pgroszko/xournalpp/build/CMakeFiles/CMakeError.log".
>

**Comment by Technius** [comment] 2019-10-18 19:38
Duplicate of #1553; see the issue for a temporary fix (which is to upgrade to CMake 3.15).

**Closed by Technius** 2019-10-18 19:38 UTC
Labels: bug
