### ISSUE TITLE
Zooming via pinch to zoom causes graphical glitches

### ISSUE THREAD

**Issue by taaem** [xournalpp/xournalpp#404] opened 2018-11-28 16:09 UTC
When zooming via mulittouch pinch to zoom gestures, the page "glitches" it zooms correctly but it also shows the fullscreen view every few moments, which makes zooming really hard.
Also zooming in general causes the view to scroll quite often so even if I'm using the handle in the menu I end up on the last page even if I started in the middle or somewhere.

**Comment by andreasb242** [comment] 2018-11-28 17:08
Link to #402 and #403

All bugs are not reproducible on my system (Ubuntu 16.04)

**Comment by morrolinux** [comment] 2018-11-28 17:34
I also have the de-centered scrolling issue when zooming via handler buttons. I think it might be somehow fixable by relative-scrolling the page while zooming in/out, to keep it centered. However, last time I tried to do so, the obtained behaviour was irregular and not desired. maybe I did not take into account all the zoom and scale variables.
I could be doing some testing this weekend if I have enough time.

**Comment by cass00** [comment] 2018-11-29 14:13
Centered pinch to zoom works quite alright for me. Here is the commit from a while ago from my xournalpp fork cass00/xournalpp@29f43991 . Not actually sure by what way it made it into the main repo. So there is certainly room for improvement.

**Comment by andreasb242** [comment] 2018-11-29 17:21
@cass00 This is merged. For me this is working if I use the touch and two fingers. (on Ubuntu 16.04)

**Comment by markwmuller** [comment] 2018-12-01 23:34
I'm not sure this is the original issue, but my pinch to zoom is also somewhat broken. Video here: 
https://imgur.com/a/d3uxU5p

Using Ubuntu 18.04, Wayland, on Thinkpad x1 yoga. (No pinch to zoom using X, I'm assuming that's expected).

**Comment by andreasb242** [comment] 2018-12-02 06:51
@markwmuller
No, it is working for me on Ubuntu 16.04 on a Lenovo Helix with X11. So this is also an issue. We had already an issue with Wayland. Chan you check if Zoom is working e.g. in Evince or EOG or so?

ps. Offtopic, I know: I installed Ubuntu 18.04 first on my Helix. But if I have the Wacom Tablet active (pen removed) Ubuntu crashes on the Login screen. Did you also have Problems, or was it working out of the Box?

**Comment by markwmuller** [comment] 2018-12-02 18:32
No pinch-to-zoom in EOG or evince, either, using X. 

18.04 worked well for me, without issues as far as wacom/touch goes.

**Comment by taaem** [comment] 2018-12-02 18:58
My zooming looks exactly like in the video, but I have pinch to zoom in evince on wayland working fine.

**Comment by andreasb242** [comment] 2018-12-02 19:14
I can not reproduce it on my system, it is correct working. And I have currently no other Touch enabled device for Testing.

The method XournalView::zoom_gesture_scale_changed_cb is called when the zoom changes.

Please add the line:
>	printf("zoom: %lf\n", scale);
And then we interpret the output.

**Comment by markwmuller** [comment] 2018-12-02 23:16
@andreasb242 Where do I add the line of code? 

FWIW, I have it working in x too, now. For me, the fix was to use `libinput` driver, rather than `wacom`, from here ( https://bugs.launchpad.net/ubuntu/+source/xf86-input-wacom/+bug/1774242 ). Now zoom works well in evince, and in Xournal++

**Comment by andreasb242** [comment] 2018-12-03 06:16
At the beginning of XournalView::zoom_gesture_scale_changed_cb

**Comment by taaem** [comment] 2018-12-03 07:06
Here is a log with that line added. I think it is related to PDFs in some way, because if I just open Xournal in a new window without having changed anything pinch-to-zoom works fine, but if I open a PDF like shown in the log something messes up.
[log.txt](https://github.com/xournalpp/xournalpp/files/2638391/log.txt)

**Comment by andreasb242** [comment] 2018-12-03 16:11
Ok, thank you, I'll try with a PDF, if can reproduce it. I can see the really big changes in Zoom, so already the Gesture sends really big differences, which causes the big size changes, e.g.

zoom: 1,501744
zoom: 654,690938

This is really a big jump.

**Comment by markwmuller** [comment] 2018-12-03 16:22
For me, it happens without opening a PDF (on wayland). Log below:

[jitters.txt](https://github.com/xournalpp/xournalpp/files/2640260/jitters.txt)

**Comment by andreasb242** [comment] 2018-12-06 18:14
@taaem 
For sure, you find my Email address in the Git History, I'll check if it also happens for me.
But I cannot promise you a fix time or so, there is really much going on at the Moment, as you see, and I don't have that much time ;-)

**Comment by andreasb242** [comment] 2018-12-16 11:17
Xournal++ probably cannot fix this issue, I looked at an example PDF, which is big and loads slow, but except of this was nothing special.

Should we smooth the values mathematically? Add an option to enable this, and hope this makes it better, even this would not be a real solution, it should probably fix the issue.

What do you think
@taaem  @markwmuller ?

**Comment by andreasb242** [comment] 2018-12-16 12:35
>Did you test it with the pdf on wayland?
No, I have currently only one Notebook with running wayland, and it has no Touchscreen.
I won't test this today for sure.

If you whish to help:
please install gtk-3-example and search for an example with Zoom gesture, if you find one, check if it's working.
If it's working we can take this as example for Xournal++.

**Comment by taaem** [comment] 2018-12-17 17:04
I just checked and it works perfectly smooth in gtk3-demo

**Comment by andreasb242** [comment] 2018-12-17 17:14
Ok, so we should compare it with our. And find the difference ;-)

**Comment by taaem** [comment] 2018-12-17 18:06
Just found something out, the zooming bug only happens if the pdf was already scrolled past the first page. So on the first page zoom works fine but once on page 2 or higher it is broken.

**Comment by andreasb242** [comment] 2018-12-17 19:02
I expected something like this, I currently expect that some coordinates are relative to the page instead of absolute of the screen or something like this.

**Comment by taaem** [comment] 2018-12-17 19:20
Don't know if that's related but in presentation mode I can only zoom in and not out. But the bug doesn't happen.

**Comment by peetCreative** [comment] 2018-12-18 22:32
That's similar to the ctrl + scroll zoom problem   in `ZoomControl.cpp`
 `event->direction` is GDK_SCROLL_SMOOTH so it goes to zoom out directly.
I'm working on it

**Comment by peetCreative** [comment] 2018-12-19 16:47
@WPettersson Can someone explain what is happening in XournalView.cpp::getZoom()
```	size_t p = getCurrentPage();
	if (p != size_t_npos && p < viewPagesLen)
	{
		XojPageView* page = viewPages[p];
		if (this->getControl()->getSettings()->isPresentationMode())
		{
			double heightZoom = this->getDisplayHeight() / page->getHeight();
			double widthZoom = this->getDisplayWidth() / page->getWidth();
			return (heightZoom < widthZoom) ? heightZoom : widthZoom;
		}
	}
``` 
This looks weird for me...

**Comment by andreasb242** [comment] 2018-12-19 17:44
This looks like fit the page to the screen size?

**Comment by WPettersson** [comment] 2018-12-19 22:01
> @WPettersson Can someone explain what is happening in XournalView.cpp::getZoom()
> 

Yup, in presentation mode it sets the zoom value to fit the page to the screen size.

**Comment by andreasb242** [comment] 2018-12-22 10:43
https://github.com/xournalpp/xournalpp/pull/565/files
I'm not sure, but I referenced the gesture now to the parent, and I calculate the coordinates now relative to the window.

Please retest. Reopen if still present.

**Comment by taaem** [comment] 2018-12-22 12:12
Just tested it and sadly it still happens but now also, without any PDF loaded with a blank page.
Don't know if thats related but I get
```
 (xournalpp:8171): Gdk-CRITICAL **: 13:10:25.950: gdk_device_get_state: assertion 'gdk_device_get_device_type (device) != GDK_DEVICE_TYPE_SLAVE || gdk_display_device_is_grabbed (gdk_device_get_display (device), device)' failed

** (xournalpp:8171): WARNING **: 13:10:25.950: Input was not stopped correctly!
```
in the logs

**Comment by andreasb242** [comment] 2018-12-22 12:33
Yes I know this warning, sometimes I don't get the end event, it's random. I get the event that input start, but not when the pen is released, and If i then query the pen, to check if it's still there, GTK warns because the pen is gone. But this works.

If you zoom with CTRL+Scrollwheel its working now, or is this also not working?
This is now the same handling, just would make sure, that we have still the same Problem, and not a new one ;-)

**Comment by taaem** [comment] 2018-12-22 12:35
Ctrl + Scroll wheel is working perfectly!

**Comment by andreasb242** [comment] 2018-12-22 12:56
So we need to understand what's the problem with GTK Gesture. Have a look at "gtkgesturezoom.c".
https://github.com/GNOME/gtk/blob/master/gtk/gtkgesturezoom.c

In my opinion you should try to get the points:
>      gtk_gesture_get_point (gesture, sequences->data, &x1, &y1);
>      gtk_gesture_get_point (gesture, sequences->next->data, &x2, &y2);

and print out x1, y1, x2 and y2, and check which of the point is jumping or so.
Do you agree? Or does anybody have a better idea?

Still: I cannot reproduce it on my system.

**Comment by taaem** [comment] 2018-12-22 13:00
I just found something out, if I comment out:
```
zoom->scrollToZoomPosition(view);
```
in XournalView->zoomChanged() it stops jumping around, it obviously doesn't zoom in where its supposed to, but it doesn't glitches out.

**Comment by taaem** [comment] 2018-12-22 13:03
Maybe it is some kind of race conditions, where the layout changes and a zoom event is fired and everything goes down. If I look at the scale value reported by Gtk with the line above commented out, nothing jumps. If I leave the line I get these 300, values randomly in between.

**Comment by andreasb242** [comment] 2018-12-22 13:11
I also expected this, because of this I added the Gesture to the parent, and not to the Xournal Widget, which is moved. But even Then, I get coordiantes which are on the Xournal widget (y=16000 and more, where my Screen has only 1200px)
But it's hard to find the real issue...

**Comment by taaem** [comment] 2018-12-22 15:07
Maybe its easier to copy some code from evince https://github.com/GNOME/evince/blob/master/libview/ev-view.c because in their implementation everything works for me.

**Comment by peetCreative** [comment] 2018-12-22 15:36
mh... On my fix branch https://github.com/peetcreative/xournalpp/tree/fix_zoom_slider scrolling zoom and Slider zoom is working roughly. But I think I have to merge a lot of things.

**Comment by andreasb242** [comment] 2018-12-22 15:43
Scrolling zoom and Slider is now working. Only gesture touch is not working on some devices, on mine it's also working.

I merged the handling together, now touch and scroll use the same handling.
The Problem is the gesture handling on some devices.

**Comment by peetCreative** [comment] 2018-12-22 15:46
OK it's not working for me. It's still scrolling to fast and far.

**Comment by linwaytin** [comment] 2019-01-09 14:41
I have a similar issue.
It happens not when I am zooming, but when I am writing with a stylus. The gesture for zooming would be suddenly triggered, and the behavior is just like the video of **markwmuller**: The page glitches.

After this happens, the application gets stuck in this mode and I cannot write normally.

I do not figure out how to reproduce it systematically, but I found if the page is zoomed out by the slider and then "Fit the width," I can get out of the "glitching" mode and be able to write again.

I hope this information would be helpful.

**Comment by andreasb242** [comment] 2019-01-09 17:15
@linwaytin The more information, the better!

**Comment by morrolinux** [comment] 2019-01-09 17:46
I noticed that when changing tool, it's not always changing for real. sometimes I have to choose the tool a second or third time before it gets "engaged" for real. The speed in doing this could be a factor (the faster, the buggier). 
What if something similar happens to the "per-device" input handling? 
Maybe the pen is not always being released properly and starts a "pinch to zoom" gesture with the new input received?
E.G: 
1) Pen gets away from the screen, but the input handler doesn't catch the event, and still thinks the pen is where it was before leaving the screen 
2) Pen or touch interaction by the user generate another active (and moving) touch point, causing the (unwanted) pinch to zoom gesture.

It's just an hypothesis of course. Could it be?

**Comment by andreasb242** [comment] 2019-01-09 18:02
The gesture handling is GTK, and should only work with Touch. So it should not possible to zoom with the Pen. And all the device input handling, which you are talking @morrolinux is only relevant for drawing, not for Zooming.

I didn't get the Zoom Problem on my device yet, but I have only one Notebook with Touch. I got today a Wacom Graphics Tablet with touch, may I can reproduce it with this. But even then: The main Problem is in the GTK Stack, probably caused by Xournal++, and therefor it's really hard to find.

**Comment by andreasb242** [comment] 2019-01-09 18:11
Even with the "non working" PDF from @taaem it's working for me.

As I have now a touch for testing, I can use this on any system, so I can set up a System where it's not working. I currently don't know what causes it.

But I have today not enough time for systematically testing.

**Comment by unruhschuh** [comment] 2019-01-09 22:31
I might be wrong, but afaik the touch function of wacoms is registered as mouse events, not touch events. Similar to a track pad on a laptop. That may or may not make a difference here, but I assume a pinch gesture on a 'real' touch device is different from a pinch gesture on a trackpad.

I'm currently also facing the problem of simulating touch events on all platforms, as I don't own a touch device.

**Comment by linwaytin** [comment] 2019-01-09 22:39
Probably a silly comment: Can we have an option to disable the gesture of zooming? 
For me the slider is enough for zooming. This problem makes the application unreliable.

**Comment by andreasb242** [comment] 2019-01-10 16:39
@linwaytin Yes, we can do an option.

@unruhschuh You are right, I checked it. It's a touchpad, not a touchscreen.
I already looked at the GTK Code, Touchpad and Touchscreen are complete different implementation. Because a touchpad is relativ, and a touchpad is absolute.

**Comment by luco5826** [comment] 2019-01-10 22:49
@linwaytin we added the ability to disable zoom gestures!

**Comment by peetCreative** [comment] 2019-01-12 11:59
I don't really now weather this issue is connected, because for me it's only ocuring with slider and button in or out zooming.
I was debugging `ZoomControil::startZoomSequence`
```
GtkWidget* widget = view->getWidget();
this->zoomWidgetPosX = gtk_widget_get_allocated_width(widget) / 2;
this->zoomWidgetPosY = gtk_widget_get_allocated_height(widget) / 2;
```
Seems to give back the size of the whole widget. not the current  visible position.

However I was tinkering around a bit to get what we need (the coordinates of the middle of the visible Rect in Widget coordniates. I came up with this and debugged again with gdb.
```
	if (centerX == -1 || centerY == -1)
	{
		Rectangle rect = getVisibleRect();

		this->zoomWidgetPosX = rect.x + (rect.width/2);
		this->zoomWidgetPosY = rect.y + (rect.height/2);
		this->scrollPositionX = this->zoomWidgetPosX / this->zoom;
		this->scrollPositionY = this->zoomWidgetPosY / this->zoom;
}
```
And it turned out that the program flow seems to be wrong, which corrupts the `scrollPositionY`. I will post if I can reproduce it.

**Comment by linwaytin** [comment] 2019-01-12 14:19
@luco5826 Thank a lot. I tried it. That works, and so far the glitching problem does not show up again.

That makes I can really use Xournalpp. Great! 
I will report if the problem shows up again.

**Comment by andreasb242** [comment] 2019-01-21 19:08
Can somebody please recheck:
https://github.com/xournalpp/xournalpp/issues/683

See my last comment, enable it and check if the zoom has still the same issue, or if the Zoom is working with this checkbox?

As already written on the other Ticket: There are some issues, e.g. Scroll wheel not working, and may other issues.

This feedback is really important for me to know where the bug is located, and how I can get it fully fixed.

**Comment by taaem** [comment] 2019-01-21 19:47
Awesome, this works! Its not buttery smooth but overall it works fine, no more jumping to 3x - 4x zoom and stuff, only thing I noticed is, that it doesn't stay on one page but scrolls when I want to zoom, so I mostly end on the last/first page when zooming, so I don't really know if it works because the scroll position is not fixed or if the bug is really fixed.

**Comment by andreasb242** [comment] 2019-01-21 20:04
> that it doesn't stay on one page but scrolls when I want to zoom

Yes, it's a complete manual implement scrolling.
And it's basically working, as I wrote in the other Ticket, I expect a lot of new tickets ;-)

But this probably also means there is a Bug in the GTK Scroll container (I forgot the name).

But anyway, I think we need to optimize the custom container, so it works for touch drawing, and then we can also fix all other stuff, as the zoom here.

But it will be much work.... So don't expect it tomorrow ;-)

**Comment by cass00** [comment] 2019-01-22 18:51
Does pinch-to-zoom work in evince @taaem ? The implementation is basically taken from there, so if it works in evince then it should also work in xournalpp. Therefore I'm not really sure that it caused by a bug in the scroll container.
When I implemented the centred zoom there were some glitches similar to the ones described here. The problem was solved by changing the gestures widget from the XournalView widget to its parent. Have a look at https://github.com/xournalpp/xournalpp/issues/161 maybe this gives some clues.

**Comment by taaem** [comment] 2019-01-22 21:38
@cass00 yes, pinch to zoom works in evince just fine. #161 sounds like the same issue to me, because while debugging, when removing the centered zoom logic it started working without issue.

**Comment by kelmes** [comment] 2019-01-22 23:12
The same GtkGesture seems to be responsible for touchpad pinch gestures, where:

1. This bug does not occur
2. zooming is not properly centred

I also tried changing the parent widget, and it seems like every parent of the viewport (and the viewport itself) works for scrolling (which I vaguely remember not being the case at some point, but I could be wrong on that), and exhibits this bug.

**Comment by andreasb242** [comment] 2019-01-23 17:52
I didn't really analyze the bug, as it does not occur on my system. But may delete all the zoom gesture stuff and start from scratch may fixes it ;-)

But because of the GTK Scroll handling I think we ne a custom implementation. GTK catches all move geastures automatically on the scrolled widget, only click is sent to the widget. It would be nice if this also would work without hacks, as this is much less work.

**Comment by taaem** [comment] 2019-02-08 18:17
@andreasb242 I have a question, technically pinch to zoom should be working in X11 right? Because for some reason I can't use the zoom gesture for zooming in Gnome Xorg mode. In Wayland the state is as described in the bug.

**Comment by andreasb242** [comment] 2019-02-08 18:26
It should work on all supported system, as this is a Gnome feature. For me it's working on X11 (Ubuntu 16.04, Lenovo Helix)

**Comment by taaem** [comment] 2019-02-08 18:30
Okay also this isn't working in Evince, so there is something completely off. At this point I'm really disappointed with Lenovo or Wacom or whoever managed to get this in this state (eg no useable pen whatsoever).

**Comment by andreasb242** [comment] 2019-02-08 18:47
Install gtk3-demo, there is also an input test, where you can test if you have multi touch working etc.

**Comment by taaem** [comment] 2019-02-08 22:12
Okay also this isn't working in Evince or the gtk3-demo, so I either have no functional pen (weird glitches) and weird zooming on Wayland or I have a working pen and no multitouch gestures on Xorg. At this point I'm really disappointed with Lenovo or Wacom or whoever managed to get this in this state.

**Comment by johrpan** [comment] 2019-02-11 12:57
I also have this problem (ThinkPad L380 Yoga) and because you mentioned, I tested my input devices with gtk3-demo. I noticed a difference between touchscreen pinch-to-zoom (which doesn't work correctly in Xournal++) and track pad (which works as expected). This colored box stays where it is after the gesture ends when using the track pad and disappears when using the touchscreen. This means, there is some kind of difference between them, but I don't know whether this helps...

**Comment by coldspark29** [comment] 2019-04-22 11:22
To warm this up a little bit. I have absolutely no glitches with evince. The zooming behaviour is nice and smooth! I do have problems with zooming in Xournal++ though, no matter whether I use pinch to zoom or Ctrl +/-, it always scrolls and zooms at the same time, which results in the mentioned graphical glitches.

**Comment by coldspark29** [comment] 2019-04-29 16:35
I realized that the bug occurs only in large documents. On the first page there is usually no problem, but on the latter pages (like page 200 or so) the scrolling effect gets worse and worse. Maybe this would be something worth looking into!

**Comment by cbm755** [comment] 2019-04-29 21:28
I think it tries to redraw several times during the pinch-and-zoom.  I've noticed that's its slower/more awkard on pages with complicated figures.

**Comment by Scafir** [comment] 2019-05-15 22:44
I also have this issue. This issue is triggered when as the scrolling bar appears. The scale factor given by the gesture then goes numb ~80% of the time: https://imgur.com/a/76UEdVi.
I tried successfully copying how evince's zoom works in xournalpp, but the problem is still here indicating that it appears when the zooming is *applied*, so here  (src/control/ZoomControl.cpp): 
```
void ZoomControl::fireZoomChanged()
{
        XOJ_CHECK_TYPE(ZoomControl);

        if (this->zoom < this->zoomMin)
        {
                this->zoom = this->zoomMin;
        }

        if (this->zoom > this->zoomMax)
        {
                this->zoom = this->zoomMax;
        }
        for (ZoomListener* z : this->listener)
        {
                z->zoomChanged();
        }
}
```
One thing worth noticing though, is that the scrolling is buttery smooth and 100% works when the GTK Touch/Scroll workaround is enabled

**Comment by taaem** [comment] 2019-07-09 14:49
I was noticing, that EOG and Evince are both pure C apps and have no issue with zooming whatsoever. (EOG's zooming is really smooth) 
Since Xournalpp uses C++ maybe the issue is somewhere in the bindings and not in Xournalpp or Gtk?

**Comment by LittleHuba** [comment] 2019-09-10 20:18
Is this bug still there? This ticket has evolved to a lot of different topics. Please state a clear description of the problem so we can fix the issue.

**Comment by taaem** [comment] 2019-09-10 20:45
The bug is still there, description below:

On Wayland pinch to zoom causes the zoom level to "jump" between the real values and wrong ones (can be lower or higher) as seen in @Scafir s video. The outcome is that you can't use pinch to zoom because you might end up zoomed in 700x. 
On Evince pinch to zoom works just fine.
For me this only happens on Wayland, on Xorg I can use the pinch t zoom gesture just fine.

**Comment by LittleHuba** [comment] 2019-09-10 21:54
Could you please switch to the new input system in the settings and retry?

**Comment by taaem** [comment] 2019-09-10 21:56
@LittleHuba just tried and it is not helping :/

**Comment by LittleHuba** [comment] 2019-09-10 21:58
Okay it seems like we need to finally implement the zoom gesture on our own. I thought about implementing it myself for another ticket but we then found a simpler solution for it. 

The zoom gesture is all GTK+ internal and fixing it will be harder than just writing down the code for zooming in our own handler.

**Comment by taaem** [comment] 2019-09-10 22:03
Okay, thanks! 
If I can help in some way please let me know!

**Comment by LittleHuba** [comment] 2019-09-10 22:05
Are you fluent in C++? :wink:

**Comment by taaem** [comment] 2019-09-10 22:07
It's a long time since I last used C++ :smile: 
I don't know if it is enough for this kind of implementation, but if you can give me hints at were to start I can try :man_shrugging:

**Comment by LittleHuba** [comment] 2019-09-10 22:33
You can at least try!

The file you should implement this is:
`src/gui/inputdevices/TouchInputHandler.cpp`

In this file you find a function called `handleImpl()` which is called for each event that is received. You can differenitiate between events of different fingers using the attribute `event->sequence`. All the other important values are also stored in `event`.

Currently this class handles scrolling for touchscreens as this is also problematic within GTK+ for some devices...

An outline of the steps you need to do:

- [ ] Disable the current check that only allows single-touch as you will require multi-touch
- [ ] Rewrite the scrolling routine so that it will ignore multi-touch (reuse the current check)
- [ ] Write the zooming algorithm

Implementation details for the zooming algorithm:
- get the zoom factor by using the distance of the two fingers
- use the center of the gesture to scroll the view accordingly (you can use parts of the scrolling algorithm in this file for doing this)

For testing purposes you can just disable the GTK zoom handling by unticking the checkbox for the zoom gesture in the settings dialog.

It is no problem if you are unable to do everything. I'll just adopt your work and finish if it should be required.

Happy coding!

**Comment by taaem** [comment] 2019-09-10 22:34
Thanks for the detailed information! I will look into it in the coming days!

**Closed** 2019-10-17 22:49 UTC
Labels: Zoom, bug, difficulty:medium, priority: high
