### ISSUE TITLE
Additional margin around drawing area appears

### ISSUE THREAD

**Issue by KlausBlum** [xournalpp/xournalpp#5159] opened 2023-09-19 09:36 UTC
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Windows installer from official release

### Xournal++ Version

1.2.1

### libgtk Version

3.24.39

### Bug Description

After restarting Xournal++ or after switching on/off fullscreen mode, additional margins around the drawing area appear where there is no toolbar in use.
It looks as if they are empty/unused toolbars that are not hidden. 

### Expected Behaviour

Empty/unused toolbars should stay hidden instead of consuming screen space.

### Steps to Reproduce

1. Select a different toolbar than the one you just have been using (View -> Toolbars). 
    No additional margins visible at the moment. 

2a. Switch fullscreen mode on and off (press F11 two times)
or
2b. Re-start Xournal++

Now you see additional space at window borders that don't have a toolbar. 
Example: If you have toolbars only at the top and the bottom, an additional margin appears at the left and the right side. 
It looks as if they are empty toolbars that don't contain buttons.

**Comment by bhennion** [comment] 2023-09-19 15:24
Duplicate of #5051

**Closed** 2023-09-19 15:25 UTC
Labels: bug
