### ISSUE TITLE
[SUGGESTION] Infinite / endless page

### ISSUE THREAD

**Issue by scrouthtv** [xournalpp/xournalpp#2683] opened 2021-01-20 11:34 UTC
**Describe the solution you'd like**
I'm interested in an infinite page feature, where the drawing area is endless in all directions.
I think this is especially useful for now-linear content, e. g. mind maps.
The idea actually came to my mind when collecting ideas in a mind map. At some place, I didn't have any more space to the sides of the page to add points.

**Describe alternatives you've considered**
Technically, cramming everything into an A4 (or otherweise configured page - a giant square page) would work, but I think it'd be way easier to just being able to expand the page as you go.
Also, if I scale the page up to a giant square, I'd have a lot of white borders in the export at the end.
Another issue with this is that the performance is very poor. An **empty** page with 100 x 100 cm takes up 200 mb of ram on my pc. And that is without any drawings.

**Comment by TomatDividedBy0** [comment] 2021-01-20 20:30
Can't second this enough. Infinite scroll is a killer feature on OneNote for me (which is my killer app for Windows). One of the main reasons I use digital notes over paper is it doesn't have those space constraints. This was the top priority I had in mind when I was looking for note-taking software to use. 

I don't know if this'd make it easier or more difficult to implement/run, but what if you treated each pen stroke as its own layer, then have a file which remembers the positions of each layer (relative to the center of the canvas). This might also help if the pen-strokes are done as SVGs.

**Comment by personalizedrefrigerator** [comment] 2021-01-20 21:29
It looks like this is a part of the goal of the [new file format](https://github.com/xournalpp/xournalpp/issues/1515#issuecomment-540214300)...

**Comment by ericschdt** [comment] 2021-05-05 17:43
Sounds like a duplicate of https://github.com/xournalpp/xournalpp/issues/1174

**Comment by ckolumbus** [comment] 2021-11-15 10:58
@LittleHuba  anything we could do to push forward on implementing endless paper size? the Project canvas seems to be unmaintained.

**Comment by LittleHuba** [comment] 2021-11-15 11:04
A team of 10 fulltime developers would certainly help but as there is no pay involved this... 🙃

The issue with this project is that it is nearly the workload of rewriting half of Xournal++. There is no quick way of doing this. We have to rewrite most of the rendering subsystem (currently in progress). We'll get there eventually but it will take time.

Oh if you know C++ or want to learn it, join in on the fun and start tackling issues on this repo. That would certainly help!

**Comment by ckolumbus** [comment] 2021-11-16 06:56
I am old.. so old that I started with C++ 😁... I'm kind of a Qt guy, not much experience with gtk++. Looking at my (maybe possible) availability it would be cool/efficient if there are some backend related topics that I could support. But I can try to help wherever you have smaller independent tasks. 
Is there some info anywhere about the open tasks and the ongoing activities / next steps?

**Comment by LittleHuba** [comment] 2021-11-16 14:58
Great to hear that you could help out with some stuff! I'm looking forward to seeing PRs from you.

We have a list of open TODOs here: https://github.com/xournalpp/xournalpp/issues/2354

Also, for smaller tasks you might want to search the issues for the tag `difficulty::easy`. 

You are of course welcome to pick whatever task you want to tackle!

**Comment by bhennion** [comment] 2021-12-15 19:08
Duplicate of #1174

**Closed by bhennion** 2021-12-15 19:08 UTC
Labels: enhancement
