### ISSUE TITLE
Settings get lost when two instances of xournalpp are open

### ISSUE THREAD

**Issue by adnidor** [xournalpp/xournalpp#1479] opened 2019-09-18 11:38 UTC
**Affects versions :**
 - OS: Arch Linux
 - Version of Xournal++: 10.0.12

**Describe the bug**
If I open and close two simultaneous instances of Xournal++, then open another instance, the setting are reset to the default

**To Reproduce**
1. Open Xournal++, write something, maybe save
2. Open new instance of Xournal++, write somethin, maybe save
3. Close the two instances
4. Open new instance

**Expected behavior**
The new instance has the same setting as the last two

**Actual behaviour**
The setting have been reset to the default values

**Comment by LittleHuba** [comment] 2019-09-18 23:35
Duplicate of #1074

**Closed by LittleHuba** 2019-09-18 23:35 UTC
Labels: bug
