### ISSUE TITLE
Please remove the broken release 1.0.17

### ISSUE THREAD

**Issue by yurivict** [xournalpp/xournalpp#1734] opened 2020-02-07 06:07 UTC
The 'install' target is broken: https://github.com/xournalpp/xournalpp/issues/1596

You shouldn't release until this is fixed. You make all port maintainers to try to build and to discover this problem.

**Comment by nicegamer7** [comment] 2020-02-07 16:22
There is nothing wrong with the 1.0.17 release (at least on my end). In #1596, @LittleHuba says

> For now do a `make translations` before building X++.

**Comment by Technius** [comment] 2020-02-07 18:35
Oops, I guess I missed reverting https://github.com/xournalpp/xournalpp/commit/f784631ef695dfbc6194a550c5ef7cc27aa6d16d when I backported changes to the 1.0.x series. I have updated the release description with a brief notice.

We're not going to pull the release because the translation target issue is a minor buildsystem issue. For now, you can either 1) [patch `po/CMakeLists.txt`](https://github.com/xournalpp/xournalpp/blob/12febf7e577aeb8756464c23713ef9a43729eede/po/CMakeLists.txt#L23) so it is compatible with your current build scripts:
```diff
-  gettext_create_translations ("${potfile}")
+  gettext_create_translations ("${potfile}" ALL)
```
or 2) modify your build scripts to run `cmake --build . --target translations` before running the install or package target.

Closing as a duplicate of #1596.

**Closed by Technius** 2020-02-07 18:35 UTC
Labels: bug
