### ISSUE TITLE
Touch scrolling stops reacting regularly

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#941] opened 2019-02-26 08:06 UTC
When scrolling with the touchscreen sometimes there is no reaction. This happens about every 7th touch input. I don't know how to further narrow down the problem.

**Comment by andreasb242** [comment] 2019-02-26 19:37
Can you reproduce it with gtk3-demo?

**Comment by coldspark29** [comment] 2019-03-02 19:59
No, I can't reproduce it with gtk3-demo

**Comment by nicjohnston** [comment] 2019-03-03 05:49
I have also run into this.  Every 7th input is a detail I haven't noticed, but I haven't looked for a pattern.
Is there a cmd line flag to output extra debugging info that would help track this down?
To unfreeze the input I typically have to open the activities overview, tap on Xournal++, then scroll back and forth a few times on both axes (using two fingers) before single finger scrolling starts working again.
For reference, I'm running Debian testing with Gnome 3.30.2 running on X11.

**Comment by peetCreative** [comment] 2019-03-14 14:47
I can reproduce this problem. It only appears to me when I'm in fullscreen.

**Comment by coldspark29** [comment] 2019-05-05 09:30
I also have it in non-fullscreen. Apart from that I can confirm once again that this is not a GTK3 issue, since I don't have any problems with e.g. Evince.

**Comment by LittleHuba** [comment] 2019-05-13 21:13
Could you recheck this with the new experimental input system (activate it in the settings)?

If you follow [this article](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs) you can provide further debug logs if you happen to still encounter the issue. Whether they are helpful in this issue is not sure though.

**Comment by lehmanju** [comment] 2019-08-06 10:37
Related/Duplicate of #1383

**Closed** 2019-08-22 18:39 UTC
Labels: bug
