### ISSUE TITLE
infinity canvas/paper

### ISSUE THREAD

**Issue by soumyaranjan191819** [xournalpp/xournalpp#4085] opened 2022-06-10 17:57 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
please add infinity paper/canvas like openboard/microsoft word so that it will be help for write bigger mathematical equations.

**Comment by bhennion** [comment] 2022-06-10 18:40
duplicate of #3123 #1174 #2683... Closing.

**Closed by bhennion** 2022-06-10 18:40 UTC
Labels: enhancement
