### ISSUE TITLE
Installer crashes after installing on Windows 7

### ISSUE THREAD

**Issue by KataFF** [xournalpp/xournalpp#3932] opened 2022-03-28 21:50 UTC
### Note: Not really an issue (the Xournal++ itself installs and works), see below for details
Hey, just wanted to let you know that the installer crashes after copying shortcuts to the Start Menu on Windows 7 Ultimate x64.

In spite of the crash error, the program seems to install and run just fine afterwards, so it's not really an issue. And yeah, I know Windows 7 isn't supported anymore, I'm really just using it for stuff which won't run in my main Arch Linux install.

Sorry for the polish localization, but the error message is the standard "xournalpp-1.1.1-windows.exe has stopped working" , below you have the typical options to "Search for the solution online" or "Close the program" and then the problem details.
![image](https://user-images.githubusercontent.com/62726159/160491841-ce81f6e8-cb06-4696-a1c5-3628e7b3129b.png)

Feel free to close this issue if you want to, thought I might just mention it in case any errors appear later on when it comes to Windows installs and this could be used for pinpointing the cause and/or troubleshooting. Cheers!

**Comment by veganaize** [comment] 2022-04-05 17:32
I'm having the same/similar problem on Windows 8.1 (x64) with `v1.1.1` and `v1.1.1+dev`.

It installs fine (with the error) but it completely fails to uninstall anything besides the start menu shortcuts.

Could this be a problem with (the relatively new) NSIS v3.08 ?

Raw error -- happens at the end of install / beginning of uninstall:
![image](https://user-images.githubusercontent.com/7102064/161815736-ec5d95b1-ce48-426c-b7e8-b0bf5b42ecfa.png)

**Comment by KataFF** [comment] 2022-05-17 23:47
Hey, an update - just tried uninstalling Xournal++ through the standard built-in Windows 7 "Remove Software" tool and the dedicated uninstaller:
![Przechwytywanie](https://user-images.githubusercontent.com/62726159/168929294-6d818e77-821f-4654-a0b9-895c9d5a7d03.PNG)
, and observed analogic behaviour as when installing - the program uninstalled just fine from Program Files (x86), Start Menu and Desktop, but the uninstaller crashed after installing:
![Przechwytywanie2](https://user-images.githubusercontent.com/62726159/168929344-f33fdb43-61f7-4b1d-a784-c4d7f54ab8c0.PNG)
![Przechwytywanie3](https://user-images.githubusercontent.com/62726159/168929357-2aa46e48-fea3-4c23-9557-c30dcfe41e68.PNG)

Further inspection after firing up regedit.exe and Ctrl+F'ing "xournal" reveals that there were a few related registry keys left - .pdf, .xoj, .xopp and .xopt file association:
![image](https://user-images.githubusercontent.com/62726159/168929455-16e3cdc5-9e6f-4172-937d-da07f0422e05.png)

Nothing else though, so it was a pretty "clean" uninstall. 

Why did I uninstall? I liked the app, but it didn't quite fit my needs - I wanted something to prepare notes mostly with keyboard and settled with Joplin after all.

Anyway, thanks to the devs for a good app. Cheers!

**Comment by Technius** [comment] 2022-05-20 07:38
Closing in favor of #4041, which seems to have identified the cause.

**Closed by Technius** 2022-05-20 07:38 UTC
