### ISSUE TITLE
Why can't I rotate the images?

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#4636] opened 2023-02-06 05:51 UTC
**Affects versions :**
 - OS: [Windows11]
 - Which version of libgtk : 3.24.36
 - Version of Xournal++: [3.24.36]
 - Installation method: [official release]

**Describe the bug**
With the objects when selecting them, it allows the rotation since a red box appears, but with the screenshots or images, when pasting them, I can not rotate them.

**To Reproduce**
1. paste an image from the clipboard
2. try to rotate

**Expected behavior**
It's not a big problem but it would be great if you could implement the rotation or if it's a bug could you tell me the solution, I hope I'm not a bother.

**Additional context**
Add any other information or context about the problem here.
![image](https://user-images.githubusercontent.com/28522011/216892359-8421a490-17c0-4786-ab6f-1e655d0f78e2.png)

**Comment by rolandlo** [comment] 2023-02-06 06:44
Duplicate of #918

**Closed by rolandlo** 2023-02-06 06:44 UTC
Labels: bug
