### ISSUE TITLE
PDF export crashes on one page

### ISSUE THREAD

**Issue by PaulCombal** [xournalpp/xournalpp#2556] opened 2020-12-17 23:39 UTC
**Affects versions :**
 - OS: Ubuntu, potentially all OSs
 - (Linux only) Desktop environment: XFCE (Xubuntu)
 - Which version of libgtk do you use
     - 3.22.30
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.0.20
 - Installation method: Snap

**Describe the bug**
I successfully opened a PDF file on Xournal++, and added the modifications I wanted. Super!

Now, when exporting as PDF, the export process crashes on a specific page, and the rest of the document is not rendered. Note that I did not edit anything on this particular page. The same result happened after removing all my edits.

Unfortunately I'm not sure if I can share the document shown here. Ask me in private if you need it. Here are screenshots so you can better see what the issue is.

![image](https://user-images.githubusercontent.com/5382590/102555345-e08d7000-40c6-11eb-8f6a-99f244e7eb18.png)
I have a 3-pages document open in Xournalpp.

![image](https://user-images.githubusercontent.com/5382590/102555427-0adf2d80-40c7-11eb-9772-246401df2144.png)
As you see my export crashed on the second page. No further pages are rendered.

Oddly enough, I can load the original PDF and immediately export it just fine, so I assume I must have broken something halfway through. The issue persists after saving the .xopp, closing Xournal++, and reopening the xopp save file.

Removing the middle page works, so it's definitely something on that page that causes the issue.

The export to PNG works just fine.

**To Reproduce**
1. Open a PDF
2. Edit it
3. Export as PDF

**Expected behavior**
The PDF exports in its entierty.

**Screenshots of Problem**
See above

**Additional context**
The console doesn't print any log when exporting.

**Comment by personalizedrefrigerator** [comment] 2020-12-18 00:25
This might be a duplicate of #2464...

**Comment by personalizedrefrigerator** [comment] 2020-12-18 00:34
If this is a duplicate, a quick fix might be to add a check that makes sure `width != 0 && !isNaN(width)` here:  https://github.com/xournalpp/xournalpp/blob/5ef6a2976557d48d1b1f6f6bafa942098b6fa985/src/model/Stroke.cpp#L94

This also assumes the issue isn't something like `pressure=NaN` (and that this is related to #2464)...

**Comment by rolandlo** [comment] 2020-12-18 05:59
Does the .xopp-file also contain sensitive data or just the pdf? We don't need the underlying pdf if the problem is #2464. The .xopp-file would be enough.

**Comment by PaulCombal** [comment] 2020-12-18 11:08
Here is the zipped xopp file
[issue.xopp.zip](https://github.com/xournalpp/xournalpp/files/5715262/issue.xopp.zip)

**Comment by rolandlo** [comment] 2020-12-18 11:30
It was indeed a case of #2464 (image with width and height 0). With this repaired file 
[issue_repaired.zip](https://github.com/xournalpp/xournalpp/files/5715360/issue_repaired.zip)
 it should work. Please check!

**Comment by PaulCombal** [comment] 2020-12-18 11:40
It worked, and "added" the image back. Feel free to close this issue, and many thanks for the active support!

**Comment by rolandlo** [comment] 2020-12-18 11:41
Closed in favor of #2464

**Closed by rolandlo** 2020-12-18 11:41 UTC
Labels: bug
