### ISSUE TITLE
Some icons are not visible in nightly build

### ISSUE THREAD

**Issue by m8** [xournalpp/xournalpp#4635] opened 2023-02-05 13:05 UTC
**Affects versions :**
 - OS: Fedora 37
 - Desktop environment: Gnome43 X11
 - Which version of libgtk do you use: 3.22.30
 - Version of Xournal++: nightly build
 - Installation method: Appimage from repo

**Describe the bug**
Some of icons are not visible in nightly build.

**Expected behavior**
Icons should be visible.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/19881231/216820237-94115d60-8243-4e4f-9e58-5859cc33b9b5.png)

**Comment by bhennion** [comment] 2023-02-05 13:54
This is a duplicate of #3945, which is a dependency issue that has been solved upstream. Updating GTK to 3.24.34 or more should solve it.

**Closed by bhennion** 2023-02-05 13:54 UTC
Labels: bug
