### ISSUE TITLE
I hope to add the calligraphy tool

### ISSUE THREAD

**Issue by AD1GO** [xournalpp/xournalpp#5951] opened 2024-10-17 11:34 UTC
### Is Your Feature Request Related to a Problem?

I hope to add the calligraphy tool
I loved this app and I don't want to move to another app.

### Feature Description

![image](https://github.com/user-attachments/assets/d7b07480-304e-425d-a07b-274256b7674c)

**Comment by rolandlo** [comment] 2024-10-17 12:25
How do you plan to add the calligraphy tool?

**Comment by AD1GO** [comment] 2024-10-18 10:52
To be honest, I don't have any programming skills, but I hope this tool is available because if this tool is available in this program, it will undoubtedly be the first program for handwriting on Windows.

What is my opinion about the type of font?

I think that the font should be at a sharp angle and contain Pressure Sensitivity, and this is all we need in programming in this regard.

Is it important to add this tool to a program like Xournalpp?

Of course, it is the only main tool missing in this program, and other simple things can be added, but this tool remains important and will work to make a qualitative shift in writing on this program.

I have seen many important posts in terms of programming regarding the calligraphy tool that can be used, and I do not know about the possibility of using GPT for programming for this tool... Is it possible?

If this tool is added to this program, I will be grateful to you for the rest of my life and all users of the program as well!

I think we should not delay any longer to add this tool to this wonderful program...

Many thanks to the contributors to the development of this program.

**Comment by rolandlo** [comment] 2024-10-18 17:55
In this case I must close the issue as a duplicate of #2166 #3777. What is the "main missing tool" in Xournal++ is highly subjective. I certainly wouldn't advice to try programming that tool with Chat GPT. Maybe someone with the right motivation will pick it up.

**Closed by rolandlo** 2024-10-18 17:55 UTC
Labels: enhancement

**Comment by AD1GO** [comment] 2024-10-18 19:00
I didn't understand what you mean!
