### ISSUE TITLE
Text rotation

### ISSUE THREAD

**Issue by Yobeco** [xournalpp/xournalpp#2040] opened 2020-06-05 16:33 UTC
**Is your feature request related to a problem? Please describe.**
No, it's just a new function

**Describe the solution you'd like**
It would be useful to be able to rotate text object in a similar way to images.

**Describe alternatives you've considered**
Make a PNG of the text with other application and import it. I have to take angle measurements to get the exact orientation...

**Additional context**
To annotate vertical or oblique graphic objects, to add diagonally written "ads" that attract attention...
With an alpha option, it would make it possible to make watermark-style notations.

**Comment by Technius** [comment] 2020-06-05 18:08
Duplicate of #1566.

**Closed by Technius** 2020-06-05 18:08 UTC
Labels: enhancement
