### ISSUE TITLE
Maths Geomertical tools

### ISSUE THREAD

**Issue by mandypreet** [xournalpp/xournalpp#3105] opened 2021-05-10 05:50 UTC
Hello Sir,
Sir, I am requesting a new feature ---**"Maths Geometrical tools"** including ruler, protractor, Compass, setsquare, basic 2D -shapes and 3D-shapes etc. So, it make us easy to teach maths online.

**Comment by personalizedrefrigerator** [comment] 2021-05-12 04:30
See also #1937

**Comment by rolandlo** [comment] 2021-05-12 18:02
Closing this, since it is a duplicate of #1937. Also for the setsquare see PR #3082

**Closed** 2021-05-12 18:15 UTC
Labels: enhancement
