### ISSUE TITLE
Shortcuts & fullscreen

### ISSUE THREAD

**Issue by ppolkf** [xournalpp/xournalpp#803] opened 2019-01-23 12:58 UTC
Hi,
it seems that when the menu bar is not shown (either in fullscreen mode or when it is hidden using the View menu) some shortcuts (like cut, copy, paste, etc) don't work while others do (goto last page, goto first page, etc). Could this be corrected?
Best,
F.

**Comment by peetCreative** [comment] 2019-01-23 13:59
Thank you for reporting the bug!
I can reproduce the bug.

**Comment by ppolkf** [comment] 2019-01-23 14:14
In case it is of any help, an analogous behavior was seen  in the original xournal when setting up personal shortcuts; it is is described in https://sourceforge.net/p/xournal/discussion/554376/thread/be0db1a7/

**Comment by andreasb242** [comment] 2019-01-23 18:01
This is caused because we hide the Menu.
The most shorcuts are assigned over the menu only, this are not working.
Some Shortcut are handled a different way, because of some reason, this are usually still working.

>Could this be corrected?

Yes. It is.

The more important question: @ppolkf are you just asking, or do you really miss the shortcuts would work without menu? Because if you just asking we can close this ticket now.
The main Problem: GTK Registers the shortcuts on Glade loading to signals, and there is no API to query any signals, therefore we cannot get the Signals Back from menu.
Technical this means we need a really good idea to get this working, or as in the Thread you mentioned, we register any keyboard shortcut twice, which I tell you this is no option, because of work and maintenance.

**Comment by andreasb242** [comment] 2019-01-23 20:34
We should check if we can place the menu behind something, but still visible. So the shortcuts keep active.

**Comment by andreasb242** [comment] 2019-02-01 20:09
Done with a workaround, which still costs 1px in height, but less is not possible....

**Comment by andreasb242** [comment] 2019-02-01 20:12
https://github.com/xournalpp/xournalpp/pull/827

**Closed by andreasb242** 2019-02-01 20:12 UTC
Labels: bug
