### ISSUE TITLE
Use language names instead of language codes in the settings

### ISSUE THREAD

**Issue by MatsG23** [xournalpp/xournalpp#4507] opened 2022-12-14 16:54 UTC
**Is your feature request related to a problem? Please describe.**
If you go to the language settings and click on the dropdown, you see that Xournal++ uses some type of shortened language code (not the "long version" like de_DE or en_GB). This can be annoying.

**Describe the solution you'd like**
List the language names in the foreign language instead to improve the user experience.

**Describe alternatives you've considered**
You could add the language name in brackets. 

**Additional context**
Using openSUSE Tumbleweed 20221213 and KDE Plasma 6.24.4 (Wayland).

**Comment by hyperupcall** [comment] 2022-12-16 21:40
Thank you for your suggestion, this apears ot be a duplicate of #3126

**Closed** 2022-12-17 06:48 UTC
Labels: enhancement
