### ISSUE TITLE
Customizable keyboard shortcut or hot keys for specific tools

### ISSUE THREAD

**Issue by ehremington** [xournalpp/xournalpp#1465] opened 2019-09-12 14:35 UTC
**Is your feature request related to a problem? Please describe.**
I use xournal in a physics class where my notes are written "live" for the students on the projector screen. I often switch between solid and dotted lines in my classroom setting. I also between two or three colors. At the moment, the toolbars are not bad, but the dotted line takes extra clicks through the drop down, and colors take cursor movements to the tool bar. I'm constantly doing this and it can be distracting to students who are used to following my cursor around.

**Describe the solution you'd like**
A hot key system so that when I am not writing in text mode, and I hit the #1 key I get my default pen, but then I have #2 set up for a white dotted line, and then I have the "r" key set up to change the color to red, and so on. It would be nice to have a place to set the key bindings myself for the tools I use most.

**Describe alternatives you've considered**
I mean clicking on tools is obviously not hard, but since I use this in a classroom setting where my physics notes are appearing live on the screen, speed in switching tools drastically cuts down on the distracting movements my students have to watch.

**Comment by LittleHuba** [comment] 2019-09-13 07:56
Duplicate of #919

**Closed by LittleHuba** 2019-09-13 07:56 UTC
Labels: enhancement
