### ISSUE TITLE
Starting xournalpp takes 5 minutes

### ISSUE THREAD

**Issue by pentix** [xournalpp/xournalpp#1636] opened 2019-11-28 21:39 UTC
**Affects versions :**
 - OS: ArchLinux
 - X11

```
    pacman -Qi gtk3
    Name            : gtk3
    Version         : 1:3.24.13-1

    pacman -Qi xournalpp 
    Name            : xournalpp
    Version         : 1.0.16-1

```
The same behavior when I build xournalpp from source (commit: fabe9e1)

**Describe the bug**
I start xournalpp and I don't see anything for about 5 minutes. After that, the
main window appears and everything works fine! 

The process does not lead to high CPU load, ksysguard reports 'disk sleep',
so I guess it's waiting for I/O?

If I run the current development version in gdb, and interrupt (Ctrl + C)
the process in those "waiting minutes", it still takes some time until the process is interrupted.
(Again, waiting for I/O I guess?)

Then, I was able to get the following backtrace:

```
Thread 1 "xournalpp" received signal SIGINT, Interrupt.
0x00007ffff68201d4 in open64 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff68201d4 in open64 () at /usr/lib/libc.so.6
#1  0x00007ffff6d54bf9 in snd_pcm_hw_open () at /usr/lib/libasound.so.2
#2  0x00007ffff6d55007 in _snd_pcm_hw_open () at /usr/lib/libasound.so.2
#3  0x00007ffff6d4530b in  () at /usr/lib/libasound.so.2
#4  0x00007ffff6d459c0 in  () at /usr/lib/libasound.so.2
#5  0x00007ffff6d4795f in snd_pcm_open () at /usr/lib/libasound.so.2
#6  0x00007ffff6de25a5 in  () at /usr/lib/libportaudio.so.2
#7  0x00007ffff6de4ddb in  () at /usr/lib/libportaudio.so.2
#8  0x00007ffff6de81ea in PaAlsa_Initialize () at /usr/lib/libportaudio.so.2
#9  0x00007ffff6ddb3e0 in Pa_Initialize () at /usr/lib/libportaudio.so.2
#10 0x00007ffff6e0f283 in portaudio::System::initialize() () at /usr/lib/libportaudiocpp.so.0
#11 0x0000555555884078 in portaudio::AutoSystem::AutoSystem(bool) (this=0x5555559caf78, initialize=true)
    at /usr/include/portaudiocpp/AutoSystem.hxx:37
#12 0x0000555555884ea1 in PortAudioProducer::PortAudioProducer(Settings*, AudioQueue<float>*)
    (this=0x5555559caf70, settings=0x555555a7b450, audioQueue=0x5555559f7bf0)
    at xournalpp/src/util/audio/PortAudioProducer.cpp:6
#13 0x000055555588304f in AudioRecorder::AudioRecorder(Settings*) (this=0x555555c07e00, settings=0x555555a7b450)
    at xournalpp/src/util/audio/AudioRecorder.cpp:9
#14 0x00005555557147bd in AudioController::AudioController(Settings*, Control*)
    (this=0x555555bfa050, settings=0x555555a7b450, control=0x555555ab5800)
    at xournalpp/src/control/AudioController.cpp:11
#15 0x0000555555716adf in Control::Control(GladeSearchpath*) (this=0x555555ab5800, gladeSearchPath=0x555555b9f0c0)
    at xournalpp/src/control/Control.cpp:103
#16 0x0000555555741434 in XournalMain::run(int, char**) (this=0x55555594fe10, argc=1, argv=0x7fffffffe018)
    at xournalpp/src/control/XournalMain.cpp:351
#17 0x000055555570fb8e in main(int, char**) (argc=1, argv=0x7fffffffe018) at xournalpp/src/Xournalpp.cpp:32

```

**To Reproduce**
1. Install xournalpp with default (factory) settings
2. Start xournalpp

**Expected behavior**
I've used it on older machines before, it starts immediately. I don't know
what it's waiting for.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
... No, it's a modern notebook ;)

**Comment by pentix** [comment] 2019-11-28 22:20
I identified the issue:
The audio recording storage location was per default set to 🌍 (in gtk's folder chooser) Setting it to my home directory leads to immediate startup.

So I guess the bug reduces down to "don't let 🌍 be the default location"

**Comment by LittleHuba** [comment] 2019-11-29 12:27
Yeah the backtrace shows quite well that the issue is in initializing the audio system. But changing that path does not make sense as fix since the sound system is absolutely unaware of the path. I assume it was a bug in one of the dependencies that got fixed. Please set the path back to the original value and see if the bug reoccurs. 

The problem is something hardware or driver related.

**Comment by pentix** [comment] 2019-11-29 15:27
Hi, you are totally right, a few notebook reboots later, I tried to use it again and the same bug appeared.
Just weird it worked perfectly after changing the path initially.

Is there a possibility to disable the audio subsystem completely?

**Comment by LittleHuba** [comment] 2019-11-29 18:25
We have not included the functionality to disable it completely. But it shouldn't be very complex. I'll write a PR the next few days.

**Comment by LittleHuba** [comment] 2019-11-29 23:03
With the new information this is a duplicate of #1468

**Closed by LittleHuba** 2019-11-29 23:03 UTC
Labels: bug
