### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by mandypreet** [xournalpp/xournalpp#3106] opened 2021-05-10 05:55 UTC
Hello Sir,
sir, recently i have downloaded the xournal++ 1.1.0 version. But when i tried to change the theme to dark. It only darken the background of thumbnail pages and all other icons and skin remain unaltered. Please solve this kind of issue or bug.
![Screenshot (107)](https://user-images.githubusercontent.com/83940423/117612193-68f9d380-b182-11eb-81cb-f2b1e42565bf.png)

**Comment by personalizedrefrigerator** [comment] 2021-05-12 04:29
See also #1746

**Comment by rolandlo** [comment] 2021-05-12 18:19
@mandypreet What OS do you use? Note that you will also have to switch to dark theme in your OS. On a Gnome-based Linux distro you would use the Tweak tool to change that. 
![grafik](https://user-images.githubusercontent.com/40485433/118024711-4cff5900-b35f-11eb-91b1-e33bb679e580.png)

**Comment by ChrTall** [comment] 2021-12-02 17:02
@rolandlo 
On Kubuntu I have configured a dark Theme for GTK Applications, but Xournal++ is always in light mode.(Snap)

**Comment by personalizedrefrigerator** [comment] 2021-12-02 19:31
> @rolandlo
> On Kubuntu I have configured a dark Theme for GTK Applications, but Xournal++ is always in light mode.(Snap)

Make sure you have the dark version of your theme installed for Snap apps: https://askubuntu.com/a/1147886

You may have to run `snap install gtk-theme-common`.

**Comment by ChrTall** [comment] 2021-12-12 20:18
@personalizedrefrigerator Thank you. I installed the app as a flatpak and now my theme is applied.
The only problem I have with the flatpak is that the icon of XournalPP is missing.

**Comment by rolandlo** [comment] 2022-01-21 07:45
Closing, since the issue is apparently solved.

**Closed by rolandlo** 2022-01-21 07:45 UTC
Labels: bug
