### ISSUE TITLE
Copied texts are pasted in reversed order

### ISSUE THREAD

**Issue by youngminpark2559** [xournalpp/xournalpp#3637] opened 2021-12-04 03:34 UTC
Hi, I'm running xournal++ of 1.1.0+dev built on Dec 1 2021 on Ubuntu 20.04.3 LTS
And I encountered this reversed pasted text problem from copied texts.
Thanks.

https://user-images.githubusercontent.com/30585126/144695560-76bf9953-d216-472b-a1e7-a0a5bdf62962.mp4

**Comment by bhennion** [comment] 2021-12-05 20:39
I can reproduce. It seems to be a regression. A build from October 24th (83c0c40f) does not have this bug on my machine (Archlinux).
@youngminpark2559 would you have time to bisect and figure out which commit broke this? If you don't know how, I'll do it when I find the time.

**Comment by youngminpark2559** [comment] 2021-12-05 22:39
@bhennion Umm, sorry, I don't have the ability to technically investigate which commit caused this problem in source code level. Please check this when you have the time.

**Comment by bhennion** [comment] 2021-12-06 02:53
Alright. The guilty commit is 0156eb6d2 that came in with #3042.
@Marmare314 @Febbe Do you know what's going on?

**Comment by bhennion** [comment] 2021-12-06 07:41
A fix is available in #3639. I will most likely be merged rapidly.

**Closed** 2021-12-06 18:18 UTC
Labels: bug, confirmed, regression
