### ISSUE TITLE
Stylus scrolls instead of drawing when inertial scroll is enabled

### ISSUE THREAD

**Issue by neldredge** [xournalpp/xournalpp#4044] opened 2022-05-22 06:21 UTC
**Affects versions :**
 - OS: Ubuntu 22.04 x86-64 using Xorg
 - Version of Xournal++: HEAD 0c2fd14ed5547b04346a758cf2f14533a29c7226 , also affects the official Ubuntu package 1.1.1-1

**Describe the bug**
Trying to draw with the stylus scrolls the screen instead of drawing.  

It only occurs when zoomed in far enough that scrolling is possible.  If zoomed out so the entire page is visible, drawing works normally.  If zoomed in so that the whole page fits horizontally but not vertically, then attempting to draw horizontal scribbles will draw normally, but trying to scribble vertically will scroll instead.

This only occurs with the GTK inertial scroll enabled; disabling it fixes the problem.

**To Reproduce**
1. Start xournalpp with no arguments, so that it starts with a blank page
2. Zoom in far enough that the entire page is not visible
3. Select pen tool
4. Try to draw with stylus

**Input Logs**
I'm not sure if these logs will be useful, since based on some debugger sessions, it seems like the offending scrolls don't go through the normal input event handling.  While the unwanted scrolls are happening, a breakpoint on `StylusInputHandler::handleImpl` is not hit.  Neither are `Layout::scrollRelative` nor `Layout::scrollAbs`.  But here they are anyway.

- [debug_input.log](https://github.com/xournalpp/xournalpp/files/8748858/debug_input.log)
- [debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/8748863/debug_gdk_input.log)
- [xinput-list.log](https://github.com/xournalpp/xournalpp/files/8748860/xinput-list.log)

**Expected behavior**
With pen tool selected, drawing with the stylus should make pen marks on the page, instead of scrolling.

**Screenshots of Problem**
Screenshots wouldn't show anything useful, but I could make a video if needed.

**Additional context**
The computer is a Dell Inspiron 5482 2-in-1 laptop, using the built-in touchscreen, with a Wacom Bamboo stylus.

The bug did not occur with Ubuntu 20.04; it began after I upgraded to 22.04.  I am not sure exactly what xournalpp version I was using on 20.04 though, I had built some custom versions so it may not have been the standard Ubuntu package.

I'm happy to investigate further, debug stuff, test patches, etc.  The bug is reliably reproducible on my system.

**Comment by rolandlo** [comment] 2022-05-27 05:36
Please post a screenshot of your settings in the input system panel of menu `Edit > Preferences`. It looks like your touchscreen device is not assigned correctly:

```
Event type:	GDK_MOTION_NOTIFY
Source device:	GDK_SOURCE_TOUCHSCREEN
Device Class:	INPUT_DEVICE_PEN
```

**Comment by neldredge** [comment] 2022-05-27 22:00
Input settings:
![input](https://user-images.githubusercontent.com/1840957/170794282-197cfdf3-f153-423d-a257-89d104cc9c61.png)

**Comment by rolandlo** [comment] 2022-05-28 21:20
@neldredge Your input settings look fine. Do you make these observations under Wayland or X11? I can reproduce the behavior (on Ubuntu 22.04), if I first use Xournal++ under Wayland (using touch and stylus, so the corresponding devices get recognized) and only later switch to the X11 backend by starting Xournal++ via `GDK_BACKEND=X11 xournalpp`.

Here are my configurations with first Wayland, then X11 backend
![first_wayland_then_x11](https://user-images.githubusercontent.com/40485433/170842193-8764de8f-c202-4cd6-a44b-b539531302e6.png)

The Wayland part are the four devices below. I can make the stylus work normally (with the X11 backend and these input devices on the list) by deactivating the `Wayland Touch` device.

What happens if you deactivate the `ELAN2097:00 04F3:324F` and/or the `DELL089E:00 06CB:CCA6 Touchpad` device in the settings actually?

The scrolling you are observing is probably coming from the kinetic scrolling by Gtk (that adjusts the values of the horizontal and vertical adjustment of the `ScrolledWindow`). 

I think turning off kinetic scrolling (at the bottom of the Touchscreen panel in the preferences) should fix your problem. You won't have kinetic scrolling any more though, so it gets harder to scroll through larger portions of a document.

**Comment by neldredge** [comment] 2022-05-28 21:46
Thanks, Roland.  This is with X11.

Disabling the `ELAN2097:00 04F3:274F (touchscreen)` device fixes the scrolling problem.  However, it has an odd side effect that if my hand touches the screen while drawing with the stylus, the stroke becomes intermittent, like a dotted line.

Disabling the touchpad has no effect on the issue.

Yes, disabling the inertial / kinetic scrolling does fix the problem (which I noted in the title :) ).  It also doesn't cause the dotted line behavior.  So it's a fine workaround for me, but a proper fix might still be nice someday.

**Comment by rolandlo** [comment] 2022-05-28 22:07
> Yes, disabling the inertial / kinetic scrolling does fix the problem (which I noted in the title :) ). It also doesn't cause the dotted line behavior. So it's a fine workaround for me, but a proper fix might still be nice someday.

Ups, I should read more carefully. 
The root of the issue lies in the fact, that Gtk thinks your stylus is a touchscreen. So a proper fix would come from Gtk. From Xournal++'s side we can only turn kinetic scrolling on or off (as far as I can see). It will be used for all devices, that Gtk recognizes as `GTK_TOUCHSCREEN`, see https://www.manpagez.com/html/gtk3/gtk3-3.14.9/GtkScrolledWindow.php#gtk-scrolled-window-set-kinetic-scrolling

**Comment by neldredge** [comment] 2022-05-28 22:46
Ah, thanks for the tip.  I found https://gitlab.gnome.org/GNOME/gtk/-/issues/4394 from which it seems that Gtk detects a stylus by the extremely sophisticated :) method of seeing if its name contains the strings `wacom`, `pen` or `eraser`. See https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/x11/gdkdevicemanager-xi2.c#L486.  Since mine contains `stylus` instead, it gets skipped.  So it would be an easy patch, but maybe I'll play around and see if I can change the name or do something else that won't require recompiling gtk.

Thanks again for the help!  You can feel free to close this issue, I'll post back with whatever else I learn.  Maybe it will help some future xournal++ user with a similar issue.

**Comment by neldredge** [comment] 2022-05-29 03:52
You were right.  I patched gtk to recognize `stylus` as a pen, and now everything works properly with the inertial scroll enabled.
```
Description: recognize a stylus device as a pen
Author: Nate Eldredge <nate@thatsmathematics.com>
Index: gtk+3.0-3.24.33/gdk/x11/gdkdevicemanager-xi2.c
===================================================================
--- gtk+3.0-3.24.33.orig/gdk/x11/gdkdevicemanager-xi2.c
+++ gtk+3.0-3.24.33/gdk/x11/gdkdevicemanager-xi2.c
@@ -453,6 +453,7 @@ create_device (GdkDeviceManager *device_
       else if (strstr (tmp_name, " pad"))
         input_source = GDK_SOURCE_TABLET_PAD;
       else if (strstr (tmp_name, "wacom") ||
+	       strstr (tmp_name, "stylus") ||
                strstr (tmp_name, "pen"))
         input_source = GDK_SOURCE_PEN;
       else if (!strstr (tmp_name, "mouse") &&
```

**Comment by rolandlo** [comment] 2022-05-29 04:59
Ok, so my `xwayland-tablet stylus:16` is affected by the same Gtk bug. Fixing that in Gtk is really the way to go. Are you planning to make a merge request for Gtk (or push for one)?
I will leave the issue open until the bug is fixed in Gtk. Otherwise we will get new reports of the same issue and have nothing to refer to.

**Comment by neldredge** [comment] 2022-05-29 23:38
I made a merge request: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4776.  It may eventually need a separate one for GTK3, I'm not sure if they would automatically consider a backport.

**Comment by rolandlo** [comment] 2022-12-31 16:47
Gtk 3.24.35 contains a fix (thanks to @neldredge), so we will only have to wait for it to land in our distro. I'm closing the issue therefore.

**Closed by rolandlo** 2022-12-31 16:47 UTC
Labels: bug, confirmed, Input
