### ISSUE TITLE
In metadata of PDF-files created by Xournal++ the "Creator" field is empty.

### ISSUE THREAD

**Issue by rbarte** [xournalpp/xournalpp#4497] opened 2022-12-11 17:09 UTC
**Affects versions :**
 - OS: Fedora Linux 37
 - (Linux only) Desktop environment: Gnome-Wayland
 - [Which version of libgtk do you use] libgtk: 3.24.35
 - Version of Xournal++: 1.1.3
 - Installation method: official rpm package installed with the dnf tool

**Describe the bug**
In metadata of PDF-files created by Xournal++ the "Creator" field is empty. 

**To Reproduce**
1. Create a new document.
2. "File" -> "Export as PDF".
3. Open a file with any pdf-viewer and see the properties or check them with a tool like pdfinfo. In the "Creator" does not show up.

**Expected behavior**
The PDF file is created using Xournal++ and this should be stated in PDFs metadata.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
Screenshot from Adobe Acrobat:
![image](https://user-images.githubusercontent.com/31691084/207027426-23bd3414-2d4d-42e3-8d85-88e0324ccad3.png)

**Additional context**
Stating that the creator is "Xournal++" would also be important from marketing point of view. So that the receivers of the PDF could check in which tool it was created.

**Comment by Technius** [comment] 2022-12-12 08:19
I can't reproduce on:
* Xournal++ 1.1.3 running on NixOS 22.11, using Cairo 1.16.0. Running `pdfinfo <path_to_pdf>` shows `Creator: xournalpp 1.1.3` and `Producer: cairo 1.16.0`.
* Xournal++ nightly (commit `81ca4db4`) running on macOS, using Cairo 1.17.6. The Creator field  of the PDF file shows as "xournalpp 1.1.3".
  <details>
  <summary>Here's what I see on macOS (click to show)</summary>

  ![image](https://user-images.githubusercontent.com/1066652/206995083-dc669f55-c4ba-4f20-b79a-d8313d35fff8.png)
  </details>

The "Creator" metadata field is set to "xournal++ (version)" in the following line of code, so it seems strange that the field doesn't isn't in your exported PDF: https://github.com/xournalpp/xournalpp/blob/81ca4db4aabbb19c5c3ecd771f9d9185d20f3bb9/src/core/pdf/base/XojCairoPdfExport.cpp#L52

**Comment by rolandlo** [comment] 2022-12-18 10:08
I can confirm the issue (empty Creator field) with Xournal++ 1.1.2 on Windows. With the current nightly build (and the same xopp-file) the Creator field is correct (`xournalpp 1.1.3+dev`).
The Creator field was added in b45e5e064bb2d61d771feb5bad5ea823aef1f8fb and merged on Oct 30 2021 into master. 
I'm closing the issue therefore.

**Closed by rolandlo** 2022-12-18 10:08 UTC
Labels: bug, PDF
