### ISSUE TITLE
Ctrl+G dialog is not usable

### ISSUE THREAD

**Issue by flyasky** [xournalpp/xournalpp#975] opened 2019-03-10 14:50 UTC
I'm drawing over long pdf. When I try to go to any page by Ctrl+G dialog  it opens  first page in document.

**Comment by andreasb242** [comment] 2019-03-10 14:52
I can not reproduce this - please try to describe the issue better. As long as we cannot reproduce this, we can not fix it...

**Comment by flyasky** [comment] 2019-03-10 15:00
1. Open any page in document
2. Gtrl+G and put number of any other page
3. Press Enter
4. You moved on first page (if Ok button used it will moves right)

**Comment by andreasb242** [comment] 2019-03-10 15:02
Ok, Enter is not working, but OK is. this was the Information I needed.

**Comment by Technius** [comment] 2020-02-05 06:15
This was fixed by #1678.

**Closed by Technius** 2020-02-05 06:15 UTC
Labels: PR available, bug, confirmed, difficulty:easy, good first issue, priority: high
