### ISSUE TITLE
Mouse wheel not scrolling

### ISSUE THREAD

**Issue by failingapbio** [xournalpp/xournalpp#4431] opened 2022-11-20 21:01 UTC
Hi,
I use Xournalpp 1.1.2 on MacOs Catalina
Mouse wheel doesn't scroll on the document. Mouse wheel only scrolls when mouse in on the scroll bar on the right of the window.
What I expect: scroll up and down when I use mouse wheel in the document. Bug or bad configuration?

Affects versions : 1.1.2
Mac

To Reproduce
Open Xournal++ and scroll on a PDF. It doesn't scroll unless the cursor is on the bar.
Expected behavior
Open Xournal++ and scroll on a PDF. It should scroll all the time when the cursor is on the page.

**Comment by Technius** [comment] 2022-11-20 21:31
I can confirm this on Monterey as well, not sure what causes this. There is only one input device reported ("Quartz device"), which was set to Pen by default for me. Changing the device type to mouse does not fix the issue.

**Comment by TheMathGuyd** [comment] 2022-12-25 22:03
Just here to confirm that this is still a bug in Ventura. Scrolling does nothing

**Comment by MahdeenSky** [comment] 2023-03-08 02:40
Has this been resolved? This is quite the problem.

**Comment by hnykda** [comment] 2023-03-09 10:17
Confirm the same on Ventura.

**Comment by advaypakhale** [comment] 2023-03-29 18:17
I can confirm the same issue on Monterey. I'm on the Mar 19 nightly build.

I'm using a Wacom Intuos S tablet, which shows up as "Quartz Pen" and "Quartz Eraser" in the input devices settings.

The trackpad doesn't work for scrolling, neither does attaching an external mouse with a scroll wheel help. I scoured the preferences to see if I was missing anything; I haven't seen any relevant settings, however. I could be entirely wrong.

The only way to scroll is either to use the arrow keys, or to manually click and drag the scroll bar. After doing the latter and attempting to write, the first few strokes are still registered as moving the scroll bar, which causes the page to jump erratically.

As someone who uses the trackpad extensively to zoom in and position my cursor while writing, this issue is rendering the program basically unusable. I would greatly appreciate it if this issue could be fixed or if a change to the default preferences is suggested. Thanks.

**Comment by Technius** [comment] 2023-04-16 22:36
Is everyone affected using Apple Silicon? The nightly build is compiled an on x86 machine and therefore is run using Rosetta 2. Scrolling does not work with the nightly build. However, when I manually compiled Xournal++ on my Mac M1 device, scrolling does work.

**Comment by MahdeenSky** [comment] 2023-04-16 22:56
> 

Yeah, I'm on an M1, could you provide the manually compiled Xournal? My cmake fails while doing so.

**Comment by CodeforEvolution** [comment] 2023-04-29 19:05
I can confirm this was an issue for macOS Catalina, and when I updated macOS Ventura, it is still a problem too. I'm using an old Mid-2012 MacBook Pro in combination with a XP-Pen Deco Fun L tablet. I also only have the Quartz Pen & Quartz Eraser options show up in the Xournal input devices settings.

I have reason to believe this is more of an issue with GTK's handling of input devices on macOS than a Xournal specific issue, at least after a quick look at the code of the Quartz backend of GTK. The backend registers input devices as they are used, and default mouse and keyboard handling seems to look off...

**Comment by DFranzen** [comment] 2023-05-08 12:06
I can also confirm this issue on Intel silicon Macs. I am using xournal++ without a stylus or touch input device and I do not see any input devices in the preferences (not even a Quartz device).
One detail to add here: the Ctrl+Scrollwheel does zoom correctly and the click of the wheel correctly acts as Button 3 for selecting the configured 3rd button tool. The only input not working is the scrolling of the wheel without Ctrl.

**Comment by lcalder** [comment] 2023-05-09 06:10
Actually, I was able to fix the Command+Scroll Wheel problem on MacOS. It didn't work before because the OS already had Cmd+MouseWheel assigned to zoom my entire screen at the OS level, so it was not available for Xournal. Just go into System Settings->Accessibility->Zoom and change the modifier key from Command to Option and Xournal will be able to zoom using the Cmd+Mouse Wheel.
![SCR-20230508-tybk](https://user-images.githubusercontent.com/50305507/237008406-29204d79-106c-444d-832f-2798a9149bc3.png)
![SCR-20230508-tybk](https://user-images.githubusercontent.com/50305507/237009084-066df1c2-b344-404a-92b3-c8359ceed0ae.png)

**Comment by advaypakhale** [comment] 2023-07-10 12:51
I found a cheap workaround for the scrolling issue. I usually use the trackpad extensively while writing to zoom in and pan around while writing (handwriting looks better that way).

If you go into Preferences > Right Mouse Button and change it to the hand tool, you can now regain _some_ scrolling functionality. The only downside is that you have to hold right-click (two fingers on most Macs), but I got used to it fairly quickly. After releasing the right click, the previously selected tool gets auto-selected, so you can go right back to writing/whatever. It isn't the most smooth experience, but at least it has made the program usable for my use case.

The only issue I have yet to fix is the really jarring and jumpy pinch-and-zoom experience. If anyone has any ideas regarding how to make the pinch-zoom more smooth, that would be much appreciated. Hope this helped.

**Comment by Doublonmousse** [comment] 2024-03-13 16:03
Works fine now with version 1.2.3

**Closed** 2024-10-21 02:58 UTC
Labels: bug, os::mac, confirmed
