### ISSUE TITLE
Can't scroll or jump to next page anymore

### ISSUE THREAD

**Issue by dinojr** [xournalpp/xournalpp#2634] opened 2021-01-08 08:18 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: Gnome-Wayland, XWayland
 - Which version of libgtk do you use 3.24.20
 - Version of Xournal++: 1.1.0+dev latest nighly as of 08/01
 - Installation method: nightly ppa

**Describe the bug**
Can't navigate pages 

**To Reproduce**
1. Create a second page,
2. Neither scrollbar, nor next page menu item nor next page/last page buttons takes you to the second page

**Comment by LeRue** [comment] 2021-01-08 08:31
Same for me here. But

- I can scroll even though
- I can only see the the topmost view. Once I scroll new things that should appear are greyed out.

**Comment by Fef0** [comment] 2021-01-08 08:42
I confirm that.
@personalizedrefrigerator maybe it's after the yesterday regression fix?
I tried to enable touchscreen but it still doesn't work and I can't even scroll with the pen and the hand tool.

**Comment by Fef0** [comment] 2021-01-08 08:51
@personalizedrefrigerator I recompiled back to commit 1398290d and it works as expected, so it's probably due to 04f038913730a79f90ec098870e1966e5ca03360 or a29b11d5bc7c67769fcce46f487dde845a67d0d6 by @Febbe and @rolandlo

**Comment by rolandlo** [comment] 2021-01-08 09:22
@Fef0 Would you please try out PR #2633 ?

**Comment by Fef0** [comment] 2021-01-08 09:39
@rolandlo I can't right now, I will in a few hours and I'll let you know

**Comment by rolandlo** [comment] 2021-01-08 09:40
I will merge it then.

**Comment by arv-pyrna** [comment] 2021-01-08 11:14
yes please xournalpp is unusable anymore! i have the whole semester of lecture notes in xournalpp. Now i can't see them anymore ( how can i roll back to previous working version ? I use latest ubuntu 20.10

**Comment by rolandlo** [comment] 2021-01-08 11:31
@arv-pyrna We are sorry for breaking things. You can either wait for roughly 12 hours (maybe a bit more, but certainly less than a day) until the PPA has a new build, or build from source as explained in the [Wiki](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md), or use version 1.0.20 for a day (through the [snap](https://snapcraft.io/xournalpp) or [flatpak](https://flathub.org/apps/details/com.github.xournalpp.xournalpp), if you don't see it from the software center). Would any of these options be fine for you?

**Comment by arv-pyrna** [comment] 2021-01-08 11:44
Thanks for the reply @rolandlo. I just installed 1.0.20 from the releases. It is working fine!  but i lost the saved settings. Is it possible to restore them ? The main thing i need is the small black dot that specify the stylus position. now, i see only mouse cursor instead of it. I got into the habit of writing with that black dot. Well, its a minor thing but I would really appreciate if there is a way to get it back.

**Comment by rolandlo** [comment] 2021-01-08 11:54
Settings for Xournal++ 1.1.0+dev and Xournal++ 1.0.20 are not identical, so you can't just copy. You should just activate the new input system, I think (input system panel in menu Edit->preferences).

**Comment by arv-pyrna** [comment] 2021-01-08 12:10
This is exactly what i needed! Big thanks @rolandlo!

**Comment by Fef0** [comment] 2021-01-08 16:20
@arv-pyrna you should use nightly builds only if you want to experiment with Xournalpp or you need specific beta functionalities in order for your setup to work. Once you get those specific functionalities, than stop upgrading. If you need a stable system, just download a stable version and go safe with that, mistakes can happen and nightly builds are there for us to try them and check if everything works as expected.

**Comment by Fef0** [comment] 2021-01-08 16:21
@rolandlo I confirm that it works with the latest commit, thank you.

**Comment by arv-pyrna** [comment] 2021-01-08 16:38
> uld use nightly builds only if

Yes you are right, when i first installed xournal in my machine, i was tracking ppa of xournal-master repo by mistake. Since nothing broke so far i never realized that i was tracking experimental build :). 

Now I replaced xournal-stable repo.

**Comment by rolandlo** [comment] 2021-01-08 23:22
The PPA has now been updated. Just `sudo apt update && sudo apt upgrade` to get rid of this bug.

**Comment by rolandlo** [comment] 2021-01-11 07:10
I will close this issue now, since it has been fixed.

**Closed by rolandlo** 2021-01-11 07:10 UTC
Labels: bug
