### ISSUE TITLE
MACOS Sonoma 14.1.1 all file navigation dialogs become unresponsive. Only real way to load a file is from the Apple Finder now.

### ISSUE THREAD

**Issue by lcalder** [xournalpp/xournalpp#5347] opened 2023-11-18 09:19 UTC
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

Copied to /Applications folder

### Xournal++ Version

1.2.2+dev

### libgtk Version

3.24.38

### Bug Description

Try to use File->Open or anything that uses the file browser such as relocating a missing pdf, etc.
The file browser dialog will open. Clicking to go to a different folder just causes a major hang, with the wait wheel just spinning for minutes at a time. You might be able to navigate to another folder 1% of the time if you wait for 10 minutes between clicks. 99% of time you will have to force quit.

### Expected Behaviour

Usual snappy navigation around folders in the file browser as always. Just updated to Sonoma 14.1.1 from 14.0 and the above problems started...

### Steps to Reproduce

Launch Xournal++
Try to open a file...
Maybe try to go up to parent folder...

**Comment by rolandlo** [comment] 2024-04-29 19:28
I can't reproduce the issue with the ARM build from https://cirrus-ci.com/task/5138787729145856
Give it a try if you can.

**Comment by eMerzh** [comment] 2024-05-16 18:38
@rolandlo on my M2 14.4.1 o have the same responsivness issues
probably also related to #4799 ... but the app in the dmg is reported as broken

**Comment by rolandlo** [comment] 2024-05-16 18:40
For the app in the dmg you need to remove the quarantine as indicated in https://github.com/xournalpp/xournalpp/issues/5643#issuecomment-2083480167

**Comment by eMerzh** [comment] 2024-05-16 18:41
yes sorry for the noise... I did it, it seems waaay better 👍

**Comment by rolandlo** [comment] 2024-10-21 02:46
An ARM build for MacOS was released with version 1.2.4. Closing this issue therefore.

**Closed by rolandlo** 2024-10-21 02:46 UTC
Labels: bug, os::mac
