### ISSUE TITLE
Be able to fill out fillable forms

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#4076] opened 2022-06-07 20:22 UTC
**Is your feature request related to a problem? Please describe.**
If a PDF is fillable, I should be able to fill it out.

**Describe the solution you'd like**
Be able to fill out PDFs
**Describe alternatives you've considered**

**Additional context**
This might be very hard, bordering on impossible without a lot of work.

**Comment by Technius** [comment] 2022-06-08 02:31
Duplicate of #3147.

**Closed by Technius** 2022-06-08 02:31 UTC
Labels: enhancement, PDF
