### ISSUE TITLE
Keyboard Shortcut for Everything

### ISSUE THREAD

**Issue by Fatih20** [xournalpp/xournalpp#1906] opened 2020-04-26 01:15 UTC
**Is your feature request related to a problem? Please describe.**
The lack of keyboard shortcut hinders a lot of people's productivity (including me)

**Describe the solution you'd like**
Users should be able to assign keyboard shortcut to every action and every tool. Just like GIMP and Inkscape.

**Comment by Technius** [comment] 2020-04-26 04:59
Duplicate of #919.

**Closed by Technius** 2020-04-26 04:59 UTC
Labels: enhancement
