### ISSUE TITLE
SegFault in Palette::getColorAt()

### ISSUE THREAD

**Issue by anutator** [xournalpp/xournalpp#4940] opened 2023-06-21 17:45 UTC
Linux Pop_OS 
```bash
Date: Tue Jan  3 18:50:27 2023
Error: signal 11
[bt]: (0) xournalpp(+0xb9c28) [0x5558fb7ebc28]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f475be42520]
[bt]: (2) xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x5558fb832fdb]
[bt]: (3) xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xc3f) [0x5558fb82c5cf]
[bt]: (4) xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x5558fb81b689]
[bt]: (5) xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbb) [0x5558fb81ba5b]
[bt]: (6) xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x8eb) [0x5558fb81cb8b]
[bt]: (7) xournalpp(+0xbc4a4) [0x5558fb7ee4a4]
[bt]: (8) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f475c945d2f]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f475c961c36]
[bt]: (10) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f475c963614]
[bt]: (11) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f475c963863]
[bt]: (12) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x241) [0x7f475caa1421]
[bt]: (13) /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe0b8e) [0x7f475caa1b8e]
[bt]: (14) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x136) [0x7f475caa1f46]
[bt]: (15) xournalpp(_ZN11XournalMain3runEiPPc+0x5df) [0x5558fb7e9bff]
[bt]: (16) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f475be29d90]
[bt]: (17) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f475be29e40]
[bt]: (18) xournalpp(_start+0x25) [0x5558fb7e7e25]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0xba0cd) [0x5558fb7ec0cd]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f475be42520]
??:0
[bt] #3 xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x5558fb832fdb]
??:0
[bt] #4 xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xc3f) [0x5558fb82c5cf]
??:0
[bt] #5 xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x5558fb81b689]
??:0
[bt] #6 xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbb) [0x5558fb81ba5b]
??:0
[bt] #7 xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x8eb) [0x5558fb81cb8b]
??:0
[bt] #8 xournalpp(+0xbc4a4) [0x5558fb7ee4a4]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x16f) [0x7f475c945d2f]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x30c36) [0x7f475c961c36]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x11a4) [0x7f475c963614]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f475c963863]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x241) [0x7f475caa1421]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe0b8e) [0x7f475caa1b8e]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x136) [0x7f475caa1f46]
??:0
[bt] #16 xournalpp(_ZN11XournalMain3runEiPPc+0x5df) [0x5558fb7e9bff]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f475be29d90]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f475be29e40]
??:0
[bt] #19 xournalpp(_start+0x25) [0x5558fb7e7e25]
??:0
```

**Comment by bhennion** [comment] 2023-08-08 16:20
Thanks for reporting. Could you elaborate a little bit: what where you doing when this happened?

**Comment by bhennion** [comment] 2023-08-21 08:33
Duplicate of #4997

**Closed by bhennion** 2023-08-21 08:33 UTC
Labels: bug, need info, Crash
