### ISSUE TITLE
Uninstall Xournalpp doest not work

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#4048] opened 2022-05-25 06:27 UTC
OS : Windows 10
Xournalpp version : May 22 2022

Uninstall program of xournalpp does not work. Files of xournalpp are not delete

**Comment by Technius** [comment] 2022-05-30 19:21
This is caused by #4041.

**Comment by Technius** [comment] 2022-06-05 21:25
Should be fixed by #4062 which will be merged in #4073.

**Closed** 2022-06-13 06:40 UTC
Labels: bug, os::windows, Crash
