### ISSUE TITLE
Accessing Documents/Downloads folders on macOS 10.15

### ISSUE THREAD

**Issue by DekunSong** [xournalpp/xournalpp#2671] opened 2021-01-16 11:58 UTC
**Affects versions :**
 - OS: macOS Catalina (10.15.7)
 - Version of libgtk: 3.24.10 
 - Version of Xournal++: 1.0.20
 - Installation method: official release

**Describe the bug**
Cannot access folders such as $HOME/Downloads $HOME/Documents or $HOME/Desktop, even though Xournal++ has been granted "full disk access" in System Preferences' Security & Privacy settings.

**To Reproduce**
1. Click "Open" in the menu.
2. Select "Document" or "Desktop" option from the sidebar.

**Expected behavior**
An error message: "Could not read the contents of (folder name) Error opening directory $HOME/(folder name): Operation not permitted"

**Comment by Technius** [comment] 2021-01-20 19:36
Duplicate of #1757.

**Closed by Technius** 2021-01-20 19:36 UTC
Labels: bug
