### ISSUE TITLE
Text spaciing changes on export to PDF

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#1390] opened 2019-08-02 16:16 UTC
**Affects versions :**
 - OS: Linux
 - Version of Xournal++ current master (Latest commit a6276cd)

**Describe the bug**
The spacing of text entered using the "text" tool changes on export to PDF. See attached xournal file, and the resulting pdf. Note that the numbers are on either side of the lines in the xournal file, but no longer in the PDF. 

**To Reproduce**
Draw vertical lines with pen. Open text box, write numbers interspaced with spaces over each line. Export to PDF. See how numbers no longer align with lines. 

See attached files (zipped because .xopp upload not allowed): [textAndLines.zip](https://github.com/xournalpp/xournalpp/files/3462124/textAndLines.zip)

**Expected behavior**
PDF looks like xournal file.

**Comment by Technius** [comment] 2019-08-03 23:27
Do you know if this only affect text, or does it affect other objects such as images and latex?

**Comment by markwmuller** [comment] 2019-08-04 00:08
I only noticed with text, it came up because I was typing data into a PDF.

**Comment by Technius** [comment] 2019-10-23 07:15
This may be caused by changing DPI scaling without restarting the application. Does this occur if you open Xournal++, load the file, and then export the PDF without changing DPI settings?

**Comment by Technius** [comment] 2019-10-23 20:37
Interestingly enough, I can't reproduce this if I follow your steps.

But if I open the file you provided, I see the following in Xournal++:
![image](https://user-images.githubusercontent.com/1066652/67431647-93cd0880-f599-11e9-8e0e-3267bb791bcf.png)

Can you also insert an image and see if the problem persists? I want to make sure this issue is limited only to text before trying to figure it out. I suspect that system DPI scaling may be affecting Pango (which we use to render text).

**Comment by markwmuller** [comment] 2019-10-23 23:30
See attached. 

Image seems OK, text still odd. Confusingly, it worked OK the first time I tried it, then I rebooted and created a new file (which has original issue)
[spacing_img.zip](https://github.com/xournalpp/xournalpp/files/3764956/spacing_img.zip)

Here's the time it worked OK, in case you can diagnose something from that:
[GRID.zip](https://github.com/xournalpp/xournalpp/files/3764965/GRID.zip)

**Comment by new-on-github** [comment] 2020-04-02 12:19
Same problem here:
Build 1.1.0 dev from 31.03.2020

Don't know why, but the I think the text changes his stretching/size and the drawing stays the same.

By the way: Thanks for this amazing free software!

**Comment by rickhg12hs** [comment] 2020-04-19 22:00
I see the same behavior.  (xounrnalpp built from GitHub master at 86aa7e5c98e25e9725454496c28afddc2aef1caf, Fedora 29, x86_64)

With a PDF background in xournalpp and added (and scaled) Text (in light blue):
![Screenshot from 2020-04-19 23-54-17](https://user-images.githubusercontent.com/6000188/79700914-2d4f4b80-8299-11ea-9ed8-48ec0ec06680.png)

and the exported PDF:
![Screenshot from 2020-04-19 23-56-31](https://user-images.githubusercontent.com/6000188/79700946-87e8a780-8299-11ea-92d8-f97eca48889c.png)

**Comment by rolandlo** [comment] 2021-03-10 20:27
Currently the way to get the least difference between xopp-file text spacing and exported pdf-file text spacing can be obtained by increasing the font size in small steps inside Xournal++ such that the line spacing remains exactly the same in the xopp-file (while the horizontal space it takes increases), but increases in the exported pdf.

For example Sans Regular 20, 20.1, 20.2, 20.3, 20.4 up to 20.47 are all perfectly aligned to the lines of the Ruled background in the xopp-file. In the export Sans Regular 20 has quite a bit smaller line spacing, whereas Sans Regular 20.47 is almost aligned to the lines. See here:
![grafik](https://user-images.githubusercontent.com/40485433/110693015-46315a00-81e7-11eb-8801-ea6f39d957c5.png)

To reproduce:
[lineSpacing_SansRegular_20-x.zip](https://github.com/xournalpp/xournalpp/files/6118659/lineSpacing_SansRegular_20-x.zip)

**Comment by mjg** [comment] 2021-04-27 10:30
I'm somewhat confused by this report. There is:
- the issue with horizontal spacing (width of spaces) being different onscreen vs. PDF
- the issue with line spacing being independent of font size up to a certain size onscreen (but correct in PDF, thus different)
How are they related?
(I do understand that the empty line issue is related to  a possible fix for the line spacing.)

**Comment by rolandlo** [comment] 2021-04-27 10:39
>     * (I do understand that the empty line issue is related to  a possible fix for the line spacing.)

The relation is as follows: The vertical line spacing is correct onscreen when using 
```c++
pango_layout_set_line_spacing(layout, 1.0);
```

(which is only available in pango>=1.44). However using it would introduce a new bug where empty lines don't contribute to the text height. 

About the horizontal spacing I'm not sure how that is related. That would have to be checked again with different pango versions.

**Comment by mjg** [comment] 2021-04-27 13:57
> > ```
> > * (I do understand that the empty line issue is related to  a possible fix for the line spacing.)
> > ```
> 
> The relation is as follows: The vertical line spacing is correct onscreen when using
> 
> ```c++
> pango_layout_set_line_spacing(layout, 1.0);
> ```
> 
> (which is only available in pango>=1.44). However using it would introduce a new bug where empty lines don't contribute to the text height.

That's the part I understood... I even looked at the pango code and scratched my head, wondering how other programs use it to produce reliable text layout.
 
> About the horizontal spacing I'm not sure how that is related. That would have to be checked again with different pango versions.

So it's not clear if it's related, but the "view on screen" codepath uses a different library from the "export to PDF" codepath, right? (Just trying to see if I can help with any release blockers.)

**Comment by rolandlo** [comment] 2021-04-27 14:16
Both "view on screen" and "export to PDF" use `Cairo` for rendering and `Pango` for text layout. Moreover "export to PDF" uses `Poppler` to deal with PDF's. 
By the way the `Inkscape` code doesn't use `pango_layout_set_line_spacing`. They somehow compute the text layout with different (and quite sophisticated) means.

**Comment by mjg** [comment] 2021-04-27 19:43
So, the 20pt xopp in `lineSpacing_SansRegular_20-x.zip` has text which lines up with the paper ruling when viewed in xournalpp but shouldn't if I understand correctly; the PDF output  has the correct smaller line spacing.
Interestingly, SVG comes out the same ways as PDF, whereas a PNG output looks like the xournalpp view.

At 20.47pt xournalpp view and PNG look exactly the same as at  20pt (in terms of line spacing), whereas SVG and PDF almost line up with the paper ruling now.

Somehow, some of these codepaths must involve setting the line spacing to the natural line spacing for the font whereas others use a default line spacing.

Also, onscreen, the line spacing "jumps" if you go from 19.99 to 20. I tend to think there is some hidden float to int and back at play...

**Comment by rolandlo** [comment] 2021-04-27 19:56
Related issue: https://gitlab.freedesktop.org/cairo/cairo/-/issues/426 (referring to https://gitlab.gnome.org/GNOME/pango/-/issues/506)

**Comment by rolandlo** [comment] 2021-06-13 21:16
Fixed by PR #2182.

**Closed by rolandlo** 2021-06-13 21:16 UTC
Labels: PR available, bug, confirmed, priority::high
