### ISSUE TITLE
Text area with fixed width, and alignment options (center…)

### ISSUE THREAD

**Issue by tobiasBora** [xournalpp/xournalpp#4708] opened 2023-03-09 15:54 UTC
First, thanks a lot for this great software.

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I'm typing a multiline text: in order to make it go to the line, I need to manually add newlines otherwise it will go out of the page. Therefore, if I need to add stuff on the first line after writting 10 lines, I need to change the position of my newlines. It would be nice also to be able to align the text (center/left/right). 

I'm quite surprised that nobody reported that before, so I might just missed the right option.

**Describe the solution you'd like**

Do like most text editors (libreoffice…): let the user first draw the text area (or at least fix the width, the height may extend arbitrarily), and make the text horizontally fit in this area.

**Describe alternatives you've considered**
Manually adding newlines… a headache to maintain.

**Comment by rolandlo** [comment] 2023-03-09 16:00
Duplicate of #2033. See also #1756 and #1092.

**Closed by rolandlo** 2023-03-09 16:00 UTC
Labels: enhancement
