### ISSUE TITLE
Windows: text tool does not enter non-English text for some IMEs

### ISSUE THREAD

**Issue by hyy6302** [xournalpp/xournalpp#1997] opened 2020-05-19 13:40 UTC
**Affects versions :**
 - OS: [Windows10]
 - Which version of libgtk do you use：I don't know，I just a user .
 - Version of Xournal++: [1.0.18]
 - Installation method: [Directly click software installation /windows直接点击exe格式安装软件]

**Describe the bug**
When I click on the text, the text box and the cursor appear, and when I type the text, the text box doesn't show anything. That means  ，you cannot enter text directly.
当我点击文本时，出现了文本框及光标，当我输入文字时，文本框没有任何显示。简单来说，不能直接输入文字。

**To Reproduce**
1. click  the text
2. type the text
3. nothing on  the text box

**Expected behavior**
The text box will show what I type . 
文本框会显示我键盘输入的文字内容.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/65583494/82332444-f98e4f80-9a17-11ea-928e-bd949f8f305a.png)

**Additional context**
中文英文阿拉伯数字都不能输入，我尝试下载Xournal  “pick a font ”里面显示的字体并安装在我自己的电脑，但是也没有解决这个问题。
Chinese 、 English、 Arabic numerals cannot be input .I tried to download the font displayed in Xournal "pick a font" and install it on my own computer, but this problem was not solved

**Comment by Technius** [comment] 2020-05-19 17:47
* Do you have the new input system enabled?
* Are you using a combined wireless mouse+keyboard combo?

**Comment by hyy6302** [comment] 2020-05-20 04:44
1. I used sogou input method without adding a new input system. I tried to use other input methods of the system, but the problem was still not solved.
2. Yes, I'm using a wireless mouse and keyboard. But when I tried to use the laptop's original keyboard, the problem remained.

1.我使用的是搜狗输入法，并没有另外添加新的输入系统，我尝试了使用系统的其他输入法，问题仍然没有解决；
2.是的，我正在使用无线鼠标键盘。但是当我尝试使用笔记本原有的键盘时，问题依然存在。

**Comment by Technius** [comment] 2020-05-20 05:01
Sorry, by "new input system," I meant whether you had this setting enabled:
![image](https://user-images.githubusercontent.com/1066652/82406721-38260900-9a1c-11ea-9ea3-34674d161cf2.png)

**Comment by hyy6302** [comment] 2020-05-20 05:46
Oh，sorry，I see . I haven't setting it ，but I tried to set it and restart xournalpp just now，something wrong，the text box disappeared, and when I typed，the software crashed.

**Comment by boffi** [comment] 2020-05-29 13:58
I have the same issue, I'll try to report here.

No text input when I use my additional keyboard.

My laptop keyboard is slightly faulty ('w', '3' and '4' keys work intermittently) so I use a [Logitech K400](https://www.logitech.com/en-us/product/wireless-touch-keyboard-k400r) that is connected via radio to a Logitech USB dongle and I'd like to use it instead of the laptop's one.

I checked in the Preferences - Input System and my configuration is as seen in the screenshot below - please note that I can't inform xournalpp that my keyboard is a keyboard...

Note that the Unifying Device (the radio gizmo) is also, incorrectly, reported as a mouse.

![Screenshot from 2020-05-29 15-55-11](https://user-images.githubusercontent.com/2244221/83267821-0e5fa580-a1c5-11ea-9fbd-29caedea8fb9.png)

**Comment by LittleHuba** [comment] 2020-05-29 14:24
You'll have to update Xournal++ to a newer version and choose the Mouse + Keyboard combo

**Comment by boffi** [comment] 2020-05-30 11:07
OK, I'll wait for Debian to update, it's not a critical issue...
Thank you

**Comment by Febbe** [comment] 2020-05-30 11:12
You could just disable the keyboard, but if it's also mouse it will deactivate the mouse. This is fixed in a newer version.

**Comment by qf-chen** [comment] 2020-06-07 13:22
I also meet the same problem. I think it's related to the input system of windows. When the English keyboard was activated, it was possible to type into the software. When a Chinese input method was activated, it was impossible to type into the software. Copy & paste Chinese characters into the text box works.

**Comment by LittleHuba** [comment] 2020-06-07 13:33
> I also meet the same problem. I think it's related to the input system of windows. When the English keyboard was activated, it was possible to type into the software. When a Chinese input method was activated, it was impossible to type into the software. Copy & paste Chinese characters into the text box works.

No here it is actually one level deeper. Keyboards are just ignored globally if they are selected as mouse within the input sytem.

**Comment by qf-chen** [comment] 2020-06-07 16:13
> 
> No here it is actually one level deeper. Keyboards are just ignored globally if they are selected as mouse within the input sytem.

I think you may point out the cause of the problem. The software communicates with keyboard directly causes the problem. For Chinese character input, there is a translation layer called input method, which translate keyboard codes to characters. Software should communicate with the input method instead of the keyboard to obtain the correct input.

**Comment by LittleHuba** [comment] 2020-06-07 19:04
That is actually what GTK should do for us. But in your case does not.

**Comment by qf-chen** [comment] 2020-06-08 00:49
I though GTK should support input method out of box in standard text box. For example, in the search box of the font peaking dialog, math tex input dialog (although it wouldn't render the characters in the output formula), autosaving box in preferences, etc., input method works without any problem, and Chinese characters can be input correctly.
![image](https://user-images.githubusercontent.com/66557374/83983812-fe358c00-a963-11ea-93f1-e1ef0cd06570.png)

**Comment by Technius** [comment] 2020-06-08 05:15
> I though GTK should support input method out of box in standard text box. For example, in the search box of the font peaking dialog, math tex input dialog (although it wouldn't render the characters in the output formula), autosaving box in preferences, etc., input method works without any problem, and Chinese characters can be input correctly.

This is really useful information. The text tool uses the GTK IME API, so maybe it's not using it correctly (at least on Windows).

**Comment by qf-chen** [comment] 2020-06-10 07:16
No, I did not meet crash.

**Comment by Dapao734** [comment] 2020-11-01 00:18
Has the problem been solved？
I also encountered this situation

**Comment by Voladorwoo** [comment] 2021-03-24 08:19
Has the problem been solved？
I also encountered this situation  on Mac

**Comment by Technius** [comment] 2021-09-16 01:04
I'm guessing that the Windows build that we produce isn't including the proper input method libraries. I'll investigate to see if this is actually the case.

**Comment by Technius** [comment] 2021-09-16 05:21
The actual issue was that the input method was not initialized correctly. This bug should be fixed in #3402.

**Closed** 2021-09-17 23:34 UTC
Labels: bug, priority::high, os::windows, Crash, Input
