### ISSUE TITLE
App wont run on mac mini m2pro

### ISSUE THREAD

**Issue by jtarpy** [xournalpp/xournalpp#6150] opened 2024-12-09 13:19 UTC
### Operating System

Mac OS

### (Linux Only) Display Server

None

### Installation Method

downloaded from github

### Xournal++ Version

1.2.5

### libgtk Version

unsure

### Bug Description

Download the DMG for a mac mini m2 pro. dragged the DMG to applications folder. Then clicked on Xournal icon in apps. System says "Xournal++ is damaged and cannot be opend. You should move it to the trash."
![Screenshot 2024-12-09 at 8 17 50 AM](https://github.com/user-attachments/assets/99afa400-c2be-47ef-919c-83f2c121280a)

### Expected Behaviour

Program would open

### Steps to Reproduce

Download app from github
move to apps folder
click on app icon

**Comment by rolandlo** [comment] 2024-12-09 13:56
Closing as a duplicate of #6145

**Closed by rolandlo** 2024-12-09 13:56 UTC
Labels: bug
