### ISSUE TITLE
Screen does not update correctly when scrolling

### ISSUE THREAD

**Issue by Faberix** [xournalpp/xournalpp#2639] opened 2021-01-08 17:28 UTC
Affects version 1.1.0+dev compiled on Jan 7 2021, 22:48. OS: Ubungu 20.10, Gnome-Wayland and X11, Xournalpp is installed from PPA, libgtk version: 3.24.23
Since this version, the screen does not update properly anymore when scrolling. The part that is moved into the displayed window is just blank (see screenshot below).

![xournalpp_scroll_not_rendering](https://user-images.githubusercontent.com/41055689/104045207-7c9a2b00-51de-11eb-8b42-5a3aa821142b.png)

Steps to reproduce: Open Xournalpp and scroll down

This is possibly related to #2634 (I didn't read the whole thing through, but as it affects scrolling and something was changed there recently, it is probably a good point to start)

**Comment by personalizedrefrigerator** [comment] 2021-01-08 17:43
This looks like a duplicate of #2631 and #2634. It has been fixed, but the version in the PPA might not have updated yet.

**Temporary Workaround:** Settings > Touchscreen > Enable GTK Touch Workaround > Restart

**Closed** 2021-01-08 18:23 UTC
Labels: bug
