### ISSUE TITLE
When moving to last page of an PDF document, xournal hangs (segfaults)

### ISSUE THREAD

**Issue by magsilva** [xournalpp/xournalpp#1867] opened 2020-04-13 19:30 UTC
When moving to last page of an PDF document (https://dx.doi.org/10.1109/TSE.1985.232210, temporarily available at [here](https://www.dropbox.com/s/jde5gm6qxcag3nx/PROUST%3A%20Knowledge-based%20program%20understanding.pdf?dl=0)), xournal++ hangs (segfaults) when scrolling to the last page.

**Affects versions :**
 - OS: Linux (Fedora 31)
 - Desktop environment: X11
 - Which version of libgtk do you use: gtk3-3.24.13
 - Version of Xournal++:  git 4798e25 (from 2020/01/16), also with latest in trunk (commit d3e6bbe758dd55a1787b8aeb010df2b3aa5da6f5)
 - Installation method: Luya's COPR (https://download.copr.fedorainfracloud.org/results/luya/xournalpp/)

**To Reproduce**
1. Step 1: Load PDF document indicated at the beginning of the report
2. Step 2: Scroll down to latest page (or simply set page number to 9 in the spinpage box
3. Step 3: If scrolling down, you may have difficulties even to get to last page, but you can move the vertical scrollbar to reach it. If using the spinpage box, you can set that page directly. Either way, xournal++ will hang (and eventually segfault).

**Additional context**
When trying to debug the problem, I noticed that several events were emitted regarding the page change. After some fiddling around the code, I could narrow it down to the latest statement of 
`Layout::updateVisibility()`: `this->view->getControl()->firePageSelected(mostPageNr)`. For some reason, this was triggering an infinite storm of events.

**Comment by Technius** [comment] 2020-04-14 02:09
This is actually caused by #1660. Note that the last page of the PDF has a different size, which causes the issue when zoom fit is enabled.

Closing as duplicate.

**Closed by Technius** 2020-04-14 02:09 UTC
Labels: bug
