### ISSUE TITLE
Writing on lines

### ISSUE THREAD

**Issue by cuppajoeman** [xournalpp/xournalpp#2169] opened 2020-08-16 01:02 UTC
When I'm writing in xournalpp, I find it to be of annoyance that when I hit, return that it doesn't automatically align me to the next line of the page. I realize that these two things maybe completely independent from eachother, but I don't like having to make a whole new textbox for each new line I need, for example: https://i.imgur.com/HfZGFZU.png

I also noted that if you keep typing into a textbox and you go off the page, you just keep going instead of line wrapping.

Anyways, these features may be out of reach, but just wanted to mention them as I encountered these difficulties.

**Comment by rolandlo** [comment] 2020-08-16 06:06
About having text aligned on the lines of the lined/ruled background I would recommend to scale the text box (hence the font size) to fit it to the lines.
![grafik](https://user-images.githubusercontent.com/40485433/90327619-aa63a680-df95-11ea-9fba-0f0e8554b165.png)

About line wrapping: I agree, this would be nice (in particular for pasted text, where it is more annoying). This has been requested several times (#2033 and #139 and #63). A problem is that we need compatibility with Xournal. One fix that would not break compatibility would be to automatically insert newline characters at appropriate positions for pasted text. It is far from perfect though and it's just an option for pasted text, not for text written in Xournal++. I think it will be easier to implement line wrapping with the new file format that in planning/early implementation stage.

**Comment by rolandlo** [comment] 2020-08-16 07:52
For the record about line wrapping: It is not difficult to add line wrapping to the code. Just add the following two lines to TextView::initPango (after the first line, which creates the layout)
```
    pango_layout_set_width(layout, 4 * 72 * PANGO_SCALE);
    pango_layout_set_wrap(layout, PANGO_WRAP_WORD);
```
This is for line wrapping with text width of **4 inches** (1 inch is 72 pt). The problem is that the file format does not provide a way to specifiy the text width. In a xopp-file a text element is written in the form
`<text font="..." size="..." x="..." y="..." color=..." ts="..." fn="...">...</text>`
It contains the font name, the size of the font, the coordinates of the upper left corner of the text box, a time stamp and the filename of an audio file. There is no text width. We would have to add a text width attribute. If not specified there should be no wrapping.

**Comment by cuppajoeman** [comment] 2020-08-20 17:47
Cool, can you give more instructions on how to how to scale the font size to the perfect size so that it stays aligned? If it was done by hand then eventually It will not be aligned right? In addition to that, we would have to have some perfect initial location chosen to start the text box or else nothing would be aligned.

Your idea is nice, but the moment if we want to change font size everything is kinda thrown off (You might want to change font size to do stuff like this: ![image](https://user-images.githubusercontent.com/19198104/90806600-9ac8c280-e2f3-11ea-835f-7b97e3182703.png) )

Considering that the above case wasn't ever going to happen, maybe we could just make it like a text file that we edit with our favorite text editor and snaps onto new-lines, in addition to having all the tools that xournalpp gives us for drawing etc...

**Comment by rolandlo** [comment] 2020-08-23 21:29
Getting the font size right should not be hard, if you have default dpi settings (dpi = 72, see preferences->zoom) and use some standard font. The distance between two background lines for lined and ruled paper is 24 pt. The baseline distance between two text lines is the font size (rounded to an integer) + some spacing (which depends on the font and scales with the font size). You want to make it exactly 24 pt.
For instance for the "Ubuntu Regular" font you should use font size 21 (any size between around 20.4 and 21.2 gives the same baseline distance).
For "Sans Regular" you should use font size 20 (any size between around 19.4 and 20.4 will do).

So you can just remember these values. If you use another font, let me know or find it out yourself. An integer font size will usually do and in my experience, and scaling from hand with three lines of text should be accurate enough to get the font size right.

To get the first text line (more or less) precisely on the first background line, you should observe that the middle of the mouse cursor will be in the middle of a capitol letter like T. You can't get it 100% accurately without editing the uncompressed xopp-file by hand, I think, but for what you can see from eye it should suffice.

If you want to fill two (or more) lines with one text line, you must scale the font size with roughly the same factor.
For instance for Sans Regular you can go with 
- 20 pt font size for filling 1 line, 
- 40 pt font size for filling 2 lines, 
- 61 pt for filling 3 lines, 
- 81 pt for filling 4 lines,
- 102 pt for filling 5 lines,
- 122.9 pt for filling 6 lines (here 122 pt is too small and 123 pt is too big)
- 144 pt for filling 7 lines
- 164 pt for filling 8 lines....

I hope that helps.

**Closed** 2020-09-28 07:04 UTC
Labels: enhancement

**Comment by Nestak2** [comment] 2022-10-21 23:53
@rolandlo Thanks for contributing to the existence of xournal++ and keeping it free!

I don't get misalignment of the text when I use ruled background, see here
![Screenshot from 2022-10-22 00-26-11](https://user-images.githubusercontent.com/16193553/197305525-55911656-dadd-4c96-ad2e-9b2275750ff4.png)

But when I switch to graph background (which I use in almost all of my notes) I do get the misaligned:
![Screenshot from 2022-10-22 00-30-18](https://user-images.githubusercontent.com/16193553/197305582-0af02eb1-d36c-4995-bed4-0133388abaa2.png)

There is just no text size that fixes it, non-integer fonts are the same size as integers (text size 11.5 produces same size characters as 11). Under preferences->zoom my dpi is set to 72, as you suggest above. Can you reproduce this problem? Do you know a solution?


About the text wrapping functionality - I would also love to have it. In your answer above I read "It is not difficult to add line wrapping to the code... The problem is that the file format does not provide a way to specifiy the text width." So I don't get - in the end is text wrapping configurable or not? Can you walk me through how to do it with some more explanations, e.g. I don't know where to find this TextView::initPango

**Comment by rolandlo** [comment] 2022-10-22 06:15
> There is just no text size that fixes it, non-integer fonts are the same size as integers (text size 11.5 produces same size characters as 11). Under preferences->zoom my dpi is set to 72, as you suggest above. Can you reproduce this problem? Do you know a solution?
> 
The only solution that comes to mind is to use a custom grid page background with a different grid size. 

> About the text wrapping functionality - I would also love to have it. In your answer above I read "It is not difficult to add line wrapping to the code... The problem is that the file format does not provide a way to specifiy the text width." So I don't get - in the end is text wrapping configurable or not? Can you walk me through how to do it with some more explanations, e.g. I don't know where to find this TextView::initPango

You can find `TextView::initPango` in the source code in the file [`src/core/view/TextView.cpp`](https://github.com/xournalpp/xournalpp/blob/master/src/core/view/TextView.cpp). If you want to have text wrapping now, you need to clone the repository, change that file and build from source (as described in the [Wiki](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md)). Pango (that is used for text layout) provides [`pango_lay_set_wrap`](https://docs.gtk.org/Pango/method.Layout.set_wrap.html), so you would have to use that method.

**Comment by lightingnerd** [comment] 2023-06-01 22:03
I understand the desire to maintain compatibility, but I would also like to reiterate the importance of implementing this request. I have also commented on a similar request made to the Xournal project. Hopefully y'all can work this out, because it's a sorely needed feature. I appreciate all the excellent work you've done here, and adding word wrapping would just be "chef's kiss", as they say! 

https://sourceforge.net/p/xournal/feature-requests/182/#ef50
