### ISSUE TITLE
Menu Windows Open on Screens Other Than the Screen which Xournal++ is on

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3175] opened 2021-06-21 05:05 UTC
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use:  3.24.29
 - Version of Xournal++:  1.1.0+dev git commit 99df9684
 - Installation method: Installed from zip from github.

**Describe the bug**
Menus that appear as pop ups, dont open on the same screen that xournal is running on. They instead open on other windows. For example I have a primary monitor, and a secondary monitor to the left, and a third which is a drawing tablet that has xournal on it. When I open a sub menu like preferences or the about window, the pop up windows open on the second monitor and not the tablet.
**To Reproduce**
1. have xournalpp open on a monitor with a multi monitor set up
2. open a menu window i.e. preferences
3. observe that it opens on a separater monitor

**Expected behavior**
the pop up window should appear on the same monitor/screen that xournal is running on.

**Additional Context**
The pop up menus work as expected on linux. Just not windows.

**Comment by Technius** [comment] 2021-06-23 22:24
Duplicate of #1204. This is a GTK bug, which we can't fix here.

**Closed by Technius** 2021-06-23 22:24 UTC
Labels: Dependency Issue, bug, confirmed
