### ISSUE TITLE
window borders and palm

### ISSUE THREAD

**Issue by ces42** [xournalpp/xournalpp#2291] opened 2020-09-30 01:51 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu
 - Desktop environment: X11 (Gnome)
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: 1.1.0+dev version of Sep 28 (commit d0f58e0), has been an issue for at least a month I think
 - Installation method: PPA and compiled from source

**Describe the bug**
The Xournal++ window has very thick borders on Gnome. These borders allow moving the window and double-clicking to (un)maximize. When writing on the right edge of the screen (as right-handed user) it sometimes happens that I accidentally (un)maximize the window with my palm.

**Expected behavior**
1.0.18 does not have these thicker windows

**Screenshots of Problem**
1.1.0-dev:
![image](https://user-images.githubusercontent.com/19842517/94634149-1ff4af00-0284-11eb-9dff-6429978491d1.png)

1.0.18:
![image](https://user-images.githubusercontent.com/19842517/94634325-9a253380-0284-11eb-9691-199c52de70ed.png)

**Comment by rolandlo** [comment] 2020-09-30 02:44
I can confirm this. Thanks for reporting, I didn't notice when that changed.

**Comment by Krzmbrzl** [comment] 2020-09-30 09:29
This is also the case on KDE Neon (19.5) using the KDE plasma WM. Note though that KDE Neon is based on Ubuntu (20.04 if that matters), so I assume it's not too surprising that the issue exists there as well. I also use the 1.1.0+dev version that is present in the PPA

**Comment by rolandlo** [comment] 2020-09-30 19:58
The commit this border was introduced is 1ba572969e27948264f5ada821f558531c330fd9. It seems the problem is that some toolbars are set to visible which are empty for the chosen toolbar. This should be fixed. Until then a workaround is to change the toolbar style forth and back (e.g. from `Portrait` to `Toolbar Left` and back to `Portrait`).

**Comment by rolandlo** [comment] 2020-10-11 07:23
This is fixed in #2309

**Closed** 2020-10-26 22:09 UTC
Labels: PR available, bug, confirmed, priority: medium, regression

**Comment by rolandlo** [comment] 2020-10-26 22:11
The fix has been merged.
