### ISSUE TITLE
Apply to all pages

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2196] opened 2020-08-28 17:32 UTC
When I choose "Apply to all pages" in the "Journal/paperback" menu, all pages turn blank. I can't choose the same paperback for all page in an existing document.

**Comment by rolandlo** [comment] 2020-08-29 06:56
I have looked at the code. The background that is copied is the one that you set in the menu `journal->configure page template`. If you have enabled "Copy current page background instead", this will mean that all pages get the Copy Background type, which will turn all pages blank. 
You can apply a background to all pages by setting in the following way: 
1. Set the desired page background in the page template settings (from menu `journal->configure page template`) 
2. disable the "Copy current page background instead" checkbox (from menu `journal->configure page template`) 
3. use "Apply to all Pages" (from menu` journal->Paper background`)

To me it still looks like a bug, but I am not 100% sure, what the intended behavior was.

**Comment by MichelReims** [comment] 2020-08-29 07:07
It's works !!! Thank's

**Comment by rolandlo** [comment] 2020-08-29 07:10
Actually, as discussed in #951, it is even more confusing. You can also select the page background from the toolbar dropdown and and apply that page background to all pages from there. This is a simpler solution. The behavior of the menubar should be fixed.

**Comment by MichelReims** [comment] 2020-08-29 08:36
I will

**Comment by MichelReims** [comment] 2020-08-29 08:37
I will try it. Thank you

**Comment by MichelReims** [comment] 2020-08-29 10:08
I don't see the page background in the toolbar

**Comment by rolandlo** [comment] 2020-08-29 10:11
It looks like this: 
![grafik](https://user-images.githubusercontent.com/40485433/91634425-9cc80b00-e9f0-11ea-9976-dfdc2cde0778.png)

It may be on the bottom (or on the left/right), depending on the chose toolbar style.

**Comment by MichelReims** [comment] 2020-08-29 10:16
Yes. It's OK

**Comment by rolandlo** [comment] 2020-08-29 10:22
I close this issue in favor of #951.

**Closed by rolandlo** 2020-08-29 10:22 UTC
Labels: bug, confirmed, enhancement

**Comment by MichelReims** [comment] 2020-08-29 14:15
Thank's
