### ISSUE TITLE
Xournal Crashes randomly

### ISSUE THREAD

**Issue by drskalman** [xournalpp/xournalpp#5519] opened 2024-02-24 09:53 UTC
### Operating System

Linux

### (Linux only) Distribution

Arch

### (Linux only) Desktop Environment

Awesome

### (Linux Only) Display Server

X.Org

### Installation Method

Official Repo

### Xournal++ Version

1.2.2-1

### libgtk Version

gtk3 1:3.24.41-1

### Bug Description

It crashes randomly while using think pad x1 yoga stylus wrting on a simple file (not pdf).

### Expected Behaviour

Not crashing.

### Steps to Reproduce

Write for a while, if you hand also touches buttom of the screen then it is more likely to crash but it happens once 30min.

### Additional ContextDate: Mon Feb 19 15:38:10 2024
Attached as comment

**Comment by drskalman** [comment] 2024-02-24 10:08
[errorlog.20240219-153810.log](https://github.com/xournalpp/xournalpp/files/14392446/errorlog.20240219-153810.log)

**Comment by tmoerschell** [comment] 2024-02-27 23:32
Duplicate of #5502. See https://github.com/xournalpp/xournalpp/issues/5502#issuecomment-1937528338 for specifics. 
Have fun using Xournal++!

**Closed as not planned** 2024-03-17 16:13 UTC
Labels: bug
