### ISSUE TITLE
Selection may scroll (instantly) to first page when dragged selection hits top toolbar

### ISSUE THREAD

**Issue by ericschdt** [xournalpp/xournalpp#2488] opened 2020-12-06 20:08 UTC
**Affects versions :**
 - OS: Manjaro KDE
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
      libgtk: 3.24.23 
 - Version of Xournal++: fad337b3
 - Installation method: AUR
- `New input method` is activated (I think I used the mouse for dragging, though)

**Describe the bug**
Sometimes it happens that the selected content jumps to the top of the first page when one starts dragging it.

**To Reproduce**
1. Add several pages
2. Write something on all pages
3. On the last page select part of the content
4. Start dragging it slowly

**Expected behavior**
The selection follows the mouse

**Screenshots of Problem**
I can try to do a screen recording later (gif).

**Comment by ericschdt** [comment] 2020-12-08 19:28
Here's an animation showing the issue. If I drag it a little bit to the top, it immediately rushes to the first page, which make it hard to place:

![resized](https://user-images.githubusercontent.com/43318127/101531726-8fc19d00-398b-11eb-92c2-63a264d79686.gif)

**Comment by tattsan** [comment] 2020-12-09 04:51
I've been also  annoyed with this behavior. Not jumps but very rapid scrolls, I think.
If you try this on documents over 100 pages,  you'll feel like you're on a fighter jet.

**Comment by ericschdt** [comment] 2020-12-09 10:44
> Not jumps but very rapid scrolls, I think.
You are right, I wasn't very precise. The title should now reflect the issue better.

**Comment by LittleHuba** [comment] 2020-12-09 12:55
I always wanted to say this: "This is a feature not a bug"

BUT: In the feature is a bug^^ It should scroll slowly once the selection hits the border of the view. This is to allow for moving selections to parts currently not visible. The speed seems to be a bit fast though...

**Comment by Technius** [comment] 2021-03-01 22:54
Closed in favor of #2889.

**Closed by Technius** 2021-03-01 22:54 UTC
Labels: bug, confirmed, difficulty::easy
