### ISSUE TITLE
Way to start Xournal++ without audio features

### ISSUE THREAD

**Issue by fpesari** [xournalpp/xournalpp#3905] opened 2022-03-10 12:58 UTC
**Is your feature request related to a problem? Please describe.**
Today a distro update temporarily caused Xournal++ to segfault due to an error with the audio system. The error was rapidly fixed by upgrading Pipewire but it made me realize that there is no reason for Xournal++ to crash on audio-related issues if the only thing the user wants to do is to annotate a PDF or take some visual notes. As such, there should be a way to use Xournal++ in audio-less mode.

**Describe the solution you'd like**
I'd simply like a way to skip initialization of the audio system (and thus disable all audio features) at runtime (rather than at compile-time). This way, if something breaks in the audio system, users can just run Xournal++ without it and do what they need to do.

I propose an `Enable audio features` toggle in the `Preferences > Audio recording` section (if not toggled, of course all the GUI controls in `Preferences > Audio recording` gets disabled) with a corresponding entry in the `~/.xournalpp/settings.xml` file, like this:

```
  <property name="enableAudio" value="true"/>
```

This way, if the program crashes on startup due to the audio subsystem and users consequently can't access the Preferences, they can work around it by manually setting the property to `false` via their text editor.

**Describe alternatives you've considered**
A command-line flag `--no-audio`, which would have the advantage of being easier to discover than a setting (but the setting is needed, IMHO).

**Comment by Technius** [comment] 2022-03-11 05:43
Duplicate of #1468. There was some initial work in getting the application to run without audio, but the work seems to have been abandoned (and is out of date by now)...

**Comment by Technius** [comment] 2022-03-11 05:45
The difference between this issue and the other one is that this request is to add a runtime configuration option, while the other one is a compile time option. As such, I'll keep both open. The runtime option is likely easier to implement.

**Comment by rolandlo** [comment] 2023-08-18 16:05
I checked it: All that is needed for disabling audio at runtime is to set `audioController` to `nullptr` in the constructor of the Control class and then whenever `audioController` or `control->getAudioController()` is used, check if it is `nullptr` or not and in the former case do nothing. It only affects the files `InputHandler.cpp`, `MainWindow.cpp`, `PageViewFindObjectHelper.h` and `SettingsDialog.cpp`. 
I will create a PR once I find time for that.

See also #5020 for how real the problem is.

**Comment by rolandlo** [comment] 2023-08-24 05:16
Closing in view of #5068

**Closed by rolandlo** 2023-08-24 05:16 UTC
Labels: enhancement, priority::medium
