### ISSUE TITLE
Strokes are drawn when exiting a selection

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#1797] opened 2020-03-24 20:15 UTC
**Affects versions :**
OS: Manjaro
(Linux only) Desktop environment: X11
Which version of libgtk do you use
gtk3 1:3.24.14+9+g429a6287e0-1
gtk2 2.24.32-2
Version of Xournal++: 1.1.0+dev 86d5178b
Installation method: AUR

**Describe the bug**
To exit a selection you have to tap somewhere with the pen. No stroke should be drawn then. @LittleHuba already fixed that once and someone broke it again.

**Comment by Febbe** [comment] 2020-03-25 01:33
I can't reproduce this with the newest master (drew something -> selected it -> tapped outside of the selection).
This seems to be an issue with specific configurations.
Do you have special options activated like the old Input System or the touch and scroll workaround?
Or even better can you provide your configuration files?

**Comment by coldspark29** [comment] 2020-03-30 07:48
No I am on the new input system and have none of the mentioned configurations activated. 


[settings.zip](https://github.com/xournalpp/xournalpp/files/4401470/settings.zip)

**Comment by Febbe** [comment] 2020-04-04 15:16
Hello Jan, 
thanks for sharing your configuration. I can reproduce it now. It is not a problem with the selection itself, rather with the fact, that you configured your first pen button to the selection tool and the tool is changed back to pen as soon you release the first pen button.
Holding the the button while clicking should be a first workaround.

**Comment by coldspark29** [comment] 2020-04-04 15:47
Okay, that makes sense. I have configured it like this, because I have the Bamboo Ink (in my opinion the best pen out there) and the buttons on it are inverted. Thank you for the advice!

**Comment by Technius** [comment] 2020-05-17 19:40
This has been addressed by the recently added setting `Stylus > Ignore the first X events`.

**Comment by coldspark29** [comment] 2020-05-18 06:35
No, that hasn’t solved it for me.

Gruß,
Jan Claußen

**Comment by LittleHuba** [comment] 2020-05-18 07:33
The setting would not fix it if set correctly. It discarded the input for everything even canceling a selection. 
We should fix this in the input system. It has to check if there is a selection that is being canceled and then discard the current input.

**Comment by coldspark29** [comment] 2020-05-18 16:12
Yes, I also think that it introduced a bug. I activated the setting at once when I read about the merge. Now when I make a selection, resize it and then duplicate it, it breaks the resizing operation previously made. I can't confirm right now if it happened due to the setting, but it fits Ulrich's description and he knows his input system best!

**Comment by coldspark29** [comment] 2020-05-25 10:08
I just checked it. The bug I described is not related to the setting.

**Closed** 2020-12-09 19:34 UTC
Labels: Input, bug
