### ISSUE TITLE
Mouse cursor not showing in video recorded with screen recorders.

### ISSUE THREAD

**Issue by ramtonio** [xournalpp/xournalpp#5058] opened 2023-08-15 12:55 UTC
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Official Release

### Xournal++ Version

1.1.3, 1.2.0

### libgtk Version

3.24.34, 3.24.38

### Bug Description

When recording my screen with Camtasia, Bandicam, Free cam and some other screen recorders, the mouse cursor doesn't appear in the recorded video.
It doesn't happen when I use Xournal++ 1.1.0 (libgtk 3.24.29).
I think the problem is with libgtk versions above 3.24.29.
Thanks.

### Expected Behaviour

I espect the cursor appears in the recorded videos as I make educational and tutorial videos and it is essential to that purpose.

### Steps to Reproduce

1 - Record the screen.
2 - Play back the video.

### Additional Context

Xournal++ functions ok.

**Comment by bhennion** [comment] 2023-08-15 19:14
Duplicate of #3469

**Closed by bhennion** 2023-08-15 19:14 UTC
Labels: bug
