### ISSUE TITLE
Be able to set the default page format

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3732] opened 2022-01-21 01:41 UTC
**Is your feature request related to a problem? Please describe.**
Every time that I create a new journal its in the format of white lined A4 paper, but I never need that format, so whenever I create a new document, I have to almost always change the document format.

**Describe the solution you'd like**
I would like to be able to configure the settings for default page/journal layout. 

The settings for this could be located in Edit > Preferences > Defaults > Page Layout

**Comment by rolandlo** [comment] 2022-01-21 05:30
Duplicate of #2191

**Closed by rolandlo** 2022-01-21 05:30 UTC
Labels: enhancement
