### ISSUE TITLE
Fill opacity glitches

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#761] opened 2019-01-15 10:15 UTC
First of all, thanks for adding this!
I have a couple of problems with fill opacity selection. 
1. How can I change the opacity if my pen has no right click option? 
2. If I select a filled shape, click the (mouse) right button to change opacity, and then move it, what happens is that I am copying it... is it expected? (see clip)

![recorded](https://user-images.githubusercontent.com/6414907/51173878-b87fab80-18b6-11e9-9046-5b1d3e67d1c3.gif)

**Comment by luco5826** [comment] 2019-01-15 11:56
Hi! Thank you for submitting an issue! Right now the way to change transparency of the fill tool is under Tools -> Fill Transparency or something similar, but it is present, it has a useful preview widget too. I'm not able to test the second problem on my system but i think xournalpp isn't supposed to behave so!

**Comment by andreasb242** [comment] 2019-01-15 18:52
I checked and I'm really surprised. I thought about a repaint problem, but yes, it copies and change the opacity!

Copy make sense, probably somebody added this as feature - I have to check.
But change the opacity?!?!?! I added this feature really recent... I have to check it.

But maybe not today - still over 10 unread notifications ;-)

**Comment by andreasb242** [comment] 2019-01-21 20:59
@Rmano 
It's not a bug, it's a feature!

If you press the right mouse button, you create a copy of the current selection.
The undo / redo handling is correct implemented also. And it does NOT change the opacity, you simple created two copies, and then moved one, so there are two at the original place, and the one you move is therefore brighter.

You can reproduce it, so you see it. I close this bug now, as I think it's clear now, and it's definitive no bug.

**Closed by andreasb242** 2019-01-21 20:59 UTC
Labels: bug
