### ISSUE TITLE
Cursor is not being recorded in camtasia screen recorder while using xournal v1.1.1 [windows]

### ISSUE THREAD

**Issue by smimer2006** [xournalpp/xournalpp#4118] opened 2022-06-26 16:24 UTC
**Affects versions :**
 - OS: [Windows]
 - Version of Xournal++ [v1.1.1]
 - I am using wacom tablet as input device

**Describe the bug**
While using xournal as white board and simultaneous screen recording with camtasia/any other screen recorder, Cursor is not recorded when it is over page area, however cursor is recorded when it is on menu bar or tool bar or any area except for on the white area. This bug was not there on earlier version(v1.0.12)

**To Reproduce**
1. Open Xournal
2. connect wacom tablet to windows PC
3. Start camtasia screen recorder
4. start writing on page area with the help of wacom tablet
5. stop camtasia screen recorder, and see the screen recorder video file
6. you will see that cursor is visible when it is out side writing area, but once you start writing in xournal, cursor will be shown at outside writing area however surprisingly writing is visible but cursor is seen elsewhere i.e. outside writing area

**Input Logs**
Follow this tutorial https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs and attach the generated files.

**Expected behavior**
I expected that cursor movement should be recorded while on writing area

**Screenshots of Problem**
N.A.

**Additional context**
This problem was not there in earlier version (1.0.12)

**Comment by bhennion** [comment] 2022-06-27 07:25
This is a duplicate of #3469. The bug is not actually in Xournal++: see the last post there (https://github.com/xournalpp/xournalpp/issues/3469#issuecomment-984929060)

**Closed by bhennion** 2022-06-27 07:25 UTC
Labels: bug, Input
