### ISSUE TITLE
Control over pen size?

### ISSUE THREAD

**Issue by Kreijstal** [xournalpp/xournalpp#2913] opened 2021-03-06 13:19 UTC
As far as I know  there are only 5 options, `very fine, fine, medium, thick, very thick`, which imho it's pretty limited, is this due to a inherent limitation or could the user choose an arbitrary value?

**Comment by rolandlo** [comment] 2021-03-06 17:29
The file format would support arbitrary pen size, but the Gui only has these 5 options.

**Comment by Technius** [comment] 2021-03-07 09:29
Related: #1361

**Comment by personalizedrefrigerator** [comment] 2021-03-13 06:06
A workaround available in 1.1.0+dev:

![](https://user-images.githubusercontent.com/46334387/111021106-feddd180-837e-11eb-91dd-207db42bc4da.png)
Change the "Pressure Multiplier" under Settings > Stylus > Pressure Sensitivity. Unfortunately, this requires opening and closing settings.

**Comment by Technius** [comment] 2022-02-19 08:33
Closing as duplicate of #1361.

**Closed by Technius** 2022-02-19 08:33 UTC
Labels: question
