### ISSUE TITLE
Xjournal does not work with iOS Monterrey 12.1

### ISSUE THREAD

**Issue by ligia127** [xournalpp/xournalpp#3719] opened 2022-01-17 12:53 UTC
Dear Ones,

after upgrading my Mac to iOS Monterrey 12.1, I can no longer use Xjournal++ 11.1.0 for Mac. After installing Xjournal++, I get a black screen of the application and no access to anything. 

Is an update planned yet?

Regards.

**Comment by rolandlo** [comment] 2022-01-17 12:58
This is a duplicate of #3517. Yes, an update is planned when Gtk 3.24.31 has landed into [`gtk-osx`](https://gitlab.gnome.org/GNOME/gtk-osx/), which may be any moment.

**Closed by rolandlo** 2022-01-17 12:58 UTC
Labels: bug
