### ISSUE TITLE
Xournal++ crashes, when clicking with both mouse buttons while using the selection tool

### ISSUE THREAD

**Issue by HagePutte** [xournalpp/xournalpp#5177] opened 2023-09-25 10:41 UTC
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Flatpak

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

The app crashes when one clicks both mouse buttons while using any of the selection tools. This happens every time without fail.

### Expected Behaviour

Continue the selection

### Steps to Reproduce

1. Select any of the selection tools
2. Click & hold the right or left mouse button
3. While still holding the right/left mouse button, click the other mouse button
4. The application will crash

**Comment by bhennion** [comment] 2023-09-25 13:44
Duplicate of #5149
If you could post there a screenshot of your mouse settings tab, it could help me reproduce.

**Closed by bhennion** 2023-09-25 13:44 UTC
Labels: bug
