### ISSUE TITLE
Surface Pro 7 Pen Lag

### ISSUE THREAD

**Issue by Sector14** [xournalpp/xournalpp#1655] opened 2019-12-06 12:45 UTC
**Affects versions :**

 - Windows 10 Version 1903 Build 18362.476
 - Xournal 1.0.15 (didn't try 1.0.16 due to installer problems)

**Describe the bug**

Writing a word with the surface pen (the model before the new "slim" pen) on a Surface Pro 7 is very laggy. You can write "test" and get the "t" to render correctly, but the stokes for the e are either entirely lost or you get a diagonal line where it's picked up the start and end position but not the smooth strokes in between.

Writing "joined up" so the entire word is done as a single stroke appears to work. But writing at a normal pace with separate characters such as "test" does not. Same occurs if I try to write gggggg doing it as a single joined up stroke works. Doing them as individual g's will work a little then a g will go missing or miss enough to be unrecognisable.

Tried with both experimental input system ticked and not. Same result.

**Input Logs**

I'm not able to generate input logs currently as my surface doesn't have any development environment setup on it yet. If you can provide a debug build I can get the logs you want however.

OneNote, Whiteboard or paint app does not exhibit these issues so I don't believe this is a hardware issue.

**Comment by LittleHuba** [comment] 2019-12-06 14:31
You'll have to install the development environment as described in our wiki. We do currently not provide any debug builds.
The problem is most likely in GTK+ though, as it is the framework getting the events from the system. We are just taking whatever we get from GTK. We have somebody working on a native solution for Windows though and he is currently trying to work around some lag in receiving events as well. What we found out so far is that the lag results most likely from GTK+ using the WinTabAPI instead of the newer InkAPI, and for some reson the older API has these lags. A workaround that works most of the time is to start a session of OneNote (UWP) in the background. This for some reson removes the lag.

**Comment by Sector14** [comment] 2019-12-06 15:14
I gave the OneNote (UWP) in the background a go. It doesn't appear to have helped in this instance. 

I'll retest this once you have a build available with native windows pen handling and if that doesn't solve the issue, will sort out a development environment to debug properly.

**Comment by LittleHuba** [comment] 2019-12-06 15:48
Installing the environment is actually quite simple. If you want to test the new feature early you will have to install the environment anyway. We only provide the nightlies based on the master branch. The new framework will not be merged into master before it works well enough.

Maybe try drawing something in OneNote and start Xournal++ before opening OneNote.

**Comment by LittleHuba** [comment] 2019-12-06 15:50
@gansgar is the one working on the framework if you want to talk to him directly. He's available on gitter from time to time.

**Comment by franzbu-png** [comment] 2020-04-21 04:51
Hi @Sector14 can you check if your surface pro 7 come with "wintab driver"? Because my Surface book 2 didn't which resulted in the lag. 
I found the driver for SB2 here: https://www.microsoft.com/en-us/download/details.aspx?id=100419

**Comment by myspaghetti** [comment] 2020-05-21 09:29
WinTAB is not an acceptable workaround because it is a deprecated interface.

**Comment by franzbu-png** [comment] 2020-05-21 09:34
@myspaghetti what do you mean by that? It is not really a workaround, since Xournalpp is based on it.(For Windows).. (at least that s what i think I know, but not 100% sure, because I am not a developer)

**Comment by myspaghetti** [comment] 2020-05-21 10:11
WinTAB is an old API that is not installed by default on modern Windows releases. Gnome should support either [RealTimeStylus](https://gitlab.gnome.org/GNOME/gtk/issues/262) (Windows Vista and later) or [Windows Pointer Input](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1563) (Windows 8 and later). Seems WPI is coming in a few weeks or months.

Xournal++ should definitely support these interfaces as soon as they land in Gnome instead of relying on WinTAB.

**Comment by franzbu-png** [comment] 2020-05-21 10:19
interesting, thanks for letting me know. you might want to share it in the [gitter chat](https://gitter.im/xournalpp/xournalpp)

**Comment by myspaghetti** [comment] 2020-05-21 10:25
After searching the issue tracker I found issue #1346, looks like Gansgar and LittleHuba are already on top of it.

**Comment by LittleHuba** [comment] 2020-05-21 10:47
> WinTAB is not an acceptable workaround because it is a deprecated interface.

WinTAB is still the interface used by most applications. Support for Windows Ink is not widely spread in multiarch frameworks. You missunderstand "deprecation" by the way. Just because an API is deprecated it does not mean that it is unusable. It just means that new code should not rely on it and you should move to the newer API in time. So to say it very clearly: It is definitely an acceptable workaround for now and will be as long as there is no support for a newer API.

> Xournal++ should definitely support these interfaces as soon as they land in Gnome instead of relying on WinTAB.

Xournal++ is built on top of GTK+. GTK+ handles all input related stuff providing us with an API that is independent of any operating system. As long as GTK+ does not provide support for Windows Ink, Windows Pointer Input or any other modern API we will not support it either. As soon as a version of GTK+ is released with support for one of this APIs Xournal++ will support it as well. 

So please stop blaming us for buggy Windows support when you should actually head over to GTK+ and ask the devs to add support for newer APIs.

**Comment by myspaghetti** [comment] 2020-05-21 12:11
>blaming us
I wasn't blaming you?

**Comment by Xourna** [comment] 2021-01-28 21:52
It's really weird! I have a quite old surface pro 3 with windows 8.1 Pro and i installed xournal on it some years ago and it writes just perfectly fine, without lagging or something. because of that i bought a second surface pro 3 recently with more RAM and HDD space. It came with Windows 10 preinstalled. Strangely, on the new surface the pen lags some milliseconds or so. Its just like some "intelligent" software with shape recognition tries to recognise some shapes in what i am drawing or so, because the lagging appears more intensly when I try do write the letter "a" or any other circle like thing. with a small "w" its like the program draws a straigt line instead of a bow. Those problems only occur when i first touch the display with the pen, later i can draw lines and circles etc. just like i want to. With microsofts paint program and windows journal the pen draws withour any problems or errors. I thought that windows 10 is the problem and installed windows 8.1 pro after a complete wipe. But there is the same problem on windows 8.1 Pro on the new surface. 

I don't know whats wrong.. The only "abnormality" that i noticed is that i got an error message when i try to install xournal on windows 10 but after unpacking i was able to open it anyway just by rightclick. i'm not shure if i got the error message after the downgrade on 8.1 pro too but I don't think that thats the real problem anyway.. 

I really hope you have any idea how to solve this problem because xournal is by far the best program that i know to handwrite in pdfs and to export notes to pdf. 

Thanks for any advice and have a nice evening.

**Comment by rolandlo** [comment] 2021-01-28 21:55
> It's really weird! I have a quite old surface pro 3 with windows 8.1 Pro and i installed xournal on it some years ago and it writes just perfectly fine, without lagging or something. because of that i bought a second surface pro 3 recently with more RAM and HDD space. It came with Windows 10 preinstalled. Strangely, on the new surface the pen lags some milliseconds or so. Its just like some "intelligent" software with shape recognition tries to recognise some shapes in what i am drawing or so, because the lagging appears more intensly when I try do write the letter "a" or any other circle like thing. with a small "w" its like the program draws a straigt line instead of a bow. Those problems only occur when i first touch the display with the pen, later i can draw lines and circles etc. just like i want to. With microsofts paint program and windows journal the pen draws withour any problems or errors. I thought that windows 10 is the problem and installed windows 8.1 pro after a complete wipe. But there is the same problem on windows 8.1 Pro on the new surface.
> 
> I don't know whats wrong.. The only "abnormality" that i noticed is that i got an error message when i try to install xournal on windows 10 but after unpacking i was able to open it anyway just by rightclick. i'm not shure if i got the error message after the downgrade on 8.1 pro too but I don't think that thats the real problem anyway..
> 
> I really hope you have any idea how to solve this problem because xournal is by far the best program that i know to handwrite in pdfs and to export notes to pdf.
> 
> Thanks for any advice and have a nice evening.

Are you using Xournal or Xournal++. Which version do you use?

**Comment by Xourna** [comment] 2021-01-28 22:02
i used the standard xournal version in the beginning on the two new and on the old surface pro 3s. 

I handed the new surface in to a computer repairman and he reinstalled windows 10 and installed xournal ++. It seemed like the problems improved a little bit but the lag still persists. before he installed xournal ++ the lines that i drew were jagged (i hope thats the right translation from google for "zigzag" lines) and after he installed xournal ++ at least the lines were more smooth.

**Comment by Xourna** [comment] 2021-01-28 22:04
on my old surface it say I'm using version 0.4.8-win 32  [although i have a win 64 operating system)

**Comment by LittleHuba** [comment] 2021-01-29 14:16
> on my old surface it says I'm using version 0.4.8-win 32 [although i have a win 64 operating system)

Then you are using Xournal which is not maintained by us. Please be aware that Xournal and Xournal++ are two different applications which are not related by more than sharing 5% of code. Especially Xournal is no longer maintained while Xournal++ is. Should you install Xournal++ from our repository and still see the bug, please make sure to install the Wintab driver as mentioned previously in this thread. This resolved similar issues for other users. I hope this helps you along.

**Comment by Xourna** [comment] 2021-01-31 12:37
Hello LittleHuba. 
Thanks for your advice! As i said, the old xournal version that i mentioned works perfectly fine on my old surface pro 3 without lagging. 
I handed in the new surface to a repairmen and as far as I understand he installed xournalpp version 1.0.20 for windows and then installed "xournalp-winpointer-20201027-setup.exe" this somehow fixed the problem perfectly fine! 
I hope that others that have the same or similar issues that i had can benefit from this information. 
Thanks again and have a nice day!

**Comment by rolandlo** [comment] 2021-07-26 07:27
I am closing this issue since Windows Pointer input support has been added to GTK+ 3.24.30 recently and is included in Xournal++ version [1.1.0-hotfix.1](https://github.com/xournalpp/xournalpp/releases/tag/1.1.0-hotfix.1). So please upgrade.

**Closed by rolandlo** 2021-07-26 07:27 UTC
Labels: Input, bug, os::windows
