### ISSUE TITLE
Active page does not update when scrolling

### ISSUE THREAD

**Issue by Debrugger** [xournalpp/xournalpp#1184] opened 2019-05-29 07:27 UTC
Scenario: open up a long pdf, scroll and read along with the lecture or searching for a passage, not writing anything yet. If you insert a page or change the display mode to two pages next to each other, the view jumps back to the active/outlined page. This behavior is very frustrating and unintuitive, especially when there's no clear reason for the 'active page' mechanism.

**Describe the solution you'd like**
Change the active page to the one currently visible when scrolling. It's not necessarily clear which page should be active when e.g. multiple are on screen, but anything is better than to suddenly be catapulted back 20 pages.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by LittleHuba** [comment] 2019-05-29 08:51
The fix for this issue should consist of two separate things:

1. Change the active page when scrolling (this is required for backward compatibility with the old input system)
2. Remove the active page system as the new input system does not require it. When doing this we need to determine the position for pasted items.

To determine the page for pasting items I would use the following steps:

1. Use the current position of the cursor if it is within a page
2. Use the page that received the last input, if it is still visible
3. Use the currently visible page

For 2. and 3. we need to take the visible area of the page into account. We did this already but it got broken by the zooming changes. There should be another issue somewhere concerning this regression.

**Comment by Technius** [comment] 2019-09-25 21:37
Pinning this issue since it gets a lot of duplicates.

**Closed** 2019-11-19 18:06 UTC
Labels: bug, difficulty:easy, enhancement, hacktoberfest, priority: high
