### ISSUE TITLE
Relative path for background PDFs when exporting to PDF using the command line fails

### ISSUE THREAD

**Issue by michaelcadilhac** [xournalpp/xournalpp#2226] opened 2020-09-09 00:20 UTC
**Affects versions :**
 - OS: Linux
 - Desktop environment: Irrelevant (command line)
 - poppler/poppler-glib version: 0.90.1-1
 - Version of Xournal++: master
 - Installation method: source

**Describe the bug**
Journals with a background cannot be exported to PDF using the commandline `xournalpp -p PDF SRC.xopp`, because they contain a relative path to the background PDF.

**To Reproduce**
1. Create a journal with a PDF background
2. On the command line: `xournalpp -p out.pdf src.xopp`
3. This results in:
```
** (com.github.xournalpp.xournalpp:207302): WARNING **: 19:13:59.238: Could not load preview image, error: The pathname “./background.pdf” is not an absolute path
** (com.github.xournalpp.xournalpp:207302): WARNING **: 19:13:59.238: [Crash Handler] Crashed with signal 11
```

**Expected behavior**
The same as if I were to open the file, and export it to PDF manually.

**Additional context**
The following is enough to fix the problem, but I'm not sure if there's a root reason behind that behavior.

```diff
diff --git a/src/model/Document.cpp b/src/model/Document.cpp
index f0034c45..593d2af3 100644
--- a/src/model/Document.cpp
+++ b/src/model/Document.cpp
@@ -291,7 +291,8 @@ auto Document::readPdf(const fs::path& filename, bool initPages, bool attachToDo
             return false;
         }
     } else {
-        if (!pdfDocument.load(filename.c_str(), password, &popplerError)) {
+        fs::path absfilename = fs::absolute (filename);
+        if (!pdfDocument.load(absfilename.c_str(), password, &popplerError)) {
             lastError = FS(_F("Document not loaded! ({1}), {2}") % filename.string() % popplerError->message);
             g_error_free(popplerError);
             unlock();
```

**Related issues**
https://github.com/xournalpp/xournalpp/issues/880 is open, which I don't understand, because to me, backgrounds always have been relative.  This is vaguely related to https://github.com/xournalpp/xournalpp/issues/1725.

**Comment by rolandlo** [comment] 2020-09-09 10:39
Issue #880 is closed now. It was left open by mistake. The file format supports absolute and relative paths (attach mode) and it has been fixed in PR #2106.

**Comment by Febbe** [comment] 2020-09-13 13:41
Thank you for your bug report,
this bug is a regression due our change from the glib filesystem library to c++17 `std::filesystem`.
I am investigating, if it's because this part still uses a mixture of glib fs and std::fs or if the conversion to a canonical path is lost due to the switch.

**Closed** 2020-09-13 18:13 UTC
Labels: bug

**Comment by rolandlo** [comment] 2021-03-10 08:36
@stheid According to my tests this should be fixed in [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly). So please try it out (for instance with the `AppImage`)

**Comment by stheid** [comment] 2021-03-10 12:35
Thanks for the blazing fast replay. i think the bug is generally fixed, but xournalpp is generally still very unstable with regard to the "background.pdf". 

xopp files with relative paths seem to work with 1.0.20 without a problem, however 1.1.0 tells me it cannot find the background pdf when starting in the ui. in the console this yields to a crash.

perhaps an easy fix would be, to allow the user to pass the background file through another command line flag. I have 80 pdfs to export and it would be very helpful to have any workarround to do that combining in an automatic manner.

Summary:
1.0.20 : UI works fine, console crashes with the above error
1.1.0: UI asks for background file, console crashes accordingly [errorlog.20210310-133449.log](https://github.com/xournalpp/xournalpp/files/6115807/errorlog.20210310-133449.log)

**Comment by rolandlo** [comment] 2021-03-10 12:39
@stheid 
Can you please tell, what command you used from the console, and share a sample xopp-file with background pdf to reproduce this crash in 1.1.0?

**Comment by stheid** [comment] 2021-03-10 12:48
# Steps to reproduce
1. take any pdf
2. annotate with xournalpp 1.0.20
3. pdf and xopp file to another folder
4. open xopp with xournalpp 1.0.20 -> everything looks fine
5. open xopp with xournalpp 1.1.0 -> "select background pdf" dialog

# example
however it might be better to reproduce it as i described it above because the bug is file path sensitive
[2226.zip](https://github.com/xournalpp/xournalpp/files/6115862/2226.zip)

**Comment by Rmano** [comment] 2021-03-10 12:51
I did also a bit of experimenting here --- I think that the problem in attach mode is that the file name is fixed and depends on the main file name. 
This is sometimes useful, but sometimes it creates problems. I think that having the possibility to have the PDF background specified as "relative" (nor attach, nor absolute) would be great especially when editing files on a shared volume. See https://github.com/xournalpp/xournalpp/issues/2736#issuecomment-788988466

**Comment by stheid** [comment] 2021-03-10 13:00
i think the issue you linked is exactly what happened here. Is there any chance for me to create a workarround? fix the xopp files with a console script using unzipping and modifying or so? for 80 pdfs i would rather read into it a little than doing it manually.

**Comment by rolandlo** [comment] 2021-03-10 13:10
We are getting off-topic. I agree that a relative filename mode would be useful. This should be discussed in #2736 though, for which I will make the title more precise.
