### ISSUE TITLE
Keyboard shortcuts are all disabled when menubar is hidden, and not in fullscreen

### ISSUE THREAD

**Issue by gi1242** [xournalpp/xournalpp#2215] opened 2020-09-04 13:51 UTC
**Affects versions :**
 - OS: Linux Debian/buster
 - (Linux only) Desktop environment: *fvwm under X*
 - Which version of libgtk do you use: *libgtk-3.0 version 3.24.5-1*
 - Version of Xournal++: *1.0.18~git20200415.1911-nogitfound-buster-1*
 - Installation method: *dpkg -i using official .deb release.*

**Describe the bug**
* Hide the menubar (not in full screen)
* All keyboard shortcuts stop working. `Ctrl Z`, `Ctrl S`, etc. Everything.

**To Reproduce**
1. Hide the menubar (without entering fullscreen).
2. Press any keyboard shortcut
3. Nothing happens.

**Expected behavior**
Keyboard shortcuts should work. Or at least those like `ctrl-S`, `ctrl-Z`, etc. (If the `alt-F` menu shortcuts don't work, that might be understandable.)

More intuitive would be to show the menubar when the user holds `alt`. (This is the approach taken by Firefox, and many other programs.) I don't know if this is easy to implement or not.

**Comment by rolandlo** [comment] 2020-09-07 20:31
This is a duplicate of #2082.

**Closed by rolandlo** 2020-09-07 20:31 UTC
Labels: bug
