### ISSUE TITLE
Recorder could not be started on MacOS

### ISSUE THREAD

**Issue by MahdeenSky** [xournalpp/xournalpp#4656] opened 2023-02-17 06:30 UTC
**Affects versions :**
 - OS: MacOS Monterey 12.5.1
 - Version of Xournal++: 1.1.3
 - Installation method: official release

**Describe the bug**
Recorder could not be started.

**To Reproduce**
1. Set storage folder for audio to Downloads in preferences.
2. Press start recording from the edit dropdown box.

**Expected behavior**
start recording successfully.

**Screenshots of Problem**
<img width="972" alt="Screen Shot 2023-02-17 at 1 21 35 AM" src="https://user-images.githubusercontent.com/49484385/219565051-ccbf2fce-c914-4906-9c31-04be6ffdc79e.png">
<img width="236" alt="Screen Shot 2023-02-17 at 1 21 52 AM" src="https://user-images.githubusercontent.com/49484385/219565096-9001833b-ef40-49cb-b8df-91bab4c06d5c.png">

**Additional context**
I gave it permission to be able to access the downloads folder, so it shouldn't be a permission issue either.
I also tried running it from the terminal to see the logs, and the relevant bits show up as 
```
** (xournalpp:74064): WARNING **: 01:27:39.473: VorbisConsumer: output file "/Users/me/Downloads/2023-02-17_01-27-39.ogg" could not be opened
caused by:File contains data in an unimplemented format.

(xournalpp:74064): Gtk-CRITICAL **: 01:27:39.484: gtk_toggle_tool_button_set_active: assertion 'GTK_IS_TOGGLE_TOOL_BUTTON (button)' failed

** (xournalpp:74064): WARNING **: 01:27:39.484: Recorder could not be started.
```

**Comment by rolandlo** [comment] 2023-02-17 06:40
That was known, although I couldn't find a ticket about it, so thanks for opening one. We'll have to investigate.

**Comment by CodeforEvolution** [comment] 2023-02-19 01:15
Confirmed in macOS Catalina 10.15.7 too with version 1.1.3 of Xournal++.

Furthermore, I think I found the reason why:
https://github.com/xournalpp/xournalpp/blob/53ddf0c21efb1d3c84e705de30a248108c5a21f0/mac-setup/build-sndfile.sh#L13

Tracing through the VorbisConsumer class, and up to libsndfile, I realized that the "...File contains data in an unimplemented format." portion of the VorbisConsumer's error message was simply because libsndfile isn't built with libogg, nor libvorbis on macOS...

**Comment by rolandlo** [comment] 2023-02-19 06:45
Thanks for investigating. The `build-sndfile.sh` script was actually replaced in https://github.com/xournalpp/xournalpp/pull/4371/files (see xournalpp.modules), but the issue is still the same. Instead of using `-DENABLE_EXTERNAL_LIBS=off` 

> ENABLE_EXTERNAL_LIBS - enable Ogg, Vorbis, FLAC and Opus support. This option is available and set to ON if all dependency libraries were found.

we must first build [libogg](https://github.com/xiph/ogg), [libvorbis](https://github.com/xiph/vorbis), [libflac](https://github.com/xiph/flac) and [libopus](https://github.com/xiph/opus) and set `-DENABLE_EXTERNAL_LIBS=on`.

**Comment by rolandlo** [comment] 2023-02-20 08:33
I have updated `xournalpp.modules` as described in the last post and built and uploaded the resulting gtk-blob. Locally (on my MacBook Pro) it works fine now.
The next nightly build should have working audio recording on MacOS. We just need to wait a day or two.

**Comment by rolandlo** [comment] 2023-02-20 14:10
The [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly), that I triggered manually just an hour ago, already has working audio recording on MacOS. I'm closing the issue therefore.

**Closed by rolandlo** 2023-02-20 14:10 UTC
Labels: bug, os::mac, confirmed
