### ISSUE TITLE
Failed to initialize PDF Cairo surface

### ISSUE THREAD

**Issue by riemarc** [xournalpp/xournalpp#3939] opened 2022-04-02 18:18 UTC
**Affects versions :**
 - OS: Ubuntu 20.04
 - Version of Xournal++: 1.1.1+dev

**Describe the bug**
I convert a lot of xopp files to pdf with `xournalpp in.xopp -p out.pdf`.
For some files I have the issue https://github.com/xournalpp/xournalpp/issues/3388.
Means I get the ouput
```
** (xournalpp:52280): ERROR **: 20:08:11.652: Failed to initialize PDF Cairo surface
Cairo error: invalid tag name, attributes, or nesting
Trace/breakpoint trap (core dumped)
```
The issues https://github.com/xournalpp/xournalpp/issues/3388 sounds like that the reason is well understood. Can you help me out to avoid this issue?

There are no issues, when I use the xournalpp-gui to export the pdf.

**Comment by bhennion** [comment] 2022-04-05 20:27
@riemarc Thanks for reporting this!
I can't reproduce. Two things:

- Would you have a file you could share (either here or with me privately) for which the crash happens?
- What is your locale (the output of `echo $LANG` in a terminal should do it)?

**Comment by riemarc** [comment] 2022-04-06 08:33
* The xopp file takes a pdf as background: [example.zip](https://github.com/xournalpp/xournalpp/files/8425022/example.zip). I have to admit that it was not to easy to generate a pseudo-background pdf file, which also causes this bug.
* local is *en_US.UTF-8*

**Comment by bhennion** [comment] 2022-04-06 11:54
@riemarc Could you try the installer available in [this post](https://github.com/xournalpp/xournalpp/pull/3944#issuecomment-1090118049) and report back?
If I understand correctly what's happening, the issue should be fixed in this version

**Closed** 2022-04-08 18:10 UTC
Labels: bug, priority::high, Input, PDF

**Comment by Doofitator** [comment] 2022-09-17 06:59
So I know this issue was closed months ago, but I've come across a similar problem and Google lead me here.

I'm running Fedora 36, so the installers referenced a few comments ago (even if they're still available for download) won't work - there's no .rpm version.

I've installed xournalpp from flatpak, which makes the command-line experience just _wonderful_, but nevertheless I'm running into the exact error as above:

    $LANG=C flatpak run com.github.xournalpp.xournalpp -p myfile.xopp myfile.pdf
    Gtk-Message: 16:29:45.851: Failed to load module "xapp-gtk3-module"
    
    ** (xournalpp:2): ERROR **: 16:29:45.886: Failed to initialize PDF Cairo surface
    Cairo error: error while writing to output stream

Figuring flatpak was at fault, I tried the AppImage from the releases page:

    $LANG=C ~/Applications/xournalpp-1.1.1-x86_64_f003447a6eaae80c404e7d751e660b4b.AppImage -p myfile.xopp myfile.pdf
    /usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
    Gtk-Message: 16:40:26.916: Failed to load module "xapp-gtk3-module"
    
    ** (AppRun.wrapped:11935): ERROR **: 16:40:26.958: Failed to initialize PDF Cairo surface
    Cairo error: error while writing to output stream,

Then I discovered that xournalpp is in Fedora's default repos (how did I not know this before??), so one `dnf in xournalpp -y` later, we had another version to try:

    $LANG=C xournalpp -p myfile.xopp myfile.pdf
    ** (xournalpp:13048): ERROR **: 16:53:03.879: Failed to initialize PDF Cairo surface
    Cairo error: error while writing to output stream

Now as the latest release was put out in February, and this issue wasn't raised until April, I'm assuming my woes are as a result of the fix not being implemented in the current release. Is that right? In that case, do I need to build Xournal++ from source in order to write PDFs from cli? I'm aware the error message is not exactly the same (`error while writing error while writing to output stream` as opposed to `invalid tag name, attributes, or nesting`) so I don't know if the issues are exactly related or not. I figure it can't hurt to comment here and see if anyone more knowledgeable than me has any idea what's going on.

**Comment by bhennion** [comment] 2022-09-17 08:11
@Doofitator I do not think your issue is the same as the one referenced in this ticket. It looks like you have a writing rights problem. Do you have writing permission in this directory?

If this was not the problem, then you can try building the latest git version from source, see if this fixes it, and report in a new issue if it does not.

**Comment by Doofitator** [comment] 2022-09-18 05:51
@bhennion I should imagine I have write permissions for my home directory - I can now say that I have built from source to no avail. I'll have to do some more investigating and make a new issue later this evening. Will keep you posted.
