### ISSUE TITLE
Zooming in with Ctrl+Scroll causes the document to scroll down

### ISSUE THREAD

**Issue by cfalas** [xournalpp/xournalpp#1753] opened 2020-02-28 21:05 UTC
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: X11
 - Which version of libgtk do you use: 3.24.14+9+g429a6287e0-1
 - Version of Xournal++: 46a4dc82
 - Installation method: Arch User Repository

**Describe the bug**
Whenever I try to zoom in by pressing Ctrl + scrolling up/down with the scroll wheel, the document does zoom in/out, but also scrolls. This happens with both a mouse, and a touchpad. On small documents, this is not so important, but when using larger documents, it is more noticeable.
Zooming in with touchscreen works perfectly

**To Reproduce**
1. Make a new journal with many pages
2. Press Ctrl and use the scroll wheel to zoom in

**Expected behavior**
I would expect the document to zoom like it does, but stay focused on the same page

**Screenshots of Problem**
![xournal](https://user-images.githubusercontent.com/34488895/75587115-6f6cc580-5a7e-11ea-9706-8abaa9e5ff84.gif)
Initially on page 5, zooming causes it to go to page 10

**Additional context**
I have this issue ever since I started using Xournal++ (about october 2019)

**Comment by mabachel** [comment] 2020-03-02 10:35
I can confirm this issue on Xournal++ 1.0.16 (built on Jan 12, 2020) installed via dnf (Fedora 31).

But for me it seems to be reversed:

Zooming in via the + button I end up further up in the document. While zooming out leads to scrolling down. This gets worse with larger documents. The more pages the documents has the more it scrolls with a single zoom stop.

**Comment by beat** [comment] 2020-03-04 16:57
I can confirm this same anoying issue, and also reversed. It is maybe reversed, because I have the scroll reversed ("natural way") ?

It started happening a few days ago, but the upgrade happened on Feb 23:

`Unpacking xournalpp (1.0.6-0~202002180641~ubuntu19.10.1) over (1.0.6-0~202002052134~ubuntu19.10.1) ...`

Using the Ubuntu repository tracking github releases:
`deb http://ppa.launchpad.net/andreasbutti/xournalpp-master/ubuntu eoan main`

**Comment by Febbe** [comment] 2020-03-04 17:52
I can confirm this issue, but it is already addressed by @Technius refactoring of the xournal widget, layouting and zoom control. 
Both of the actions are executed: Zoom and scroll.

**Comment by beat** [comment] 2020-03-04 18:58
Cool! Thanks @Febbe and @Technius ! Is there another issue # or a PR link to track when this is done ?

Not sure if that was a side-issue: It actually started happening when Gnome 3 desktop (Ubuntu 19.10) crashed (for a separate unknown reason) and the X window and Gnome restarted. Sometimes Xournal survives that event, and sometimes not! Would be cool that Xournal survives, or at least does an autosave before dying.

**Comment by Technius** [comment] 2020-03-05 00:51
> I can confirm this issue, but it is already addressed by @Technius refactoring of the xournal widget, layouting and zoom control.
Both of the actions are executed: Zoom and scroll.

Just to clarify, this issue *hasn't* been fixed yet, but the plan is to fix it in the refactor. I've been **very** busy recently, but I'm hoping to continue in a few weeks.

> Cool! Thanks @Febbe and @Technius ! Is there another issue # or a PR link to track when this is done ?

Yes, check out #1433. I think about 50% of that ticket has been addressed by the current refactoring (`view-rewrite` branch), but the ticket doesn't encompass the whole scope of the refactor.

> Not sure if that was a side-issue: It actually started happening when Gnome 3 desktop (Ubuntu 19.10) crashed (for a separate unknown reason) and the X window and Gnome restarted. Sometimes Xournal survives that event, and sometimes not! Would be cool that Xournal survives, or at least does an autosave before dying.

This could potentially be caught with some additional programming, but I'm not 100%.

**Closed** 2020-04-06 18:20 UTC
Labels: bug, confirmed
