### ISSUE TITLE
"Loading..." screen flashes when changing pages in PDF annotation

### ISSUE THREAD

**Issue by rosulek** [xournalpp/xournalpp#1477] opened 2019-09-17 19:02 UTC
**Affects versions :**
 - OS: Linux/ubuntu
 - version: all? certainly affects latest build from 88064cc, and release 1.0.13

**Describe the bug**
When annotating a PDF and switching between pages, the entire page is momentarily replaced by a big white screen with "Loading...".

I am using xournalpp to record video lectures where I advance through PDF slides and annotate them with the pen tools. This loading screen issue is particularly distracting because my slides have black background and the "Loading" screen is white.

**To Reproduce**
1. choose a PDF (preferably with dark background and many pages) to annotate
2. step forward/backwards using "previous/next page" toolbar buttons or PgUp/PgDn

Note: The "Loading" screen doesn't show for **every** page change, but only much of the time.

**Expected behavior**
Seamless transition between two PDF pages

**Screenshots of Problem**
![gif](https://imgur.com/dVy2l8F.gif)

**Comment by LittleHuba** [comment] 2019-09-17 20:57
Another problem related to #1405

**Comment by rosulek** [comment] 2019-09-17 21:02
The discussion on #1405 led me to believe that it was fixed in commit 7a521bf, but I still see the issue when compiling the latest from main branch.

**Comment by LittleHuba** [comment] 2019-09-17 21:17
I think it is only a partial fix. The problem is that the current rendering system does not prerender anything and the cache cleaning is very agressive.
Both actually lead to a number of additional issues. We will have to tackle both to get a satisfactory fix for this issue.

**Comment by JJones780** [comment] 2019-09-18 12:45
Thanks for pointing this out...  My comment in 1405 about other potential quirks.... you've confirmed one of them. 

#1405 was the same pages flashing. This was when switching between pages.

Turns out the pagebuffer clearing algorithm was reverse..  it's clearing more recent pages first... resulting in the behaviour you are noticing.

It leaves at least 4 "hidden page" buffers valid but aggressively clears out any more than that.

I'm too tired to trust myself to merge anything so I'll post the PR and follow through tomorrow.

**Comment by JJones780** [comment] 2019-09-19 03:45
Tested the background buffer and looked into the bug history (since 2011).

For the record: Here's the list of <visible>, [buffered] and {unbuffered} pages as I scrolled down from 0 to 15 with 2 and sometimes 3 pages visible at a time:
```
<0>  <1>  [2]  [3]  [4]  [5]  [6]  {7}  {8}  {9}  {10}  {11}  [12]  [13]  {14}  [15]  {16}  {17}
[0]  <1>  <2>  [3]  [4]  [5]  [6]  {7}  {8}  {9}  {10}  {11}  [12]  [13]  {14}  [15]  {16}  {17}
[0]  [1]  <2>  <3>  [4]  [5]  [6]  {7}  {8}  {9}  {10}  {11}  [12]  [13]  {14}  [15]  {16}  {17}
[0]  [1]  [2]  <3>  <4>  [5]  [6]  {7}  {8}  {9}  {10}  {11}  [12]  [13]  {14}  [15]  {16}  {17}
[0]  [1]  [2]  [3]  [4]  [5]  <6>  <7>  {8}  {9}  {10}  {11}  [12]  [13]  {14}  [15]  {16}  {17}
[0]  [1]  [2]  [3]  [4]  [5]  [6]  <7>  <8>  {9}  {10}  {11}  {12}  [13]  {14}  [15]  {16}  {17}
[0]  [1]  [2]  [3]  [4]  [5]  [6]  [7]  [8]  <9>  <10>  [11]  {12}  [13]  {14}  {15}  {16}  {17}
{0}  [1]  [2]  [3]  [4]  [5]  [6]  [7]  [8]  [9]  [10]  <11>  <12>  {13}  {14}  {15}  {16}  {17}
{0}  {1}  {2}  [3]  [4]  [5]  [6]  [7]  [8]  [9]  [10]  [11]  <12>  <13>  <14>  {15}  {16}  {17}
{0}  {1}  {2}  {3}  [4]  [5]  [6]  [7]  [8]  [9]  [10]  [11]  [12]  <13>  <14>  {15}  {16}  {17}
{0}  {1}  {2}  {3}  {4}  [5]  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
{0}  {1}  {2}  {3}  {4}  {5}  [6]  [7]  [8]  [9]  [10]  [11]  [12]  [13]  <14>  <15>  {16}  {17}
```
One can see that it stops reclaiming buffers so that there are always 12 buffers allocated in this case.  
This will be at minimum 5 offscreen buffers (when buffers are large) in addition to ALL pages visible. 

more next comment...

**Comment by JJones780** [comment] 2019-09-19 03:49
Memory Use Worst Case Scenario:
The maximum memory allocated in "worst case" scenario would be 
maximum page size 
+ maximum zoom 
+ 4 visible pages ( just their corners visible) 
+ min 4 offscreen buffers
 = giving us 8 allocated pixbuffers.
x 16mb each

**But.. if we bump up the Prefs->Zoom->DisplayDPICalibration to 400 it becomes 502MB each !!**


I'll open an issue about this - I don't intend to guard against this in this PR.

**Closed** 2019-09-19 03:53 UTC
Labels: bug

**Comment by michaelcadilhac** [comment] 2020-07-23 02:48
I don't believe that this is solved.  I still get the Loading… message fairly often, which is disrupting in a presentation.

**Comment by michaelcadilhac** [comment] 2020-07-26 00:50
So I guess my problem is that there's no preemptive load of the next page, which in the context of a presentation, is much needed.  I've temporarily butchered that in the clearMemoryTimer, calling the rerender of the page after the current one.  (Is there a logical place for that hack, rather than there?  This obviously doesn't work if I'm going through a fast-paced animation slide by slide.)

As we're on the topic, I'm reporting two interesting (?) quirks.  Consider the trace below, using the same syntax as JJones780, and printing before and after the purge:
```
Loading document:
  BEFOR: <0> {1} {2} {3} {4} {5} {6} {7} {8} {9} {10} {11} {12} {13} {14} {15} {16} {17} {18} {19} 
  AFTER: <0> {1} {2} {3} {4} {5} {6} {7} {8} {9} {10} {11} {12} {13} {14} {15} {16} {17} {18} {19} 
quickly scroll to EOF (less than 5 seconds):
  BEFOR: [0] [1] [2] {3} [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] [16] [17] [18] <19> 
  AFTER: {0} {1} {2} {3} {4} [5] [6] [7] [8] [9] {10} {11} {12} {13} {14} {15} {16} {17} {18} <19> 
go back one slide:
  BEFOR: {0} {1} {2} {3} {4} [5] [6] [7] [8] [9] {10} {11} {12} {13} {14} {15} {16} [17] <18> {19} 
  AFTER: {0} {1} {2} {3} {4} [5] [6] [7] [8] {9} {10} {11} {12} {13} {14} {15} {16} {17} <18> {19} 
```
The two weirdities:
1. After all pages were loaded (all square brackets),  pages 5-9 are the one saved from the purge, instead of (one would expect) 15-18.
2. Going back one slide to slide 18 loads slide 17, but it gets immediately trashed (together with slide 9, which is consistent with point 1).  This is recurring.

**Comment by michaelcadilhac** [comment] 2020-09-08 23:14
FYI, I have been using that snippet with all my recordings this session, and it seems to be working fine.  Can something similar be considered for inclusion?
