### ISSUE TITLE
Allow configuring default paper background

### ISSUE THREAD

**Issue by Esokrates** [xournalpp/xournalpp#3003] opened 2021-04-05 09:02 UTC
**Is your feature request related to a problem? Please describe.**
Everytime xournalpp is started, the default paper background is "Ruled with vertical line" which I never use.
I wish to just use a Graph background. Having to adjust this every time is annoying.

**Describe the solution you'd like**
In the settings there is a "Defaults" category which is pretty sparse. I think an option to configure the default paper background would fit in well.

**Comment by rolandlo** [comment] 2021-04-05 09:05
Duplicate of #2191

**Closed by rolandlo** 2021-04-05 09:05 UTC
Labels: enhancement

**Comment by Esokrates** [comment] 2021-04-05 09:19
@rolandlo Thanks for pointing out the duplicate, I guess I was too fast when looking over the existing bugs. Thanks very much and sorry for the duplicate.
