### ISSUE TITLE
Slow saving with large files, is it possible to speed it up?

### ISSUE THREAD

**Issue by tubbadu** [xournalpp/xournalpp#4091] opened 2022-06-14 15:30 UTC
**Is your feature request related to a problem? Please describe.**
When dealing with a large file with a lot of drawings, everytime that I click save it takes some time so save, the bigger the file the longer the time taken to save, so It is really difficult for me to take long notes in a single page, and I need to split it in multiple lightes files.

**Describe the solution you'd like**
Is it possible to speed this up a bit? for example, the file may be an archive with every page as a different file, so that saving the document will only overwrite the modified pages?

**Describe alternatives you've considered**
I know it's a mess to change the save format but I can't think of other ways of doing it, but it would be really nice for long notes (for example if I would like to take all semester notes in a single files, so that it become easier to check them all without jumping from a file to another one

**Comment by bhennion** [comment] 2022-07-21 18:10
Closing as duplicate of #3915

**Closed by bhennion** 2022-07-21 18:10 UTC
Labels: enhancement
