### ISSUE TITLE
Crash when zooming in and out of a document with different page sizes

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#1897] opened 2020-04-22 18:44 UTC
**Affects versions :**
Linux Ubuntu 18.04, xournalpp 8cd6b0be 

**Describe the bug**
Crash when zooming in and out of a document with different page sizes

**To Reproduce**

1. Open the attached `twosizes.pdf`
[twosizes.pdf](https://github.com/xournalpp/xournalpp/files/4518352/twosizes.pdf)

2. Go to the second page (click on it, or scroll down)
3. Zoom clicking on 
![image](https://user-images.githubusercontent.com/6414907/80019624-206c6b00-84d8-11ea-8ff9-260638f7fde2.png)
4. Draw something / move up down 

`xournalpp` freezes a while and then errors out with:

```
** (xournalpp:8387): WARNING **: 20:32:32.011: Error calculating zoom value
[1]    8387 segmentation fault (core dumped)  xournalpp twosizes.pdf
```

**Screenshots of Problem**

It's  a bit big... let's see:

![ezgif com-resize](https://user-images.githubusercontent.com/6414907/80020649-ab9a3080-84d9-11ea-8be8-4fab8f24748d.gif)

**Additional info**

It happened several times to me. Now I understand the pattern (for example, I had to review a stiched PDF wich changed form lettersize to A4 to random figure sizes, and sometime `xournalpp` crashed on me).

**Comment by Technius** [comment] 2020-04-22 21:05
Duplicate of #1660.

**Closed by Technius** 2020-04-22 21:05 UTC
Labels: bug
