### ISSUE TITLE
Error: Signal 11

### ISSUE THREAD

**Issue by avidseeker** [xournalpp/xournalpp#4923] opened 2023-06-10 10:57 UTC
- OS: Arch Linux
 - libgtk: 3.24.38
 - Version of Xournal++: 1.1.3+dev (b1041980)
 - Manual compilation

Stack trace: https://paste.debian.net/1282564/

**Comment by bhennion** [comment] 2023-08-08 16:22
This is going to be very difficult to track down. Does it happen often (with a similar backtrace)?

**Comment by bhennion** [comment] 2023-10-04 06:19
This is most likely a duplicate of #4931

**Closed by bhennion** 2023-10-04 06:19 UTC
Labels: bug, Crash
