### ISSUE TITLE
Shortcuts configuration menu

### ISSUE THREAD

**Issue by Globulle** [xournalpp/xournalpp#2938] opened 2021-03-12 13:08 UTC
**Is your feature request related to a problem? Please describe.**
I'm frustrated by not being able to customizing or adding shortcuts. For example, I would like to select red color by simply pressing the R key.

**Describe the solution you'd like**
A menu to configure shortcuts should be useful.

**Comment by rolandlo** [comment] 2021-03-12 13:12
Duplicate of 919.

**Closed by rolandlo** 2021-03-12 13:12 UTC
Labels: enhancement

**Comment by Globulle** [comment] 2021-03-12 14:04
Sorry, I did my best to find a previous similar issue but I missed this one...
