### ISSUE TITLE
Support of importing .one files

### ISSUE THREAD

**Issue by CountOmega** [xournalpp/xournalpp#3671] opened 2021-12-17 04:55 UTC
First of all, hats off to you guys for making such a great note taking app. A nice feature addition would be the ability to import .one packages. Evernote and [aspose](https://blog.aspose.com/2021/10/14/convert-onenote-word-java/) support this. For many people this would be a valid reason to finally to switch to linux. I don't exactly know how these files store data, but I'd be happy to test and debug.

**Comment by rolandlo** [comment] 2021-12-18 04:08
Duplicate of #2237.

**Closed by rolandlo** 2021-12-18 04:08 UTC
Labels: enhancement
