### ISSUE TITLE
Adding Xournalpp to Debian repositories

### ISSUE THREAD

**Issue by pktiuk** [xournalpp/xournalpp#2148] opened 2020-08-06 18:51 UTC
I have heard about the ongoing process of adding Xournal++ to official Debian repositories, but there is not much progress in this matter for a long time. [link](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927076)

This idea seems to be abandoned, there is not much work done in this matter, even the package is not ready yet, so I created this issue to monitor the progress of adding Xournal++ to Debian packages, starting from preparing `.deb` the package according to official guidelines.
Later it could be used for tracking long [process of adding package](https://www.debian.org/doc/manuals/developers-reference/pkgs.html#newpackage).

Things to do:
- [x] prepare package (the easiest way of checking what should be done is by using [lintian](https://en.wikipedia.org/wiki/Lintian) )
- [x] find maintainer (maybe we should firstly ping someone who was involved in the first attempt)
- [x] add package

**Comment by pktiuk** [comment] 2020-08-06 18:53
In terms of preparing package, I have just submitted an issue solving part of Errors from lintian, after acceptance report will look like this:
```
E: xournalpp: latest-changelog-entry-without-new-date
E: xournalpp: no-copyright-file
E: xournalpp: unstripped-binary-or-object usr/bin/xournalpp
W: xournalpp: binary-without-manpage usr/bin/xournalpp
W: xournalpp: binary-without-manpage usr/bin/xournalpp-thumbnailer
W: xournalpp: non-standard-dir-perm usr/ 0775 != 0755
W: xournalpp: non-standard-dir-perm usr/bin/ 0775 != 0755
W: xournalpp: non-standard-dir-perm usr/share/ 0775 != 0755
W: xournalpp: non-standard-dir-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: xournalpp: script-not-executable usr/share/xournalpp/ui/icons/hicolor/update-icon-cache.sh
W: xournalpp: script-not-executable usr/share/xournalpp/ui/iconsDark/hicolor/update-icon-cache.sh
```

I would like to ask somebody, who is longer involved in this project (and knows its history) about preparing `copyright` file, which could be later included in package
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

We should also think about dealing with copyright files, we can try to make some conversion tool, which would generate proper Debian-styled changelogs from the current main changelog, or just do it manually before every release (maybe someone knows any tool, which could do it).

**Comment by pktiuk** [comment] 2020-08-06 19:12
4. Could anyone explain me why there ate two distinct `.deb` files for Ubuntu and Debian?

**Comment by Febbe** [comment] 2020-08-06 19:38
They link against the different versions provided by Debian and Ubuntu.

**Comment by pktiuk** [comment] 2020-08-06 20:15
They link against different versions of what?
I thought that every package working in Debian should work in Ubuntu (because most of packages on Ubuntu are imported from Debian repositories).

**Comment by Technius** [comment] 2020-09-19 21:10
No, [Ubuntu and Debian are not binary compatible](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian). Ubuntu may make packaging changes when it ports over packages. For example, Ubuntu 20.04 uses `libzip5` for libzip instead of `libzip4` on Debian and earlier Ubuntu versions, which has been a major source of headaches for us. This is why we provide different deb packages for Ubuntu and Debian.

Thanks for your PR, I'll take a look at that in the upcoming days.

**Comment by apandada1** [comment] 2020-09-20 09:08
We can add `libzip5 | libzip4` to `depends` in the control file to fix the incompatibility. Then the package manager will search for whichever one of these is available.

**Comment by rolandlo** [comment] 2020-12-22 10:44
According to the Debian maintainer interested in adding Xournal++ to the Debian repository, the (only) issue is the copyrights file:

> The situation now is that the *only* sticking point is
> debian/copyright, which is a mess. Note all the "god knows" entries.
> And the providence of a bunch of the .svg files is unclear, with
> internal copyright strings embedded in them giving various flavours of
> CC. Some of which might need to be replaced if they're the wrong
> flavours; fortunately there are collections of appropriate open source
> .svg icons that could be used instead if it comes to that.
> 
> If someone were to help with getting the copyright info worked out, I
> can slot it straight into Debian. But there were so many little moving
> parts I just couldn't clear an entire day to try and figure it all
> out. Someone more familiar with the code base and its history would
> probably have a much easier time of it.
> 
> --Barak.
> 
> PS I'm using xournalpp in teaching this semester. Got a new Dell
> Inspiron 15 7591 2in1 with a pressure sensitive pen enabled screen,
> and it's great for remote teaching.

We should try to resolve the situation. 
For the original post see [this link](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927076)

**Comment by rolandlo** [comment] 2020-12-22 21:09
The mess the in the debian/copyright file from the quote above refers to [this file](https://github.com/barak/xournalpp/blob/debian/debian/copyright) in the maintainer's fork (debian branch)

**Comment by rolandlo** [comment] 2020-12-22 22:13
What I can say using `GitLens` FileHistory in VS Code:

> Files: src/util/hashcombine.h
> Copyright: 2020 God Knows
> License: BOOST
> 
> 

The file `hashcombine.h` was added via PR #1238 by @Febbe (code) in f4e4fcff86611e76a391f41900199a7bd58a14e5 and @LittleHuba (license) in 7d1435c784587555d114006cbc294eee1916a070

> 
> Files: *.svg
> Copyright: 2020 God Knows
> Comment: These have license metadata
> License: CC
> 
> Files: ui/iconsDark/hicolor/scalable/actions/audio-playback-pause.svg
>        ui/iconsDark/hicolor/scalable/actions/audio-playback-stop.svg
>        ui/icons/hicolor/scalable/actions/audio-playback-pause.svg
>        ui/icons/hicolor/scalable/actions/audio-playback-stop.svg
>        ui/icons/hicolor/scalable/actions/audio-record.svg
>        ui/icons/hicolor/scalable/actions/fullscreen.svg
>        ui/icons/hicolor/scalable/actions/grid_snapping.svg
>        ui/icons/hicolor/scalable/actions/snapping.svg
>        ui/icons/hicolor/scalable/actions/tool_camera.svg
> Comment: These have no license fields so appear to be under the overarching project license.
> Copyright: 2020 God Knows
> License: GPL-2+
> 

- the 4 svg-files related to audio were added via PR #922 by @LittleHuba in 334d125e31b4d6647fb1010e9951649e01ce0ee0, 
- the fullscreen svg-file was added via PR #890 by @andreasb242 in f177d940655b780736f19eb2e8ddd0132754d12c, 
- the 2 icons related to snapping were also added via PR #890 by @andreasb242 in b47c587a4e74a7a475325b88955dc6bae861e467 Their dark counterparts contain the `xmlns:cc="http://creativecommons.org/ns#"` tag. Moreover there is a comment in the code that reads 

> // Icon snapping.svg made by www.freepik.com from www.flaticon.com
On www.flaticon.com one finds a so called Flaticon license.

- the tool_camera svg-file was also added via PR #890 by @andreasb242 in f177d940655b780736f19eb2e8ddd0132754d12c

**Comment by LittleHuba** [comment] 2020-12-23 00:46
My SVGs from back then were hand made by me. Hence same license as Xournal++.

**Comment by andreasb242** [comment] 2021-01-05 17:26
>the tool_camera svg-file was also added via PR #890 by @andreasb242 in f177d94

This is from Humanity Theme in Ubuntu:
https://raw.githubusercontent.com/andreasb242/xournalpp/b47c587a4e74a7a475325b88955dc6bae861e467/ui/icons/hicolor/scalable/actions/tool_camera.svg

Ubuntu 18.04 still contains this Icon, with a little change: The LED at the Botton is new.
![grafik](https://user-images.githubusercontent.com/822958/103677991-4876fe00-4f83-11eb-9ce4-54eaa18fe1f9.png)

/usr/share/icons/Humanity/devices/48/camera-photo.svg

License: GPL v2
http://changelogs.ubuntu.com/changelogs/pool/main/h/humanity-icon-theme/humanity-icon-theme_0.6.15/copyright

**Comment by andreasb242** [comment] 2021-01-05 17:28
>the fullscreen svg-file was added via PR #890 by @andreasb242 in f177d94,
Also Humanity:
https://raw.githubusercontent.com/andreasb242/xournalpp/b47c587a4e74a7a475325b88955dc6bae861e467/ui/icons/hicolor/scalable/actions/fullscreen.svg
![grafik](https://user-images.githubusercontent.com/822958/103678440-d2bf6200-4f83-11eb-85b1-0bd9b0bfdb4c.png)

/usr/share/icons/Humanity/actions@2/24/gtk-fullscreen.svg

**Comment by andreasb242** [comment] 2021-01-05 17:36
The grid_snapping.svg and snapping.svg icon is from Morrolinux, I only moved it:
git log --follow  ./ui/icons/hicolor/scalable/actions/grid_snapping.svg

First Commit:
commit db219f8b0554ddf51fb9ad459afc1d4de1c0ce71
Author: morro <morrolinux@gmail.com>
Date:   Mon Dec 10 11:15:30 2018 +0100

    grid snapping icon and toolbar



git log --follow  ./ui/icons/hicolor/scalable/actions/snapping.svg
First Commit:
commit 5f00cf9433e9d89cce434cfc7a116142ffef0bad
Author: morro <morrolinux@gmail.com>
Date:   Fri Dec 7 12:23:30 2018 +0100

    add rotation snapping toolbar button

**Comment by barak** [comment] 2021-01-16 14:27
Thanks for the detective work.

I pushed minor `debian/copyright` mods (a441dd04 f7ef9e4b) but couldn't get traction on the SVG files. If someone could organize the information gathered here into the appropriate format, that would forestall any future issues. When I tried to do it myself, I found the trails running cold before I got to an actual author/date. E.g., `tool_camera.svg` is apparently a minor edit of something taken from https://www.iconspng.com, but I couldn't find it there, and the [Humanity Theme copyright file]( http://changelogs.ubuntu.com/changelogs/pool/main/h/humanity-icon-theme/humanity-icon-theme_0.6.15/copyright ) has names but no dates, and I doubt they're the people who actually drew that camera SVG anyway.

Unfortunately digital forensics and archeology are not my forte...

**Comment by barak** [comment] 2021-01-16 14:30
PS Xournal++ is in the Debian "new" queue: https://ftp-master.debian.org/new/xournalpp_1.0.20-1.html awaiting approval from the ftpmaster team.

**Comment by barak** [comment] 2021-02-03 20:59
Uh oh! The package was **_REJECTED_** because of the copyright situation.

Here was the logic:
```
... Unfortunately the CC-BY-SA-2 license
is not compatible with DFSG[1], so please remove the affected file
from the source tarball.
Please also mention the files licensed under a CC-4 license.
...
[1] https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_Share-Alike_.28CC-BY-SA.29_v3.0
```
Fair enough, right?

I'd really appreciate help getting the icon copyright situation under control, so Xournal++ can make its way into Debian and then trickle down everywhere. Having Debian-specific patches to replace problematic icons seems like a bad idea: everyone wants the entire thing to be free without strings, and nobody wants the icon set to switch around. There's no shortage of large collections of free (as in really free, not some squicky sorta-free license) SVG icons. Hell, there's 1600 SVG files below /usr/share/icon on my Debian laptop, which is new and has very little installed.

Help?

**Comment by rolandlo** [comment] 2021-02-03 21:32
@barak 
The icon situation may become much simpler after #1735 has been (completed and) merged. There will be one single icon theme in two flavors (colored and monchrome) plus the Xournal++ app icon. The app icon has already been changed in version 1.1.0+dev (current master).
The current schedule intends to release version 1.1.0 at the end of this month. Would it make sense to plan for that, rather than finding solutions for version 1.0.20 and changing things again shortly thereafter?

**Comment by Technius** [comment] 2021-02-03 22:39
@barak In addition to Roland's comments, is there anything we could do to make the packaging easier in the future?

**Comment by barak** [comment] 2021-02-04 13:12
Fantastic to hear the icons are being redone anyway. Sure, can wait. I hope to get Xournal++ into the next stable release, which is firming up now, but a couple weeks delay should be okay.

Honestly, the Debian packaging scripts are pretty simple. If there's anything in my debian branch, subdir debian/, that you think should be migrated upstream, go ahead. Like, I generate a man page automatically using `help2man`, maybe that should be maintained manually and have more info in it? I dunno. But right now there are only two actual issues.

1. The file `debian/changelog` is being used as the upstream changelog, and CHANGELOG.md is also used for similar information, and this requires manual manipulation etc. Not a big deal, but for consistency it probably would make sense to keep the change log for the package proper outside of debian/.

2. Copyright and providence of files. Some people are really persnickety about tracking copyrights, and this includes the debian ftpmasters. It's usually easiest to record that kind of thing at the time. Maybe in a git commit log where the file is first added, maybe in a change log, maybe somewhere else that only copyright info is kept. But somewhere central.

**Comment by rolandlo** [comment] 2021-02-04 19:45
Thanks @barak, I would appreciate having the man page creation upstreamed.

**Comment by barak** [comment] 2021-02-05 09:32
@rolandlo, happy to do that. The man page creation is trivial, but it relies on invoking `help2man` which makes that a build dependency. And it probably makes cross-compilation a bit tricky, since it relies on running the executable at build time.

Anyway, the stanza right now is:
```make
debian/xournalpp.1:
        help2man --no-info \
                --version-string="$(DEB_VERSION)" \
                --name="Xournal++, $(shell egrep '^Description: ' debian/control | head -1 | sed 's/Description: //')" \
                ./*/src/xournalpp > $@
```
Maybe it would make sense to generate `man/man1/xournalpp.1` and keep it as a static source file installed by cmake in the usual way for man pages, and just regenerate it manually periodically using some script kept in `man/`? The advantage of `help2man` is that it keeps the `--help` text in sync with the man page. But you can add extra sections to the man page by putting fragments in files and passing them as options to `help2man`, so it's possible to keep the advantages of `help2man` while also crafting proper sections to expand out the man page, documenting things like device support, plugins, etc.

**Comment by mjg** [comment] 2021-02-20 11:06
Maybe a general remark from a Fedora maintainer (not for xournal/pp there, though):
In several projects, I see attempts to maintain debian specific packaging info or rpm spec files or such. This usually results in:

- "unnecessary" project releases for packaging updates or fixes
- distribution specific "cruft" in the (upstream) project
- seamingly general deb/spec which indeed work on specific distros only (e.g. Ubuntu/Mandriva but not Debian/Fedora)
- stale distro specific cruft once a packager loses interest

I think a clear boundary between upstream project and distro packaging helps both, as long as there is mutual communication. So by all means: upstream your distro patches if they benefit everyone, raise those copyright issues and solve them upstream in the project. But please do not do the distro specific packaging (e.g. the changelog format) within the upstream project.

**Comment by barak** [comment] 2021-02-20 11:56
Completely agree with @mjg: it's better to have distribution-specific packaging branches that contain only the packaging info, and keep it off the main branch.

That said, with git it's not too much hassle for me to merge in the upstream changes and fix up any toe-stepping on the debian/ directory manually. So it's more a "best practices" issue than a stumbling block.

Having the upstream changelog live partly in debian/changelog is a bit more of a hassle, because I don't want to lose that info. Also it's not where people would expect to see it. E.g., people running Fedora would probably not think to look there.

Copyright information really should live in AUTHORS or COPYRIGHT or something like that. Although the machine-readable format recommended for debian/copyright makes it tempting for upstream to keep things there. Maybe putting it in COPYRIGHT but in that format would be best practice? I dunno, it gets kind of fuzzy. But right now, the issue isn't so much where that info lives, as its existence at all, and more to the point, solving any copyright issues in old stray imported files.

**Comment by rolandlo** [comment] 2021-02-24 11:56
@mjg @barak 
In our case we need the debian folder for creating the Ubuntu PPA .deb packages on [Launchpad](https://code.launchpad.net/~andreasbutti/+recipe/xournalpp-daily). I guess that makes some toe-stepping inevitable. As far as I understand we need the debian/changelog there in order for the Launchpad recipe to build successfully.

About the Fedora [.spec file](https://github.com/xournalpp/xournalpp/blob/master/rpm/fedora/xournalpp.spec). Should we remove it?

**Comment by mjg** [comment] 2021-02-24 12:12
> @mjg @barak
> In our case we need the debian folder for creating the Ubuntu PPA .deb packages on [Launchpad](https://code.launchpad.net/~andreasbutti/+recipe/xournalpp-daily). I guess that makes some toe-stepping inevitable. As far as I understand we need the debian/changelog there in order for the Launchpad recipe to build successfully.
> 
> About the Fedora [.spec file](https://github.com/xournalpp/xournalpp/blob/master/rpm/fedora/xournalpp.spec). Should we remove it?

That is for Fedora's xournalpp maintainer to say.

From my perspective as a packager, the best upstream is one which does not do any bundling of libraries, is clear about changed requirements and is open to upstreaming patches. I guess that's all fine here :)

Also, from my experience as a Fedora packager, I can never rely on upstream spec files and they often go stale. I cannot maintain the file within an upstream project anyways: the changes are often related to other packages' changes or release requirements etc., so even the versioning does not make sense within the upstream package. So it seems to be unnecessary maintenance burden for upstream (you) but does not hurt (nor, in most cases, help) the downstream packager, that's all.

**Comment by apandada1** [comment] 2021-02-24 12:30
The stable PPA maintainer here.
Deleting `debian/` would break the nightly releases PPA. The stable PPA can still be manually built using the existing `debian/` template.

I have a request towards everyone. Please keep the `debian/` directory until the package is included in the official debian repositories (after which PPAs won't be essential anymore, because then xournalpp could be installed straight in Ubuntu and derivatives). 

Right now, the `debian/` directory does not require any maintenance as such. So, let's wait until xournalpp gets included in Debian.

**Comment by barak** [comment] 2021-02-24 13:29
@apandada1 That sounds ideal! I've been trying to push it into Debian proper, but copyright issues in SVG files and such have been getting in my way. (And we just missed the strike date for the next stable release.)

Please do feel free to snarf anything from debian/ on my packaging branch if that makes sense for the PPA. Certainly I've plundered yours!

**Comment by rolandlo** [comment] 2021-02-24 15:09
> I have a request towards everyone. Please keep the `debian/` directory until the package is included in the official debian repositories (after which PPAs won't be essential anymore, because then xournalpp could be installed straight in Ubuntu and derivatives).

Having the package included in the official debian repository may make the stable PPA inessential, but not the unstable PPA (with the latest master). Currently the Debian package from the nightly releases doesn't work #2687, the [package_description](https://github.com/xournalpp/xournalpp/blob/master/debian/package_description) (which I think should be put into the root folder, not the debian folder) is slightly outdated and the PPA build derives the wrong version number from the (outdated) changelog. The fix #2701 for the nightly released Debian package is designed to contain some improvements, which also contain changes to the `debian` directory. I think we can't wait with all of that for the inclusion of the package in the official debian repository.

**Comment by apandada1** [comment] 2021-02-24 15:45
@rolandlo There may be a way to still generate packages in Launchpad even when the `debian` directory is deleted in the master branch. One has to create a separate branch in Launchpad which contains the `debian` directory (this branch need not be be updated anymore), and Launchpad would automatically merge the latest changes in master into it, when it clones from GitHub.

See [this](https://askubuntu.com/a/1270912/124466) answer in Ask Ubuntu (this answer is about changing the name of the package during building, but one can similarly merge the whole `debian` directory before building).

However, (in my opinion) it often helps to keep the `debian` directory in upstream (e.g. many of us use the unstable PPA to test the unreleased version, it is much easier than compiling from sources/manually downloading .deb files everyday). The upstream `debian` directory usually does not require much maintenance.
The distribution packagers can maintain their own version of `debian` directory, if they feel necessary.

**Comment by rolandlo** [comment] 2021-02-24 16:41
@luyatshimbalanga What is your take on the question whether we should remove the [xournalpp.spec file](https://github.com/xournalpp/xournalpp/blob/master/rpm/fedora/xournalpp.spec) from the main repository? It would make things easier for us (as we don't need to think any longer about whether we need to update it from our side) and maybe also for you (as you would not be disturbed by us).

**Comment by barak** [comment] 2021-02-24 16:49
@rolandlo @apandada1 Ultimately I'd hope the debian/ directory for an unstable/PPA release will be nearly identical to the one on the debian development branch. In principle, there's no reason for them to differ at all.

I'm happy to try to minimize divergence in the interim as well.

But at the end of the day, it does not really matter.

**Comment by luyatshimbalanga** [comment] 2021-02-25 02:38
> @luyatshimbalanga What is your take on the question whether we should remove the [xournalpp.spec file](https://github.com/xournalpp/xournalpp/blob/master/rpm/fedora/xournalpp.spec) from the main repository? 

I will suggest to keep that spec for daily git snapshot in mind with very little maintenance. The only needed changes are version_string in `%global	version_string 1.1.0` and add `BuildRequires:  pkgconfig(librsvg-2.0)` for the new dependency. The benefit is more testing from Fedora users.

**Comment by barak** [comment] 2021-03-03 15:57
I have my debian branch on github merged with the Xournal++ stable branch, and I've updated the debian/copyright file for the new free icons. I merged common licenses where I could, to reduce clutter. It should all be good to go, once stable is released as 1.1.0. But if someone could check that didn't miss any horrible copyright issues, that would be great.

**Comment by rolandlo** [comment] 2021-03-10 21:50
@barak I am a bit confused about your debian/copyright file. We are working to get  #2886 merged, which replaces all the action icons (those in the folders whose name contains `hicolor`) by those created freshly by @Fatih20 (licensed under GPLv2). Other than that we only have the app icons in the `pixmaps` folder, which were created by @luyatshimbalanga (I have to check if that was also GPLv2).

**Comment by barak** [comment] 2021-03-11 00:26
@rolandlo The info there is from grovelling through commits trying to figure out where various files came from, and also looking at embedded info in the SVG files and copyright comments in source files. I refreshed it after merging the stable branch; not sure how accurate that was. Or how necessary, given #2886 will render much of it obsolete. Anyway, you folks know first-hand where things come from, so I'm very happy to accept corrections to debian/copyright. And if stanzas in there become obsolete and debian/copyright gets really short due to #2886 being merged, fantastic.

**Comment by rolandlo** [comment] 2021-03-14 07:46
@barak The man pages (for both `xournalpp` and `xournalpp-thumbnailer`) are now generated (using help2man) from the `cmake` scripts. There is no need any more for rules in the debian folder to create it. See  #2701 and the fixup #2947. The release builds generated in Azure pipelines (which don't use the debian folder) and the Launchpad PPA builds (that are generated via `dh-buildpackage`) both work and include the man pages.

**Comment by barak** [comment] 2021-03-14 14:39
Great. Just merged with my branch. Nice that cmake does the help2man stuff, my debian/rules file is shrinking properly.

It builds fine in a chroot without a git executable. I didn't check if the compilation is different though, like different version strings or something.

**Comment by rolandlo** [comment] 2021-07-18 23:54
@barak We just released version 1.1.0.

**Comment by barak** [comment] 2021-11-06 15:49
@rolandlo @luyatshimbalanga https://tracker.debian.org/pkg/xournalpp
```sh
$ sudo apt update
$ sudo apt install xournalpp/sid
$ apt policy xournalpp
xournalpp:
  Installed: 1.1.0-2
  Candidate: 1.1.0-2
  Version table:
 *** 1.1.0-2 450
        450 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```
Xournal++ is now in Debian unstable, the mirrors etc will pick it up soon, it should migrate to testing, to Ubuntu, etc,  and this issue can now be closed.

**Comment by rolandlo** [comment] 2021-11-06 16:02
Wonderful news! Thanks @barak! I am closing the issue.

**Closed by rolandlo** 2021-11-06 16:02 UTC
Labels: enhancement, priority::high, packaging

**Comment by rolandlo** [comment] 2022-02-14 07:43
@barak Could you please upgrade the `.deb` package to the newly released version `1.1.1`?

**Comment by barak** [comment] 2022-02-14 18:57
on it

**Comment by barak** [comment] 2022-02-14 19:19
done
