### ISSUE TITLE
If there's an "magnifying glass" it would be better...

### ISSUE THREAD

**Issue by ktrNozomi** [xournalpp/xournalpp#4913] opened 2023-06-06 03:49 UTC
A complete experience can be referred to "Goodnotes" on iPad.

```
+-------------------------+
|                         |
|       +---+             |
|       |   |             |  <- the small area is the one to be magnified
|       +---+             |  <- the outside one is the whole document
|                         |
|                         |
|                         |
+-------------------------+
|  you can write here     |
|  with a magnifying area |
+-------------------------+
```

**Comment by bhennion** [comment] 2023-06-06 13:08
Duplicate of #1638

**Closed** 2023-06-06 13:09 UTC
Labels: enhancement
