### ISSUE TITLE
[Regression] Incorrect scroll origin during pinch-to-zoom on touchscreen

### ISSUE THREAD

**Issue by inducer** [xournalpp/xournalpp#1935] opened 2020-05-04 23:42 UTC
**Affects versions :**
 - OS: Linux/X11
 - Which version of libgtk do you use: Debian 3.24.18-1
 - Version of Xournal++: Good: 46a4dc8292fbca0bce24b8ade6dceee83db16791 Bad: 13f7a5b3
 - Installation method: Source build from git

**Describe the bug**
When I use the touchscreen on my Dell XPS13 2-in-1 7390 to zoom using a pinch-to-zoom gesture, it feels as if the document is being zoomed "about" the document origin (on page 1) rather than the pinch center. This is particularly noticeable on multi-page documents, where this center is very far away.

Note that this is a regression from the "good" git revision to the "bad" git revision. I'm using libinput drivers for the touchscreen.

**To Reproduce**
1. Load a multi-page document
2. Pinch to zoom
3. Watch the spot you were meaning to zoom into zip far away.

**Comment by inducer** [comment] 2020-05-05 00:10
Git bisect yields fea36863a9fc44bdb4cab67a7d65e65635696c7e as the culprit, which seems Zoom-related. This is further corroborated by the fact that reverting that commit on top of master fixes the behavior.

cc @jvwowd as the  commit author

Git bisect log for completeness:
```
git bisect start
# good: [46a4dc8292fbca0bce24b8ade6dceee83db16791] Merge pull request #1749 from Guldoman/master
git bisect good 46a4dc8292fbca0bce24b8ade6dceee83db16791
# bad: [13f7a5b3230c25ab7f59e9fdab246ffc5e69e65f] Fix issue #1931
git bisect bad 13f7a5b3230c25ab7f59e9fdab246ffc5e69e65f
# skip: [5a90a804ae71916357993bf5346f2ed14097d8cf] replaced mem::make_unique with std::make_unique.
git bisect skip 5a90a804ae71916357993bf5346f2ed14097d8cf
# bad: [269c1acdcb864e6ca073e1047a1c48f01cf91ffb] Set application name in binary to desktop id
git bisect bad 269c1acdcb864e6ca073e1047a1c48f01cf91ffb
# good: [dbdc02997e589e1ab2671094a3a8eab756ba4d6a] Merge pull request #1819 from rolandlo/fix-eraser-bug
git bisect good dbdc02997e589e1ab2671094a3a8eab756ba4d6a
# skip: [99766c1a037a5060e498c8ff8808c52a4a916b7a] Fix Latex not working on Windows
git bisect skip 99766c1a037a5060e498c8ff8808c52a4a916b7a
# bad: [3acdd07259eb89b35634ac6ccd5829b5175633d2] Merge pull request #1898 from Technius/cursor-highlight
git bisect bad 3acdd07259eb89b35634ac6ccd5829b5175633d2
# bad: [7e7cf8b786fc826069be5aaa4418115ba83915f1] [skip ci] Update installation instructions in README
git bisect bad 7e7cf8b786fc826069be5aaa4418115ba83915f1
# bad: [4c4cf510fb1b637a2896714241ddabfd928f94b6] Fixed possible self assigning bug. Replaced custom ref count by a std::shared_ptr
git bisect bad 4c4cf510fb1b637a2896714241ddabfd928f94b6
# bad: [e16faa7bcdbceb49d8a4d15e07df3fd963552c85] Update .gitignore
git bisect bad e16faa7bcdbceb49d8a4d15e07df3fd963552c85
# bad: [6790c9737494d209b41f266217085372e77eae05] Merge pull request #1830 from jvwowd/fix-ctrl-scroll-zoom
git bisect bad 6790c9737494d209b41f266217085372e77eae05
# good: [e4fdfeffd8e787e78cd7c734843751c95ae93d75] Refactored Rectangle.h so that template code is only in the header file. Also replaced some bad code
git bisect good e4fdfeffd8e787e78cd7c734843751c95ae93d75
# bad: [fea36863a9fc44bdb4cab67a7d65e65635696c7e] Minimal fix of ctrl+scroll zoom bug
git bisect bad fea36863a9fc44bdb4cab67a7d65e65635696c7e
# first bad commit: [fea36863a9fc44bdb4cab67a7d65e65635696c7e] Minimal fix of ctrl+scroll zoom bug
```

**Comment by LittleHuba** [comment] 2020-05-05 12:51
Do you have the new input system activated?

**Comment by inducer** [comment] 2020-05-05 14:55
Yes.

**Comment by Febbe** [comment] 2020-05-05 16:41
Yes unfortunately I had objections against that commit and no time. It was merged faster than I could interfere and since it seemed everything worked I didn't said anything. The original committee changed the desired behaviour of the functions above, but the behaviour was the right and it should've been changed in the callee.

**Comment by Febbe** [comment] 2020-05-05 16:42
If you have time to make a commit to fix both, that would be great. Otherwise me or another dev will look into it as soon we have time.

**Comment by Technius** [comment] 2020-05-05 20:22
Duplicate of #1843.

**Comment by inducer** [comment] 2020-05-05 20:23
Thanks for the response! Since I've got a workaround and many other commitments, I'm happy to wait until one of you gets around to it. Thank you very much for the work you put into Xournal++! I use it for teaching and research basically every day.

**Closed by Technius** 2020-05-05 20:22 UTC
Labels: bug
