### ISSUE TITLE
parts of LaTeX equations not resizing

### ISSUE THREAD

**Issue by SaVoAMP** [xournalpp/xournalpp#4555] opened 2023-01-02 18:23 UTC
**Affects versions :**
 - OS: Linux Mint 20.3 x86_64
 - Version of Xournal++: 1.1.3

**Describe the bug**
Equations containing square roots, fractions or boxes don't resize correctly

**To Reproduce**
1. Open the LaTeX tool
2. Type an equation containing square roots, fractions or boxes, e. g. `$\boxed{\sqrt{\frac{x^2}{4}}}$`
3. Press ok
4. Resize the equation to ~0.5 or less of its original size
5. Deselect the equation

**Expected behavior**
The equation should not change in appearance after deselecting

**Video of Problem**
[![image](https://user-images.githubusercontent.com/95933072/210267245-8172be4c-f054-40e1-951c-0607166f16ad.png)](https://user-images.githubusercontent.com/95933072/210266869-59ba42c3-96bd-4228-8cb4-64d7fa8f5651.mp4)

**Additional context**
After exporting to .pdf resized equations look ugly.

**Comment by tattsan** [comment] 2023-01-02 19:58
It seems to be related with #3692, but I've met that bug only on exported PDF.
For the exported PDF, I use 10x-method explained in #3692 for a workaround.
You can also try #3773, but I don't think that PR is an appropriate solution.

**Comment by RichardScharf** [comment] 2023-01-02 20:48
I just checked, on Windows 10 and Windows 11 it appears only on exported .pdf files!

On Linux Mint 21.04 (and 20.3) it renders thick lines after deselecting the equation!

**Comment by VirtualNonsense** [comment] 2023-01-02 21:07
Same thing on Manjaro

**Comment by tattsan** [comment] 2023-01-03 17:50
I've also confirmed the bug on the sceen on recent build. I'll start bisection.

**Comment by tattsan** [comment] 2023-01-03 18:51
The bug was introduced by fc17f8555790689dc2e4d2f8ea5bd5a2c2216ca0 . @bhennion so you have any concerns?

**Comment by tattsan** [comment] 2023-01-03 19:41
This bug can be avoided with #3773, but there should be no need to use `poppler_page_render_for_printing`  for screen display.

**Comment by RichardScharf** [comment] 2023-01-03 20:49
> This bug can be avoided with #3773, but there should be no need to use `poppler_page_render_for_printing` for screen display.

Just compiled your draft and tested it on Ubuntu 22.04 LTS.

This seems to fix the problem, why is it not merged into the nightly build yet?

Is there any way to approve your draft or vote?

**Comment by bhennion** [comment] 2023-01-04 16:50
It looks like a poppler bug to me. I'll try to make a MWE and report upstream.
In the meantime, we need a workaround as this cripples the Text tool.

**Comment by Technius** [comment] 2023-01-06 06:26
Has anyone reproduced this 1.1.3? This appears to be a nightly bug.

**Comment by bhennion** [comment] 2023-01-06 08:44
Yes, it's only on master. I think I know where it comes from. I'll try to write a fix.

**Closed** 2023-02-16 17:38 UTC
Labels: bug, rendering, regression, LaTeX
