### ISSUE TITLE
Crash of Unknown Cause

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#3935] opened 2022-03-29 22:01 UTC
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: Gnome 41, Wayland
 - Which version of libgtk do you use: 3.24.33
 - Version of Xournal++: 1.1.1
 - Installation method: Flatpak

**Describe the bug**
Hard crash of unknown cause. Perhaps the same as #3755?

**To Reproduce**
Unknown. I was simply writing. It may have been linked to an autosave, but I cannot confirm that.

**Additional context**

Error Logs:
```
Date: Tue Mar 29 14:55:30 2022
Error: signal 11
[bt]: (0) xournalpp(+0x206c99) [0x55744ac3bc99]
[bt]: (1) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x39530) [0x7f1ae77b5530]
[bt]: (2) xournalpp(_ZNK7Element7getTypeEv+0x4) [0x55744ac0d5e4]
[bt]: (3) xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x23) [0x55744ac32b23]
[bt]: (4) xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x9b) [0x55744ac32cfb]
[bt]: (5) xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xe6) [0x55744ac33576]
[bt]: (6) xournalpp(_ZN10PreviewJob8drawPageEv+0x3c3) [0x55744ab2ae83]
[bt]: (7) xournalpp(_ZN10PreviewJob3runEv+0x35) [0x55744ab2b165]
[bt]: (8) xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x11c) [0x55744ab2df7c]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x862c9) [0x7f1ae8df22c9]
[bt]: (10) /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x83ba) [0x7f1ae7de13ba]
[bt]: (11) /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f1ae787db03]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0x2071ab) [0x55744ac3c1ab]
[bt] #2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x39530) [0x7f1ae77b5530]
[bt] #3 xournalpp(_ZNK7Element7getTypeEv+0x4) [0x55744ac0d5e4]
[bt] #4 xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x23) [0x55744ac32b23]
[bt] #5 xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x9b) [0x55744ac32cfb]
[bt] #6 xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xe6) [0x55744ac33576]
[bt] #7 xournalpp(_ZN10PreviewJob8drawPageEv+0x3c3) [0x55744ab2ae83]
[bt] #8 xournalpp(_ZN10PreviewJob3runEv+0x35) [0x55744ab2b165]
[bt] #9 xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0x11c) [0x55744ab2df7c]
[bt] #10 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x862c9) [0x7f1ae8df22c9]
[bt] #11 /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x83ba) [0x7f1ae7de13ba]
[bt] #12 /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f1ae787db03]
```

**Comment by K4LCIFER** [comment] 2022-03-29 22:03
Perhaps the same as #3755?

**Comment by bhennion** [comment] 2022-07-21 18:08
Closing as duplicate of #3755

**Closed by bhennion** 2022-07-21 18:08 UTC
Labels: bug
