### ISSUE TITLE
Zooming in on large PDFs makes them vanish

### ISSUE THREAD

**Issue by itsCryne** [xournalpp/xournalpp#5420] opened 2023-12-21 22:29 UTC
### Operating System

Linux

### (Linux only) Distribution

Manjaro

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Arch repo / AUR

### Xournal++ Version

1.2.2 & 1.2.2+dev (7fa4c174)

### libgtk Version

3.24.38

### Bug Description

When zooming in past a certain level on a large PDF, it vanishes

### Expected Behaviour

Zooming should not make the PDF vanish

### Steps to Reproduce

1. Open a large PDF, e.g. `convert xc:none -page 50x10000 bigpage.pdf && xournalpp bigpage.pdf`
2. Zoom in
3. Past a certain zoom level, the PDF vanishes and only the background is visible

**Comment by rolandlo** [comment] 2023-12-21 22:52
This looks like a duplicate of #5333.

**Closed by rolandlo** 2023-12-21 22:52 UTC
Labels: bug
