### ISSUE TITLE
Stamp Button

### ISSUE THREAD

**Issue by mptrv** [xournalpp/xournalpp#3543] opened 2021-11-05 14:41 UTC
Hi!

A useful resource is a **"stamp button"**, like the one in Moodle (see image below).

![image](https://user-images.githubusercontent.com/11620491/140526413-8076cf4e-75db-4926-9c3a-46e1970b40f2.png)

The images of the stamp could be fixed or customizable.

Some applications should be: in correcting tests, adding signatures, quickly point text or graphic material.

Best regards!

**Comment by rolandlo** [comment] 2021-11-05 18:13
That would sound like a useful addition to me.

**Comment by bhennion** [comment] 2021-12-16 08:45
This looks like a duplicate of #1652. Closing this in favor of #1652, as a (temporary) workaround is proposed therein.

**Closed by bhennion** 2021-12-16 08:45 UTC
Labels: enhancement, priority::medium

**Comment by mptrv** [comment] 2021-12-23 15:33
Ok.
