### ISSUE TITLE
Feature to edit keyboard shortcuts

### ISSUE THREAD

**Issue by idea-log** [xournalpp/xournalpp#3805] opened 2022-02-12 19:04 UTC
Hello there,
There are pre-defined shortcuts but I'd like to be able to change the keyboard shortcuts myself to suit my needs. I am sure that many users would appreciate such a feature. Thank you for your consideration and time. Great App!

**Comment by rolandlo** [comment] 2022-02-12 21:12
Duplicate of #919. Please find some solutions (via plugins) there.

**Closed by rolandlo** 2022-02-12 21:12 UTC
