### ISSUE TITLE
I come back to the top of the document when I add a new page at the end of a document

### ISSUE THREAD

**Issue by MichelReims** [xournalpp/xournalpp#2289] opened 2020-09-29 11:27 UTC
I work under windows 10 with the nightly-automated release of the 28 september.
Sometimes, when I add a new page at the end of a document, I come back to the top of the document.

**Comment by rolandlo** [comment] 2020-09-29 11:36
Thanks for the bug report. Please provide an update if you can clearly see the pattern of when the bug appears. If it is reproducible it can get fixed easier. I think it is very important to fix it, since it is connected with other problems like bug #2211.

**Comment by Rmano** [comment] 2020-09-29 13:05
It happens all the time to me too. In the following video:

1. open `xournalpp`
2. write something, add a new page
3. scroll to the new page, write something.
4. new page, repeat
5. after (in this case 3) pages `xournapp` jumps back to the first page when adding a new one


![test](https://user-images.githubusercontent.com/6414907/94561993-0c861b80-0265-11eb-81b3-44c4f1e51674.gif)


I think it had something to do with the fit-to-page (which works strangely, as well as presentation mode --- shouldn't just show one page at a time in presentation mode?

**Comment by Rmano** [comment] 2020-09-29 13:09
This seems the same: https://github.com/xournalpp/xournalpp/issues/1926

**Comment by rolandlo** [comment] 2020-10-11 19:06
@Rmano Could you please test PR  #2312. It seems to almost solve the problem.

**Comment by Rmano** [comment] 2020-10-12 10:36
Even if not perfect, the current state of PR #2312 solves this issue. I commented in the PR with more details.

**Comment by rolandlo** [comment] 2020-10-28 18:15
Now PR #2346 should do it perfectly. PR #2312 was closed in favor of PR #2346

**Closed** 2020-10-30 15:53 UTC
Labels: Zoom, bug, papercut
