### ISSUE TITLE
Copy paste screenshots of pdf

### ISSUE THREAD

**Issue by tobiasBora** [xournalpp/xournalpp#4047] opened 2022-05-23 20:19 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes I like to copy/paste a part of a theorem somewhere else in the document, for instance to copy a theorem close to the proof etc...

**Describe the solution you'd like**

I'd love to have a tool to select a part of the pdf (either lasso or rectangle) and copy/paste it as a new image in the pdf. It would be even better if it could also copy the annotations at the same time, but I guess it's not really important as annotations can also be copied separately.

**Describe alternatives you've considered**

For now I use an external app to take screenshots and copy/paste the image.

**Comment by bhennion** [comment] 2022-05-24 06:55
Duplicate of #1040. See also #3953.

**Closed by bhennion** 2022-05-24 06:55 UTC
Labels: enhancement
