### ISSUE TITLE
Crash on inserting new Tex object

### ISSUE THREAD

**Issue by garrinoa** [xournalpp/xournalpp#4370] opened 2022-10-29 19:07 UTC
Hello,
I just discovered a bug causing a crash when clicking the 'Add/Edit Tex' button, both on the toolbar and using the menu option under Tools > Add/Edit Tex. The keyboard shortcut (unsurprisingly) also causes the program to crash. When clicking the button, the program freezes for several seconds, and exits without an error dialogue or any other visible symptoms. There does not seem to be a noticeable spike in CPU or memory use. 

Windows 11 Home Version 10.0.22621 (x64, w/ 12 GB RAM, Intel i7 10th gen)
Xournal Version 1.1.2 (commit 3fe37c1d-dirty)
libgtk Version 3.24.34

**Comment by rolandlo** [comment] 2022-10-29 19:18
Probably you don't have a LaTeX installation or the TeX generator (`pdflatex`) cannot be found in path. This was already reported in #4334 and fixed in #4345.
So unless you are reporting another issue, I will close this one as a duplicate of #4334.

**Closed** 2023-02-17 08:44 UTC
Labels: Crash, orphaned
