### ISSUE TITLE
Autoload .xopp files

### ISSUE THREAD

**Issue by janpath** [xournalpp/xournalpp#1147] opened 2019-05-13 23:28 UTC
**Affects versions :**
 - Xournal++ 1.0.10

**Describe the bug**
When the “Autoload .pdf.xoj” option is enabled (which should probably be renamed) I would also expect Xournal++ to autoload .xopp files.

**Comment by veecue** [comment] 2019-05-14 09:00
Will be fixed by #1117
.xopp will not be autoloaded, but .pdf.xopp will and the default file extension for saving a file opened from a PDF will be .pdf.xopp

**Comment by SenaidaHdez** [comment] 2019-05-30 00:21
Also happens here! It doesn't autoload neither pdf.xoj nor .xopp

**Comment by jonasBoss** [comment] 2019-06-29 17:50
As #1117 got merged, it is now possible to save *.pdf.xopp files, which will get automatically loaded. Existing files can be renamed "*.pdf.xopp" to enable autoloading for them. 
If the intent is to automatically load *.xopp files as well, this should be a Feature request.

**Comment by Febbe** [comment] 2019-07-23 18:14
I will close this now, since #1117 fixed the bug and the issue is very old. Please open a new feature request issue.

**Closed by Febbe** 2019-07-23 18:14 UTC
Labels: bug
