### ISSUE TITLE
Use Second Screen for Presentation of Document Without Toolbars, Menus, etc. as You Annotate It

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#4239] opened 2022-09-18 05:00 UTC
As a professor I use xournalpp a lot for presenting in class and for making videos for my students.  I recently saw [a feature of OpenBoard](https://condor.depaul.edu/~jmoore/tech/openboard/#:~:text=Annotate%20Document%3A%20This%2C%20as%20the,from%20three%20thicknesses%20of%20eraser.) I wish xournalpp had.  See the screenshot below showing what I mean.  Presently I mirror my screen using full screen, but this is even better.  The students don't see your toolbars, etc. and so it is less disctacting for them, and looks cleaner.  It also allows me to have access to the menus while I present, but the students don't see them.  
![Screenshot from 2022-09-17 21-53-33](https://user-images.githubusercontent.com/994565/190886452-1f6ac0ae-6d01-46e4-8bab-02a19c7bd481.png)

**Comment by rolandlo** [comment] 2022-09-18 05:20
That's a feature, that we aim to implement. There is some big refactoring going on right now that will eventually lead to the option to have multiple views. See #4137 for details.

**Comment by bhennion** [comment] 2022-10-06 11:14
Duplicate of #2020

**Closed by bhennion** 2022-10-06 11:14 UTC
Labels: enhancement
