### ISSUE TITLE
The clang-format CI check is not functioning anymore

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#4699] opened 2023-03-07 08:48 UTC
The CI check succeeds without actually checking anything (kinda the worst thing it can do...).

Here is a typical CI output:

```
Starting: Run clang-format on modified files
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.214.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash /home/vsts/work/_temp/c73957b5-bebd-487a-9db8-221be0203599.sh
Previous HEAD position was 23fc626e Merge 03de6aa5e6fc32328231b8e923260d70004e08b3 into 0859a5ba252a9a94efc33c3770e6145f4f722d75
Switched to a new branch 'master'
branch 'master' set up to track 'origin/master'.
fatal: invalid reference: scale-arrow-head
fatal: Not a valid object name scale-arrow-head
Computing diff to commit hash
no modified files to format
Finishing: Run clang-format on modified files
```

**Comment by bhennion** [comment] 2023-03-07 10:22
This happens on all PRs. For some reason, the git repository available in the check does not see the PR's branch. You can look at some debugging output I made in #4700:
```
Switched to a new branch 'master'
branch 'master' set up to track 'origin/master'.
git remote --verbose
origin	*** (fetch)
origin	*** (push)
git branch
* master
git remote show origin
* remote origin
  Fetch URL: ***
  Push  URL: ***
  HEAD branch: master
  Remote branches:
    1.0.x                        tracked
    Febbe-patch-enum-cmp         tracked
    feature-pr-comment-releases  tracked
    gtk4                         tracked
    gtk4test                     tracked
    l10n_master                  tracked
    master                       tracked
    refactoring_ElementContainer tracked
    release-1.1                  tracked
    releases                     tracked
    rewrite                      tracked
    stable                       tracked
    view-rewrite                 tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
System.PullRequest.SourceRepositoryURI = ***
git switch origin/pr/fixCI
fatal: invalid reference: pr/fixCI
Calling git merge-base
fatal: Not a valid object name pr/fixCI
Computing diff to commit hash
no modified files to format
Finishing: Run clang-format on modified files
```

There is basically no trace of the PR's branch in there... I don't know where to go from there.
@Febbe would you have time to give this a look? (you were the last one to look at this check)

**Comment by bhennion** [comment] 2023-03-07 10:23
I also do not understand why the CI check is not failing while `git switch your_pr_branch_name` returns an error code (128).

**Comment by Febbe** [comment] 2023-03-07 11:11
I can take a look, but for reference: We could remove our script. Llvm now delivers a "run-clang-format.py" script, which does everything and also returns exitcode 1, when it actually has files to format.

**Comment by bhennion** [comment] 2023-03-07 12:12
> I can take a look, but for reference: We could remove our script. Llvm now delivers a "run-clang-format.py" script, which does everything and also returns exitcode 1, when it actually has files to format.

Using Llvm's would be best then, I think.

**Comment by Technius** [comment] 2023-03-12 09:09
> For some reason, the git repository available in the check does not see the PR's branch.

Based on the recent logs, it seems like Azure Pipelines is now performing a sparse checkout by default, so the branch list is not fetched.

> Llvm now delivers a "run-clang-format.py" script, which does everything and also returns exitcode 1, when it actually has files to format.

I can't find this script in the official LLVM project. But there is an official `git-clang-format` script (which I believe we're currently using) that should do what we want:
```
git-clang-format --diff $target_branch $current_branch
```
The problem is that we'll need to make sure configure the CI check to checkout the history correctly.

**Comment by Febbe** [comment] 2023-03-13 22:19
> I can't find this script in the official LLVM project. But there is an official git-clang-format script (which I believe we're currently using) that should do what we want:

Sorry, I meant `git-clang-format`. And since (I think) LLVM 15 this script now returns an error code.

>The problem is that we'll need to make sure configure the CI check to checkout the history correctly.

We want the common ancestor commit of both source and target as base:
`git merge-base branch2 branch3`
`git clang-format --diff $(git merge-base current target)` or `git clang-format --diff $(git merge-base current target) current`
could do the trick.

**Comment by bhennion** [comment] 2023-03-13 22:51
This is already what we did (actually what you @Febbe implemented in #4144). The issue is the Azure pipeline does not fetch the forked remote hosting the PR branch (or at least I could not find it while debugging. See the log I put in [this post](https://github.com/xournalpp/xournalpp/issues/4699#issuecomment-1457916876)).

> @Technius why do we still use azure pipelines, instead of GitHub Actions?

That's a fairly good question.

**Comment by Febbe** [comment] 2023-03-14 01:31
I think the reason is a bug: https://developercommunity.visualstudio.com/t/buildsourcebranch-no-longer-contains-git-reference/1192275 and 
https://github.com/microsoft/azure-pipelines-tasks/issues/13589 mentioned the same problem for `Build.SourceBranch` seems like they did not fix it for `System.PullRequest.SourceBranch`

**Comment by Febbe** [comment] 2023-03-14 12:02
Should be fixed now.

**Closed by Febbe** 2023-03-14 12:02 UTC
Labels: bug, priority::high, Scripting

**Comment by bhennion** [comment] 2023-03-15 20:43
Thanks for taking care of that @Febbe!
