### ISSUE TITLE
Ctrl+z and Ctrl+y stop working with hidden Menu-Bar

### ISSUE THREAD

**Issue by ThomasSeeker** [xournalpp/xournalpp#2314] opened 2020-10-12 14:28 UTC
Hey there,

Ctrl+z and Ctrl+y stop working when the Menu-Bar is hidden. Is this by purpose?
I'd like to have it working in both cases. Is this possible?

Thanks for your wonderful work!
;-)

**Comment by rolandlo** [comment] 2020-10-12 17:30
That will be fixed in future. @duncanawoods already seems to have a concrete idea how to fix it, although it is not yet implemented. See #2082. I will close this, since it is a duplicate of #2082.

**Closed by rolandlo** 2020-10-12 17:30 UTC
