### ISSUE TITLE
Export to svg creates broken svg files

### ISSUE THREAD

**Issue by ianbrody** [xournalpp/xournalpp#4653] opened 2023-02-15 09:14 UTC
**Affects versions :**
 - OS: Arch linux
 - (Linux only) Desktop environment: awesome wm (X11)
 - Which version of libgtk do you use: 3.24.36
 - Version of Xournal++: 1.1.3
 - Installation method: arch linux repo package

**Describe the bug**
For documents involving at least a few moderately complicated pen strokes, exporting to svg results in a file that cannot be opened by the svg (pre)viewers that I have-- inkscape, firefox, viewnior. Instead, these programs crash or fail to start.

**To Reproduce**
1. Draw a few moderately complicated strokes on a new document using a stylus
2. Save
3. Export to svg
4. Open the svg in inkscape

**Expected behavior**
Inkscape opens the svg file  

**Additional context**
example .xopp file and associated .svg file attached in the zip (warning-- my first attempt to attach these unzipped made my browser crash; there's clearly something wrong with them)
[test2.zip](https://github.com/xournalpp/xournalpp/files/10741262/test2.zip)

**Comment by bhennion** [comment] 2023-02-15 09:31
Thanks for reporting. This is a duplicate of #4112

**Closed by bhennion** 2023-02-15 09:31 UTC
Labels: bug
