### ISSUE TITLE
a shortcut described by the program doesn't work.

### ISSUE THREAD

**Issue by yodavid1984** [xournalpp/xournalpp#4141] opened 2022-07-08 17:01 UTC
EDIT: never mind. the source of the problem was something else. 

**Affects versions :**
 - OS: Linux Mint 20.3 Cinnamon, Cinnamon Version 5.2.7, Linux Kernel 5.4.0-91-generic
 - Version of Xournal++: 1.1.1
 - Installation method: software manager

**Describe the bug**
the commands Previous Layer and Next layer do work when i go Navigation > Previous Layer or Navitation > Next Layer, but not when i use what the program says are the shortcuts to these functions, shift+pagedown or shift+pageup 

**To Reproduce**
1. create a document with more than one layer. scribble something in each of them so you can visualize them at all times
2. press shift+pagedown and see if what you scribbled on the top one disappears

**Expected behavior**
whenever i press shift+pagedown, the toplayer is deactivated, then when pressed again, the new top layer is deactivated and so on. the opposite with shift+pageup

Add any other information or context about the problem here.

**Comment by rolandlo** [comment] 2022-07-10 18:13
Closing the issue, since the problem is not related to the Xournal++ code.

**Closed by rolandlo** 2022-07-10 18:13 UTC
Labels: bug
