### ISSUE TITLE
AppImage segfaults on Ubuntu focal

### ISSUE THREAD

**Issue by TheAssassin** [xournalpp/xournalpp#3080] opened 2021-04-28 00:36 UTC
Observed with Xournal++ 1.0.20.

I've just upgraded one of my computers to focal, and suddenly Xournal++ started to segfault. The reason seems to be a missing dependency, `libgdk_pixbuf`, which is on the AppImage excludelist for libraries.

linuxdeploy-plugin-gtk (which you also use) now force-deploys the library to fix the issue. I also started a discussion about removing the library from the excludelist, given that the entry is at least 5 years old (https://github.com/AppImage/pkg2appimage/issues/475).

In the meantime, just rebuilding and uploading a new AppImage should fix the bug. I've checked that adding the bionic library to the AppDir fixes the issue.

I am yet to try this in a fresh Xubuntu focal VM. But, as said, the plugin also deploys the library, and I'm not aware of issues like the one described for inkscape in the excludelist. Probably, the issue went away somewhere in between the versions on bionic and xenial.

**Comment by rolandlo** [comment] 2021-04-28 00:46
We know of that. That's why we reworked the AppImage for [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly). Since version 1.1.0 will soon become the new stable release and there won't be any more releases in the 1.0.x series, you really don't need to worry much about the 1.0.20 AppImage.

**Comment by rolandlo** [comment] 2021-04-28 08:12
Closing this issue as duplicate of  #2567

**Closed by rolandlo** 2021-04-28 08:12 UTC
Labels: bug

**Comment by TheAssassin** [comment] 2021-04-28 11:58
Well, it's not working at all, so I thought you'd just quickly rebuild it and ship a working one... Welp, I'll try the nightly then. Perhaps you can move it up a bit on https://github.com/xournalpp/xournalpp/releases, it's quite hard to find.
