### ISSUE TITLE
Exported PDF cannot be read by Adobe Reader

### ISSUE THREAD

**Issue by DhruvaSambrani** [xournalpp/xournalpp#2648] opened 2021-01-11 14:10 UTC
**Affects versions :**
 - Windows
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use: 3.24.23
 - Version of Xournal++: 1.0.20
 - Installation method: Chocolatey

**Describe the bug**
A background pdf was annotated and images added. The exported PDF can be read by Sumatra PDF reader, EDGE and Chrome.
It cannot however be read by Adobe Acrobat Reader. 

On windows, it says- `There was an error processing a page. There was a problem reading this document (135)`

**To Reproduce**
1. Make a pdf file
2. Open the pdf file as background
3. Annotate
4. Export as PDF

**Expected behavior**
Exported PDF can be read by Adobe reader

**Comment by rolandlo** [comment] 2021-01-11 14:13
Duplicate of #2601. This is a bug in Cairo. Version 1.0.19 works for pdf export.

**Closed by rolandlo** 2021-01-11 14:13 UTC
Labels: bug
