### ISSUE TITLE
Xjournal crashed

### ISSUE THREAD

**Issue by rs0404** [xournalpp/xournalpp#4968] opened 2023-07-27 01:37 UTC
Date: Thu Jul 27 07:19:31 2023
Error: signal 11
[bt]: (0) xournalpp(+0xd56d1) [0x560539b706d1]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f40fb042520]
[bt]: (2) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18f1a7) [0x7f40fc18f1a7]
[bt]: (3) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_hash_table_insert+0x2e) [0x7f40fb93fd0e]
[bt]: (4) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x197620) [0x7f40fc197620]
[bt]: (5) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1923e7) [0x7f40fc1923e7]
[bt]: (6) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x192687) [0x7f40fc192687]
[bt]: (7) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
[bt]: (8) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
[bt]: (9) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
[bt]: (10) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
[bt]: (11) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
[bt]: (12) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
[bt]: (13) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
[bt]: (14) /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17575b) [0x7f40fc17575b]
[bt]: (15) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x1290) [0x7f40fba68700]
[bt]: (16) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f40fba68863]
[bt]: (17) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x46be6) [0x7f40fc8cebe6]
[bt]: (18) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x332ad) [0x7f40fc8bb2ad]
[bt]: (19) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x562c8) [0x7f40fb9522c8]
[bt]: (20) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x174) [0x7f40fb951c44]
[bt]: (21) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f40fb9a7258]
[bt]: (22) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f40fb94f3e3]
[bt]: (23) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7f40fbba6fb5]
[bt]: (24) xournalpp(_ZN11XournalMain3runEiPPc+0x4ee) [0x560539b7381e]
[bt]: (25) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f40fb029d90]
[bt]: (26) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f40fb029e40]
[bt]: (27) xournalpp(_start+0x2a) [0x560539b6fc8a]

Try to get a better stracktrace...
[bt] #1 xournalpp(+0xd5c4d) [0x560539b70c4d]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f40fb042520]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18f1a7) [0x7f40fc18f1a7]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_hash_table_insert+0x2e) [0x7f40fb93fd0e]
??:0
[bt] #5 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x197620) [0x7f40fc197620]
??:0
[bt] #6 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1923e7) [0x7f40fc1923e7]
??:0
[bt] #7 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x192687) [0x7f40fc192687]
??:0
[bt] #8 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
??:0
[bt] #9 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1926e3) [0x7f40fc1926e3]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgtk-3.so.0(+0x17575b) [0x7f40fc17575b]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x1290) [0x7f40fba68700]
??:0
[bt] #17 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f40fba68863]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x46be6) [0x7f40fc8cebe6]
??:0
[bt] #19 /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x332ad) [0x7f40fc8bb2ad]
??:0
[bt] #20 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x562c8) [0x7f40fb9522c8]
??:0
[bt] #21 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x174) [0x7f40fb951c44]
??:0
[bt] #22 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab258) [0x7f40fb9a7258]
??:0
[bt] #23 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f40fb94f3e3]
??:0
[bt] #24 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1a5) [0x7f40fbba6fb5]
??:0
[bt] #25 xournalpp(_ZN11XournalMain3runEiPPc+0x4ee) [0x560539b7381e]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f40fb029d90]
??:0
[bt] #27 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f40fb029e40]
??:0
[bt] #28 xournalpp(_start+0x2a) [0x560539b6fc8a]
??:0

**Comment by bhennion** [comment] 2023-08-08 10:29
Thanks for reporting. The crash log was create by a previous version. The cause of thoses crashes have possibly been fixed in 1.2.
Please update to Xournal++ 1.2, and open a new issue if a new crash occurs and you have a more recent crashlog.

**Closed by bhennion** 2023-08-08 10:29 UTC
