### ISSUE TITLE
(New input system) Sometimes a stroke is drawn when it shouldn't.

### ISSUE THREAD

**Issue by derchr** [xournalpp/xournalpp#2053] opened 2020-06-09 16:36 UTC
**Affects versions :**
 - OS: Manjaro Linux
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: 3.24.20 
 - Version of Xournal++:  1.1.0+dev (current master branch)
 - Installation method: AUR (git)

I use a wacom tablet (xsetwacom get 19 TabletPCButton returns on, so I ticked the check box under Settings->Input System) to write in Xournalpp.
Sometimes (I've only noticed this issue when the new input system was on) a stroke is drawn when I'm not pressing any buttons or drawing with the stylus on the tablet. This happens after closing a window or after switching from another window to Xournalpp.
Here is a short video for demonstration:
https://imgur.com/8VAUYbI

1. Use the new input system.
2. Use a drawing tablet.
3. Open a menu and close it.

**Expected behavior**
No strokes should be drawn.

**Comment by LittleHuba** [comment] 2020-06-09 16:38
Could you provide input logs please? https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs

**Comment by 4VRDriver** [comment] 2020-06-09 19:04
Thank you for your quick response. I had a hard time trying to reproduce the bug but eventually it happed again:

[debug_input.log](https://github.com/xournalpp/xournalpp/files/4754273/debug_input.log)

[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/4754274/debug_gdk_input.log)

**Comment by 4VRDriver** [comment] 2020-06-21 11:17
I noticed a bug, that could be related to this issue (it also only happens when the new input system is enabled).

I have two buttons on my pen. Button 1 is for erasing stuff and Button 2 is the hand tool:

1. Set up two pages and scroll to the end of page 1 so that both pages are visible.
2. Start hovering over page 1, then switch page 2 and hover over that.
3. Now press any button (erasing or hand tool) and set down the pen on the graphic tablet.

A stroke will be drawn although I am pressing the erase button.
This is very easy to reproduce and happens (to my knowledge) every time.

**Comment by tattsan** [comment] 2020-08-10 06:31
I've been also annoyed by this phenomenon on my wacom tablet (Linux).
This happens under the following conditions.
(1) xsetwacom set "Wacom's some device" "TabletPCButton" "on"
(2) In xournalpp's preferences setting, 'Merge button events with stylus tip events' is checked.

Today I disabled both settings, and the annoying strokes disappeared.

**Comment by bhennion** [comment] 2022-07-12 20:33
Duplicate of #3274, fixed by #3701

**Closed by bhennion** 2022-07-12 20:33 UTC
Labels: bug, Input
