### ISSUE TITLE
Freeze when using the touchpen (Ubuntu 23.10)

### ISSUE THREAD

**Issue by LucaSchueller** [xournalpp/xournalpp#5355] opened 2023-11-21 19:20 UTC
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 23.10

### (Linux only) Desktop Environment

GNOME 45.0

### (Linux Only) Display Server

Wayland

### Installation Method

PPA

### Xournal++ Version

1.2.2

### libgtk Version

3.24.38

### Bug Description

The application freezes after using the touchpen. After pressing the start button and reopening Xournal++, the application behaves like usuaal until i use the pen again.

Using the mouse or finger to draw does work. I only crashes when using the pen.

### Expected Behaviour

Not freezing when using the touchpen.

### Steps to Reproduce

Using the touchpen 

### Additional Context
Problem occured after updating from Ubuntu 22.10 with GNOME 43 to 23.10 with GNOME 45

Used Hardware:
Lenovo Thinkpad X1 Yoga Gen 2 with Wacom ISDv4 50b4

**Comment by rolandlo** [comment] 2023-11-21 19:37
This looks like #5249, except that you use Wayland. Are you sure of that?

**Comment by LucaSchueller** [comment] 2023-11-21 19:44
Oops, yeah, I'm using X11 and didn't saw the other open issue. Thanks!

**Comment by rolandlo** [comment] 2023-11-21 19:46
Closing as a duplicate of #5249 then.

**Closed by rolandlo** 2023-11-21 19:46 UTC
Labels: bug
