### ISSUE TITLE
Rubber resets drawing color

### ISSUE THREAD

**Issue by Krzmbrzl** [xournalpp/xournalpp#1940] opened 2020-05-05 18:31 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Linux (KDE Neon)
 - X11
 - Which version of libgtk do you use No idea
 - Version of Xournal++: Xournal++ 1.1.0+dev 
 - Installation method: PPA

**Describe the bug**
When having the briwse-tool selected (the one with which I can move the screen) if I activate the rubber (via button on my stylus) the drawing color gets reset to black.

**To Reproduce**
See description

**Expected behavior**
The color selected drawing color should not be affected

**Comment by rolandlo** [comment] 2020-05-05 20:50
I can confirm the bug and add the following info:

To reproduce the bug:
1. map the first stylus button to the eraser
2. select a color different from black in the toolbar
3. select the hand tool
4. press and release the first stylus button

Then the pen tool will be selected and the color in the toolbar will be reset to black. 
Interestingly, if black is already the selected color, then the hand tool will be selected again, not the pen tool.

I think that regardless of the selected color pressing and releasing the stylus button should bring back the previously chosen tool.

**Comment by idotobi** [comment] 2020-07-03 20:50
@Krzmbrzl : I think the issue is resolved by my Pull Request #2048 

Following the instructions form @rolandlo : 

![xournalpp-hand-bug](https://user-images.githubusercontent.com/16611056/86496832-5a32db00-bd7f-11ea-8fcb-b26cc9b6f0fb.gif)

That is the behaviour you would expect right?

_Of course apart from the fact that changing the colour while the handtool is active and the eraser is selected via the button does not have any effect._

**Comment by Krzmbrzl** [comment] 2020-07-04 09:32
Yes that's what I'd expect :+1: 
(You linked to an issue instead to your PR though - but the video shows the expected behavior :D )

**Comment by idotobi** [comment] 2020-07-04 10:17
Great :tada:  (and yes the issue was a typo :sweat_smile: ... fixed it)

**Closed** 2020-10-04 16:22 UTC
Labels: Input, bug, papercut, priority: medium
