### ISSUE TITLE
Pasting pictures crashes Xournalpp

### ISSUE THREAD

**Issue by ysooqe** [xournalpp/xournalpp#1611] opened 2019-11-18 12:26 UTC
**Affects versions :**
 - OS: Linux
 - Gnome (X11)
 - Version of Xournal++ : 1.1.0+dev (compiled 2019-11-18) and 1.0.16

**Description**
Trying to paste a picture (screenshot) from the clipboard, e.g. executing `gnome-screenshot -i` and then "saving" that screenshot to the clipboard and then pasting it (e.g. with Ctrl+V) into Xournalpp crashes Xournalpp.

**Steps to reproduce**
1. Start Xournalpp.
2. Run `gnome-screenshot -i`, take a screenshot and copy it to clipboard.
3. Paste that screenshot into Xournalpp with Ctrl+V.

**Expected behavior**
The picture should be pasted into Xournalpp.

**Actual behavior**
Xournalpp crashes.

**Attached files**
[debug_input.log](https://github.com/xournalpp/xournalpp/files/3858571/debug_input_p2.log)
[debug_gdk_input_p2.log](https://github.com/xournalpp/xournalpp/files/3858572/debug_gdk_input_p2.log)
[xinput_list.log](https://github.com/xournalpp/xournalpp/files/3858576/xinput_list.log)

**Comment by LittleHuba** [comment] 2019-11-18 14:46
Did this work in prior versions?

The bug shows that the pasted content could not be transformed to an image. Hence the content is most likely not formatted in a way that Xournal++ could work with it.

**Comment by ysooqe** [comment] 2019-11-18 14:53
> Did this work in prior versions?
> 
> The bug shows that the pasted content could not be transformed to an image. Hence the content is most likely not formatted in a way that Xournal++ could work with it.

Yes, it did definitely work for 1.0.12, I have used this a lot of times.

**Comment by LittleHuba** [comment] 2019-11-18 16:04
Could you try saving the file instead using gnome-screenshot and then opening it in another image editing application. Does a copy paste from that application fail as well?

**Comment by Rmano** [comment] 2019-11-18 16:56
I tried with 1.0.16, Ubuntu 18.04 with image copied with `flameshot` and `GIMP`, and I have no crashes. The format of the images is PNG in both cases, I *think*.

**Comment by LittleHuba** [comment] 2019-11-18 16:58
Then the issue is most likely with `gnome-screenshot`. Does pasting from `gnome-screenshot` into `GIMP` work?

**Comment by Rmano** [comment] 2019-11-18 17:10
I tried with `gnome-screenshot -c` and pasting in `xournalpp` works here. So must be something different between my system/libraries and @ysooqe

**Comment by ysooqe** [comment] 2019-11-19 06:11
> Then the issue is most likely with `gnome-screenshot`. Does pasting from `gnome-screenshot` into `GIMP` work?

I also used `gnome-screenshot -c`

I just tried it, pasting into GIMP and Krita is working fine without any odd behaviors.

> I tried with `gnome-screenshot -c` and pasting in `xournalpp` works here. So must be something different between my system/libraries and @ysooqe

This exact thing is not working for me here.

**Comment by Technius** [comment] 2019-11-28 06:38
Can you post the log that was saved to `~/.xournalpp/errorlogs/`?

Even if the pasted image is malformed, it should not be causing a crash (this indicates a bug on our part). We'll need to adjust the pasting code to gracefully handle errors.

**Comment by Technius** [comment] 2019-11-28 07:23
Direct cause is this line:
https://github.com/xournalpp/xournalpp/blob/fabe9e1ad8d2c8198d49a0540f78062e1ce08b34/src/control/ClipboardHandler.cpp#L351

The [second argument](https://developer.gnome.org/gtk3/stable/gtk3-Selections.html#gtk-selection-data-targets-include-image) is
> whether to accept only targets for which GTK+ knows how to convert a pixbuf into the format

Since it's set to `false`, this is causing GTK to allow pastes of images that cannot be converted into a `GdkPixbuf`. The result is that a null pointer is passed to `Control::clipboardPasteImage`, which _does not_ verify the validity of the passed pixbuf!

The quick fix is to set the second argument to `false`. A better fix is to refactor/rewrite the clipboard handling to ensure that a similar bug cannot occur again (we also need to write tests for these kinds of issues).

@ysooqe This suggests that you might be missing some dependencies. Which distro are you using?

**Comment by ysooqe** [comment] 2019-11-29 13:27
> Can you post the log that was saved to `~/.xournalpp/errorlogs/`?
> 
> Even if the pasted image is malformed, it should not be causing a crash (this indicates a bug on our part). We'll need to adjust the pasting code to gracefully handle errors.

I do not have the logs corresponding to those I recorded when I first reported the issue but I just forced a crash again and got the folling [errorlog](https://gist.github.com/ysooqe/38170654032932b0d63c228445835aa2)

> @ysooqe This suggests that you might be missing some dependencies. Which distro are you using?

I am using "vanilla" Arch Linux with basically all the latest updates installed.

**Comment by LittleHuba** [comment] 2019-11-29 18:29
Yeah Arch Linux is not shipping optional libraries. Problem is that we do not really know what library you would need for that. Maybe a look at the dependency list of Cairo could clear that up.

**Comment by ysooqe** [comment] 2019-11-30 10:11
> Yeah Arch Linux is not shipping optional libraries. Problem is that we do not really know what library you would need for that. Maybe a look at the dependency list of Cairo could clear that up.

I am not entirely sure what you mean by that. If you mean the dependencies of the [cairo package](https://www.archlinux.org/packages/extra/x86_64/cairo/) that is in the Arch Linux repositories, then I can say that I had the package itselft installed (and therefore all of its dependencies) at the time of reporting the issue, i.e. all of the possible denpendency packages/libraries where installed.

**Comment by LittleHuba** [comment] 2019-11-30 10:25
Yeah. There are no optional depends which might have resulted in this. Since I have Arch I just tried to replicate the issue but for me `gnome-screenshot` does not even send the image to the clipboard...

@Rmano and @ysooqe could both of you please provide the raw clipboard content. Maybe we get somewhere if we compare both.

This command should extract the content to a file:
```bash
xsel -b > some.txt
```

**Comment by ysooqe** [comment] 2019-11-30 12:48
> Yeah. There are no optional depends which might have resulted in this. Since I have Arch I just tried to replicate the issue but for me `gnome-screenshot` does not even send the image to the clipboard...
> 
> @Rmano and @ysooqe could both of you please provide the raw clipboard content. Maybe we get somewhere if we compare both.
> 
> This command should extract the content to a file:
> 
> ```shell
> xsel -b > some.txt
> ```

`xsel -b` does not show anything and if I use `xclip -selection clipboard -o` I get `Error: target STRING not available`.
Pasting whatever is residing in the clipboard in Xournalpp keeps crashing it but pasting it in other applications like GIMP works without issues (i.e. the screenshot is pasted into GIMP)

**Comment by ysooqe** [comment] 2019-12-31 08:01
I installed Xournalpp on a fresh installation of the operation system and the issue does not happen on this clean, fresh installation of Arch and Gnome.
I am not sure if this counts as a resolved issue, but it seems like this was more of an issue with Gnome than it was with Xournalpp.

**Comment by lehmanju** [comment] 2020-03-22 22:23
I will close this as I can not reproduce it either.

**Closed by lehmanju** 2020-03-22 22:23 UTC
Labels: Crash, bug, priority: high
