### ISSUE TITLE
mysterious error 

### ISSUE THREAD

**Issue by Shahin-rmz** [xournalpp/xournalpp#4981] opened 2023-07-31 17:35 UTC
Hello, lately I have seen my xournal app has lost it's icon and when I open it it shows me the following error.
Not sure what is it and why it is there as I am not working with it for a week or so.
```
Date: Thu Apr 13 10:05:31 2023
Error: signal 11
[bt]: (0) /snap/xournalpp/69/usr/bin/xournalpp(+0x435b8a) [0x5574fcba5b8a]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f7861502090]
[bt]: (2) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2dcb95) [0x7f78625ffb95]
[bt]: (3) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x13b06) [0x7f7861d67b06]
[bt]: (4) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f7861d88b34]
[bt]: (5) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
[bt]: (6) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e63ce) [0x7f78625093ce]
[bt]: (7) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0xa6) [0x7f7861d6aee6]
[bt]: (8) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x13b06) [0x7f7861d67b06]
[bt]: (9) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f7861d88b34]
[bt]: (10) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
[bt]: (11) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e30ec) [0x7f78625060ec]
[bt]: (12) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x1b2) [0x7f7861d678b2]
[bt]: (13) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x277d3) [0x7f7861d7b7d3]
[bt]: (14) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x125b) [0x7f7861d88dcb]
[bt]: (15) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
[bt]: (16) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d3f2) [0x7f78625603f2]
[bt]: (17) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
[bt]: (18) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
[bt]: (19) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
[bt]: (20) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
[bt]: (21) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
[bt]: (22) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
[bt]: (23) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
[bt]: (24) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
[bt]: (25) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x278c90) [0x7f786259bc90]
[bt]: (26) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
[bt]: (27) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3e3189) [0x7f7862706189]
[bt]: (28) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
[bt]: (29) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d693) [0x7f7862560693]
[bt]: (30) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2b104a) [0x7f78625d404a]
[bt]: (31) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xa2f61) [0x7f78623c5f61]
[bt]: (32) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x13b06) [0x7f7861d67b06]
[bt]: (33) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f7861d88b34]
[bt]: (34) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
[bt]: (35) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e6df8) [0x7f7862509df8]
[bt]: (36) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0xa6) [0x7f7861d6aee6]
[bt]: (37) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x13b06) [0x7f7861d67b06]
[bt]: (38) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f7861d88b34]
[bt]: (39) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
[bt]: (40) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e307e) [0x7f786250607e]
[bt]: (41) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e4a7b) [0x7f7862507a7b]
[bt]: (42) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e8524) [0x7f786250b524]
[bt]: (43) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_event_controller_handle_event+0x70) [0x7f78624c4570]
[bt]: (44) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3c376d) [0x7f78626e676d]
[bt]: (45) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3c3a52) [0x7f78626e6a52]
[bt]: (46) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x9c27f) [0x7f78623bf27f]
[bt]: (47) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x13b06) [0x7f7861d67b06]
[bt]: (48) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x2e0) [0x7f7861d87e50]
[bt]: (49) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
[bt]: (50) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3c4b10) [0x7f78626e7b10]
[bt]: (51) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d068) [0x7f7862560068]
[bt]: (52) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0x91b) [0x7f78625625db]
[bt]: (53) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x400f9) [0x7f78622350f9]
[bt]: (54) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x825a6) [0x7f78622775a6]
[bt]: (55) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x28d) [0x7f7862c0a99d]
[bt]: (56) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x59c40) [0x7f7862c0ac40]
[bt]: (57) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f7862c0ace3]
[bt]: (58) /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x205) [0x7f7861eb3c25]
[bt]: (59) /snap/xournalpp/69/usr/bin/xournalpp(_ZN11XournalMain3runEiPPc+0x5ef) [0x5574fca12559]
[bt]: (60) /snap/xournalpp/69/usr/bin/xournalpp(main+0x29) [0x5574fc9ce292]
[bt]: (61) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f78614e3083]
[bt]: (62) /snap/xournalpp/69/usr/bin/xournalpp(_start+0x2e) [0x5574fc9ce1ae]


Try to get a better stracktrace...
[bt] #1 /snap/xournalpp/69/usr/bin/xournalpp(+0x4360fc) [0x5574fcba60fc]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f7861502090]
??:0
[bt] #3 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2dcb95) [0x7f78625ffb95]
??:0
[bt] #4 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x13b06) [0x7f7861d67b06]
??:0
[bt] #5 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f7861d88b34]
??:0
[bt] #6 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
??:0
[bt] #7 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e63ce) [0x7f78625093ce]
??:0
[bt] #8 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0xa6) [0x7f7861d6aee6]
??:0
[bt] #9 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x13b06) [0x7f7861d67b06]
??:0
[bt] #10 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xfc4) [0x7f7861d88b34]
??:0
[bt] #11 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
??:0
[bt] #12 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1e30ec) [0x7f78625060ec]
??:0
[bt] #13 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x1b2) [0x7f7861d678b2]
??:0
[bt] #14 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x277d3) [0x7f7861d7b7d3]
??:0
[bt] #15 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x125b) [0x7f7861d88dcb]
??:0
[bt] #16 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f7861d89143]
??:0
[bt] #17 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d3f2) [0x7f78625603f2]
??:0
[bt] #18 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
??:0
[bt] #19 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
??:0
[bt] #20 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
??:0
[bt] #21 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
??:0
[bt] #22 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
??:0
[bt] #23 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
??:0
[bt] #24 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0xde0d8) [0x7f78624010d8]
??:0
[bt] #25 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
??:0
[bt] #26 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x278c90) [0x7f786259bc90]
??:0
[bt] #27 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
??:0
[bt] #28 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x3e3189) [0x7f7862706189]
??:0
[bt] #29 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d49e) [0x7f786256049e]
??:0
[bt] #30 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x23d693) [0x7f7862560693]
??:0
[bt] #31 /snap/xournalpp/69/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2b104a) [0x7f78625d404a]
??:0
```

**Comment by bhennion** [comment] 2023-08-01 19:21
This crash log is dated from April. You have probably upgraded Xournal++, so now existing bugreports are shown. This is a duplicate of #4917, #4651, #4038, #2013. and #4979. So I'm closing it.

**Closed by bhennion** 2023-08-01 19:21 UTC
