### ISSUE TITLE
Xournal++ crashes when a blank page is added in "Annotate PDF" mode

### ISSUE THREAD

**Issue by jgrnst** [xournalpp/xournalpp#2211] opened 2020-09-02 22:48 UTC
**Affects versions :**
 - OS: Linux Kubuntu 20.04
 - (Linux only) KDE
 - Which version of libgtk do you use
     - 3.24.20
 - Version of Xournal++: 1.1.0+dev
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method:
       Package built from source

**Describe the bug**
When a blank page is added in "Annotate PDF" mode xournal++ freezes and eventually crashes.

**To Reproduce**
1. Launch xournal++
2. Open a PDF file in "Annotate PDF" mode
3. Open the pull-down menu next to "Insert page" button at the bottom of the screen
4. Select any blank page format (tried with plain, ruled, ruled with a vertical line)'
5. Click "Insert page" button 

**Expected behavior**
A blank page should be added to the document

**Screenshots of Problem**

** Message: 15:39:17.874: lastOpenPath set
[1]+  Segmentation fault      (core dumped) xournalpp

Error log is not created

**Comment by rolandlo** [comment] 2020-09-03 02:58
Most likely this is the same bug as reported in #2144. The problem is that Xournal++ enters an infinite loop of zooming/scrolling methods calling each other. The freeze is fixed in pull request #2146 but at the cost of not getting page number update if you move to page 1 of the document.

**Comment by rolandlo** [comment] 2020-09-03 03:25
In fact, as I checked now, with PR #2146 there is no freeze when adding a blank page in "Annotate PDF" mode. It is interesting, that this happens only when the background is a pdf in the unfixed version.

**Comment by nikkopomata** [comment] 2020-10-05 16:34
I've been experiencing essentially the same bug (version 1.1.0+dev, libgtk 3.24.20, Mint 20, XFCE 4.14)

The following DOES NOT work, i.e. xournal++ crashes:
- Adding non-pdf-background pages to a pdf-background document (existing .xopp, new Annotate Document, etc) when xournal++ was opened on a blank-background document (e.g. opened without an argument, or opened with a reference to an existing blank-background document) (exception below)
- Adding image-background pages to a blank-background document when xournal++ was opened on a blank-background document

The following DOES work fine:
- Adding blank-style pages to a blank-background document, apparently any context
- Adding pdf-background pages to a pdf-background document, apparently any context
- Adding blank-style pages to a pdf-background document *when the focus is on a blank-background page* (which has been added in a previous session)
- Any of the above operations *when* xournal++ was opened on a pdf-background document (e.g. using Open With, or in terminal via "xournalpp doc.pdf" or "xournalpp doc.xopp")

**Comment by rolandlo** [comment] 2020-10-05 20:06
@nikkopomata Thanks for your precise observations. That should help a lot in finding the bug(s).

**Comment by rolandlo** [comment] 2020-10-11 19:08
@nikkopomata Could you please test PR  #2312. It may solve the problem.

**Closed** 2020-10-30 20:47 UTC
Labels: Crash, bug, confirmed, priority: high

**Comment by Technius** [comment] 2020-10-30 21:11
Is #2346 guaranteed to fix this bug?

**Comment by jgrnst** [comment] 2020-10-30 21:27
> Is #2346 guaranteed to fix this bug?

I tested the latest version few minutes ago, and it looks like that issue has disappeared.

**Comment by rolandlo** [comment] 2020-10-30 21:29
Also according to my tests this bug has been fixed with #2346.

**Comment by rolandlo** [comment] 2020-10-30 22:47
You can also test out PR #2146 on top of it. You can append new pdf pages, delete pages, add pages with any background and append the pdf pages again as long as you want, there is no crash. Previously it crashed on the first time already.
