### ISSUE TITLE
Zooming with the slider changes page

### ISSUE THREAD

**Issue by peetCreative** [xournalpp/xournalpp#416] opened 2018-11-29 17:46 UTC
When I zoom with the slider the location in the document is changing to other page. Zooming back brings me back to the correct page.

**Comment by peetCreative** [comment] 2018-12-05 14:58
This seems to be a bug with the automatic gtk zooming..

**Comment by andreasb242** [comment] 2018-12-06 18:33
There is no GTK Zooming, this is a Custom Xournal++ implementation.

**Comment by peetCreative** [comment] 2018-12-10 18:30
mh... That's right.... Took me a while digging through the code. I suspect `Layout::layoutPages` and subsequent (`this->view->pagePosition->update(this->view->viewPages, len, height)`) to make the changes. 
Still don't completly understand what is going on there. The function is called three times, when pressing the ZoomIn, ZoomOut or two times when the slider is used. This is probably not the bug, but seems unefficient? 
One may also rewrite such function with std libraries, as it gets easier to understand is, or?

**Comment by andreasb242** [comment] 2018-12-10 19:39
> This is probably not the bug, but seems unefficient?
Yes, probably a Bug, but I sometimes it's not easy to get rid of this, and sometimes it's really needed (e.g. auto layouting boxed layouts)

>One may also rewrite such function with std libraries, as it gets easier to understand is, or?
About Which standard Libraries are you thinking about?

**Comment by andreasb242** [comment] 2018-12-10 21:08
Layout.cpp is mainly the layouting of the pages. It calculates the position of each page, depending on the Zoom and the layout options, like two pages.

The Layout itself does not have any container, the container is in XournalView, and its only an array:
	XojPageView** viewPages;

The whole Displaying is done by GTK, also which part are rendered or not.
The painting is done in gtk_xournal_draw:

Iterate over all Pages
>	while (it.hasNext())
>	{
...

If the page is not visible at all, skip it...
>		if (!clippingRect.intersects(pv->getRect()))
>		{
>			continue;
>		}

...

Paint a single page, the page is cached as image, and rendered in a background Thread.
We draw the whole page, but technical over Cairo / GTK only the part which is needed, is painted.
But this is all handled by GTK
>		pv->paintPage(cr, NULL);

>	}

But this is mostly not relevant for this bug.
The issue is relative simple:

If the Zoom changes, the surface size increases:
>	this->setLayoutSize(width, height);

So the Scrollbar gets updated (in Background by GTK)
But I think the Scrollbar keeps the current position. But the Page is not at this position anymore, because the page is bigger or smaller.

Therefor the solution would might be:
Before change the zoom, which page at which position is at the center of the screen vertically.
e.g. gtk_xournal_get_page_view_for_pos_cached does something like this:

>	PagePositionHandler* pph = xournal->view->getPagePositionHandler();
>	return pph->getViewAt(x, y, xournal->pagePositionCache);

*new* Calculate the relative position (0.0 ... 1.0 or something like this)
Do the Zooming.
*new* call XournalView::scrollTo(size_t pageNo, double yDocument)
yDocument needs to be the absolute position, so _lastposition * pageHeigth * zoom_ 

That should do it.

**Comment by peetCreative** [comment] 2018-12-12 01:47
I was doing a bit work on it rewriting zooming. But still has the problem. pushed my changes to: 
https://github.com/peetCreative/xournalpp/tree/fix_zoom_slider

**Comment by peetCreative** [comment] 2018-12-15 22:32
While trying to solve this. I found out that my changes in #526 causes problems with shift zooming. Maybe rewert #526.

**Comment by andreasb242** [comment] 2018-12-16 09:54
@peetCreative  I have a look at this

**Comment by andreasb242** [comment] 2018-12-16 11:13
Basically working, but not perfect.
I currently store only the page, not the position of the page.
And if the page is so small, that multiple pages are displayed, the zoom may change the page to one of them.

**Comment by morrolinux** [comment] 2018-12-20 11:54
I'm sorry to say this, but 8de93a8d26b7dcf65e10ba519ec690c2f20bd084 totally broke the "pinch to zoom" feature for touch devices.
Here's what the previous commit (cde933f56b4b14983b72674072ecd28e7dc5b8c9) looks like:
![peek 20-12-2018 12-49](https://user-images.githubusercontent.com/20294254/50283297-c24bf580-0455-11e9-9072-b7a31e883b7c.gif)

And Here's what this commit (8de93a8d26b7dcf65e10ba519ec690c2f20bd084) looks like:
![peek 20-12-2018 12-53](https://user-images.githubusercontent.com/20294254/50283451-37b7c600-0456-11e9-8b2d-421f9e70e453.gif)

The zoom always happens relative to the top left corner of the current page, making it useless on touch devices (where it worked fine)

**Comment by andreasb242** [comment] 2018-12-20 21:51
Sorry, i'll have a look at this

**Comment by andreasb242** [comment] 2018-12-22 10:33
should be fixed with https://github.com/xournalpp/xournalpp/pull/565/files

**Comment by peetCreative** [comment] 2018-12-22 16:17
I just try to find out why your changes do not fix the problem for me.

**Comment by andreasb242** [comment] 2018-12-22 16:31
What's happening?

**Comment by peetCreative** [comment] 2018-12-22 16:53
I think the widget Position is not scaled.

**Closed** 2018-12-22 17:49 UTC
Labels: bug

**Comment by andreasb242** [comment] 2018-12-22 17:57
My the discussion should be here in the Ticket.

I comment the pull. I'll copy to here.
https://github.com/xournalpp/xournalpp/pull/576/

----
@peetCreative Is this really working for you? How did you test this?

Even with the mouse and with the touch it doesn't work.
If I do a review, I look at code, like possible crashes, something which looks really wrong or so, and I probably don't see a bug.

If I analyze it now in detail, the only relevant change you did is:
zoomWidgetPosX and zoomWidgetPosY is scaled.

But this are coordinates which are on the widget side, not on the document side, therefore are independent of the zoom.

With your change now: the document moves down/right if I zoom in, or up/left if I zoom out.
