### ISSUE TITLE
PPA-Support for Ubuntu Groovy Gorilla?

### ISSUE THREAD

**Issue by AxelMKlein** [xournalpp/xournalpp#2343] opened 2020-10-26 11:21 UTC
Hi dear Xournal++-Team,

when will the support for Ubuntu Groovy Gorilla happen in the PPA andreasbutti/xournalpp-master?

Great software! Love it.

Best regards
Axel

**Comment by Technius** [comment] 2020-10-30 08:34
Duplicate of #2107.

**Closed by Technius** 2020-10-30 08:34 UTC

**Comment by rolandlo** [comment] 2020-11-01 04:09
The PPA support for Ubuntu Groovy Gorilla has been added.
