### ISSUE TITLE
Enable screen page scrolling 

### ISSUE THREAD

**Issue by christiankral** [xournalpp/xournalpp#2063] opened 2020-06-13 08:37 UTC
**Is your feature request related to a problem? Please describe.**

When I am reading a document (made of many A4 pages) and take notes I have a couple ways to scroll through such document
- Cursor (arrow) keys up and down (too slow)
- Use the sidebars (distracts from reading as such action requires a precise mouse pointer movement)
- Gestures (two fingers) is often a little annoying as I always have to move my fingers towards the screen, scroll on, and rest the arm somewhere else then 
- Page Up and Down does unfortunately not scroll vertically within the page but always to the previous or next page: this is the **feature request**: please allow scrolling 

**Describe the solution you'd like**

- In the current implementation CTRL+Page Up and Page Down switches from one page to another. This is good
  ![image](https://user-images.githubusercontent.com/4184218/84564034-425bce80-ad60-11ea-8a3f-2edf03dbed36.png)
- Pressing Page Up and Down (**without CTRL**) does the very exact thing as if I were holding the CTRL key. I were great if pressing Page Up and Down (**without CTRL**) would allow to move approximately 80-90% of the displayed vertical range up and down. This would allow continuously reading the document and note taking if required.

![image](https://user-images.githubusercontent.com/4184218/84564118-f3faff80-ad60-11ea-98cc-e435ede39a7f.png)

**Comment by Technius** [comment] 2020-06-18 02:36
Duplicate of #1412.

**Closed by Technius** 2020-06-18 02:36 UTC
Labels: enhancement
