### ISSUE TITLE
Feature request to move content to next page with vertical space tool

### ISSUE THREAD

**Issue by legendofa** [xournalpp/xournalpp#2330] opened 2020-10-21 12:26 UTC
Sometimes there is not enough space on a page to insert something. Creating a new page would leave a lot of whitespace.

It would be useful to insert the right amount vertical space and move content of every page down to the next page.
Could be a setting for the vertical space tool (maybe the default one).

This should appear on the next page:

![feature](https://user-images.githubusercontent.com/34162874/96719064-73947d00-1398-11eb-8ffb-f4e6bf0db326.gif)

Copying content manually to the next page can be time consuming for long documents.

Pictures then can be moved to the next page if half of them are overlapping the next page.

**Comment by rolandlo** [comment] 2020-10-21 13:44
duplicate of  #1186

**Closed by rolandlo** 2020-10-21 13:44 UTC
Labels: enhancement
