### ISSUE TITLE
PDF export results in near-empty file

### ISSUE THREAD

**Issue by inducer** [xournalpp/xournalpp#3394] opened 2021-09-12 23:58 UTC
**Affects versions :**
 - OS: Linux
 - Desktop environment: Gnome 40
```
Xournal++ 1.1.0
└──libgtk: 3.24.30
```
 - Installation method: from git source, bd3ca75f
 - Bug also appears with the 1.1.0 release deb.

**Describe the bug**
Exporting the file `report-marked-up.xopp` at

https://ssl.tiker.net/nextcloud/s/bgL5QJa5ttyMy2k?

results in the (useless, near-empty) PDF file at the same location. Note how the PDF is smaller than the original `report.pdf`. I should add that this does not happen for all overlay PDFs, but this PDF (fortunately) exhibits the problem *and* is redistributable.

**To Reproduce**

1. Download files from https://ssl.tiker.net/nextcloud/s/bgL5QJa5ttyMy2k?
1. Open `report-marked-up.xopp`
2. `Ctrl-E` to export to PDF
3. Hit Enter to confirm defaults
4. Save to `report-marked-up.pdf`
4. Observe useless PDF having been created.

Printing to PDF yields the expected output and serves as a temporary workaround.

**Expected behavior**
A PDF containing the original PDF content and my markups is generated.

#3388 is possibly related, although no error message is generated during export.

**Comment by rolandlo** [comment] 2021-09-13 03:13
The file exports normally on my system (Ubuntu 21.04) with Xournal++ 1.1.0.

**Comment by inducer** [comment] 2021-09-13 04:14
Huh. The AppImage also exports this correctly, too, which means it's likely one of the shared libraries on my system. Likeliest candidates:

- `libcairo2`, mine (Debian testing) 1.16.0-5, [Ubuntu](https://packages.ubuntu.com/search?keywords=libcairo2&searchon=names&suite=hirsute&section=all) 1.16.0-5ubuntu1
- `libpoppler102`, mine (Debian testing) 20.09.0-3.1, [Ubuntu](https://packages.ubuntu.com/search?keywords=libpoppler&searchon=names&suite=hirsute&section=all) 21.02.0-1

I guess I'll go hunt for an updated poppler to check. Unfortunately, the version I have is the one with which Debian stable was released.

**Comment by inducer** [comment] 2021-09-13 04:24
Hmm... so Debian has libpoppler111 (21.06.1-1) in `experimental`, but upgrading to that and rebuilding xournal++ doesn't seem to help.

**Comment by rolandlo** [comment] 2021-09-13 12:56
> Hmm... so Debian has libpoppler111 (21.06.1-1) in `experimental`, but upgrading to that and rebuilding xournal++ against it doesn't seem to help.

The AppImage uses relatively old dependencies, since it is built on Ubuntu 18.04. So upgrading libraries may not be the right step.

**Comment by ttrindade80** [comment] 2021-09-18 00:39
Hello all, I am using Arch Linux and have the same issue.
poppler 21.09.0-1
cairo 1.17.4-5
xournalpp 1.1.0-2

The pdf output file is empty.

**Comment by Technius** [comment] 2021-09-18 20:31
I'm not sure it's a dependency version problem. The PDF exports correctly on Solus with poppler 21.06.1 and cairo 1.17.4.

**Comment by LittleHuba** [comment] 2021-09-20 11:35
This could as well be a regression in a newer version of Poppler or a distribution-specific fix gone wrong. You may want to test compiling Poppler 21.06.1 manually on your system.

**Comment by ttrindade80** [comment] 2021-09-22 13:52
> This could as well be a regression in a newer version of Poppler or a distribution-specific fix gone wrong. You may want to test compiling Poppler 21.06.1 manually on your system.

I tried with poppler 21.06.1, from Arch repository, and the problem persists. Then I used the AUR repository to install poppler from git, but everything remains the same.

**Comment by ttrindade80** [comment] 2021-09-23 12:37
> This could as well be a regression in a newer version of Poppler or a distribution-specific fix gone wrong. You may want to test compiling Poppler 21.06.1 manually on your system.

Today I tried the poppler master branch, Release 21.09.0, and get the same.

**Comment by LittleHuba** [comment] 2021-09-23 16:25
`G_MESSAGES_DEBUG=Poppler xournalpp` produces the following output on the console:

```
Poppler-INFO: 18:20:12.838: Internal error at position -1: cairo context error: invalid tag name, attributes, or nesting<0a>
```

This is definitely an issue in Poppler. Please open a ticket over at their issue tracker and link it here.

**Comment by LittleHuba** [comment] 2021-09-23 16:31
You can use `pdfunite <source> <destination>` to fix such files for now. This command should not modify your PDF.

**Comment by inducer** [comment] 2021-09-23 22:23
> `pdfunite`

I'm not sure I understand. The PDF xournal++ creates is tiny (in terms of file size) and AFAIK contains none of the information from the drawing in xournal++. How would `pdfunite` recover this information?

**Comment by LittleHuba** [comment] 2021-09-24 06:39
No pdfunite is not able to recover this information. You can reparse the original background file though.

So please use pdfunite on your background PDF.

**Comment by ttrindade80** [comment] 2021-09-24 23:14
Thank you Ulrich,

The problem is in the original pdf file, I use pdfunit and the output pdf
works!

Tiago Trindade
***@***.***


Em sex., 24 de set. de 2021 às 03:40, Ulrich Huber ***@***.***>
escreveu:

**Comment by LittleHuba** [comment] 2021-09-26 06:56
Duplicate of #3380

**Closed by LittleHuba** 2021-09-26 06:56 UTC
Labels: bug, Dependency Issue
