### ISSUE TITLE
Regression: Selection Tool not working with Styuls Button 2

### ISSUE THREAD

**Issue by idotobi** [xournalpp/xournalpp#2539] opened 2020-12-13 16:32 UTC
**Affects versions :**
 - OS: Arch
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use: libgtk: 3.24.23 
 - Version of Xournal++: Xournal++ 1.1.0+dev 
 - Installation method: build from 

**Describe the bug**
Lasso tool does no longer work when activated via Stylus Button 2:
![image](https://user-images.githubusercontent.com/16611056/102017520-cb7fac80-3d67-11eb-842a-081068d25b99.png)

**To Reproduce**
1. Set Stylus Button 2 to Select Region
2. Save Settings
3. Try to use Button 2 from Stylus

**Expected behavior**
Selected Region is shown while drawing and contained strokes are selected after completion.

**Screenshots of Problem**
No selected region is shown and nothing can be selected.
![Peek 2020-12-13 17-31](https://user-images.githubusercontent.com/16611056/102017769-2bc31e00-3d69-11eb-86e2-b7ae6bd1acd8.gif)

**Additional context**
It seems that 925acf9eefce1775bb3b174d2742d620243a3412 introduced this regression. @Febbe could you please check where this could come from?

**Comment by idotobi** [comment] 2021-02-12 21:50
I just gave a quick shot at trying to find the root cause and I realized that the problem is not just limited to the selection tool.

Basically when I press the "Button 1" xournalpp no longer triggers `XojPageView::onButtonPressEvent`s. However, with the eraser button it works. I'll try around a bit more, but maybe this helps someone else.

**Comment by idotobi** [comment] 2021-02-13 20:55
I think I figured out the problem. It's that 

https://github.com/xournalpp/xournalpp/blob/891c972c27a335113f8a424ae7d3adcbc1ed3f18/src/gui/inputdevices/StylusInputHandler.cpp#L29 only handles `event.button == 1`

However, when testing on my machine the following is observed:

* Drawing without Stylus Button -> `event.button == 1`
* Drawing with Stylus Button 2 -> `event.button == 3`
* Drawing with Eraser Button -> `event.button == 1`

Adding  an additional check for `event.button ==3` would solve the issue.

However comparing to the old inputdevice implementation I guess `event.button > 0` fits the bill better as there might also be other buttons.

https://github.com/xournalpp/xournalpp/blob/master/src/gui/inputdevices/old/NewGtkInputDevice.cpp#L227-L230

Apologies to @Febbe as it was not your commit that triggered this as I originally assumed. I thought it was your commit as in your commit the _config file path_ had changed. This resulted in me having two different preferences one with the new input system and one with the old input system :see_no_evil: when trying to find when this observed "regression" happened. The bug at the root of this, however, was there pretty much since the beginning.

**Comment by tattsan** [comment] 2021-02-15 12:40
I can't reproduce this behavior under normal settings. ( I also use the app on X11/Arch Linux. )
If I configure both
-  ``xsetwacom set "Some device Pen stylus" "TabletPCButton" "on"``  for xf86-input-wacom driver.
- [ ] ``Merge button events with stylus tip events`` is not checked in Xournal++ Preferences.

then I get the same behavior. And if the PR #2805 is applied, the button function is recoverd.
1. I've thought the above settings are wrong configuration. Am I wrong?
2. Does the PR #2805 intend to save these settings?

**Comment by idotobi** [comment] 2021-02-16 15:58
@tattsan : Thank you so much!

You're right :see_no_evil:.

Seems like I have this setting standard and only now started to have issues with it.

```bash
/h/~ $ xsetwacom --list devices
Wacom ISDv4 E6 Pen stylus       	id: 13	type: STYLUS    
Wacom ISDv4 E6 Finger touch     	id: 14	type: TOUCH     
Wacom ISDv4 E6 Pen eraser       	id: 20	type: ERASER    
/h/~ $ xsetwacom get 13 TabletPCButton
on
```

I guess this PR can be closed then.
However, I'm wondering if this should be documented additional to being implemented in the settings.
I'll continue the discussion of that in the linked issue.

**Comment by idotobi** [comment] 2021-02-16 16:28
For now I added it to https://github.com/xournalpp/xournalpp/wiki/Frequently-Asked-Questions-&-Problem-Solving.

One further thing I was wondering when researching for the FAQ. The official [repo](https://github.com/linuxwacom/xf86-input-wacom/wiki/xsetwacom#tabletpcbutton) of xsetwacom  and the man pages say that the default for this setting is `on` for Tablets.

```
       TabletPCButton on|off
              If  on, the stylus must be in contact with the screen for a sty‐
              lus side button to work.  If off, stylus buttons will work  once
              the  stylus is in proximity of the tablet (regardless of whether
              it is touching the screen).  Default:  on for  Tablet  PCs;  off
              for all other models.
```

In xournalpp the setting is `off` by default. Is this intentional?
I would assume that most users of xournalpp use a tablet, right?

**Comment by tattsan** [comment] 2021-02-16 17:13
This confusing setup has been also discussed  in #2496 .

If both settings were enabled, it caused the issue #2053 (It seems that #1679 and #2762 are also the same issue), so I've disabled both settings almost a half-year.  But recently #2749 fixed the issue.

**Comment by tpwrules** [comment] 2022-08-30 19:33
FWIW I have exactly this symptom on my Surface Go with Windows 10 and exactly the same fix works (turning on "Merge button events with stylus tip events"). I don't know how to do the equivalent `xsetwacom` check in Windows but this helped me and maybe the documentation could be tweaked.

**Comment by rolandlo** [comment] 2022-08-30 19:44
On Windows, that `Merge button events with stylus tip events` checkbox should always be enabled, I think, since that corresponds to the way input sequences are reported by Gtk. See https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-860083264 and https://github.com/xournalpp/xournalpp/issues/2316#issuecomment-867621727

**Closed** 2023-02-01 08:31 UTC
Labels: bug, Input, priority::medium

**Comment by gomarcus** [comment] 2023-12-13 13:52
The keys on the MS Slim Pen 2 still dont work!
When changing the settings for a button, the tool seems to be switched after button use, but when (e.g. using insert space tool) the stylus would not insert space (but it seems like the tool specific mouse indicator is used). Same with most other tools like select, ...
