### ISSUE TITLE
Bug during program startup

### ISSUE THREAD

**Issue by ma-sadeghi** [xournalpp/xournalpp#4974] opened 2023-07-29 15:27 UTC
```
Date: Tue Oct 11 15:11:06 2022
Error: signal 11
[bt]: (0) xournalpp(+0xc10d0) [0x5633d1eef0d0]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f11b3bc6090]
[bt]: (2) xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x5633d1f4847b]
[bt]: (3) xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xd45) [0x5633d1f3c1d5]
[bt]: (4) xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x5633d1f2aa79]
[bt]: (5) xournalpp(_ZN10MainWindow15toolbarSelectedEP11ToolbarData+0x7c) [0x5633d1f2ab0c]
[bt]: (6) xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbd) [0x5633d1f2b34d]
[bt]: (7) xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x957) [0x5633d1f2cbc7]
[bt]: (8) xournalpp(+0xc5746) [0x5633d1ef3746]
[bt]: (9) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x1b2) [0x7f11b437a802]
[bt]: (10) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x28814) [0x7f11b438e814]
[bt]: (11) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x10ae) [0x7f11b4399bbe]
[bt]: (12) /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f11b439a0f3]
[bt]: (13) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x122) [0x7f11b44d27f2]
[bt]: (14) /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe2bce) [0x7f11b44d2bce]
[bt]: (15) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x172) [0x7f11b44d2f52]
[bt]: (16) xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x5633d1ef02c1]
[bt]: (17) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f11b3ba7083]
[bt]: (18) xournalpp(_start+0x2e) [0x5633d1eee84e]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0xc156c) [0x5633d1eef56c]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f11b3bc6090]
??:0
[bt] #3 xournalpp(_ZNK7Palette10getColorAtEm+0x1b) [0x5633d1f4847b]
??:0
[bt] #4 xournalpp(_ZN15ToolMenuHandler4loadEP11ToolbarDataP10_GtkWidgetPKcb+0xd45) [0x5633d1f3c1d5]
??:0
[bt] #5 xournalpp(_ZN10MainWindow11loadToolbarEP11ToolbarData+0x59) [0x5633d1f2aa79]
??:0
[bt] #6 xournalpp(_ZN10MainWindow15toolbarSelectedEP11ToolbarData+0x7c) [0x5633d1f2ab0c]
??:0
[bt] #7 xournalpp(_ZN10MainWindow20createToolbarAndMenuEv+0xbd) [0x5633d1f2b34d]
??:0
[bt] #8 xournalpp(_ZN10MainWindowC1EP15GladeSearchpathP7Control+0x957) [0x5633d1f2cbc7]
??:0
[bt] #9 xournalpp(+0xc5746) [0x5633d1ef3746]
??:0
[bt] #10 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x1b2) [0x7f11b437a802]
??:0
[bt] #11 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x28814) [0x7f11b438e814]
??:0
[bt] #12 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x10ae) [0x7f11b4399bbe]
??:0
[bt] #13 /lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x93) [0x7f11b439a0f3]
??:0
[bt] #14 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_register+0x122) [0x7f11b44d27f2]
??:0
[bt] #15 /lib/x86_64-linux-gnu/libgio-2.0.so.0(+0xe2bce) [0x7f11b44d2bce]
??:0
[bt] #16 /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x172) [0x7f11b44d2f52]
??:0
[bt] #17 xournalpp(_ZN11XournalMain3runEiPPc+0x4b1) [0x5633d1ef02c1]
??:0
[bt] #18 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f11b3ba7083]
??:0
[bt] #19 xournalpp(_start+0x2e) [0x5633d1eee84e]
??:0
```

**Comment by lilianasouz** [comment] 2023-08-03 19:07
Date: Wed Nov 23 15:54:43 2022
Error: signal 11
[bt]: (0) xournalpp(+0x201a75) [0x55d63ab13a75]
[bt]: (1) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7fd7166410c0]
[bt]: (2) xournalpp(_ZNK7Element7getTypeEv+0x4) [0x55d63aae4db4]
[bt]: (3) xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x22) [0x55d63ab0a382]
[bt]: (4) xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x9b) [0x55d63ab0a53b]
[bt]: (5) xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xfe) [0x55d63ab0af8e]
[bt]: (6) xournalpp(_ZN10PreviewJob8drawPageEv+0x38a) [0x55d63aa073ea]
[bt]: (7) xournalpp(_ZN10PreviewJob3runEv+0x34) [0x55d63aa07764]
[bt]: (8) xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0xf3) [0x55d63aa0a333]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x87b59) [0x7fd717c1ab59]
[bt]: (10) /usr/lib/x86_64-linux-gnu/libc.so.6(+0x8f1da) [0x7fd7166911da]
[bt]: (11) /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x44) [0x7fd716719d84]


Try to get a better stracktrace...
[bt] #1 xournalpp(+0x202096) [0x55d63ab14096]
[bt] #2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0) [0x7fd7166410c0]
[bt] #3 xournalpp(_ZNK7Element7getTypeEv+0x4) [0x55d63aae4db4]
[bt] #4 xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x22) [0x55d63ab0a382]
[bt] #5 xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x9b) [0x55d63ab0a53b]
[bt] #6 xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xfe) [0x55d63ab0af8e]
[bt] #7 xournalpp(_ZN10PreviewJob8drawPageEv+0x38a) [0x55d63aa073ea]
[bt] #8 xournalpp(_ZN10PreviewJob3runEv+0x34) [0x55d63aa07764]
[bt] #9 xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0xf3) [0x55d63aa0a333]
[bt] #10 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x87b59) [0x7fd717c1ab59]
[bt] #11 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x8f1da) [0x7fd7166911da]
[bt] #12 /usr/lib/x86_64-linux-gnu/libc.so.6(clone+0x44) [0x7fd716719d84]

**Comment by bhennion** [comment] 2023-08-08 10:27
Thanks for reporting. Those crash logs are pretty old and are only shown now because of the update to 1.2. The cause of thoses crashes have most likely been fixed by now.
Please open a new issue if a new crash occurs and you have a more recent crashlog.

**Closed by bhennion** 2023-08-08 10:27 UTC
