### ISSUE TITLE
Crash after pressing undo

### ISSUE THREAD

**Issue by as4s4hetic** [xournalpp/xournalpp#5111] opened 2023-09-01 10:46 UTC
[errorlog.20230831-103158.log](https://github.com/xournalpp/xournalpp/files/12497127/errorlog.20230831-103158.log)
### Operating System

Linux

### (Linux only) Distribution

Arch Linux

### (Linux only) Desktop Environment

StumpWM

### (Linux Only) Display Server

X.Org

### Installation Method

pacman

### Xournal++ Version

1.2.1

### libgtk Version

3.24.38

### Bug Description

xournalpp crashed after i hit undo

I have not tried to reproduce this bug

### Expected Behaviour

undo

### Steps to Reproduce

I have not tried to reproduce it as I do not remember the exact sequence of actions I performed for this to happen

### Additional Context

Error log attached

**Comment by as4s4hetic** [comment] 2023-09-01 10:47
[errorlog.20230831-103158.log](https://github.com/xournalpp/xournalpp/files/12497122/errorlog.20230831-103158.log)

**Comment by rolandlo** [comment] 2023-09-01 14:10
Could this be a duplicate of #5046?

**Comment by bhennion** [comment] 2023-09-03 16:17
> Could this be a duplicate of #5046?

Yes. The crashlog is the same, the triggering sequence is the same. Closing.

**Closed by bhennion** 2023-09-03 16:17 UTC
Labels: bug
