### ISSUE TITLE
Multilayer selection

### ISSUE THREAD

**Issue by yasmah74** [xournalpp/xournalpp#4879] opened 2023-05-17 14:02 UTC
**Affects versions :**
 - OS: Linux Ubuntu 23.04
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use: 3.24.37
 - Version of Xournal++: 1.1.3+dev
 - Installation method: apt

**Describe the bug**
When attempting to use the "Select Multi-Layer Region" and "Select Multi-Layer Rectangle" tools in the application, the expected behavior is to select objects from all layers included the layers below. However, the tools are not functioning as intended and are only selecting objects from the uppermost layer, rendering them indistinguishable from the "Select Region" tool. As a result, it is currently impossible to select objects from multiple layers at once using these tools.

**To Reproduce**
1. write something in layer 1
2. write something in layer 2
3. select both Writtings with "Select Multi-Layer Region" or "Select Multi-Layer Rectangle" from layer 2.

**Expected behavior**
see above

**Comment by yasmah74** [comment] 2023-05-17 14:06
Related to: #2783

**Comment by rolandlo** [comment] 2023-05-18 08:52
Closing as a duplicate of #2783

**Closed by rolandlo** 2023-05-18 08:52 UTC
Labels: bug
