### ISSUE TITLE
[Multi-monitor] [Windows] Pen draws at wrong position

### ISSUE THREAD

**Issue by eleonoraarnone** [xournalpp/xournalpp#1801] opened 2020-03-26 15:18 UTC
**Affects versions :**
 - OS: Windows
 - Version of Xournal++: 1.0.17 
 - Installation method: form the zip on GitHub

**Describe the bug**
The bug is similar to the one reported in issue #1472 and it occurs when I am using two monitors. The app was working correctly until I connected the second monitor. Like in the other issue, the pen's starting point for drawing is incorrect if I use it with my stylus, but it works fine with my mouse. 
I am using a Huion drawing tablet, the two monitors have different resolutions: one is 3200x1800, while the second is 2560x1440. 
With the Huion tablet, you can choose to work on the whole area or on a monitor at a time. I tried all the three options (whole area, first screen only, second screen only) and the error always occurs (even if with different misplacement). 
The pen works fine on other applications like Adobe Reader and OneNote, thus I believe it is not an issue of the tablet itself. 

**Screenshots of Problem**
Look at issue #1472, the screenshot would be exactly the same.

**Comment by Febbe** [comment] 2020-03-26 15:34
Hello @eleonoraarnone
I can imagine different causes of this problem, but I can't reproduce it. So we need your help.
You are using QHD and a WQHD Monitor, so working with them is propably not possible without a custom scaling factor. Can you retry it with a Monitor scaling off 100% again? 
(Desktop -> rightclick -> displaysettings -> scaling)
Also It could be, that it will work again, if you swap your primary screen, can you try to swap the primary screen?
Another thing could be, that the underlying Input System stretches the drawing Tablet over all screens, then it would be a dependancy issue.

Thanks for your help.

**Comment by Febbe** [comment] 2020-03-26 15:38
Related to: #1773

**Comment by eleonoraarnone** [comment] 2020-03-26 16:00
Hi @Febbe , 
I normally use the QHD without scaling and the other one with a 250% scaling.
I tried to put the scaling at 100% on both the monitors and the app works correctly. Unfortunately, as you said it is not possible to use the 13 inches 3200x1800 monitor without scaling. 

I also tried to swap the primary screen (leaving the 250% scaling) but it didn't work. 
 
Regarding the last point, I imagine that should be the behavior when I choose to work simultaneously on both monitors with the tablet, but not when I choose one screen to work on. I do not know how to check this if you have any idea on how to verify if it is a dependency issue I'm happy to check. I attach you a screenshot of the Huion app that maybe can help. 

Thank you! 

![image](https://user-images.githubusercontent.com/11456601/77668038-33e0f080-6f83-11ea-93cd-5657cb183a4f.png)

**Comment by Febbe** [comment] 2020-03-26 16:21
Switching the screens only makes sense, if you work on the screen with no scaling, did you tried to draw on each monitor with each configuration? Now we know, that's at least a scaling issue 😅. Can you also try to use xournalpp with only the wqhd monitor and scaling?

**Comment by eleonoraarnone** [comment] 2020-03-26 16:30
Yes I tried with all the possible configurations and the issue is always there. 
If I disconnect the external monitor everything works on fine on my laptop (that has the wqhd monitor) with the scaling. 
I believe the problem is the different scaling because I also tried to set the scaling to 200% on both screens and the app works fine.

**Comment by Febbe** [comment] 2020-03-26 16:38
Ok you helped us a lot, I think we can work with that.

**Comment by Wolfgang001** [comment] 2020-04-03 00:20
I have the same issue:  Pen draws at wrong position, when I use TWO monitors with different scaling.   Works fine with one monitor, and also when the scaling factor is the same.  No problem in OneNote, even for different scaling.

**Comment by ownhardy** [comment] 2020-04-22 18:41
I have the (presumably) same issue: In my case I use a dual monitor setup. The second monitor (where Journal++ runs on) is set to a non-native screen resolution, such that it intentionally dispaly wide black borders ar the left and right end of the monitor. When using a touch pen on this display, then Journal++ draws the line with quite a big offset. (When judging with my eye, I would say this offset is the same as the width of the black borders on this display.)

**Comment by KrackenO** [comment] 2020-05-05 08:26
OS: Windows
    Version of Xournal++: 1.0.18
    Installation method: form the zip on GitHub

Same issue here for one of my friend I just tried to help. She has 2 monitors. If she opens Xournal++, everything works fine. But if she closes it and restart Xournal++, then the pen doesn't draw at the stylus location. If she unplugs the second monitor, everything works fine again.

If that may help: we found that setting "Scale and layout" to 100% in the Windows Display Panel solve the problem (but is not convenient because everything is so small on the Desktop...)
![Capture d’écran de 2020-05-05 10-22-07](https://user-images.githubusercontent.com/64832976/81047302-6d7a1500-8eba-11ea-9818-2321fbb03fc5.png)

**Comment by LittleHuba** [comment] 2020-05-05 12:48
Ahh that is most likely the GTK_Scale thing again. We had that issue once before but it had been fixed then...

Seems like it resurfaced in GTK. See here for further reference: https://gitlab.gnome.org/GNOME/gtk/-/issues/734

**Comment by blueWalrus** [comment] 2020-06-07 07:08
I have the same issue simply by rotating my screen. 

OS: Windows
Version of Xournal++: 1.0.18

**Comment by hacker1024** [comment] 2020-06-17 01:16
I have this too, both scales are at 100%.

**Comment by hacker1024** [comment] 2020-06-17 01:18
This happens on Linux when XInput isn't configured correctly. I don't know how GTK works on Windows, but if it includes XInput code, the issue could be related.

https://wiki.archlinux.org/index.php/Touchscreen#Using_a_touchscreen_in_a_multi-head_setup

**Comment by zerovectorspace** [comment] 2020-08-31 21:58
OS: Windows 10
Xournal++ Version: 1.0.18
Desktop is extended to tablet

Temporary fix:

Rather than set the scaling globally using Display Settings you can use the Compatibility Settings in the Properties for the Xournal++ binary under `C:\Program Files\Xournal++\bin\xournalpp.exe`

Right-click xournalpp.exe > Properties > Compatibility > Change high DPI settings > High DPI Scaling Override
Enable Override high DPI scaling behavior.
Set "Scaling performed by" drop-down to Application

**Comment by Wolfgang001** [comment] 2020-09-01 02:36
Thanks zerovectorspace, your fix works for me.

**Comment by jmartin1454** [comment] 2020-09-11 16:02
Thank you!  The temporary fix worked for me, too.

**Comment by fchierchie** [comment] 2020-09-23 17:27
> OS: Windows 10
> Xournal++ Version: 1.0.18
> Desktop is extended to tablet
> 
> Temporary fix:
> 
> Rather than set the scaling globally using Display Settings you can use the Compatibility Settings in the Properties for the Xournal++ binary under `C:\Program Files\Xournal++\bin\xournalpp.exe`
> 
> Right-click xournalpp.exe > Properties > Compatibility > Change high DPI settings > High DPI Scaling Override
> Enable Override high DPI scaling behavior.
> Set "Scaling performed by" drop-down to Application

It worked for me. Thanks

**Comment by thomaswwp** [comment] 2021-01-10 16:44
Thanks for this. Fix worked for me.

Four monitor setup
Windows 10
Xournal++ 1.0.20

**Comment by realtofuine** [comment] 2021-01-20 17:37
> OS: Windows 10
> Xournal++ Version: 1.0.18
> Desktop is extended to tablet
> 
> Temporary fix:
> 
> Rather than set the scaling globally using Display Settings you can use the Compatibility Settings in the Properties for the Xournal++ binary under `C:\Program Files\Xournal++\bin\xournalpp.exe`
> 
> Right-click xournalpp.exe > Properties > Compatibility > Change high DPI settings > High DPI Scaling Override
> Enable Override high DPI scaling behavior.
> Set "Scaling performed by" drop-down to Application

It doesn't work for me :(

**Comment by CaptainKostaZ** [comment] 2021-02-01 19:58
Still to be fixed?

**Comment by realtofuine** [comment] 2021-02-01 20:38
Yeah

**Comment by CaptainKostaZ** [comment] 2021-02-02 03:34
Check this https://github.com/tauu/xournal

**Comment by LittleHuba** [comment] 2021-02-02 09:34
If nobody complains on the GTK issue tracker, this issue won't be prioritized by their devs. So head over to their issue tracker. Link is some comments above and mention that you have this issue and it needs fixing. Our dev team is dependent on GTK fixing this issue and we can not do anything within our codebase to fix this.

**Comment by Technius** [comment] 2021-02-10 22:26
Windows DPI scaling settings are kind of annoying. We should add the "override dpi scaling" tip to the installation instructions; it's a common problem when trying to play games on Windows, too.

**Comment by LawrenceRao007** [comment] 2021-02-22 18:43
I'm still having trouble with this on a 4K monitor.  My main monitor is 1920x1080, I have a Huion 13 which is also 1920x1080 and a 4K wall monitor 3840x2160.  If I use 200% scaling for the 4K but use the Huion for the app then the X-coordinate of the stylus is incorrect - the x-values seem to be 50% of what they should be.  If I try the workaround then I get the X and Y coordinates corrupted in a different way - the X seems to be halved and then translated to the right and the Y coordinate is also halved but maybe not translated.  It works perfectly well with the mouse in Xournal and other apps are fine altogether.  If I change to HD throughout and 100% scaling then all is well although my wall monitor doesn't look very nice :(

Any help appreciated.

**Comment by LittleHuba** [comment] 2021-02-22 20:40
This is indeed the same issue. As you already mentioned, setting the resolution and scale the same on both screens fixes the issue. This is as far as we know the only way to fix this. We can't do anything about this on our side. Please mention this over at the GTK issue tracker for them to fix this issue.

**Comment by LawrenceRao007** [comment] 2021-02-22 21:08
I'm not sure I know what GTK is.  However, for the most part, I use my stylus in 'dumb' (mouse only) mode.  I'm not interested in 4096 pressure levels etc - I teach maths not art.  For every other piece of software that I use my stylus with, it is simply a mouse.  The stylus moves the cursor on the monitor that I select in the Huion software work area, the tip of the stylus produces mouse up / down functionality and the Huion software allows me to map keystrokes for the 2 mouse buttons and the pad.  Would it be possible to set Xournal into a mouse only mode as well?

**Comment by LittleHuba** [comment] 2021-02-23 10:52
> I'm not sure I know what GTK is.

GTK is a library that abstracts different operating systems like Windows/Linux so we can run Xournal++ on both without having to go into the details of every operating system. For this it also handles device input and abstracts it in a way that it looks the same on every operating system. You can find the issue tracker here: https://gitlab.gnome.org/GNOME/gtk/-/issues/734

> Would it be possible to set Xournal into a mouse only mode as well?

Not in the way as you would require. The data Windows provides for your inputs are handled incorrectly by GTK. That wouldn't change even if we treated the device differently. You would still experience the bug just the same. So please head over to the issue tracker and ask for them to fix this issue.

**Comment by LawrenceRao007** [comment] 2021-02-23 11:55
OK, thank you.  The only software I write is for browsers and they handle everything like that.  I will try to raise the problem on the GTK repository.

**Comment by nicegamer7** [comment] 2021-03-11 14:18
This might solve the issue, https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3275.

**Comment by Nestak2** [comment] 2021-03-17 18:34
@Febbe 
> Another thing could be, that the underlying Input System stretches the drawing Tablet over all screens, then it would be a dependancy issue.
- This is the problem that I am having, I have also described it in this post [here](https://askubuntu.com/questions/1324194/dual-screen-set-up-shows-stylus-position-off-set). Do you have any advice how to solve it? Note that my problem appears only on Ubuntu 20.04, but not on Windows.

**Comment by Nestak2** [comment] 2021-03-19 12:25
I resolved my issue with 1 click! All I needed to do is on log-in in Ubuntu 20.04.1 to select that I want to use Wayland, not xorg. No change of settings files needed, no figuring out what the main monitor is, just a 1-click-solution. Credit goes to [this answer](https://askubuntu.com/a/1308720/771488), look it up for more info

**Comment by LittleHuba** [comment] 2021-03-19 16:51
> Another thing could be, that the underlying Input System stretches the drawing Tablet over all screens, then it would be a dependancy issue.

For future reference, this can be fixed in X-Org sessions by mapping the input device to a specific screen.
```
xinput --map-to-output <device> <screen>
```

You can get the name of the screen using `xrandr` and the name of the device by `xinput --list`.

**Comment by H0radricCube** [comment] 2022-05-09 09:30
> OS: Windows 10 Xournal++ Version: 1.0.18 Desktop is extended to tablet
> 
> Temporary fix:
> 
> Rather than set the scaling globally using Display Settings you can use the Compatibility Settings in the Properties for the Xournal++ binary under `C:\Program Files\Xournal++\bin\xournalpp.exe`
> 
> Right-click xournalpp.exe > Properties > Compatibility > Change high DPI settings > High DPI Scaling Override Enable Override high DPI scaling behavior. Set "Scaling performed by" drop-down to Application

This works for me! Thanks~

**Comment by bhennion** [comment] 2023-02-01 08:28
Closing as this is a GTK issue (if it still is an issue at all)

**Closed by bhennion** 2023-02-01 08:28 UTC
Labels: bug, os::windows, Input, Dependency Issue
