### ISSUE TITLE
Can we have a way to precisely choose what pen thichness we can use?

### ISSUE THREAD

**Issue by IzzaldinSamir** [xournalpp/xournalpp#3821] opened 2022-02-16 01:54 UTC
**Is your feature request related to a problem? Please describe.**
Can we have a way to precisely choose what pen thickness we can use?

**Describe the solution you'd like**
Provide a simple way to do that.

**Describe alternatives you've considered**
0^1

**Additional context**
Having more advanced pen options would be nice.

Thanks for such a great program!

**Comment by mercifulboss** [comment] 2022-02-16 17:01
They already exist. You just need to make a custom toolbar

**Comment by IzzaldinSamir** [comment] 2022-02-16 17:51
I see but what about like specifying exactly the pen size like using a value and other advanced options?

**Comment by Technius** [comment] 2022-02-19 08:31
Duplicate of #1361. There is a stroke thickness slider in the works (#3288) but there hasn't been much progress on it lately.

**Closed by Technius** 2022-02-19 08:31 UTC
Labels: enhancement

**Comment by prbuen** [comment] 2022-03-10 07:06
Having a small set of thicknesses is great (and 5 different sizes is plenty enough), but it would great to be able to customize these 5 sizes in the settings. (NB: It's possible to do this in xournal, by editing the list of pen_thicknesses in ~/.xournal/config).

**Comment by NNoah18** [comment] 2023-02-15 19:49
> They already exist. You just need to make a custom toolbar

How do you do that? I only see 5 presets, are you saying I can make a new preset?

**Comment by rdrg109** [comment] 2023-03-20 00:47
@prbuen Are you completely sure about that? To me, it looks like that's not true. I'm using

```
$ xournalpp --version
```

```
Xournal++ 1.1.3
└──libgtk: 3.24.36
```

I used `strace` to see the files that are opened when using `xournalpp`, and `~/.xournal/config` is not listed. See the list of unique files that are opened by xournal in my system.

```
$ strace --trace=openat -o main.log xournalpp
$ cat main.log | grep '/home/' | sort -u
```

```
openat(AT_FDCWD, "/home/myusername/.Xauthority", O_RDONLY) = 8
openat(AT_FDCWD, "/home/myusername/.Xauthority", O_RDONLY) = 9
openat(AT_FDCWD, "/home/myusername/.Xdefaults", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.Xdefaults-r1", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.cache/event-sound-cache.tdb.2d4d14b6144b40d3b75ad889bcbcc577.x86_64-pc-linux-gnu", O_RDWR|O_CREAT|O_NOCTTY|O_CLOEXEC, 0644) = 17
openat(AT_FDCWD, "/home/myusername/.cache/xournalpp/errorlogs", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 12
openat(AT_FDCWD, "/home/myusername/.config/gtk-3.0/gtk.css", O_RDONLY) = 8
openat(AT_FDCWD, "/home/myusername/.config/gtk-3.0/settings.ini", O_RDONLY) = 8
openat(AT_FDCWD, "/home/myusername/.config/ibus/bus", O_RDONLY|O_DIRECTORY) = 11
openat(AT_FDCWD, "/home/myusername/.config/ibus/bus/2d4d14b6144b40d3b75ad889bcbcc577-unix-0", O_RDONLY) = 11
openat(AT_FDCWD, "/home/myusername/.config/ibus/bus/2d4d14b6144b40d3b75ad889bcbcc577-unix-0", O_RDONLY) = 12
openat(AT_FDCWD, "/home/myusername/.config/pulse/client.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.config/xournalpp/colornames.ini", O_RDONLY) = 12
openat(AT_FDCWD, "/home/myusername/.config/xournalpp/colornames.ini", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 18
openat(AT_FDCWD, "/home/myusername/.config/xournalpp/settings.xml", O_RDONLY) = 11
openat(AT_FDCWD, "/home/myusername/.config/xournalpp/settings.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 18
openat(AT_FDCWD, "/home/myusername/.config/xournalpp/toolbar.ini", O_RDONLY) = 12
openat(AT_FDCWD, "/home/myusername/.icons/Adwaita/cursors/default", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.icons/Adwaita/cursors/text", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.icons/Adwaita/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.icons/default/cursors/default", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.icons/default/cursors/text", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.icons/default/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share", O_RDONLY) = 18
openat(AT_FDCWD, "/home/myusername/.local/share/fonts/NotoSansMono-Regular.otf", O_RDONLY) = 12
openat(AT_FDCWD, "/home/myusername/.local/share/icons", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 12
openat(AT_FDCWD, "/home/myusername/.local/share/icons/Adwaita/cursors/default", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share/icons/Adwaita/cursors/text", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share/icons/Adwaita/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share/icons/default/cursors/default", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share/icons/default/cursors/text", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share/icons/default/index.theme", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share/icons/icon-theme.cache", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/myusername/.local/share/mime//mime.cache", O_RDONLY) = 12
openat(AT_FDCWD, "/home/myusername/.local/share/recently-used.xbel", O_RDONLY) = 11
openat(AT_FDCWD, "/home/myusername/.local/share/recently-used.xbel.Y2BU11", O_RDWR|O_CREAT|O_EXCL, 0666) = 18
openat(AT_FDCWD, "/home/myusername/.pulse/client.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

I also grepped the repository's history for the configuration `pen_thicknesses` and no result is shown.


```
$ git log --pickaxe-regex -p -S 'pen_thicknesses'  | wc -l
```
 
```
0
```

**Comment by prbgit** [comment] 2023-03-20 04:38
@rdrg109 In Xournal, not in Xournal++ :)
