### ISSUE TITLE
Presenter Mode

### ISSUE THREAD

**Issue by wallento** [xournalpp/xournalpp#1301] opened 2019-06-27 09:23 UTC
**Is your feature request related to a problem? Please describe.**
I know it may seem entirely unrelated, but I would find it extremely useful: A full fledged presenter mode. I am using PowerPoint in teaching and as many others I use hand-drawing annotations as a didactic feature to develop problems or to hand-annotate on questions. The problem is that I want to use beamer and FOSS tools instead.

**Describe the solution you'd like**
A full presenter mode (as in PowerPoint) shows me the time, notes and the next slide. Plus I can draw on it and different colors and pens. After presenting, the annotations remain in the document and I can distribute it to my students. 

**Describe alternatives you've considered**
I have looked into a couple of beamer presenter programs, and found pdfpc the most mature. Unfortunately, there seems zero interest in the feature and the suggestion was closed immediately: https://github.com/pdfpc/pdfpc/issues/442

In my humble technical understanding it should be viable to include the functionality as they are at least based on similar technologies. Having pdfpc store annotations in a (new file format probably) xournal++ format would be very useful. If there is no interest in this feature in pdfpc, it may be a nice addition to xournal++ to have its own presenter mode, potentially based on the pdfpc codebase.

**Additional context**
I am happy to help with it, but have no direct experience in GTK..

**Comment by LittleHuba** [comment] 2019-06-27 19:07
Duplicate of #1168 
There are additional wishes though...

**Closed by LittleHuba** 2019-06-27 19:07 UTC
Labels: enhancement

**Comment by wallento** [comment] 2019-06-27 20:08
Oh, yes, very sorry, missed this one was going into more than a second screen. Thanks!
