### ISSUE TITLE
Assert failing when using vertical space tool

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#3967] opened 2022-04-19 06:47 UTC
**Affects versions :** latest master, on Archlinux with KDE X11:
```
$ ./install/bin/xournalpp --version
xournalpp 1.1.1+dev
└──libgtk: 3.24.33
```

**Describe the bug**
Failing assert when using (in a weird way, see below) the vertical space tool. This is most likely the symptome of a deeper evil.

```
ERROR:/home/benjamin/xournalpp-fork/src/core/gui/PageView.cpp:320:bool XojPageView::onButtonPressEvent(const PositionInputData&): 'this->verticalSpace' should be nullptr
Bail out! ERROR:/home/benjamin/xournalpp-fork/src/core/gui/PageView.cpp:320:bool XojPageView::onButtonPressEvent(const PositionInputData&): 'this->verticalSpace' should be nullptr

** (xournalpp:78511): WARNING **: 08:30:49.406: [Crash Handler] Crashed with signal 6

** (xournalpp:78511): WARNING **: 08:30:49.407: [Crash Handler] Wrote crash log to: /home/benjamin/.cache/xournalpp/errorlogs/errorlog.20220419-083049.log
```

**To Reproduce**
1. Open a new document (optionally draw a couple of strokes on it)
2. Zoom in
3. With the vertical space tool selected, do
    1. Press the mouse button anywhere on the sheet. NEVER RELEASE THE BUTTON
    2. Press `CTRL`. NEVER RELEASE THE BUTTON
    3. Move up and down a little.
    4. Zoom out (with `CTRL` already down, the scrolling wheel or the `-` key should do it)
    5. Move up and down a little.
    6. Observe the crash.

It works every time here, provided I zoomed enough in at the beginning.
It may be relevant: I'm using a touchpad for those tests.

**Comment by rolandlo** [comment] 2022-04-19 06:52
I can confirm the crash (and used my mouse for it, not a touchpad)

**Comment by rolandlo** [comment] 2022-04-19 09:37
Looking at the issue a little big, I came to the conclusion that there must be something wrong in the logic of these lines:

https://github.com/xournalpp/xournalpp/blob/6f151c7704a53efde1714d9a0d98eca7d597c783/src/core/gui/inputdevices/PenInputHandler.cpp#L264-L276

Via
https://github.com/xournalpp/xournalpp/blob/6f151c7704a53efde1714d9a0d98eca7d597c783/src/core/gui/inputdevices/PenInputHandler.cpp#L137-L143
they issue a `ButtonPressEvent` to the page, even though it's only a motion event and not originating from outside the page.
Since the vertical space tool is still active, that makes the assertion `g_assert_null(this->verticalSpace)` fail.

**Comment by rolandlo** [comment] 2022-04-19 18:41
Looking more closely, I discovered that the problem comes right after the page layout computation is updated. 
At the moment when it is checked (via `getPageAtCurrentPosition`) e.g. in
https://github.com/xournalpp/xournalpp/blob/6f151c7704a53efde1714d9a0d98eca7d597c783/src/core/gui/inputdevices/PenInputHandler.cpp#L25-L33, the event x- and y-coordinates may not be valid any more with respect to the recalculated layout.
In the following sequence:
1. motion event is received by the `eventCallback` of the `InputContext`
2. the layout is recalculated (due to zooming in)
3. the page corresponding to the event from above is determined with respect to the new layout. This may give the wrong result.

I tried to fix the problem by determining the page corresponding to an event right when the event is received. That didn't fix the problem though. In any case, the problem is that the page corresponding to an event is not always correctly determined shortly after the layout has been recalculated due to zooming.

**Comment by Technius** [comment] 2022-04-20 05:54
I took a look at the code in PageView, and it seems like only the vertical select case assumes that a button press cannot occur while the mouse is already being hold down. Is this a reasonable assumption to make, or should we change the behavior so that the vertical selection is restarted?

**Comment by rolandlo** [comment] 2022-04-20 19:22
> I took a look at the code in PageView, and it seems like only the vertical select case assumes that a button press cannot occur while the mouse is already being hold down. Is this a reasonable assumption to make, or should we change the behavior so that the vertical selection is restarted?

Currently that assumption is unreasonable, since a button press event is issued from the code under some circumstances (when the last event could not be assigned to a page, because the layout update messes things up). So I think we should change the behavior so that the vertical selection is restarted.

**Comment by bhennion** [comment] 2022-04-21 17:26
> Currently that assumption is unreasonable, since a button press event is issued from the code under some circumstances (when the last event could not be assigned to a page, because the layout update messes things up). So I think we should change the behavior so that the vertical selection is restarted.

I don't think we should change the Vertical selection tool, but rather fix the source of the falsly issued event. 

Anyway, I don't how reasonable the current assumption is (namely that no button press event can be issued while the button is (supposedly) already down). There may be faulty device drivers out there, or there may be a button press from a different device.
This kind of situations should be handled upstream, in the input system, and not in the PageView (again, not a view...) class.

**Comment by Technius** [comment] 2022-04-27 04:51
Let's just reset the vertical selection for to avoid the crashes for now. The proper fix is something that needs to be implemented in the longer term.

**Comment by Technius** [comment] 2022-04-27 04:59
Actually, that assertion shouldn't have been there regardless. The case did not check the actual mouse button used, so you could trigger the assert failure by 1) initiating a vertical select with left mouse button and 2) right clicking while the vertical select is active.

**Closed** 2022-04-29 06:30 UTC
Labels: bug, confirmed, regression
