### ISSUE TITLE
Select a text in an imported pdf document 

### ISSUE THREAD

**Issue by FO2020** [xournalpp/xournalpp#3691] opened 2022-01-01 15:25 UTC
Hello,
Thanks for nice program . I am using this program on surface pro 8 . One thing is missing or maybe I don't know about is selecting a text in an imported pdf document. Is this feature available or missing.?

**Comment by rolandlo** [comment] 2022-01-01 15:28
This feature is implemented in Pull Request #3326. Hopefully it will soon make it into the official version.

**Comment by FO2020** [comment] 2022-01-07 18:20
Thanks. It will be very helpful to have that. Is there any time frame for it.?

**Comment by rolandlo** [comment] 2022-01-07 18:23
> Thanks. It will be very helpful to have that. Is there any time frame for it.?

No, there is no time frame. Depends on the time availability of the contributor and the reviewer(s). But I can say the code is mostly ready and it's more about small things to improve. It's a big pull request though and that always takes a while.

**Comment by FO2020** [comment] 2022-01-07 19:58
I agree it will takes time as it is open source app and cross platform. I have been user of goodnotes on ipad pro and needed an app alternativ to it and this app is the one which have many similar features . But there are to things that are missing which are  
1-the ability to make folder and subfolders
2-Take screenshot with lasso tool . I used this alt in math teaching.

**Comment by rolandlo** [comment] 2022-01-07 20:09
About 1: you're probably talking about #799
About 2: There is already a plugin (Quick Screenshot) for that. It currently only works on Linux though.

**Comment by FO2020** [comment] 2022-01-07 21:05
1-yes, something like that.
2-I am using windows now on a surface pro . I will check if this is available. One regarding picture. It is not possible to past pictures inside the document . This is maybe important for taking a screenshot either inside the app or outside via snipping tool in windows. Now one have to save the picture first then import it to the app. Cumbersome litt bit.

**Comment by rolandlo** [comment] 2022-01-07 21:10
> It is not possible to past pictures inside the document . This is maybe important for taking a screenshot either inside the app or outside via snipping tool in windows. Now one have to save the picture first then import it to the app. Cumbersome litt bit.

If pasting from the clipboard does not work, you should open up an issue on the issue tracker.

**Comment by FO2020** [comment] 2022-01-07 21:54
I just tasted it again and it worked, but I have to use the ctr +c to paste
it . The quick screenshot worked as well, but one still has to use a
keyboard shortcut to do it. What would have been convenient for me if I
could paste it whenever want by using the stylus to touch anywhere and get
the past option .
 For  quick screenshot, I would like to have something similar. I use lasso
tool to select a region then getting som options like copy , save (as png
or jpeg) and the touch anywhere inside the document to get the paste
option. Goodnotes and notability for iOS  have this feature.

fre. 7. jan. 2022 kl. 22:10 skrev Roland Lötscher ***@***.***

**Comment by FO2020** [comment] 2022-01-07 21:56
One last thing regarding pictures is the ability to crop them instantly inside the app .

**Comment by Technius** [comment] 2022-01-29 10:22
Closing as duplicate of #1745.

**Closed by Technius** 2022-01-29 10:22 UTC
Labels: enhancement
