### ISSUE TITLE
errorlog

### ISSUE THREAD

**Issue by creamJelly** [xournalpp/xournalpp#5075] opened 2023-08-21 08:31 UTC
[errorlog.20230818-163304.log](https://github.com/xournalpp/xournalpp/files/12393989/errorlog.20230818-163304.log)

**Comment by bhennion** [comment] 2023-08-21 08:37
Thanks for reporting. This looks like a duplicate of #4997 (which has a fix in the pipeline)
Does the app run normally passed the first run?
I'm going to close this issue as a duplicate. Reopen if the answer to the above question is "no".

**Closed by bhennion** 2023-08-21 08:37 UTC
