### ISSUE TITLE
'Very thick' on toolbar

### ISSUE THREAD

**Issue by TheBB** [xournalpp/xournalpp#1415] opened 2019-08-16 11:38 UTC
It seems that there are five pen thickness options (very thin, thin, medium, thick and very thick) but only the middle three of these have toolbar items. I usually swap between medium and very thick, and it's tedious to go into the menu every time I need the latter (especially since I like fullscreen).

Ref: https://github.com/xournalpp/xournalpp/blob/90f583a851265c52abc69aa7fcc81fe632ca23d1/src/gui/toolbarMenubar/ToolMenuHandler.cpp#L524-L526

**Comment by Febbe** [comment] 2019-08-16 12:40
I had already had the idea to switch to a drop down menu with the ability to have a custom thickness. Just adding the missing options to the toolbar would be to much boilerplate in my opinion. It is already very overloaded

**Comment by TheBB** [comment] 2019-08-16 13:00
Well I didn't have in mind to have it there by default. I was just surprised that it wasn't available as a config option.

**Comment by JJones780** [comment] 2019-08-17 09:28
I agree that it would be a bit much to add to the default toolbars but I don't see a problem with aking it available for custom toolbars.  It's only two lines of code and very basic icons ( which I'll get around to next day ).  There is some (minor? I haven't looked at the code yet )  complication in that the highlighter and eraser only have 3 sizes.. and share the same toolbar tools.

If @Febbe wants to add a drop down menu toolbar item as well that would be great ... but I'm not sure it would be worth the effort. We'd probably want to keep both options ( i.e. not switch to drop-down only ) as touchscreen users don't appreciate drop down menus as much as mouse users do.

**Comment by Technius** [comment] 2019-08-17 23:41
Duplicate of #1361. But I'll leave this open in case we want to implement just the two new sizes.

**Closed** 2019-08-24 08:13 UTC
Labels: enhancement
