### ISSUE TITLE
Mac Stable version instantly crashes, other versions have problem with stroke latency -> xournal is unusable on Mac 😞 

### ISSUE THREAD

**Issue by lupja** [xournalpp/xournalpp#3122] opened 2021-05-19 10:52 UTC
**Affects versions :**
 - OS: Mac, Big Sur (version 11.3.1 [20E241])
 - Which version of libgtk do you use
     - 3.24.10
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - 1.0.19 is the one with stroke delay on the video
     - 1.0.20 (Stable) crashing
     - 1.1.0+dev has the worst stroke delay, on the second video
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]
     - official releases, all from https://xournalpp.github.io/installation/macos/
 - Using One by Wacom

**Describe the bug**
I'm having multiple problems with 3 versions of Xournal++.

- **1.0.19** has a stroke delay which makes it impossible to write any notes at all.
  - for this version only: a small stroke is being drawn even after I've raised the pan from the pad, it can be seen on the first video at 00:44
- **1.0.20** (Stable) version crashes immediately after launching it
- **1.1.0+** (Nightly) has a massive stroke delay, worst than 1.0.19. It's absolutely impossible to write any notes.

**To Reproduce**
VIDEO

**Expected behavior**
Light and responsive stroke.
Same as I demonstrated with the SketchBook app.

**Screenshots of Problem**
Videos: First 1.0.19, SketchBook and Stable version; second 1.1.0+ version

It was too big for GitHub -> OneDrive
https://1drv.ms/u/s!Av-nG9jzmkU5g8QCcniof3vIMBwqWA?e=dDue6g

https://user-images.githubusercontent.com/84447275/118800578-5aa56900-b8a0-11eb-9465-b6369f2d6c10.mov

**Comment by rolandlo** [comment] 2021-05-19 12:38
Duplicate of #2302, where the issue was solved by upgrading Gtk. There is even a test build.

**Closed by rolandlo** 2021-05-19 12:38 UTC
Labels: bug

**Comment by lupja** [comment] 2021-05-19 15:52
Okay, thank you very much. However, #2302 isn't solving the "Stable crashing" issue, or?

Also, @rolandl, would you mind creating another link to the functional version? The last one has expired already. Thanks in advance!

**Comment by rolandlo** [comment] 2021-05-19 16:09
Well, #2302 won't make version 1.0.20 functional on MacOS BigSur, but the next stable release (version 1.1.0) will soon be released and we have no plans to continue the 1.0.x series. I will create another link to the functional version in #2302.
