### ISSUE TITLE
Appimage abnormal exit when add text

### ISSUE THREAD

**Issue by ghost** [xournalpp/xournalpp#3581] opened 2021-11-17 12:22 UTC
**Affects versions :**
 - OS: LinuxMint 20.01 xfce4
 - Desktop environment: xfce4
 - Version of Xournal++: 1.1.0
 - Installation method: Appimage

**Describe the bug**
The application exit when I try to add text.

**Additional context**
log:
```
stxw@stxw-c:~/download/2021_11_17$ ./xournalpp-1.1.0-x86_64.AppImage 
** Message: 20:16:17.027: TEXTDOMAINDIR = /tmp/.mount_xournamRlV0C/usr/share/locale:, PACKAGE_LOCALE_DIR = /usr/share/locale, chosen directory = /tmp/.mount_xournamRlV0C/usr/share/locale
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = 没有那个文件或目录
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = 没有那个文件或目录
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Cannot connect to server socket err = 没有那个文件或目录
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
** Message: 20:16:17.208: Plugin "MigrateFontSizes" UI initialized
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
** Message: 20:16:22.448: lastOpenPath set
** Message: 20:16:22.449: 文件： /home/stxw/documents/linux-cmd.zh.pdf

(AppRun.wrapped:65402): Gdk-WARNING **: 20:16:34.088: Native Windows wider or taller than 32767 pixels are not supported

(AppRun.wrapped:65402): Gdk-CRITICAL **: 20:16:34.092: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

(AppRun.wrapped:65402): Gdk-CRITICAL **: 20:16:34.092: gdk_device_get_name: assertion 'GDK_IS_DEVICE (device)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

** (AppRun.wrapped:65402): WARNING **: 20:16:34.100: [Crash Handler] Crashed with signal 6

** (AppRun.wrapped:65402): WARNING **: 20:16:34.100: [Crash Handler] Wrote crash log to: /home/stxw/.cache/xournalpp/errorlogs/errorlog.20211117-201634.log

** (AppRun.wrapped:65402): WARNING **: 20:16:34.228: 尝试紧急保存当前打开的文档…

** (AppRun.wrapped:65402): WARNING **: 20:16:34.229: 文档已经保存为"/home/stxw/.config/xournalpp/emergencysave.xopp"
```

log file:
```
Date: Wed Nov 17 20:16:34 2021
Error: signal 6
[bt]: (0) /tmp/.mount_xournamRlV0C/AppRun.wrapped(+0x1deed0) [0x561306d92ed0]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7efc91d1f210]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7efc91d1f18b]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7efc91cfe859]
[bt]: (4) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911) [0x7efc91f84911]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c) [0x7efc91f9038c]
[bt]: (6) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7) [0x7efc91f903f7]
[bt]: (7) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9) [0x7efc91f906a9]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt19__throw_logic_errorPKc+0x41) [0x7efc91f8721e]
[bt]: (9) /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN11InputEvents19translateDeviceTypeEP10_GdkDeviceP8Settings+0xdc) [0x561306d4547c]
[bt]: (10) /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN11InputEvents14translateEventEP9_GdkEventP8Settings+0x71) [0x561306d45531]
[bt]: (11) /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN12InputContext6handleEP9_GdkEvent+0x4e) [0x561306d4495e]
[bt]: (12) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgtk-3.so.0(+0x2318f7) [0x7efc948818f7]
[bt]: (13) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgobject-2.0.so.0(+0x102f6) [0x7efc933ac2f6]
[bt]: (14) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit_valist+0x72d) [0x7efc933c73ad]
[bt]: (15) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7efc933c810f]
[bt]: (16) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgtk-3.so.0(+0x379445) [0x7efc949c9445]
[bt]: (17) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgtk-3.so.0(gtk_main_do_event+0x77e) [0x7efc948808ce]
[bt]: (18) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgdk-3.so.0(+0x37765) [0x7efc94387765]
[bt]: (19) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgdk-3.so.0(+0x67f92) [0x7efc943b7f92]
[bt]: (20) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7efc94fd817d]
[bt]: (21) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7efc94fd8400]
[bt]: (22) /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7efc94fd84a3]
[bt]: (23) /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgio-2.0.so.0(g_application_run+0x1fd) [0x7efc93696f3d]
[bt]: (24) /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN11XournalMain3runEiPPc+0x4ab) [0x561306c9088b]
[bt]: (25) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7efc91d000b3]
[bt]: (26) /tmp/.mount_xournamRlV0C/AppRun.wrapped(_start+0x2a) [0x561306c6f23a]


Try to get a better stracktrace...
[bt] #1 /tmp/.mount_xournamRlV0C/AppRun.wrapped(+0x1df3a1) [0x561306d933a1]
??:0
[bt] #2 /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7efc91d1f210]
??:0
[bt] #3 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7efc91d1f18b]
??:0
[bt] #4 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7efc91cfe859]
??:0
[bt] #5 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911) [0x7efc91f84911]
??:0
[bt] #6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c) [0x7efc91f9038c]
??:0
[bt] #7 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7) [0x7efc91f903f7]
??:0
[bt] #8 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9) [0x7efc91f906a9]
??:0
[bt] #9 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt19__throw_logic_errorPKc+0x41) [0x7efc91f8721e]
??:0
[bt] #10 /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN11InputEvents19translateDeviceTypeEP10_GdkDeviceP8Settings+0xdc) [0x561306d4547c]
??:0
[bt] #11 /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN11InputEvents14translateEventEP9_GdkEventP8Settings+0x71) [0x561306d45531]
??:0
[bt] #12 /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN12InputContext6handleEP9_GdkEvent+0x4e) [0x561306d4495e]
??:0
[bt] #13 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgtk-3.so.0(+0x2318f7) [0x7efc948818f7]
??:0
[bt] #14 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgobject-2.0.so.0(+0x102f6) [0x7efc933ac2f6]
??:0
[bt] #15 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit_valist+0x72d) [0x7efc933c73ad]
??:0
[bt] #16 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgobject-2.0.so.0(g_signal_emit+0x8f) [0x7efc933c810f]
??:0
[bt] #17 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgtk-3.so.0(+0x379445) [0x7efc949c9445]
??:0
[bt] #18 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgtk-3.so.0(gtk_main_do_event+0x77e) [0x7efc948808ce]
??:0
[bt] #19 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgdk-3.so.0(+0x37765) [0x7efc94387765]
??:0
[bt] #20 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgdk-3.so.0(+0x67f92) [0x7efc943b7f92]
??:0
[bt] #21 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7efc94fd817d]
??:0
[bt] #22 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7efc94fd8400]
??:0
[bt] #23 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7efc94fd84a3]
??:0
[bt] #24 /tmp/.mount_xournamRlV0C/usr/bin/../lib/libgio-2.0.so.0(g_application_run+0x1fd) [0x7efc93696f3d]
??:0
[bt] #25 /tmp/.mount_xournamRlV0C/AppRun.wrapped(_ZN11XournalMain3runEiPPc+0x4ab) [0x561306c9088b]
??:0
[bt] #26 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7efc91d000b3]
??:0
[bt] #27 /tmp/.mount_xournamRlV0C/AppRun.wrapped(_start+0x2a) [0x561306c6f23a]
??:0
```

**Comment by bhennion** [comment] 2021-11-17 12:29
This is probably a duplicate of #3500. It has been fixed for the next release.

**Comment by bhennion** [comment] 2022-08-07 08:59
Duplicate of #3500

**Closed by bhennion** 2022-08-07 08:59 UTC
Labels: bug
