### ISSUE TITLE
Latex is extremely slow on Ubuntu

### ISSUE THREAD

**Issue by frohro** [xournalpp/xournalpp#730] opened 2019-01-11 15:11 UTC

**Comment by frohro** [comment] 2019-01-11 15:15
I'm using Ubuntu 18.10, and inserting a Latex equation is extremely slow to edit.  Just to backup over the x^2 takes what seems like a very long time (maybe 30 seconds for three letters).  Perhaps there could be a way you could enter the Latex to render, and then click a render button to see what it looks like.  That would be much better for me than this very slow automatic rendering.  :-)

**Comment by andreasb242** [comment] 2019-01-11 15:22
On a Core 2 Duo L9400 (very slow and old) on Ubuntu 18.04 it's rendering live.
I'm currently downloading Ubuntu 18.10, and will set up a Testmachine, and check if this also happens with Ubuntu 18.10.

**Comment by andreasb242** [comment] 2019-01-11 15:36
I'll set up system, and if it's reproducible it's probably easy to fix.
If it's not, then it has something to with your system. In this case you have to do some testing, e.g. you can execute

>time mathtex-xournalpp.cgi -m 0 "\png\usepackage{color}\color{black}\dpi{{600}}\normalsize x^2" -o test.png

On my dev PC this outputs:
>real	0m0.118s
>user	0m0.068s
>sys	0m0.004s

So it took 118ms to generate the image, which is much, much faster than the 30s you told.
But it also can be an issue with loading the image, or something else, which is not covered by this test.

If you can do this now, we know where the problem is located.

**Comment by frohro** [comment] 2019-01-11 16:18
frohro@frohro-260:~/Projects/xournalpp/build$ time mathtex-xournalpp.cgi -m 0 "\png\usepackage{color}\color{black}\dpi{{600}}\normalsize x^2" -o test.png

real	0m0.119s
user	0m0.079s
sys	0m0.018s

So that is working.

**Comment by andreasb242** [comment] 2019-01-11 16:49
I missed your second answer. Probably I was writing mine at this time.

So if it's working I close the issue.
@frohro You can reopen the Tickets when it happens again.

**Closed by andreasb242** 2019-01-11 16:49 UTC
Labels: bug

**Comment by Rmano** [comment] 2019-01-11 18:21
Sometime there are *huge* delays when fonts are generated for the first time in X... could be this?

**Comment by frohro** [comment] 2019-01-11 18:23
It might be.  I'll reply here if I ever experience it again on this laptop.

**Comment by luco5826** [comment] 2019-01-12 21:41
Hi @frohro ! I personally followed the development of the real time rendering latex feature on xournalpp and any suggestion is very well accepted! 
I was thinking about an alternative solution instead of how it is now, maybe we could wait something like 1 sec after the user stops writing and THEN render the latex, but it is hard to intercept such "event". 
Right now we get the "text changed" event and it triggers a render every character gets modified!
