### ISSUE TITLE
View "single page"

### ISSUE THREAD

**Issue by leonardoxopp** [xournalpp/xournalpp#2117] opened 2020-07-13 17:01 UTC
Hello,

In View menu there are "Pair Pages", "Presentation Mode" and "Full Screen".

Although "Presentation Mode" seems to be single page view, zoom can not be adjusted.

It would be useful if a "Single Page" option was added (Xournal has it but Xournal++ does not) with zoom adjustable by user.

Kind regards,
Leonardo

**Comment by rolandlo** [comment] 2020-07-16 17:25
I think it would make sense to reimplement this feature in the viewport refactoring process #1795. It seems useful for some purposes. Quoting from the Xournal User's manual:

> The one-page mode is more appropriate if your journal is a scrapbook in which the pages have different characteristics (in particular, if you are annotating a series of pictures of different sizes).

**Comment by onlycparra** [comment] 2020-08-09 16:40
Also, in single page view, when all your pages have the same size, and you navigate across them (next and previous), each page is displayed right on top of each other (same size and position), This is a useful tool to compare the similarity of contiguous pages. This is attractive when designing presentations, or want to sketch a basic overlay animation.

**Comment by bhennion** [comment] 2022-12-25 11:28
Duplicate of #1035

**Closed by bhennion** 2022-12-25 11:28 UTC
Labels: enhancement, priority::medium
