### ISSUE TITLE
after "Insert page after", sometimes screen jumps to first page

### ISSUE THREAD

**Issue by leonardoxopp** [xournalpp/xournalpp#2120] opened 2020-07-18 17:52 UTC
- OS: Linux - debian 10
- Desktop nvironment: xfce
- Which version of libgtk do you use: 3.24.5
- Version of Xournal++: 1.1.0+dev, git commit "a320e1c5"
- Installation method: build from source

**Describe the bug**
After inserting "New page after", the new page is created in the right place, ok!! However, sometimes the screen jumps to first page and I have to navigate to the correct page.

**To Reproduce**
WHEN it happens (I say "when" because sometimes this bug does not occurs)

1) Create a few pages
2) Go to some random page
3) Insert page after, the screen goes to page 1.

As I said, I can't reproduce this all the time. It is very random.

**Expected behavior**
Inserting new page should always display the new inserted page or, at least, stay at the same page.

Kind regards,
Leonardo

**Comment by rolandlo** [comment] 2020-07-19 20:18
duplicate of #1517

**Closed by rolandlo** 2020-07-19 20:18 UTC
Labels: bug
