### ISSUE TITLE
Custom toolbar buttons order not remembered correctly

### ISSUE THREAD

**Issue by nekohayo** [xournalpp/xournalpp#2501] opened 2020-12-08 03:23 UTC
**Affects versions :**
 - OS: Linux
 - GNOME 3.38 under Xorg/X11
 - libgtk 3.24.23
 - Version of Xournal++: 1.0.19
 - Installation method: official package from Fedora 33

I have no idea what causes this, but the custom ordering of my toolbar items is not remembered across restarts of the application. Video demonstration: [xournalpp-toolbar-items-ordering-not-remembered.zip](https://github.com/xournalpp/xournalpp/files/5656636/xournalpp-toolbar-items-ordering-not-remembered.zip)

This is what I had in the terminal while this was being recorded:

```
$ xournalpp 
Gtk-WARNING **: 22:13:00.142: Theme parsing error: <data>:1:22: Junk at end of value for font-family
Gdk-CRITICAL **: 22:13:21.096: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
Gdk-CRITICAL **: 22:13:21.097: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
Gdk-CRITICAL **: 22:13:21.097: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
Gdk-CRITICAL **: 22:13:21.097: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
Gtk-WARNING **: 22:13:22.651: A floating object was finalized. This means that someone called g_object_unref() on an object that had only a floating reference; the initial floating reference is not owned by anyone and must be removed with _object_ref_sink().
** Message: 22:13:23.150: Removed tool item IMAGE from Toolbar toolbarTop1 ID 403

Gdk-CRITICAL **: 22:13:23.150: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
** Message: 22:13:23.152: ToolbarData::insertItem(toolbarTop1, IMAGE, 20);
** Message: 22:13:23.153: Toolbar found: toolbarTop1
** Message: 22:13:23.153: return 433

GLib-GObject-CRITICAL **: 22:13:24.616: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** Message: 22:13:25.736: MemoryLeak: sum 0 objects.

$ xournalpp 
Gtk-WARNING **: 22:13:32.475: Theme parsing error: <data>:1:22: Junk at end of value for font-family
** Message: 22:13:34.974: MemoryLeak: sum 0 objects.
```

**Comment by rolandlo** [comment] 2020-12-08 05:09
Duplicate of #2154. Thanks for the additional details.

**Closed by rolandlo** 2020-12-08 05:09 UTC
Labels: bug
