### ISSUE TITLE
No writing sheet on raspian

### ISSUE THREAD

**Issue by vaghettiroberto** [xournalpp/xournalpp#2551] opened 2020-12-17 15:02 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - raspian
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11]
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]

**Describe the bug**

**To Reproduce**
1. Step 1
2. Step 2
3. etc.

**Expected behavior**

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other information or context about the problem here.

I have compiled xounalpp on raspian, it works but the paper is not present in the main window. Actually it can save e read the work that is effectively present in the program

**Comment by Febbe** [comment] 2020-12-18 21:22
Can you fill the bug report completely?
Also, the used compiler, processor infrastructure and gtk-version may be interesting. 

Can you try to compile with -Wall?

**Comment by emaninspace** [comment] 2020-12-19 00:34
pi@raspberrypi:~/Downloads/xournalpp/build/src $ ./xournalpp --version
Xournal++ 1.1.0+dev
└──libgtk: 3.24.5

![2020-12-18-163255_1920x1080_scrot](https://user-images.githubusercontent.com/5379467/102675559-bb444480-414e-11eb-8187-dc8c7b1f110b.png)

I was fiddling with the column and row settings and zooming in and out. Eventually I could see the page but only if it was not zoomed past the point where I could see the whole page.

**Comment by Febbe** [comment] 2020-12-19 14:32
Yes this is the same bug as #2514

**Comment by LittleHuba** [comment] 2021-01-07 11:23
Will close as this is a duplicate of #2514.

**Closed by LittleHuba** 2021-01-07 11:23 UTC
Labels: bug
