### ISSUE TITLE
Presentation on second display

### ISSUE THREAD

**Issue by GregDMeyer** [xournalpp/xournalpp#1168] opened 2019-05-21 19:06 UTC
This might be a little non-trivial to implement, but I thought I'd put it out there. It would be super cool if it was possible to show *only* the page area on a second display. What I am imagining is writing on my tablet with all the toolbars etc visible on the native display, and only what I am drawing being displayed on e.g. a projector.

Right now it is possible to give a presentation on a second display by just mirroring displays, but then all of the toolbars etc are visible, and in general this requires changing the resolution of the native display. Another option (on linux) is to use xrandr to export only a portion of the framebuffer, but this is pretty hacky ;)

I can poke around how to implement this if I have some spare time, but thought I would put the idea in public in case someone else sees an easy way to implement it.

**Comment by LittleHuba** [comment] 2019-05-21 19:17
This is actually not that hard as we are using the MVC pattern which supports such things. We only need to generate the window with this single view and change a few parts of the code to handle multiple such views.

Unfortunately we have a lot to do currently so this may still take some time.

**Comment by JJones780** [comment] 2019-05-22 02:55
Would the floatingToolbox (i.e. popup menu ) suffice for your use case? This is currently under development (#1161) but it allows one to use a full screen page only display. Here's a gifanim showing functionality without any sidewindows etc. You can put only the tools you need in the floating toolbar.
![allpage small](https://user-images.githubusercontent.com/2329541/58144018-0fe9ab80-7c0a-11e9-84c8-987c258504de.gif)

**Comment by GregDMeyer** [comment] 2019-05-22 20:30
@JJones780 Thanks! This could be a good temporary solution, though I'm not sure it does everything I am looking for---

There is another consideration aside from the toolbars. On my tablet, mirroring displays with e.g. a projector forces me to set my builtin display to a non-native resolution with an aspect ratio that doesn't match. Not only is this less visually nice, it also totally screws up the calibration of my tablet pen with position on the screen (so where I'm writing isn't where my pen is touching). Admittedly that's my problem ;) but I think it would be a nice, clean solution to export the page to a non-mirrored display. (I think some other note-taking software does this, but I don't have any concrete examples).

Thanks for your time and input!!

**Comment by JJones780** [comment] 2019-05-23 00:49
Are you using the same projector most of the time? You mentioned you are proficient with xrandr so it might be worthwhile to script an xrandr command to set it up ( see below )
I work with a 4k display at times and use xrandr to show the same but zoomed-out image on my 1080p laptop touch/stylus enabled screen.  It works exceptionally well and thankfully they have the same aspect ratios - but xrandr can even help there. **One problem I ran into is that I can't use my dedicated nvidia gpu and have to resort to the intel graphics which supports zooming out.**

I got a bit carried away... So I also added in extra info for others who might not be familiar with xrandr. Maybe I'll copy this somewhere more visible.

For reference - My laptop video outputs are eDP1 and an external HDMI1 ( _run xrandr to see what your names are_).

I imagine this might work for you with an external 1280x1024 projector?

`xrandr --output HDMI1 --mode 1280x1024  --scale 1.5x1.0547`
**options:** 
` --panning 1920x1080` will pan the display as the mouse/pointer moves if the scale doesn't show the entire desktop ( due to aspect differences ?)
` --pos 100x0` to fix the external display offset instead of using panning
`--same-as eDP1` to line up the top left corners of the two displays if needed.


If you have problems with the stylus/touchscreen lining up ( i.e. second screen extends outside of main screen ):
```
xinput --map-to-output "N-trig DuoSense Pen stylus"  eDP1
xinput --map-to-output "N-trig DuoSense"  eDP1

```
Note For scripts use device names as above! You can use an id # instead of"N-trig.." but the id# can change by simply booting with a different usb device plugged in.  _hint: run xinput on its own for device names._

**Comment by cbm755** [comment] 2019-05-25 19:53
another related nice feature (that could be possible with good MVC separation) would be showing the previous page on a different screen.  Then I can make a presentation on one projector while also showing the previous page on a second projector.  This would duplicate how I currently teach with two doccams.

**Comment by Technius** [comment] 2019-05-30 06:31
@cbm755 That would be pretty easy to implement once we get presentation working on a second display.

**Comment by LittleHuba** [comment] 2019-06-27 19:08
Additional wishes from #1301:
A full presenter mode (as in PowerPoint) shows me the time, notes and the next slide

**Comment by wallento** [comment] 2019-06-27 20:30
Thanks for pointing me here @LittleHuba! When it comes to presentations, I am still stuck at PowerPoint because I find the presenter mode very useful during lectures. The ability to store drawings and distribute them to my students after the lecture allows me to develop things beyond just adding some strokes here and there, but without much need of post-processing. But now I am thinking of finally moving to beamer and look into how to get to at least the same level of comfort.

I have looked into pdfpc recently, which pretty much resembles the very basic functionality of the powerpoint presenter, but doesn't have (and wants to have) the ability to store drawings.

As this issue is currently something like a wish list, I want to add my thoughts and wishes :)

- Very basic is the second monitor as in the original text, this already helps a lot and seems reasonable
- Special treatment of beamer overlays would be great, in particular an annotation drawing should be identical for all overlay pages. The logic for this can probably be derived from pdfpc or others, where this grouping happens. I am less sure about how that could work with xournal++. This specialization could even extend to a processing step (plugin?) where the overlay slides except the last ones are removed for the sanitized PDF for distribution, but that's like lowest priority as it is just a tedious task otherwise
- Some special layout of the "presenter screen" to show next slide, notes, time, etc. This seems pretty much straightforward too in general and can grow over time.
- Essentially what @cbm755 said: This was brought up by students and colleagues that already do it manually. Having the ability to add further screens (we have up to three different screens in lecture halls that we can all drive individually) and then either show the last slide or "stick" arbitrary slides there is very useful. Those could be definitions, summaries, overviews, etc.

Sorry, for just adding more thoughts and suggestions and no solutions (yet), but it would be really great if xournal++ could be extended towards those. Unfortunately, my GTK experience is very limited, but I could potentially help out with some of the tasks during summer break.

BTW: Thanks for working on xournal++, it finally feels like my convertible and my preferred OS become actually compatible ;)

**Comment by pierrethibault** [comment] 2019-10-18 20:14
As a temporary solution for linux laptop users, what I do (currently with xournal, but xournal++ would be the same) on linux for teaching is mirroring just a portion of my laptop screen. I have a script that runs
```
otherscreen=`xrandr | grep " connected " | tail -1 | awk '{print $1}'`
```
to detect the plugged projector, then
```
xrandr --output $otherscreen --mode 1280x1024 --pos 10x24
```
to mirror a 1280x1024 section of my screen, offset by 10 pixels in x and 24 in y.
Then, I run
```
wmctrl -r :SELECT: -e 0,0,-120,1286,1150
```
and click on the Xournal window to reshape it.

My students see only the drawing portion of the window, and I have a 640-pixel band on the right to put my notes or other useful material.

I use ffmpeg with the same size and offset settings to make screencasts of my lectures.

**Comment by CryptoMathician** [comment] 2020-09-09 10:25
A full presentation mode with second monitor and showing the time on the screen together with nodes would be very helpful and would make Xournalpp more attractive to use for presentations - not only for note taking. 

It would be very nice, if it would be possible to implement a presentation mode, which are able to do
- sharing slides on a second screen 
- show Beamer notes (Latex slides as pdf) only of the presenter view
- show a timer of the whole presentation + timer for the actual slide
- settings to choose the second screen

I would appreciate it, if that will be a feature in the future.

**Comment by kauesena** [comment] 2021-10-17 22:15
Are there news regarding this issue?
I'd like to mention another use case. I usually write with view very zoomed in and when doing a presentation it would be nice to be able to zoom in for writing while still showing the whole page for the audience.

**Comment by bhennion** [comment] 2022-12-25 11:27
Duplicate of #936

**Closed by bhennion** 2022-12-25 11:27 UTC
Labels: enhancement, difficulty::hard, priority::medium

**Comment by niceiq** [comment] 2023-05-03 00:41
OpenBoard does this pretty efficiently. This is what I am currently using, but I want to switch to Xournal++. As an online teacher working with a multi-monitor setup, this feature would be amazing.

**Comment by niceiq** [comment] 2023-09-12 02:28
Any news regarding that issue?
