### ISSUE TITLE
Can't write anything on Xournal++

### ISSUE THREAD

**Issue by Encefaloniel** [xournalpp/xournalpp#2583] opened 2020-12-23 02:48 UTC
**Affects versions :**
 - OS: Manjaro 20.2
 - Desktop environment: XFCE
 - Version of libgtk: 3.24.23
 - Version of Xournal++: 1.0.19    
 - Installation method: Manjaro software manager

**Describe the bug**
Can only write dots. Can't write any continuous lines.

**To Reproduce**
1. Choosing "pen" 
2. Holding mouse click to write/draw something

**Expected behavior**
Making a continuous line

**Actual behavior**
With pen tool, i only get a dot on the first place i clicked the mouse button.

**Additional context**
The same problem occurs with any tool that requires clicking and holding mouse button to draw (e.g highlighter, draw geometric figures)
Tools that use the keyboard (e.g text tool, add/edit tex) work normally.
I also installed Xournal++ through the snap command but the problem still occurs.

**Comment by personalizedrefrigerator** [comment] 2020-12-23 02:59
Are you using the new input system? If not, try enabling it.

**Comment by Encefaloniel** [comment] 2020-12-23 03:59
> Are you using the new input system? If not, try enabling it.

Okay, i was not using it. Now it's working fine. First time using Xournal++ so i did not know about it. Thank you for the help.

**Comment by personalizedrefrigerator** [comment] 2020-12-23 04:43
The new input system is labeled "Experimental". This should probably no longer be the case.

![image](https://user-images.githubusercontent.com/46334387/102960143-2d41c400-4496-11eb-8715-0977b9a868fa.png)

Thank you for the bug report!

**Comment by rolandlo** [comment] 2020-12-23 05:18
@personalizedrefrigerator This label and the old input system will be removed with PR #2308
Since the problem is solved, I will close this issue now.

**Closed by rolandlo** 2020-12-23 05:18 UTC
Labels: bug
