### ISSUE TITLE
Inserting vertical space should not silently drop content off the bottom of the page

### ISSUE THREAD

**Issue by AxelBoldt** [xournalpp/xournalpp#1874] opened 2020-04-19 00:21 UTC
Thank you for Xournal++, it's great! However...

If I insert vertical space between two lines on a page, material at the bottom of that page is silently moved off the page and is lost. (Or is it? I don't know where to find it.) This, to me, makes the feature entirely useless, because clearly that's not what I want or expect when editing notes. I want the material to be pushed onto the next page, and if there is no next page, I want a warning. I think that's what every user would expect.

(I'm using Xournal++ 1.0.17 on Windows 7.)

**Comment by Technius** [comment] 2020-04-19 18:28
Duplicate of #1186.

**Closed by Technius** 2020-04-19 18:28 UTC
Labels: bug
