### ISSUE TITLE
move .xournalpp to .config and .local

### ISSUE THREAD

**Issue by atticus-sullivan** [xournalpp/xournalpp#1887] opened 2020-04-21 11:24 UTC
Hi,

would you mind moving your config files to `.config` and the data you store usually in `.xournalpp` to `.local` / `.local/share`? Or even better, respect the XDG  directories (set by environment variables), see [https://wiki.archlinux.org/index.php/XDG_user_directories](url). Many users prefer this under linux since with this the home directory stays clean ;)

**Comment by Technius** [comment] 2020-04-21 17:58
Duplicate of #1101.

**Closed by Technius** 2020-04-21 17:58 UTC
Labels: enhancement
