### ISSUE TITLE
Xournal++ Crash

### ISSUE THREAD

**Issue by triptronics** [xournalpp/xournalpp#1457] opened 2019-09-05 16:20 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 19.04 / GNOME
 - Version of Xournal++ 1.0.13

**Describe the bug**
While using Xournal++, the program randomly crashed. I was just writing as usual until I thought I had somehow accidently closed the window but no, xournal++ crashed. I was able to recover my file just fine.

**To Reproduce**
1. Not sure... this never happened before. I was simply writing with my pen as usual.

**Expected behavior**
Pls don't crash on me, I beg.

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

**Additional context**
[errorlog.20190905-120820.log](https://github.com/xournalpp/xournalpp/files/3580250/errorlog.20190905-120820.log)

**Comment by triptronics** [comment] 2019-09-05 18:13
Crashed another two times, all the same contents in the crash log. This wasn't happening before :/

**Comment by Technius** [comment] 2019-09-06 07:20
Looks like an element is being deallocated prematurely/set to null somewhere. I have a few questions:

* Did all of the crashes happen while you were using the pen?
* Specifically, which version of "1.0.13" are you using? Do you know when you downloaded it, or do you know the git commit id?
* What kind of objects are present in your document? Strokes? Images? Text? etc.
* Did you do anything major before this issue starting happening? e.g. updating packages?

**Comment by lehmanju** [comment] 2019-09-28 17:55
Related to #1475 #1471

**Comment by lehmanju** [comment] 2019-09-28 17:58
@triptronics try installing gtk version 3.24.10

**Comment by WillNilges** [comment] 2019-12-05 22:19
I'll say that recently, I've been experiencing a lot of crashing on a WQHD ThinkPad Yoga Gen 1 running Fedora 31. It's been hard to track down a pattern, but it seems to happen when I do this:
- Open Xournal++
- Change pens and pen sizes
- Try to write.
The app then crashes, often without offering recovery or saving my settings.

**Comment by LittleHuba** [comment] 2019-12-05 22:34
Please do not resurrect very old issues, that's reserved for necromancers :wink:. The scenarios over time change and it is more confusing than helping for finding the cause.

Please open a new issue instead and provide the error logs you may find at `~/.config/xournalpp/errorlogs/` or for older versions at `~/.xournalpp/errorlogs/`.

**Comment by LittleHuba** [comment] 2019-12-05 22:35
@triptronics please provide an update if installing the mentioned GTK version helped. Otherwise I'll close the thread as orphaned.

**Comment by triptronics** [comment] 2019-12-05 23:11
> @triptronics please provide an update if installing the mentioned GTK version helped. Otherwise I'll close the thread as orphaned.

Hi @LittleHuba,
I didn't have the chance to test this and final exams are approaching so I am just using the stable release from May and it is not crashing. Something in the new one is definently causing a crash though. I'll try installing the new latest stable version (if there is one out or when it comes out) and I'll report back. Maybe this issue can be closed till then and if I have an issue with the new stable version I'll reopen. Thank you!

**Comment by LittleHuba** [comment] 2019-12-06 07:41
Okay. Please close the issue yourself. Otherwise you'll be unable to open it again.

**Comment by WillNilges** [comment] 2019-12-06 15:07
I will try the GTK version, give me the weekend though, as it is finals week.

**Comment by WillNilges** [comment] 2019-12-06 15:10
I can say now that I have also been experiencing similar crashes on my T450s with an external Wacom tablet.

**Comment by WillNilges** [comment] 2019-12-06 15:59
FYI my GTK3 version is
gtk3-3.24.13-1.fc31.x86_64

**Comment by lehmanju** [comment] 2020-03-23 07:45
@WillNilges could you reproduce the issue? If not please close this ticket.

**Comment by WillNilges** [comment] 2020-03-23 11:40
This wasn't my issue in the first place, so I can't close it. But I can say that the crash hasn't happened in a very long time, so It's probably fine to close the issue.

**Closed** 2020-03-23 17:54 UTC
Labels: Crash, bug, need info, priority: high
