### ISSUE TITLE
Crash when holding middle mouse and dragging out of the document pane.

### ISSUE THREAD

**Issue by RogerGodzilla** [xournalpp/xournalpp#2224] opened 2020-09-08 04:57 UTC
**Affects versions : 1.0.16-4-g07cb970f5a**
 - OS: Linux Focal Fossa 20.04 LTS
 - Desktop environment: Gnome
 - Which version of libgtk do you use
     - not 100% sure, but I think it's something like 3.0.so.1.1.0
 - Version of Xournal++: 1.0.16-4-g07cb970f5a - latest/stable
 - Installation method: Ubuntu Software install

**Describe the bug**
When scrolling by holding middle mouse click, if the cursor leaves the document frame the program crashes.

**To Reproduce**
1. Step 1
    load a document in xournal++
2. Step 2
    move the cursor over the document frame
3. Step 3
    press and hold the middle mouse button
4. Step 4
    drag the cursor out of the document frame

**Expected behavior**
The document continues to move with the cursor

**Actual behavior**
The program crashes

**Comment by rolandlo** [comment] 2020-09-09 20:28
I can't reproduce this bug. What are your settings for Input System and for Mouse (middle mouse button)? Please check this under edit->preferences.

**Comment by RogerGodzilla** [comment] 2020-09-09 22:15
>What are your settings for Input System and for Mouse (middle mouse button)? Please check this under edit->preferences.


![image](https://user-images.githubusercontent.com/32744356/92660288-bce4ad80-f2bf-11ea-834a-b98e3d3e6f71.png)

![image](https://user-images.githubusercontent.com/32744356/92660315-ce2dba00-f2bf-11ea-81d6-025e7501f23f.png)

![image](https://user-images.githubusercontent.com/32744356/92660346-dc7bd600-f2bf-11ea-90c5-3639b33b6e37.png)

![image](https://user-images.githubusercontent.com/32744356/92660386-ebfb1f00-f2bf-11ea-963d-03e827122cbe.png)

I have included some extra settings that I thought had a chance of being related to help reduce your time cost. Thanks for the help!

**Comment by RogerGodzilla** [comment] 2020-09-09 23:01
It's probably worth noting that I use a wacom intuos tablet, but the bug is still present when I use my mouse (even without the tablet plugged in).

**Comment by RogerGodzilla** [comment] 2020-09-09 23:07
Just opened xournal, caused a crash, then grabbed the error log from snap/xournalpp/31/errorlogs
[errorlog.20200909-180418.log](https://github.com/xournalpp/xournalpp/files/5198305/errorlog.20200909-180418.log)

**Comment by rolandlo** [comment] 2020-09-10 04:14
Thanks for the infos. Unfortunately I still cannot reproduce the bug, although I use the same OS and the same (snap) version of Xournal++. 
Can you check if this behaviour is still there, if you enable the new input system and restart Xournal++?

**Comment by RogerGodzilla** [comment] 2020-09-10 04:27
When I enable new input system, I can't reproduce the crash. The stylus requires a press when switching tools via the integrated buttons (ie hold a button on the stylus to switch to region select *and* drag the pen instead of hover-dragging) but it works flawlessly!

It will take some getting used to, but I think this system is better.
Thank you!

**Comment by RogerGodzilla** [comment] 2020-09-10 04:27
Oh, should I mark this as resolved, or should we leave it open?

**Comment by rolandlo** [comment] 2020-09-10 04:34
Since the old input system is soon going to be eliminated, I am closing this issue now.

**Closed by rolandlo** 2020-09-10 04:34 UTC
Labels: bug
