### ISSUE TITLE
new page adding

### ISSUE THREAD

**Issue by soumyaranjan191819** [xournalpp/xournalpp#4099] opened 2022-06-16 19:09 UTC
**Is your feature request related to a problem? Please describe.**
when i add a new page there  is a gap between two page and it makes problem.if possible make two page connected so that it will easy to write.
![xouranalcpp](https://user-images.githubusercontent.com/92353506/174146665-5e4c9baf-4ada-437c-91cc-c700e5f701aa.png)

**Describe the solution you'd like**
two page must be connected with no gap between them
**Describe alternatives you've considered**

**Additional context**

**Comment by bhennion** [comment] 2022-07-21 18:03
Duplicate of #3633

**Closed by bhennion** 2022-07-21 18:03 UTC
Labels: enhancement
