### ISSUE TITLE
Preferences is unaccessible in Mac.

### ISSUE THREAD

**Issue by MahdeenSky** [xournalpp/xournalpp#4655] opened 2023-02-17 02:07 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Mac
 - Version of Xournal++: 1.1.3
 - Installation method: official release

**Describe the bug**
Xournal Preferences is impossible to modify or even enter

**To Reproduce**
1. Click Xournal++ on the top left of the mac menu bar
2. Preferences, about Xournal, are greyed out.

**Expected behavior**
Preferences is accessible and can be opened.

**Screenshots of Problem**
<img width="283" alt="Screen Shot 2023-02-16 at 9 06 20 PM" src="https://user-images.githubusercontent.com/49484385/219531077-ac3d0b6e-de3f-4525-9e91-46ea0b5c537b.png">

**Comment by rolandlo** [comment] 2023-02-17 05:24
This is basically a duplicate of #4633. I'm closing it therefore.

**Closed by rolandlo** 2023-02-17 05:24 UTC
Labels: bug

**Comment by rolandlo** [comment] 2023-02-17 05:26
Meanwhile find the preferences under menu `Edit > Preferences`. It's just not integrated into the global menu.
