### ISSUE TITLE
Simpler alternative keyboard shortcuts

### ISSUE THREAD

**Issue by hiptmair** [xournalpp/xournalpp#1616] opened 2019-11-19 07:10 UTC
It would be desirable to have **single-key keyboard shortcuts** as an alternative to the currently provided multi-key keyboard shortcuts whenever the user is in a mode that does not require keyboard input.

When writing on my tablet I also have a small wireless keyboard on my desk. It would be very convenient, if I could change modes, colors, etc. by _pressing a single key_ on that keyboard with my left hand instead of either using the awkward `Ctrl-Shift-<key>` shortcuts or clicking an icon with my pen.

It should also be possible to control pen and eraser thickness by means of keyboard shortcuts.

**Comment by Technius** [comment] 2019-11-20 02:04
Duplicate of #919.

**Closed by Technius** 2019-11-20 02:04 UTC
Labels: enhancement
