### ISSUE TITLE
Dissappearing cursor issues when using pen, highlighter and eraser

### ISSUE THREAD

**Issue by nicolae-stroncea** [xournalpp/xournalpp#2751] opened 2021-02-06 02:16 UTC
I was able to reproduce the issues on both the Flatpak and Ubuntu PPA.

I included the Flatpak issues here as I wasn't sure if this is technically a packaging issue and should be reported in the flathub repository instead. Let me know if you prefer I post them there.

**Affects versions :**
 - OS: Linux, Gnome X11, Ubuntu 20.04
 - Which version of libgtk do you use
     - libgtk: 3.24.2 ubuntu ppa,  3.24.21 in flatpak app
 - Which version of Xournal++:
   - 1.1.0 dev(installed from ubuntu ppa) and 1.0.20(flatpak)

**Bug description**:

There are multiple and I think they may be related.

1. (Both new and old input systems, both PPA and Flatpak) Mouse pointer disappears when highlighting with pencil. Both versions affected. To reproduce, just highlight something. This can make it hard to determine how to position cursor when highlighting something.
2. (Both new and old input systems, Flatpak) Eraser icon completely disappears when using the Flatpak to annotate an existing PDF. To reproduce, open a PDF to annotate, click on eraser and go to drawing area. Eraser icon disappears and I have no clue where I am on the drawing canvas. It seems fine however when I just open a blank xournal sheet from the start. Note: it may be a bit more random than that.
3. (new input system, Flatpak, wacom). Cursor disappears when using a highlighter, or any colored pen(except for white, red, black and red). This is using the regular colour palette with a right hand note taking toolbar. This is very similar to issue 2. and makes it impossible to use those tools as i have no idea where i am in the drawing canvas

**Comment by Technius** [comment] 2021-02-06 19:53
Can confirm bug 1 happens on a version compiled from source. But is this really a big issue? If you're highlighting something, you're going to be focus on the cursor position anyways. I suppose it can be a problem when you're trying to add highlights to a region that is already highlighted / the same color.

I can't reproduce the second bug in my manually compiled version; perhaps this is a Flatpak issue?

Third issue suggests that there is a problem in the Flatpak configuration that is preventing the cursor from changing correctly.

**Comment by nicolae-stroncea** [comment] 2021-02-07 06:33
@Technius thinking more on it, i don't think that 1 is an issue. I also realized that I can also choose a small dot icon in "View" preferences to create a small cursor for the highlighter.

**Comment by nicolae-stroncea** [comment] 2021-02-07 23:34
I launched the flatpak from terminal to look at the logs and I am seeing these lines whenever I'm using a tool without a cursor:

```
** (com.github.xournalpp.xournalpp:2): WARNING **: 18:30:04.842: CSS Cursor and backup not valid 'grab', ''

** (com.github.xournalpp.xournalpp:2): WARNING **: 18:30:09.107: CSS Cursor and backup not valid 'default', ''

```

**Comment by Technius** [comment] 2021-02-08 22:58
That definitely looks like a flatpak packaging issue. Maybe some files are not being packaged correctly.

**Comment by rolandlo** [comment] 2021-07-26 07:36
The flatpak for version 1.1.0 doesn't have this issue any more, so I am closing this issue.

**Closed by rolandlo** 2021-07-26 07:36 UTC
Labels: Flatpak, bug, papercut, priority::medium
