### ISSUE TITLE
DOTTED graph with border

### ISSUE THREAD

**Issue by langfingaz** [xournalpp/xournalpp#2119] opened 2020-07-18 15:20 UTC
**Affects versions :**
 - OS: Linux (Arch Linux - (Linux only) Desktop environment: X11
 - Version of Xournal++: 1.0.18-1, Git commit 535d261d
 - Installation method: pacman

**Describe the bug**
I have a `.xopp` file with two pages (provided at the bottom of this issue). Both pages have the "graph with border" background and some handwritings on them.

When I export it as PDF, the resulting PDF has correct background for the first page, but has a "__dotted__ graph with border" background on the second page. Note, you can't select a background of this type in Xournalpp ^^.

When I extract my `.xopp` file and look into the XML file, the two pages start with these lines:
* page1:
```
<page width="595.27559100" height="841.88976400">
<background type="solid" color="#ffffffff" style="graph" config="m1=40,rm=1"/>
<layer>
```
* page2:
```
<page width="595.27559100" height="841.88976400">
<background type="solid" color="#ffffffff" style="graph" config="m1=40,rm=1"/>
<layer>
```

So I wonder where the error comes from ...

**To Reproduce**
Export provided `.xopp` file as PDF, e.g. with `xournalpp -p strangeBackground.pdf a6_Formeln.xopp`.
The bug does __not__ occur when exporting as image, e.g. with `xournalpp -i allFine.png a6_Formeln.xopp`.

I could not reproduce this error (so far) with a new `.xopp` file. The steps I tried:
1) Create new PDF
2) Change background of "insert Page" to "insert graph with border"
3) Insert two pages deleted the first one (as it's background is is ruled)
4) When exporting this `.xopp` file, the resulting PDF is fine!

**Expected behavior**
Exported PDF should have "graph with border" background on all two pages.

**Screenshots of Problem**
<img src="https://cloud.privacy1st.de/s/8fkXjtp2kgtzBKS/download" alt="drawing" width="200"/>

**Additional context**
* Link to `.xopp` file: [https://cloud.privacy1st.de/s/icGBdRsJYTkDHHx]()
* Link to PDF: [https://cloud.privacy1st.de/s/PCy6pTtHFxWSS6L]()
* Link to XML: [https://cloud.privacy1st.de/s/nmAXESLHCNyTcJ5]()

**Comment by rolandlo** [comment] 2020-07-18 17:54
Thank you for the detailed bug report. I'll look into this. The bug is reproducible with version 1.1.0+dev.

**Comment by rolandlo** [comment] 2020-07-18 19:53
I can say now exactly when the problem arises:

1. Create a new xopp-file with 2 pages, both with graph paper (with or without border)
2. Draw at least one stroke on the first page. Make sure **the last stroke you paint on the first page is dotted**. 
3. Draw whatever you like on the second page (nothing is fine, too)
4. Export the pdf (with background)
5. Open the exported pdf with a pdf-viewer and observe that the second page has a dotted background.

The reason seems to be quite clear: When the first page has been drawn the cairo context preserves the dotted line style until the next page is drawn. It should be reset instead. 
I think this should be easy to fix. Addressing this might fix some other problems as well. When I find time (next week) I will provide a PR (unless someone else wants to it).

**Comment by langfingaz** [comment] 2020-07-19 18:43
Wow, thanks for your quick reply! I'm glad I could help with my detailed report ;)

**Comment by rolandlo** [comment] 2020-07-22 22:10
I was correct in describing the cause of the problem. PR #2131 is a simple fix. Once it gets merged this issue will be closed.

**Closed** 2020-07-26 17:33 UTC
Labels: bug, confirmed
