### ISSUE TITLE
Table of Contents in Xournal++ and pdf created out of a journal

### ISSUE THREAD

**Issue by 1st-AdmiralGeneral** [xournalpp/xournalpp#4463] opened 2022-12-01 08:34 UTC
**Is your feature request related to a problem? Please describe.**
I use Xournal++ to summarize my University stuff. Usually my Journals become very long. It is difficult to work in a Journal i haven't used a long time. It would be really helpful to have a table of content(TOC) for a good overview of the content and a fast browse in the Journal.
If i import a PDF in Xournal i can use the TOC of the PDF. But if i create my own Journal there is no tool to create a TOC.

**Describe the solution you'd like**
How i would Imagine this tool:
The sections and subsections could be placed in the Journal like the Text-tool. In the toolbox there is a tool called "SECTION" if clicked, it is possible to choose between section, subsection, ...,  etc.. After this you can write the title of the section and place it in the Journal.
Additional there should be a new mode (besides layer and page) in the sidebar called table of content. Just like in a PDF-reader, with a click on a subsection in the sidebar the journal navigates to this page where the subsection is.

Maybe there can be conflicts if you import a PDF with a TOC and you want to use the "SECTION" tool. I don't know if it is possible to make it work but to chooes between 

**Describe alternatives you've considered**
I have tried to create a TOC and a Section using the Latex tool but couldn't make it work. My Latex skills are low.
I tried the  \section{blablabla} command usable in the \documentclass{article} but didn't work.
Maybe it is possible to do this with the Latex tool, if so i would be more as happy if someone could help me with the right commands.

**Additional context**

**Comment by RichardScharf** [comment] 2022-12-01 13:59
I currently use jPDF Tweak to edit the TOC externally afterwards, a feature like this would be nice though.

**Comment by bhennion** [comment] 2022-12-01 17:30
Duplicate of #3193

**Closed by bhennion** 2022-12-01 17:30 UTC
Labels: enhancement
