### ISSUE TITLE
lag and flickering when using pen

### ISSUE THREAD

**Issue by domenicozambella** [xournalpp/xournalpp#4016] opened 2022-05-09 11:12 UTC
**Affects versions :**
   - Kubuntu 20.04
   - libgtk: 3.24.20
   - xournalpp: 1.1.1+dev
   - Installation method: PPA

The problem begun end of April after an upgrade.

https://user-images.githubusercontent.com/26542246/167398403-a68206bf-0bac-4ac2-8512-2e642a5b9dbe.mp4

**Comment by danemtsov** [comment] 2022-05-09 14:04
Probably duplicate of #4011

**Closed** 2022-05-09 14:25 UTC
Labels: bug
