### ISSUE TITLE
line thickness using tablet

### ISSUE THREAD

**Issue by hsikkema** [xournalpp/xournalpp#1998] opened 2020-05-19 19:20 UTC
When I annotate a PDF file, the line width is only one pixel and I would like much more width.  Either I do not know how to make wider lines or that capability is not there.  I see the "fine", "medium" and "thick" options but nothing that lets me specify the number of pixels ... "Thick" is far too narrow for my writing.

Below is a sample of what I see in Windows 10.  At the top middle of the screen shot, you'll see some scribbles in "fine", "medium" and "thick" and then an arrow pointing to the thickness I'd like to see.  (I did that on Adobe PDF Reader)

![image](https://user-images.githubusercontent.com/65623722/82368812-05f8b500-99e4-11ea-9764-f1a531e992f0.png)

**Comment by Technius** [comment] 2020-05-20 03:10
Unfortunately, no one has started working on #1361 yet (which this issue is a duplicate of). There is a `Very Thick` option you can drag on to your toolbar with `View > Toolbars > Customize`; it may not be what you need, but I think it's at least worth trying.

**Closed by Technius** 2020-05-20 03:10 UTC
Labels: enhancement

**Comment by manu-mannattil** [comment] 2020-06-10 01:00
I have the same issue and as a workaround I've been using a small [Python script](https://gist.github.com/manu-mannattil/eebe61eb68f184295eeb6848d9be8d08) to modify the stroke thickness.
