### ISSUE TITLE
"g_unlink() failed" when trying to write LaTeX annotations

### ISSUE THREAD

**Issue by DUOLabs333** [xournalpp/xournalpp#2775] opened 2021-02-08 16:03 UTC
Windows 10, Xournal 1.1.0 dev. When I'm typing up LaTeX annotations, every second or so, it says "Could not save .tex file: [path] could not be saved. g_unlink() failed. Permission denied". The annotation does not even load in the preview. Running in administrator mode does not work. I did not keep the folder in "Program Files", if that matters.

**Comment by rolandlo** [comment] 2021-02-08 17:37
I can reproduce the problem with the nightly from Feb 08, 2021 on Windows. It doesn't happen with the nightly from the day before (Feb 07). The regression must have been introduced in #2728. 
@redweasel Do you have a Windows testing environment?

**Comment by redweasel** [comment] 2021-02-09 19:27
uh... @rolandlo I could setup a windows testing environment. But lets not conclude to fast. On first glance this does not seem to come from my commit.

@DUOLabs333 what version of Xournal++ do you use exactly? (you can check that in the "help > about" dialog)

**Comment by DUOLabs333** [comment] 2021-02-09 19:35
@redweasel I am using 1.1.0+ dev version that was built today at 00:18:29

**Comment by redweasel** [comment] 2021-02-09 20:09
Ok thanks. I assume your compiled commit is 6c0aa8332c7da94d9336ae247c54384ceb93cee3. I will investigate a little.

**Comment by redweasel** [comment] 2021-02-09 20:27
This is the relevant code which sent the message is in `LatexGenerator.cpp`.
@DUOLabs333 Can you check your console output for warnings? Because according to the following code in `PathUtil.cpp` it should have shown a Message saying "Could not create folder ..." and wrote a warning into the console if the folder which is used to output the LaTeX can not be created.

If that is not the case then please check if there is a Temporary folder for xournalpp with a file called "tex.tex" in it. As I do not use Windows, I don't know where that folder is though, so a quick google might help. I also don't know which programs are allowed to use the Temporary Folder in Windows, which might be relevant, as this is seemingly a permission issue.

Also, which version did work for you? What did you change except the version?

```c++

auto Util::getTmpDirSubfolder(const fs::path& subfolder) -> fs::path {
    auto p = fs::u8path(g_get_tmp_dir());
    p /= FS(_F("xournalpp-{1}") % Util::getPid());
    p /= subfolder;
    return Util::ensureFolderExists(p);
}

auto Util::ensureFolderExists(const fs::path& p) -> fs::path {
    try {
        fs::create_directories(p);
    } catch (fs::filesystem_error const& fe) {
        Util::execInUiThread([=]() {
            string msg = FS(_F("Could not create folder: {1}\nFailed with error: {2}") % p.u8string() % fe.what());
            g_warning("%s %s", msg.c_str(), fe.what());
            XojMsgBox::showErrorToUser(nullptr, msg);
        });
    }
    return p;
}```

**Comment by DUOLabs333** [comment] 2021-02-09 20:43
@redweasel  Where would I get the console output. And yes, there are multiple temp folders for xournal (don't know why). It's located at .\AppData\Local\Temp.

**Comment by rolandlo** [comment] 2021-02-09 20:44
@DUOLabs333 You only get console output if you build Xournal++ from source and run it from the console. Have you already experience with that?

**Comment by DUOLabs333** [comment] 2021-02-09 20:45
No, I use the pre-built versions.

**Comment by rolandlo** [comment] 2021-02-09 20:49
Ok, so I will take a look at it.

**Comment by redweasel** [comment] 2021-02-09 20:49
Ok well, in case the warning was there, there should have been a dialog. If thats not the case, then I guess the warning won't be there either.

As this seems like a permission thing and not anything caused by my recent commit, I will leave this up for you @rolandlo.

**Comment by rolandlo** [comment] 2021-02-09 20:50
@redweasel OK, I will find out.

**Comment by DUOLabs333** [comment] 2021-02-09 20:51
But I ran the program in administrator mode, and the error still persisted.

**Comment by rolandlo** [comment] 2021-02-09 22:04
So far I can say, that the regression has been introduced with #2728 and that there are no console messages. 
The error occurs when calling `g_file_set_contents` in 

```c++
    if (!g_file_set_contents(texFilePath.c_str(), texFileContents.c_str(), texFileContents.length(), &err)) {
        return fail({FS(_F("Could not save .tex file: {1}") % err->message)});
    }
```
The documentation can be found [here](https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-file-set-contents-full). 

Citing from that reference Windows related errors:
> On Windows renaming a file will not remove an existing file with the new name, so on Windows there is a race condition between the existing file being removed and the temporary file being renamed.

> On Windows there is no way to remove a file that is open to some process, or mapped into memory. Thus, this function will fail if filename already exists and is open.

It seems to me that the second Windows related error is responsible here: The file already exists and is open.

**Comment by Technius** [comment] 2021-02-09 22:27
The culprit might be the removal of these lines: https://github.com/xournalpp/xournalpp/pull/2728/files#diff-4cc526c85603171a74965175fdbde361e04536f97440c5b7cb673911fa7fe133L139-L141

**Comment by DUOLabs333** [comment] 2021-02-10 01:54
The newest update may have fixed the problem.

**Comment by rolandlo** [comment] 2021-02-10 05:06
> 
> 
> The culprit might be the removal of these lines: https://github.com/xournalpp/xournalpp/pull/2728/files#diff-4cc526c85603171a74965175fdbde361e04536f97440c5b7cb673911fa7fe133L139-L141

You are right about that. If I add these lines back with `isUpdating` replaced by `isUpdating()` it works again

**Comment by rolandlo** [comment] 2021-02-10 05:07
> 
> 
> The newest update may have fixed the problem.

What do you mean with "the newest update"?

**Comment by redweasel** [comment] 2021-02-10 08:53
@rolandlo Ok I see now how this comes from my commit, thanks for your work.
The lines with `isUpdating` were removed on purpose though, because the object `self` is already freed in case the render was canceled. I am assuming `g_file_set_contents_full` is closing the file after its execution, so if you type only one letter at a time, the error should not appear (if I understand the bug correctly). The problem might be that `g_file_set_contents_full` is canceled. If I read the documentation correctly, then `g_file_set_contents` which is called here should be atomic and not create a blocking file, even if canceled, so in theory this should not be a problem (so I don't understand the problem yet). There are some things one can try and see if it fixes the issue.
1. use a mutex to temporarily block the cancel action during the file save.
2. make the file save async, so if the render task is canceled the file save will still finish and close the file.

**Comment by Technius** [comment] 2021-02-10 09:02
@redweasel Wait, are we looking at the same lines of code? To be clear, I was referring to the (removed) updating check at the top of `LatexController:triggerImageUpdate`. I believe that the check should be safe since it's called either 1) on a keypress event; or 2) after rendering has been completed (so the dialog has not been closed yet).

**Comment by redweasel** [comment] 2021-02-10 11:25
@Technius oops. Yes, I was looking at the wrong check. There were two of those removed in that patch...

In that case, I made it `unsetUpdating` which should cancel the previous render and therefore release the temporary file "tex.tex". It might not be waiting for that to actually happen, could that be the issue?

**Comment by DUOLabs333** [comment] 2021-02-10 15:16
@rolandlo The binary released yesterday.

**Comment by DUOLabs333** [comment] 2021-02-10 18:25
@rolandlo Whoops, the issue isn't fixed. Must have mixed it up with an old version of Xournal++ I still have (thankfully).

**Comment by Technius** [comment] 2021-02-10 19:21
@DUOLabs333 Does the issue occur if you wait for the preview to update before typing in each character? E.g. when writing `x^2`, you would type in `x`, wait, type in  `^`, wait, type in `2`, wait. (Please try with a longer example). If the issue does not happen, that would confirm my hypothesis.

> @redweasel In that case, I made it unsetUpdating which should cancel the previous render and therefore release the temporary file "tex.tex". It might not be waiting for that to actually happen, could that be the issue?

Here's my guess: `unsetUpdating` would cancel the previous render, but that wouldn't solve the problem because the tasks could be scheduled in such a way that the new preview request would attempt to write to the same file handle before the previous render task is cancelled.

**Comment by DUOLabs333** [comment] 2021-02-10 19:26
Huh, you're right. If I wait between presses, nothing pops up. However, if I press multiple keys at the same time, the error pops up.

Side note, though: why are there so much ten folders for journal, and can you make either a portable version or allow us to set our own temp folder (I like to use portable software whenever possible)?

**Comment by redweasel** [comment] 2021-02-11 16:13
Ok I have dug, through the code once again and I have kind of an idea whats happening.

This is what I think the patch might look like: (but didn't test on windows)
```diff
diff --git a/src/control/LatexController.cpp b/src/control/LatexController.cpp
index e9847c88..998ddf5c 100644
--- a/src/control/LatexController.cpp
+++ b/src/control/LatexController.cpp
@@ -140,6 +140,9 @@ auto LatexController::showTexEditDialog() -> string {
 
 void LatexController::triggerImageUpdate(const string& texString) {
     this->unsetUpdating();
+    if (this->isUpdating()) {
+        return;
+    }
 
     this->lastPreviewedTex = texString;
     const std::string texContents = LatexGenerator::templateSub(
@@ -201,7 +204,7 @@ void LatexController::onPdfRenderComplete(GObject* procObj, GAsyncResult* res, L
         }
     }
 
-    self->unsetUpdating();
+    g_clear_object(&self->updating_cancellable);
     self->updateStatus();
     if (shouldUpdate) {
         self->triggerImageUpdate(currentTex);
@@ -232,7 +235,6 @@ void LatexController::updateStatus() {
 
 void LatexController::unsetUpdating() {
     g_cancellable_cancel(updating_cancellable);
-    g_clear_object(&updating_cancellable);
 }
 
 void LatexController::deleteOldImage() {
```

**Comment by rolandlo** [comment] 2021-02-11 16:29
I can test your patch on Windows and report back.

**Comment by rolandlo** [comment] 2021-02-11 16:56
The patch does not work on Windows. If you switch the order of `this->unsetUpdating` and the following 3 lines in `LaTeXController::triggerImageUpdate` it does work.

**Comment by redweasel** [comment] 2021-02-11 17:06
@rolandlo Thanks! If switching those statements fixes it, then the `this->unsetUpdating` would be omitted completely, cause it would not be doing anything. But the patch should work. I think I missed a detail in `isUpdating`. Can you test again?

```diff
diff --git a/src/control/LatexController.cpp b/src/control/LatexController.cpp
index e9847c88..87951f2f 100644
--- a/src/control/LatexController.cpp
+++ b/src/control/LatexController.cpp
@@ -140,6 +140,9 @@ auto LatexController::showTexEditDialog() -> string {
 
 void LatexController::triggerImageUpdate(const string& texString) {
     this->unsetUpdating();
+    if (this->isUpdating()) {
+        return;
+    }
 
     this->lastPreviewedTex = texString;
     const std::string texContents = LatexGenerator::templateSub(
@@ -201,14 +204,14 @@ void LatexController::onPdfRenderComplete(GObject* procObj, GAsyncResult* res, L
         }
     }
 
-    self->unsetUpdating();
+    g_clear_object(&self->updating_cancellable);
     self->updateStatus();
     if (shouldUpdate) {
         self->triggerImageUpdate(currentTex);
     }
 }
 
-bool LatexController::isUpdating() { return updating_cancellable && !g_cancellable_is_cancelled(updating_cancellable); }
+bool LatexController::isUpdating() { return updating_cancellable; }
 
 void LatexController::updateStatus() {
     GtkWidget* okButton = this->dlg.get("texokbutton");
@@ -232,7 +235,6 @@ void LatexController::updateStatus() {
 
 void LatexController::unsetUpdating() {
     g_cancellable_cancel(updating_cancellable);
-    g_clear_object(&updating_cancellable);
 }
 
 void LatexController::deleteOldImage() {
```

**Comment by rolandlo** [comment] 2021-02-11 17:52
Now the TexImage doesn't change at all when adding letters to the LaTeX formula.

**Comment by redweasel** [comment] 2021-02-11 18:02
@rolandlo ok thanks, for testing. I will try to completely fix this now and make a PR.

**Comment by Technius** [comment] 2021-02-16 01:29
@DUOLabs333 The PR has been merged. Let us know if the issue is fixed in the next nightly version.

**Closed** 2021-02-16 01:28 UTC
Labels: bug, confirmed, os::windows, priority::high, regression

**Comment by DUOLabs333** [comment] 2021-02-16 14:44
@Technius I don't see a new nightly version, though.

**Comment by rolandlo** [comment] 2021-02-16 14:58
@DUOLabs333 You will have to wait one more day.

**Comment by DUOLabs333** [comment] 2021-02-17 15:32
@rolandlo The new version seems to work fine.
