### ISSUE TITLE
Drawing lines on second page just vanish after a few seconds

### ISSUE THREAD

**Issue by StefanL38** [xournalpp/xournalpp#2876] opened 2021-02-25 12:36 UTC
(Please complete the following information, and then delete this line)

**Affects versions :**
xournal++ 1.0.20 for windows  language german

 - Installation method: 
xournalpp-1.0.20-windows.exe

**Describe the bug**
I started with an empty page and inserted a pixel image 
then draw lines and high-ligthing lines.
inserted a copy of the pixelimage
again drawing lines and highlighting lines
This pages has three layers backround layer 1 layer 2

then inserted a second page
inserted a copy of the image on that second page
added a layer. 
Then I wanted to add new hand-drawn lines
but the lines on the second page keep vanishing !!??? !!!
I draw them 1 to 5 seconds plop   the line is no longer there!! 

Guys this is a knock-out-criterium!! I'm doing live presentations with an audience
and then this faulty behaviour? I like xournal++ very much but if you can't stop this bug I will change to another software. 

I attach the *.xopp-file as zipfile.
[.11FOS1-orthogonaler-Abst-25-02-2021.autosave.zip](https://github.com/xournalpp/xournalpp/files/6042950/default.11FOS1-orthogonaler-Abst-25-02-2021.autosave.zip)

I'm very curious what you were answering to this issue

best regards Stefan

**Comment by rolandlo** [comment] 2021-02-25 13:01
This is bug #2464, which has already been fixed in master. Just use the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly) so that doesn't happen any more. The file must be repaired though, if you want to use it further. Here is the repaired version: 
[OrthAbst_Repaired.zip](https://github.com/xournalpp/xournalpp/files/6043060/OrthAbst_Repaired.zip)

**Comment by StefanL38** [comment] 2021-02-25 18:46
Hi Roland,

thank you for answering.  I switched from a nighly build of version 1.1.don't remember which one   to 1.0.20 because I had several crashes with the nighly build.

and version 1.0.20 is described as stable. Yeah stable I had no crashes. But buggy. As I have experienced now.

If I can enable any kind of debug-logging that helps analysing why the crashes occured please tell so.

I had programmed a pluigin which I lost in the uninstalling process from switching to different versions.

Can you describe which folders I can backup to keep all my customisationswhen installing a new version.?

best regards Stefan

**Comment by rolandlo** [comment] 2021-02-25 18:59
If there are crashes with the nightly it is high time to report and fix them, since version 1.1.0 is about to get released. So it would really help if you use the nightly version and try to reproduce the crash. Debugging is so much easier if a crash can be reproduced in a step to step way. Once we can reproduce it ourselves, you can't help much more (unless you build from source). 

About the lost plugin: On Linux the plugin folder doesn't get deleted. It may be different on Windows. Except of the plugin folder (when you have custom plugins) there is nothing you should backup when installing a new version, I think. You could backup the `settings.xml` file, but you may run into trouble if you use it in a new version.

**Comment by StefanL38** [comment] 2021-02-26 15:47
Hi Roland, I downloaded the nightly build of Feb 25 2021 00:16:35

and had a very annoying behaviour: after maybe 30 minutes of drawing with a pen on the touchscreen of my Lenovo Thinkpad X1 Tablet Generation 1 it took 2 to 10 seonds until some drawn lines did appear on the screen. 

Some time it is working smooth as expected some time not. 

You can imagine what this means on a live-session trying to write and explain things

I had autohotkey or the GotoMeeting-App under suspect of interfering with xournal++ or using too much CPU-power. But I could reproduce this behaviour with all this additional software terminated.

Again I have the question: Does Xournal++ does have some kind of on/off-switchable debug-function that writes plain text into a textfile?

When I was working for a mechanical-engineering company as a software-developper for industrial controls log-textfiles were the most common way for debugging. For really everything! Profi-Bus-controls, additional processor-cards for realtime control of high-speed servomotors, network-communication using UDP, TCP/IP,  Siemens\_Sicalis or whatever.

Everything was written into a logfile. So if you haven't implemented that as an on/off-switchable feature I say it is time for it.

Todays harddiscs are so fast this will cause only 0,5% processor-load

What else way to you suggest to reproduce this behaviour?

I rather go back to version 1.0.01 than going on with this behaviour.

best regards Stefan

**Comment by rolandlo** [comment] 2021-02-26 17:33
> and had a very annoying behaviour: after maybe 30 minutes of drawing with a pen on the touchscreen of my Lenovo Thinkpad X1 Tablet Generation 1 it took 2 to 10 seonds until some drawn lines did appear on the screen. 
> 
> Some time it is working smooth as expected some time not.

This sounds like issue #2520. I could never reproduce it, even though I use Xournal++ (on Ubuntu) for several hours daily. Please head over to #2520 and report your observations there. 

About logs: You can enable some input related logs, see [the wiki](https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs). They can only be generated if you build from source though, and I am not at all sure they will help to identify the problem.

**Comment by rolandlo** [comment] 2021-02-26 17:50
I will close this issue now, since the original question is solved.

**Closed by rolandlo** 2021-02-26 17:50 UTC
Labels: bug
