### ISSUE TITLE
Text fields won't export properly in PDF under windows 10

### ISSUE THREAD

**Issue by roynico** [xournalpp/xournalpp#3057] opened 2021-04-21 06:50 UTC
The function "PDF export" seem not to be able to export properly the text fields. 
I have made several experiments and: 
* either the file won't open at all (for example in Adobe Acrobat)
* or the file opens but all the text fields are absent

I'm under windows 10, Xournal++ v 1.0.20

Note that the PDF is correct if one rather does "Print to a file".
Note also that the buggy exported PDFs (that do not show the text fields under windows), DO show the text fields under Linux (Ubuntu 20.04 + Evince pdf viewer).

**Comment by rolandlo** [comment] 2021-04-21 07:01
Duplicate of  #3014.

**Closed by rolandlo** 2021-04-21 07:01 UTC
