### ISSUE TITLE
How to make a clickable https hyperlink?

### ISSUE THREAD

**Issue by brpy** [xournalpp/xournalpp#2068] opened 2020-06-16 16:02 UTC
Hello, This is a great open source projects that is valuable to me.
Is there a way I can add clickable links to the pdf? I searched online and in older issues but could find it.

Thank you!

**Comment by Technius** [comment] 2020-06-16 20:25
We currently don't have this feature. Duplicate of #1827.

**Closed by Technius** 2020-06-16 20:25 UTC
