### ISSUE TITLE
Small white border/line on the right side of every page 

### ISSUE THREAD

**Issue by MeiramSh** [xournalpp/xournalpp#4520] opened 2022-12-23 18:32 UTC
**Affects versions :**
 - OS: Manjaro Linux
 - Desktop environment: X11
 - Which version of libgtk do you use: 3.24.34
 - Version of Xournal++: 1.1.2, 3fe37c1d
 - Installation method: pacman

**Describe the bug**
Small white border on the right side of every page in a generated pdf. 

**To Reproduce**
1. Open app
2. Change background color to something other than white
3. Export pdf
4. Zoom in the right side of a page
5. See the white border

**Expected behavior**
No white border

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/71583853/209392052-b17bff49-0ae1-4986-91ff-faa7474a0d2f.png)

**Comment by Technius** [comment] 2022-12-24 15:44
Does this also happen with the nightly release?

**Comment by MeiramSh** [comment] 2022-12-25 13:11
Yes. I've just compiled from source, the same line appears.
![image](https://user-images.githubusercontent.com/71583853/209469242-76f6a8c5-4a12-4198-935f-f15f7442b3ba.png)

**Comment by bhennion** [comment] 2022-12-27 07:09
I can reproduce.

**Comment by Technius** [comment] 2022-12-27 09:42
My guess is that this is some sort of rounding error.

**Comment by AayushCurious** [comment] 2022-12-29 04:42
Has to be some faulty error or pixelation?

**Comment by MeiramSh** [comment] 2022-12-30 00:12
@Technius @AayushCurious @bhennion I am not sure how it may help, but I found out that commit 8021ed04b18f81db7efce36d5cbbf84e7da7fb86 doesn't have this issue. I checked out to this specific commit, and found that there is no white line
![image](https://user-images.githubusercontent.com/71583853/210022758-845c5dac-f96b-4cfa-ac38-0c48225c9ac6.png)

**Comment by MeiramSh** [comment] 2022-12-30 05:10
White border was removed when I commented out this line 
 `
    setlocale(LC_NUMERIC, "C");
`
from [src](https://github.com/xournalpp/xournalpp/tree/master/src)/[core](https://github.com/xournalpp/xournalpp/tree/master/src/core)/[control](https://github.com/xournalpp/xournalpp/tree/master/src/core/control)/XournalMain.cpp

**Comment by bhennion** [comment] 2023-01-04 17:33
The white strip appears (both on the right and at the bottom of the page) when the page size is not a round number of points (1 pt = 1/72 inch). This happens very often as soon as the paper size is given in international units (cm).

Here is an example of an exported pdf:
[2023-01-04-Note-18-11.pdf](https://github.com/xournalpp/xournalpp/files/10346082/2023-01-04-Note-18-11.pdf)

Running `pdfinfo -box foo.pdf` on such a file, we get
```
Page size:       481.882 x 926.914 pts
Page rot:        0
MediaBox:            0.00     0.00   481.88   926.91
CropBox:             0.00     0.00   481.88   926.91
BleedBox:            0.00     0.00   481.88   926.91
TrimBox:             0.00     0.00   481.88   926.91
ArtBox:              0.00     0.00   481.88   926.91
```
but the cairo_pdf_surface has size 482x927 pts. 

**If your locale is not C**, removing the line
https://github.com/xournalpp/xournalpp/blob/23eaf334ad332a6c7d0350fe18ac20020103a370/src/core/control/XournalMain.cpp#L78
creates a pdf wize page size 481x926 (the double numbers get truncated due to the locales not matching).

I'm not quite sure what the pdf specifications say about non-integral page sizes, but a simple fix would be to take std::floor when creating the cairo_pdf_surface. It's an easy fix, but I'm not quite sure this is the way to go: if the user selects A4 as a paper format, the exported pdf should have size A4 and not some approximation of A4.

pdfinfo seems to recognize A4 even with the approximation:
```
Page size:       595 x 841 pts (A4)
```
vs
```
Page size:       595.276 x 841.89 pts (A4)
```

I'm not 100% positive, but I think the bug lies in cairo rather than in Xournal++. Anyway, it's easier for us to fix it than to wait for a fix upstream.

**Comment by rolandlo** [comment] 2023-01-04 17:40
Hmm, when I create a A4 page with `pdflatex` I also get the exact numbers according to `pdfinfo`: 
`Page size:       595.276 x 841.89 pts (A4)`

It might be a bit dangerous to change the page size. Maybe some printer doesn't recognize it as A4 anymore and complains about the paper format. We would have to check that.

**Comment by bhennion** [comment] 2023-01-04 17:45
> Maybe some printer doesn't recognize it as A4 anymore and complains about the paper format. We would have to check that.

Yes, my thought exacly...

Also, pdflatex can generated red background pages with format A4 without any issue.

**Comment by bhennion** [comment] 2023-01-04 19:25
Ok. The bug is in cairo_pdf_surface_set_size.

Here is a minimal reproducer:
[mwe.zip](https://github.com/xournalpp/xournalpp/files/10346880/mwe.zip)

Unzip, run `make` then run `./test` and open `test.pdf`. The pdf is fine, A4, no white stripe.

Uncomment the lines
```
//    cairo_pdf_surface_set_size(surface,
//				       X_INCHES * 72.0,
//				       Y_INCHES * 72.0);
```
rebuild and rerun: a white stripe!

I will report upstream.

**Comment by bhennion** [comment] 2023-01-10 12:54
The issue was fixed upstream. Closing as we just have to wait it makes it to our pipelines.

**Closed** 2023-01-10 12:54 UTC
Labels: bug, confirmed, rendering, priority::medium
