### ISSUE TITLE
log

### ISSUE THREAD

**Issue by AstolfoOnTheMoon** [xournalpp/xournalpp#5021] opened 2023-08-08 08:04 UTC
Date: Mon Jul 24 15:52:19 2023
Error: signal 11
[bt]: (0) /usr/bin/xournalpp(+0x1bb044) [0x55c73d87f044]
[bt]: (1) /lib64/libc.so.6(+0x3db70) [0x7fa8ea85fb70]
[bt]: (2) /usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x25) [0x55c73d875e35]
[bt]: (3) /usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x93) [0x55c73d876063]
[bt]: (4) /usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xdc) [0x55c73d87615c]
[bt]: (5) /usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x224) [0x55c73d79c914]
[bt]: (6) /usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x77) [0x55c73d79cb97]
[bt]: (7) /usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0xf3) [0x55c73d797523]
[bt]: (8) /lib64/libglib-2.0.so.0(+0x8a983) [0x7fa8ebe1a983]
[bt]: (9) /lib64/libc.so.6(+0x8c907) [0x7fa8ea8ae907]
[bt]: (10) /lib64/libc.so.6(+0x112870) [0x7fa8ea934870]

Try to get a better stracktrace...
[bt] #1 /usr/bin/xournalpp(+0x1bb501) [0x55c73d87f501]
??:0
[bt] #2 /lib64/libc.so.6(+0x3db70) [0x7fa8ea85fb70]
??:0
[bt] #3 /usr/bin/xournalpp(_ZNK12DocumentView11drawElementEP6_cairoP7Element+0x25) [0x55c73d875e35]
??:0
[bt] #4 /usr/bin/xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x93) [0x55c73d876063]
??:0
[bt] #5 /usr/bin/xournalpp(_ZN12DocumentView8drawPageESt10shared_ptrI7XojPageEP6_cairobbbb+0xdc) [0x55c73d87615c]
??:0
[bt] #6 /usr/bin/xournalpp(_ZN10PreviewJob8drawPageEv+0x224) [0x55c73d79c914]
??:0
[bt] #7 /usr/bin/xournalpp(_ZN10PreviewJob3runEv+0x77) [0x55c73d79cb97]
??:0
[bt] #8 /usr/bin/xournalpp(_ZN9Scheduler17jobThreadCallbackEPS_+0xf3) [0x55c73d797523]
??:0
[bt] #9 /lib64/libglib-2.0.so.0(+0x8a983) [0x7fa8ebe1a983]
??:0
[bt] #10 /lib64/libc.so.6(+0x8c907) [0x7fa8ea8ae907]
??:0
[bt] #11 /lib64/libc.so.6(+0x112870) [0x7fa8ea934870]
??:0

**Comment by bhennion** [comment] 2023-08-08 16:46
This is most likely the same data race as in #4917. Duplicate of #4917

**Closed by bhennion** 2023-08-08 16:46 UTC
