### ISSUE TITLE
Crash when opening file or annotating PDF changes directory (gnome-icon-theme dep missing)

### ISSUE THREAD

**Issue by bryanmr** [xournalpp/xournalpp#1347] opened 2019-07-13 17:19 UTC
**Affects versions :**
 - OS: Kubuntu Linux 19.04
 - Xournal++ 1.0.13 build on July 10, 2019, 17:02:53

**Describe the bug**
When attempting to open files, changing the directory being displayed causes xournal++ to crash on two different systems.

**To Reproduce**
1. Open xournalpp
2. Click file, then open
3. Switch to any directory (can open files if they are in the first directory displayed)

**Expected behavior**
Display files to open

**Additional context**
Tried on two different setups. Using Kubuntu 19.04 on both, with 4k resolution. Can open the files via the command line and everything works. Saving displays the same behavior, but not on every directory opened.

[xournal_crash.txt](https://github.com/xournalpp/xournalpp/files/3389033/xournal_crash.txt)
[errorlog.20190713-130800.log](https://github.com/xournalpp/xournalpp/files/3389034/errorlog.20190713-130800.log)

**Comment by Technius** [comment] 2019-07-14 07:45
I can't reproduce the bug, but it looks similar to this [GIMP issue](https://gitlab.gnome.org/GNOME/gimp/issues/2029). Can you try installing `gnome-icon-theme`?

**Comment by bryanmr** [comment] 2019-07-14 16:29
I ran `sudo apt install gnome-icon-theme` and the issue went away. I'll leave this open to track that this seems to be a dependency for a Kubuntu desktop, I don't have the time today to look at doing a pull request to modify that, but I can look into it here in a day or two hopefully.

Thanks for the research and super fast turnaround!

**Comment by LittleHuba** [comment] 2019-07-15 09:43
We should add this to the FAQ as it arises quite often.

**Comment by bryanmr** [comment] 2019-07-21 00:08
The thing that is weird here is that this doesn't seem to be a problem with `xournalpp` at all. That icon seems to be something that is required by GTK itself and it being missing should impact multiple apps. I am guessing the reason that I am seeing this but others are not is that `xournalpp` is the first GTK app I installed on these systems, and it was coming from a PPA that isn't working around the missing icon.

I'm not sure if adding this to the dependency list is the right answer or if documenting it is. Getting the `Breeze` icon pack that Kubuntu uses to have the `image-missing` icon would probably be the more correct thing to do.

I'll keep looking into it for an upstream fix, and see if that makes sense... I'm fine with this being closed in any case.

**Comment by Technius** [comment] 2019-07-21 17:09
This seems to be an upstream (Kubuntu) issue, so I'm going to close this. Added this to the [newly created FAQ on the wiki](https://github.com/xournalpp/xournalpp/wiki/Frequently-Asked-Questions).

**Closed by Technius** 2019-07-21 17:09 UTC
Labels: Dependency Issue, bug
