### ISSUE TITLE
Xournal++ (nightly )crashes by the use of the pdf tool after ubuntu update

### ISSUE THREAD

**Issue by ausd1emaus** [xournalpp/xournalpp#5360] opened 2023-11-24 11:26 UTC
### Operating System

Linux

### (Linux only) Distribution

ubuntu

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

Wayland

### Installation Method

PPA

### Xournal++ Version

1.2.2+dev

### libgtk Version

3.24.33

### Bug Description

when ever i try to select text in a pdf with the pdf tool to highlight it, Xournal++ crashes.
it happens eith the tool to select a line.

### Expected Behaviour

Xournal++ wont crash by select a line and allows to highlight or copy the selected line

### Steps to Reproduce

1. open a pdf in Xournal++
2. selct pdf tool (line selection)
3. try to select a line in the pdf
4. crash

**Comment by rolandlo** [comment] 2023-11-24 11:39
Duplicate of #5343
This is already fixed in the release branch via #5348

**Closed by rolandlo** 2023-11-24 11:39 UTC
Labels: bug

**Comment by rolandlo** [comment] 2023-11-24 11:42
You may want to install from the [releases page](https://github.com/xournalpp/xournalpp/releases) instead of the PPA for the time being (until version `1.2.3` is released or the release branch is merged into master).

**Comment by ausd1emaus** [comment] 2023-11-24 13:56
thanks for trying to help me but i don*t really know how to install from the release page.
can you help me with this?

**Comment by rolandlo** [comment] 2023-11-24 14:11
> thanks for trying to help me but i don*t really know how to install from the release page. can you help me with this?

Sure. As you are on Ubuntu Jammy Jellyfish (22.04), download the Ubuntu Jammy version from the list of assets on the releases page (under Automated nightly build), or use the [direct link](https://github.com/xournalpp/xournalpp/releases/download/nightly/xournalpp-1.2.2+dev-nightly.20231123-Ubuntu-jammy-x86_64.deb),
open the terminal (hit `<Ctrl><Alt>t`) and run
```term
cd ~/Downloads
sudo apt install ./xournalpp-1.2.2+dev-nightly.20231123-Ubuntu-jammy-x86_64.deb
```
Instead of using the terminal, installing via double clicking on the downloaded .deb file might also work.

**Comment by ausd1emaus** [comment] 2023-11-24 14:42
it works, thank you very much for your help! :)
