### ISSUE TITLE
Flatpak Xournalpp cannot access /tmp/ (which prevents normal interaction with eg mail clients)

### ISSUE THREAD

**Issue by cascremers** [xournalpp/xournalpp#2426] opened 2020-11-20 11:13 UTC
**Affects versions :**
 - Flatpak  ( Xournal++ 1.0.19, libgtk 3.24.20 )

**Describe the bug**
Cannot open any file in /tmp/
This is due to default flatpak policy, and there is a simple fix. This was encountered by many other project such as gimp and slack, see e.g. https://github.com/lobner/com.slack.Slack/commit/92d83a5e7e57e067fb1fe8388f7dbe695cb47274

**To Reproduce**
1. Install xournalpp from flatpak
2. Put a PDF file in /tmp/
3. Try to open /tmp/ (no visible files)

**Expected behavior**
Files in /tmp/ should be accessible to xournalpp.

**Additional context**
See the referenced github issue for a fix.

I realise that this is a bug in the flatpak repo, so I could not even do a PR here, but it looked as if all bugs (including for flatpak) were posted here. I'll double post to the xournalpp flatpak repo, let me know if that's not the recommended way.

**Comment by Technius** [comment] 2020-11-22 07:59
Duplicate of flathub/com.github.xournalpp.xournalpp#19

**Closed by Technius** 2020-11-22 07:59 UTC
Labels: bug
