### ISSUE TITLE
Xournal black window

### ISSUE THREAD

**Issue by p-alfio11** [xournalpp/xournalpp#3619] opened 2021-11-25 14:16 UTC
**Affects versions :**
 - OS:  MacOS monteray 
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --1.1.0` 
 - Version of Xournal++: [1.1.0]
     
 - Installation method: [official release]

**Describe the bug**
I install xournall app in my mac and give the permise to install.
 the first time to  run the application  the program isn't start and the window is total black 

**To Reproduce**
1. Step 1 unarchive the file
2. Step 2 open the unarchive file with the aministrator 
3. step 3 exe xournal app 

**Screenshots of Problem**
<img width="723" alt="Schermata 2021-11-25 alle 15 15 38" src="https://user-images.githubusercontent.com/85387140/143457102-01179bcf-6bf2-45af-8c83-2e1bc966ec66.png">

sorry for my bad  english,
thank you,
Alfio

**Comment by rolandlo** [comment] 2021-11-25 21:30
Duplicate of https://github.com/xournalpp/xournalpp/issues/3517

**Closed by rolandlo** 2021-11-25 21:30 UTC
Labels: bug
