### ISSUE TITLE
Inconvenient scrolling of the document when dragging the selected object

### ISSUE THREAD

**Issue by novikovAK** [xournalpp/xournalpp#3646] opened 2021-12-07 23:28 UTC
**Affects versions :**
 - OS: Windows 11
 - Version of Xournal++: 1.1.0
 - Installation method: official release
 
**Describe the bug**
When copying an image to a listing or simply selecting any object and dragging it up and down with the left mouse button pressed, the entire document scrolls very quickly. There is no such thing in older versions. I have been working with Xournal for 7 years. It was in the new version that such a problem appeared. Please solve this problem. Thank you in advance!

**To Reproduce**
1. Make a full-page zoom
2. Draw something big and highlight it
3. Hold down the left mouse button and drag the selected object down or up

**Expected behavior**
I would like the page NOT to SCROLL at all when dragging the selected object with the left mouse button pressed. As it was before in previous versions. Let the page scroll ONLY through the mouse wheel. You can also add the ability to disable this "smart" scrolling in the settings!

**Screenshots of Problem**
Video recording with a bug demonstration: https://youtu.be/u2L4n_VOveI

**Additional context**
I have been working with your program for a very long time (about 6-7 years). I am happy to work on your program. She's just wonderful! I recommend it to all my colleagues. Therefore, the bug found made me very sad. I sincerely hope that you will be able to solve the problem I found

**Comment by rolandlo** [comment] 2021-12-08 03:15
The issue is already fixed in the [nightly release](https://github.com/xournalpp/xournalpp/releases/tag/nightly). You can either install the (unstable) nightly release or wait for the upcoming 1.1.1 release. In case of the nightly release I would recommend to wait for another day, as there is currently another issue, that should be fixed within a day (via #3644).

**Closed by rolandlo** 2021-12-08 03:15 UTC
Labels: bug

**Comment by novikovAK** [comment] 2021-12-08 10:57
Thank you very much! A very high-quality cool app! I will be happy to download the stable version when it is available.
