### ISSUE TITLE
change of tool

### ISSUE THREAD

**Issue by efarcy** [xournalpp/xournalpp#3191] opened 2021-06-26 16:47 UTC
**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows] : linux mint  20.1
 - (Linux only) Desktop environment: [e.g. Wayland, Gnome-Wayland, XWayland, X11] cinnamon
 - Which version of libgtk do you use
     - can be obtained by running `xournalpp --version` or in the **About** window : 3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]  1.1.0+dev 25/06/2021
     - can be obtained by running `xournalpp --version` or in the **About** window
 - Installation method: [e.g. PPA, Flatpak, official release, etc.]  : .deb

**Describe the bug**
Hi,
My default tool is the pen.
When I am in text mode and I use the keyboard CTRL+SHIFT+D for the pen mode, it's not exactly as if I use CTRL+SHIFT+P :
With  CTRL+SHIFT+D, I can't choose the tool to draw a rectangle immediatly : I must put the pen down, before I can choose the rectangle : While I have not pu the pen down, the option of rectangle and the others is  grayed out.
**To Reproduce**
1. Choose the pen mode for default tool.
2. Choose text mode.
3. press the keys CTRL+SHIFT+D
4. Try to choose the icon of the rectangle tool 

**Expected behavior**
The icon of  rectangle tool should'nt be grayed out and i should choose one of this tools (rectangle, ellipse, arrow, ...)
**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/83125577/123520002-cef8d680-d6ae-11eb-85cb-40128b4f0ab5.png)

**Additional context**
Add any other information or context about the problem here.

thanks !

**Comment by Technius** [comment] 2021-06-27 09:44
Looks like the UI is not updated immediately when the Default Tool is used.

Here's what I observed by following OP's steps:
1. Switch to the text tool.
2. Use the Default Tool, and then start a stroke with the mouse (do not end the stroke yet).
3. Notice that the UI still has the text tool selected, with the stroke type selector grayed out.
4. Lift the stroke.
5. Notice that the pen is now selected, with the stroke type set to rectangle.

**Comment by JulianHeuser** [comment] 2022-10-21 19:50
I can't reproduce this in 1.1.2-dev (024c3419) - I still get it in 1.1.1 though.
Some change must have fixed this problem since then.

**Comment by rolandlo** [comment] 2022-10-21 20:02
This was fixed by #3947, I think. I will close the issue therefore.

**Closed by rolandlo** 2022-10-21 20:02 UTC
Labels: bug, confirmed, priority::medium
