### ISSUE TITLE
Holding second pen button (switching momentarily to hand tool) does not allow moving around page

### ISSUE THREAD

**Issue by michaelsjackson** [xournalpp/xournalpp#2717] opened 2021-01-28 00:18 UTC
Linux, Ubuntu 18.04, experienced this in older versions as well, in certain cases.  This bug seems to have an older age. Latest night build.

**Comment by michaelsjackson** [comment] 2021-01-28 00:26
Just found out, if I touch with the pen the graphics tablet then it is working, but normally, also in original Xournal (without ++) this is working also when the pen is in the air, meaning without touching the tablet.  But at least there is a solution for now, better than nothing.  Thanks friends.

**Comment by Mittagskogel** [comment] 2021-04-07 12:10
I have the same issue. In the stable 1.0.20-hotfix release (Commit adaa97ff), this still works correctly: Pressing the pen button while hovering is enough to execute the corresponding action. I use this with the select region and eraser tools. I just compiled Xournal++ (newest commit) for my Raspberry Pi, and now I need to touch the pen to the tablet in combination with pressing the corresponding button in order to use the function (Select region, Eraser, and Hand tool). Perhaps this problem appeared with the new input system. I use the old input system in the 1.0.20-hotfix release.

**Comment by Mittagskogel** [comment] 2021-04-07 12:21
As a note, I can't use the older 1.0.20-hotfix release on my raspi because of the disappearing page bug (https://github.com/xournalpp/xournalpp/issues/2875)

**Comment by rolandlo** [comment] 2021-04-07 12:37
You should enable the `Merge button events with stylus button settings` checkbox in menu `Edit -> Preferences` (input system panel)

**Comment by Mittagskogel** [comment] 2021-04-07 13:56
Awesome, that works, thank you! Apparently I had not tried that in the newest version, even though I thought I had.
As a side note: `xsetwacom get 6 TabletPCButton` returns `off` for me, which is probably why I didn't enable the checkbox in the first place.

**Comment by Mittagskogel** [comment] 2021-04-08 06:43
Sorry, I did find more issues with this. In commit e5cdd5f2, everything works correctly; I can hover select and hover erase. In the latest commit, hover erase mostly works (although it seems like I need to hold the pen *extra* close to the tablet). Hover select does not work.
I'm happy using the older build, but let me know if there is anything I can do to help!

**Comment by rolandlo** [comment] 2021-04-08 07:41
@Mittagskogel 
In case you manage to build from source (as described in [the wiki](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md)) you could check if commit ea92dc7340c76237213b0e0fdc521647a5bfaf2f has introduced a regression with respect to the `Merge button events with stylus button settings` mode.

**Comment by Mittagskogel** [comment] 2021-04-08 10:38
Yes, I can confirm that commit ea92dc7 introduced the regression. The parent cc9b32f works fine.

**Comment by rolandlo** [comment] 2021-04-08 10:51
@Mittagskogel Thanks for testing.
@redweasel @Febbe What's your take on that?

**Comment by redweasel** [comment] 2021-04-09 07:39
I mentioned this in https://github.com/xournalpp/xournalpp/pull/2984 and I think my suspicion was correct then. I would fix this by making the zero pressure detection only abort the action if it is using a drawing tool with pressure sensitivity. I think I completely missed that there. (To my defense, I was asking for testing in the PR)

**Comment by redweasel** [comment] 2021-04-09 12:32
Ok now I am really confused... It seemed very likely that my commit was the culprit, but reverting my commit didn't fix the issue... Maybe I am testing wrong?

Here is what I did:
1. `xsetwacom set <stylus> TabletPCButton off`
2. Preferences: Enable drawing outside: on, Merge button events: off, Pressure Sensitivity: on (no inference)
3. Preferences: set stylus button 2 to use the hand tool
4. restart xournalpp (essential step!)
5. click stylus button 2 in hover and try to move

If merge button event was on in that session (without restart) then the hover grab works in my case, but if started with merge events off, it doesn't work.

Actually even adaa97f which is really old, shows the same behavior if you use the new input system and no merge button events. I you use the old input system and no merge button events, hover grab works though.

I start to feel like this is a long standing bug or is it intended behavior and I am just going mad? At this point can someone explain exactly what the intended behavior is for all the options in the input system. Actually, don't explain it here, make a design document, pin it and link it, so everyone knows what the correct behavior is, cause I don't know and I bet there are more people who don't know. The setting "Merge button events with stylus tip events" does not really tell me what it is supposed to be doing in practice.

**Comment by Mittagskogel** [comment] 2021-04-09 13:40
"The setting "Merge button events with stylus tip events" does not really tell me what it is supposed to be doing in practice." Totally agree with that. A tooltip would help :)

One discrepancy I see is that I never did step 1. `xsetwacom set <stylus> TabletPCButton off`. I didn't realize that was a settable property, and I don't know what it does. Everything else seems to be the same for me. I've been working with cc9b32f0 for a few hours now, and it seems to be working fine. There is one other annoying bug involving lines being drawn when they shouldn't, but hopefully that is unrelated and has no place in this thread.

Another thing to note: I am not using the new input system in my adaa97f build.
Keep in mind I've been testing all this on my raspberry pi (armv6), so let me know if you'd like me to test it on x86-64 as well.

**Comment by rolandlo** [comment] 2021-04-13 06:00
@redweasel 
In my case enabling `Merge button events with stylus tip events` is seriously broken. I activate the highlighter with one stylus button. When the `Merge button events with stylus tip events` mode (which is explained in #940) is activated I would expect highlighting to work when pressing the button even if the tip does not touch the screen. It works when I revert your commit. With your commit I just get a dot when I press the button. There is a similar (long-standing) issue on Windows. 
When reverting your commit (or checking out a previous commit) I observe another issue with highlighting though. Touching the screen will terminate the highlighting even if the button is still pressed. 

The problem is that with different styluses/different system settings and different OS'es we get different event sequences reported while physically doing the same. It would make sense to list all those event sequences (with annotations about the physical interactions) tagged with the OS, the OS stylus settings and the relevant Xournal++ settings. That would make it much easier to improve the `StylusHandler` code without creating regressions.

**Comment by redweasel** [comment] 2021-04-15 13:30
@rolandlo So what we would need is an available build of xournalpp with some instructions to collect the data of a few strokes with all the buttons. Then collect all that data in a new task. (Maybe we can get there without this step though)

I would like to write the perfect stylus handler, which solves all issues once and for all (*really annoyed by now...*). I will open a task for a new stylus interaction design going into detail about every possible interaction possibility.

**Comment by rolandlo** [comment] 2021-04-30 13:06
> Also @rolandlo can you link the long standing issue on windows here? I would be curious to see the input sequences there.
Windows issues: #2628, #2894, #2316

**Comment by Technius** [comment] 2021-06-24 06:54
Closing since #2984 was reverted in #3178.

**Closed by Technius** 2021-06-24 06:54 UTC
Labels: bug, regression
