### ISSUE TITLE
Add Cube

### ISSUE THREAD

**Issue by masac** [xournalpp/xournalpp#1708] opened 2020-01-18 15:16 UTC
Is it possible to add a cube in Xournal ++?

![Captură de ecran la 2020-01-18 17-05-30](https://user-images.githubusercontent.com/5394850/72666157-299cf600-3a18-11ea-8880-475e39ca6141.png)

**Comment by Technius** [comment] 2020-01-20 00:07
There's currently no built-in way to create shapes, but you can create an SVG file with something like Inkscape and then insert it as an image in X++.

Closing this issue as a duplicate of #1652.

**Closed by Technius** 2020-01-20 00:07 UTC
Labels: enhancement
